-- ═══════════════════════════════════════════════════════════════════════
-- Rainford High School — the school's REAL KS3 scheme of work, 2025-26.
--
-- ⚠️ GENERATED FILE — DO NOT EDIT BY HAND.
--    Regenerate with:  python3 rainford_ks3_sow.py
--    Source of truth:  rainford_ks3_sow.py (ENTRIES + MAPPING), transcribed
--                      from 'Ks3 SOW 25-26 (NEW).xlsx'
--    Written to:       supabase/seeds/20260907003000_rainford_ks3_overrides.sql
--    Target table:     public.scheme_of_work_overrides (PER-SCHOOL, KS3 only)
--    Human report:     docs/ks4/rainford-ks3-sow-mapping.md
--
-- ⚠️ SEED DATA AND REFERENCE EVIDENCE. **Never the platform default, never a
--    template.** The platform default is the 185 rows in
--    scheme_of_work_entries, generated by ks3_seed_sow.py from ks3_data/.
--    Mide's ruling of 2026-07-26: "Rainford's SOW is reference evidence, never
--    a template — the platform must be school-agnostic."
--
-- ⚠️ THIS FILE COLLIDES WITH supabase/seeds/20260726182000_ks3_school_schemes.sql
--    Both claim exclusive ownership of Rainford's KS3 override rows and both
--    open with the same scoped DELETE. Whichever is applied last wins, silently.
--    They are two answers at two resolutions — the old one places all 185
--    platform lessons from MRB-103's unit→year map; this one places Rainford's
--    own 162 taught lessons in Rainford's own order and is honest about the 34
--    the platform cannot cover. **Apply exactly one.** OPEN ON MIDE.
--
-- Idempotent: every KS3 override row for THIS SCHOOL is deleted and rewritten,
-- inside one transaction. No other school's rows, and no KS4 row, is touched.
-- Re-running is safe and is the intended way to apply a change.
--
-- academic_week is a per-(year, subject) teaching ORDER 1..n, not a calendar
-- week — the platform's own convention (ks3_seed_sow.py; backend
-- consumer/work.js). Rainford teaches two content lessons in most weeks, so
-- "1a" and "1b" become order 1 and 2. The calendar week itself has no column;
-- it is preserved verbatim in notes and is not queryable. See the generator
-- docstring, Finding 1.
--
-- The Skills track (Teacher B) writes NO rows — it runs in parallel with the
-- content track and has nowhere to sit under the (school, year, subject, week)
-- unique key. All 82 of its entries are mapped in the generator regardless.
-- See Finding 2.
--
-- Requires migrations 20260501212106_schools_layer.sql and
-- 20260727081530_ks3_scheme_of_work_overrides.sql.
--
-- Row counts, generated:
--
--   Y7  Biology 24 (23 mapped, 1 gap)  ·  Chemistry 22 (21 mapped, 1 gap)  ·  Physics 24 (19 mapped, 5 gap)
--   Y8  Biology 24 (16 mapped, 8 gap)  ·  Chemistry 22 (22 mapped, 0 gap)  ·  Physics 24 (22 mapped, 2 gap)
--   Y9  Biology 8 (3 mapped, 5 gap)  ·  Chemistry 8 (2 mapped, 6 gap)  ·  Physics 6 (0 mapped, 6 gap)
--
--   162 rows · 128 carry a lesson slug · 34 are Rainford lessons the
--   platform has no lesson for (subtopic null, reason in notes)
--   max academic_week 24 (KS3 ceiling 39)
--
-- ═══════════════════════════════════════════════════════════════════════

begin;

-- Preconditions. Failing here with a sentence beats failing later on a NOT NULL
-- violation against a subselect that quietly returned NULL.
do $$
begin
  if (select count(*) from public.subjects
       where name in ('Biology', 'Chemistry', 'Physics')) <> 3 then
    raise exception 'Rainford KS3 seed: public.subjects is missing one of '
                    'Biology / Chemistry / Physics. Seed subjects first.';
  end if;
  if (select count(*) from public.schools where name = 'Rainford High School') <> 1 then
    raise exception 'Rainford KS3 seed: expected exactly one school named %, '
                    'found %. The seed looks the school up by name because '
                    'ids differ between test and production.',
                    'Rainford High School',
                    (select count(*) from public.schools where name = 'Rainford High School');
  end if;
end $$;

-- Idempotency: this file owns every KS3 override row for this school. Scoped to
-- school_id AND key_stage so no other school and no KS4 row can be caught by it.
delete from public.scheme_of_work_overrides
 where key_stage = 'KS3'
   and school_id = (select id from public.schools where name = 'Rainford High School');

-- ── Year 7 · Biology — 24 lessons, 23 mapped, 1 gap ──
insert into public.scheme_of_work_overrides
  (school_id, key_stage, year_group, tier, pathway, subject_id, academic_week, topic, subtopic, notes)
values
  -- Bio 1- Cells & Organisation
  -- 1a   Microscopes
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 1, 'Bio 1- Cells & Organisation', 'using-a-microscope', 'Rainford Y7 week 1a · Bio 1- Cells & Organisation · platform B1 Using a microscope'),
  -- 1b   Animal cells
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 2, 'Bio 1- Cells & Organisation', 'animal-and-plant-cells', 'Rainford Y7 week 1b · Bio 1- Cells & Organisation · platform B1 Animal and plant cells · SPLIT 2→1: Rainford teaches animal and plant cells over two lessons; the platform draws them as one (`animal-and-plant-cells`). 2a carries the same slug.'),
  -- 2a   Plant cells
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 3, 'Bio 1- Cells & Organisation', 'animal-and-plant-cells', 'Rainford Y7 week 2a · Bio 1- Cells & Organisation · platform B1 Animal and plant cells · SPLIT 2→1: the second half of `animal-and-plant-cells`. See 1b.'),
  -- 2b   Specialised cells
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 4, 'Bio 1- Cells & Organisation', 'specialised-cells', 'Rainford Y7 week 2b · Bio 1- Cells & Organisation · platform B1 Specialised cells'),
  -- 3a   Diffusion in cells
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 5, 'Bio 1- Cells & Organisation', 'diffusion', 'Rainford Y7 week 3a · Bio 1- Cells & Organisation · platform C1 Diffusion · ⚠ cross-discipline: taught as Biology here, drawn in a Chemistry unit · CROSS-DISCIPLINE: Rainford teaches diffusion inside Bio 1, so this row is BIOLOGY; the platform''s only `diffusion` lesson belongs to C1 (Chemistry). Decision B — the banner decides the subject.'),
  -- 3b   Organisation in organisms
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 6, 'Bio 1- Cells & Organisation', 'levels-of-organisation', 'Rainford Y7 week 3b · Bio 1- Cells & Organisation · platform B1 Levels of organisation'),
  -- 4a   Skeletal system
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 7, 'Bio 1- Cells & Organisation', 'what-the-skeleton-does', 'Rainford Y7 week 4a · Bio 1- Cells & Organisation · platform B2 What the skeleton does'),
  -- 4b   Muscles & KO quiz
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 8, 'Bio 1- Cells & Organisation', 'antagonistic-muscle-pairs', 'Rainford Y7 week 4b · Bio 1- Cells & Organisation · platform B2 Antagonistic muscle pairs'),
  -- Bio 2- Diet & Digestion
  -- 13a  Balanced diet
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 9, 'Bio 2- Diet & Digestion', 'a-balanced-diet', 'Rainford Y7 week 13a · Bio 2- Diet & Digestion · platform B3 A balanced diet'),
  -- 13b  Food tests: Carbohydrates
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 10, 'Bio 2- Diet & Digestion', 'food-tests', 'Rainford Y7 week 13b · Bio 2- Diet & Digestion · platform B3 Food tests · SPLIT 2→1: Rainford splits the food tests over carbohydrates then protein & fat; the platform draws one `food-tests` lesson. 14a carries the same slug.'),
  -- 14a  Food tests: Protein & fat
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 11, 'Bio 2- Diet & Digestion', 'food-tests', 'Rainford Y7 week 14a · Bio 2- Diet & Digestion · platform B3 Food tests · SPLIT 2→1: the second half of `food-tests`. See 13b.'),
  -- 14b  Energy in food
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 12, 'Bio 2- Diet & Digestion', 'energy-in-food-and-what-you-need', 'Rainford Y7 week 14b · Bio 2- Diet & Digestion · platform B3 Energy in food and what you need'),
  -- 15a  Digestive system
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 13, 'Bio 2- Diet & Digestion', 'the-digestive-system', 'Rainford Y7 week 15a · Bio 2- Diet & Digestion · platform B3 The digestive system'),
  -- 15b  Absorption
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 14, 'Bio 2- Diet & Digestion', 'absorption-and-the-small-intestine', 'Rainford Y7 week 15b · Bio 2- Diet & Digestion · platform B3 Absorption and the small intestine'),
  -- 16a  Enzymes
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 15, 'Bio 2- Diet & Digestion', 'enzymes-in-digestion', 'Rainford Y7 week 16a · Bio 2- Diet & Digestion · platform B3 Enzymes in digestion'),
  -- 16b  Malnutrition & KO quiz
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 16, 'Bio 2- Diet & Digestion', 'when-diet-goes-wrong', 'Rainford Y7 week 16b · Bio 2- Diet & Digestion · platform B3 When diet goes wrong'),
  -- Bio 3- Reproduction
  -- 25a  KO review& Male & female reproductive organs
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 17, 'Bio 3- Reproduction', 'human-reproductive-systems', 'Rainford Y7 week 25a · Bio 3- Reproduction · platform B5 Human reproductive systems'),
  -- 25b  Fertilisation
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 18, 'Bio 3- Reproduction', 'gametes-and-fertilisation', 'Rainford Y7 week 25b · Bio 3- Reproduction · platform B5 Gametes and fertilisation'),
  -- 26a  Puberty   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 19, 'Bio 3- Reproduction', null, 'Rainford Y7 week 26a · Bio 3- Reproduction · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. The platform''s B5 has no puberty lesson. `human-reproductive-systems` mentions puberty only in passing (''sperm are made continuously from puberty onwards'') and 25a already carries it.'),
  -- 26b  Menstrual cycle
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 20, 'Bio 3- Reproduction', 'the-menstrual-cycle', 'Rainford Y7 week 26b · Bio 3- Reproduction · platform B5 The menstrual cycle'),
  -- 27a  Pregnancy
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 21, 'Bio 3- Reproduction', 'gestation-placenta-and-birth', 'Rainford Y7 week 27a · Bio 3- Reproduction · platform B5 Gestation, the placenta and birth'),
  -- 27b  Birth
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 22, 'Bio 3- Reproduction', 'gestation-placenta-and-birth', 'Rainford Y7 week 27b · Bio 3- Reproduction · platform B5 Gestation, the placenta and birth · SPLIT 2→1: the platform''s `gestation-placenta-and-birth` covers pregnancy and birth together. 27a carries the same slug.'),
  -- 28a  Flower structure
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 23, 'Bio 3- Reproduction', 'flowers-and-pollination', 'Rainford Y7 week 28a · Bio 3- Reproduction · platform B5 Flowers and pollination'),
  -- 28b  Pollination & KO quiz
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Biology'), 24, 'Bio 3- Reproduction', 'fertilisation-seeds-and-fruit', 'Rainford Y7 week 28b · Bio 3- Reproduction · platform B5 Fertilisation, seeds and fruit · Mapped to `fertilisation-seeds-and-fruit` on the outcome ''explain how fertilisation occurs in plants''. Note the platform draws pollination itself inside `flowers-and-pollination`, which 28a carries — so the split between 28a and 28b does not line up with the platform''s.');

-- ── Year 7 · Chemistry — 22 lessons, 21 mapped, 1 gap ──
insert into public.scheme_of_work_overrides
  (school_id, key_stage, year_group, tier, pathway, subject_id, academic_week, topic, subtopic, notes)
values
  -- Chem 1- States of matter
  -- 5a   Solids, liquids and gases
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 1, 'Chem 1- States of matter', 'solids-liquids-and-gases', 'Rainford Y7 week 5a · Chem 1- States of matter · platform C1 Solids, liquids and gases'),
  -- 5b   Changing states
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 2, 'Chem 1- States of matter', 'changes-of-state', 'Rainford Y7 week 5b · Chem 1- States of matter · platform C1 Changes of state'),
  -- 6a   Gas Pressure
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 3, 'Chem 1- States of matter', 'gas-pressure', 'Rainford Y7 week 6a · Chem 1- States of matter · platform C1 Gas pressure'),
  -- 6b   Pure mixtures and solutions
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 4, 'Chem 1- States of matter', 'pure-or-mixture', 'Rainford Y7 week 6b · Chem 1- States of matter · platform C3 Pure or mixture? · MERGE 1→2: covers `pure-or-mixture` and `dissolving-and-solutions`. Mapped to the first; `dissolving-and-solutions` is co-covered here.'),
  -- 7a   Filtration
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 5, 'Chem 1- States of matter', 'filtration', 'Rainford Y7 week 7a · Chem 1- States of matter · platform C3 Filtration'),
  -- 7b   Evaporation
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 6, 'Chem 1- States of matter', 'evaporation-and-crystallisation', 'Rainford Y7 week 7b · Chem 1- States of matter · platform C3 Evaporation and crystallisation'),
  -- 8a   Distillation
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 7, 'Chem 1- States of matter', 'distillation', 'Rainford Y7 week 8a · Chem 1- States of matter · platform C3 Distillation'),
  -- 8b   Chromatography & KO quiz
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 8, 'Chem 1- States of matter', 'chromatography', 'Rainford Y7 week 8b · Chem 1- States of matter · platform C3 Chromatography'),
  -- Chem 2- Chemical reactions
  -- 17a  Writing word equations
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 9, 'Chem 2- Chemical reactions', 'word-equations', 'Rainford Y7 week 17a · Chem 2- Chemical reactions · platform C4 Word equations'),
  -- 17b  Chemical vs physical changes
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 10, 'Chem 2- Chemical reactions', 'chemical-vs-physical-change', 'Rainford Y7 week 17b · Chem 2- Chemical reactions · platform C4 Chemical change vs physical change'),
  -- 18a  Exo & Endothemric reactions
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 11, 'Chem 2- Chemical reactions', 'exothermic-reactions', 'Rainford Y7 week 18a · Chem 2- Chemical reactions · platform C7 Exothermic reactions · MERGE 1→2: the platform draws `exothermic-reactions` and `endothermic-reactions` as two lessons; Rainford teaches both in one. Mapped to the exothermic half; `endothermic-reactions` is co-covered here and is placed nowhere else in Rainford''s scheme.'),
  -- 18b  Combustion
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 12, 'Chem 2- Chemical reactions', 'combustion', 'Rainford Y7 week 18b · Chem 2- Chemical reactions · platform C5 Combustion'),
  -- 19a  Incomplete combustion
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 13, 'Chem 2- Chemical reactions', 'combustion', 'Rainford Y7 week 19a · Chem 2- Chemical reactions · platform C5 Combustion · SPLIT 2→1: the platform''s `combustion` covers complete AND incomplete combustion in one lesson. 18b carries the same slug.'),
  -- 19b  Oxidation
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 14, 'Chem 2- Chemical reactions', 'oxidation', 'Rainford Y7 week 19b · Chem 2- Chemical reactions · platform C5 Oxidation'),
  -- 20a  Thermal decompositon
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 15, 'Chem 2- Chemical reactions', 'thermal-decomposition', 'Rainford Y7 week 20a · Chem 2- Chemical reactions · platform C5 Thermal decomposition'),
  -- 20b  Testing for gases & KO quiz   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 16, 'Chem 2- Chemical reactions', null, 'Rainford Y7 week 20b · Chem 2- Chemical reactions · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. The platform has no gas-tests lesson. The individual tests are embedded elsewhere — limewater in C5 `thermal-decomposition`, the squeaky pop in C6 `acid-plus-metal` — so no single lesson is the right pointer.'),
  -- Chem 3- Materials
  -- 29a  Metals and acid
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 17, 'Chem 3- Materials', 'acid-plus-metal', 'Rainford Y7 week 29a · Chem 3- Materials · platform C6 Acid + metal'),
  -- 29b  Reactivity series
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 18, 'Chem 3- Materials', 'the-reactivity-series', 'Rainford Y7 week 29b · Chem 3- Materials · platform C9 The reactivity series'),
  -- 30a  Displacement reactions
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 19, 'Chem 3- Materials', 'displacement', 'Rainford Y7 week 30a · Chem 3- Materials · platform C5 Displacement · Mapped to C5 `displacement` (observing whether displacement happened). The platform also has C9 `predicting-displacement` (predicting from the series), which Rainford places nowhere — 29b Reactivity series is the nearest thing.'),
  -- 30b  Carbon in the reactivity series
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 20, 'Chem 3- Materials', 'getting-metals-out-of-rocks', 'Rainford Y7 week 30b · Chem 3- Materials · platform C9 Getting metals out of rocks'),
  -- 31a  Metals and recyling
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 21, 'Chem 3- Materials', 'a-planet-with-limits', 'Rainford Y7 week 31a · Chem 3- Materials · platform C10 A planet with limits: resources and recycling · Mapped to `a-planet-with-limits`, the platform''s finite-resources and recycling lesson.'),
  -- 31b  Properties of Ceramics, Composites & Polymers & KO quiz
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Chemistry'), 22, 'Chem 3- Materials', 'ceramics-polymers-and-composites', 'Rainford Y7 week 31b · Chem 3- Materials · platform C9 Ceramics, polymers and composites');

-- ── Year 7 · Physics — 24 lessons, 19 mapped, 5 gap ──
insert into public.scheme_of_work_overrides
  (school_id, key_stage, year_group, tier, pathway, subject_id, academic_week, topic, subtopic, notes)
values
  -- Phys 1- Forces & Motion
  -- 9a   Forces
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 1, 'Phys 1- Forces & Motion', 'what-a-force-is', 'Rainford Y7 week 9a · Phys 1- Forces & Motion · platform P4 What a force is'),
  -- 9b   Mass & weight
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 2, 'Phys 1- Forces & Motion', 'mass-vs-weight', 'Rainford Y7 week 9b · Phys 1- Forces & Motion · platform P12 Mass vs weight · Title-matched to `mass-vs-weight`. The outcome ''calculate weight as mass x gravity'' is also `gravity-and-weight`, which Rainford places nowhere in Year 7.'),
  -- 10a  Balancing forces
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 3, 'Phys 1- Forces & Motion', 'drawing-and-adding-forces', 'Rainford Y7 week 10a · Phys 1- Forces & Motion · platform P4 Drawing and adding forces'),
  -- 10b  Friction
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 4, 'Phys 1- Forces & Motion', 'friction', 'Rainford Y7 week 10b · Phys 1- Forces & Motion · platform P4 Friction'),
  -- 11a  Speed
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 5, 'Phys 1- Forces & Motion', 'speed', 'Rainford Y7 week 11a · Phys 1- Forces & Motion · platform P3 Speed'),
  -- 11b  Distance-time graphs
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 6, 'Phys 1- Forces & Motion', 'distance-time-graphs', 'Rainford Y7 week 11b · Phys 1- Forces & Motion · platform P3 Distance–time graphs'),
  -- 12a  Simple machines & moments
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 7, 'Phys 1- Forces & Motion', 'simple-machines', 'Rainford Y7 week 12a · Phys 1- Forces & Motion · platform P1 Simple machines · Mapped to `simple-machines`. Rainford also lands Y8 10a ''Work done'' on this lesson — different year, so no key collision, but the same platform lesson is taught twice.'),
  -- 12b  More moments & KO quiz
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 8, 'Phys 1- Forces & Motion', 'moments', 'Rainford Y7 week 12b · Phys 1- Forces & Motion · platform P4 Moments: the turning effect'),
  -- Phys 2- Electricity & Magnetism
  -- 21a  KO review & Circuit symbols
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 9, 'Phys 2- Electricity & Magnetism', 'current-and-circuits', 'Rainford Y7 week 21a · Phys 2- Electricity & Magnetism · platform P8 Current and circuits · Circuit symbols are taught inside the platform''s `current-and-circuits` (verified: they appear in that lesson''s question set and nowhere else).'),
  -- 21b  Potential difference and current
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 10, 'Phys 2- Electricity & Magnetism', 'potential-difference', 'Rainford Y7 week 21b · Phys 2- Electricity & Magnetism · platform P8 Potential difference · MERGE 1→2: covers `potential-difference` and `current-and-circuits`. Mapped to potential difference; 21a carries current-and-circuits.'),
  -- 22a  Series circuits
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 11, 'Phys 2- Electricity & Magnetism', 'series-and-parallel', 'Rainford Y7 week 22a · Phys 2- Electricity & Magnetism · platform P8 Series and parallel'),
  -- 22b  Parallel circuits
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 12, 'Phys 2- Electricity & Magnetism', 'series-and-parallel', 'Rainford Y7 week 22b · Phys 2- Electricity & Magnetism · platform P8 Series and parallel · SPLIT 2→1: the platform draws `series-and-parallel` as one lesson. 22a carries the same slug.'),
  -- 23a  Resistance
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 13, 'Phys 2- Electricity & Magnetism', 'resistance', 'Rainford Y7 week 23a · Phys 2- Electricity & Magnetism · platform P8 Resistance'),
  -- 23b  Static electricity
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 14, 'Phys 2- Electricity & Magnetism', 'charging-by-rubbing', 'Rainford Y7 week 23b · Phys 2- Electricity & Magnetism · platform P9 Charging by rubbing'),
  -- 24a  Conductors & insulators
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 15, 'Phys 2- Electricity & Magnetism', 'conductors-and-insulators', 'Rainford Y7 week 24a · Phys 2- Electricity & Magnetism · platform P8 Conductors and insulators'),
  -- 24b  Magnets & magnetic fields & KO quiz
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 16, 'Phys 2- Electricity & Magnetism', 'magnetic-fields', 'Rainford Y7 week 24b · Phys 2- Electricity & Magnetism · platform P10 Magnetic fields · MERGE 1→3: field lines (`magnetic-fields`), how magnets interact (`magnets-and-poles`) and how a compass works (`the-earth-is-a-magnet`) in one lesson. Mapped to `magnetic-fields`; the other two are co-covered here and placed nowhere else.'),
  -- Phys 3- Space
  -- 32a  Our Solar System   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 17, 'Phys 3- Space', null, 'Rainford Y7 week 32a · Phys 3- Space · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. The platform has no lesson naming or comparing the planets. `the-sun-stars-and-galaxies` DEFINES what a solar system is, as one rung of a star→solar-system→galaxy→universe ladder, but it is not a planets lesson — and 32b already carries it.'),
  -- 32b  The wider universe
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 18, 'Phys 3- Space', 'the-sun-stars-and-galaxies', 'Rainford Y7 week 32b · Phys 3- Space · platform P12 The Sun, stars and galaxies'),
  -- 33a  Gravity in space
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 19, 'Phys 3- Space', 'gravity-earth-moon-and-sun', 'Rainford Y7 week 33a · Phys 3- Space · platform P12 Gravity between Earth, Moon and Sun'),
  -- 33b  Earth and the Seasons
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 20, 'Phys 3- Space', 'seasons-and-the-tilt', 'Rainford Y7 week 33b · Phys 3- Space · platform P12 Seasons and the tilt'),
  -- 34a  The moon and eclipses   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 21, 'Phys 3- Space', null, 'Rainford Y7 week 34a · Phys 3- Space · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. No platform lesson on moon phases or eclipses. P12 `gravity-earth-moon-and-sun` is about gravity, not about what we see.'),
  -- 34b  The origins and fate of the universe   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 22, 'Phys 3- Space', null, 'Rainford Y7 week 34b · Phys 3- Space · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. The platform has no big-bang lesson at KS3 (searched: the phrase appears nowhere in ks3_data).'),
  -- 35a  Alien life debate   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 23, 'Phys 3- Space', null, 'Rainford Y7 week 35a · Phys 3- Space · UNMAPPED (enrichment): an enrichment or debate lesson with no platform equivalent · UNMAPPED. A debate lesson; no platform equivalent, and none wanted.'),
  -- 35b  Moon landing debate   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 7, null, null, (select id from public.subjects where name = 'Physics'), 24, 'Phys 3- Space', null, 'Rainford Y7 week 35b · Phys 3- Space · UNMAPPED (enrichment): an enrichment or debate lesson with no platform equivalent · UNMAPPED. A debate lesson; no platform equivalent, and none wanted.');

-- ── Year 8 · Biology — 24 lessons, 16 mapped, 8 gap ──
insert into public.scheme_of_work_overrides
  (school_id, key_stage, year_group, tier, pathway, subject_id, academic_week, topic, subtopic, notes)
values
  -- Bio 4- Bioenergetics
  -- 1a   Photosynthesis
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 1, 'Bio 4- Bioenergetics', 'the-photosynthesis-reaction', 'Rainford Y8 week 1a · Bio 4- Bioenergetics · platform B7 The photosynthesis reaction'),
  -- 1b   Respiratory system
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 2, 'Bio 4- Bioenergetics', 'the-gas-exchange-system', 'Rainford Y8 week 1b · Bio 4- Bioenergetics · platform B4 The gas exchange system'),
  -- 2a   Breathing & gas exchange
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 3, 'Bio 4- Bioenergetics', 'how-breathing-works', 'Rainford Y8 week 2a · Bio 4- Bioenergetics · platform B4 How breathing works'),
  -- 2b   Aerobic respiration
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 4, 'Bio 4- Bioenergetics', 'aerobic-respiration', 'Rainford Y8 week 2b · Bio 4- Bioenergetics · platform B8 Aerobic respiration'),
  -- 3a   Anaerobic respiration
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 5, 'Bio 4- Bioenergetics', 'anaerobic-respiration-in-humans', 'Rainford Y8 week 3a · Bio 4- Bioenergetics · platform B8 Anaerobic respiration in humans'),
  -- 3b   Fermentation
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 6, 'Bio 4- Bioenergetics', 'fermentation', 'Rainford Y8 week 3b · Bio 4- Bioenergetics · platform B8 Fermentation and what we use it for'),
  -- 4a   The Circulatory system   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 7, 'Bio 4- Bioenergetics', null, 'Rainford Y8 week 4a · Bio 4- Bioenergetics · UNMAPPED (beyond-ks3): beyond the statutory KS3 programme of study — ks3_data/school_schemes.py already records it as beyond_statutory for this school · UNMAPPED, and expected: ks3_data/school_schemes.py already records ''circulation'' for this school as beyond_statutory — ''KS4 content; not in the 2014 KS3 programme of study''. The platform correctly has no KS3 circulation lesson.'),
  -- 4b   Blood & Vessels & KO quiz   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 8, 'Bio 4- Bioenergetics', null, 'Rainford Y8 week 4b · Bio 4- Bioenergetics · UNMAPPED (beyond-ks3): beyond the statutory KS3 programme of study — ks3_data/school_schemes.py already records it as beyond_statutory for this school · UNMAPPED, same reason as 4a: circulation is beyond statutory KS3.'),
  -- Bio 5- Genetics & Evolution
  -- 13a  Variation
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 9, 'Bio 5- Genetics & Evolution', 'variation-continuous-and-discontinuous', 'Rainford Y8 week 13a · Bio 5- Genetics & Evolution · platform B10 Variation: continuous and discontinuous'),
  -- 13b  DNA
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 10, 'Bio 5- Genetics & Evolution', 'chromosomes-genes-and-dna', 'Rainford Y8 week 13b · Bio 5- Genetics & Evolution · platform B10 Chromosomes, genes and DNA'),
  -- 14a  Development of the DNA Model
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 11, 'Bio 5- Genetics & Evolution', 'how-we-worked-out-dna', 'Rainford Y8 week 14a · Bio 5- Genetics & Evolution · platform B10 How we worked out DNA''s structure'),
  -- 14b  Genetic crosses
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 12, 'Bio 5- Genetics & Evolution', 'passing-it-on-heredity', 'Rainford Y8 week 14b · Bio 5- Genetics & Evolution · platform B10 Passing it on: heredity'),
  -- 15a  Evolution
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 13, 'Bio 5- Genetics & Evolution', 'natural-selection', 'Rainford Y8 week 15a · Bio 5- Genetics & Evolution · platform B11 Natural selection'),
  -- 15b  Speciation
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 14, 'Bio 5- Genetics & Evolution', 'what-makes-a-species', 'Rainford Y8 week 15b · Bio 5- Genetics & Evolution · platform B10 What makes a species'),
  -- 16a  Extinction
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 15, 'Bio 5- Genetics & Evolution', 'when-the-environment-changes-extinction', 'Rainford Y8 week 16a · Bio 5- Genetics & Evolution · platform B11 When the environment changes: extinction'),
  -- 16b  Selective breeding   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 16, 'Bio 5- Genetics & Evolution', null, 'Rainford Y8 week 16b · Bio 5- Genetics & Evolution · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. The platform''s B10/B11 have no selective-breeding lesson (searched: the phrase appears nowhere in ks3_data).'),
  -- Bio 6- Ecosystems
  -- 25a  Food chains & webs
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 17, 'Bio 6- Ecosystems', 'food-chains-and-food-webs', 'Rainford Y8 week 25a · Bio 6- Ecosystems · platform B9 Food chains and food webs'),
  -- 25b  Pyramids of number   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 18, 'Bio 6- Ecosystems', null, 'Rainford Y8 week 25b · Bio 6- Ecosystems · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. The platform''s B9 has no pyramids lesson of either kind (searched: ''pyramid'' appears nowhere in ks3_data).'),
  -- 26a  Pyramids of biomass   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 19, 'Bio 6- Ecosystems', null, 'Rainford Y8 week 26a · Bio 6- Ecosystems · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED, same reason as 25b.'),
  -- 26b  Animal adaptation   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 20, 'Bio 6- Ecosystems', null, 'Rainford Y8 week 26b · Bio 6- Ecosystems · UNMAPPED (ambiguous): could be either of two platform lessons and neither is clearly right — left unmapped rather than guessed · UNMAPPED — AMBIGUOUS, and this one is a close call. The platform''s nearest lesson is B11 `variation-and-competitive-success`, which does use the language of being ''well adapted to a particular environment'' — but its subject is variation driving competitive success within a species, not how organisms are adapted to cold/hot/dry habitats. Rejected as a near-miss rather than mapped, so the gap stays visible.'),
  -- 27a  Plant adaptation   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 21, 'Bio 6- Ecosystems', null, 'Rainford Y8 week 27a · Bio 6- Ecosystems · UNMAPPED (ambiguous): could be either of two platform lessons and neither is clearly right — left unmapped rather than guessed · UNMAPPED — AMBIGUOUS, same near-miss as 26b and rejected for the same reason. `leaves-built-for-the-job` (B7) is adjacent but is about photosynthesis, not habitat.'),
  -- 27b  Biodiversity
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 22, 'Bio 6- Ecosystems', 'biodiversity-and-gene-banks', 'Rainford Y8 week 27b · Bio 6- Ecosystems · platform B11 Biodiversity and gene banks'),
  -- 28a  Random sampling
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 23, 'Bio 6- Ecosystems', 'sampling-an-ecosystem', 'Rainford Y8 week 28a · Bio 6- Ecosystems · platform B9 Sampling an ecosystem'),
  -- 28b  Transects   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Biology'), 24, 'Bio 6- Ecosystems', null, 'Rainford Y8 week 28b · Bio 6- Ecosystems · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. The platform''s `sampling-an-ecosystem` is quadrats only — random placement and sample size — and does not cover transects. 28a carries that lesson.');

-- ── Year 8 · Chemistry — 22 lessons, 22 mapped, 0 gap ──
insert into public.scheme_of_work_overrides
  (school_id, key_stage, year_group, tier, pathway, subject_id, academic_week, topic, subtopic, notes)
values
  -- Chem 4- Atoms, elements & compounds
  -- 5a   Atoms
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 1, 'Chem 4- Atoms, elements & compounds', 'the-atom-daltons-model', 'Rainford Y8 week 5a · Chem 4- Atoms, elements & compounds · platform C2 The atom: Dalton''s model · MERGE: also covers `chemical-symbols` (''identify elements from their symbols''), which Rainford places nowhere else.'),
  -- 5b   Elements & compounds
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 2, 'Chem 4- Atoms, elements & compounds', 'elements', 'Rainford Y8 week 5b · Chem 4- Atoms, elements & compounds · platform C2 Elements'),
  -- 6a   Compounds
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 3, 'Chem 4- Atoms, elements & compounds', 'compounds', 'Rainford Y8 week 6a · Chem 4- Atoms, elements & compounds · platform C2 Compounds'),
  -- 6b   Mixtures
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 4, 'Chem 4- Atoms, elements & compounds', 'pure-or-mixture', 'Rainford Y8 week 6b · Chem 4- Atoms, elements & compounds · platform C3 Pure or mixture?'),
  -- 7a   Metals and non-metals
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 5, 'Chem 4- Atoms, elements & compounds', 'metals-and-non-metals', 'Rainford Y8 week 7a · Chem 4- Atoms, elements & compounds · platform C8 Metals and non-metals · MERGE: the outcome ''chemical properties of metal and non-metal oxides with respect to acidity'' is the platform''s `metal-and-non-metal-oxides`, which 20b Acid rain also lands on.'),
  -- 7b   Group 1- Alkali metals
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 6, 'Chem 4- Atoms, elements & compounds', 'group-1-the-alkali-metals', 'Rainford Y8 week 7b · Chem 4- Atoms, elements & compounds · platform C8 Group 1 — the alkali metals'),
  -- 8a   Group 7- Halogens
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 7, 'Chem 4- Atoms, elements & compounds', 'group-7-the-halogens', 'Rainford Y8 week 8a · Chem 4- Atoms, elements & compounds · platform C8 Group 7 — the halogens'),
  -- 8b   Group 0- Noble Gases
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 8, 'Chem 4- Atoms, elements & compounds', 'group-0-and-why-groups-exist', 'Rainford Y8 week 8b · Chem 4- Atoms, elements & compounds · platform C8 Group 0 and why groups exist'),
  -- Chem 5- Acids & Alkalis
  -- 17a  Universal indicator and the pH scale
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 9, 'Chem 5- Acids & Alkalis', 'the-ph-scale-and-indicators', 'Rainford Y8 week 17a · Chem 5- Acids & Alkalis · platform C6 The pH scale and indicators'),
  -- 17b  Neutralisation
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 10, 'Chem 5- Acids & Alkalis', 'neutralisation', 'Rainford Y8 week 17b · Chem 5- Acids & Alkalis · platform C6 Neutralisation'),
  -- 18a  Acids and metals
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 11, 'Chem 5- Acids & Alkalis', 'acid-plus-metal', 'Rainford Y8 week 18a · Chem 5- Acids & Alkalis · platform C6 Acid + metal'),
  -- 18b  Acids and metal carbonates
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 12, 'Chem 5- Acids & Alkalis', 'acids-and-carbonates', 'Rainford Y8 week 18b · Chem 5- Acids & Alkalis · platform C6 Acids and carbonates'),
  -- 19a  Salts
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 13, 'Chem 5- Acids & Alkalis', 'making-a-pure-dry-salt', 'Rainford Y8 week 19a · Chem 5- Acids & Alkalis · platform C6 Making a pure dry salt'),
  -- 19b  Making a salt
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 14, 'Chem 5- Acids & Alkalis', 'making-a-pure-dry-salt', 'Rainford Y8 week 19b · Chem 5- Acids & Alkalis · platform C6 Making a pure dry salt · SPLIT 2→1: `making-a-pure-dry-salt` covers naming the salt and making it. 19a carries the same slug.'),
  -- 20a  Uses of acids and alkalis
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 15, 'Chem 5- Acids & Alkalis', 'acids-and-alkalis', 'Rainford Y8 week 20a · Chem 5- Acids & Alkalis · platform C6 Acids and alkalis'),
  -- 20b  Acid rain
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 16, 'Chem 5- Acids & Alkalis', 'metal-and-non-metal-oxides', 'Rainford Y8 week 20b · Chem 5- Acids & Alkalis · platform C8 Metal and non-metal oxides · Acid rain is taught substantively inside C8 `metal-and-non-metal-oxides` and nowhere else on the platform. Rainford teaches it in Chem 5, so the row is Chemistry either way.'),
  -- Chem 6- Earth & Atmosphere
  -- 29a  The Earth's structure
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 17, 'Chem 6- Earth & Atmosphere', 'inside-the-earth', 'Rainford Y8 week 29a · Chem 6- Earth & Atmosphere · platform C10 Inside the Earth'),
  -- 29b  Sedimentary
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 18, 'Chem 6- Earth & Atmosphere', 'three-ways-to-make-a-rock', 'Rainford Y8 week 29b · Chem 6- Earth & Atmosphere · platform C10 Three ways to make a rock'),
  -- 30a  Igneous & metamorphic
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 19, 'Chem 6- Earth & Atmosphere', 'three-ways-to-make-a-rock', 'Rainford Y8 week 30a · Chem 6- Earth & Atmosphere · platform C10 Three ways to make a rock · SPLIT 2→1: the platform''s `three-ways-to-make-a-rock` covers all three rock types in one lesson. 29b carries the same slug.'),
  -- 30b  Rock cycle
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 20, 'Chem 6- Earth & Atmosphere', 'the-rock-cycle', 'Rainford Y8 week 30b · Chem 6- Earth & Atmosphere · platform C10 The rock cycle'),
  -- 31a  Changes to the atmosphere
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 21, 'Chem 6- Earth & Atmosphere', 'whats-in-the-air', 'Rainford Y8 week 31a · Chem 6- Earth & Atmosphere · platform C10 What''s in the air'),
  -- 31b  Air pollution
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Chemistry'), 22, 'Chem 6- Earth & Atmosphere', 'carbon-dioxide-humans-and-climate', 'Rainford Y8 week 31b · Chem 6- Earth & Atmosphere · platform C10 Carbon dioxide, humans and climate · Mapped to `carbon-dioxide-humans-and-climate`. The platform''s `whats-in-the-air` is atmosphere composition and 31a carries it.');

-- ── Year 8 · Physics — 24 lessons, 22 mapped, 2 gap ──
insert into public.scheme_of_work_overrides
  (school_id, key_stage, year_group, tier, pathway, subject_id, academic_week, topic, subtopic, notes)
values
  -- Phys 4- Energy
  -- 9a   Energy stores
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 1, 'Phys 4- Energy', 'energy-stores', 'Rainford Y8 week 9a · Phys 4- Energy · platform P1 Energy stores'),
  -- 9b   Energy transfers
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 2, 'Phys 4- Energy', 'energy-transfers-before-and-after', 'Rainford Y8 week 9b · Phys 4- Energy · platform P1 Energy transfers: before and after'),
  -- 10a  Work done
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 3, 'Phys 4- Energy', 'simple-machines', 'Rainford Y8 week 10a · Phys 4- Energy · platform P1 Simple machines · The platform defines work done inside `simple-machines` (verified: it is a key term there and there is no standalone work-done lesson). Rainford also teaches simple machines at Y7 12a.'),
  -- 10b  Power
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 4, 'Phys 4- Energy', 'power-ratings-in-watts', 'Rainford Y8 week 10b · Phys 4- Energy · platform P2 Power ratings in watts'),
  -- 11a  Energy Costs
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 5, 'Phys 4- Energy', 'reading-a-fuel-bill', 'Rainford Y8 week 11a · Phys 4- Energy · platform P2 Reading a fuel bill'),
  -- 11b  KO Quiz/Energy efficiency
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 6, 'Phys 4- Energy', 'conservation-of-energy', 'Rainford Y8 week 11b · Phys 4- Energy · platform P1 Conservation of energy · The platform has no efficiency lesson; useful-vs-wasted energy, dissipation and efficiency are taught inside `conservation-of-energy`.'),
  -- 12a  Fossil fuels
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 7, 'Phys 4- Energy', 'fuels-and-energy-resources', 'Rainford Y8 week 12a · Phys 4- Energy · platform P2 Fuels and energy resources'),
  -- 12b  Renewable energy
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 8, 'Phys 4- Energy', 'fuels-and-energy-resources', 'Rainford Y8 week 12b · Phys 4- Energy · platform P2 Fuels and energy resources · SPLIT 2→1: the platform''s `fuels-and-energy-resources` covers fossil and renewable together. 12a carries the same slug.'),
  -- Phys 5- Waves
  -- 21a  Waves
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 9, 'Phys 5- Waves', 'waves-on-water', 'Rainford Y8 week 21a · Phys 5- Waves · platform P6 Waves on water: what a wave is'),
  -- 21b  Reflection
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 10, 'Phys 5- Waves', 'reflection-mirrors-and-scattering', 'Rainford Y8 week 21b · Phys 5- Waves · platform P7 Reflection: mirrors and scattering'),
  -- 22a  Refraction
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 11, 'Phys 5- Waves', 'refraction', 'Rainford Y8 week 22a · Phys 5- Waves · platform P7 Refraction'),
  -- 22b  Colours & filters
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 12, 'Phys 5- Waves', 'colour-and-the-spectrum', 'Rainford Y8 week 22b · Phys 5- Waves · platform P7 Colour and the spectrum · MERGE 1→2: the colours of light (`colour-and-the-spectrum`) and how filters change appearance (`why-things-look-coloured`). Mapped to the first; the second is co-covered here.'),
  -- 23a  Sound
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 13, 'Phys 5- Waves', 'frequency-pitch-and-loudness', 'Rainford Y8 week 23a · Phys 5- Waves · platform P6 Frequency, pitch and loudness'),
  -- 23b  KO Quiz/The Ear
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 14, 'Phys 5- Waves', 'hearing-and-auditory-range', 'Rainford Y8 week 23b · Phys 5- Waves · platform P6 Hearing and auditory range'),
  -- 24a  Ultrasound & infrasound
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 15, 'Phys 5- Waves', 'ultrasound-at-work', 'Rainford Y8 week 24a · Phys 5- Waves · platform P6 Ultrasound at work'),
  -- 24b  EM Spectrum   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 16, 'Phys 5- Waves', null, 'Rainford Y8 week 24b · Phys 5- Waves · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. The electromagnetic spectrum appears in ks3_data ONLY as a `ks4_becomes` note on P7 `light-travels` and `colour-and-the-spectrum` — i.e. the platform names it as what these lessons become at KS4, and deliberately does not teach it at KS3.'),
  -- Phys 6- Energy in matter
  -- 32a  Forces in states of matter
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 17, 'Phys 6- Energy in matter', 'particle-model', 'Rainford Y8 week 32a · Phys 6- Energy in matter · platform C1 The particle model · ⚠ cross-discipline: taught as Physics here, drawn in a Chemistry unit · CROSS-DISCIPLINE: taught in Phys 6, so this row is PHYSICS; the platform''s `particle-model` belongs to C1 (Chemistry).'),
  -- 32b  Pressure
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 18, 'Phys 6- Energy in matter', 'pressure-force-over-area', 'Rainford Y8 week 32b · Phys 6- Energy in matter · platform P5 Pressure = force ÷ area'),
  -- 33a  Gas Pressure
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 19, 'Phys 6- Energy in matter', 'gas-pressure', 'Rainford Y8 week 33a · Phys 6- Energy in matter · platform C1 Gas pressure · ⚠ cross-discipline: taught as Physics here, drawn in a Chemistry unit · CROSS-DISCIPLINE, and a deliberate RE-TEACH: taught in Phys 6, so this row is PHYSICS, while the platform''s `gas-pressure` belongs to C1 (Chemistry). Rainford teaches the same lesson twice — Y7 6a under Chem 1 and here — which is a legitimate spiral, not a transcription error.'),
  -- 33b  Density
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 20, 'Phys 6- Energy in matter', 'density', 'Rainford Y8 week 33b · Phys 6- Energy in matter · platform P11 Density'),
  -- 34a  Conduction
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 21, 'Phys 6- Energy in matter', 'conduction', 'Rainford Y8 week 34a · Phys 6- Energy in matter · platform P1 Conduction'),
  -- 34b  Convection   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 22, 'Phys 6- Energy in matter', null, 'Rainford Y8 week 34b · Phys 6- Energy in matter · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED, and this is a genuine platform GAP worth Mide''s eye: P1 has `conduction`, `radiation` and `insulation` but NO convection lesson. Convection appears in ks3_data only as a distractor inside the radiation and insulation question sets.'),
  -- 35a  Thermal conductivity
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 23, 'Phys 6- Energy in matter', 'conduction', 'Rainford Y8 week 35a · Phys 6- Energy in matter · platform P1 Conduction · SPLIT 2→1: the platform''s `conduction` covers thermal conductivity as the property. 34a carries the same slug.'),
  -- 35b  Uses of insulators
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 8, null, null, (select id from public.subjects where name = 'Physics'), 24, 'Phys 6- Energy in matter', 'insulation', 'Rainford Y8 week 35b · Phys 6- Energy in matter · platform P1 Insulation');

-- ── Year 9 · Biology — 8 lessons, 3 mapped, 5 gap ──
insert into public.scheme_of_work_overrides
  (school_id, key_stage, year_group, tier, pathway, subject_id, academic_week, topic, subtopic, notes)
values
  -- Bio 7- Health & disease
  -- 1    Smoking & alcohol
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Biology'), 1, 'Bio 7- Health & disease', 'alcohol-and-smoking', 'Rainford Y9 week 1 · Bio 7- Health & disease · platform B6 Alcohol and smoking'),
  -- 1    Recreactional drugs
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Biology'), 2, 'Bio 7- Health & disease', 'what-drugs-do-to-the-body', 'Rainford Y9 week 1 · Bio 7- Health & disease · platform B6 What drugs do to the body'),
  -- 2    Effects of exercise
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Biology'), 3, 'Bio 7- Health & disease', 'exercise-asthma-and-smoking', 'Rainford Y9 week 2 · Bio 7- Health & disease · platform B4 Exercise, asthma and smoking'),
  -- 2    Microbes & disease   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Biology'), 4, 'Bio 7- Health & disease', null, 'Rainford Y9 week 2 · Bio 7- Health & disease · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. The platform has no KS3 lesson on microbes, pathogens or disease transmission (searched: ''pathogen'' appears nowhere in ks3_data). B6 is drugs, alcohol and substance misuse only.'),
  -- 3    Preventing transmission   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Biology'), 5, 'Bio 7- Health & disease', null, 'Rainford Y9 week 3 · Bio 7- Health & disease · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED, same gap as ''Microbes & disease''.'),
  -- 3    KO Quiz/Defence against disease   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Biology'), 6, 'Bio 7- Health & disease', null, 'Rainford Y9 week 3 · Bio 7- Health & disease · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED, same gap: no immune-system lesson at KS3.'),
  -- 4    Vaccination   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Biology'), 7, 'Bio 7- Health & disease', null, 'Rainford Y9 week 4 · Bio 7- Health & disease · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED, same gap: ''vaccine'' appears in ks3_data only in B5 `lifestyle-and-the-developing-foetus`, in passing.'),
  -- 4    Uses of bacteria   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Biology'), 8, 'Bio 7- Health & disease', null, 'Rainford Y9 week 4 · Bio 7- Health & disease · UNMAPPED (ambiguous): could be either of two platform lessons and neither is clearly right — left unmapped rather than guessed · UNMAPPED — AMBIGUOUS. B3 `bacteria-in-the-gut` is the only bacteria lesson and it is specifically about the gut microbiome; Rainford''s lesson is the general industrial and food uses of bacteria. Adjacent, not the same — left unmapped rather than pointed at the wrong lesson.');

-- ── Year 9 · Chemistry — 8 lessons, 2 mapped, 6 gap ──
insert into public.scheme_of_work_overrides
  (school_id, key_stage, year_group, tier, pathway, subject_id, academic_week, topic, subtopic, notes)
values
  -- Chem 7- Rate of reaction
  -- 5    Rates of reaction   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Chemistry'), 1, 'Chem 7- Rate of reaction', null, 'Rainford Y9 week 5 · Chem 7- Rate of reaction · UNMAPPED (beyond-ks3): beyond the statutory KS3 programme of study — ks3_data/school_schemes.py already records it as beyond_statutory for this school · UNMAPPED. The whole of Rainford''s Chem 7 except Catalysts and Conservation of mass is beyond statutory KS3 — ks3_data/school_schemes.py records ''rate-of-reaction'' for this school as beyond_statutory, ''KS4 content; not in the 2014 KS3 programme of study''.'),
  -- 5    Measuring rate (colour change)   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Chemistry'), 2, 'Chem 7- Rate of reaction', null, 'Rainford Y9 week 5 · Chem 7- Rate of reaction · UNMAPPED (beyond-ks3): beyond the statutory KS3 programme of study — ks3_data/school_schemes.py already records it as beyond_statutory for this school · UNMAPPED. Beyond statutory KS3 — see ''Rates of reaction''.'),
  -- 6    Measuring rate (gas collection)   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Chemistry'), 3, 'Chem 7- Rate of reaction', null, 'Rainford Y9 week 6 · Chem 7- Rate of reaction · UNMAPPED (beyond-ks3): beyond the statutory KS3 programme of study — ks3_data/school_schemes.py already records it as beyond_statutory for this school · UNMAPPED. Beyond statutory KS3 — see ''Rates of reaction''.'),
  -- 6    Rates of reaction (Temperature)   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Chemistry'), 4, 'Chem 7- Rate of reaction', null, 'Rainford Y9 week 6 · Chem 7- Rate of reaction · UNMAPPED (beyond-ks3): beyond the statutory KS3 programme of study — ks3_data/school_schemes.py already records it as beyond_statutory for this school · UNMAPPED. Beyond statutory KS3 — see ''Rates of reaction''.'),
  -- 7    KO Quiz/Rates of reaction (Concentration)   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Chemistry'), 5, 'Chem 7- Rate of reaction', null, 'Rainford Y9 week 7 · Chem 7- Rate of reaction · UNMAPPED (beyond-ks3): beyond the statutory KS3 programme of study — ks3_data/school_schemes.py already records it as beyond_statutory for this school · UNMAPPED. Beyond statutory KS3 — see ''Rates of reaction''.'),
  -- 7    Rates of reaction (Surface area)   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Chemistry'), 6, 'Chem 7- Rate of reaction', null, 'Rainford Y9 week 7 · Chem 7- Rate of reaction · UNMAPPED (beyond-ks3): beyond the statutory KS3 programme of study — ks3_data/school_schemes.py already records it as beyond_statutory for this school · UNMAPPED. Beyond statutory KS3 — see ''Rates of reaction''.'),
  -- 8    Catalysts
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Chemistry'), 7, 'Chem 7- Rate of reaction', 'catalysts', 'Rainford Y9 week 8 · Chem 7- Rate of reaction · platform C6 Catalysts · The only lesson in Rainford''s Chem 7 with a platform equivalent: C6 `catalysts`. The rest of the unit is beyond statutory KS3.'),
  -- 8    Conservation of mass
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Chemistry'), 8, 'Chem 7- Rate of reaction', 'mass-in-a-reaction', 'Rainford Y9 week 8 · Chem 7- Rate of reaction · platform C4 Mass in a reaction · Mapped to C4 `mass-in-a-reaction` — the outcomes are ''observe reactions where the mass changes'' and ''explain why the mass may appear to increase or decrease'', which is that lesson exactly. The platform also has C2 `conservation-of-mass` (the principle), which Rainford places nowhere.');

-- ── Year 9 · Physics — 6 lessons, 0 mapped, 6 gap ──
insert into public.scheme_of_work_overrides
  (school_id, key_stage, year_group, tier, pathway, subject_id, academic_week, topic, subtopic, notes)
values
  -- Phys 7- Exploring space
  -- 9    Nuclear fusion   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Physics'), 1, 'Phys 7- Exploring space', null, 'Rainford Y9 week 9 · Phys 7- Exploring space · UNMAPPED (beyond-ks3): beyond the statutory KS3 programme of study — ks3_data/school_schemes.py already records it as beyond_statutory for this school · UNMAPPED. ks3_data/school_schemes.py records ''fusion-and-star-life-cycle'' for this school as beyond_statutory, ''KS4 content; not in the 2014 KS3 programme of study''.'),
  -- 9    Life cycle of a star   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Physics'), 2, 'Phys 7- Exploring space', null, 'Rainford Y9 week 9 · Phys 7- Exploring space · UNMAPPED (beyond-ks3): beyond the statutory KS3 programme of study — ks3_data/school_schemes.py already records it as beyond_statutory for this school · UNMAPPED. Beyond statutory KS3 — see ''Nuclear fusion''.'),
  -- 10   Space exploration   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Physics'), 3, 'Phys 7- Exploring space', null, 'Rainford Y9 week 10 · Phys 7- Exploring space · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. The platform''s P12 has no space-exploration lesson.'),
  -- 10   Living in space   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Physics'), 4, 'Phys 7- Exploring space', null, 'Rainford Y9 week 10 · Phys 7- Exploring space · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. No platform equivalent.'),
  -- 11   Living on Mars   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Physics'), 5, 'Phys 7- Exploring space', null, 'Rainford Y9 week 11 · Phys 7- Exploring space · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. No platform equivalent.'),
  -- 11   Cosmic radiation   ← no platform lesson
  ((select id from public.schools where name = 'Rainford High School'), 'KS3', 9, null, null, (select id from public.subjects where name = 'Physics'), 6, 'Phys 7- Exploring space', null, 'Rainford Y9 week 11 · Phys 7- Exploring space · UNMAPPED (absent): no platform KS3 lesson covers this · UNMAPPED. The platform has no KS3 lesson on ionising radiation; P1 `radiation` is infrared/thermal radiation and is a different subject.');

commit;
