"""Physics · Electricity — the MRB-338 expansion of `resistors`.

The weight falls where AQA 6.2.1.4 actually spends it: the I–V behaviour of the
five named components, and the two sensing components' behaviour in a series
pair, which is where the spec's own worked street-light example lives and where
the baseline twelve had only two rows. The required practical (RP16) takes a
second band of rows for its method and its errors — reversing the connections,
keeping the current low, the protective resistor, diagnosing a line that bends
— and the rest goes on calculations from stated I–V data, since a lamp and a
thermistor only really separate from an ohmic resistor once numbers are put on
them. ⚠️ SEAM: `circuit-symbols` owns the SHAPES of the diode, LED, thermistor
and LDR symbols and how to draw and read them; this leaf owns their ELECTRICAL
BEHAVIOUR only, so no row here asks what a component looks like on a diagram,
and none reuses that leaf's ammeter/voltmeter resistance framing.
"""

TOPIC = "electricity"
SUBJECT = "physics"

QUESTIONS = [
    # ── easier · e05–e12 ────────────────────────────────────────────────
    {
        "id": "ks4-resistors-e05",
        "subtopic_slug": "resistors",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happens to the resistance of a light-dependent resistor as the light falling on it becomes brighter.",
        "options": [
            "It increases, because the light has to be absorbed by the material first",
            "It decreases, because more charge carriers become available",
            "It stays the same, because an LDR is an ohmic conductor",
            "It falls to zero, because bright light removes all opposition",
        ],
        "correct_index": 1,
        "why": "Brighter light frees more charge carriers inside the semiconductor, so the resistance of an LDR falls; in darkness there are few carriers and its resistance is very high.",
    },
    {
        "id": "ks4-resistors-e06",
        "subtopic_slug": "resistors",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State one advantage of using an LED instead of a filament lamp to light a room.",
        "options": [
            "It transfers a greater proportion of its energy to light",
            "It can be connected either way round in the circuit",
            "It has a constant resistance at every potential difference",
            "It needs no potential difference across it to switch on",
        ],
        "correct_index": 0,
        "why": "An LED transfers far more of the energy supplied to it to light, and far less to the surroundings by heating, which is why LEDs have replaced filament lamps.",
    },
    {
        "id": "ks4-resistors-e07",
        "subtopic_slug": "resistors",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a diode does to an alternating supply in a rectifier.",
        "options": [
            "It raises the frequency of the supply to a very much higher value than before",
            "It shares the supply equally between two separate branches",
            "It allows current in one direction only, giving a direct supply",
            "It stores the charge and then releases it at a steady rate",
        ],
        "correct_index": 2,
        "why": "A diode blocks the half of each cycle in which the current would flow backwards, so the current reaching the device is always in the same direction.",
    },
    {
        "id": "ks4-resistors-e08",
        "subtopic_slug": "resistors",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the component used in a camera exposure meter to sense how bright a scene is.",
        "options": [
            "A thermistor, whose resistance responds to the temperature around it",
            "A diode, which passes current in one direction only",
            "A fuse, which melts when the current through it becomes too large",
            "A light-dependent resistor, whose resistance responds to light",
        ],
        "correct_index": 3,
        "why": "The resistance of a light-dependent resistor falls as the light falling on it brightens, so the current in its circuit is a measure of how bright the scene is.",
    },
    {
        "id": "ks4-resistors-e09",
        "subtopic_slug": "resistors",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the approximate potential difference at which a silicon diode begins to conduct in the forward direction.",
        "options": [
            "About 0.6 V",
            "About 6 V",
            "About 0.06 V",
            "About 60 V",
        ],
        "correct_index": 0,
        "why": "A silicon diode passes almost no current until the forward potential difference reaches roughly 0.6 V, after which the current rises steeply.",
    },
    {
        "id": "ks4-resistors-e10",
        "subtopic_slug": "resistors",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student plots current against potential difference for a filament lamp. State the shape of the line obtained.",
        "options": [
            "A straight line through the origin, with a constant gradient",
            "A curve that becomes shallower as the potential difference rises",
            "A horizontal line, because the current cannot change at all",
            "A straight line that meets the current axis at a point above the origin",
        ],
        "correct_index": 1,
        "why": "The filament heats up as the current rises, so its resistance increases and each extra volt adds less current than the last, bending the line over.",
    },
    {
        "id": "ks4-resistors-e11",
        "subtopic_slug": "resistors",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State why the connections to the supply are reversed partway through the required practical on I–V characteristics.",
        "options": [
            "To recharge the cells so that the supply stays at a steady value",
            "To remove the heating effect that spoils the first set of readings",
            "To obtain negative values of current and potential difference",
            "To reduce the resistance of the wires joining the components",
        ],
        "correct_index": 2,
        "why": "Reversing the supply drives the current the other way, so the graph can be completed on the negative side — which is how a diode's one-way behaviour shows up.",
    },
    {
        "id": "ks4-resistors-e12",
        "subtopic_slug": "resistors",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State one reason for keeping the current low during the required practical on I–V characteristics.",
        "options": [
            "So that the ammeter can display a reading with more decimal places",
            "So that the potential difference across the component stays at zero throughout",
            "So that the current has time to spread evenly through the wires",
            "So that the components do not heat up and change their resistance",
        ],
        "correct_index": 3,
        "why": "A component that warms up changes its resistance during the experiment, so the readings would no longer describe that component at a single temperature.",
    },

    # ── standard · s05–s26 ──────────────────────────────────────────────
    {
        "id": "ks4-resistors-s05",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A thermistor of resistance 7.0 kΩ is connected in series with a 5.0 kΩ fixed resistor across a 6.0 V supply. Calculate the potential difference across the fixed resistor.",
        "options": [
            "2.5 V",
            "3.5 V",
            "3.0 V",
            "6.0 V",
        ],
        "correct_index": 0,
        "why": "The resistances add to 12 kΩ, so the current is 6.0 ÷ 12 000 = 0.50 mA, and V = I × R = 0.50 mA × 5.0 kΩ = 2.5 V.",
    },
    {
        "id": "ks4-resistors-s06",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A security-light circuit contains a light-dependent resistor joined end to end with a 15 kΩ fixed resistor, the pair placed across a 14 V supply. In bright sunlight the LDR has a resistance of 5.0 kΩ. Determine the potential difference across the LDR in bright sunlight.",
        "options": [
            "10.5 V",
            "3.5 V",
            "7.0 V",
            "14 V",
        ],
        "correct_index": 1,
        "why": "The resistances add to 20 kΩ, so the current is 14 ÷ 20 000 = 0.70 mA, and V = 0.70 mA × 5.0 kΩ = 3.5 V across the LDR.",
    },
    {
        "id": "ks4-resistors-s07",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A thermistor has a resistance of 8.0 kΩ at 10 °C, falling to 2.0 kΩ at 40 °C. It is the only component in a circuit driven by a 12 V battery. Calculate the current through it when it is at 40 °C.",
        "options": [
            "1.5 mA",
            "24 mA",
            "6.0 mA",
            "6.0 A",
        ],
        "correct_index": 2,
        "why": "At 40 °C the resistance is 2.0 kΩ = 2000 Ω, so I = V ÷ R = 12 ÷ 2000 = 0.0060 A = 6.0 mA.",
    },
    {
        "id": "ks4-resistors-s08",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a filament lamp cannot be given a single resistance value.",
        "options": [
            "Its resistance depends on which way round the current passes",
            "Its resistance depends on the length of the wires used to connect it up",
            "Its resistance depends on the brightness of the room it is in",
            "Its resistance depends on how hot the filament is, which depends on the current",
        ],
        "correct_index": 3,
        "why": "A filament lamp is not ohmic: a larger current heats the filament and raises its resistance, so V ÷ I gives a different value at every point on the graph.",
    },
    {
        "id": "ks4-resistors-s09",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the resistance of a thermistor falls when it is warmed.",
        "options": [
            "Warming releases more charge carriers inside it, so charge flows more easily",
            "Warming makes its ions vibrate more, so they obstruct the electrons more",
            "Warming expands the material, so the charge has a shorter path to travel",
            "Warming drives a larger current, and a larger current lowers the resistance of anything",
        ],
        "correct_index": 0,
        "why": "A thermistor is made from a semiconductor: heating it releases extra charge carriers, so more charge flows for the same potential difference and the resistance falls.",
    },
    {
        "id": "ks4-resistors-s10",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the resistance of a light-dependent resistor falls when brighter light shines on it.",
        "options": [
            "The light warms the surface, and a warm surface reflects a larger share of the current back",
            "The light frees extra charge carriers in the material, so charge flows more easily",
            "The light pushes the electrons along, adding to the force from the supply",
            "The light is absorbed as energy, which the component stores until it is dark",
        ],
        "correct_index": 1,
        "why": "Light falling on the semiconductor releases extra charge carriers, so the brighter the light the lower the resistance.",
    },
    {
        "id": "ks4-resistors-s11",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "At night the lamp outside a house switches itself on. Its sensing circuit joins a light-dependent resistor in series with a fixed resistor. Explain why the potential difference across the LDR is greatest in darkness.",
        "options": [
            "In darkness the LDR's resistance is lowest, so it passes the supply's whole current",
            "In darkness the current is smallest, and a small current produces a large pd across any component",
            "In darkness the LDR's resistance is highest, and the larger resistance takes the larger share of the supply pd",
            "In darkness the fixed resistor stops conducting, so the supply pd appears across the LDR instead",
        ],
        "correct_index": 2,
        "why": "Components in series share the supply pd in proportion to their resistances, and an LDR's resistance is at its highest in darkness, so its share is at its largest.",
    },
    {
        "id": "ks4-resistors-s12",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A fire alarm uses a thermistor as its sensor. Explain how the circuit detects a fire.",
        "options": [
            "The heat raises the thermistor's resistance, the current falls, and the alarm is triggered",
            "The heat melts a thin wire inside the thermistor, which completes the alarm circuit",
            "The heat charges the thermistor, which then supplies the pd that the alarm needs",
            "The heat lowers the thermistor's resistance, the current rises, and the alarm is triggered",
        ],
        "correct_index": 3,
        "why": "A thermistor's resistance falls as it gets hotter, so the current in the sensing circuit rises and the control circuit switches the alarm on.",
    },
    {
        "id": "ks4-resistors-s13",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe the I–V graph of a diode for negative values of potential difference.",
        "options": [
            "It lies almost flat along the axis, because almost no current passes",
            "It rises steeply, because a reversed diode has almost no resistance",
            "It is a straight line through the origin, exactly as it is for a fixed resistor",
            "It curves over gently, because the diode heats up as the pd is reversed",
        ],
        "correct_index": 0,
        "why": "A diode has a very high resistance in reverse, so the current stays close to zero however large the reversed potential difference becomes.",
    },
    {
        "id": "ks4-resistors-s14",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A fixed resistor is held at a constant temperature while its readings are taken, the connections are then reversed and the readings repeated. Predict the shape of the complete graph.",
        "options": [
            "A straight line for the positive values and a flat line for all of the negative ones",
            "One straight line through the origin, continuing into the negative values",
            "Two separate straight lines that meet the axes well away from the origin",
            "A curve that becomes steeper once the connections have been reversed",
        ],
        "correct_index": 1,
        "why": "An ohmic conductor has the same resistance whichever way the current passes, so the graph is one straight line through the origin running into both quadrants.",
    },
    {
        "id": "ks4-resistors-s15",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The fixed resistor in the I–V required practical must stay at a constant temperature. Suggest how a student achieves this.",
        "options": [
            "Use the largest current the supply can give, and work through the readings quickly",
            "Stand the resistor in a beaker of hot water held at a steady 80 °C",
            "Use small currents and switch the circuit off between readings",
            "Connect a second identical resistor in parallel with the first one",
        ],
        "correct_index": 2,
        "why": "The heating comes from the current, so keeping the current small and not leaving it flowing means the resistor barely warms and its resistance stays constant.",
    },
    {
        "id": "ks4-resistors-s16",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student says that a filament lamp obeys Ohm's law because its I–V graph passes through the origin. Explain why the student is wrong.",
        "options": [
            "Ohm's law applies only to graphs that do not pass through the origin at all",
            "Ohm's law applies to alternating supplies, and the lamp was tested on a direct supply",
            "Ohm's law needs the graph to be drawn with pd on the vertical axis instead",
            "Ohm's law needs current to be proportional to pd, and the lamp's graph curves",
        ],
        "correct_index": 3,
        "why": "A graph through the origin is not enough: Ohm's law requires a straight line, and the lamp's line bends over as the hot filament's resistance rises.",
    },
    {
        "id": "ks4-resistors-s17",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A filament lamp carries a current of 0.25 A when the potential difference across it is 4.0 V. Calculate its resistance at this point, and state how it would change at 8.0 V.",
        "options": [
            "16 Ω, and it would be larger at 8.0 V",
            "16 Ω, and it would be smaller at 8.0 V",
            "1.0 Ω, and it would be larger at 8.0 V",
            "0.063 Ω, and it would stay the same at 8.0 V",
        ],
        "correct_index": 0,
        "why": "R = V ÷ I = 4.0 ÷ 0.25 = 16 Ω; at a higher pd the larger current heats the filament further, so the resistance would be larger.",
    },
    {
        "id": "ks4-resistors-s18",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student builds an indicator: a 300 Ω resistor joined end to end with an LED, the pair placed across a 5.0 V battery. The pd measured across the glowing LED is 2.0 V. Calculate the current.",
        "options": [
            "17 mA",
            "10 mA",
            "6.7 mA",
            "23 mA",
        ],
        "correct_index": 1,
        "why": "The resistor takes 5.0 − 2.0 = 3.0 V, so I = V ÷ R = 3.0 ÷ 300 = 0.010 A = 10 mA, and the same current passes through the LED.",
    },
    {
        "id": "ks4-resistors-s19",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain how a light-dependent resistor lets a camera measure how bright a scene is.",
        "options": [
            "It gives out a potential difference of its own, in proportion to the light",
            "It counts the light that falls on it and sends that number to the camera",
            "Its resistance falls as the scene brightens, so the current in its circuit rises",
            "Its resistance rises as the scene brightens, so it blocks the extra light",
        ],
        "correct_index": 2,
        "why": "An LDR's resistance depends on the light falling on it, so the current in its circuit changes with brightness and can be used as a measure of it.",
    },
    {
        "id": "ks4-resistors-s20",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the energy transfers of an LED and of a filament lamp that are supplied with the same power.",
        "options": [
            "The lamp transfers more of it to light, the LED more of it to the surroundings",
            "Both transfer the same share to light, but the LED works at a lower pd",
            "Both transfer all of it to light, and neither of them heats the surroundings",
            "The LED transfers more of it to light, the lamp more of it to the surroundings",
        ],
        "correct_index": 3,
        "why": "An LED is far more efficient: most of the energy supplied to it is transferred to light, while a filament lamp transfers most of it to the surroundings by heating.",
    },
    {
        "id": "ks4-resistors-s21",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain how one diode allows a device that needs direct current to be run from an alternating supply.",
        "options": [
            "It conducts only while the current is the right way round, blocking the other half",
            "It reverses the current during the half-cycle that runs the wrong way",
            "It stores charge during one half-cycle and releases it during the next one",
            "It lowers the frequency of the supply until the current stops reversing",
        ],
        "correct_index": 0,
        "why": "A diode passes current one way only, so the halves of the cycle that would drive the current backwards are blocked and the device receives current in a single direction.",
    },
    {
        "id": "ks4-resistors-s22",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A component carries 0.40 A when the potential difference across it is 2.0 V, and 0.80 A when the potential difference is 4.0 V. Determine whether it is an ohmic conductor.",
        "options": [
            "No — the resistance rises from 5.0 Ω to 10 Ω between the two readings",
            "Yes — the resistance is 5.0 Ω at both readings, so current is proportional to pd",
            "Yes — the current doubled, so the resistance must have doubled as well",
            "No — an ohmic conductor carries the same current at any pd",
        ],
        "correct_index": 1,
        "why": "R = V ÷ I gives 2.0 ÷ 0.40 = 5.0 Ω and 4.0 ÷ 0.80 = 5.0 Ω, so the resistance is unchanged and the current is directly proportional to the pd.",
    },
    {
        "id": "ks4-resistors-s23",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student measures a component's resistance as 4.0 Ω at 2.0 V and as 6.0 Ω at 6.0 V. Identify the component.",
        "options": [
            "A fixed resistor, kept throughout at a constant temperature",
            "A diode, connected so that the current passes in the reverse direction only",
            "A filament lamp, whose filament heats up as the current rises",
            "A thermistor, warmed steadily while the readings are being taken",
        ],
        "correct_index": 2,
        "why": "Only a component whose resistance rises with current fits: the filament gets hotter at the higher pd, so V ÷ I gives a larger value.",
    },
    {
        "id": "ks4-resistors-s24",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "An oven thermostat uses a thermistor. Explain how the control circuit knows that the oven has reached the temperature that was set.",
        "options": [
            "The thermistor's resistance rises as the oven heats, and the circuit reacts to that rise",
            "The thermistor melts once the set temperature is passed, breaking the heater circuit",
            "The thermistor stores the heat until it is full, and then refuses to pass any current",
            "The thermistor's resistance falls as the oven heats, and the circuit reacts to that fall",
        ],
        "correct_index": 3,
        "why": "An NTC thermistor's resistance falls as the temperature rises, so the potential difference across it changes and the control circuit opens the switch at the set value.",
    },
    {
        "id": "ks4-resistors-s25",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A diode is connected the correct way round in series with a lamp and a 6.0 V battery. The potential difference across the conducting diode is 0.7 V. Calculate the potential difference across the lamp.",
        "options": [
            "5.3 V",
            "6.7 V",
            "6.0 V",
            "0.7 V",
        ],
        "correct_index": 0,
        "why": "The potential differences across components in series add up to the supply pd, so the lamp takes 6.0 − 0.7 = 5.3 V.",
    },
    {
        "id": "ks4-resistors-s26",
        "subtopic_slug": "resistors",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare how the resistance of a thermistor and the resistance of a light-dependent resistor respond to their surroundings.",
        "options": [
            "Both rise — the thermistor when it is warmed, the LDR when the light brightens",
            "Both fall — the thermistor when it is warmed, the LDR when the light brightens",
            "The thermistor's falls when warmed, while the LDR's rises when the light brightens",
            "The thermistor's rises when warmed, while the LDR's falls when the light brightens",
        ],
        "correct_index": 1,
        "why": "Both respond negatively: an NTC thermistor's resistance falls as it gets hotter, and an LDR's falls as the light shining on it gets brighter.",
    },

    # ── harder · h05–h26 ────────────────────────────────────────────────
    {
        "id": "ks4-resistors-h05",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A filament lamp carries 0.30 A at 1.5 V and 0.60 A at 9.0 V. Determine how many times larger its resistance is at the second reading than at the first.",
        "options": [
            "Three times larger",
            "Twice as large",
            "Six times larger",
            "The same at both readings",
        ],
        "correct_index": 0,
        "why": "R = V ÷ I gives 1.5 ÷ 0.30 = 5.0 Ω and 9.0 ÷ 0.60 = 15 Ω, and 15 ÷ 5.0 = 3.",
    },
    {
        "id": "ks4-resistors-h06",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "An LDR is wired in series with a 1.0 kΩ fixed resistor across a 6.0 V supply. The LDR's resistance is 5.0 kΩ in dim light and 1.0 kΩ in bright light. Compare the potential difference across the fixed resistor under each lighting condition.",
        "options": [
            "5.0 V in dim light and 3.0 V in bright light",
            "1.0 V in dim light and 3.0 V in bright light",
            "6.0 V in dim light and 6.0 V in bright light",
            "1.2 V in dim light and 6.0 V in bright light",
        ],
        "correct_index": 1,
        "why": "In dim light the total is 6.0 kΩ, so the current is 1.0 mA and the fixed resistor takes 1.0 mA × 1.0 kΩ = 1.0 V; in bright light the total is 2.0 kΩ, the current is 3.0 mA and it takes 3.0 V.",
    },
    {
        "id": "ks4-resistors-h07",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A security light switches on when the potential difference across its 4.0 kΩ fixed resistor falls to 4.0 V. The supply is 12 V and the fixed resistor is in series with a light-dependent resistor. Determine the LDR's resistance at the instant the light switches on.",
        "options": [
            "4.0 kΩ",
            "16 kΩ",
            "8.0 kΩ",
            "12 kΩ",
        ],
        "correct_index": 2,
        "why": "The current is 4.0 ÷ 4000 = 1.0 mA, and the LDR takes 12 − 4.0 = 8.0 V, so its resistance is 8.0 ÷ 0.0010 = 8000 Ω = 8.0 kΩ.",
    },
    {
        "id": "ks4-resistors-h08",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "At a potential difference of 1.0 V a diode carries 20 mA in the forward direction and 0.00020 mA in the reverse direction. Determine how many times larger its reverse resistance is than its forward resistance.",
        "options": [
            "1000 times larger",
            "100 times larger",
            "10 000 times larger",
            "100 000 times larger",
        ],
        "correct_index": 3,
        "why": "At the same potential difference the resistance is inversely proportional to the current, so the ratio is 20 ÷ 0.00020 = 100 000.",
    },
    {
        "id": "ks4-resistors-h09",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the use of an LED rather than a filament lamp in a torch powered by a small battery.",
        "options": [
            "Better — far more of the energy stored in the battery is transferred to light",
            "Worse — an LED needs a much larger current than a filament lamp of the same brightness would",
            "Better — an LED has no resistance at all, so the battery supplies no energy to it",
            "No difference — both transfer the same fraction of the energy supplied to light",
        ],
        "correct_index": 0,
        "why": "An LED transfers a much greater proportion of the energy supplied to light and much less to the surroundings by heating, so a given battery lasts longer for the same brightness.",
    },
    {
        "id": "ks4-resistors-h10",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student's I–V graph for a fixed resistor is straight at low potential differences but bends over at the highest ones. Suggest what happened and how to avoid it.",
        "options": [
            "The battery ran down during the readings; replace it with a fresh one each time",
            "The large current warmed the resistor, raising its resistance; use smaller currents",
            "The large current cooled the resistor, lowering its resistance; use larger currents",
            "The resistor became a diode at high pd; put a protective resistor in series with it",
        ],
        "correct_index": 1,
        "why": "A resistor is ohmic only while its temperature is constant; the largest currents heated it, so its resistance rose and the line bent over. Smaller currents keep it cool.",
    },
    {
        "id": "ks4-resistors-h11",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A greenhouse controller must open a vent when the air becomes too warm, and lower a blind when the sun becomes too bright. Determine which sensing component belongs in each part of the controller.",
        "options": [
            "A diode for the vent and a variable resistor for the blind",
            "A light-dependent resistor for the vent and a thermistor for the blind",
            "A thermistor for the vent and a light-dependent resistor for the blind",
            "A variable resistor for the vent and a diode for the blind",
        ],
        "correct_index": 2,
        "why": "A thermistor's resistance responds to temperature and an LDR's responds to light, so each senses the quantity that its part of the controller has to act on.",
    },
    {
        "id": "ks4-resistors-h12",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A device needs a current that is always in the same direction, but only an alternating supply is available. Explain how a single diode helps, and state one limitation of using just one.",
        "options": [
            "It blocks the reversed half of each cycle, so the current that follows is perfectly steady",
            "It smooths the supply into a steady current, but lowers the pd by about 0.6 V",
            "It doubles the frequency of the supply, but wastes half of the energy by heating",
            "It blocks the reversed half of each cycle, but the current then comes in pulses",
        ],
        "correct_index": 3,
        "why": "The diode passes only the halves of the cycle in which the current is the right way round, so the device receives one-way current — but it arrives in pulses with gaps between them.",
    },
    {
        "id": "ks4-resistors-h13",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare what happens to the resistance of a metal wire and to the resistance of an NTC thermistor when both are heated by the same amount.",
        "options": [
            "The wire's rises as its ions vibrate more; the thermistor's falls as carriers are freed",
            "The wire's falls as its ions vibrate more; the thermistor's rises as carriers are freed",
            "Both rise, because heating makes it harder for charge to pass through any solid",
            "Both fall, because heating gives the charge carriers the energy they need to move",
        ],
        "correct_index": 0,
        "why": "In a metal, heating makes the lattice ions vibrate more and obstruct the electrons, raising the resistance; in a semiconducting thermistor, heating releases extra charge carriers and the resistance falls.",
    },
    {
        "id": "ks4-resistors-h14",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A street light switches on when the potential difference across its light-dependent resistor reaches two thirds of the supply. Suggest how to make it switch on while the sky is still brighter.",
        "options": [
            "Replace the LDR with one that has a larger resistance in the dark",
            "Replace the fixed resistor with one of smaller resistance",
            "Replace the fixed resistor with one of larger resistance",
            "Replace the supply with one of larger potential difference",
        ],
        "correct_index": 1,
        "why": "The pd reaches two thirds of the supply when the LDR's resistance has risen to twice the fixed resistance, and brighter light means a lower LDR resistance, so a smaller fixed resistor triggers it earlier.",
    },
    {
        "id": "ks4-resistors-h15",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A circuit needs a component that passes current equally in both directions and whose resistance depends on temperature. Determine which component meets both requirements.",
        "options": [
            "A diode, which responds to temperature but conducts one way only",
            "An LDR, which conducts both ways but responds to light, not to heat",
            "A thermistor, which conducts both ways and responds to temperature",
            "A fixed resistor, which conducts both ways and has a constant resistance",
        ],
        "correct_index": 2,
        "why": "A thermistor conducts equally in either direction, unlike a diode, and its resistance falls as the temperature rises, unlike a fixed resistor.",
    },
    {
        "id": "ks4-resistors-h16",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A thermistor is connected on its own across a 9.0 V supply. The current is 3.0 mA at 20 °C and 9.0 mA at 60 °C. Calculate its resistance at each of those temperatures.",
        "options": [
            "1.0 kΩ at 20 °C and 3.0 kΩ at 60 °C",
            "27 kΩ at 20 °C and 81 kΩ at 60 °C",
            "0.33 kΩ at 20 °C and 1.0 kΩ at 60 °C",
            "3.0 kΩ at 20 °C and 1.0 kΩ at 60 °C",
        ],
        "correct_index": 3,
        "why": "R = V ÷ I gives 9.0 ÷ 0.0030 = 3000 Ω at 20 °C and 9.0 ÷ 0.0090 = 1000 Ω at 60 °C, so the resistance falls as the thermistor warms.",
    },
    {
        "id": "ks4-resistors-h17",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "An LED must carry 20 mA from a 9.0 V supply. When it is lit the potential difference across the LED is 2.0 V. Calculate the resistance of the protective resistor needed in series with it.",
        "options": [
            "350 Ω",
            "450 Ω",
            "100 Ω",
            "550 Ω",
        ],
        "correct_index": 0,
        "why": "The resistor must take 9.0 − 2.0 = 7.0 V while carrying 20 mA, so R = V ÷ I = 7.0 ÷ 0.020 = 350 Ω.",
    },
    {
        "id": "ks4-resistors-h18",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the I–V graph of a diode with the I–V graph of a fixed resistor that is kept at a constant temperature.",
        "options": [
            "The diode's is one straight line both ways; the resistor's is flat in reverse and steep forward",
            "The resistor's is one straight line both ways; the diode's is flat in reverse and steep forward",
            "Both are straight lines, but the diode's is steeper because it has a lower resistance",
            "Both are curves, because the resistance of each of them changes as the current rises",
        ],
        "correct_index": 1,
        "why": "A fixed resistor at constant temperature has the same resistance whichever way the current passes, giving one straight line, while a diode conducts only above about 0.6 V forward and blocks the reverse direction.",
    },
    {
        "id": "ks4-resistors-h19",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student investigating a diode obtains only positive values of current and potential difference. Explain what their results show so far, and what they should do next.",
        "options": [
            "Only the reverse direction has been tested; turn the diode round and repeat",
            "The diode is faulty, since a working one gives negative readings straight away",
            "Only the forward direction has been tested; reverse the connections and repeat",
            "The results are complete, because a diode's graph is always drawn in just one quadrant",
        ],
        "correct_index": 2,
        "why": "Positive readings alone describe only the forward direction; reversing the connections gives the negative values that show the diode blocking the current the other way.",
    },
    {
        "id": "ks4-resistors-h20",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student says that in complete darkness a light-dependent resistor behaves like a diode, because almost no current passes through it. Evaluate this claim.",
        "options": [
            "Correct — both have a very high resistance, so both behave the same way",
            "Wrong — an LDR in darkness has a very low resistance, so a large current passes",
            "Correct — in darkness an LDR conducts only the way a diode would",
            "Wrong — the LDR still passes current equally either way, while a diode blocks one way",
        ],
        "correct_index": 3,
        "why": "A dark LDR has a very high resistance but conducts the same in both directions, while a diode's high resistance appears in one direction only, whatever the lighting.",
    },
    {
        "id": "ks4-resistors-h21",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 2.5 kΩ thermistor and a 500 Ω resistor are placed one after the other across a 12 V supply. Calculate the current, in milliamps.",
        "options": [
            "4.0 mA",
            "4.8 mA",
            "24 mA",
            "0.25 mA",
        ],
        "correct_index": 0,
        "why": "2.5 kΩ is 2500 Ω, so the total resistance is 2500 + 500 = 3000 Ω and I = V ÷ R = 12 ÷ 3000 = 0.0040 A = 4.0 mA.",
    },
    {
        "id": "ks4-resistors-h22",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "At dusk a light-dependent resistor and a fixed resistor each have a resistance of 20 kΩ, and the two are in series across an 8.0 V supply. Determine the potential difference across each at dusk, and describe how the two change as night falls.",
        "options": [
            "4.0 V each at dusk; the fixed resistor's share grows and the LDR's share falls",
            "4.0 V each at dusk; the LDR's share grows and the fixed resistor's share falls",
            "8.0 V each at dusk; both shares stay the same however dark it becomes outside",
            "2.0 V each at dusk; the LDR's share then falls because darkness lowers its resistance",
        ],
        "correct_index": 1,
        "why": "Equal resistances share the 8.0 V equally, giving 4.0 V each; as it darkens the LDR's resistance rises, so it takes a larger share and the fixed resistor takes less.",
    },
    {
        "id": "ks4-resistors-h23",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the I–V graph of a filament lamp is almost straight for the smallest values of current.",
        "options": [
            "At small currents the filament is at its hottest, so its resistance is steady",
            "At small currents the current passes through the supporting wires, not the filament",
            "At small currents the filament barely warms, so its resistance hardly changes",
            "At small currents the glass envelope carries a share of the current instead",
        ],
        "correct_index": 2,
        "why": "Resistance rises only when the filament heats, and at very small currents almost no heating occurs, so over that part of the range the lamp is nearly ohmic.",
    },
    {
        "id": "ks4-resistors-h24",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 10 Ω resistor and a 30 Ω resistor are each tested separately over the same range of potential difference. Compare the current in each at 6.0 V and the steepness of the two I–V lines.",
        "options": [
            "0.60 A and 0.20 A; the 30 Ω line is three times as steep as the 10 Ω line",
            "0.20 A and 0.60 A; the 30 Ω line is three times as steep as the 10 Ω line",
            "60 A and 20 A; the two lines turn out to have exactly the same steepness",
            "0.60 A and 0.20 A; the 10 Ω line is three times as steep as the 30 Ω line",
        ],
        "correct_index": 3,
        "why": "I = V ÷ R gives 6.0 ÷ 10 = 0.60 A and 6.0 ÷ 30 = 0.20 A; the smaller resistance passes more current per volt, so its line is three times as steep.",
    },
    {
        "id": "ks4-resistors-h25",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A filament lamp and a fixed resistor each carry 0.50 A when 6.0 V is across them. The potential difference across each is then raised to 12 V. Predict which of them carries the larger current.",
        "options": [
            "The filament lamp, because a hotter filament lets charge through more easily",
            "Neither — both carry 1.0 A, since both started from the same current at 6.0 V",
            "The fixed resistor, because the lamp's hotter filament now has a larger resistance",
            "Neither — both carry 0.50 A, since the current is set by the lamp and the resistor",
        ],
        "correct_index": 2,
        "why": "The resistor stays at 12 Ω and carries 12 ÷ 12 = 1.0 A, while the lamp's filament heats further, so its resistance exceeds 12 Ω and its current is less than 1.0 A.",
    },
    {
        "id": "ks4-resistors-h26",
        "subtopic_slug": "resistors",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A fire alarm sounds when the potential difference across its 3.0 kΩ fixed resistor reaches 4.0 V. That resistor is in series with a thermistor across a 9.0 V supply, and the thermistor's resistance is 2.0 kΩ at 70 °C. Determine whether the alarm sounds at 70 °C.",
        "options": [
            "No — the fixed resistor takes 3.6 V, which is below the 4.0 V needed",
            "No — the fixed resistor takes 1.8 V, which is below the 4.0 V needed",
            "Yes — the fixed resistor takes the whole 9.0 V, because the thermistor takes none",
            "Yes — the fixed resistor takes 5.4 V, which is above the 4.0 V needed",
        ],
        "correct_index": 3,
        "why": "The total resistance is 3.0 + 2.0 = 5.0 kΩ, so the current is 9.0 ÷ 5000 = 1.8 mA and the fixed resistor takes 1.8 mA × 3.0 kΩ = 5.4 V, above the 4.0 V trigger.",
    },
]
