"""Physics · Electricity — the MRB-338 expansion of `series-parallel-circuits`.

The weight falls on the two places the baseline twelve only touch once each:
combinations with more than two components — three parallel branches, a series
pair inside a branch, a parallel pair inside a loop — and the required
practical on combining resistors, where the demand is apparatus, control
variables and the error a student actually makes rather than arithmetic. The
household-wiring reason is carried by named-appliance scenarios (a kettle and a
toaster on one ring main, a third appliance plugged in) so that the fact is
examined through what an appliance keeps or loses, never as the bare question
the lesson already prints with its answer.
"""

TOPIC = "electricity"
SUBJECT = "physics"

QUESTIONS = [
    {
        "id": "ks4-series-parallel-circuits-e05",
        "subtopic_slug": "series-parallel-circuits",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two lamps and a resistor are joined in one series loop with a "
                "battery. An ammeter placed between the first lamp and the "
                "resistor reads 0.40 A. State the reading on a second ammeter "
                "placed between the second lamp and the battery.",
        "options": [
            "0.13 A",
            "0.40 A",
            "1.2 A",
            "0.20 A",
        ],
        "correct_index": 1,
        "why": "A series loop offers one path only, so the same current passes "
               "through every part of it and the second ammeter also reads 0.40 "
               "A.",
    },
    {
        "id": "ks4-series-parallel-circuits-e06",
        "subtopic_slug": "series-parallel-circuits",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Five identical 4.0 Ω resistors are connected one after another in a single loop. Calculate the total resistance of the five together.",
        "options": [
            "0.80 Ω",
            "4.0 Ω",
            "20 Ω",
            "9.0 Ω",
        ],
        "correct_index": 2,
        "why": "Resistances in series add, so the total is 5 × 4.0 = 20 Ω.",
    },
    {
        "id": "ks4-series-parallel-circuits-e07",
        "subtopic_slug": "series-parallel-circuits",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A kettle and a reading lamp are plugged into different sockets on the same 230 V ring main, which connects them in parallel. State the potential difference across the reading lamp while the kettle is boiling.",
        "options": [
            "230 V",
            "115 V",
            "460 V",
            "23 V",
        ],
        "correct_index": 0,
        "why": "Every branch of a parallel circuit has the full supply pd across it, so the lamp still has 230 V whatever the kettle is doing.",
    },
    {
        "id": "ks4-series-parallel-circuits-e08",
        "subtopic_slug": "series-parallel-circuits",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two 10 Ω resistors are connected side by side in parallel. Calculate the total resistance of the pair.",
        "options": [
            "20 Ω",
            "10 Ω",
            "0.20 Ω",
            "5.0 Ω",
        ],
        "correct_index": 3,
        "why": "Two equal branches share the current equally, so twice as much current flows for the same pd and the total is half of 10 Ω, which is 5.0 Ω.",
    },
    {
        "id": "ks4-series-parallel-circuits-e09",
        "subtopic_slug": "series-parallel-circuits",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A set of decorative lights has its lamps connected in parallel. One lamp fails and stops conducting. State what happens to the remaining lamps.",
        "options": [
            "They all go out, because the circuit has lost one of its paths",
            "They go dimmer, because the broken lamp still takes a share of the pd",
            "They keep working, because each one has its own path to the supply",
            "They grow brighter, because the current the broken lamp took passes to them",
        ],
        "correct_index": 2,
        "why": "Each parallel branch is a separate path with the full supply pd across it, so a break in one branch leaves the others unchanged.",
    },
    {
        "id": "ks4-series-parallel-circuits-e10",
        "subtopic_slug": "series-parallel-circuits",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Three branches of a parallel circuit carry currents of 0.20 A, 0.50 A and 1.10 A. Calculate the current drawn from the supply.",
        "options": [
            "0.60 A",
            "1.80 A",
            "1.60 A",
            "1.10 A",
        ],
        "correct_index": 1,
        "why": "The branch currents add to give the supply current: 0.20 + 0.50 + 1.10 = 1.80 A.",
    },
    {
        "id": "ks4-series-parallel-circuits-e11",
        "subtopic_slug": "series-parallel-circuits",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two resistors joined in series have a total resistance of 15 Ω. One of them has a resistance of 6.0 Ω. Calculate the resistance of the other.",
        "options": [
            "9.0 Ω",
            "21 Ω",
            "2.5 Ω",
            "15 Ω",
        ],
        "correct_index": 0,
        "why": "In series the resistances add, so the missing one is 15 − 6.0 = 9.0 Ω.",
    },
    {
        "id": "ks4-series-parallel-circuits-e12",
        "subtopic_slug": "series-parallel-circuits",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "In the required practical on combining resistors, a student needs the current in one branch of a parallel pair. State where the ammeter must be connected.",
        "options": [
            "In parallel with that branch, so that it has the same pd across it as the branch",
            "In the main wire beside the battery, so that it reads the current before it divides",
            "Between the two branches, so that it reads the current passing from one to the other",
            "In series within that branch, so that the branch's own current passes through it",
        ],
        "correct_index": 3,
        "why": "An ammeter reads the current in the path it sits in, so measuring one branch means placing it inside that branch and nowhere else.",
    },
    {
        "id": "ks4-series-parallel-circuits-s05",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 15 Ω branch and a 10 Ω branch are wired side by side across a 30 V supply. Determine the single resistance that would draw the same current from that supply.",
        "options": [
            "25 Ω",
            "6.0 Ω",
            "12.5 Ω",
            "10 Ω",
        ],
        "correct_index": 1,
        "why": "The branches take 30 ÷ 15 = 2.0 A and 30 ÷ 10 = 3.0 A, giving 5.0 A in all, so R = 30 ÷ 5.0 = 6.0 Ω — below the 10 Ω branch, as a parallel total always is.",
    },
    {
        "id": "ks4-series-parallel-circuits-s06",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 12 V supply is connected to three parallel branches of resistance 12 Ω, 6.0 Ω and 4.0 Ω. Calculate the current drawn from the supply.",
        "options": [
            "0.55 A",
            "2.0 A",
            "6.0 A",
            "3.0 A",
        ],
        "correct_index": 2,
        "why": "Each branch has 12 V across it, giving 1.0 A, 2.0 A and 3.0 A, and the branch currents add to 6.0 A.",
    },
    {
        "id": "ks4-series-parallel-circuits-s07",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two 8.0 Ω resistors are connected across a 16 V supply, first in series and then in parallel. Compare the current drawn from the supply in the two arrangements.",
        "options": [
            "1.0 A in series and 4.0 A in parallel, because the parallel total resistance is lower",
            "1.0 A in series and 0.25 A in parallel, because the branches share the current between them",
            "4.0 A in series and 1.0 A in parallel, because a single loop carries the whole current",
            "2.0 A in both arrangements, because the supply pd and the resistors are unchanged",
        ],
        "correct_index": 0,
        "why": "In series R = 16 Ω so I = 1.0 A; in parallel R = 4.0 Ω so I = 4.0 A — the same two components draw four times the current when they are given two paths.",
    },
    {
        "id": "ks4-series-parallel-circuits-s08",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A kettle and a toaster are plugged into sockets on the same 230 V ring main and switched on together. The toaster is then switched off. Describe what happens to the kettle.",
        "options": [
            "Its pd rises above 230 V because it no longer shares the supply with the toaster",
            "It keeps the full 230 V across it, so its current stays exactly as it was",
            "Its pd falls because the ring main now delivers a smaller total current",
            "Its current rises because the total resistance of the ring main has fallen",
        ],
        "correct_index": 1,
        "why": "Parallel branches each hold the supply pd, so switching one appliance off changes neither the pd across the kettle nor the current in it.",
    },
    {
        "id": "ks4-series-parallel-circuits-s09",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student builds a series circuit of two resistors and wants to check that the potential differences across them add up to the supply potential difference. Describe how the voltmeters must be connected.",
        "options": [
            "One across each resistor and one across the supply, each in parallel with what it measures",
            "One in series with each resistor, so that the same current passes through the meter",
            "One in the main wire and one in each branch of the circuit, read one after the other",
            "One in series between the two resistors, so that it reads the pd passing between them",
        ],
        "correct_index": 0,
        "why": "Potential difference is measured between two points, so a voltmeter is always connected in parallel with the part of the circuit it is measuring.",
    },
    {
        "id": "ks4-series-parallel-circuits-s10",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student measures the potential difference across each of two resistors in series and records 4.2 V and 7.6 V with a supply marked 12 V. Suggest why the two readings do not add up to exactly 12 V.",
        "options": [
            "Potential difference is not conserved in a series circuit, so the pds need not add up",
            "The leads and connections have small resistances that take a share of the pd, and each reading is only given to two significant figures",
            "The voltmeter changes the current in the circuit because it is connected in series with the two resistors",
            "One of the two resistors must have been connected in parallel rather than in series",
        ],
        "correct_index": 1,
        "why": "The pds round a loop do add to the supply pd, so the shortfall is the small pd across the leads together with the limited precision of the readings.",
    },
    {
        "id": "ks4-series-parallel-circuits-s11",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 15 Ω resistor is connected in series with an unknown resistor across a 24 V supply, and the current is 0.60 A. Calculate the resistance of the unknown resistor.",
        "options": [
            "55 Ω",
            "40 Ω",
            "9.0 Ω",
            "25 Ω",
        ],
        "correct_index": 3,
        "why": "The total resistance is 24 ÷ 0.60 = 40 Ω, so the unknown resistor is 40 − 15 = 25 Ω.",
    },
    {
        "id": "ks4-series-parallel-circuits-s12",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two resistors are connected in parallel across a 6.0 V battery. The resistance of one branch is then increased. Predict the effect on the current in the other branch.",
        "options": [
            "It increases, because the current that no longer flows in the first branch is diverted into it",
            "It decreases, because the total resistance of the parallel combination has risen",
            "It is unchanged, because that branch still has 6.0 V across it and its own resistance",
            "It increases, because the total current drawn from the battery has to stay the same",
        ],
        "correct_index": 2,
        "why": "The pd across a branch is fixed by the supply, so I = V ÷ R for that branch is untouched by what happens in the other one.",
    },
    {
        "id": "ks4-series-parallel-circuits-s13",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 9.0 V battery drives a network made of two sections joined one after the other. The first section is a parallel pair of 6.0 Ω resistors and the second is a parallel pair of 3.0 Ω resistors. Calculate the current drawn from the battery.",
        "options": [
            "0.50 A",
            "2.0 A",
            "3.0 A",
            "1.0 A",
        ],
        "correct_index": 1,
        "why": "Each parallel pair halves to 3.0 Ω and 1.5 Ω, which add in series to 4.5 Ω, so I = 9.0 ÷ 4.5 = 2.0 A.",
    },
    {
        "id": "ks4-series-parallel-circuits-s14",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which arrangement of three 9.0 Ω resistors gives a total resistance of 3.0 Ω?",
        "options": [
            "All three connected in series",
            "Two in parallel, with the third in series with the pair",
            "All three connected in parallel",
            "Two in series, with the third in parallel across the pair",
        ],
        "correct_index": 2,
        "why": "Three equal branches each carry the same current, so three times as much current flows as through one alone and the total is 9.0 ÷ 3 = 3.0 Ω.",
    },
    {
        "id": "ks4-series-parallel-circuits-s15",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two lamps connected in parallel are working normally. A resistor is then connected in series with the battery. Predict the effect on the brightness of the lamps.",
        "options": [
            "Both become brighter, because the total resistance of the circuit has fallen",
            "Neither changes, because each lamp still has the full battery pd across it",
            "Only the lamp nearer the battery dims, because the current reaches it first",
            "Both become dimmer, because the pd left across the parallel pair has fallen",
        ],
        "correct_index": 3,
        "why": "The added resistor is in the single main path, so it takes a share of the battery pd and leaves less across the parallel pair, lowering both lamp currents.",
    },
    {
        "id": "ks4-series-parallel-circuits-s16",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "In the required practical a student connects two resistors in parallel and places one ammeter in each branch and a third in the main wire. Describe the relationship the three readings should show.",
        "options": [
            "The main-wire reading equals the sum of the two branch readings",
            "The main-wire reading equals the larger of the two branch readings",
            "All three readings are equal, because the current is the same everywhere",
            "The two branch readings add up to twice the main-wire reading",
        ],
        "correct_index": 0,
        "why": "Charge leaving the supply divides between the branches and rejoins afterwards, so the branch currents must add to the current in the main wire.",
    },
    {
        "id": "ks4-series-parallel-circuits-s17",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 2.0 Ω, a 4.0 Ω and a 6.0 Ω resistor form a single series loop with a 36 V battery. Determine the potential difference across the 6.0 Ω resistor.",
        "options": [
            "18 V",
            "36 V",
            "6.0 V",
            "12 V",
        ],
        "correct_index": 0,
        "why": "The total resistance is 12 Ω so the current is 36 ÷ 12 = 3.0 A, and across the 6.0 Ω resistor V = 3.0 × 6.0 = 18 V.",
    },
    {
        "id": "ks4-series-parallel-circuits-s18",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A family plugs a third appliance into a ring main that already has two appliances working on it. Describe the effect on the current drawn from the mains and on the two appliances already working.",
        "options": [
            "The total current is unchanged, because it is shared between more appliances",
            "The total current rises, and the appliances already working each draw a little less",
            "The total current falls, because adding another branch raises the total resistance",
            "The total current rises, while the appliances already working are unaffected",
        ],
        "correct_index": 3,
        "why": "A new branch is a further path, so the supply current rises, while the existing branches keep the same pd and therefore the same current.",
    },
    {
        "id": "ks4-series-parallel-circuits-s19",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student measures the total resistance of two resistors in parallel and obtains a value slightly larger than the value calculated from the marked resistances. Suggest the most likely reason.",
        "options": [
            "The resistors warmed up, and warming a metal wire lowers its resistance",
            "The ammeter was connected in parallel, so it read a current that was far too large",
            "A parallel combination is always larger than either resistor, so the value is right",
            "The connecting leads and crocodile clips add a little extra resistance to the circuit",
        ],
        "correct_index": 3,
        "why": "The meter measures the whole path, so the small resistance of the leads and clips is included and pushes the measured value above the calculated one.",
    },
    {
        "id": "ks4-series-parallel-circuits-s20",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 200 Ω resistor is connected in parallel with a 2.0 Ω resistor. Explain why the total resistance of the pair is a little under 2.0 Ω rather than a little over it.",
        "options": [
            "The two resistances are subtracted, which leaves a total 198 Ω smaller than before",
            "The extra branch gives the charge a second path, so more current flows for the same pd",
            "The supply pd is shared between the branches, so each branch receives less than before",
            "Adding a second resistor lowers the pd across the first, and a lower pd means a lower resistance",
        ],
        "correct_index": 1,
        "why": "Total resistance is supply pd ÷ total current, and any extra branch adds current without changing the pd, so the total must fall below the smallest branch.",
    },
    {
        "id": "ks4-series-parallel-circuits-s21",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 10 Ω resistor and a 15 Ω resistor are connected in parallel, and that combination is joined in series with a 4.0 Ω resistor. Calculate the total resistance of the whole circuit.",
        "options": [
            "29 Ω",
            "2.4 Ω",
            "10 Ω",
            "6.0 Ω",
        ],
        "correct_index": 2,
        "why": "The parallel pair behaves as 6.0 Ω, and resistances in series add, so the whole circuit is 6.0 + 4.0 = 10 Ω.",
    },
    {
        "id": "ks4-series-parallel-circuits-s22",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Older sets of festive lights were wired in series, and the whole string went dark when a single lamp failed. Explain why a modern string wired in parallel does not behave this way.",
        "options": [
            "A series string has one loop, so a break anywhere stops the current in all the lamps",
            "A series string shares the supply pd, so the other lamps are left with too little to light",
            "The failed lamp's resistance drops to zero, which short-circuits the rest of the string",
            "The current in a series string is used up by the lamps before it reaches the last one",
        ],
        "correct_index": 0,
        "why": "A parallel string gives every lamp its own path to the supply, so a break in one path leaves all the other paths complete.",
    },
    {
        "id": "ks4-series-parallel-circuits-s23",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "In the required practical the same two resistors are connected first in series and then in parallel. State why the supply potential difference must be kept the same for both arrangements.",
        "options": [
            "So that the resistors themselves keep the same resistance in both arrangements",
            "So that any change in the current is caused by the arrangement and not by the supply",
            "So that the ammeter gives the same reading in both of the two arrangements",
            "So that the total resistance of the circuit is the same in both arrangements",
        ],
        "correct_index": 1,
        "why": "Current depends on both pd and resistance, so the pd is the control variable that leaves the arrangement as the only thing that has changed.",
    },
    {
        "id": "ks4-series-parallel-circuits-s24",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two branches of resistance 18 Ω and 9.0 Ω are connected in parallel across an 18 V supply. The 18 Ω resistor is replaced by a 6.0 Ω resistor. Calculate the new current drawn from the supply.",
        "options": [
            "3.0 A",
            "1.2 A",
            "5.0 A",
            "2.4 A",
        ],
        "correct_index": 2,
        "why": "The branches now take 18 ÷ 6.0 = 3.0 A and 18 ÷ 9.0 = 2.0 A, so the supply current is 5.0 A, up from the 3.0 A drawn before.",
    },
    {
        "id": "ks4-series-parallel-circuits-s25",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A lamp is connected on its own across a 6.0 V battery. A second identical lamp is then added in series with it. Compare the potential difference across the first lamp in the two cases.",
        "options": [
            "6.0 V on its own and 3.0 V once the second lamp is in series with it",
            "6.0 V in both cases, because the pd of the battery has not changed",
            "3.0 V on its own and 6.0 V once the second lamp is in series with it",
            "6.0 V on its own and 12 V once the second lamp is added to the loop",
        ],
        "correct_index": 0,
        "why": "The supply pd divides between series components, so two identical lamps take half of it each.",
    },
    {
        "id": "ks4-series-parallel-circuits-s26",
        "subtopic_slug": "series-parallel-circuits",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "In the resistor-combination practical a student is told to switch the supply off between readings. Suggest why this instruction is given.",
        "options": [
            "The battery pd rises while it is left switched on, which raises every reading",
            "The resistors warm up as current passes, and a warmer resistor has a higher resistance",
            "The ammeter needs time to fall back to zero before it can be read accurately",
            "The current has to be given time to drain out of the connecting leads",
        ],
        "correct_index": 1,
        "why": "Heating a metallic conductor increases its resistance, so leaving the current on would make later readings drift away from the marked values.",
    },
    {
        "id": "ks4-series-parallel-circuits-h05",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Three lamps of resistance 6.0 Ω, 12 Ω and 12 Ω each have their own path to a 12 V battery. Calculate the resistance of the whole network.",
        "options": [
            "30 Ω",
            "3.0 Ω",
            "10 Ω",
            "6.0 Ω",
        ],
        "correct_index": 1,
        "why": "The branches take 2.0 A, 1.0 A and 1.0 A, so the supply delivers 4.0 A and R = 12 ÷ 4.0 = 3.0 Ω.",
    },
    {
        "id": "ks4-series-parallel-circuits-h06",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 12 V supply feeds two parallel branches. One branch holds a single 4.0 Ω resistor; the other holds a 2.0 Ω resistor in series with a 4.0 Ω resistor. Calculate the current drawn from the supply.",
        "options": [
            "1.2 A",
            "3.0 A",
            "5.0 A",
            "2.0 A",
        ],
        "correct_index": 2,
        "why": "The first branch takes 12 ÷ 4.0 = 3.0 A and the second, of resistance 6.0 Ω, takes 12 ÷ 6.0 = 2.0 A, giving 5.0 A from the supply.",
    },
    {
        "id": "ks4-series-parallel-circuits-h07",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "One branch of a circuit connected across a 9.0 V battery holds a 3.0 Ω resistor in series with a 6.0 Ω resistor. Determine the potential difference across the 6.0 Ω resistor.",
        "options": [
            "9.0 V",
            "3.0 V",
            "0.17 V",
            "6.0 V",
        ],
        "correct_index": 3,
        "why": "The branch has 9.0 V across its 9.0 Ω, so it carries 1.0 A, and the 6.0 Ω resistor takes 1.0 × 6.0 = 6.0 V of that.",
    },
    {
        "id": "ks4-series-parallel-circuits-h08",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two 4.0 Ω heating elements are connected across a 12 V supply, first in series and then in parallel. Determine how many times larger the supply current is in the parallel arrangement.",
        "options": [
            "Twice as large, because each branch gives the supply a second path to drive current through",
            "Four times larger, because the total resistance falls from 8.0 Ω to 2.0 Ω",
            "The same, because the supply pd and the two elements are unchanged",
            "Half as large, because the current divides between the two branches",
        ],
        "correct_index": 1,
        "why": "In series I = 12 ÷ 8.0 = 1.5 A and in parallel I = 12 ÷ 2.0 = 6.0 A, and 6.0 ÷ 1.5 = 4.",
    },
    {
        "id": "ks4-series-parallel-circuits-h09",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Branches of 10 Ω, 20 Ω and 20 Ω are connected in parallel across a 20 V supply. The 10 Ω branch is then replaced by a 5.0 Ω branch. Determine the change in the current drawn from the supply.",
        "options": [
            "It rises by 4.0 A, to a new supply current of 8.0 A",
            "It is unchanged at 4.0 A, because the supply pd has not changed",
            "It rises by 2.0 A, to a new supply current of 6.0 A",
            "It falls by 2.0 A, because a smaller branch resistance takes less current",
        ],
        "correct_index": 2,
        "why": "The currents were 2.0 + 1.0 + 1.0 = 4.0 A and become 4.0 + 1.0 + 1.0 = 6.0 A, a rise of 2.0 A.",
    },
    {
        "id": "ks4-series-parallel-circuits-h10",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student measures the total resistance of two parallel resistors as 3.8 Ω, while the value calculated from the printed markings is 4.0 Ω. Evaluate the most likely explanation.",
        "options": [
            "The printed values carry a tolerance, so the true resistances differ a little from them",
            "The rule for combining resistors in parallel does not apply when the two resistances are unequal",
            "The leads add resistance, which makes a measured total smaller than the calculated one",
            "The resistors heated up, and heating a metal conductor lowers its resistance",
        ],
        "correct_index": 0,
        "why": "A 5% difference is within the tolerance band printed on ordinary resistors, and both of the other effects named would push the measured value the other way.",
    },
    {
        "id": "ks4-series-parallel-circuits-h11",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 60 Ω resistor and a 40 Ω resistor are connected in parallel across a 120 V supply. Determine the total resistance and state how it compares with the smaller of the two resistances.",
        "options": [
            "100 Ω, the sum of the two branch resistances",
            "50 Ω, the mean of the two branch resistances",
            "24 Ω, which is smaller than the 40 Ω branch",
            "40 Ω, the smaller of the two branch resistances",
        ],
        "correct_index": 2,
        "why": "The branches take 2.0 A and 3.0 A, so R = 120 ÷ 5.0 = 24 Ω, below the 40 Ω branch as a parallel total must be.",
    },
    {
        "id": "ks4-series-parallel-circuits-h12",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Network A is two 8.0 Ω resistors in series and network B is two 8.0 Ω resistors in parallel. Each network in turn is joined in series with a 4.0 Ω resistor across a 20 V supply. Compare the supply currents.",
        "options": [
            "1.0 A for network A and 2.5 A for network B",
            "1.0 A for network A and 5.0 A for network B",
            "2.5 A for network A and 1.0 A for network B",
            "1.25 A for network A and 2.5 A for network B",
        ],
        "correct_index": 0,
        "why": "With A the circuit is 16 + 4.0 = 20 Ω giving 1.0 A; with B it is 4.0 + 4.0 = 8.0 Ω giving 2.5 A.",
    },
    {
        "id": "ks4-series-parallel-circuits-h13",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student claims that wiring a house in series would be safer because the total current drawn from the mains would be smaller. Evaluate this claim.",
        "options": [
            "The total current would be smaller, but each appliance would receive only a share of the 230 V and one failure would stop them all",
            "The total current would be smaller, and each appliance would still receive the full 230 V from the supply",
            "The total current would be larger, because resistances add up in a series circuit",
            "The total current would be unchanged, because the mains pd fixes the current in the house",
        ],
        "correct_index": 0,
        "why": "Series wiring does raise the total resistance and so lower the current, but it also splits the 230 V between appliances and makes every appliance depend on all the others.",
    },
    {
        "id": "ks4-series-parallel-circuits-h14",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 9.0 Ω resistor is connected in parallel with an unknown resistor, and the combination has a total resistance of 6.0 Ω. Determine the resistance of the unknown resistor.",
        "options": [
            "3.0 Ω",
            "15 Ω",
            "4.5 Ω",
            "18 Ω",
        ],
        "correct_index": 3,
        "why": "Across 18 V the combination would take 3.0 A and the 9.0 Ω branch 2.0 A, leaving 1.0 A for the unknown branch, so R = 18 ÷ 1.0 = 18 Ω.",
    },
    {
        "id": "ks4-series-parallel-circuits-h15",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student uses a 6 V supply for the series arrangement and a 2 V supply for the parallel arrangement, then compares the two currents. Explain why this comparison is not valid.",
        "options": [
            "The parallel arrangement needs a larger supply pd than the series one before any current passes",
            "The current depends on the supply pd as well as on the arrangement, so the two cannot be compared",
            "Resistance changes with the supply pd, so the marked resistances no longer apply",
            "The ammeter has to be re-zeroed every time the supply pd is changed",
        ],
        "correct_index": 1,
        "why": "Two variables have been changed at once, so any difference in current cannot be attributed to the arrangement alone.",
    },
    {
        "id": "ks4-series-parallel-circuits-h16",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 24 V supply feeds three parallel branches. Two of them have resistances of 24 Ω and 12 Ω, and the supply delivers 7.0 A in total. Determine the resistance of the third branch.",
        "options": [
            "36 Ω",
            "8.0 Ω",
            "4.0 Ω",
            "6.0 Ω",
        ],
        "correct_index": 3,
        "why": "The two known branches take 1.0 A and 2.0 A, leaving 4.0 A for the third, so R = 24 ÷ 4.0 = 6.0 Ω.",
    },
    {
        "id": "ks4-series-parallel-circuits-h17",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 6.0 Ω lamp and a 3.0 Ω lamp are connected in parallel across a 12 V battery. A 2.0 Ω resistor is then connected in series with the battery. Determine the new current in the 6.0 Ω lamp.",
        "options": [
            "2.0 A",
            "1.0 A",
            "3.0 A",
            "1.5 A",
        ],
        "correct_index": 1,
        "why": "The pair behaves as 2.0 Ω, so the circuit is 4.0 Ω and carries 3.0 A; that leaves 6.0 V across the pair, so the 6.0 Ω lamp now takes 1.0 A instead of 2.0 A.",
    },
    {
        "id": "ks4-series-parallel-circuits-h18",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 4.0 Ω resistor and a 6.0 Ω resistor are joined end to end to form one branch of a network, and a single 10 Ω resistor forms a second branch beside it. Determine the total resistance of the network.",
        "options": [
            "20 Ω",
            "10 Ω",
            "5.0 Ω",
            "2.5 Ω",
        ],
        "correct_index": 2,
        "why": "The series branch is 4.0 + 6.0 = 10 Ω, so the network is two equal 10 Ω branches in parallel, giving 5.0 Ω.",
    },
    {
        "id": "ks4-series-parallel-circuits-h19",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two 4.0 Ω resistors in series across a 24 V supply have 12 V across each. A third 4.0 Ω resistor is then connected in parallel with the second one. Determine the new potential difference across the first resistor.",
        "options": [
            "12 V",
            "24 V",
            "16 V",
            "6.0 V",
        ],
        "correct_index": 2,
        "why": "The parallel pair is 2.0 Ω, so the circuit is 6.0 Ω and carries 24 ÷ 6.0 = 4.0 A, putting 4.0 × 4.0 = 16 V across the first resistor.",
    },
    {
        "id": "ks4-series-parallel-circuits-h20",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Three lamps are connected in parallel. One goes out while the other two stay lit, and the ammeter in the main wire reads a smaller current than before. Explain what has happened.",
        "options": [
            "The battery has run down, so it can no longer supply enough current to light all three lamps",
            "The main wire has broken, which stops the current in that one branch only",
            "That lamp's filament has broken, so its branch carries no current and the total falls",
            "The other two lamps have taken the broken lamp's share of the supply pd",
        ],
        "correct_index": 2,
        "why": "Losing one branch removes that branch's current from the total while leaving the other branches with the same pd, so they stay lit and the main current drops.",
    },
    {
        "id": "ks4-series-parallel-circuits-h21",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "In the resistor-combination practical a student repeats each ammeter reading three times and takes a mean. Explain how this improves the investigation.",
        "options": [
            "It removes the systematic error caused by the resistance of the connecting leads",
            "It reduces the effect of random error, so the mean is closer to the true current",
            "It makes the resistors warm up evenly, so that their resistance stays constant",
            "It increases the resolution of the ammeter, so that smaller currents can be read",
        ],
        "correct_index": 1,
        "why": "Repeat readings scatter either side of the true value, so averaging them reduces random error, though it cannot remove a systematic one.",
    },
    {
        "id": "ks4-series-parallel-circuits-h22",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A circuit must draw 0.80 A from a 12 V supply, and only two 30 Ω resistors are available. Determine which arrangement of them is needed.",
        "options": [
            "Series, which gives a total resistance of 60 Ω",
            "Neither, because 0.80 A cannot be obtained from two 30 Ω resistors",
            "Series, because a single loop carries a larger current than two branches",
            "Parallel, which gives a total resistance of 15 Ω",
        ],
        "correct_index": 3,
        "why": "In parallel the pair is 15 Ω and 12 ÷ 15 = 0.80 A, whereas in series the pair is 60 Ω and the current would be only 0.20 A.",
    },
    {
        "id": "ks4-series-parallel-circuits-h23",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 230 V ring main supplies a fridge of resistance 460 Ω, a lamp of resistance 920 Ω and a heater of resistance 115 Ω, all in parallel. Calculate the total current drawn from the mains.",
        "options": [
            "0.15 A",
            "2.50 A",
            "2.75 A",
            "2.00 A",
        ],
        "correct_index": 2,
        "why": "Each appliance has 230 V across it, giving 0.50 A, 0.25 A and 2.00 A, which add to 2.75 A.",
    },
    {
        "id": "ks4-series-parallel-circuits-h24",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Three resistors in a single series loop with a 20 V supply carry a current of 0.50 A. Two of them have resistances of 10 Ω and 18 Ω. Determine the resistance of the third.",
        "options": [
            "12 Ω",
            "40 Ω",
            "28 Ω",
            "68 Ω",
        ],
        "correct_index": 0,
        "why": "The total resistance is 20 ÷ 0.50 = 40 Ω, so the third resistor is 40 − 10 − 18 = 12 Ω.",
    },
    {
        "id": "ks4-series-parallel-circuits-h25",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student predicts that a 5.0 Ω resistor and a 20 Ω resistor in parallel will have a total resistance of 12.5 Ω. Identify the mistake and give the correct total resistance.",
        "options": [
            "They added the two resistances together; the correct total is 25 Ω",
            "They took the mean of the two resistances; the correct total is 4.0 Ω",
            "They used only the larger resistance; the correct total is 20 Ω",
            "They halved the smaller resistance; the correct total is 2.5 Ω",
        ],
        "correct_index": 1,
        "why": "Across 20 V the branches would take 4.0 A and 1.0 A, so R = 20 ÷ 5.0 = 4.0 Ω; 12.5 Ω is the mean of the two, which is never how resistances combine.",
    },
    {
        "id": "ks4-series-parallel-circuits-h26",
        "subtopic_slug": "series-parallel-circuits",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 12 V supply feeds two parallel branches and the ammeter in the main wire reads 1.20 A. One branch contains a 30 Ω resistor. Determine the resistance of the second branch.",
        "options": [
            "10 Ω",
            "30 Ω",
            "7.5 Ω",
            "15 Ω",
        ],
        "correct_index": 3,
        "why": "The 30 Ω branch takes 12 ÷ 30 = 0.40 A, leaving 0.80 A for the second branch, so R = 12 ÷ 0.80 = 15 Ω.",
    },
]
