"""Physics · Forces — the MRB-338 expansion for `upthrust-floating`.
Higher tier throughout, and triple only.

The frozen twelve already own Archimedes' principle stated plainly, the
pressure-difference cause of upthrust, the sink-in-water-float-in-mercury
density comparison, one ρVg calculation in seawater, one in oil, the
apparent-weight subtraction on a newtonmeter, one floating cube's displaced
volume, the "upthrust depends on the brick's mass" correction, the diver's
displaced volume from a loss of apparent weight, the flooded ballast tank,
the aluminium-and-lead equal-volume comparison, and one submerged-fraction
density calculation.

This file works the ground around them: the free-body balance at the
moment of floating (upthrust equals weight, resultant zero) and the
three-way comparison of upthrust, weight and resultant as an object is
lowered in, sinks, or rests on the bottom; the MAXIMUM upthrust available
to a fully submerged object and why exceeding it means sinking; floating
with part of the volume above the surface, including the density ratio in
both directions and the change of waterline between fresh water, sea water
and denser brine; the steel-ship question a pupil finds hardest — a dense
material floating because the shaped hull displaces a large volume; hot-air
balloons and helium balloons as upthrust in a GAS; the Plimsoll line; an
overflow-can measurement; and why upthrust is unchanged by depth once an
object is fully under.

⚠️ The plain arithmetic of a liquid column (p = h ρ g on its own) belongs
to `pressure-in-a-fluid`; here the pressure difference appears only as the
CAUSE of upthrust.
"""

TOPIC = "forces"
SUBJECT = "physics"

QUESTIONS = [
    # ---------------------------------------------------------------- easier
    {
        "id": "ks4-upthrust-floating-e05",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State the direction in which upthrust acts on an object in a fluid.",
        "options": [
            "Vertically upwards",
            "In the direction the object is moving through the fluid at that moment, which is why it slows a sinking object down",
            "Vertically downwards",
            "Horizontally, away from the nearest wall of the container",
        ],
        "correct_index": 0,
        "why": "Upthrust comes from the fluid pressure being greater underneath than on top, so the resulting force always points straight up.",
    },
    {
        "id": "ks4-upthrust-floating-e06",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Write down the condition that holds while an object floats at rest on the surface of a liquid.",
        "options": [
            "The object's weight is greater than the upthrust on it",
            "The object's density matches the density of the liquid exactly, which is the only way it can remain at rest",
            "The upthrust equals the object's weight",
            "The upthrust equals the weight of the whole object plus the liquid",
        ],
        "correct_index": 2,
        "why": "A floating object is in equilibrium, so the upward push from the fluid exactly balances its weight and the resultant force is zero.",
    },
    {
        "id": "ks4-upthrust-floating-e07",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A stone is held fully under water and then released. Its weight is greater than the upthrust on it. Predict what it does.",
        "options": [
            "It hangs where it is, because the two forces are both acting on it",
            "It rises slowly to the surface and floats there",
            "It drifts sideways towards the nearest wall of the container it has been dropped into, and then settles against that wall",
            "It sinks, because the resultant force on it acts downwards",
        ],
        "correct_index": 3,
        "why": "Weight down is larger than upthrust up, so there is a downward resultant force and the stone accelerates towards the bottom.",
    },
    {
        "id": "ks4-upthrust-floating-e08",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "An object of volume 0.050 m³ is held completely under fresh water. Calculate the upthrust on it. (density of water = 1000 kg/m³, g = 10 N/kg)",
        "options": [
            "5000 N",
            "500 N",
            "50 N",
            "20 000 N",
        ],
        "correct_index": 1,
        "why": "Upthrust = ρVg = 1000 × 0.050 × 10 = 500 N, which is the weight of the water pushed aside.",
    },
    {
        "id": "ks4-upthrust-floating-e09",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Give the test, in terms of density, for whether a solid object will float in a liquid.",
        "options": [
            "It floats if it is less dense than the liquid",
            "It floats if it weighs less than one kilogram in air",
            "It floats if it is denser than the liquid, since the extra density is what pushes the liquid out of the way beneath it",
            "It floats if its volume is greater than the liquid's volume",
        ],
        "correct_index": 0,
        "why": "A less dense object displaces its own weight of fluid before it is fully under, so the upthrust can balance its weight.",
    },
    {
        "id": "ks4-upthrust-floating-e10",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Name the quantity of fluid whose weight gives the size of the upthrust.",
        "options": [
            "The fluid left in the container after the object is lowered into it, measured right up to the new surface level",
            "The total fluid in the container",
            "The fluid displaced by the object",
            "The fluid touching the object's upper face",
        ],
        "correct_index": 2,
        "why": "Archimedes' principle: the upthrust equals the weight of the fluid pushed out of the way by the object.",
    },
    {
        "id": "ks4-upthrust-floating-e11",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Swimmers feel lighter in a pool than on the poolside. Account for that.",
        "options": [
            "Upthrust from the water acts upwards and partly balances their weight",
            "The water pushes them along, and that forward push is what takes the weight off their legs as they swim",
            "Gravity is a little weaker down in the water than it is up in the air",
            "Water reduces the swimmer's mass for as long as they stay in it",
        ],
        "correct_index": 0,
        "why": "The weight is unchanged, but the upthrust acts the other way, so the apparent weight supported by the swimmer is much smaller.",
    },
    {
        "id": "ks4-upthrust-floating-e12",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A helium balloon released indoors rises to the ceiling. Explain why in terms of forces.",
        "options": [
            "Warm air currents in the room carry the balloon upwards until it reaches the ceiling and cannot go any higher",
            "Helium has no weight of its own to hold the balloon down",
            "Helium is repelled by the ground beneath the balloon",
            "The upthrust from the air exceeds the balloon's total weight",
        ],
        "correct_index": 3,
        "why": "Air is a fluid, so it exerts upthrust equal to the weight of air displaced; that beats the small weight of helium plus rubber.",
    },
    {
        "id": "ks4-upthrust-floating-e13",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A block floats with part of it standing above the water line. Compare the water displaced with the block's own volume.",
        "options": [
            "The water displaced has the greater volume of the two",
            "They are the same, because the block is in the water",
            "The displaced water has a volume equal to the submerged part only",
            "The displaced water has a volume equal to the part above the surface, since that is the part the water has been pushed away from",
        ],
        "correct_index": 2,
        "why": "Only the part of the block below the surface pushes water aside, so the displaced volume matches the submerged volume.",
    },
    {
        "id": "ks4-upthrust-floating-e14",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State the upthrust on a log of weight 240 N that floats motionless on a lake.",
        "options": [
            "0 N",
            "480 N",
            "120 N",
            "240 N",
        ],
        "correct_index": 3,
        "why": "The log is at rest, so the forces balance and the upthrust must equal its 240 N weight exactly.",
    },
    {
        "id": "ks4-upthrust-floating-e15",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Describe how the water pressure on the top and bottom faces of a submerged cube compare.",
        "options": [
            "The pressure on the bottom face is greater, because it is deeper",
            "The pressure on the top face is greater, because the whole weight of water above the cube presses down on it from directly overhead",
            "The pressures are identical on the two faces",
            "The pressure on the bottom face is greater only in sea water",
        ],
        "correct_index": 0,
        "why": "Pressure rises with depth, so the lower face is pushed up harder than the upper face is pushed down — and that difference is the upthrust.",
    },
    {
        "id": "ks4-upthrust-floating-e16",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A ball of weight 6.0 N is held under water where the upthrust on it is 9.0 N. Calculate the resultant force on the ball at the moment it is let go.",
        "options": [
            "15.0 N downwards",
            "3.0 N upwards",
            "9.0 N upwards",
            "3.0 N downwards",
        ],
        "correct_index": 1,
        "why": "The resultant is 9.0 − 6.0 = 3.0 N, and it acts upwards because the upthrust is the larger force, so the ball rises.",
    },
    {
        "id": "ks4-upthrust-floating-e17",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Identify what happens to the reading on a newtonmeter when the hanging mass is lowered into water.",
        "options": [
            "The reading falls, because upthrust supports part of the weight",
            "The reading is unchanged, because the mass has not changed",
            "The reading rises, because the water adds weight",
            "The reading falls to zero as soon as any part of the mass is below the surface of the water",
        ],
        "correct_index": 0,
        "why": "The upthrust pushes up on the object, so the newtonmeter only has to supply the difference — the apparent weight.",
    },
    {
        "id": "ks4-upthrust-floating-e18",
        "subtopic_slug": "upthrust-floating",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why a cork bobs back up when it is pushed under water and released.",
        "options": [
            "Cork is repelled by water because it does not get wet",
            "Pushing it down squeezes the cork, and it springs back to its own shape again, carrying itself up to the surface as it does so",
            "Under water the upthrust beats its weight, so it rises",
            "The hand transfers energy to the cork as it pushes it down",
        ],
        "correct_index": 2,
        "why": "Cork is much less dense than water, so submerging it displaces far more weight of water than the cork itself weighs.",
    },

    # -------------------------------------------------------------- standard
    {
        "id": "ks4-upthrust-floating-s05",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A steel hull weighing thousands of newtons floats although steel is about eight times denser than water. Resolve the apparent contradiction.",
        "options": [
            "Steel becomes lighter once salt water has begun to corrode it",
            "The hull is hollow, so the shape displaces a huge volume of water and the average density of ship plus air is below that of water",
            "The engines push water downwards hard enough to hold the ship up",
            "Steel is denser than fresh water but less dense than sea water",
        ],
        "correct_index": 1,
        "why": "Floating is decided by the average density of the whole shaped object, not by the density of the material it is made from.",
    },
    {
        "id": "ks4-upthrust-floating-s06",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A block of volume 0.040 m³ and weight 260 N is released fully under fresh water. Determine what it does. (density of water = 1000 kg/m³, g = 10 N/kg)",
        "options": [
            "It sinks, because the 400 N upthrust is smaller than the weight",
            "It floats, because the 400 N upthrust exceeds the 260 N weight",
            "It hangs still, because upthrust and weight are equal",
            "It sinks, because upthrust never acts on an object that is completely below the surface of the water",
        ],
        "correct_index": 1,
        "why": "Upthrust = ρVg = 1000 × 0.040 × 10 = 400 N, which beats the 260 N weight, so the block rises and ends up floating.",
    },
    {
        "id": "ks4-upthrust-floating-s07",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A ship moves from a river out into the sea, where the water is denser. Predict the change in how deeply it sits.",
        "options": [
            "It sits lower, because sea water presses down on the deck",
            "It sits slightly higher, because less volume must be displaced for the same upthrust",
            "Nothing changes, since the ship's weight is the same in both",
            "It sits lower, because the salt dissolved in sea water adds its own weight to the hull as it flows past",
        ],
        "correct_index": 1,
        "why": "The upthrust must still equal the ship's weight, and denser water supplies that weight from a smaller displaced volume.",
    },
    {
        "id": "ks4-upthrust-floating-s08",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A crown of volume 0.0012 m³ hangs from a spring balance and is lowered into water. Calculate the drop in the balance reading. (density of water = 1000 kg/m³, g = 10 N/kg)",
        "options": [
            "12 N",
            "1.2 N",
            "120 N",
            "0.012 N",
        ],
        "correct_index": 0,
        "why": "The fall in reading equals the upthrust: ρVg = 1000 × 0.0012 × 10 = 12 N.",
    },
    {
        "id": "ks4-upthrust-floating-s09",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A sealed tin is lowered deeper and deeper once it is already completely under water. Describe what happens to the upthrust on it.",
        "options": [
            "It grows in proportion to the depth, because the weight of water above the tin increases with every metre it descends",
            "It grows steadily, because the pressure at that depth is greater",
            "It falls, because the water above the tin is squeezed together",
            "It stays the same, because the displaced volume does not change",
        ],
        "correct_index": 3,
        "why": "Both faces feel a higher pressure at greater depth, but the DIFFERENCE between them is unchanged, so ρVg — and the upthrust — stays put.",
    },
    {
        "id": "ks4-upthrust-floating-s10",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "An overflow can is filled to the spout and a pebble is dropped in. The water collected weighs 0.35 N. State the upthrust on the pebble.",
        "options": [
            "It cannot be found without the pebble's mass",
            "0.35 N",
            "0.70 N",
            "0.035 N",
        ],
        "correct_index": 1,
        "why": "The collected water is exactly the water displaced, so by Archimedes' principle its 0.35 N weight is the upthrust.",
    },
    {
        "id": "ks4-upthrust-floating-s11",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A hot-air balloon climbs when the burner is lit. Explain the physics.",
        "options": [
            "Heating the air inside makes it less dense, so the balloon's total weight falls below the upthrust from the surrounding air",
            "The flame pushes downwards on the ground beneath it",
            "Hot air is attracted upwards towards the warmer upper atmosphere",
            "Heating the air raises the pressure inside and that stretches the envelope",
        ],
        "correct_index": 0,
        "why": "The displaced volume of cold outside air is fixed by the envelope, so reducing the weight of the air inside tips the balance upwards.",
    },
    {
        "id": "ks4-upthrust-floating-s12",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A plastic cube of density 600 kg/m³ floats in water of density 1000 kg/m³. Work out the fraction of it below the surface.",
        "options": [
            "0.40",
            "1.67",
            "0.60",
            "0.06",
        ],
        "correct_index": 2,
        "why": "For a floating object the submerged fraction equals the density ratio, 600 ÷ 1000 = 0.60, so three fifths of the cube is under.",
    },
    {
        "id": "ks4-upthrust-floating-s13",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Compare the upthrust on a swimmer floating at the surface with the upthrust on the same swimmer held completely under.",
        "options": [
            "It is smaller at the surface, where only part of the body displaces water",
            "It is larger at the surface, since the surface of the water is where the push upwards from the liquid is at its very strongest",
            "It is the same in both, because the swimmer's weight is unchanged",
            "It is smaller under water, because the water above presses down",
        ],
        "correct_index": 0,
        "why": "Upthrust follows the displaced volume, so fully submerged displaces more and gives the maximum upthrust that body can receive.",
    },
    {
        "id": "ks4-upthrust-floating-s14",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A lump of iron of weight 78 N is lowered into oil, where the upthrust on it is 8.8 N. Determine its apparent weight.",
        "options": [
            "86.8 N",
            "8.8 N",
            "78.0 N",
            "69.2 N",
        ],
        "correct_index": 3,
        "why": "Apparent weight = true weight − upthrust = 78 − 8.8 = 69.2 N.",
    },
    {
        "id": "ks4-upthrust-floating-s15",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Cargo ships carry a painted Plimsoll line on the hull. Suggest the physics it is based on.",
        "options": [
            "It marks the point where the steel of the hull is at its thickest, and so the place where the sea can press hardest on it",
            "It marks how far the ship may safely be loaded down",
            "It records the depth of the water the ship was built in",
            "It shows the level the sea reaches during a normal storm",
        ],
        "correct_index": 1,
        "why": "Adding cargo makes the ship sit lower until the extra displaced water balances it; below the line there is too little hull left to float safely.",
    },
    {
        "id": "ks4-upthrust-floating-s16",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A fishing float of volume 0.000050 m³ is pushed fully under fresh water. Calculate the largest upthrust it can receive. (density = 1000 kg/m³, g = 10 N/kg)",
        "options": [
            "0.050 N",
            "0.50 N",
            "5.0 N",
            "50 N",
        ],
        "correct_index": 1,
        "why": "The maximum upthrust comes when the whole volume is submerged: ρVg = 1000 × 0.000050 × 10 = 0.50 N.",
    },
    {
        "id": "ks4-upthrust-floating-s17",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "An egg lies on the bottom of a glass of tap water, then rises once several spoonfuls of salt are stirred in. Explain the change.",
        "options": [
            "The salt dissolves part of the eggshell, and the lighter egg is then carried up to the surface by the stirring",
            "The stirring pushes the egg upwards each time",
            "The salt raises the water's density, so the upthrust on the egg grows until it exceeds the egg's weight",
            "The salt reduces the egg's weight by drying out its contents",
        ],
        "correct_index": 2,
        "why": "Upthrust = ρ_fluid × V × g, so raising the liquid's density raises the upthrust on the unchanged egg until it floats.",
    },
    {
        "id": "ks4-upthrust-floating-s18",
        "subtopic_slug": "upthrust-floating",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A sheet of metal foil sinks, but the same foil folded into an open box floats. Give the reason.",
        "options": [
            "The folds trap water and hold the box on the surface",
            "Folding the foil lowers the weight of metal in it",
            "Folding raises the volume the shape displaces before it is fully under, and the average density of metal plus enclosed air drops below the water's",
            "A flat sheet has less surface area for the water to push on",
        ],
        "correct_index": 2,
        "why": "The foil's weight is unchanged, but a box shape displaces enough water to give an upthrust that matches it before the box goes under.",
    },

    # ---------------------------------------------------------------- harder
    {
        "id": "ks4-upthrust-floating-h05",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A cube of side 0.10 m and weight 12 N is lowered slowly into water until just submerged. (density of water = 1000 kg/m³, g = 10 N/kg) Determine the force in the supporting string at that point.",
        "options": [
            "22 N",
            "12 N",
            "2.0 N",
            "10 N",
        ],
        "correct_index": 2,
        "why": "The volume is 0.0010 m³, so the upthrust is 1000 × 0.0010 × 10 = 10 N and the string carries only 12 − 10 = 2.0 N.",
    },
    {
        "id": "ks4-upthrust-floating-h06",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A sealed drum rests on the bed of a lake. Compare the upthrust, its weight and the push from the lake bed.",
        "options": [
            "Upthrust equals the weight, and the bed exerts no push on it at all",
            "The bed's push is larger than the weight, which is why the drum stays still instead of sinking further into the mud",
            "Upthrust on its own holds the drum up, and the lake bed is irrelevant",
            "Weight is greater than upthrust, and the bed supplies the rest",
        ],
        "correct_index": 3,
        "why": "The drum sank, so its weight beats the maximum upthrust; the lake bed makes up the difference, giving zero resultant at rest.",
    },
    {
        "id": "ks4-upthrust-floating-h07",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "An object of mass 4.5 kg has a volume of 0.0030 m³. Decide whether it floats in water and justify the answer numerically. (density of water = 1000 kg/m³)",
        "options": [
            "It floats, because 4.5 kg is a small mass",
            "It sinks: its density is 1500 kg/m³, which is above the water's",
            "It floats, because its volume is smaller than one cubic metre",
            "It sinks, because its density works out at 0.00067 kg/m³, and that is far below the density of the water around it",
        ],
        "correct_index": 1,
        "why": "ρ = m ÷ V = 4.5 ÷ 0.0030 = 1500 kg/m³, and anything denser than the fluid it sits in will sink.",
    },
    {
        "id": "ks4-upthrust-floating-h08",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A pupil argues that upthrust must grow as an object is taken deeper, since the pressure down there is greater. Evaluate the argument.",
        "options": [
            "It holds, because the deeper water presses harder on the base",
            "It holds once the object is more than ten metres down",
            "It fails: both faces feel the extra pressure, so the difference between them — and so the upthrust — is unchanged",
            "It fails, because pressure has nothing to do with upthrust",
        ],
        "correct_index": 2,
        "why": "Upthrust comes from the pressure DIFFERENCE across the object, which depends on its height in the fluid, not on how deep it is.",
    },
    {
        "id": "ks4-upthrust-floating-h09",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A raft of area 3.0 m² and weight 1800 N floats on fresh water. Calculate the depth of raft below the waterline. (density of water = 1000 kg/m³, g = 10 N/kg)",
        "options": [
            "0.60 m",
            "0.060 m",
            "6.0 m",
            "0.18 m",
        ],
        "correct_index": 1,
        "why": "Floating means upthrust = 1800 N, so the displaced volume is 1800 ÷ 10 000 = 0.18 m³, and the depth is 0.18 ÷ 3.0 = 0.060 m.",
    },
    {
        "id": "ks4-upthrust-floating-h10",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A foam buoy sits in brine of density 1200 kg/m³, with exactly 75% of it under the waterline and the rest showing above. Work out the density of the foam.",
        "options": [
            "1600 kg/m³",
            "300 kg/m³",
            "900 kg/m³",
            "1200 kg/m³",
        ],
        "correct_index": 2,
        "why": "The submerged fraction equals the density ratio, so ρ = 0.75 × 1200 = 900 kg/m³.",
    },
    {
        "id": "ks4-upthrust-floating-h11",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A diver adds lead to a weight belt until they hover motionless in mid-water. Describe the force condition that has been reached.",
        "options": [
            "The total weight of diver and lead now equals the upthrust, so the resultant force is zero",
            "The lead has cancelled the upthrust entirely, leaving no upward push at all",
            "The diver's density is now above the water's, which is what stops the slow drift upwards towards the surface",
            "Weight now slightly exceeds the upthrust, and the difference is taken up by the water",
        ],
        "correct_index": 0,
        "why": "Hovering is equilibrium, so the upthrust exactly balances the combined weight — neutral buoyancy, with average density equal to the water's.",
    },
    {
        "id": "ks4-upthrust-floating-h12",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A boulder weighing 900 N in air weighs 560 N when hung fully under water. Determine its volume. (density of water = 1000 kg/m³, g = 10 N/kg)",
        "options": [
            "0.090 m³",
            "0.146 m³",
            "0.056 m³",
            "0.034 m³",
        ],
        "correct_index": 3,
        "why": "The upthrust is the loss of apparent weight, 900 − 560 = 340 N, so V = 340 ÷ (1000 × 10) = 0.034 m³.",
    },
    {
        "id": "ks4-upthrust-floating-h13",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Assess the claim that a large ship floats because its enormous weight pushes the water down and the water pushes back just as hard.",
        "options": [
            "It is right, and the push of the hull on the water and the push of the water on the hull are an interaction pair under Newton's third law",
            "It is right, but only while the ship is moving forwards",
            "It is wrong, since water cannot push back on anything above it",
            "It is wrong: upthrust is set by the weight of water displaced",
        ],
        "correct_index": 3,
        "why": "An interaction pair is not the explanation here — the size of the upthrust is fixed by how much water the hull pushes aside.",
    },
    {
        "id": "ks4-upthrust-floating-h14",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "An ice cube floats in a glass of water filled to the brim. Predict the water level once the ice has melted completely.",
        "options": [
            "It stays level, as the meltwater fills the displaced volume",
            "It overflows, because ice takes up more room than the same mass of water does, so melting releases that extra volume into the glass",
            "It drops, because ice is less dense than liquid water",
            "It overflows, because melting adds extra water to the glass",
        ],
        "correct_index": 0,
        "why": "A floating cube displaces its own weight of water, and that weight of meltwater takes up exactly the volume the cube had pushed aside.",
    },
    {
        "id": "ks4-upthrust-floating-h15",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A balloon of volume 2.0 m³ is filled with helium. Air has density 1.2 kg/m³ and the balloon plus helium weighs 12 N. Determine the resultant force on it. (g = 10 N/kg)",
        "options": [
            "24 N upwards",
            "12 N downwards",
            "36 N upwards",
            "12 N upwards",
        ],
        "correct_index": 3,
        "why": "The upthrust from the air is 1.2 × 2.0 × 10 = 24 N, so the resultant is 24 − 12 = 12 N acting upwards.",
    },
    {
        "id": "ks4-upthrust-floating-h16",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Two balls of identical volume, one hollow and one solid, are both held fully under water on strings. Compare the tensions in the strings.",
        "options": [
            "The solid ball's string is under more tension, because both receive the same upthrust but the solid ball weighs more",
            "The two tensions are equal, because the upthrusts are equal",
            "The hollow ball's string is under more tension, since a hollow shape is pushed upwards harder by the water surrounding it",
            "Neither string is under tension while the balls are below the surface",
        ],
        "correct_index": 0,
        "why": "Upthrust depends on displaced volume only, so it is the same for both; the heavier ball leaves a larger unbalanced weight for its string.",
    },
    {
        "id": "ks4-upthrust-floating-h17",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A wooden block floats in water, then the same block is placed in oil of density 800 kg/m³. Deduce what happens to the fraction submerged.",
        "options": [
            "It falls, because oil is thicker and holds the block up better",
            "It is unchanged, because the block's own density has not altered",
            "The block sinks to the bottom of the oil straight away",
            "A larger fraction sinks below the surface, because the less dense oil must be displaced in greater volume to match the weight",
        ],
        "correct_index": 3,
        "why": "The submerged fraction is ρ_block ÷ ρ_fluid, so a smaller fluid density means a bigger fraction under — unless the block is denser than the oil, when it sinks.",
    },
    {
        "id": "ks4-upthrust-floating-h18",
        "subtopic_slug": "upthrust-floating",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A submarine at rest on the surface pumps water out of its ballast tanks. Deduce the effect and give the reason.",
        "options": [
            "It sits lower, because pumping uses energy from the hull",
            "It sits higher, because its weight falls while the hull's volume stays the same",
            "It stays exactly where it is, because the water moved was already part of the vessel and so the total mass of the submarine is unchanged",
            "It sits higher, because the empty tanks make the hull larger",
        ],
        "correct_index": 1,
        "why": "Emptying the tanks removes mass without altering the external volume, so less hull needs to be under the water for upthrust to match the weight.",
    },
]
