"""Physics · Forces — the MRB-338 expansion, subtopic `free-body-diagrams`.

The baseline twelve already own the "every force acting ON the object" rule,
the downward weight arrow, arrow length as magnitude, a ladder against a
smooth wall, a crate dragged at constant velocity, a rising balloon, a level
car's two resultants, a hanging box, the mislabelled 'force of the car on the
road', a ball at the top of its flight, a sledge pulled at 40°, and a
three-force equilibrium.

This file takes the DRAWING CONVENTIONS the twelve leave untouched — arrows
from one point, labelling, a body reduced to a dot or a box, what the
direction of an arrow represents — and then works hard at the question the
baseline only opens: WHICH BODY a force belongs to. Book and table, swimmer
and water, hammer and nail, rocket and exhaust gases, magnet and pin are all
worked as interaction pairs whose two halves go on two different diagrams.
Beyond that it adds a run of described diagrams to read equilibrium from
(terminal velocity, a parachute just opened, a lift under acceleration, level
flight, a rough slope, a humpback bridge, a block held against a wall), the
classic invented arrows ('the force of motion', a centripetal force added on
top of the real forces, a double-counted parachute pull), resolution into
components, and the closed tip-to-tail triangle.

⚠️ Every scenario here is described IN WORDS — arrow directions, arrow
lengths and which body is chosen — because nothing renders a picture.
"""

TOPIC = "forces"
SUBJECT = "physics"

QUESTIONS = [
    {
        "id": "ks4-free-body-diagrams-e05",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State where the tails of the arrows are placed on a free body diagram.",
        "options": [
            "Spread evenly around the outside edge of the object so that none of them overlap one another",
            "All at a single point that stands for the whole of the object",
            "At the point where the object touches the ground",
            "Wherever there is room on the page",
        ],
        "correct_index": 1,
        "why": "The body is reduced to one point and every force is drawn acting from that point, which makes the resultant easy to see.",
    },
    {
        "id": "ks4-free-body-diagrams-e06",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain how a complicated object such as a lorry is usually represented on a free body diagram.",
        "options": [
            "By a detailed outline of the lorry, so that each force can be drawn on the correct part",
            "By a full scale drawing of the lorry, measured out carefully on graph paper first",
            "By a sketch of the road, since the road is what supplies most of the forces involved",
            "By a dot or a simple box, because the shape of the lorry does not alter the forces on it",
        ],
        "correct_index": 3,
        "why": "The diagram is about the forces, not the shape, so the object is reduced to a dot or a plain rectangle.",
    },
    {
        "id": "ks4-free-body-diagrams-e07",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State what should be written beside each arrow on a free body diagram.",
        "options": [
            "The name of the force, and its size in newtons where that is known",
            "The mass of the object in kilograms, repeated next to each of the arrows on the page",
            "The speed at which the object is travelling at that moment in the motion",
            "Nothing needs writing",
        ],
        "correct_index": 0,
        "why": "An unlabelled arrow says nothing; naming the force and quoting its size in newtons is what makes the diagram usable.",
    },
    {
        "id": "ks4-free-body-diagrams-e08",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A book lies still on a table. Its free body diagram has two arrows of equal length, one pointing down and one pointing up. Name the upward one.",
        "options": [
            "The weight of the table, which is pressing upwards against the underside of the book",
            "Air resistance, which pushes upwards on anything that is sitting still on a horizontal surface",
            "The normal contact force, which is the push that the table gives back up through the book",
            "Upthrust from the air surrounding the book",
        ],
        "correct_index": 2,
        "why": "A surface pushes back at right angles to itself on whatever rests on it, and that push is the normal contact force.",
    },
    {
        "id": "ks4-free-body-diagrams-e09",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Give the direction of the normal contact force exerted by a horizontal floor on a crate standing on it.",
        "options": [
            "Sideways along the floor, in whichever direction the crate would slide if it were pushed",
            "Downwards, in the same direction as the weight of the crate is acting on the same diagram",
            "Along the diagonal of the crate, running from its bottom corner up towards the opposite top corner",
            "Vertically upwards",
        ],
        "correct_index": 3,
        "why": "A normal contact force is perpendicular to the surface that produces it, and a horizontal floor therefore pushes straight up.",
    },
    {
        "id": "ks4-free-body-diagrams-e10",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A skydiver is falling through the air before the parachute is opened. Name the upward arrow on the skydiver's free body diagram.",
        "options": [
            "The normal contact force, which the air supplies to the skydiver all the while the fall is going on",
            "Air resistance, which always acts against the direction in which the skydiver is falling",
            "Upthrust, which is the buoyancy force the atmosphere provides on the way down",
            "Tension, because the harness is pulling upwards on the skydiver's shoulders",
        ],
        "correct_index": 1,
        "why": "Air resistance is a frictional drag force that always acts against the direction of motion, so for a falling skydiver it points upwards.",
    },
    {
        "id": "ks4-free-body-diagrams-e11",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A rowing boat floats motionless on a still lake. Name the upward force on its free body diagram.",
        "options": [
            "Upthrust from the water the hull has pushed aside",
            "The normal contact force from the bed of the lake, transmitted up through the water",
            "The weight of the water",
            "Tension",
        ],
        "correct_index": 0,
        "why": "The water pushes up on the boat with an upthrust equal to the weight of the water the hull displaces.",
    },
    {
        "id": "ks4-free-body-diagrams-e12",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A broken-down car is towed forward by a straight rope. Name the forward force that the rope puts on the car.",
        "options": [
            "The weight of the rope, which acts along its length and drags the car along behind it",
            "The normal contact force of the rope, which acts at right angles to the road surface below it",
            "Tension",
            "Friction from the rope, which pulls the car towards the vehicle at the front",
        ],
        "correct_index": 2,
        "why": "A rope that is being stretched pulls inwards at both ends, and that pull along the rope is called tension.",
    },
    {
        "id": "ks4-free-body-diagrams-e13",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State what the direction an arrow points in tells you about the force it represents.",
        "options": [
            "How many newtons the force is worth, since a steeper arrow means a much stronger push",
            "How long the force has been acting on the object in question",
            "Which way the force acts, that is, its line of action",
            "Which of the forces on the diagram was drawn first",
        ],
        "correct_index": 2,
        "why": "Length carries the size of a force and direction carries its line of action; the two pieces of information are kept separate.",
    },
    {
        "id": "ks4-free-body-diagrams-e14",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Decide whether the pull that a hanging pendulum bob exerts on the Earth belongs on the bob's free body diagram.",
        "options": [
            "No, because that force acts on the Earth rather than on the bob, so it goes on the Earth's diagram",
            "Yes, because that pull is part of the same interaction pair",
            "Yes, because it is a gravitational force and every gravitational force is drawn",
            "Yes, provided it is drawn shorter than the weight arrow",
        ],
        "correct_index": 0,
        "why": "A free body diagram carries only the forces acting ON the chosen body; the partner force in the pair acts on the other body entirely.",
    },
    {
        "id": "ks4-free-body-diagrams-e15",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A lamp hangs at rest from the ceiling on one vertical cord. Count the arrows needed on its free body diagram.",
        "options": [
            "Three, on the grounds that the ceiling, the cord and the Earth each supply one force of their own to it",
            "One, because a hanging lamp has just its weight pulling downwards on it as it hangs there",
            "Four, one for each of the compass directions the lamp could possibly be pulled towards",
            "Two",
        ],
        "correct_index": 3,
        "why": "The lamp has its weight acting downwards and the tension in the cord acting upwards, and at rest those two are equal.",
    },
    {
        "id": "ks4-free-body-diagrams-e16",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A magnet is held a short distance above a loose steel pin and the pin lifts up. Decide whether the magnetic force appears on the pin's diagram.",
        "options": [
            "No, because the magnet is not touching the pin, and just contact forces are ever drawn on a diagram of this kind",
            "Yes, drawn upwards from the pin, because it is one of the forces that is acting on the pin itself",
            "No, because magnetism is a property of the magnet rather than a force acting on anything",
            "Yes, but drawn on the magnet's diagram instead, since the magnet is the object producing it",
        ],
        "correct_index": 1,
        "why": "Non-contact forces belong on the diagram just as contact forces do; what matters is that the force acts on the chosen body.",
    },
    {
        "id": "ks4-free-body-diagrams-e17",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "An apple falls from a branch and air resistance on it is small enough to ignore. Count the arrows on its free body diagram.",
        "options": [
            "Two, one for the weight pulling down and one for the branch still pulling upwards on it",
            "Three, because gravity, motion and acceleration would each need an arrow of their own drawing in",
            "One",
            "None, because an apple in mid-air has nothing touching it to supply a force",
        ],
        "correct_index": 2,
        "why": "Once it has left the branch nothing touches the apple, and air resistance is being ignored, so only its weight is drawn.",
    },
    {
        "id": "ks4-free-body-diagrams-e18",
        "subtopic_slug": "free-body-diagrams",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A free body diagram shows exactly two arrows of the same length pointing in opposite directions. State the resultant force.",
        "options": [
            "Zero, because two equal forces in opposite directions cancel one another out completely",
            "Twice the size of either arrow, because the two of them are added together end to end",
            "Equal to the length of one of the two arrows that have been drawn on the diagram",
            "Impossible to tell without being told the mass of the object that was chosen",
        ],
        "correct_index": 0,
        "why": "Equal and opposite forces on the same body add to nothing, so the body stays at rest or keeps a constant velocity.",
    },
    {
        "id": "ks4-free-body-diagrams-s05",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A book rests on a table. Identify the force that belongs on the TABLE's free body diagram rather than on the book's.",
        "options": [
            "The upward push of the table on the book, which is the force holding the book where it is at the moment",
            "The downward push that the book itself exerts on the flat upper surface of the table",
            "The weight of the book, which acts downwards from the centre of mass of the book itself",
            "The air resistance acting on the book",
        ],
        "correct_index": 1,
        "why": "Book-on-table and table-on-book are an interaction pair, and each half is drawn on the body it acts on, never on both.",
    },
    {
        "id": "ks4-free-body-diagrams-s06",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A swimmer pushes the water backwards with her hands and moves forwards. Identify the arrow that belongs on the swimmer's diagram.",
        "options": [
            "The backward push of her hands on the water, drawn pointing behind her as she goes along",
            "Both halves of the pair, on the grounds that the two forces are equal in size and opposite in direction",
            "Neither of the two, because the swimmer and the water are moving at the same time",
            "The forward push that the water gives back to the swimmer as she swims",
        ],
        "correct_index": 3,
        "why": "The swimmer pushes the water back and the water pushes her forward; only the force ON the swimmer goes on her diagram.",
    },
    {
        "id": "ks4-free-body-diagrams-s07",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A rocket engine throws hot exhaust gases downwards and the rocket climbs. Determine which force is drawn upwards on the rocket's diagram.",
        "options": [
            "The downward push of the rocket on the exhaust gases, since producing that is what the engine is there for",
            "The weight of the exhaust gases, which is smaller than the weight of the rocket that carries them",
            "The upward push that the exhaust gases give back to the rocket as they are thrown out",
            "The upthrust of the surrounding air",
        ],
        "correct_index": 2,
        "why": "The two pushes are an interaction pair acting on different bodies; the rocket's own diagram carries only the gases' push on it.",
    },
    {
        "id": "ks4-free-body-diagrams-s08",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A skydiver has reached terminal velocity. Describe the two arrows on the free body diagram at that moment.",
        "options": [
            "Equal arrows, one up and one down",
            "A long downward weight arrow and a short upward drag arrow, since the skydiver is still moving downwards all the time",
            "A short downward weight arrow and a long upward drag arrow, which is what brought the fall to a steady speed",
            "A single downward weight arrow, because drag disappears once a steady speed has been reached",
        ],
        "correct_index": 0,
        "why": "Terminal velocity is constant velocity, so the resultant is zero and the drag arrow has grown until it matches the weight exactly.",
    },
    {
        "id": "ks4-free-body-diagrams-s09",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Immediately after a parachute opens, the falling parachutist slows sharply. Compare the arrow lengths on the diagram at that instant.",
        "options": [
            "The weight arrow is drawn longer than the drag arrow, which is why the fall is slowing down so sharply",
            "The drag arrow is drawn longer than the weight arrow, so the resultant force on the parachutist points upwards",
            "The two arrows are drawn the same length as one another, because the parachute has now opened fully",
            "Just a drag arrow is drawn, because the parachute cancels the weight of the parachutist out",
        ],
        "correct_index": 1,
        "why": "Opening the canopy multiplies the drag, so for a while drag exceeds weight, the resultant points up, and the downward speed falls.",
    },
    {
        "id": "ks4-free-body-diagrams-s10",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A car speeds up along a straight level road. Four arrows are drawn on its diagram. Describe the horizontal pair.",
        "options": [
            "The driving force arrow and the resistive force arrow are exactly the same length as each other here",
            "The resistive force arrow is drawn the longer of the two, because the road and the air are both opposing it",
            "Just a driving force arrow is drawn, because resistive forces vanish once a car is speeding up",
            "The driving force arrow is drawn longer than the total resistive force arrow that opposes it",
        ],
        "correct_index": 3,
        "why": "Speeding up needs a resultant in the direction of travel, so the driving force must be drawn longer than the total resistance.",
    },
    {
        "id": "ks4-free-body-diagrams-s11",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A lift is accelerating upwards from rest. Compare the tension arrow with the weight arrow on the free body diagram of the lift car.",
        "options": [
            "The tension arrow is drawn longer than the weight arrow beneath it on the same diagram",
            "The weight arrow is the longer, which is what gives the lift the upward acceleration it needs at the start",
            "The two arrows are the same length, because the cable is holding the whole of the lift car",
            "No weight arrow is drawn while the lift is moving upwards away from the ground floor",
        ],
        "correct_index": 0,
        "why": "An upward acceleration needs an upward resultant, and the only upward force on the car is the tension, so tension must exceed weight.",
    },
    {
        "id": "ks4-free-body-diagrams-s12",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A lift descends at a steady speed. Compare the two vertical arrows on its free body diagram.",
        "options": [
            "The weight arrow is the longer of the pair, on the grounds that the lift car is travelling downwards at the time",
            "The tension arrow is the longer of the pair, because the cable is having to hold the lift back",
            "They are equal",
            "No arrows at all are needed while a lift happens to be travelling at a steady speed inside its shaft",
        ],
        "correct_index": 2,
        "why": "Steady speed in a straight line means zero resultant, whichever way the lift happens to be moving, so tension equals weight.",
    },
    {
        "id": "ks4-free-body-diagrams-s13",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "An aeroplane cruises in level flight at a constant speed. Four arrows are drawn for its free body diagram. State the relationships between them.",
        "options": [
            "Lift is drawn larger than weight, and thrust is drawn larger than drag as well",
            "Just lift and weight are needed, because thrust and drag cancel and so may be left out",
            "Thrust is drawn larger than drag while lift and weight are drawn equal",
            "Lift is drawn equal to weight and thrust is drawn equal to drag, so both resultants come to zero",
        ],
        "correct_index": 3,
        "why": "Constant velocity means the resultant is zero both vertically and horizontally, so each opposing pair is drawn the same length.",
    },
    {
        "id": "ks4-free-body-diagrams-s14",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A hammer drives a nail into a plank. Determine which force belongs on the free body diagram of the nail.",
        "options": [
            "The push of the nail back on the hammer head, drawn upwards from the point where they meet",
            "The downward push that the hammer head gives the nail",
            "The weight of the hammer, drawn downwards, on the grounds that it is the hammer doing the driving here",
            "Nothing, because the nail is not moving by itself",
        ],
        "correct_index": 1,
        "why": "Hammer-on-nail and nail-on-hammer are an interaction pair, and the nail's own diagram carries only the force the hammer exerts on it.",
    },
    {
        "id": "ks4-free-body-diagrams-s15",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A crate stays still while two horizontal ropes pull it in opposite directions with 250 N each. Describe the horizontal arrows.",
        "options": [
            "One arrow of 500 N, found by adding the two rope tensions together on the grounds that both are pulling",
            "Two arrows of 125 N each, because the single crate has to share the pull between the two ropes",
            "Two arrows of 250 N pointing in opposite directions",
            "No horizontal arrows are drawn, since the crate is not going anywhere while it stays still",
        ],
        "correct_index": 2,
        "why": "Both tensions act on the crate and both are drawn; they are equal and opposite, which is why the resultant is zero and it stays put.",
    },
    {
        "id": "ks4-free-body-diagrams-s16",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "figure": "ks4-fig-free-body-sign-40n",
        "text": "The diagram is the free body diagram for a hanging sign. Deduce the state of the sign.",
        "options": [
            "It is in equilibrium, so it is either at rest or else moving at a constant velocity",
            "It is accelerating downwards at 9.8 m/s², on the grounds that its weight has been drawn on the diagram",
            "It is speeding up, because there are two forces acting on it rather than just the one",
            "The diagram cannot be read without knowing the mass of the sign in kilograms first",
        ],
        "correct_index": 0,
        "why": "The two forces are equal in size and opposite in direction, so the resultant force is zero. A zero resultant is what equilibrium means: the sign is at rest or moving at a constant velocity.",
    },
    {
        "id": "ks4-free-body-diagrams-s17",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A puck glides across level ice at a constant velocity, with friction small enough to ignore. Describe its free body diagram.",
        "options": [
            "A forward arrow that keeps it going, together with a weight arrow and a normal contact force arrow",
            "A weight arrow downwards and a normal contact force arrow upwards, equal in length, with nothing horizontal at all",
            "A weight arrow and nothing else, because the ice is too slippery to exert a force on the puck",
            "Four equal arrows, one up, one down and one in each of the two horizontal directions of travel",
        ],
        "correct_index": 1,
        "why": "Nothing keeps a moving object moving; with friction ignored the only forces are the vertical pair, which balance.",
    },
    {
        "id": "ks4-free-body-diagrams-s18",
        "subtopic_slug": "free-body-diagrams",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A block slides down a rough slope at a steady speed. Determine the set of forces on the block's free body diagram.",
        "options": [
            "Weight, a normal contact force and a friction arrow pointing down the slope in the direction it slides",
            "Weight by itself, because a sliding block has already left the surface it was resting upon",
            "Weight and friction, with no normal contact force, because the slope is not a horizontal one",
            "Weight, a normal contact force, and friction always acting up the slope",
        ],
        "correct_index": 3,
        "why": "Friction opposes the sliding, so it points up the slope; the normal contact force is perpendicular to the slope surface.",
    },
    {
        "id": "ks4-free-body-diagrams-h05",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "On a diagram of a ball whirled on a string, a student draws the string tension towards the centre and adds a separate centripetal force arrow beside it. Criticise this.",
        "options": [
            "The tension IS the centripetal force here, so drawing both counts the same force twice over",
            "The centripetal force should point outwards, away from the centre of the circle",
            "Tension does not act on a whirling ball, so the centripetal arrow is the correct one",
            "Nothing is wrong, because a ball moving in a circle does need both of those arrows drawn",
        ],
        "correct_index": 0,
        "why": "'Centripetal' names the job a force is doing, not an extra force; here the string's tension is the force doing that job.",
    },
    {
        "id": "ks4-free-body-diagrams-h06",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A trolley is given a shove and then coasts along a bench. A student draws a forward arrow labelled 'the force of motion'. Evaluate the diagram.",
        "options": [
            "It is correct, because something has to keep on pushing the trolley along or it would come to a stop immediately",
            "It is correct, provided that arrow is drawn shorter than the friction arrow pointing the other way",
            "It is wrong: the hand stopped acting on the trolley at the moment of release, so no forward force is left",
            "It is wrong, because the arrow should have been drawn backwards along the bench instead of forwards",
        ],
        "correct_index": 2,
        "why": "Motion is not a force. Once contact ends the only horizontal force left is friction, which is why the trolley slows down.",
    },
    {
        "id": "ks4-free-body-diagrams-h07",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A 120 N pull acts at 30° above the horizontal. Determine its horizontal component. (cos 30° = 0.866, sin 30° = 0.500)",
        "options": [
            "139 N",
            "104 N",
            "60 N",
            "120 N",
        ],
        "correct_index": 1,
        "why": "The horizontal component is F cos 30° = 120 × 0.866 = 104 N; the 60 N value is the vertical component instead.",
    },
    {
        "id": "ks4-free-body-diagrams-h08",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A box of weight 200 N sits on a slope at 25° to the horizontal. Determine the component of its weight acting down the slope. (sin 25° = 0.423, cos 25° = 0.906)",
        "options": [
            "181 N, taking the component parallel to the slope to be the weight multiplied by cos 25° instead",
            "200 N, because the whole of the weight acts down the slope once the box is on an incline",
            "473 N, dividing the weight by sin 25° rather than multiplying the two together",
            "84.6 N, which is the weight multiplied by the sine of the angle of the slope",
        ],
        "correct_index": 3,
        "why": "The component along the slope is W sin 25° = 200 × 0.423 = 84.6 N; W cos 25° is the component pressing into the surface.",
    },
    {
        "id": "ks4-free-body-diagrams-h09",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "figure": "ks4-fig-force-grid-ring-8n-6n",
        "text": "A small ring is in equilibrium under three forces. The diagram shows two of them, drawn to scale. Determine the third force.",
        "options": [
            "14 N, acting down and to the left, on the grounds that the two known forces simply add together arithmetically",
            "2 N, acting down and to the left, from taking the smaller known force away from the larger one",
            "10 N, down and to the left",
            "10 N, acting up and to the right, matching the resultant of the two forces already on the diagram",
        ],
        "correct_index": 2,
        "why": "The two forces shown have a resultant of √(8² + 6²) = 10 N, pointing up and to the right; a scale drawing gives the same. For equilibrium the third force must cancel it: 10 N, down and to the left.",
    },
    {
        "id": "ks4-free-body-diagrams-h10",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A lawnmower is pushed by a handle that slopes downwards, so part of the push acts into the ground. Predict the effect on the normal contact force.",
        "options": [
            "It rises, because the ground now has to balance the weight and the downward part of the push as well",
            "It falls, because some of the push is being used up going forwards instead of downwards",
            "It stays the same, because a normal contact force depends just on the weight of the mower",
            "It falls away to zero as soon as any part of the push is directed into the ground beneath the mower itself",
        ],
        "correct_index": 0,
        "why": "The vertical arrows must still balance, so the floor's push has to match weight plus the downward component, which also raises friction.",
    },
    {
        "id": "ks4-free-body-diagrams-h11",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A car drives over the top of a humpback bridge, and its path curves downwards there. Compare the sizes of the weight and the normal contact force on the car at the very top.",
        "options": [
            "The normal contact force is larger than the weight at the top of the hump",
            "There is no normal contact force at the very top, because the car is momentarily leaving the road surface",
            "The two forces are equal, on the grounds that the car is still in contact with the road all the way over",
            "The weight is larger than the normal contact force right at the top of the hump",
        ],
        "correct_index": 3,
        "why": "At the top the car is moving along a curve whose centre is below it, so its velocity is changing and its acceleration, and therefore the resultant force, points downwards. So the weight must be larger than the normal contact force.",
    },
    {
        "id": "ks4-free-body-diagrams-h12",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A conker is swung on a string in a horizontal circle at a steady speed. State the direction of the resultant force on it.",
        "options": [
            "Along the direction it is travelling, which is what keeps its speed steady as it goes round",
            "Towards the centre of the circle, along the string and inwards towards the hand holding it",
            "Outwards, away from the centre, which is the way the conker seems to be pulling on the hand",
            "Zero, because the conker is going round at a steady speed rather than speeding up or slowing",
        ],
        "correct_index": 1,
        "why": "Steady speed but changing direction is still acceleration, and that acceleration — so the resultant — is directed at the centre.",
    },
    {
        "id": "ks4-free-body-diagrams-h13",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A satellite circles the Earth well above the atmosphere. Count the arrows its free body diagram needs.",
        "options": [
            "One, its weight, drawn pointing straight towards the centre of the Earth far below it",
            "Two: one for its weight, and one for the forward thrust that keeps it moving around its orbit",
            "Three: its weight, a forward thrust, and an outward force balancing out the pull of the planet",
            "None, because a satellite in orbit is weightless and so has nothing acting upon it",
        ],
        "correct_index": 0,
        "why": "Nothing touches the satellite and there is no atmosphere to speak of, so gravity is the only force — and it is the centripetal force.",
    },
    {
        "id": "ks4-free-body-diagrams-h14",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A passenger stands on the floor of a lift that is accelerating downwards. Compare the floor's push with the passenger's weight.",
        "options": [
            "The push of the floor is drawn longer than the weight arrow, which is why the passenger feels light",
            "The push of the floor is drawn equal to the weight, on the grounds that the passenger stands on it throughout",
            "The push of the floor is drawn shorter than the weight arrow standing beside it",
            "No push from the floor is drawn while a lift is accelerating downwards inside its shaft",
        ],
        "correct_index": 2,
        "why": "Accelerating downwards needs a downward resultant, so the upward push from the floor must be smaller than the downward weight.",
    },
    {
        "id": "ks4-free-body-diagrams-h15",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "One arrow on a book's free body diagram reads 'the table pushes up on the book'. Identify its interaction partner and say where that partner is drawn.",
        "options": [
            "'The weight of the book', drawn downwards on this very same diagram of the book",
            "'The book pushes down on the table', and that one is drawn on the free body diagram of the table instead",
            "'The Earth pulls the book down', drawn on the diagram of the book alongside the first arrow",
            "'The table pushes down on the floor', drawn on the diagram of the floor underneath it",
        ],
        "correct_index": 1,
        "why": "An interaction pair is the same type of force between the same two objects, acting on each in turn — so the partner sits on the table's diagram.",
    },
    {
        "id": "ks4-free-body-diagrams-h16",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Three forces hold an object in equilibrium and are redrawn tip to tail as a scale diagram. Describe the shape they make.",
        "options": [
            "A straight line, because forces in equilibrium have to act along one line as a matter of course",
            "A triangle that does not quite close, where the gap left stands for the size of the resultant force",
            "An open shape whose size depends on the order in which the three arrows happened to be drawn out",
            "A closed triangle, with the third arrow ending exactly where the first one began",
        ],
        "correct_index": 3,
        "why": "Adding the three vectors tip to tail gives a resultant of zero, and a zero resultant means the last arrow lands back at the start.",
    },
    {
        "id": "ks4-free-body-diagrams-h17",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "figure": "ks4-fig-free-body-parachutist-three-arrows",
        "text": "A student draws this free body diagram for a parachutist and her open parachute, together as one object, as they fall. Assess the arrow labelled 'pull of the parachute'.",
        "options": [
            "It should not be there: the lines pull between two parts of the same object, so for this object it is not an outside force",
            "It is correct, because the canopy pulls upwards on the harness quite separately from the drag",
            "It is correct, but it ought to be drawn downwards rather than upwards on the diagram",
            "It should not be there, because a parachute exerts no force on the person hanging beneath it",
        ],
        "correct_index": 0,
        "why": "For the parachutist and parachute as one object, the pull of the lines is a force between two parts of that object, so it does not belong on its free body diagram. The only upward force from outside is the air resistance (drag), which acts mostly on the canopy. Drawing both counts that one force twice.",
    },
    {
        "id": "ks4-free-body-diagrams-h18",
        "subtopic_slug": "free-body-diagrams",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A board rubber is held still against a vertical whiteboard by a horizontal push. Determine the four arrows its free body diagram needs.",
        "options": [
            "Weight down, the push towards the board, and the board's normal contact force back out, with nothing else drawn",
            "Weight down, the push towards the board, the board's push back out, and a downward friction arrow as well",
            "Weight down, friction up, the push towards the board, and the board's normal contact force back out",
            "Weight down and the push towards the board by itself, because a vertical surface supplies no other force",
        ],
        "correct_index": 2,
        "why": "The horizontal pair balance each other and friction along the board's surface acts upwards to balance the weight, holding it still.",
    },
]
