"""Physics · Forces — the MRB-338 expansion, subtopic
`stopping-distance-braking`.

The baseline twelve define thinking distance, run two thinking-distance
calculations, add the two distances together, scale a braking distance
by v squared twice, and judge the wet road, the loaded lorry and the
deep-tyre-tread claim.

This file takes what sits around that. It defines BRAKING distance in
its own right and fixes the typical 0.2-0.9 s reaction time; it works
the energy side hard, which the baseline barely touches — the kinetic
store emptying into the thermal store of the brakes, glowing discs,
drilled metal discs, and brake fade on a long descent; it separates the
driver factors (tiredness, alcohol, drugs, a phone) from the vehicle and
road factors (worn tyres, a larger braking force, ice, a slope, a skid)
and asks which distance each one moves; it measures reaction time with
the ruler-drop test and works backwards from a thinking distance to a
reaction time; and it spells out the danger of a large deceleration —
very large forces on the people inside, and a skid that leaves the
steering useless.

Braking is treated here as an ENERGY and SAFETY story. Calculating an
average braking force from work done belongs to
`work-done-energy-transfer`, and no row here does it.
"""

TOPIC = "forces"
SUBJECT = "physics"

QUESTIONS = [
    {
        "id": "ks4-stopping-distance-braking-e05",
        "subtopic_slug": "stopping-distance-braking",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what is meant by the braking distance of a vehicle.",
        "options": [
            "The distance travelled in the time it takes the driver to react to a hazard",
            "The total distance from spotting a hazard to coming to a stop",
            "The distance travelled once the brakes are applied, until the vehicle stops",
            "The shortest gap a driver should leave from the vehicle in front",
        ],
        "correct_index": 2,
        "why": "Braking distance is measured from the moment the brakes start to act; the distance covered before that is the thinking distance.",
    },
    {
        "id": "ks4-stopping-distance-braking-e06",
        "subtopic_slug": "stopping-distance-braking",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give a typical range for the reaction time of a driver.",
        "options": [
            "0.2 s to 0.9 s",
            "2 s to 9 s, which is where the advice to leave a two-second gap comes from",
            "0.002 s to 0.009 s",
            "About 5 s for an alert driver",
        ],
        "correct_index": 0,
        "why": "A reaction time is a fraction of a second, so at motorway speed even an alert driver covers many metres before braking begins.",
    },
    {
        "id": "ks4-stopping-distance-braking-e07",
        "subtopic_slug": "stopping-distance-braking",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Braking empties a car's kinetic energy store. Name the store that the energy mostly ends up in.",
        "options": [
            "The chemical store of the fuel in the tank",
            "The elastic store of the tyres, which are squashed a little as the car slows",
            "The gravitational store of the car",
            "The thermal store of the brakes",
        ],
        "correct_index": 3,
        "why": "Friction between the pads and the discs does work on them, so the brakes get hot — which is where the kinetic energy goes.",
    },
    {
        "id": "ks4-stopping-distance-braking-e08",
        "subtopic_slug": "stopping-distance-braking",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Identify the factor that lengthens the thinking distance.",
        "options": [
            "Worn brake pads",
            "The driver being tired",
            "A wet road surface",
            "Bald tyres with no tread left",
        ],
        "correct_index": 1,
        "why": "Tiredness lengthens the reaction time, and thinking distance = speed × reaction time; the other three change the grip or the braking force.",
    },
    {
        "id": "ks4-stopping-distance-braking-e09",
        "subtopic_slug": "stopping-distance-braking",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A driver moving at 12 m/s has a reaction time of 0.50 s. Calculate the thinking distance.",
        "options": [
            "24 m",
            "12.5 m",
            "6.0 m",
            "0.042 m",
        ],
        "correct_index": 2,
        "why": "Thinking distance = speed × reaction time = 12 × 0.50 = 6.0 m.",
    },
    {
        "id": "ks4-stopping-distance-braking-e10",
        "subtopic_slug": "stopping-distance-braking",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Complete the word equation: stopping distance = thinking distance + ...",
        "options": [
            "reaction time",
            "the speed of the vehicle",
            "the total distance travelled",
            "braking distance",
        ],
        "correct_index": 3,
        "why": "The two parts of a stop are the ground covered while reacting and the ground covered while the brakes act.",
    },
    {
        "id": "ks4-stopping-distance-braking-e11",
        "subtopic_slug": "stopping-distance-braking",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why brake discs become hot when a car slows down.",
        "options": [
            "Work done by friction raises their thermal energy store",
            "The car's kinetic store is destroyed and heat is left behind",
            "Hot air from the engine is blown over them as the car slows down",
            "The brakes make new energy while they rub on the discs",
        ],
        "correct_index": 0,
        "why": "Energy is transferred, never created or destroyed: friction does work on the discs and pads, raising their temperature.",
    },
    {
        "id": "ks4-stopping-distance-braking-e12",
        "subtopic_slug": "stopping-distance-braking",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Identify the road condition that lengthens the braking distance.",
        "options": [
            "Bright sunshine ahead",
            "Ice on the road surface",
            "A long, straight road",
            "Heavy traffic in the other lane",
        ],
        "correct_index": 1,
        "why": "Ice cuts the friction between tyre and road, so the braking force is smaller and the car travels further before stopping.",
    },
    {
        "id": "ks4-stopping-distance-braking-s05",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A car is driven at 20 m/s by a driver whose reaction time is 0.25 s. Calculate the thinking distance.",
        "options": [
            "80 m",
            "0.0125 m",
            "20.25 m",
            "5.0 m",
        ],
        "correct_index": 3,
        "why": "20 m/s × 0.25 s = 5.0 m, which is more than a car's length covered before the brakes even begin to act.",
    },
    {
        "id": "ks4-stopping-distance-braking-s06",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A car's braking distance is 12 m at 10 m/s. Estimate the braking distance at 20 m/s on that road.",
        "options": [
            "24 m",
            "48 m",
            "144 m",
            "6 m",
        ],
        "correct_index": 1,
        "why": "Braking distance goes with the square of the speed: the speed doubles, so the distance becomes 2² × 12 = 48 m.",
    },
    {
        "id": "ks4-stopping-distance-braking-s07",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why drinking alcohol lengthens a driver's stopping distance.",
        "options": [
            "It reduces the grip between the tyres and the road surface",
            "It makes the brakes less able to grip the discs firmly",
            "It slows the driver's reactions, so the thinking distance grows",
            "It increases the mass of the car, so more energy must be removed by the brakes",
        ],
        "correct_index": 2,
        "why": "Alcohol is a driver factor: it lengthens the reaction time and so the thinking distance, while leaving the brakes and tyres untouched.",
    },
    {
        "id": "ks4-stopping-distance-braking-s08",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A coach driver brakes again and again on a long, steep descent and finds the brakes becoming less effective. Name this effect.",
        "options": [
            "Brake fade",
            "Thinking distance creep, caused by the driver tiring on the descent",
            "Terminal velocity",
            "Elastic deformation of the brake pads",
        ],
        "correct_index": 0,
        "why": "The brakes cannot lose heat fast enough, so they overheat and the friction force they can apply drops — known as brake fade.",
    },
    {
        "id": "ks4-stopping-distance-braking-s09",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe the main energy transfer taking place while a car brakes to a stop.",
        "options": [
            "Thermal energy from the brakes flows into the car's kinetic store",
            "The car's kinetic store empties into the brakes' thermal store",
            "The chemical store of the fuel empties into the thermal store of the road surface",
            "Kinetic energy is used up and lost as the car slows",
        ],
        "correct_index": 1,
        "why": "The brakes do work against the car's motion, so the kinetic store falls and the thermal stores of the pads and discs rise by the same amount.",
    },
    {
        "id": "ks4-stopping-distance-braking-s10",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A driver holds a conversation on a hands-free phone on a dry road with new tyres. Identify the distance that is affected.",
        "options": [
            "Only the braking distance, since the brakes have to work harder",
            "Both distances, as the road conditions have changed as well",
            "Neither distance, because the phone is hands-free and the road is dry",
            "Only the thinking distance",
        ],
        "correct_index": 3,
        "why": "Distraction is a driver factor, and a hands-free phone still takes attention, so the reaction time and thinking distance grow.",
    },
    {
        "id": "ks4-stopping-distance-braking-s11",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a very large deceleration is dangerous for the people inside a car.",
        "options": [
            "The car's mass rises sharply, which makes the seat belts less effective",
            "The brakes cool too quickly and can crack under the sudden change",
            "Very large forces act on the people inside",
            "The thinking distance grows, so the driver has less time to steer away from danger",
        ],
        "correct_index": 2,
        "why": "F = m a: a big deceleration needs a big force, and that force has to be supplied to every passenger by belts and seats.",
    },
    {
        "id": "ks4-stopping-distance-braking-s12",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Riding at 18 m/s, a motorcyclist needs 0.60 s to respond and then covers a further 30 m under braking. Work out the total distance used in stopping.",
        "options": [
            "40.8 m",
            "30.6 m",
            "48 m",
            "10.8 m",
        ],
        "correct_index": 0,
        "why": "Thinking distance = 18 × 0.60 = 10.8 m, and 10.8 + 30 = 40.8 m in total.",
    },
    {
        "id": "ks4-stopping-distance-braking-s13",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why stopping distances at motorway speeds are so much greater than in a town.",
        "options": [
            "Motorway surfaces give less grip than town roads do",
            "Thinking distance grows with speed while braking distance grows with speed squared",
            "Drivers react more slowly when they are bored",
            "Heavier vehicles use motorways",
        ],
        "correct_index": 1,
        "why": "Trebling the speed trebles the thinking distance but makes the braking distance nine times larger, so the total climbs steeply.",
    },
    {
        "id": "ks4-stopping-distance-braking-s14",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the effect on the braking distance of carrying four passengers rather than travelling alone.",
        "options": [
            "It is shorter, because the extra weight presses the tyres into the road",
            "It is unchanged, since braking distance depends on speed alone",
            "It is longer",
            "It is unchanged, but the thinking distance becomes longer instead",
        ],
        "correct_index": 2,
        "why": "More mass at the same speed means a bigger kinetic store for the brakes to empty, which takes a greater distance.",
    },
    {
        "id": "ks4-stopping-distance-braking-s15",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A lorry brakes on a steep downhill stretch. State the effect on its braking distance compared with level ground.",
        "options": [
            "Shorter, because gravity helps the brakes to slow the lorry down",
            "Unchanged, as gravity acts at right angles to the road",
            "Shorter, because the wheels press harder on the road surface",
            "Longer, because part of the lorry's weight now acts down the slope",
        ],
        "correct_index": 3,
        "why": "Part of the lorry's weight now acts down the slope, opposing the brakes, so more distance is needed to bring it to rest.",
    },
    {
        "id": "ks4-stopping-distance-braking-s16",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe a simple way of measuring a person's reaction time in the classroom.",
        "options": [
            "Time how long they take to run 10 m across the laboratory",
            "Drop a ruler between their open fingers and measure how far it falls before they catch it",
            "Measure how long they can hold their breath for",
            "Count how many times they can clap in ten seconds",
        ],
        "correct_index": 1,
        "why": "The distance the ruler falls depends only on the time before the catch, so it can be converted straight into a reaction time.",
    },
    {
        "id": "ks4-stopping-distance-braking-s17",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how the thinking distance changes when a car's speed is doubled, with the same driver at the wheel.",
        "options": [
            "It stays the same",
            "It becomes four times as large",
            "It doubles, in step with the speed",
            "It becomes half as large, since there is less time to react",
        ],
        "correct_index": 2,
        "why": "Thinking distance = speed × reaction time, and the reaction time has not changed, so the distance is proportional to the speed.",
    },
    {
        "id": "ks4-stopping-distance-braking-s18",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why drivers are told to leave a bigger gap from the vehicle in front at higher speeds.",
        "options": [
            "The stopping distance is longer, so more room is needed to pull up safely",
            "The car in front brakes more sharply on a fast road than on a slow one",
            "Air resistance pushes the following car forwards into the gap",
            "The thinking distance becomes shorter as the speed rises, which is a hidden hazard",
        ],
        "correct_index": 0,
        "why": "Both parts of the stop grow with speed, so the gap has to grow too if the driver is to stop inside it.",
    },
    {
        "id": "ks4-stopping-distance-braking-s19",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Identify the change that has no effect at all on a car's thinking distance.",
        "options": [
            "The driver taking a long shift without a break",
            "Fitting new brake pads and discs",
            "The driver texting at the wheel",
            "The driver taking medicine that causes drowsiness",
        ],
        "correct_index": 1,
        "why": "New brakes shorten the braking distance only; thinking distance is fixed by the speed and the driver's reaction time.",
    },
    {
        "id": "ks4-stopping-distance-braking-s20",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A car is fitted with brakes able to apply a larger braking force. State the effect on its braking distance.",
        "options": [
            "It becomes longer, because more energy is transferred to the brakes",
            "It is unchanged, since braking distance is set by the speed alone",
            "It becomes longer, as the tyres are more likely to skid on the road",
            "It becomes shorter, because the same kinetic store is removed by a bigger force",
        ],
        "correct_index": 3,
        "why": "The same kinetic store is removed by a larger force, so the work is done over a shorter distance.",
    },
    {
        "id": "ks4-stopping-distance-braking-s21",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Before braking begins, a motorbike at 25 m/s covers 15 m of road. Work out how long its rider took to respond.",
        "options": [
            "375 s",
            "1.7 s",
            "0.60 s",
            "0.04 s",
        ],
        "correct_index": 2,
        "why": "Rearranging thinking distance = speed × reaction time gives 15 ÷ 25 = 0.60 s.",
    },
    {
        "id": "ks4-stopping-distance-braking-s22",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a skidding car takes longer to stop than one whose tyres keep gripping.",
        "options": [
            "Sliding tyres give a smaller friction force than gripping ones",
            "A skidding car has a larger mass pressing down on the road surface",
            "Skidding raises the driver's reaction time and so the thinking distance",
            "The wheels turn faster while the car is skidding, which carries it further along the road",
        ],
        "correct_index": 0,
        "why": "Once the tyres slide, the backward force on the car falls, so the kinetic store is removed over a longer distance.",
    },
    {
        "id": "ks4-stopping-distance-braking-s23",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a driver at the end of a long night shift is more likely to have a collision.",
        "options": [
            "Tiredness stiffens the brakes so they respond less well to the pedal",
            "Tiredness lengthens the reaction time, so the thinking distance grows",
            "Tiredness raises the car's mass and its kinetic energy at a given speed",
            "Tiredness reduces the grip of the tyres because the driver steers less smoothly",
        ],
        "correct_index": 1,
        "why": "Every extra tenth of a second of reaction time adds metres at speed, and those metres come before the brakes do anything at all.",
    },
    {
        "id": "ks4-stopping-distance-braking-s24",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The same car stops in 24 m on a dry road and 36 m on a wet one, from the same speed and with the same driver. Explain the difference.",
        "options": [
            "The driver reacts more slowly in the rain, which lengthens the thinking distance",
            "Rain adds mass to the car, so the brakes have more kinetic energy to remove",
            "Water reduces the friction at the tyres, so the braking distance grows",
            "Wet brakes squeak, so the driver presses the pedal more gently than on a dry road surface",
        ],
        "correct_index": 2,
        "why": "The driver and the speed are unchanged, so the thinking distance is the same; only the grip, and therefore the braking distance, has altered.",
    },
    {
        "id": "ks4-stopping-distance-braking-s25",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A lorry is driven at 22 m/s and responds to a hazard 0.45 s after it appears. Work out how far it goes before its brakes start to act.",
        "options": [
            "49 m",
            "0.020 m",
            "22.45 m",
            "9.9 m",
        ],
        "correct_index": 3,
        "why": "22 × 0.45 = 9.9 m. Adding the two numbers instead of multiplying gives the tempting 22.45 m.",
    },
    {
        "id": "ks4-stopping-distance-braking-s26",
        "subtopic_slug": "stopping-distance-braking",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the braking distance grows much faster than the thinking distance as a car speeds up.",
        "options": [
            "Braking distance depends on the square of the speed, but thinking distance only on the speed itself",
            "Brakes work less well at high speed",
            "Reaction times shorten at high speed",
            "The car's mass increases at high speed",
        ],
        "correct_index": 0,
        "why": "Doubling the speed doubles the thinking distance but quadruples the braking distance, because the kinetic store depends on v².",
    },
    {
        "id": "ks4-stopping-distance-braking-h05",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "At 10 m/s a car has a thinking distance of 7.0 m and a braking distance of 8.0 m. Estimate its stopping distance at 30 m/s.",
        "options": [
            "93 m",
            "45 m",
            "135 m",
            "21 m",
        ],
        "correct_index": 0,
        "why": "Thinking distance trebles to 21 m and braking distance becomes 3² × 8.0 = 72 m, giving 93 m altogether.",
    },
    {
        "id": "ks4-stopping-distance-braking-h06",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A minibus comes down a mountain road with the brakes held on for several minutes, and the driver notices the pedal feels soft. Explain what has happened.",
        "options": [
            "The tyres have worn smooth over the long descent, so there is much less grip available",
            "The thinking distance has grown because the driver is concentrating hard",
            "The brakes have cooled so much that they no longer press on the discs properly",
            "The brakes have overheated and lost some of their effectiveness",
        ],
        "correct_index": 3,
        "why": "Continuous braking puts energy into the discs faster than they can lose it, and hot brakes grip less well — this is brake fade.",
    },
    {
        "id": "ks4-stopping-distance-braking-h07",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 1400 kg car travelling at 20 m/s is brought to rest. Calculate the energy transferred out of its kinetic store.",
        "options": [
            "28 000 J",
            "280 000 J",
            "14 000 J",
            "560 000 J",
        ],
        "correct_index": 1,
        "why": "Kinetic energy = 0.5 × 1400 × 20² = 280 000 J, and all of it ends up warming the brakes.",
    },
    {
        "id": "ks4-stopping-distance-braking-h08",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "On dry tarmac a van needs 16 m to brake from 12 m/s. Work out how much road it needs to brake from 18 m/s there.",
        "options": [
            "24 m",
            "32 m",
            "36 m",
            "48 m",
        ],
        "correct_index": 2,
        "why": "The speed ratio is 1.5, so the distance ratio is 1.5² = 2.25, giving 2.25 × 16 = 36 m.",
    },
    {
        "id": "ks4-stopping-distance-braking-h09",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two drivers travel at 24 m/s. One has a reaction time of 0.30 s and the other 0.80 s. Calculate the difference in their thinking distances.",
        "options": [
            "12.0 m",
            "26.4 m",
            "0.50 m",
            "19.2 m",
        ],
        "correct_index": 0,
        "why": "The difference in reaction times is 0.50 s, and 24 × 0.50 = 12 m — three car lengths of extra road.",
    },
    {
        "id": "ks4-stopping-distance-braking-h10",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two tests on the same car at the same speed give the same thinking distance but twice the braking distance. Suggest what changed.",
        "options": [
            "The driver had become tired between the two tests",
            "The car was driven faster in the second test than in the first one",
            "The driver's reaction time doubled between the tests, which lengthened the stop",
            "The road was slippery for the second test",
        ],
        "correct_index": 3,
        "why": "An unchanged thinking distance rules out the driver and the speed, so the change must be to the grip or the brakes.",
    },
    {
        "id": "ks4-stopping-distance-braking-h11",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a car stopping from a high speed can leave its brake discs glowing.",
        "options": [
            "The kinetic store emptied is very large, so a great deal of energy is transferred to the brakes",
            "Friction creates new energy inside the brake discs",
            "Air resistance heats the brake discs as the car slows",
            "The thinking distance is long at high speed",
        ],
        "correct_index": 0,
        "why": "Kinetic energy depends on v², so a fast car carries a huge store, and the brakes must take all of it in a few seconds.",
    },
    {
        "id": "ks4-stopping-distance-braking-h12",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A driver's stopping distance at 15 m/s is 30 m. Explain why the stopping distance at 30 m/s is more than double that.",
        "options": [
            "Thinking distance grows with the square of the speed while braking distance simply doubles",
            "Only the thinking distance doubles; the braking distance goes up four times",
            "Reaction time doubles as well, which adds an extra amount on top of the rest",
            "The brakes become less effective as the speed rises, adding to the distance",
        ],
        "correct_index": 1,
        "why": "The two parts scale differently: one is proportional to v and the other to v², so the total more than doubles.",
    },
    {
        "id": "ks4-stopping-distance-braking-h13",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Using a phone raises a driver's reaction time from 0.60 s to 1.2 s. At 24 m/s, calculate the extra thinking distance.",
        "options": [
            "28.8 m",
            "7.2 m",
            "14.4 m",
            "1.2 m",
        ],
        "correct_index": 2,
        "why": "The extra reaction time is 0.60 s, and 24 × 0.60 = 14.4 m of road covered with nobody braking.",
    },
    {
        "id": "ks4-stopping-distance-braking-h14",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the assumption behind saying that braking distance is proportional to the square of the speed.",
        "options": [
            "That the driver's reaction time stays the same at every speed",
            "That the road is always level and dry, and the car is always empty of passengers",
            "That the car's mass falls as the fuel is used up during the journey",
            "That the braking force stays the same",
        ],
        "correct_index": 3,
        "why": "The kinetic store is proportional to v², so a fixed braking force must act over a distance proportional to v² to remove it.",
    },
    {
        "id": "ks4-stopping-distance-braking-h15",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Approaching at 35 m/s, a coach driver takes 0.80 s to respond and the wheels then need 100 m to halt the coach. How far does it go altogether?",
        "options": [
            "128 m",
            "100.8 m",
            "135 m",
            "28 m",
        ],
        "correct_index": 0,
        "why": "Thinking distance = 35 × 0.80 = 28 m, so the stop takes 28 + 100 = 128 m in all.",
    },
    {
        "id": "ks4-stopping-distance-braking-h16",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student claims that doubling a car's speed doubles its braking distance. Evaluate the claim.",
        "options": [
            "Correct, because braking distance is proportional to the speed in the same way as thinking distance",
            "Wrong — it becomes about four times as large",
            "Correct, provided the road surface stays exactly as it was",
            "Wrong — it becomes about eight times as large",
        ],
        "correct_index": 1,
        "why": "It is the THINKING distance that simply doubles; braking distance follows v², so it quadruples.",
    },
    {
        "id": "ks4-stopping-distance-braking-h17",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Braking from 20 m/s uses 40 m of road. Determine how much road is used braking from 30 m/s under identical conditions.",
        "options": [
            "60 m",
            "120 m",
            "90 m",
            "80 m",
        ],
        "correct_index": 2,
        "why": "(30 ÷ 20)² = 2.25, so the braking distance becomes 2.25 × 40 = 90 m. Simply scaling by 1.5 gives the tempting 60 m.",
    },
    {
        "id": "ks4-stopping-distance-braking-h18",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why filling a car with luggage leaves the thinking distance unchanged.",
        "options": [
            "Thinking distance depends only on the speed and the driver's reaction time",
            "The extra load presses the tyres down and improves the grip on the road, which cancels it out",
            "The luggage is behind the driver, so it does not affect the front wheels at all",
            "The extra mass adds to the kinetic energy and shortens the reaction time to match",
        ],
        "correct_index": 0,
        "why": "Mass matters only once the brakes are working; before that the car simply travels at its speed for the reaction time.",
    },
    {
        "id": "ks4-stopping-distance-braking-h19",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two identical cars brake from the same speed and one stops in half the distance. Suggest the most likely reason.",
        "options": [
            "Its driver reacted more quickly to the hazard ahead",
            "It was carrying more passengers than the other car was",
            "Its brakes were worn, so less of the kinetic store was removed by them",
            "Its tyres gripped a drier part of the road",
        ],
        "correct_index": 3,
        "why": "Halving the whole distance points to a much larger braking force, and grip is what sets that force.",
    },
    {
        "id": "ks4-stopping-distance-braking-h20",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A steep downhill road is wet and is being driven at speed. Describe the combined effect on the stopping distance.",
        "options": [
            "Both the wet surface and the slope lengthen the braking distance, so the whole stop is much longer",
            "Only the thinking distance is lengthened",
            "The two effects cancel, leaving the distance unchanged",
            "The slope shortens the stop while the water lengthens it",
        ],
        "correct_index": 0,
        "why": "Water cuts the grip and the slope adds a component of weight down the hill, and both act to lengthen the braking distance.",
    },
    {
        "id": "ks4-stopping-distance-braking-h21",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the brake discs on a fast car are made of metal and drilled with holes.",
        "options": [
            "The holes let rainwater collect inside the disc and cool it down",
            "Metal conducts the energy away quickly and the holes help the discs cool",
            "The holes make the discs lighter, which reduces the car's kinetic energy at any speed",
            "Metal stores the energy as elastic potential energy, which is released later on",
        ],
        "correct_index": 1,
        "why": "The brakes must shed the thermal energy between stops, or they fade; good conduction and a large surface area do that.",
    },
    {
        "id": "ks4-stopping-distance-braking-h22",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Identify the situation in which BOTH the thinking distance and the braking distance are lengthened.",
        "options": [
            "A tired driver on a dry road with new tyres",
            "An alert driver on an icy road with good tyres",
            "A tired driver on an icy road",
            "An alert driver on a dry road with worn tyres and a heavy load",
        ],
        "correct_index": 2,
        "why": "Tiredness is a driver factor and ice is a road factor, so one lengthens the thinking distance and the other the braking distance.",
    },
    {
        "id": "ks4-stopping-distance-braking-h23",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A car's stopping distance at 20 m/s is 54 m, of which 14 m is thinking distance. Calculate its stopping distance at 10 m/s.",
        "options": [
            "27 m",
            "13.5 m",
            "20 m",
            "17.0 m",
        ],
        "correct_index": 3,
        "why": "The thinking part halves to 7 m and the braking part quarters from 40 m to 10 m, so the total is 17 m.",
    },
    {
        "id": "ks4-stopping-distance-braking-h24",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why published stopping distances are only estimates.",
        "options": [
            "They are worked out for one car on a dry road with an alert driver, so real values vary",
            "They are measured at speeds nobody drives at",
            "Reaction times, road surfaces and vehicles all differ",
            "The equation for braking distance has not been tested",
        ],
        "correct_index": 2,
        "why": "Each quantity in the calculation has a wide spread in real life, so a published figure is a typical case rather than a guarantee.",
    },
    {
        "id": "ks4-stopping-distance-braking-h25",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A driver halves her speed along the same stretch of road. Describe what happens to the braking distance.",
        "options": [
            "It halves",
            "It falls to a quarter of its previous value",
            "It stays the same, as the braking force has not changed at all",
            "It falls to an eighth of its previous value",
        ],
        "correct_index": 1,
        "why": "Braking distance follows v², so halving the speed divides the distance by 2² = 4.",
    },
    {
        "id": "ks4-stopping-distance-braking-h26",
        "subtopic_slug": "stopping-distance-braking",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why braking very hard can make a car harder to steer as well as uncomfortable for its passengers.",
        "options": [
            "The car's mass rises as it slows, which makes the steering heavier",
            "The thinking distance becomes longer, so the driver is slower to steer around a hazard",
            "The brakes cool rapidly and grip unevenly on each wheel",
            "The tyres can lose grip and skid, so steering has little effect",
        ],
        "correct_index": 3,
        "why": "A locked, sliding tyre cannot push the car sideways, so the car keeps going the way it was already travelling.",
    },
]
