"""Physics · Forces — the MRB-338 expansion, subtopic `distance-time-graphs`.

The baseline twelve already own: one gradient read from a line through the
origin, the bare statement that gradient gives speed, a downward-sloping
return leg, a gradient between two lifted points, a rise-then-flat average
speed, a kilometre-and-minute line converted to m/s, two cyclists compared,
the "area under the line" misconception, a two-gradient journey, a curve
flattening to horizontal, an out-and-back walk with a wait in it, and a line
plotted in kilometres against hours.

This file takes the ground beside those: what the axes are and what goes
wrong when they are swapped, a flat line read as a stop rather than as slow
motion, a curve that STEEPENS, lines that start above the origin, two lines
crossing and what the crossing instant means, lines of equal gradient at
different heights, reading a distance off at an intermediate time and
predicting a later one, finding when two travellers meet, why a line can
never run vertically, why a stop drags the average below every moving
section, and a set of evaluate-the-claim rows on gradient, height and shape.

⚠️ Every graph in this file is DESCRIBED in words, with its coordinates
given, because a question pool has no figure to point at. Nothing here reads
a velocity-time graph — gradient as acceleration and area as distance belong
to `acceleration`.
"""

TOPIC = "forces"
SUBJECT = "physics"

QUESTIONS = [
    {
        "id": "ks4-distance-time-graphs-e05",
        "subtopic_slug": "distance-time-graphs",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a horizontal line on a graph of distance against time tells you about the object.",
        "options": [
            "It is moving away from the start at a steady speed the whole time",
            "It is stationary",
            "It is speeding up",
            "It is returning to the start",
        ],
        "correct_index": 1,
        "why": "A flat line has zero gradient, and the gradient is the speed, so nothing is moving; the distance reading simply stays where it is.",
    },
    {
        "id": "ks4-distance-time-graphs-e06",
        "subtopic_slug": "distance-time-graphs",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A van sets off from a depot along a straight road. Its distance from the depot reaches 140 m after 8.0 s, and the plot of distance against time is one straight stretch. Calculate the speed.",
        "options": [
            "1120 m/s",
            "0.057 m/s",
            "148 m/s",
            "17.5 m/s",
        ],
        "correct_index": 3,
        "why": "The gradient is 140 / 8.0 = 17.5 m/s. Multiplying the two readings gives 1120, which is neither a speed nor a distance.",
    },
    {
        "id": "ks4-distance-time-graphs-e07",
        "subtopic_slug": "distance-time-graphs",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which axis on a graph of distance against time carries the time?",
        "options": [
            "The horizontal axis",
            "The vertical axis",
            "Either axis, provided the gradient is still worked out as rise over run",
            "Neither: time is shown by the length of the line",
        ],
        "correct_index": 0,
        "why": "Time is the independent variable, so it goes along the bottom; distance is plotted up the side. The name of the graph lists them in that order, distance against time.",
    },
    {
        "id": "ks4-distance-time-graphs-e08",
        "subtopic_slug": "distance-time-graphs",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two straight lines are drawn from the origin on one plot of distance against time. Line M is steeper than line N. State which object moves faster.",
        "options": [
            "N, because a shallower line covers more time",
            "They move at the same speed because both lines are straight",
            "M, because a steeper line means a greater gradient",
            "Neither line can show a speed until the scale has been read off both axes carefully",
        ],
        "correct_index": 2,
        "why": "Steeper means more distance covered in each second, and that is exactly what a bigger speed is.",
    },
    {
        "id": "ks4-distance-time-graphs-e09",
        "subtopic_slug": "distance-time-graphs",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A pupil plots distance against time for a toy car and gets a straight line through the origin reaching 60 m at 16 s. Calculate the speed.",
        "options": [
            "960 m/s",
            "0.27 m/s",
            "3.75 m/s",
            "76 m/s",
        ],
        "correct_index": 2,
        "why": "60 / 16 = 3.75 m/s. Dividing the time by the distance gives 0.27, whose unit would be seconds per metre.",
    },
    {
        "id": "ks4-distance-time-graphs-e10",
        "subtopic_slug": "distance-time-graphs",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "On a plot of distance against time the line becomes steeper as the journey goes on. State what is happening to the object.",
        "options": [
            "It is speeding up",
            "It is slowing down",
            "It is moving at a steady speed",
            "It is going backwards towards the point it set out from",
        ],
        "correct_index": 0,
        "why": "A rising gradient means each second brings more distance than the one before, which is what speeding up means.",
    },
    {
        "id": "ks4-distance-time-graphs-e11",
        "subtopic_slug": "distance-time-graphs",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A line runs straight from (0 s, 10 m) to (20 s, 50 m) on a plot of distance against time. Calculate the speed.",
        "options": [
            "2.5 m/s",
            "0.5 m/s",
            "60 m/s",
            "2.0 m/s",
        ],
        "correct_index": 3,
        "why": "The gradient uses the CHANGE in distance: (50 - 10) / 20 = 2.0 m/s. Using 50 / 20 and forgetting the 10 m head start gives 2.5 m/s.",
    },
    {
        "id": "ks4-distance-time-graphs-e12",
        "subtopic_slug": "distance-time-graphs",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A cyclist's plot of distance against time stays horizontal between 30 s and 50 s. State how far she travels in that interval.",
        "options": [
            "50 m, read straight off the vertical axis at the end of the flat section",
            "0 m, since she stays where she is",
            "20 m",
            "30 m",
        ],
        "correct_index": 1,
        "why": "The distance reading does not change, so she covers no ground at all; the 20 s is time spent at rest.",
    },
    {
        "id": "ks4-distance-time-graphs-s05",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A tram sets off and its distance from the depot rises steadily to 480 m at 40 s, after which the plotted line stays flat until 100 s. Determine the average speed for the full 100 s.",
        "options": [
            "4.8 m/s",
            "12 m/s",
            "9.6 m/s",
            "0.21 m/s",
        ],
        "correct_index": 0,
        "why": "Average speed uses the whole time, waiting included: 480 / 100 = 4.8 m/s. The 12 m/s is the speed while it was moving, which is not the same figure.",
    },
    {
        "id": "ks4-distance-time-graphs-s06",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two runners are timed over the same straight track. On the plotted graph, P's line reaches 120 m at 15 s while Q's line needs 24 s to reach 120 m. Determine each speed.",
        "options": [
            "P at 0.13 m/s and Q at 0.21 m/s, because speed is time divided by distance",
            "Both at 5.0 m/s, since both lines reach the same distance",
            "P at 8.0 m/s and Q at 5.0 m/s",
            "P at 5.0 m/s and Q at 8.0 m/s",
        ],
        "correct_index": 2,
        "why": "120 / 15 = 8.0 m/s and 120 / 24 = 5.0 m/s. Reaching the same distance says nothing about speed until the times are compared.",
    },
    {
        "id": "ks4-distance-time-graphs-s07",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A plot of distance against time for a school bus is a straight line for the first 200 s, then a flat section, then another straight line of the same steepness. Describe the journey.",
        "options": [
            "The bus gets steadily faster, stops, then gets faster again over the last stage",
            "Steady speed, then a stop, then the same steady speed again",
            "Steady speed, then a reverse, then forward again",
            "The bus is stationary for the whole journey",
        ],
        "correct_index": 1,
        "why": "Equal gradients mean equal speeds, and the flat part in between is a stop at a bus stop rather than a change of direction.",
    },
    {
        "id": "ks4-distance-time-graphs-s08",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A hiking app plots kilometres up the side and hours along the bottom. The line climbs steadily from 2.0 km at 0.50 h to 11.0 km at 2.0 h. Determine the speed in m/s.",
        "options": [
            "6.0 m/s",
            "0.60 m/s",
            "4.5 m/s",
            "1.67 m/s",
        ],
        "correct_index": 3,
        "why": "The gradient is 9.0 km in 1.5 h, which is 6.0 km/h; 6000 m divided by 3600 s gives 1.67 m/s. The 6.0 is the speed in km/h, not in m/s.",
    },
    {
        "id": "ks4-distance-time-graphs-s09",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "On a walker's plot of distance from home against time, the line falls steadily from 800 m at 100 s to zero at 500 s. Calculate her speed on the return leg.",
        "options": [
            "1.6 m/s",
            "8.0 m/s",
            "0.50 m/s",
            "2.0 m/s",
        ],
        "correct_index": 3,
        "why": "She covers 800 m in 400 s, so the speed is 2.0 m/s. The minus sign on the gradient tells you the direction, not the size.",
    },
    {
        "id": "ks4-distance-time-graphs-s10",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A journey is plotted as distance from home against time. Explain what a section with a steeper downward slope shows.",
        "options": [
            "The object is moving away from home faster",
            "The object is returning home more quickly than before",
            "The object has stopped moving altogether, because a downward slope cannot show motion",
            "The object is moving away from home slowly",
        ],
        "correct_index": 1,
        "why": "Downward means the distance from home is shrinking, so the object is coming back; steeper means it is doing so at a greater speed.",
    },
    {
        "id": "ks4-distance-time-graphs-s11",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Between 0 s and 60 s a train's plotted line is a smooth curve that keeps getting steeper. State how the train is moving.",
        "options": [
            "At a steady speed, because the line is unbroken",
            "Backwards towards the station it left",
            "Speeding up, because the gradient is increasing",
            "Slowing down, because a curve shows the speed falling away as the journey continues",
        ],
        "correct_index": 2,
        "why": "A curve means the speed is changing; the direction of the bend says which way. Getting steeper means the speed is rising.",
    },
    {
        "id": "ks4-distance-time-graphs-s12",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two cars start from one place at the same moment. Car J's plotted line is straight; car K's curves upwards more and more steeply and crosses J's line at 40 s. Describe what happens at 40 s.",
        "options": [
            "K catches up with J, and after that it is ahead",
            "The two cars collide with one another",
            "K stops and J carries on at a steady speed",
            "J and K swap places on the road, because a crossing point means the lines exchange their gradients",
        ],
        "correct_index": 0,
        "why": "A crossing means both are the same distance from the start at the same instant; K's steeper gradient afterwards puts it in front.",
    },
    {
        "id": "ks4-distance-time-graphs-s13",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A plotted line is horizontal for 25 s and then rises steeply. Explain what the driver did.",
        "options": [
            "Drove at a steady speed for 25 s, then stopped for the rest of the time shown",
            "Waited for 25 s, then drove off quickly",
            "Reversed for 25 s, then drove forwards",
            "Drove slowly for 25 s, then more slowly still",
        ],
        "correct_index": 1,
        "why": "Flat means no distance is being covered, so the car is waiting; the steep rise afterwards is a large distance in each second.",
    },
    {
        "id": "ks4-distance-time-graphs-s14",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A runner's plotted line rises from the origin to 300 m at 60 s, is flat until 90 s, then rises again to 500 m at 140 s. Calculate her speed over the first section.",
        "options": [
            "5.0 m/s",
            "3.6 m/s",
            "0.20 m/s",
            "18000 m/s",
        ],
        "correct_index": 0,
        "why": "The first section alone gives 300 / 60 = 5.0 m/s. The 3.6 m/s would be the average over the whole 140 s, which the question did not ask for.",
    },
    {
        "id": "ks4-distance-time-graphs-s15",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Determine the average speed of a cyclist whose plotted line climbs to 900 m at 120 s, stays flat to 180 s, then climbs to 1500 m at 300 s.",
        "options": [
            "7.5 m/s",
            "3.3 m/s",
            "5.0 m/s",
            "12.5 m/s",
        ],
        "correct_index": 2,
        "why": "The totals are 1500 m and 300 s, giving 5.0 m/s. The 7.5 and 5.0 figures for the two moving sections are both higher than the average, because the stop adds time and no distance.",
    },
    {
        "id": "ks4-distance-time-graphs-s16",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how you would find the speed of an object from a straight line on a plot of distance against time.",
        "options": [
            "Read the distance at the end and divide by the number of squares",
            "Measure the length of the line with a ruler",
            "Find the area between the line and the time axis",
            "Work out the gradient, which is the change in distance divided by the time it took",
        ],
        "correct_index": 3,
        "why": "Speed is distance per unit time, and that is precisely what a gradient measures; the physical length of the drawn line depends only on the scales chosen.",
    },
    {
        "id": "ks4-distance-time-graphs-s17",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A pupil puts time up the side and distance along the bottom by mistake. State what the gradient of her straight line now gives.",
        "options": [
            "The speed, because the gradient of any graph of motion is a speed whichever way the axes are drawn",
            "The acceleration of the object",
            "The time taken for each metre, which is one divided by the speed",
            "Nothing can be worked out from the line at all",
        ],
        "correct_index": 2,
        "why": "Gradient is always the vertical change over the horizontal change, so swapping the axes turns metres per second into seconds per metre.",
    },
    {
        "id": "ks4-distance-time-graphs-s18",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A dinghy's plotted line is straight from (0 s, 0 m) to (50 s, 400 m). Calculate the speed and state whether it changes.",
        "options": [
            "8.0 m/s, and the speed rises steadily because the line keeps climbing",
            "0.125 m/s, and the speed is constant",
            "20 000 m/s, and the speed is constant",
            "8.0 m/s, and the speed stays the same throughout",
        ],
        "correct_index": 3,
        "why": "400 / 50 = 8.0 m/s, and a straight line has one gradient all the way, so the speed does not change. A climbing line is not the same as a steepening one.",
    },
    {
        "id": "ks4-distance-time-graphs-s19",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a line on a plot of distance against time cannot be drawn vertically.",
        "options": [
            "Time would then be running backwards along the graph",
            "It would mean a distance was covered in zero time",
            "The axes would have to be swapped over to make the plot fit on the page properly",
            "A vertical line shows a stationary object",
        ],
        "correct_index": 1,
        "why": "A vertical section has an infinite gradient, so it claims an infinite speed. Nothing can be in two places at one instant.",
    },
    {
        "id": "ks4-distance-time-graphs-s20",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A tractor's plotted line is straight from the origin and reaches 180 m at 60 s. Determine how long it takes to reach 300 m at the same speed.",
        "options": [
            "100 s",
            "120 s",
            "90 s",
            "1.0 s",
        ],
        "correct_index": 0,
        "why": "The gradient is 3.0 m/s, so 300 m needs 300 / 3.0 = 100 s. Extending a straight line is safe here because the speed is not changing.",
    },
    {
        "id": "ks4-distance-time-graphs-s21",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A coach trip is plotted as distance from school against time. The line rises to 12 km at 30 min, stays flat for 90 min, then falls back to 0 km at 150 min. Determine the total distance and the final displacement.",
        "options": [
            "Distance 24 km, displacement 0 km",
            "Distance 12 km, displacement 12 km",
            "Distance 24 km, displacement 24 km, since the coach covered 24 km in all",
            "Distance 12 km, displacement 0 km",
        ],
        "correct_index": 0,
        "why": "The coach goes out 12 km and comes back 12 km, so 24 km of road passes under it, but it finishes in the school car park it left.",
    },
    {
        "id": "ks4-distance-time-graphs-s22",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "On one plot of distance against time, one line is straight and another curves so that it flattens off. Compare what the two lines show.",
        "options": [
            "Both objects move at a steady speed, since both lines keep climbing",
            "The straight line shows a steady speed; the flattening curve shows a speed that is falling away",
            "The straight line shows a stop",
            "The curve shows the faster object",
        ],
        "correct_index": 1,
        "why": "Constant gradient means constant speed; a gradient that shrinks towards zero means an object slowing towards a stop.",
    },
    {
        "id": "ks4-distance-time-graphs-s23",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A courier's plotted line starts at the origin, is straight, and reaches 450 m at 90 s. Determine how far she has gone at 30 s.",
        "options": [
            "50 m",
            "135 m",
            "450 m",
            "150 m",
        ],
        "correct_index": 3,
        "why": "The gradient is 5.0 m/s, so after 30 s she has covered 5.0 x 30 = 150 m. On a straight line the distance grows in proportion to the time.",
    },
    {
        "id": "ks4-distance-time-graphs-s24",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Walker X's line starts at the origin and walker Y's starts at 200 m at time zero. The two lines have the same gradient. Compare the two journeys.",
        "options": [
            "Y walks faster because its line is higher up the graph the whole way across",
            "X walks faster because its line begins at the origin",
            "They walk at the same speed; Y simply began 200 m further on",
            "Y is stationary at 200 m",
        ],
        "correct_index": 2,
        "why": "Speed is the gradient, not the height. Equal gradients mean equal speeds, and the 200 m is only a head start.",
    },
    {
        "id": "ks4-distance-time-graphs-s25",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A plotted line rises steadily from the origin to 60 m at 12 s. Calculate the speed and state the distance covered in the first 6.0 s.",
        "options": [
            "0.20 m/s and 30 m",
            "5.0 m/s and 60 m",
            "12 m/s and 30 m",
            "5.0 m/s and 30 m",
        ],
        "correct_index": 3,
        "why": "60 / 12 = 5.0 m/s, and half the time at a steady speed covers half the distance, so 30 m.",
    },
    {
        "id": "ks4-distance-time-graphs-s26",
        "subtopic_slug": "distance-time-graphs",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the average speed for a journey containing a stop is lower than the speed of the moving sections.",
        "options": [
            "The stop shortens the distance travelled, so the average must come down",
            "Average speed is read from the steepest part of the line",
            "The stopped time still counts in the total time, but adds no distance",
            "A stop makes the line steeper, and that steeper section pulls the whole average down",
        ],
        "correct_index": 2,
        "why": "The average divides total distance by total time. Waiting grows the denominator and leaves the numerator alone, so the answer falls.",
    },
    {
        "id": "ks4-distance-time-graphs-h05",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A delivery round is plotted as distance from the depot against time. The plot runs in one straight stretch to 90 m at 15 s and in a second, shallower stretch to 150 m at 45 s. Determine both section speeds and the overall average.",
        "options": [
            "6.0 m/s, then 2.0 m/s, with an average of 3.3 m/s",
            "6.0 m/s, then 3.3 m/s, with an average of 4.0 m/s",
            "6.0 m/s, then 2.0 m/s, with an average of 4.0 m/s, the mean of the two section speeds",
            "90 m/s, then 60 m/s, with an average of 150 m/s",
        ],
        "correct_index": 0,
        "why": "The sections give 90/15 = 6.0 m/s and 60/30 = 2.0 m/s, while the average uses the totals: 150/45 = 3.3 m/s. The mean of the two section speeds is wrong because the slower section lasts twice as long.",
    },
    {
        "id": "ks4-distance-time-graphs-h06",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A pupil says a curved line on this kind of graph must mean the object is changing direction. Evaluate this claim.",
        "options": [
            "Correct: only a change of direction can bend the line on this kind of graph",
            "Wrong: a curve means the speed is changing, not the direction",
            "Correct, because a straight line means one direction",
            "Wrong: a curve means the object has stopped",
        ],
        "correct_index": 1,
        "why": "The gradient is the speed, so a changing gradient is a changing speed. A change of direction shows up as the line turning downwards, not as a smooth bend.",
    },
    {
        "id": "ks4-distance-time-graphs-h07",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A car's plotted line reaches 240 m at 30 s and 600 m at 60 s, both stretches being straight. Determine how much the speed changes between them.",
        "options": [
            "It falls by 4.0 m/s, from 12 m/s to 8.0 m/s",
            "It rises by 4.0 m/s, from 8.0 m/s to 12 m/s",
            "It rises by 12 m/s",
            "It does not change, because both sections are straight lines on the plot",
        ],
        "correct_index": 1,
        "why": "The first gradient is 240/30 = 8.0 m/s; the second is 360/30 = 12 m/s, using the CHANGE in distance. Two straight sections can have two different gradients.",
    },
    {
        "id": "ks4-distance-time-graphs-h08",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A boat's distance from a harbour is plotted against time: straight up to 1200 m at 200 s, flat until 500 s, then straight back down to 0 m at 900 s. Determine the average speed and the average velocity over the 900 s.",
        "options": [
            "2.67 m/s and 2.67 m/s",
            "1.33 m/s and 0 m/s",
            "2.67 m/s and 0 m/s",
            "2.67 m/s and 2.67 m/s, because the boat kept moving apart from the flat section",
        ],
        "correct_index": 2,
        "why": "The path is 2400 m in 900 s, giving 2.67 m/s, but the boat finishes back in the harbour, so its displacement and therefore its average velocity are zero.",
    },
    {
        "id": "ks4-distance-time-graphs-h09",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Line R is straight with a gradient of 4.0 m/s. Line S curves upwards, starting shallower than R and finishing steeper. Determine when S is travelling faster than R.",
        "options": [
            "S is faster the whole way, because a curve beats a straight line",
            "S is never faster than R",
            "S is faster at the start and slower at the end",
            "S is faster once its own gradient has grown past 4.0 m/s, which happens late on",
        ],
        "correct_index": 3,
        "why": "Compare gradients, not heights. S starts below 4.0 m/s and rises through it, so it overtakes R in speed at the moment the two gradients match.",
    },
    {
        "id": "ks4-distance-time-graphs-h10",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the gradient of the line, and not how high the line has got, is what gives the speed.",
        "options": [
            "The height says only how far the object has got, while the steepness says how far it gets each second",
            "The height of the line is measured in seconds, so it cannot give a speed",
            "The height gives the acceleration instead",
            "The height and the gradient give the same value here",
        ],
        "correct_index": 0,
        "why": "A slow object that set off long ago can be higher up the graph than a fast one that has just started; only the steepness compares distance with time.",
    },
    {
        "id": "ks4-distance-time-graphs-h11",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A runner's plotted line rises steeply at first and then bends until it is flat at 2400 m after 600 s. Determine her average speed and describe how her speed changed.",
        "options": [
            "4.0 m/s, and her speed fell away until she stopped",
            "4.0 m/s, and her speed rose steadily to the end",
            "0.25 m/s, and her speed stayed the same",
            "4.0 m/s, and her speed fell away because a flat part of a plot shows a slow steady walk",
        ],
        "correct_index": 0,
        "why": "2400 / 600 = 4.0 m/s for the average. The gradient starts large and shrinks to zero, so she slowed to a halt rather than kept walking slowly.",
    },
    {
        "id": "ks4-distance-time-graphs-h12",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A cyclist's line is straight from the origin to (240 s, 1800 m). Determine the speed in kilometres per hour.",
        "options": [
            "7.5 km/h",
            "450 km/h",
            "2.08 km/h",
            "27 km/h",
        ],
        "correct_index": 3,
        "why": "The gradient is 1800/240 = 7.5 m/s, and 7.5 x 3.6 = 27 km/h. The 7.5 is correct but carries the wrong unit.",
    },
    {
        "id": "ks4-distance-time-graphs-h13",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A pupil finds a gradient by dividing the time by the distance. Explain what has gone wrong and what unit the answer carries.",
        "options": [
            "Nothing is wrong; either way round gives a speed in m/s",
            "The answer is an acceleration in m/s squared",
            "The division is upside down, so the answer is in s/m, a time for each metre",
            "The pupil should have multiplied, which would give a distance travelled in metres",
        ],
        "correct_index": 2,
        "why": "Gradient is the vertical change over the horizontal change. Inverting it inverts the unit too, and checking the unit is the quickest way to catch the slip.",
    },
    {
        "id": "ks4-distance-time-graphs-h14",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Bus 1's line is straight to 3000 m at 300 s. Bus 2 waits 100 s and then its line runs straight, also reaching 3000 m at 300 s. Determine bus 2's speed while it is moving.",
        "options": [
            "10 m/s",
            "15 m/s",
            "30 m/s",
            "7.5 m/s",
        ],
        "correct_index": 1,
        "why": "Bus 2 has only 200 s of moving time for the same 3000 m: 3000 / 200 = 15 m/s. Bus 1's 10 m/s is the lower figure because it used the full 300 s.",
    },
    {
        "id": "ks4-distance-time-graphs-h15",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A pupil claims that two straight lines meeting at a point means the two objects had the same speed at that moment. Evaluate this claim.",
        "options": [
            "Correct: a meeting point means the gradients are equal there",
            "Wrong: it means one object has stopped",
            "Wrong: it means they are at the same distance at the same time, not the same speed",
            "Correct, because both lines are straight",
        ],
        "correct_index": 2,
        "why": "A crossing is about position, not gradient. Equal speeds would show as parallel lines, which need never meet at all.",
    },
    {
        "id": "ks4-distance-time-graphs-h16",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Determine the average speed of a lorry whose plotted distance rises to 4.0 km at 200 s, holds steady until 400 s, then rises to 9.0 km at 700 s.",
        "options": [
            "16.7 m/s",
            "12.9 m/s",
            "20.0 m/s",
            "11.3 m/s",
        ],
        "correct_index": 1,
        "why": "9000 m over the full 700 s gives 12.9 m/s. The two moving sections run at 20.0 m/s and 16.7 m/s, both above the average because of the 200 s stop.",
    },
    {
        "id": "ks4-distance-time-graphs-h17",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A straight line runs from (0 s, 250 m) down to (100 s, 50 m). Determine the speed and the direction of travel.",
        "options": [
            "2.0 m/s, moving back towards the starting point",
            "2.0 m/s, moving away from the starting point",
            "3.0 m/s, moving back towards the starting point",
            "0.50 m/s, moving back towards the start, since the gradient is the time divided by the distance",
        ],
        "correct_index": 0,
        "why": "The distance reading falls by 200 m in 100 s, so the speed is 2.0 m/s and the object is heading back the way it came.",
    },
    {
        "id": "ks4-distance-time-graphs-h18",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A lift's motion is plotted as a series of straight sections with flat parts between them. Determine what that shape shows.",
        "options": [
            "The lift accelerates smoothly all the way to the top floor",
            "The lift must be faulty, because a real journey would give one smooth unbroken curve from start to finish",
            "The lift moves backwards during the flat parts of the plot",
            "The lift moves at a steady speed, waits, then moves again",
        ],
        "correct_index": 3,
        "why": "Each straight section is a run between floors at a near-constant speed, and each flat part is the lift standing still while its doors are open.",
    },
    {
        "id": "ks4-distance-time-graphs-h19",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "For a ball dropped from a window, a pupil draws a straight line through the origin. Explain why that shape cannot be right.",
        "options": [
            "A straight line would mean the ball speeds up, and a falling ball slows down",
            "A falling ball covers no distance, so the line should be flat",
            "The line should slope downwards because the ball goes down",
            "A falling ball speeds up, so the line should curve and get steeper",
        ],
        "correct_index": 3,
        "why": "A straight line claims one fixed speed, but a dropped ball gains about 9.8 m/s of speed every second, so each second adds more distance than the last.",
    },
    {
        "id": "ks4-distance-time-graphs-h20",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "P's line runs straight from the origin and reaches 600 m at 300 s. Q's line runs straight from 900 m at time zero down to 0 m at 450 s. Determine when the two walkers meet.",
        "options": [
            "225 s",
            "300 s",
            "450 s",
            "150 s",
        ],
        "correct_index": 0,
        "why": "Both walk at 2.0 m/s, so P is at 2.0t metres and Q at 900 - 2.0t. Setting those equal gives 4.0t = 900 and t = 225 s, which is where the two lines cross.",
    },
    {
        "id": "ks4-distance-time-graphs-h21",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain how two journeys can share an average speed and still be drawn as very differently shaped lines.",
        "options": [
            "Two journeys with the same average speed must have identical lines on the plot, so this cannot happen",
            "The average uses the totals only, so the shape in between can differ",
            "Average speed is read from the steepest section of the line",
            "The scales on the axes must have been drawn differently",
        ],
        "correct_index": 1,
        "why": "A steady plod and a sprint-and-rest can arrive at the same place at the same time; the average knows only the two end points.",
    },
    {
        "id": "ks4-distance-time-graphs-h22",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A cyclist's plot has a straight section of gradient 9.0 m/s followed by a curve that flattens to horizontal. Determine what the cyclist does.",
        "options": [
            "Rides at 9.0 m/s, then speeds up before stopping",
            "Rides at 9.0 m/s the whole way, since the gradient stays the same on this plot",
            "Rides at 9.0 m/s, then slows down and stops",
            "Rides at 9.0 m/s, then reverses back to the start",
        ],
        "correct_index": 2,
        "why": "The gradient falls from 9.0 m/s to zero, so the speed does the same. Horizontal means at rest, not reversing, which would need the line to fall.",
    },
    {
        "id": "ks4-distance-time-graphs-h23",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A line is straight from the origin to (5.0 min, 1.5 km). Determine the speed in m/s and how far the object would go in 8.0 min at that speed.",
        "options": [
            "0.20 m/s and 96 m",
            "5.0 m/s and 2400 m",
            "5.0 m/s and 4000 m",
            "300 m/s and 2400 m",
        ],
        "correct_index": 1,
        "why": "1500 m over 300 s is 5.0 m/s, and 8.0 min is 480 s, so 5.0 x 480 = 2400 m. Both quantities have to be converted before the division.",
    },
    {
        "id": "ks4-distance-time-graphs-h24",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two lines on one plot have the same gradient, but one of them is twice as long. Determine what is the same and what is different about the journeys.",
        "options": [
            "The speeds are different but both cover the same distance",
            "The longer line shows a faster journey",
            "The longer line shows a slower journey",
            "The speeds are equal; the longer line simply covers more distance over more time",
        ],
        "correct_index": 3,
        "why": "Gradient fixes the speed, and it is shared. Length along the line only says the journey went on for longer, taking it further.",
    },
    {
        "id": "ks4-distance-time-graphs-h25",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Determine the speed shown by a straight line passing through (10 s, 45 m) and (40 s, 180 m).",
        "options": [
            "4.5 m/s",
            "4.0 m/s",
            "6.0 m/s",
            "0.22 m/s",
        ],
        "correct_index": 0,
        "why": "Use the changes in both quantities: (180 - 45) / (40 - 10) = 135 / 30 = 4.5 m/s. Using 180/40 gives 4.5 here only by coincidence of the numbers chosen, so always take both differences.",
    },
    {
        "id": "ks4-distance-time-graphs-h26",
        "subtopic_slug": "distance-time-graphs",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A pupil describes a flat section of the line as the object moving at a steady speed. Explain the mistake.",
        "options": [
            "A flat section shows steady speed, so the description is right",
            "A flat section shows the object moving backwards steadily",
            "A flat section has zero gradient, so the object is at rest",
            "A flat section shows a steady speed only when the axes are the right way round on the plot",
        ],
        "correct_index": 2,
        "why": "Steady speed is a straight line with a gradient; steady position is a straight line with none. Being at rest is a special case of steady, but the speed is zero.",
    },
]
