"""Physics · Forces — the MRB-338 expansion, subtopic `resultant-forces`.

The baseline twelve already own: the definition of a resultant, a two-force
trolley sum, the zero-resultant motion statement, the unbalanced-forces
statement, a lift with equal tension and weight, a boat at 2200 N against
1500 N, a parachutist at 750 N against 300 N, a crate under 90 N east and
two westward forces, a skydiver just after the canopy opens, and two
perpendicular pairs (7.0 N with 24 N, and 25 N with 25 N).

This file stays strictly COLLINEAR — every force in it lies along one line,
because the vector-diagram and component work belongs to `resolving-forces`.
The fresh ground is: three- and four-force sums along a line; working
BACKWARDS from a stated resultant to a missing force; equilibrium read in
both directions (zero resultant permits rest OR steady speed, and steady
speed proves zero resultant); a resultant that opposes the motion and what
that does to the speed; the direction of the resultant setting the direction
of the change in velocity; and the difference between 'no resultant force'
and 'no forces at all'.

⚠️ Deliberately NOT here: F = m a and any mass or acceleration arithmetic
(`newtons-laws`), forces at an angle or resolved into components
(`resolving-forces`), and arrow diagrams (`free-body-diagrams`).
"""

TOPIC = "forces"
SUBJECT = "physics"

QUESTIONS = [
    {
        "id": "ks4-resultant-forces-e05",
        "subtopic_slug": "resultant-forces",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A box is pushed along a bench by two forces acting the same way, of 12 N and 8 N. Calculate the resultant force on the box.",
        "options": [
            "20 N, acting in the same direction as both of the pushes",
            "4 N in the direction of the push, because the smaller force is taken away from the larger one",
            "96 N in the direction of the push, found by multiplying",
            "0 N, because the two forces cancel each other out",
        ],
        "correct_index": 0,
        "why": "Forces along the same line and in the same direction simply add together: 12 + 8 = 20 N.",
    },
    {
        "id": "ks4-resultant-forces-e06",
        "subtopic_slug": "resultant-forces",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what is meant by balanced forces.",
        "options": [
            "Forces on an object that give a resultant of zero",
            "Forces that act on an object only when that object is completely still and nothing is moving it",
            "Forces that are all the same size but act in different directions",
            "Forces that act on two objects rather than one",
        ],
        "correct_index": 0,
        "why": "Balanced means the forces cancel out, so the resultant is zero and the object's velocity does not change.",
    },
    {
        "id": "ks4-resultant-forces-e07",
        "subtopic_slug": "resultant-forces",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A toy car has a force of 9 N acting to the right and a force of 4 N acting to the left. Calculate the resultant force.",
        "options": [
            "13 N to the right, because the two forces on the car are always added together",
            "36 N to the right, which comes from multiplying the two force values given",
            "5 N to the right",
            "5 N to the left",
        ],
        "correct_index": 2,
        "why": "Forces in opposite directions subtract: 9 - 4 = 5 N, acting in the direction of the larger force, which is to the right.",
    },
    {
        "id": "ks4-resultant-forces-e08",
        "subtopic_slug": "resultant-forces",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A parked van has a resultant force of zero acting on it. Describe what happens to the van.",
        "options": [
            "It starts to roll slowly",
            "It becomes heavier",
            "Its shape changes",
            "It stays exactly where it is, because a zero resultant cannot change the van's motion at all",
        ],
        "correct_index": 3,
        "why": "A resultant of zero means no change of velocity, so a van that is already stationary stays stationary.",
    },
    {
        "id": "ks4-resultant-forces-e09",
        "subtopic_slug": "resultant-forces",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two forces act on an object along the same line but in opposite directions, and they are not equal. State the direction of the resultant.",
        "options": [
            "Halfway between the two forces, because the resultant has to share the two directions equally",
            "In the direction of the larger of the two forces",
            "In the direction of the smaller force",
            "At right angles to both of the forces",
        ],
        "correct_index": 1,
        "why": "The smaller force cancels part of the larger one, so what is left over points the same way as the larger force.",
    },
    {
        "id": "ks4-resultant-forces-e10",
        "subtopic_slug": "resultant-forces",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Several forces act on a skateboard. Give the name for the one force that would have exactly the same effect as all of them.",
        "options": [
            "The resultant force",
            "The average force, which is worked out by sharing the total equally between all the forces acting",
            "The balanced force",
            "The applied force",
        ],
        "correct_index": 0,
        "why": "The resultant is the single force that could replace every force acting and leave the motion unchanged.",
    },
    {
        "id": "ks4-resultant-forces-e11",
        "subtopic_slug": "resultant-forces",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A rope is pulled with 15 N to the left and 15 N to the right. Calculate the resultant force on the rope.",
        "options": [
            "30 N, found by adding the two pulls on the rope together",
            "15 N to the left, because a pull to the left comes first",
            "225 N, found by multiplying the two pulls together",
            "0 N, because the two pulls cancel each other exactly",
        ],
        "correct_index": 3,
        "why": "Equal forces in opposite directions cancel exactly, so 15 - 15 = 0 N and the forces are balanced.",
    },
    {
        "id": "ks4-resultant-forces-e12",
        "subtopic_slug": "resultant-forces",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A trolley already rolling forward has a resultant force acting forwards. State the effect on the trolley.",
        "options": [
            "It keeps moving at the same steady speed",
            "It stops immediately and stays at rest",
            "It speeds up in the direction it is moving",
            "Its mass increases as it travels",
        ],
        "correct_index": 2,
        "why": "A resultant force changes the velocity, and one acting the same way as the motion makes the object go faster.",
    },
    {
        "id": "ks4-resultant-forces-s05",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Three sailors haul on the same mooring line in the same direction with forces of 210 N, 185 N and 160 N. Calculate the resultant pull on the line.",
        "options": [
            "555 N, acting in the direction that the three sailors are hauling",
            "135 N, found by taking the two smaller pulls away from the largest pull of the three",
            "210 N, because only the largest of the three pulls has any effect on the mooring line",
            "185 N, the middle value, because that is the average pull",
        ],
        "correct_index": 0,
        "why": "Forces acting along one line in the same direction add: 210 + 185 + 160 = 555 N.",
    },
    {
        "id": "ks4-resultant-forces-s06",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A car engine provides a driving force of 3000 N while the total resistive force on the car is 1200 N. Calculate the resultant force.",
        "options": [
            "4200 N forwards",
            "1800 N forwards, because opposing forces along one line are subtracted from one another",
            "1800 N backwards",
            "0 N, since the car is moving",
        ],
        "correct_index": 1,
        "why": "The two forces oppose one another, so 3000 - 1200 = 1800 N, acting in the direction of the larger force.",
    },
    {
        "id": "ks4-resultant-forces-s07",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "In a tug of war, the red team pulls with 450 N and the blue team pulls with 380 N in the opposite direction. Determine the resultant force on the rope.",
        "options": [
            "830 N towards the red team, because both teams are pulling on the very same length of rope",
            "70 N towards the blue team, since the rope moves away from the team that pulls hardest",
            "70 N acting towards the red team, the stronger of the two",
            "415 N towards the red team, the mean of the two pulls",
        ],
        "correct_index": 2,
        "why": "The pulls are in opposite directions, so 450 - 380 = 70 N, acting the way the stronger team is pulling.",
    },
    {
        "id": "ks4-resultant-forces-s08",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A sledge is pulled forwards by a rope while friction of 150 N acts backwards. The resultant force on the sledge is 200 N forwards. Calculate the pull in the rope.",
        "options": [
            "50 N, found by taking the resultant force away from the frictional force acting backwards",
            "200 N, because the resultant force and the rope's pull are always the same size as one another",
            "150 N, the same size as the friction",
            "350 N, since the pull must beat the friction and leave 200 N",
        ],
        "correct_index": 3,
        "why": "The pull has to overcome the 150 N of friction and leave 200 N over, so the pull is 150 + 200 = 350 N.",
    },
    {
        "id": "ks4-resultant-forces-s09",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "At the moment of launch a rocket's engines push upwards with 50 000 N while its weight is 30 000 N. Calculate the resultant force and give its direction.",
        "options": [
            "20 000 N upwards, acting in the direction of the larger force",
            "80 000 N upwards, because the thrust and the weight both act on the same rocket body",
            "20 000 N downwards, since weight acts on all objects",
            "30 000 N downwards, the size of the weight",
        ],
        "correct_index": 0,
        "why": "Thrust acts up and weight acts down, so 50 000 - 30 000 = 20 000 N, acting the way the larger force points.",
    },
    {
        "id": "ks4-resultant-forces-s10",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A tram travels along a straight level track at an unchanging 14 m/s. State the resultant force on the tram.",
        "options": [
            "Equal to the driving force of the tram's motor",
            "Zero, because its velocity is not changing at all",
            "A forward force, since it keeps moving forwards",
            "A backward force, since friction is present",
        ],
        "correct_index": 1,
        "why": "Constant velocity means no change of motion, and only a zero resultant leaves the velocity alone.",
    },
    {
        "id": "ks4-resultant-forces-s11",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A lift is speeding up as it rises. Compare the tension in the cable with the weight of the lift.",
        "options": [
            "The tension equals the weight exactly, because the cable has to support the whole of the lift",
            "The tension is smaller than the weight, since the lift is being lowered on the cable",
            "The tension is larger than the weight of the lift",
            "There is no tension while the lift is moving",
        ],
        "correct_index": 2,
        "why": "Speeding up while moving upwards needs a resultant force upwards, so the upward tension must be the larger of the two.",
    },
    {
        "id": "ks4-resultant-forces-s12",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A crate is pushed across a floor with a force of 80 N while friction opposes it with 80 N. Describe the motion of the crate.",
        "options": [
            "It speeds up steadily, as an 80 N push acts the whole time",
            "It slows and stops, because friction always wins in the end",
            "Its speed keeps changing, since two forces act at once",
            "It stays where it is, or carries on sliding at a steady speed",
        ],
        "correct_index": 3,
        "why": "The forces balance and the resultant is zero, so whatever the crate was doing it carries on doing.",
    },
    {
        "id": "ks4-resultant-forces-s13",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A book lies still on a table. The table pushes up on it with 12 N and its weight is 12 N downwards. State the resultant force on the book.",
        "options": [
            "0 N, so the motion of the book does not change at all",
            "24 N downwards, because both of the forces are acting on the very same book",
            "12 N upwards, as the table's push is doing something",
            "12 N downwards, because weight acts on everything",
        ],
        "correct_index": 0,
        "why": "Two equal forces in opposite directions on one object cancel, leaving a resultant of zero and the book at rest.",
    },
    {
        "id": "ks4-resultant-forces-s14",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A cyclist stops pedalling and applies the brakes while still rolling forwards. State the direction of the resultant force on her.",
        "options": [
            "Forwards, in the direction she is still travelling",
            "Backwards, acting against the direction of her motion",
            "There is no resultant force at all once a rider has stopped pedalling on a bicycle",
            "Downwards, because her weight is now the only force still acting on the bicycle",
        ],
        "correct_index": 1,
        "why": "Braking leaves only backward forces, so the resultant opposes her motion and her speed falls.",
    },
    {
        "id": "ks4-resultant-forces-s15",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A wind exerts 20 N eastwards on a sign while a guy rope pulls it with 35 N westwards. Determine the resultant force on the sign.",
        "options": [
            "55 N westwards, because the two forces acting on the sign are added to each other",
            "15 N eastwards, because the wind is the force that acts over the larger area",
            "15 N westwards",
            "700 N westwards, found by multiplying the two values",
        ],
        "correct_index": 2,
        "why": "The forces are opposite, so 35 - 20 = 15 N, in the direction of the 35 N rope, which is westwards.",
    },
    {
        "id": "ks4-resultant-forces-s16",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "An ice puck glides across a frictionless surface with no resultant force on it. Predict what it does next.",
        "options": [
            "It slows gradually until it stops moving",
            "It speeds up as it slides along the ice",
            "It curves round to one side as it travels",
            "It carries on at the same speed in the same straight line",
        ],
        "correct_index": 3,
        "why": "With no resultant force there is nothing to change its velocity, so both its speed and its direction stay the same.",
    },
    {
        "id": "ks4-resultant-forces-s17",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Four horizontal forces act on a raft along one line: 60 N and 25 N to the north, and 40 N and 45 N to the south. Determine the resultant.",
        "options": [
            "0 N, since 85 N north balances 85 N south",
            "170 N north, adding all four forces up",
            "85 N north, using the northward forces",
            "20 N south, using the two largest",
        ],
        "correct_index": 0,
        "why": "Collect each direction first: 60 + 25 = 85 N north and 40 + 45 = 85 N south, so the two totals cancel.",
    },
    {
        "id": "ks4-resultant-forces-s18",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A lorry driver notices the speedometer reading is falling steadily. State what this shows about the resultant force on the lorry.",
        "options": [
            "The resultant force on the lorry must have fallen to zero while it was travelling along",
            "It acts backwards, against the direction of the motion",
            "It acts forwards, because the lorry travels forwards",
            "It acts downwards, because the weight of the lorry is pressing on the road surface",
        ],
        "correct_index": 1,
        "why": "A falling speed is a change of velocity, and the resultant that causes it must point against the direction of travel.",
    },
    {
        "id": "ks4-resultant-forces-s19",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A raindrop falls at a steady speed for the last part of its journey to the ground. State what this tells you about the forces on it.",
        "options": [
            "Its weight must have fallen to zero at some point during the fall to the ground",
            "Air resistance must now be larger than the weight, which is why the drop stops speeding up",
            "Air resistance now equals its weight, so the resultant is zero",
            "No forces act on the raindrop at all once it has reached its final speed",
        ],
        "correct_index": 2,
        "why": "Steady speed means zero resultant, so the upward air resistance must now be exactly as big as the downward weight.",
    },
    {
        "id": "ks4-resultant-forces-s20",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A swimmer produces a forward force of 140 N while the water drags backwards on her with 95 N. Calculate the resultant force on the swimmer.",
        "options": [
            "235 N forwards, adding the two values that the question gives",
            "45 N backwards, because water resistance acts against any swimmer",
            "95 N backwards, the size of the drag force",
            "45 N forwards",
        ],
        "correct_index": 3,
        "why": "The forces are opposite, so 140 - 95 = 45 N, acting forwards because the forward force is the larger one.",
    },
    {
        "id": "ks4-resultant-forces-s21",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A train's motors provide 12 000 N forwards while the resistive forces total 12 000 N. Describe the motion of the train.",
        "options": [
            "It travels at a constant speed, or it stays where it is at rest",
            "It speeds up steadily, because its motors keep running",
            "It slows down steadily, because resistive forces always beat the forces driving a train forwards",
            "It stops at once, since the two forces cancel",
        ],
        "correct_index": 0,
        "why": "The forces balance, so the resultant is zero and the velocity is unchanged — which permits steady motion as well as rest.",
    },
    {
        "id": "ks4-resultant-forces-s22",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which statement about an object with a resultant force of zero is correct?",
        "options": [
            "No forces can be acting on it, because if any force were acting then it would have to move",
            "Its velocity does not change",
            "It must be losing speed steadily",
            "It must be completely stationary",
        ],
        "correct_index": 1,
        "why": "A zero resultant means no change of velocity; the object may be at rest or moving steadily, and forces may well be acting.",
    },
    {
        "id": "ks4-resultant-forces-s23",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A canal barge is moving forwards, and the resultant force on it acts backwards. Predict what happens to its speed.",
        "options": [
            "The speed rises, because a resultant force acting on any object makes that object go faster",
            "The speed stays the same, since the barge was already travelling forwards before this",
            "The speed falls",
            "The barge reverses at once",
        ],
        "correct_index": 2,
        "why": "A resultant against the motion reduces the velocity, so the barge slows; it would only reverse if it kept acting after the barge stopped.",
    },
    {
        "id": "ks4-resultant-forces-s24",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A cable car hangs at rest from its cable. Its weight is 24 000 N. State the tension in the cable.",
        "options": [
            "48 000 N, because the cable has to hold both the car and the weight of the car",
            "12 000 N, as the load is shared",
            "0 N, because nothing at all is moving",
            "24 000 N, matching the weight of the cable car",
        ],
        "correct_index": 3,
        "why": "At rest the resultant is zero, so the upward tension must be exactly equal to the 24 000 N downward weight.",
    },
    {
        "id": "ks4-resultant-forces-s25",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A shopping trolley is pushed forwards, and the resultant force on it points forwards. State the direction in which its velocity changes.",
        "options": [
            "Its velocity changes in the same direction as the resultant force, so the trolley gains speed forwards",
            "Its velocity changes backwards, opposite to the resultant",
            "Its velocity changes sideways, at right angles to the push",
            "Its velocity does not change at all",
        ],
        "correct_index": 0,
        "why": "The change in velocity is always in the direction of the resultant force, so a forward resultant means the trolley speeds up forwards.",
    },
    {
        "id": "ks4-resultant-forces-s26",
        "subtopic_slug": "resultant-forces",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two removal workers push a wardrobe along one line, one with 130 N forwards and the other with 90 N backwards. Calculate the resultant.",
        "options": [
            "220 N forwards, because two people are both pushing on the very same piece of furniture",
            "40 N forwards, acting in the direction of the larger of the two pushes",
            "40 N backwards, since the second worker is opposing the first one",
            "110 N forwards, the mean of the two pushes",
        ],
        "correct_index": 1,
        "why": "Opposite forces subtract: 130 - 90 = 40 N, acting forwards because the 130 N push is the larger.",
    },
    {
        "id": "ks4-resultant-forces-h05",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Three forces act along one line on a pallet: 60 N to the east, 25 N to the west and 35 N to the west. Determine the resultant force.",
        "options": [
            "120 N east, because every one of the three forces given acts on the same pallet at once",
            "60 N east, because only the single largest of the three forces has any effect here",
            "0 N, because the westward forces total 60 N",
            "10 N west",
        ],
        "correct_index": 2,
        "why": "The two westward forces total 25 + 35 = 60 N, which exactly balances the 60 N eastward force.",
    },
    {
        "id": "ks4-resultant-forces-h06",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A balloon has vertical forces of 18 N and 6 N upwards and 20 N and 4 N downwards. Determine the resultant force.",
        "options": [
            "48 N upwards, found by adding together every one of the four forces that the question lists",
            "24 N downwards, using only the two downward forces",
            "14 N upwards, using the largest force in each of the two directions",
            "0 N, so the balloon's velocity does not change",
        ],
        "correct_index": 3,
        "why": "Upwards gives 18 + 6 = 24 N and downwards gives 20 + 4 = 24 N, so the two totals cancel exactly.",
    },
    {
        "id": "ks4-resultant-forces-h07",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student writes: 'When forces act on an object the biggest one wins and the others make no difference.' Evaluate this statement.",
        "options": [
            "It is wrong: every force contributes to the resultant, and the smaller ones cancel part of the largest",
            "It is right, because only the largest force can change how an object moves",
            "It is wrong, because the smallest force is the one that decides the motion",
            "It is right whenever the object concerned happens to be stationary at the start",
        ],
        "correct_index": 0,
        "why": "The resultant is the combination of them all: 60 N against 25 N leaves 35 N, so the smaller force has changed the outcome.",
    },
    {
        "id": "ks4-resultant-forces-h08",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A lift descends at a constant speed. Compare the tension in the cable with the weight of the lift.",
        "options": [
            "The tension is smaller, because the lift is going down and a downward motion needs a downward resultant",
            "The tension is exactly equal to the weight",
            "The tension is larger, because the cable is holding the lift up",
            "There is no tension at all while the lift descends",
        ],
        "correct_index": 1,
        "why": "Constant speed means zero resultant, whichever way the lift is travelling, so the tension must match the weight exactly.",
    },
    {
        "id": "ks4-resultant-forces-h09",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A hot-air balloon has an upward force of 500 N from the air and a weight of 460 N. Determine the resultant force and its effect.",
        "options": [
            "960 N upwards, so the balloon rises very quickly indeed once it has been released",
            "40 N downwards, so the balloon sinks slowly back towards the ground below it",
            "40 N upwards, so the balloon speeds up as it rises",
            "0 N, so the balloon hovers at one height",
        ],
        "correct_index": 2,
        "why": "The forces oppose, so 500 - 460 = 40 N upwards, and a resultant upwards on a rising balloon makes it rise faster.",
    },
    {
        "id": "ks4-resultant-forces-h10",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A football rolls across level grass and gradually loses speed. Account for this using the idea of a resultant force.",
        "options": [
            "There is no resultant force, and a ball on grass slows anyway",
            "A forward resultant acts on the ball, and a forward resultant is what makes a moving object lose speed",
            "The weight of the ball provides a resultant along the grass",
            "Friction gives a resultant against the motion, which reduces the velocity",
        ],
        "correct_index": 3,
        "why": "Nothing pushes the ball on, so friction from the grass leaves a backward resultant, and that steadily reduces its speed.",
    },
    {
        "id": "ks4-resultant-forces-h11",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Justify the claim that an object with a zero resultant force cannot be changing speed.",
        "options": [
            "Because a zero resultant means no forces are acting, and an object with no forces cannot move at all",
            "Because only a resultant force can change velocity, so with none the speed stays as it is",
            "Because a zero resultant always brings a moving object gently to a halt",
            "Because a zero resultant reverses any motion the object already had",
        ],
        "correct_index": 1,
        "why": "A change of velocity requires a resultant force; with a resultant of zero there is nothing to produce that change.",
    },
    {
        "id": "ks4-resultant-forces-h12",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A skydiver falls for several seconds before opening her parachute. Describe how the resultant force on her changes during that time.",
        "options": [
            "It stays exactly the same, because her weight does not change during the fall",
            "It falls, because air resistance grows as she speeds up",
            "It grows, because she is travelling faster all the time",
            "It reverses, because drag becomes bigger than her weight",
        ],
        "correct_index": 1,
        "why": "Weight stays the same but the upward drag rises with speed, so the downward resultant gets smaller as she falls.",
    },
    {
        "id": "ks4-resultant-forces-h13",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Assess the claim that a moving object must always have a resultant force pushing it along in the direction of travel.",
        "options": [
            "It is correct, because an object that had no resultant force acting along its path would stop almost at once",
            "It is correct, but only while the object happens to be speeding up",
            "It is incorrect: an object moving at constant velocity has no resultant force at all",
            "It is incorrect, because a moving object has no forces on it",
        ],
        "correct_index": 2,
        "why": "A resultant is needed to CHANGE velocity, not to maintain it, so steady motion in a straight line needs no resultant at all.",
    },
    {
        "id": "ks4-resultant-forces-h14",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A submarine has a weight of 90 000 N, an upthrust of 90 000 N, a forward thrust of 5000 N and a drag of 2000 N. Determine the resultant force.",
        "options": [
            "187 000 N, found by adding every one of the four forces that are listed in the question",
            "7000 N forwards, adding the thrust and the drag together",
            "180 000 N upwards, using the vertical pair",
            "3000 N forwards",
        ],
        "correct_index": 3,
        "why": "The vertical forces cancel, leaving the horizontal pair: 5000 - 2000 = 3000 N in the direction of the thrust.",
    },
    {
        "id": "ks4-resultant-forces-h15",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A barge on a canal is acted on by 250 N forwards, 180 N backwards and a further 95 N backwards. Determine the resultant force.",
        "options": [
            "25 N backwards",
            "525 N forwards, because all three of the forces are acting on the very same barge",
            "70 N forwards, using the largest backward force only",
            "25 N forwards, because the forward force is the largest single value",
        ],
        "correct_index": 0,
        "why": "Backwards totals 180 + 95 = 275 N against 250 N forwards, so 275 - 250 = 25 N and the resultant acts backwards.",
    },
    {
        "id": "ks4-resultant-forces-h16",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A stone is thrown vertically upwards and is still rising. State the direction of the resultant force on it.",
        "options": [
            "Upwards, in the direction the stone is moving",
            "Downwards, because its weight still acts on it",
            "There is no resultant while the stone rises",
            "Sideways, away from the thrower's hand",
        ],
        "correct_index": 1,
        "why": "Once it has left the hand the only forces are weight and air resistance, both acting downwards while it rises, so it slows.",
    },
    {
        "id": "ks4-resultant-forces-h17",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Distinguish between an object with no forces acting on it and an object with a resultant force of zero.",
        "options": [
            "There is no difference between the two at all, because both phrases describe exactly the same situation",
            "The first is always stationary while the second is always in motion",
            "The first has nothing acting; the second has forces that cancel",
            "The first must be in space while the second has to be on the ground",
        ],
        "correct_index": 2,
        "why": "Several large forces can cancel to give zero, so a zero resultant does not mean an absence of forces — though both give no change of velocity.",
    },
    {
        "id": "ks4-resultant-forces-h18",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "An airship hovers at a fixed height above a stadium. Deduce the relationship between the upward and downward forces on it.",
        "options": [
            "The upward force must be the larger, because the airship is up in the air and has to stay there",
            "The downward force must be the larger, because weight acts on everything that is near the Earth",
            "The forces need not be related, since a hovering object is not moving anywhere at all",
            "They are equal, so the resultant is zero",
        ],
        "correct_index": 3,
        "why": "Hovering is unchanging velocity, which requires a resultant of zero, so the upward and downward forces must match.",
    },
    {
        "id": "ks4-resultant-forces-h19",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A conveyor belt carries a parcel along at an unchanging speed. State the resultant force on the parcel and explain your reasoning.",
        "options": [
            "Zero, because the velocity of the parcel is not changing at all",
            "A forward force, because the belt carries the parcel along",
            "A backward force, because friction acts between the parcel and the surface of the moving belt",
            "It cannot be worked out without the mass of the parcel",
        ],
        "correct_index": 0,
        "why": "The reasoning runs from the motion to the forces: an unchanging velocity is only possible when the resultant is zero.",
    },
    {
        "id": "ks4-resultant-forces-h20",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A dinghy is driven forwards by 320 N from its outboard motor, and the resultant force on it is 75 N forwards. Determine the total resistive force.",
        "options": [
            "395 N, adding the two values given in the question together to find the total",
            "245 N",
            "75 N, the same size as the resultant force acting on the dinghy",
            "320 N, the same as the driving force",
        ],
        "correct_index": 1,
        "why": "The resistance cancels part of the driving force, so it is 320 - 75 = 245 N acting backwards.",
    },
    {
        "id": "ks4-resultant-forces-h21",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two tugs pull a ship along one line, one forwards with 8000 N and one backwards with 3000 N, while the water resists with 2000 N. Determine the resultant.",
        "options": [
            "13 000 N forwards, adding all three values",
            "5000 N forwards, using the two tugs alone",
            "3000 N forwards, once both of the backward forces have been taken from the forward pull",
            "6000 N forwards, using the largest values",
        ],
        "correct_index": 2,
        "why": "Backwards totals 3000 + 2000 = 5000 N, so the resultant is 8000 - 5000 = 3000 N in the direction of the leading tug.",
    },
    {
        "id": "ks4-resultant-forces-h22",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student concludes from a set of balanced forces that the object they act on has to be at rest. Assess this conclusion.",
        "options": [
            "It is sound, because forces that balance one another are unable to keep any object in motion",
            "It is sound, but only on the condition that friction is acting somewhere in the situation",
            "It is unsound, because balanced forces mean the object has to be slowing down instead",
            "It is unsound, because balanced forces permit steady motion in a straight line as well as rest",
        ],
        "correct_index": 3,
        "why": "Balanced forces prevent a CHANGE of velocity, and a velocity that does not change may be any steady value, including zero.",
    },
    {
        "id": "ks4-resultant-forces-h23",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A remote-controlled boat moving north has the resultant force on it switched from north to south. Predict what happens to the boat.",
        "options": [
            "It slows, stops, and then gains speed to the south",
            "It reverses its direction of travel the instant that the resultant force on it is switched round",
            "It carries on northwards at exactly the same speed, since it was already moving before the switch",
            "It halts straight away and then stays where it is",
        ],
        "correct_index": 0,
        "why": "A resultant opposing the motion reduces the velocity to zero and then builds it up in the new direction; nothing happens instantly.",
    },
    {
        "id": "ks4-resultant-forces-h24",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a physicist is able to replace several forces acting on one object with a single resultant.",
        "options": [
            "Because the forces are all the same size, so replacing them with one of them changes nothing",
            "Because the single resultant has the same effect on the motion as all of them together",
            "Because only one force can act on an object at any one moment in time",
            "Because the largest of the forces is the only one that has any effect",
        ],
        "correct_index": 1,
        "why": "That equivalence is the definition of a resultant, and it is what makes force problems tractable.",
    },
    {
        "id": "ks4-resultant-forces-h25",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the resultant force on a parachutist in the first moment after she jumps with the resultant once she is falling at a steady speed.",
        "options": [
            "It is zero at first and largest later on",
            "It is the same at both of those two moments",
            "It is largest at first and then falls to zero later",
            "It acts upwards at first and downwards later on",
        ],
        "correct_index": 2,
        "why": "At the start she is barely moving so air resistance is tiny and the resultant is nearly her whole weight; at steady speed the two balance.",
    },
    {
        "id": "ks4-resultant-forces-h26",
        "subtopic_slug": "resultant-forces",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A lift travelling upwards is slowing down as it nears the top floor. State the direction of the resultant force on it.",
        "options": [
            "Upwards, because the lift is travelling upwards while all of this is happening",
            "There is no resultant force, because the lift is about to come to a stop anyway",
            "Sideways, along the direction of the floor of the lift car",
            "Downwards, against the direction of motion",
        ],
        "correct_index": 3,
        "why": "The resultant always points the way the velocity is changing; a rising lift that is slowing has its velocity changing downwards.",
    },
]
