"""Physics · Magnetism and electromagnetism — the MRB-338 expansion for
`induced-potential`.

The baseline twelve already own the NAME of the generator effect, one action
that induces a pd, the second finger of Fleming's right-hand rule, the slip
rings of an a.c. generator, the force needed to push a magnet at a coil, 25
revolutions per second giving 25 Hz, a commutator turning the output into
pulsing d.c., a reversed sweep reversing the current, the copper tube, the
200-turn/0.50 s against 400-turn/2.0 s comparison, what makes a device a motor
rather than a generator, and the bicycle generator scaled from 4.0 m/s to
10 m/s.

This file takes the ground those twelve leave: the other two fingers of the
right-hand rule and why it is the right hand at all; the four factors, one at
a time and then as a list; the null cases (a still magnet, a wire moved along
the lines, a coil with a gap in it, a coil adrift inside a uniform field);
Lenz's law as a direction rule and then as an energy argument, with the near
face of the coil traced both on the way in and on the way out; the rotating
coil's peak and zero positions, its frequency from revolutions per minute and
from a period, and why its output can never be re-shaped by speed alone; and
the eddy-current family — a ring, a cut ring, a braking fin, an induction hob
and a spun aluminium disc.

Transformers, the National Grid, and every NAMED generating device in service
belong to the `transformers` and `uses-generator-effect` leaves and appear
nowhere here; the one two-coil row is plain mutual induction with no core, no
turns ratio and no equation. The motor effect and Fleming's LEFT-hand rule are
named only where a row exists to tell the two hands apart.
"""

TOPIC = "magnetism"
SUBJECT = "physics"

QUESTIONS = [
    # ══ easier · e05–e18 ═════════════════════════════════════════════════
    # The two remaining fingers, which hand and why, the four factors one at
    # a time, and the null cases a student meets first.
    {
        "id": "ks4-induced-potential-e05",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A student sets up the right-hand rule to work out an induced current. State the quantity that the first finger is pointed along.",
        "options": [
            "The direction of the magnetic field, running from north to south",
            "The direction in which the wire itself is being moved through the magnetic field",
            "The direction of the induced current, which flows along the moving wire",
            "The direction of the force that the magnetic field exerts on the wire while it is moving",
        ],
        "correct_index": 0,
        "why": "In both of Fleming's rules the First finger is the Field. It is set along the field lines, which always run from the north pole of the magnet to the south pole.",
    },
    {
        "id": "ks4-induced-potential-e06",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State what the thumb represents when Fleming's right-hand rule is applied to a wire that is generating a current.",
        "options": [
            "The direction of the magnetic field running between the poles of the magnet",
            "The direction in which the conductor is being moved through the magnetic field",
            "The direction of the current that the induced potential difference drives round the circuit",
            "The strength of the magnetic field that passes through the moving conductor",
        ],
        "correct_index": 1,
        "why": "ThuMb is Motion. In the generator effect the motion is the cause: you move the wire, and a current follows. The second finger gives that induced current.",
    },
    {
        "id": "ks4-induced-potential-e07",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State which hand is used for the generator effect, and why the other hand is not the one used.",
        "options": [
            "The left hand, because the induced current is what the rule is designed to find",
            "The right hand, because current always flows clockwise in a generator coil",
            "The right hand, because the left-hand rule is for the force on a wire that carries a current",
            "Either hand, as long as the first finger is pointed along the field lines",
        ],
        "correct_index": 2,
        "why": "Right hand for the generator effect: motion in, current out. The left-hand rule is the motor effect, where a current already flows and you want the force on the wire.",
    },
    {
        "id": "ks4-induced-potential-e08",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State the four factors that change the size of the potential difference induced in a coil of wire.",
        "options": [
            "The wire's resistance, its length, its thickness and its temperature",
            "The size of the current in the coil, the resistance of the wire and the coil's own mass",
            "The supply voltage, the resistance of the coil, the thickness of the wire and the room temperature",
            "Speed of movement, field strength, number of turns, and the area of the coil",
        ],
        "correct_index": 3,
        "why": "Move it faster, use a stronger magnet, add turns, or use a wider coil, and the induced pd rises. Resistance affects the current that flows, but not the pd that is induced.",
    },
    {
        "id": "ks4-induced-potential-e09",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A bar magnet is placed inside a coil of wire and then held completely still. State what the coil's meter reads.",
        "options": [
            "Zero, because the field through the coil is not changing while the magnet is still",
            "A steady reading, because the magnet's field is still passing through the middle of the coil",
            "A reading that slowly falls away as the magnet gradually loses strength",
            "A small alternating reading, because the coil's own field keeps flipping over",
        ],
        "correct_index": 0,
        "why": "A field on its own induces nothing. Only a CHANGING field through the coil induces a pd, so a stationary magnet gives a reading of exactly zero however strong it is.",
    },
    {
        "id": "ks4-induced-potential-e10",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A straight wire is moved steadily along the direction of the magnetic field lines instead of across them. State what is induced.",
        "options": [
            "The largest pd possible, because the wire stays inside the field for the whole move",
            "No potential difference at all, because the wire cuts no field lines when it moves along them",
            "A potential difference half the size of the one produced by moving across the lines",
            "A steady direct potential difference in place of an alternating one",
        ],
        "correct_index": 1,
        "why": "Cutting field lines is what induces a pd. A wire sliding along the lines never crosses any of them, so nothing at all is induced no matter how fast it goes.",
    },
    {
        "id": "ks4-induced-potential-e11",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "In this topic, state what the word induced means when it is applied to a potential difference.",
        "options": [
            "Pushed into the wire by the chemical reactions taking place inside a battery",
            "Carried into the conductor by the electrons that flow out of the magnet's north pole",
            "Produced in a conductor by a changing magnetic field, not by a cell",
            "Made permanent in the metal, so that the conductor keeps its potential difference afterwards",
        ],
        "correct_index": 2,
        "why": "Induced means caused from outside without contact. The changing field does the work; no chemical cell and no electrical connection to the magnet is needed at all.",
    },
    {
        "id": "ks4-induced-potential-e12",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A coil is connected to a sensitive centre-zero meter and a magnet is pushed into it. Describe what the needle does.",
        "options": [
            "It climbs steadily and then stays at its highest reading afterwards",
            "It moves smoothly to a steady reading and holds there while the magnet sits inside",
            "It swings to one side and then to the other, twice over for every single push of the magnet",
            "It flicks to one side while the magnet is moving, then settles back at zero",
        ],
        "correct_index": 3,
        "why": "The deflection lasts only while the magnet moves. A centre-zero meter is used because the needle can swing either way, showing the direction of the induced current.",
    },
    {
        "id": "ks4-induced-potential-e13",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A magnet is clamped so that it cannot move, and the coil is moved over it instead. State whether a potential difference is induced.",
        "options": [
            "Yes, because the field through the coil still changes as the coil moves",
            "No, because only a moving magnet can induce a potential difference in a coil",
            "Yes, but the induced potential difference is much smaller than when the magnet moves",
            "No, because the coil carries no current of its own, so there is nothing for the field to act on",
        ],
        "correct_index": 0,
        "why": "What always matters is the change in field through the coil. Moving the coil past a fixed magnet changes it just as effectively as moving the magnet past a fixed coil.",
    },
    {
        "id": "ks4-induced-potential-e14",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State how many times the induced potential difference reaches a peak during one complete turn of a generator coil.",
        "options": [
            "Once, at the moment when the coil passes through the upright position",
            "Twice, once in each direction, with the pd falling right through zero in between",
            "Four times in all, because each of the coil's two long sides produces a peak of its own",
            "Never, because the output of a generator holds at one steady value",
        ],
        "correct_index": 1,
        "why": "The sides cut the field lines fastest twice per turn, half a revolution apart, and they are moving opposite ways each time. So one turn gives a positive peak and a negative one.",
    },
    {
        "id": "ks4-induced-potential-e15",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A magnet is pushed into a coil twice as fast as before, with nothing else altered. State the effect on the induced potential difference.",
        "options": [
            "It stays exactly the same, because the magnet itself has not been changed",
            "It falls to half its old value, since the magnet spends less time in the coil",
            "It doubles, because the field through the coil is now changing at twice the rate it did before",
            "It rises to four times its old value, in the same way that kinetic energy does",
        ],
        "correct_index": 2,
        "why": "The induced pd depends on the rate of change of the field. Double the speed, double the rate, double the pd. The time spent inside the coil is not what counts.",
    },
    {
        "id": "ks4-induced-potential-e16",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "The bar magnet used in a coil experiment is swapped for a stronger one and moved at the same speed. State the effect.",
        "options": [
            "Nothing changes, because only the speed of the magnet matters here",
            "The induced potential difference falls, because a stronger field opposes the motion more",
            "The induced potential difference reverses its direction, although its size is completely unchanged",
            "The induced potential difference gets larger, and so does the induced current",
        ],
        "correct_index": 3,
        "why": "A stronger magnet means more field lines cut in the same time, so a larger pd. With the same circuit resistance, a larger pd drives a larger current as well.",
    },
    {
        "id": "ks4-induced-potential-e17",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Extra turns of wire are wound onto a coil, and the same magnet is then moved into it at the same speed as before.",
        "options": [
            "The induced potential difference is bigger, because every turn adds to the total",
            "The induced potential difference is unchanged, since the turns do not matter",
            "The frequency of the output rises, but its peak size stays the same",
            "The induced potential difference is smaller, because the extra turns add more resistance to it",
        ],
        "correct_index": 0,
        "why": "Each turn has a pd induced across it and the turns are in series, so the pds add. Extra resistance does reduce the current, but it does not reduce the induced pd.",
    },
    {
        "id": "ks4-induced-potential-e18",
        "subtopic_slug": "induced-potential",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "A coil, a magnet and a meter are connected with no cell anywhere in the circuit. State whether a current can flow.",
        "options": [
            "No, because every circuit needs a cell before any current can flow in it",
            "Yes, because moving the magnet always induces a potential difference that drives the current itself",
            "No, because a meter will only ever respond to a current sent to it by a battery",
            "Yes, but only if the coil has first been magnetised by a current from a cell",
        ],
        "correct_index": 1,
        "why": "The induced pd is the supply. Move the magnet and the coil becomes the source, driving a current round the circuit with no chemical cell present anywhere.",
    },

    # ══ standard · s05–s18 ═══════════════════════════════════════════════
    # Lenz's law as a direction rule and as an energy argument, the near face
    # traced in and out, the rotating coil's peak, zero and frequency, and
    # the two null cases that need a reason rather than a recall.
    {
        "id": "ks4-induced-potential-s05",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "State the rule that fixes the direction of a current induced in a complete circuit.",
        "options": [
            "It flows so that its own field lines up with the field of the approaching magnet",
            "It always flows clockwise when it is viewed from the end that the magnet is entering",
            "It always flows so that its own magnetic field opposes the change that made it",
            "It flows in whichever direction offers the lowest resistance through the turns of the coil",
        ],
        "correct_index": 2,
        "why": "This is Lenz's law. The induced current is never a passive result: it sets up a field that fights the change, whichever way round that change happens to be.",
    },
    {
        "id": "ks4-induced-potential-s06",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A north pole is pushed towards one end of a coil that forms a complete circuit. State what that end of the coil becomes.",
        "options": [
            "A south pole, which pulls the magnet inwards and speeds it up",
            "Neither pole, because a coil can only become magnetic when a battery drives a current",
            "A north pole at first and then a south pole, because the induced current keeps on reversing",
            "A north pole, which repels the approaching magnet and opposes its motion",
        ],
        "correct_index": 3,
        "why": "Lenz's law again: the coil opposes the approach, so the face nearest the magnet must become the same pole and push back. A south face would pull the magnet in for free.",
    },
    {
        "id": "ks4-induced-potential-s07",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "That same north pole is then pulled back out of the coil. State what the near end of the coil becomes as the magnet leaves.",
        "options": [
            "A south pole, which attracts the magnet and resists its removal",
            "A north pole, which pushes the magnet away and helps it leave more quickly",
            "A south pole, but only after the magnet has completely left the inside of the coil",
            "Neither pole, because the induced current stops the moment the magnet begins to move away",
        ],
        "correct_index": 0,
        "why": "Now the change being opposed is the magnet leaving, so the coil tries to hold it. The face flips to south and attracts it back, and the induced current reverses.",
    },
    {
        "id": "ks4-induced-potential-s08",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why conservation of energy requires an induced effect to oppose, rather than help, the motion that causes it.",
        "options": [
            "A current must always oppose the supply that is driving it around a circuit",
            "If it helped, the magnet would speed up by itself and energy would come from nowhere",
            "Energy is always conserved inside a magnet, so its field strength can never be allowed to fall",
            "Opposing the motion stores energy inside the coil, where it is then trapped",
        ],
        "correct_index": 1,
        "why": "Suppose the induced field pulled the magnet in. It would accelerate, induce more, accelerate more, and give out electrical energy forever from nothing. That cannot happen.",
    },
    {
        "id": "ks4-induced-potential-s09",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A rectangular coil is rotated steadily in a uniform magnetic field. State the position at which the induced potential difference peaks.",
        "options": [
            "When the plane of the coil sits at right angles to the direction of the field",
            "When the coil has turned exactly one quarter of a full revolution from rest",
            "When the plane of the coil lies along the field, so that its sides cut the field lines fastest",
            "At the instant when the coil is momentarily still at the top of its rotation",
        ],
        "correct_index": 2,
        "why": "With the coil edge-on to the field, its long sides sweep straight across the lines and cut them at the greatest rate. That is the instant of maximum induced pd.",
    },
    {
        "id": "ks4-induced-potential-s10",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "During one complete turn of a generator coil, state the position where the output potential difference falls to zero.",
        "options": [
            "At the moment the coil passes through its fastest point of travel",
            "When the plane of the coil lies along the field lines, so they run through the turns",
            "Only at the very start and at the very end of a turn, because the coil is stationary then",
            "When the coil's plane is at right angles to the field and its sides move along it",
        ],
        "correct_index": 3,
        "why": "Here the sides are travelling parallel to the field lines for an instant, so no lines are cut and the induced pd is zero. It happens twice in every full rotation.",
    },
    {
        "id": "ks4-induced-potential-s11",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A generator's coil is turned at twice its previous rate. State the effect on both the frequency and the peak potential difference.",
        "options": [
            "Both always double: twice as many turns each second and twice the rate of cutting",
            "The frequency doubles but the peak potential difference stays the same",
            "The frequency doubles while the peak potential difference is halved, keeping the power fixed",
            "The peak potential difference doubles while the frequency is left unchanged",
        ],
        "correct_index": 0,
        "why": "Turning faster does two things at once. One cycle per turn means the frequency follows the turning rate, and the faster cutting of field lines raises the peak pd too.",
    },
    {
        "id": "ks4-induced-potential-s12",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A coil and a magnet can be moved in either order. Explain why it makes no difference which of the two is the part that moves.",
        "options": [
            "Both arrangements work because the magnet's field is far stronger than the coil's own",
            "What always matters is the relative movement, since that is what changes the field in the coil",
            "Moving the coil works, but it gives a pd half the size of a moving magnet's",
            "Either one works, because the meter cannot tell which way round the circuit is wired",
        ],
        "correct_index": 1,
        "why": "Only the relative motion of coil and magnet changes the field threading the coil. Which one an observer calls stationary is a choice about the frame, not about the physics.",
    },
    {
        "id": "ks4-induced-potential-s13",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A coil has a gap cut in its wire so that no current can flow, and a magnet is then moved into it. State what happens.",
        "options": [
            "No potential difference appears, because the circuit is no longer complete",
            "A current flows across the gap as a spark, driven by the induced potential difference",
            "A potential difference is still induced, but no current can flow",
            "A potential difference and a current both appear, because the coil's own field bridges the gap",
        ],
        "correct_index": 2,
        "why": "Inducing a pd needs only a changing field and a conductor. A complete circuit is needed for a current, so the pd appears across the gap with nothing flowing.",
    },
    {
        "id": "ks4-induced-potential-s14",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "An oscilloscope shows a generator's output completing one full cycle in 0.025 s. Calculate the frequency of that output.",
        "options": [
            "0.025 Hz",
            "400.0 Hz",
            "25 Hz",
            "40.0 Hz",
        ],
        "correct_index": 3,
        "why": "Frequency is one divided by the period: f = 1 / 0.025 = 40 Hz. Dividing by 0.025 is the same as multiplying by 40, so 400 Hz is a slipped decimal point.",
    },
    {
        "id": "ks4-induced-potential-s15",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A straight wire is swept between the poles of a strong horseshoe magnet. State the sweep direction that induces the largest potential difference.",
        "options": [
            "At right angles to the field lines, cutting as many of them as possible",
            "Parallel to the field lines, moving straight across from one pole to the other",
            "At an angle of forty-five degrees to the field lines, which balances the effects",
            "In a slow circle inside the gap, so that the wire stays inside the field for much longer",
        ],
        "correct_index": 0,
        "why": "The pd depends on how quickly field lines are cut, and a wire moving at ninety degrees to the lines cuts the greatest number of them in any given time.",
    },
    {
        "id": "ks4-induced-potential-s16",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A coil carries a current that is steadily changing. A second, separate coil is held close beside it and connected to a meter.",
        "options": [
            "No reading, because only a moving magnet is able to induce anything in a coil",
            "A reading, because the changing field from the first coil passes through the second",
            "No reading, because the two coils are not joined by any wire so nothing can pass across the gap",
            "A steady reading that does not depend on how the first current is changing",
        ],
        "correct_index": 1,
        "why": "The first coil's current makes a magnetic field, and a changing current makes a changing field. That changing field through the second coil induces a pd in it.",
    },
    {
        "id": "ks4-induced-potential-s17",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why a coil turning steadily in a uniform field produces an output that changes all the time rather than a steady one.",
        "options": [
            "The field between the magnet's poles gets stronger and weaker as the coil turns",
            "The coil speeds up and slows down twice during each complete revolution it makes",
            "The coil's angle to the field changes constantly, so the rate at which lines are cut changes",
            "The slip rings swap the connections over twice in every single turn of the coil",
        ],
        "correct_index": 2,
        "why": "The field is uniform and the turning is steady, but the angle is not. Edge-on the sides cut lines quickly; face-on they cut none, so the output sweeps between the two.",
    },
    {
        "id": "ks4-induced-potential-s18",
        "subtopic_slug": "induced-potential",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A lab generator makes 1800 complete turns every minute. Calculate the frequency of the alternating output it produces.",
        "options": [
            "108000 Hz",
            "1800.0 Hz",
            "60 Hz",
            "30.0 Hz",
        ],
        "correct_index": 3,
        "why": "One turn gives one cycle, so convert turns per minute to turns per second: 1800 / 60 = 30 turns each second, giving 30 Hz. Multiplying by 60 instead gives 108000 Hz.",
    },

    # ══ harder · h05–h18 ═════════════════════════════════════════════════
    # The eddy-current family, rate against size, two evaluations, and the
    # three predictions a student has to reason out rather than recall.
    {
        "id": "ks4-induced-potential-h05",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A magnet is dropped through a horizontal copper ring lying flat on a stand. Explain why it slows noticeably as it passes the ring.",
        "options": [
            "A current induced in the ring sets up a field that pushes back on the falling magnet",
            "Copper is weakly magnetic, so the ring attracts the magnet and holds it back",
            "The ring becomes permanently magnetised by the magnet and then clings to it as it drops past",
            "Air trapped in the hole of the ring cushions the magnet as it drops through",
        ],
        "correct_index": 0,
        "why": "The approaching magnet changes the field through the ring, inducing a current round it. By Lenz's law that current's field opposes the approach, so the magnet is slowed.",
    },
    {
        "id": "ks4-induced-potential-h06",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "That same copper ring is then cut right through at one point. Explain why the falling magnet is no longer slowed as it passes.",
        "options": [
            "Cutting the copper destroys the magnetism that the ring had built up earlier",
            "The cut breaks the loop, so no induced current can flow and no opposing field is set up at all",
            "The gap adds so much resistance that the induced potential difference falls to zero",
            "The two cut ends repel each other, which pushes the ring clear of the magnet",
        ],
        "correct_index": 1,
        "why": "A pd is still induced round the cut ring, but with the loop broken no current flows. No current means no magnetic field of its own, so there is nothing to oppose the fall.",
    },
    {
        "id": "ks4-induced-potential-h07",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A drop-tower ride is slowed by passing metal fins between strong magnets, with nothing ever touching. Explain how it is brought to rest.",
        "options": [
            "The magnets attract the metal fins directly, and that attraction drags the car back",
            "Air squeezed between the magnets and the fins forms a cushion that slows the car",
            "Eddy currents induced in the fins make fields that oppose the motion",
            "The fins become magnetised on the way down and are then repelled by every magnet they pass",
        ],
        "correct_index": 2,
        "why": "As a fin sweeps past, the field through it changes and loops of current are induced inside the metal. Their fields oppose the motion, so the car loses kinetic energy.",
    },
    {
        "id": "ks4-induced-potential-h08",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "An induction hob heats a steel pan placed on it but leaves a glass dish on the same ring completely cold. Explain why.",
        "options": [
            "Steel is heavier than glass, so it takes in much more heat from the ring",
            "The hob's ring gets hot and steel carries that heat away much faster than glass does",
            "Steel is attracted to the magnets beneath the surface, and that pulling is what warms the pan",
            "The changing field induces currents in the steel, and glass conducts none",
        ],
        "correct_index": 3,
        "why": "The hob makes a rapidly changing magnetic field. That induces currents in a conducting base, which heat it. Glass is an insulator, so no current and no heating.",
    },
    {
        "id": "ks4-induced-potential-h09",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "The same field change happens in a 300-turn coil in 0.20 s and in a 900-turn coil in 0.60 s. Compare the two induced potential differences.",
        "options": [
            "They are the same, because three times the turns meets three times the time",
            "The 900-turn coil gives three times as much, because it has three times the turns",
            "The 300-turn coil gives nine times as much once the turns and the time are combined",
            "The 900-turn coil gives nine times as much, because the turns matter far more than the timing",
        ],
        "correct_index": 0,
        "why": "Induced pd rises with turns and falls with the time taken. Tripling the turns multiplies by 3; tripling the time divides by 3. The two effects cancel exactly.",
    },
    {
        "id": "ks4-induced-potential-h10",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why a large field change made very slowly can induce a smaller potential difference than a small change made quickly.",
        "options": [
            "Large changes always induce large potential differences, whatever the timing",
            "Induced pd depends on how fast the field through the coil changes, not on how much",
            "A slow change gives the coil's own resistance more time to use up the potential difference",
            "The coil cools down during a slow change, and a cold coil always induces less",
        ],
        "correct_index": 1,
        "why": "It is the rate that counts. A huge change spread over a long time gives a low rate; a tiny change in an instant gives a high rate and therefore the larger induced pd.",
    },
    {
        "id": "ks4-induced-potential-h11",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A student claims that a bigger magnet always gives a bigger induced current. Evaluate this claim.",
        "options": [
            "Always correct, because the size of the magnet fixes the current on its own",
            "Correct, provided that the magnet is moved at the same speed as it was before",
            "Partly right: a stronger field raises the induced pd, but the current also depends on resistance",
            "Always wrong, because the induced current depends only on how fast the magnet moves",
        ],
        "correct_index": 2,
        "why": "Size and strength are not the same thing either. Even with a genuinely stronger field, a high-resistance circuit still limits the current the larger pd can drive.",
    },
    {
        "id": "ks4-induced-potential-h12",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "An aluminium disc spun close to a strong magnet slows down, even though aluminium is not attracted to magnets. Explain the drag on the disc.",
        "options": [
            "Aluminium is weakly magnetic after all, so the magnet grips it",
            "The magnet's field drives air against the spinning disc, and the friction slows it",
            "Spinning the disc magnetises it permanently, so that it is then attracted towards the magnet",
            "Eddy currents induced in the disc set up fields that oppose its turning",
        ],
        "correct_index": 3,
        "why": "Aluminium is a good conductor even though it is not magnetic. Spinning it through the field induces eddy currents, and those currents make fields that resist the spin.",
    },
    {
        "id": "ks4-induced-potential-h13",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "State where the electrical energy leaving a generator comes from, and explain the part played by the opposing force.",
        "options": [
            "Work done against the opposing force moves energy from a kinetic store to the circuit",
            "The coil creates new energy, which is why no force is needed to turn it",
            "The magnet's permanent store of magnetic energy drains a little with every turn of the coil",
            "Energy comes from the warmth of the wire, which cools as the current flows",
        ],
        "correct_index": 0,
        "why": "The opposing force is the pathway, not a nuisance. Whoever turns the coil must work against it, and that work is exactly the energy delivered to the circuit.",
    },
    {
        "id": "ks4-induced-potential-h14",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A generator's coil is turned at a steadily increasing rate. Predict the shape of the output trace on an oscilloscope.",
        "options": [
            "The waves get closer together but keep exactly the same height throughout",
            "The waves become both taller and closer together, because the peak pd and the frequency both rise",
            "The waves get taller while staying the same distance apart on the screen",
            "The trace flattens into a straight line once the turning becomes fast enough",
        ],
        "correct_index": 1,
        "why": "Speeding up raises the frequency, so the cycles crowd together, and raises the rate of cutting field lines, so each peak grows. Both changes happen at once.",
    },
    {
        "id": "ks4-induced-potential-h15",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A student wants a higher frequency from a generator while keeping the peak potential difference the same. State why turning it faster will not do this.",
        "options": [
            "Frequency and peak pd are both fixed by the magnet, so a speed change alters neither",
            "Turning it faster lowers the peak pd instead, so the two effects simply cancel each other out",
            "Faster turning raises the rate of cutting as well, so the peak pd rises too",
            "The frequency is set by the slip rings and cannot be changed by the turning speed",
        ],
        "correct_index": 2,
        "why": "Speed controls both quantities together, so it cannot separate them. To hold the peak down while raising the frequency, change something else: fewer turns, or a weaker magnet.",
    },
    {
        "id": "ks4-induced-potential-h16",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A coil is pushed into a magnetic field and then pulled out again at exactly the same steady speed. Compare the two induced currents.",
        "options": [
            "Equal in size and flowing in the same direction on each journey",
            "The current on the way out is larger, because pulling the coil free needs more force",
            "A current flows only on the way in, because the coil holds on to the field once it is inside",
            "They are equal in size on both journeys, but they flow in opposite directions",
        ],
        "correct_index": 3,
        "why": "The same field change at the same rate gives the same size of pd each time. The change reverses, though, so by Lenz's law the induced current reverses with it.",
    },
    {
        "id": "ks4-induced-potential-h17",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A small coil is moved steadily about inside a very large uniform magnetic field and never reaches its edge. State the potential difference induced.",
        "options": [
            "None at all, because the field through the coil never changes at any point",
            "A steady pd, because the coil is moving through a magnetic field the whole time",
            "An alternating pd, with a frequency that depends on how quickly the coil is moved",
            "A pd that grows the further the coil travels, because it passes more and more field lines",
        ],
        "correct_index": 0,
        "why": "Uniform means identical everywhere, so sliding the coil about leaves the field through it exactly as it was. No change means no induced pd, however fast the coil moves.",
    },
    {
        "id": "ks4-induced-potential-h18",
        "subtopic_slug": "induced-potential",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A student says that a generator creates electrical energy out of nothing at all. Evaluate this statement.",
        "options": [
            "Right, because the magnet keeps its strength however long it runs",
            "Wrong: a generator only transfers energy between stores and never creates any",
            "Right, because the induced pd appears in a circuit that has no cell supplying it at all",
            "Wrong, because a generator always destroys some of the energy it is given",
        ],
        "correct_index": 1,
        "why": "Energy cannot be created or destroyed, only transferred. A generator moves energy from the kinetic store of the turning coil into the circuit, and wastes some as heat.",
    },
]
