"""Physics · Magnetism and electromagnetism — the MRB-338 expansion for
`poles-of-a-magnet`.

The baseline twenty already own the ferromagnetic list, like-poles-repel, the
non-contact force, steel for a permanent magnet, the two poles, the definition
of an induced magnet, force falling with distance, repulsion as the only proof,
induced magnetism in a second bar, domain saturation from over-stroking, the
steel-and-aluminium can sorter, the electromagnet core as an induced magnet,
the two-bars-attract-either-way deduction, hard against soft materials, the
nail dropping when the current stops, aligned against random domains, Curie
heating in a Bunsen flame, alternating strokes, a dropped magnet weakening,
and one paperclip holding a second. None of those is asked again here.

This file takes the ground they leave free: unlike poles attracting, what a
magnet cut in half becomes and why a single pole has never been obtained, a
suspended magnet settling north–south, steel as an iron alloy, induced
magnetism always being attraction, MAKING and UNMAKING a magnet with a coil
rather than by stroking, keepers and how magnets are stored, which pole is
induced at which end, neodymium against steel, everyday objects that do and do
not respond (fridge doors, coins, phone cases, card stripes, aluminium cans),
Newton's third law on a magnet and a nail, the pole-pair rule set beside
electric charge, the hot core of the Earth, and the practical-skills work —
an anomalous paperclip count, a pull force falling away with a card gap, and
what a quoted pull force actually means.
"""

TOPIC = "magnetism"
SUBJECT = "physics"

QUESTIONS = [
    # ---------------------------------------------------------------- easier
    {
        "id": "ks4-poles-of-a-magnet-e09",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two bar magnets lie end to end on a bench, arranged so that a north pole faces a south pole. State the direction of the force between them.",
        "options": [
            "They are pulled towards one another, because unlike poles attract",
            "They are pushed apart, because two poles held near each other always repel",
            "There is no force on either magnet until the two poles are touching",
            "They are pushed sideways, at right angles to the line joining them",
        ],
        "correct_index": 0,
        "why": "A north pole and a south pole attract. Only two poles of the same kind repel.",
    },
    {
        "id": "ks4-poles-of-a-magnet-e10",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A magnet is offered in turn to four metal blocks, made of copper, brass, aluminium and iron. State which block it picks up.",
        "options": [
            "The brass block, since brass contains copper and zinc together",
            "The copper block, since copper is one of the best conductors of electricity there is",
            "The iron block, since iron is one of the few magnetic metals",
            "All four blocks, since a magnet will pick up any metal at all",
        ],
        "correct_index": 2,
        "why": "Only iron, cobalt, nickel and their alloys such as steel are attracted. Copper, brass and aluminium are not magnetic.",
    },
    {
        "id": "ks4-poles-of-a-magnet-e11",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A bar magnet is cut cleanly in half across its middle. State what each half is afterwards.",
        "options": [
            "One half holds a north pole and the other half holds a south pole",
            "Each half is now a shorter magnet with a north pole and a south pole",
            "Neither half is a magnet any longer, because the north and south poles have been separated",
            "Each half keeps its magnetism but has only one pole left at the cut end",
        ],
        "correct_index": 1,
        "why": "Cutting a magnet makes two smaller magnets. New poles appear at the cut faces, so each piece still has both a north and a south pole.",
    },
    {
        "id": "ks4-poles-of-a-magnet-e12",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A bar magnet is hung from a long thread so that it can turn freely, well away from any other magnet or piece of steel. State the direction it finally settles in.",
        "options": [
            "It settles pointing east and west, at right angles to the Earth's field",
            "It keeps turning slowly and never settles in one particular direction",
            "It settles with one end pointing roughly north and the other roughly south",
            "It settles pointing straight down, because it is pulled towards the ground",
        ],
        "correct_index": 2,
        "why": "The magnet lines itself up with the Earth's magnetic field, so its north-seeking pole ends up pointing roughly north.",
    },
    {
        "id": "ks4-poles-of-a-magnet-e13",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Steel is a mixture of iron with a small amount of carbon. State why a steel paperclip is still attracted to a magnet.",
        "options": [
            "Because the carbon in the steel is itself a strongly magnetic element",
            "Because the clip has been bent into a shape that traps a magnetic field",
            "Because steel is mostly iron, and iron is a magnetic material",
            "Because every alloy is magnetic, whatever the metals that have been mixed together to make it",
        ],
        "correct_index": 2,
        "why": "Steel is an alloy of iron, and the iron in it is ferromagnetic, so steel behaves as a magnetic material.",
    },
    {
        "id": "ks4-poles-of-a-magnet-e14",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "An iron washer becomes an induced magnet while it sits in the field of a nearby bar magnet. State whether it is then attracted to or repelled by that bar magnet.",
        "options": [
            "Repelled, because the washer takes on the same pole as the end of the bar magnet nearest to it",
            "Attracted, because induced magnetism always produces attraction",
            "Attracted at first, and then repelled once the washer is fully magnetised",
            "Neither, because an induced magnet feels no force from the magnet that induced it",
        ],
        "correct_index": 1,
        "why": "The pole induced in the washer is always opposite to the nearby pole, so the force on an induced magnet is always attraction.",
    },
    {
        "id": "ks4-poles-of-a-magnet-e15",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A magnet is slid about underneath a wooden table, and a steel paperclip resting on the table top slides about with it. State what this shows.",
        "options": [
            "That wood becomes a magnet whenever a magnet is held underneath it",
            "That the clip is heavier than the magnetic force acting on it",
            "That the magnet must be touching the clip through a small hole hidden in the table top",
            "That the magnetic force acts at a distance, and through the wood",
        ],
        "correct_index": 3,
        "why": "Magnetism is a non-contact force. It acts across a gap, and wood does not stop it.",
    },
    {
        "id": "ks4-poles-of-a-magnet-e16",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State one everyday object that relies on a permanent magnet to do its job.",
        "options": [
            "A glass window pane, which is held in its frame magnetically",
            "A cupboard door catch, which snaps shut onto a small steel plate",
            "A wooden ruler, which is used for drawing straight pencil lines",
            "A plastic kettle, which heats the water inside it using an electric heating element",
        ],
        "correct_index": 1,
        "why": "A magnetic catch uses a permanent magnet to attract a steel plate on the door, holding it closed.",
    },

    # -------------------------------------------------------------- standard
    {
        "id": "ks4-poles-of-a-magnet-s07",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Bar magnets are usually stored in pairs with a small soft iron keeper laid across each end. Explain the purpose of the keepers.",
        "options": [
            "They label which end is the north pole so that the pair is not mixed up",
            "They stop the magnets sliding about and scratching one another in the box",
            "They complete a loop for the field, so the domains stay lined up and the magnets keep their strength",
            "They magnetise the pair a little more strongly every day they are left in the box",
        ],
        "correct_index": 2,
        "why": "The keepers give the field a path of magnetic material to run through. With no free poles left exposed, the domains are not gradually disturbed.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s08",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A technician needs to turn a plain steel bar into a permanent magnet, and has a coil of wire and a d.c. supply available. Describe what should be done.",
        "options": [
            "Place the bar inside the coil and pass a steady direct current through the coil",
            "Place the bar inside the coil and leave the supply switched off for at least several hours",
            "Wrap the coil round the bar and connect only one end of it to the supply",
            "Hold the bar a metre from the coil and switch the supply on and off repeatedly",
        ],
        "correct_index": 0,
        "why": "The steady current makes a strong, steady field inside the coil. That field lines up the domains in the steel, and the steel is hard enough to keep them lined up.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s09",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how a magnetised steel bar can be demagnetised using a coil that carries alternating current.",
        "options": [
            "Drop the bar through the middle of the coil as quickly as possible while the current is switched off",
            "Hold the bar still in the middle of the coil until the coil becomes warm",
            "Place the bar in the coil, then draw it slowly out of the field while the current flows",
            "Connect the coil to a much larger direct current and leave the bar inside it",
        ],
        "correct_index": 2,
        "why": "The alternating field keeps reversing, and it becomes weaker as the bar is withdrawn. The domains are left pointing in all directions instead of one.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s10",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The north pole of a bar magnet is held a centimetre from one end of an unmagnetised iron rod. State which pole appears in the near end of the rod, and give the reason.",
        "options": [
            "A north pole, because the rod copies the pole that is nearest to it",
            "A south pole, because the induced pole is always the one that gives attraction",
            "No pole at all, because a rod this short cannot hold two separate poles",
            "Both poles at once, because the near end is where the field enters the rod",
        ],
        "correct_index": 1,
        "why": "Induced magnetism always produces attraction, so the pole induced nearest the magnet must be the opposite kind to it.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s11",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Headphone magnets are made from a neodymium alloy rather than from magnetised steel. Suggest the advantage this gives the designer.",
        "options": [
            "Neodymium conducts electricity well, so the very same magnet can also carry the audio signal to the coil",
            "Neodymium cannot be demagnetised by heating, unlike every other magnetic material that exists",
            "Neodymium is not attracted to steel, so the magnet will not stick to the case",
            "A neodymium magnet gives a much stronger field for its size, so the earpiece can be small",
        ],
        "correct_index": 3,
        "why": "Neodymium alloys hold a far stronger magnetisation than steel, so a small, light magnet can still drive the coil hard.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s12",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A screwdriver is stroked several times in one direction with the pole of a strong magnet, and afterwards it holds a steel screw on its tip. Explain what the stroking has done.",
        "options": [
            "It has worn a rough surface onto the metal tip, so that the screw is gripped there by friction",
            "It has lined up the domains in the steel, so the screwdriver is now itself a magnet",
            "It has left a thin coating of magnetic material from the magnet on the tip",
            "It has warmed the tip, and warm steel holds a screw better than cold steel",
        ],
        "correct_index": 1,
        "why": "Stroking turns the domains in the steel so that they point the same way. The screwdriver becomes a weak permanent magnet and attracts the screw.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s13",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Four paperclips hang in a chain below a bar magnet, but a fifth clip will not stay on the end. Explain why the chain cannot be made longer.",
        "options": [
            "The magnet has used up its magnetism on the four clips already hanging",
            "Each clip is a weaker induced magnet than the one above it, and the fifth is too weak to hold",
            "The clips further down are colder, and cold steel cannot be magnetised at all",
            "Only four clips can ever hang from one magnet, whatever the magnet is made of",
        ],
        "correct_index": 1,
        "why": "Each clip is magnetised by the field of the one above, which is already weaker. The induced magnetism dies away down the chain until it cannot support another clip.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s14",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A magnetic catch holds a cupboard door firmly shut, yet once the door has swung open by a few millimetres it feels almost free. Explain this.",
        "options": [
            "The catch is switched off automatically as soon as the door starts to move",
            "The door becomes lighter once it is moving, so less force is needed to hold it",
            "The magnetic force falls away very sharply over only the first few millimetres of gap",
            "The steel plate on the door loses its magnetism the moment contact is broken",
        ],
        "correct_index": 2,
        "why": "Magnetic attraction weakens rapidly with distance, so a gap of a millimetre or two leaves very little force.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s15",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the needle of a walker's compass is made from a magnetically hard material and not from soft iron.",
        "options": [
            "A soft iron needle would rust away, and a rusty needle cannot turn freely on its pivot",
            "A magnetically hard material weighs a good deal less, so the needle can spin on a much finer pivot",
            "A soft iron needle would lose its own magnetism, so it would no longer point north",
            "A hard material lines itself up with the Earth's field far faster than a soft one does",
        ],
        "correct_index": 2,
        "why": "The needle has to stay a permanent magnet. Soft iron only stays magnetic while it sits in a strong field, so it would be useless away from one.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s16",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what is meant by a magnetic domain in a piece of iron.",
        "options": [
            "A tiny region in which the atoms all behave as magnets pointing the same way",
            "The region of space outside the iron in which its own magnetic field can still be detected",
            "A small pocket of a different metal left in the iron when it was smelted",
            "The narrow band at each end of the iron where its two poles are found",
        ],
        "correct_index": 0,
        "why": "A domain is a small region inside the material where the atomic magnets already point together. Magnetising the material lines the domains up with each other.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s17",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A maglev train is held clear of its track by magnets fixed to the train and to the track. State how the poles must be arranged, and why.",
        "options": [
            "Unlike poles facing, because attraction is a stronger force than repulsion",
            "Like poles facing, because two poles of the same kind always push each other apart",
            "One magnet only, because a single pole is enough to lift a train",
            "The poles facing sideways, because a vertical force would derail the train",
        ],
        "correct_index": 1,
        "why": "Like poles repel. Facing north to north, or south to south, gives an upward push that lifts the train off the rails.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s18",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A note held to a fridge door by a small magnet falls straight off when the same magnet is tried on an aluminium window frame. Explain the difference.",
        "options": [
            "The fridge door is steel, which is magnetic, while aluminium is not",
            "The window frame is colder than the fridge door, so the magnet is much weaker when held there",
            "The fridge door is painted, and paint is needed for a magnet to grip a surface",
            "The window frame is vertical, and a magnet only works on a horizontal surface",
        ],
        "correct_index": 0,
        "why": "A fridge door has a steel outer skin, and steel is attracted to a magnet. Aluminium is not a magnetic material, so there is no force on the magnet.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s19",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The magnet inside a loudspeaker has to give the same field strength after ten years of use. State the property the magnet material must have.",
        "options": [
            "It must conduct electricity well, so that the signal passes through it",
            "It must be magnetically soft, so that its field can follow the signal",
            "It must expand very little when it becomes warm, so that the gap stays exactly the same width",
            "It must be magnetically hard, so that its domains stay lined up over time",
        ],
        "correct_index": 3,
        "why": "A magnetically hard material keeps its domain alignment once it has been magnetised, so the permanent magnet does not fade.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s20",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A magnetic car phone holder is sold with a thin steel plate to be glued inside the phone case. Explain why the plate is needed.",
        "options": [
            "The plate spreads the weight of the phone out so that the glue does not peel away from it",
            "A phone case is plastic or aluminium, and neither of those is attracted to a magnet",
            "The plate turns the phone case into a permanent magnet of its own",
            "The plate stops the magnet's field from reaching the phone and damaging its screen or its battery",
        ],
        "correct_index": 1,
        "why": "The magnet can only attract a magnetic material. The steel plate gives it something ferromagnetic to pull on.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s21",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student is handed a bar of an unknown grey metal and asked to find out whether it is a magnetic material. Describe the test and the result that would prove it is.",
        "options": [
            "Weigh the bar, then weigh it again after a day: a magnetic material gains mass",
            "Hold a compass at each end in turn: a magnetic material turns the needle right round",
            "Bring a known magnet near the bar: a magnetic material is pulled towards it",
            "Drop the bar onto a hard floor: a magnetic material rings at a higher pitch",
        ],
        "correct_index": 2,
        "why": "Attraction to a magnet is the test for a magnetic material. The bar itself need not be a magnet for this to work.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s22",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Iron, cobalt and nickel are attracted to magnets, while copper, zinc and tin are not. State what the first three metals have that the others do not.",
        "options": [
            "A much higher density than the metals that are not attracted",
            "Domains that can be lined up so that their magnetism adds together",
            "Atoms that carry an overall electric charge rather than being electrically neutral",
            "A far higher melting point, which is what allows magnetism to survive",
        ],
        "correct_index": 1,
        "why": "Ferromagnetic metals contain domains — regions whose atomic magnets already point together — which an external field can line up.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s23",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The steel hull of a new ship is found to be weakly magnetised before the ship has left the shipyard. Suggest how this happened.",
        "options": [
            "The paint used on ships contains iron, which magnetises as it dries",
            "Sea water carries a small electric current through the hull, and that current magnetises the steel",
            "Steel always becomes magnetised the moment it is shaped into a curve",
            "Hammering and riveting the steel while it sat in the Earth's field lined up its domains",
        ],
        "correct_index": 3,
        "why": "Knocks let the domains move, and the Earth's weak field gives them a direction to settle into. Steel is hard enough to keep that alignment.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s24",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A UK one penny coin minted in 2010 is copper-plated steel, while one minted in 1985 is solid bronze. Predict which coin a magnet picks up, and explain.",
        "options": [
            "Both coins, because the copper on the outside of each one is attracted to a magnet",
            "Neither coin, because coins are made deliberately from metals that are not magnetic",
            "The 1985 coin, because older coins were made before non-magnetic alloys were used",
            "The 2010 coin, because its core is steel and the thin copper plating is not in the way",
        ],
        "correct_index": 3,
        "why": "Copper and bronze are not magnetic. The steel core of the newer coin is, and a thin non-magnetic coating does not block the field.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s25",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A bank card carries its details in a dark stripe, and cardholders are warned to keep the card away from strong magnets. Explain the warning.",
        "options": [
            "The stripe stores data as a pattern of magnetisation, which a strong field can scramble",
            "The stripe is made of steel, and a strong magnet would bend the whole card badly out of shape",
            "The stripe carries a small electric current of its own, which a strong magnet would short out completely",
            "A strong magnet would heat the stripe enough to melt the plastic of the card underneath it",
        ],
        "correct_index": 0,
        "why": "The stripe is a magnetic coating whose pattern of tiny magnetised regions holds the data. An outside field can re-align those regions and destroy it.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s26",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two bar magnets are kept side by side in a drawer with both north poles at the same end. Explain why this arrangement weakens them over time.",
        "options": [
            "Each magnet cools the other one down, and a cold magnet gradually loses all of its strength over time",
            "Each magnet's field runs backwards through its neighbour, slowly disturbing its domains",
            "The two magnets share one field, so each one ends up with half the strength",
            "Touching magnets rub together, and that friction slowly wears the magnetic layer clean away",
        ],
        "correct_index": 1,
        "why": "Side by side with like poles together, each magnet sits in a field that opposes its own magnetisation, which gradually pulls the domains out of line.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s27",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "An iron bar is held upright and tapped along its length with a hammer for a minute. A compass held near it afterwards is deflected. Explain the result.",
        "options": [
            "The hammering made the bar hot, and hot iron gives out a magnetic field",
            "The compass is responding to the hammer, which is the magnetised object here",
            "The hammering jolted the domains free, and the Earth's field settled them one way",
            "The hammering added iron from the hammer head onto the surface of the bar",
        ],
        "correct_index": 2,
        "why": "Mechanical shock lets the domains move. Held in line with the Earth's field, they settle preferentially along it, leaving the bar weakly magnetised.",
    },
    {
        "id": "ks4-poles-of-a-magnet-s28",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The core of the Earth is mostly iron at a temperature above 4000 degrees Celsius. Explain why that iron cannot be acting as a permanent magnet.",
        "options": [
            "Iron that hot is liquid, and only a solid can contain any domains at all",
            "The core is under such enormous pressure that its atoms are squeezed far too close together to be magnetic",
            "Iron only becomes magnetic once it has been stroked with another magnet first",
            "Far above the Curie temperature the domains cannot stay lined up, so the iron is not magnetic",
        ],
        "correct_index": 3,
        "why": "Heating past the Curie temperature gives the atoms so much energy that domain alignment is destroyed. The Earth's field comes from motion of the molten iron instead.",
    },

    # ---------------------------------------------------------------- harder
    {
        "id": "ks4-poles-of-a-magnet-h07",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A grey bar is known to be either a permanent magnet or a piece of unmagnetised iron, and no other equipment is available. Explain why hanging it from a thread settles the question.",
        "options": [
            "Only the magnet will hang level, because magnetism lifts one end slightly",
            "Only the magnet will turn to lie north and south, because it lines up with the Earth's field",
            "Only the iron will swing, because unmagnetised iron is the lighter of the two",
            "Only the iron will turn, because a magnet is held still by its own field",
        ],
        "correct_index": 1,
        "why": "A suspended permanent magnet lines up with the Earth's field. An unmagnetised bar has no poles of its own and so settles in no particular direction.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h08",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student writes that a magnet pulls on an iron nail but the nail does not pull back on the magnet. Evaluate this statement.",
        "options": [
            "Correct — only the magnet has poles, so only the magnet can exert a force",
            "Correct — the nail is too light for its pull on the magnet to exist",
            "Incorrect — the nail pulls on the magnet with an equal and opposite force",
            "Incorrect — the nail pulls back, but with a much smaller force than the magnet's",
        ],
        "correct_index": 2,
        "why": "The two forces are an interaction pair: equal in size, opposite in direction, and acting on different objects. Mass does not change that.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h09",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why no amount of breaking up a magnet has ever produced a piece carrying a north pole with no south pole.",
        "options": [
            "The magnetism comes from domains, and every one of those has both poles itself",
            "The two poles are held together by a force far too strong for any hammer or saw to break apart",
            "A north pole is always destroyed first, so it never survives being separated",
            "Breaking a magnet destroys its magnetism, so no poles of any kind remain",
        ],
        "correct_index": 0,
        "why": "Magnetism arises from the atoms themselves, each of which behaves as a tiny magnet with two ends. Dividing the material only ever gives smaller two-pole magnets.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h10",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A permanent magnet fitted in a car engine bay is specified for use up to 150 degrees Celsius. Explain why a maximum working temperature has to be quoted.",
        "options": [
            "Above it the magnet would expand so much that it would no longer fit its housing",
            "Above it the magnet would begin to conduct electricity and short the circuit out",
            "Heat gives the domains energy to slip out of line, so the magnet never fully recovers",
            "Heat makes a magnet swap its poles over, so the device would run backwards",
        ],
        "correct_index": 2,
        "why": "Thermal energy lets domains rotate away from their aligned direction. The loss is not recovered on cooling, and above the Curie temperature the magnetism goes entirely.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h11",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two identical steel bars are magnetised, one by stroking with a bar magnet and one by being placed inside a powerful coil. The coil-made magnet turns out much stronger. Explain why.",
        "options": [
            "The coil warms the bar, and a warm bar takes up magnetism far more readily than a cold one ever does",
            "The coil leaves a little of its copper on the bar, which adds to the magnetism",
            "Stroking only magnetises the outer surface, while a coil magnetises the whole thickness of the bar",
            "The coil's field is stronger and reaches the whole bar at once, so more domains end up aligned",
        ],
        "correct_index": 3,
        "why": "How strongly a bar is magnetised depends on how many of its domains are turned into line. A strong field acting on the whole bar aligns far more of them than a hand-held pole passing along it.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h12",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student counts the paperclips one magnet holds on five days and records 9, 9, 8, 9 and 3. Explain what the value of 3 most likely is and what should be done about it.",
        "options": [
            "It is an anomalous result, probably a slipped clip, and it should be repeated and left out of the mean",
            "It is evidence that the magnet has been demagnetised, so the earlier results are wrong",
            "It is the most reliable result, because a smaller number is easier to count accurately",
            "It is a random error that cancels out, so all five results should simply be averaged",
        ],
        "correct_index": 0,
        "why": "A single value far away from four close results is anomalous. Good practice is to repeat that measurement and exclude it from the mean rather than average it in.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h13",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A company sells rings that clip round a copper water pipe and claims they treat the water magnetically. Explain why a physicist would doubt any magnetic effect on the pipe itself.",
        "options": [
            "Copper is not a magnetic material, so a magnet exerts no force on the pipe at all",
            "Copper is magnetic, but only when a current is flowing along the pipe wall",
            "The pipe would have to be earthed before a magnetic field could enter it",
            "A magnet cannot act through the water inside, so the ring would have no effect",
        ],
        "correct_index": 0,
        "why": "Only iron, cobalt, nickel and their alloys are ferromagnetic. A static magnet held against copper produces no force on it.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h14",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "An iron nail hangs from the north pole of a magnet and holds a second nail below it. Deduce the pole at the free lower tip of the first nail.",
        "options": [
            "A south pole, matching the south pole induced at its upper end",
            "A north pole, because the upper end is a south pole and the two must differ",
            "Neither pole, because an induced magnet carries only one pole at a time",
            "A north pole, because an induced magnet copies the pole of whatever magnetised it",
        ],
        "correct_index": 1,
        "why": "The end nearest the magnet's north pole is induced as a south pole, so that it is attracted. The far end of the same induced magnet must then be a north pole.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h15",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A person squeezes two magnets together with like poles facing, holds them still, and then lets go. Describe the energy transfers involved.",
        "options": [
            "No energy is transferred at any stage, because the magnets never touch each other",
            "Work done in pushing them together is stored, then transferred to a kinetic store on release",
            "Energy is created by the magnets as they fly apart, which is where the motion comes from",
            "The person's energy is transferred entirely to the thermal store of the two magnets",
        ],
        "correct_index": 1,
        "why": "Pushing against repulsion does work, which is stored in a magnetic potential store. Releasing them transfers that store to kinetic energy as they accelerate apart.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h16",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student writes that a stainless steel sink cannot contain any iron, because a fridge magnet will not stick to it. Evaluate this claim.",
        "options": [
            "Correct — nothing containing iron can fail to attract a magnet",
            "Correct — stainless steel is an alloy of chromium and nickel with no iron in it",
            "Incorrect — the sink is mostly iron, but that kind of stainless steel is not ferromagnetic",
            "Incorrect — the magnet is simply far too weak, and a considerably stronger one would stick to it firmly",
        ],
        "correct_index": 2,
        "why": "Stainless steels are mostly iron. The common kitchen grades have a crystal structure in which the domains do not form, so they are not attracted.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h17",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two bar magnets are laid in a straight line, touching, with the north pole of one against the south pole of the other. Predict what a paperclip does at the join.",
        "options": [
            "It is held very firmly there, because two poles are acting on it at once",
            "It is held there only if it is offered up to the join from directly above rather than from the side",
            "It is thrown clear, because the two opposing poles push outwards at the join",
            "It is barely held at all, because the touching north and south poles cancel out",
        ],
        "correct_index": 3,
        "why": "Joined north to south, the pair behaves as one longer magnet with poles only at the outer ends. There is almost no free pole at the join.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h18",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "The force between two magnets and the force between two charged spheres are both non-contact forces. State one important difference between magnetic poles and electric charges.",
        "options": [
            "Charges can be separated one from the other, but poles are only ever found in pairs",
            "Charges attract only, while poles can either attract each other or repel each other",
            "Charges act through a vacuum, while magnetic poles need air in between them",
            "Charges act only over very short distances, while magnetic poles act over any distance at all",
        ],
        "correct_index": 0,
        "why": "A single positive or negative charge is perfectly ordinary, but a north pole has never been obtained without a south pole accompanying it.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h19",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student tests whether a coin is magnetic by pressing it against a fridge door and seeing whether it stays. Explain why the test proves nothing.",
        "options": [
            "The fridge door is painted, and a layer of paint would stop even a magnetic coin sticking to it",
            "Two magnetic materials attract one another only when one of them is a magnet",
            "The coin is not a magnet, so it will not stick whether or not it is magnetic",
            "The door is vertical, so gravity would pull the coin off in any case",
        ],
        "correct_index": 2,
        "why": "Two pieces of unmagnetised magnetic material do not attract each other. The coin has to be offered to an actual magnet for the test to mean anything.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h20",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A magnet is advertised with a pull force of 12 N. Explain why a buyer will rarely measure that value in practice.",
        "options": [
            "The quoted value is measured flat against thick steel, and any gap or thin steel gives far less",
            "The quoted value is really the weight of the magnet itself rather than the force that it can exert",
            "The quoted value applies only while the magnet is actually being moved along a surface rather than held still",
            "The quoted value has been doubled by the seller so that the magnet appears to be much better value",
        ],
        "correct_index": 0,
        "why": "Pull force is quoted for ideal conditions: direct contact, a flat clean surface, and steel thick enough to carry all the field. Paint, a rough surface or thin steel all reduce it.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h21",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A steel bar is heated until it is red hot, losing all its magnetism, and is then left standing upright to cool. It is found to be very slightly magnetic afterwards. Explain why.",
        "options": [
            "Some of the original domain alignment survived the heating deep inside the bar",
            "Hot steel picks up iron from the air, and that iron arrives already magnetised",
            "Cooling always leaves a bar magnetic, whatever direction it is standing in",
            "As it cooled, the domains re-formed in the Earth's field, which is always present",
        ],
        "correct_index": 3,
        "why": "Cooling back below the Curie temperature lets domains form again. Any field present while that happens, even the Earth's weak one, gives them a slight preferred direction.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h22",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two identical bar magnets are joined north to south to make one bar of double the length. Predict whether one end now holds twice as many paperclips.",
        "options": [
            "Yes, because both of the magnets contribute their own pull to that very same end of the bar",
            "Yes, because doubling the overall length of a magnet always doubles its strength too",
            "No, because the pair acts as one longer magnet whose end pole is little changed",
            "No, because joining two magnets halves the strength of each of them",
        ],
        "correct_index": 2,
        "why": "Joining them in line simply makes a longer magnet. The pole at each outer end is much as it was, so the number of clips held is similar, not doubled.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h23",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A computer hard disk stores data as tiny regions of a coating, each magnetised one way or the other. Explain why that coating must be magnetically hard.",
        "options": [
            "A physically hard coating resists being scratched by the read head as it sweeps across the spinning disk",
            "A soft coating would lose its magnetisation as soon as the writing field went, losing the data",
            "A hard coating spins more smoothly, which is what lets the disk turn so fast",
            "A soft coating would conduct electricity and short out the read head above it",
        ],
        "correct_index": 1,
        "why": "The data has to survive with no field applied. Only a magnetically hard material keeps its domains aligned after the writing head has moved on.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h24",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "An inventor claims that because like poles repel for ever without wearing out, magnets can be arranged to drive a machine that never needs an energy supply. Evaluate the claim.",
        "options": [
            "Correct, provided the magnets are made from a magnetically hard material that does not weaken",
            "Correct, because the repulsive force between them does work continuously and costs nothing at all to run",
            "Incorrect, because magnetic forces are far too weak to drive any real machine",
            "Incorrect, because work has to be done to push the poles together before they can push apart",
        ],
        "correct_index": 3,
        "why": "Every push apart has to be paid for by an equal push together. Round a complete cycle no energy is gained, so the machine cannot run without a supply.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h25",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two magnets of the same size, one of magnetised steel and one of neodymium alloy, hold 6 and 40 paperclips. State what this shows, and give one advantage the steel magnet still has.",
        "options": [
            "The steel is the better magnet of the two, and it is also much cheaper to buy than the alloy",
            "The neodymium holds far stronger magnetisation, but steel is cheaper and less brittle",
            "The steel has been magnetised badly, and remagnetising it properly would match the alloy",
            "The neodymium magnet is much the heavier of the two, which is the only reason it holds more clips",
        ],
        "correct_index": 1,
        "why": "Clip count compares the strength of the magnetisation. Neodymium wins easily, but it is expensive and shatters readily, while steel is cheap and tough.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h26",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A steel paperclip is left resting on a strong magnet for a week and then taken off. It is found to pick up a second clip on its own. Explain this observation.",
        "options": [
            "A trace of the magnet's material has rubbed off onto the surface of the clip",
            "The clip has absorbed some of the magnet's own field and will release all of it within minutes",
            "Steel is magnetically hard enough to keep some domains aligned after the field goes",
            "Any metal left touching a magnet becomes a permanent magnet after a few days",
        ],
        "correct_index": 2,
        "why": "Steel keeps part of its induced alignment once the field is removed, so the clip is left weakly but permanently magnetised.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h27",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "The force needed to pull a magnet off a steel plate is measured with 0, 1 and 2 sheets of card in between, giving 16 N, 7 N and 3 N. Describe the pattern shown by these results.",
        "options": [
            "The force falls steeply, roughly halving for every single extra sheet of card added",
            "The force falls by a fixed 6 N for every extra sheet of card that is added",
            "The force stays much the same, because card is not a magnetic material",
            "The force falls in direct proportion to the thickness of card in the gap",
        ],
        "correct_index": 0,
        "why": "16 N, 7 N and 3 N each roughly halve. The fall is far steeper than a fixed step, which shows the field weakening sharply over a very small distance.",
    },
    {
        "id": "ks4-poles-of-a-magnet-h28",
        "subtopic_slug": "poles-of-a-magnet",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A small magnet is sealed inside an aluminium can. A second magnet held outside the can can still feel a force from it. Explain why the aluminium does not block the effect.",
        "options": [
            "The can is thin, and any material blocks a field only if it is several centimetres thick",
            "The force is carried by the air inside the can rather than through the metal wall",
            "Aluminium is not a magnetic material, so it does not gather or divert the field",
            "The aluminium becomes magnetised itself and simply passes the force straight on",
        ],
        "correct_index": 2,
        "why": "A field is only redirected by ferromagnetic material such as iron. Aluminium has no effect on it, so the field passes through the wall of the can unchanged.",
    },
]
