"""Physics · Waves — the MRB-338 expansion: sound waves and the range of hearing.

Subtopic 6.6.1.4 (HT only, physics only) holds three things that pupils run
together: what kind of wave sound is and what it therefore needs to travel
through; where the audible range ends at each end, and what lies beyond it; and
what ultrasound is then used for. The easier band fixes the vocabulary and the
named numbers, the standard band applies them to a familiar instrument or
animal, and the harder band is mostly d = v × t / 2 worked forwards, backwards
and across two boundaries, plus the comparisons an examiner asks for. Echo
sounding as a way of exploring the Earth belongs to
`waves-detection-exploration`, not here.
"""

TOPIC = "waves"
SUBJECT = "physics"

QUESTIONS = [
    # ── easier ──────────────────────────────────────────────────────────
    {
        "id": "ks4-sound-waves-hearing-e05",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State which type of wave a sound wave is.",
        "options": [
            "A transverse wave, in which the particles move at right angles to the direction of travel",
            "A longitudinal wave, in which the particles always vibrate along the direction of travel",
            "An electromagnetic wave, which needs no particles in order to travel from place to place",
            "A stationary wave, in which the particles at the centre never move from their positions",
        ],
        "correct_index": 1,
        "why": "Sound travels as a longitudinal wave: the particles of the medium vibrate backwards and forwards along the direction the wave moves.",
    },
    {
        "id": "ks4-sound-waves-hearing-e06",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Name the region of a sound wave in which the particles of air are pushed closest together.",
        "options": [
            "A rarefaction",
            "A compression",
            "A crest",
            "A trough",
        ],
        "correct_index": 1,
        "why": "A longitudinal sound wave is a series of compressions, where the particles are pushed together, and rarefactions, where they are spread apart.",
    },
    {
        "id": "ks4-sound-waves-hearing-e07",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State which property of a sound wave determines its pitch.",
        "options": [
            "Its wavelength",
            "Its speed",
            "Its amplitude",
            "Its frequency",
        ],
        "correct_index": 3,
        "why": "A higher frequency is heard as a higher pitch; the amplitude sets the loudness instead.",
    },
    {
        "id": "ks4-sound-waves-hearing-e08",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State the lowest frequency that counts as ultrasound.",
        "options": [
            "20 000 Hz",
            "20 Hz",
            "2000 Hz",
            "200 000 Hz",
        ],
        "correct_index": 0,
        "why": "Ultrasound is sound above the upper limit of human hearing, which is about 20 000 Hz.",
    },
    {
        "id": "ks4-sound-waves-hearing-e09",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State the approximate speed of sound in water.",
        "options": [
            "340 m/s",
            "3.0 × 10⁸ m/s",
            "1500 m/s",
            "150 m/s",
        ],
        "correct_index": 2,
        "why": "Sound travels at roughly 1500 m/s in water, far faster than the 340 m/s it manages in air.",
    },
    {
        "id": "ks4-sound-waves-hearing-e10",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Put solids, liquids and gases in order of the speed at which sound travels through them, fastest first.",
        "options": [
            "Gases, then liquids, then solids, because sound spreads most freely where the particles are furthest apart",
            "Liquids, then solids, then gases, because a liquid lets the particles both touch and move past each other",
            "Solids, then liquids, then gases, because the vibration passes on fastest where the particles are closest",
            "The speed is the same in all three, because the frequency of the source is what fixes how fast sound moves",
        ],
        "correct_index": 2,
        "why": "The closer the particles, the sooner each one passes the vibration to the next, so sound is fastest in solids and slowest in gases.",
    },
    {
        "id": "ks4-sound-waves-hearing-e11",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State what a bat uses ultrasound for.",
        "options": [
            "To warm the air ahead of it so that it can fly through cold night air more easily",
            "To stun the insects it is hunting so that they can be caught more easily in flight",
            "To communicate with bats roosting many kilometres away across open countryside",
            "To navigate and find insects, by emitting pulses and detecting the reflections",
        ],
        "correct_index": 3,
        "why": "A bat echolocates: it emits ultrasound pulses and listens for the reflections to build a picture of what is around it.",
    },
    {
        "id": "ks4-sound-waves-hearing-e12",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Name the unit in which the loudness of a sound is measured.",
        "options": [
            "The decibel",
            "The hertz",
            "The newton",
            "The watt",
        ],
        "correct_index": 0,
        "why": "Loudness is measured in decibels (dB); the hertz measures frequency instead.",
    },
    {
        "id": "ks4-sound-waves-hearing-e13",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State two natural sources of infrasound.",
        "options": [
            "Lightning and hailstones",
            "Birdsong and rustling leaves",
            "Crickets and bat calls",
            "Earthquakes and volcanoes",
        ],
        "correct_index": 3,
        "why": "Earthquakes, volcanoes and ocean waves all produce sound below 20 Hz, which is infrasound.",
    },
    {
        "id": "ks4-sound-waves-hearing-e14",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Name the medical scan that uses ultrasound to examine how well a heart is working.",
        "options": [
            "A CT scan",
            "An MRI scan",
            "An electrocardiogram",
            "An echocardiogram",
        ],
        "correct_index": 3,
        "why": "An echocardiogram is an ultrasound scan of the heart, used to check the valves, the chamber sizes and the flow of blood.",
    },
    {
        "id": "ks4-sound-waves-hearing-e15",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State what happens to a sound wave when it reaches a hard flat wall.",
        "options": [
            "It is reflected, and may be heard as an echo",
            "It is refracted, and carries on beyond the wall",
            "It is absorbed entirely, and nothing returns",
            "It is split into its separate frequencies",
        ],
        "correct_index": 0,
        "why": "Hard surfaces reflect sound; the reflected sound is what is heard as an echo.",
    },
    {
        "id": "ks4-sound-waves-hearing-e16",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State what SONAR is used to measure at sea.",
        "options": [
            "The saltiness of the water, from the way the pulse is weakened as it travels",
            "The temperature of the water, from the pitch of the pulse when it returns",
            "The depth of the water, from the time an ultrasound pulse takes to return",
            "The speed of the ship, from the change in pitch of the pulse it sends out",
        ],
        "correct_index": 2,
        "why": "SONAR sends an ultrasound pulse down and times the echo from the seabed, which gives the depth.",
    },
    {
        "id": "ks4-sound-waves-hearing-e17",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State what an ultrasound flaw detector is used for in industry.",
        "options": [
            "Measuring the temperature inside a running furnace",
            "Finding cracks inside metal parts without cutting them open",
            "Counting the parts that pass along a conveyor belt",
            "Working out the chemical composition of an alloy",
        ],
        "correct_index": 1,
        "why": "Ultrasound reflects from the boundary at a crack, so a flaw inside a casting is found without damaging it.",
    },
    {
        "id": "ks4-sound-waves-hearing-e18",
        "subtopic_slug": "sound-waves-hearing",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State the frequency range over which human hearing is most sensitive.",
        "options": [
            "About 20 Hz to 60 Hz",
            "About 2 kHz to 5 kHz",
            "About 15 kHz to 20 kHz",
            "About 30 kHz to 40 kHz",
        ],
        "correct_index": 1,
        "why": "The ear is most sensitive around 2–5 kHz, which is the range that carries most of the sound of speech.",
    },

    # ── standard ────────────────────────────────────────────────────────
    {
        "id": "ks4-sound-waves-hearing-s05",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "An astronaut outside a spacecraft cannot hear a colleague shouting a metre away. Explain why.",
        "options": [
            "Space is far too cold for the particles to vibrate quickly enough for a sound wave to be carried",
            "The suit is sealed, and a sealed suit reflects every sound wave arriving at it straight back out into space again",
            "Sound is a mechanical wave and needs particles to vibrate, and space is very nearly a vacuum",
            "Sound travels so slowly in space that the shout would take several hours to cover a metre",
        ],
        "correct_index": 2,
        "why": "A longitudinal wave is passed on by particles bumping into one another, so with almost no particles there is nothing to carry the sound.",
    },
    {
        "id": "ks4-sound-waves-hearing-s06",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A note is played into the water of a swimming pool. A swimmer under the water hears it at the same pitch as a listener in the air. Explain why.",
        "options": [
            "The frequency is set by the source and never changes, and it is the frequency that is heard as pitch",
            "The wavelength is set by the source and does not change, and it is the wavelength that is heard as pitch",
            "The speed of the note is the same in water and in air, so nothing about the wave changes at all",
            "The water slows the note down and shortens its wavelength, and these two changes cancel each other out",
        ],
        "correct_index": 0,
        "why": "Crossing into water changes the speed and the wavelength together, but the number of vibrations per second is fixed by the source, so the pitch is unaltered.",
    },
    {
        "id": "ks4-sound-waves-hearing-s07",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A loudspeaker plays a note across a room. Describe what the air particles between the speaker and the listener actually do.",
        "options": [
            "They are blown steadily across the room from the loudspeaker to the listener's ear",
            "They stay exactly where they are, and only the energy of the note crosses the room without them",
            "They vibrate backwards and forwards about the same average position while the wave travels across",
            "They circle around a fixed point, moving up on a compression and down again on a rarefaction",
        ],
        "correct_index": 2,
        "why": "A wave transfers energy without transferring matter: each particle oscillates about its own position and passes the disturbance on.",
    },
    {
        "id": "ks4-sound-waves-hearing-s08",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "An ultrasound transducer produces sound of frequency 40 kHz. The speed of sound in air is 340 m/s. Calculate its wavelength in air.",
        "options": [
            "0.0085 m",
            "0.085 m",
            "118 m",
            "8.5 m",
        ],
        "correct_index": 0,
        "why": "Rearranging v = f × wavelength gives 340 ÷ 40 000 = 0.0085 m.",
    },
    {
        "id": "ks4-sound-waves-hearing-s09",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A medical scanner uses ultrasound of frequency 2.0 MHz. The speed of sound in soft tissue is 1500 m/s. Calculate its wavelength in the tissue.",
        "options": [
            "1.3 × 10³ m",
            "7.5 × 10⁻³ m",
            "3.0 × 10⁹ m",
            "7.5 × 10⁻⁴ m",
        ],
        "correct_index": 3,
        "why": "2.0 MHz is 2.0 × 10⁶ Hz, so the wavelength is 1500 ÷ 2.0 × 10⁶ = 7.5 × 10⁻⁴ m.",
    },
    {
        "id": "ks4-sound-waves-hearing-s10",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Describe how a scanner builds an image of a baby from a single ultrasound pulse sent into the body.",
        "options": [
            "The pulse is absorbed by each organ in turn, and the amount absorbed by each one is used to shade the picture",
            "Part of the pulse is reflected at each boundary between tissues, and the return times fix how deep each boundary lies",
            "The pulse makes each tissue give out an ultrasound signal of its own, whose strength is turned into brightness on the screen",
            "The pulse passes right through the body to a detector on the far side, which records how much of it survived the journey",
        ],
        "correct_index": 1,
        "why": "An ultrasound image is built from partial reflections: each boundary between tissues of different density sends part of the pulse back, and its timing gives the depth.",
    },
    {
        "id": "ks4-sound-waves-hearing-s11",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "An ultrasound pulse is sent into a thick steel casting. Describe what the operator sees if there is a crack inside it.",
        "options": [
            "A single echo that arrives later than expected, because the crack lengthens the path the pulse must take",
            "No echo at all, because the crack scatters the whole pulse sideways and none of it returns to the probe",
            "An extra echo arriving before the one from the far face, because the crack reflects part of the pulse early",
            "A much louder echo from the far face, because the crack focuses the pulse onto the back of the casting",
        ],
        "correct_index": 2,
        "why": "The boundary at the crack reflects part of the pulse, so an echo arrives sooner than the one from the back of the casting and gives the flaw's depth.",
    },
    {
        "id": "ks4-sound-waves-hearing-s12",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why a bat hunting small insects uses ultrasound rather than sound within the human hearing range.",
        "options": [
            "Ultrasound travels much faster through air, so the echo from an insect comes back far sooner",
            "Ultrasound is not absorbed by air at all, so the pulses reach insects much further away from the bat",
            "Ultrasound is much louder than audible sound, so even a small insect returns a very strong echo",
            "Ultrasound has a much shorter wavelength, so it reflects well from an object as small as an insect",
        ],
        "correct_index": 3,
        "why": "A wave reflects clearly only from objects comparable with or larger than its wavelength, and ultrasound's short wavelength suits a small target.",
    },
    {
        "id": "ks4-sound-waves-hearing-s13",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A shout in a small room is not heard as a separate echo, but the same shout across a valley is. Explain why.",
        "options": [
            "In a small room the reflected sound returns too soon after the original for the ear to separate the two",
            "In a small room the walls absorb every sound completely, so no reflected sound ever comes back to the ear",
            "In a small room the sound has too little energy left to reflect, while across a valley it is still strong",
            "In a small room the reflected sound comes back at a much lower pitch, so the ear does not recognise it as the same shout",
        ],
        "correct_index": 0,
        "why": "The ear only distinguishes a reflection as a separate sound if it arrives more than about 0.1 s after the original, which needs a reflecting surface well over 15 m away.",
    },
    {
        "id": "ks4-sound-waves-hearing-s14",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why an echo sounder must be told the speed of sound in the water before it can display a depth.",
        "options": [
            "It measures only the time for the pulse to return, and a time cannot be turned into a distance without a speed",
            "It measures only the frequency of the returning pulse, and that has to be converted into a speed before use",
            "It measures only the loudness of the returning pulse, which falls off at a rate that depends on the speed",
            "It measures the distance directly, and the speed is needed only to check the answer it has already found",
        ],
        "correct_index": 0,
        "why": "The instrument times the echo; the depth comes from d = v × t / 2, so the speed in that water must be supplied.",
    },
    {
        "id": "ks4-sound-waves-hearing-s15",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain how an ultrasonic bath cleans a delicate piece of jewellery without anything touching it.",
        "options": [
            "The ultrasound raises the temperature of the water until the dirt dissolves away from the metal surface",
            "The ultrasound reacts chemically with the grease on the jewellery and breaks it down into soluble pieces",
            "The ultrasound magnetises the jewellery, and the dirt is then repelled from the surface of the metal",
            "The ultrasound sets up rapid vibrations in the liquid, and these dislodge dirt from the surface of the metal",
        ],
        "correct_index": 3,
        "why": "High-frequency vibrations in the liquid shake dirt loose from the surface, which is why delicate items can be cleaned without scrubbing.",
    },
    {
        "id": "ks4-sound-waves-hearing-s16",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why elephants use very low-frequency calls to keep in contact across many kilometres of open country.",
        "options": [
            "Low-frequency sound travels far faster through air, so a call reaches a distant herd in a much shorter time",
            "Low-frequency sound can only be heard by elephants, so no energy is wasted on other animals hearing the call",
            "Low-frequency sound is carried underground through the soil, which absorbs far less of it than the air does",
            "Low-frequency sound spreads around obstacles such as trees and is absorbed less by the air as it travels",
        ],
        "correct_index": 3,
        "why": "Long-wavelength sound diffracts around obstacles and loses less energy to the air over distance, so infrasound carries much further than a high note.",
    },
    {
        "id": "ks4-sound-waves-hearing-s17",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why the range of human hearing is always quoted as approximate rather than as exact figures.",
        "options": [
            "The limits are fixed for everyone, but the instruments used to measure them are not accurate enough to give exact values",
            "The limits vary from person to person and with age, so no single pair of values describes everybody",
            "The limits change with the loudness of the sound, so a quiet note has a completely different range from a loud one",
            "The limits depend on the air temperature, which changes the speed of sound and so changes what can be heard",
        ],
        "correct_index": 1,
        "why": "20 Hz to 20 kHz is a typical range for a healthy young person; individuals differ, and the upper limit falls with age.",
    },
    {
        "id": "ks4-sound-waves-hearing-s18",
        "subtopic_slug": "sound-waves-hearing",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Compare infrasound and ultrasound.",
        "options": [
            "Both are inaudible to people: infrasound lies below about 20 Hz and ultrasound above about 20 kHz",
            "Both are inaudible to people: infrasound is quieter than the ear can detect and ultrasound is louder than it can bear",
            "Infrasound is inaudible because it lies below 20 Hz, while ultrasound is simply audible sound that is unusually loud",
            "Infrasound travels only through solids and ultrasound only through gases, which is why neither is heard in air",
        ],
        "correct_index": 0,
        "why": "The two sit at opposite ends of the audible range: infrasound is too low in frequency to hear, ultrasound too high.",
    },

    # ── harder ──────────────────────────────────────────────────────────
    {
        "id": "ks4-sound-waves-hearing-h05",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "An ultrasound pulse is sent into a steel bar and an echo returns 2.0 × 10⁻⁴ s later. The speed of sound in steel is 5900 m/s. Calculate the depth of the reflecting surface.",
        "options": [
            "1.18 m",
            "0.59 m",
            "0.30 m",
            "2.95 × 10⁷ m",
        ],
        "correct_index": 1,
        "why": "d = v × t ÷ 2 = 5900 × 2.0 × 10⁻⁴ ÷ 2 = 0.59 m.",
    },
    {
        "id": "ks4-sound-waves-hearing-h06",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A ship is above water 1800 m deep. The speed of sound in the water is 1500 m/s. Calculate the time between sending a sonar pulse and receiving its echo.",
        "options": [
            "0.83 s",
            "1.2 s",
            "2.4 s",
            "4.8 s",
        ],
        "correct_index": 2,
        "why": "The pulse travels 3600 m in all, so t = 3600 ÷ 1500 = 2.4 s.",
    },
    {
        "id": "ks4-sound-waves-hearing-h07",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "An ultrasound probe is placed on the skin and a boundary lies 4.5 cm below it. The speed of sound in the tissue is 1500 m/s. Calculate the time before the echo returns.",
        "options": [
            "3.0 × 10⁻⁵ s",
            "6.0 × 10⁻⁵ s",
            "3.3 × 10⁴ s",
            "6.0 × 10⁻³ s",
        ],
        "correct_index": 1,
        "why": "The pulse covers 0.090 m in all, so t = 0.090 ÷ 1500 = 6.0 × 10⁻⁵ s.",
    },
    {
        "id": "ks4-sound-waves-hearing-h08",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "An echo sounder above a seabed known to be 60 m down records an echo 0.080 s after the pulse is sent. Calculate the speed of sound in this water.",
        "options": [
            "750 m/s",
            "3000 m/s",
            "1500 m/s",
            "4.8 m/s",
        ],
        "correct_index": 2,
        "why": "The pulse covers 120 m in 0.080 s, so v = 120 ÷ 0.080 = 1500 m/s.",
    },
    {
        "id": "ks4-sound-waves-hearing-h09",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A scanner detects one echo 4.0 × 10⁻⁵ s after the pulse is sent and a second 1.0 × 10⁻⁴ s after it. The speed of sound in the tissue is 1500 m/s. Calculate the distance between the two boundaries.",
        "options": [
            "0.045 m",
            "0.090 m",
            "0.21 m",
            "0.015 m",
        ],
        "correct_index": 0,
        "why": "The extra time is 6.0 × 10⁻⁵ s, which covers 0.090 m there and back, so the boundaries are 0.045 m apart.",
    },
    {
        "id": "ks4-sound-waves-hearing-h10",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A hospital must image a structure deep in the abdomen. A 10 MHz probe gives finer detail than a 2 MHz probe, but higher frequencies are absorbed more strongly by tissue. Determine which probe to use.",
        "options": [
            "The 10 MHz probe, because the finer detail that it gives is worth far more than any loss of signal on the way down to the organ",
            "The 2 MHz probe, because the 10 MHz ultrasound would be absorbed before it reached the structure, so no echo would return",
            "The 10 MHz probe, because a higher frequency travels faster through tissue and so reaches greater depths",
            "Either probe, because the depth a pulse reaches depends only on how loud it is and not on its frequency",
        ],
        "correct_index": 1,
        "why": "Resolution improves with frequency but penetration falls, so a deep structure needs the lower frequency even though the image is coarser.",
    },
    {
        "id": "ks4-sound-waves-hearing-h11",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A bat emits a pulse and hears its echo from an insect 0.012 s later. The speed of sound in air is 340 m/s. Calculate the distance to the insect.",
        "options": [
            "4.1 m",
            "2.0 m",
            "1.0 m",
            "28 m",
        ],
        "correct_index": 1,
        "why": "d = 340 × 0.012 ÷ 2 = 2.04 m, which is 2.0 m to two significant figures.",
    },
    {
        "id": "ks4-sound-waves-hearing-h12",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A sonar set calibrated for seawater, in which sound travels at 1500 m/s, is used in a fresh-water lake where sound travels at 1480 m/s. Predict the effect on the depth it displays.",
        "options": [
            "The displayed depth is slightly too small, because the pulse spends longer in the slower water than the set allows for",
            "The displayed depth is slightly too large, because the set assumes a higher speed than the pulse actually travels at",
            "The displayed depth is unaffected, because the set measures a time and the time does not depend on the speed",
            "The displayed depth is far too large, because sound is absorbed more strongly by fresh water than by seawater",
        ],
        "correct_index": 1,
        "why": "The set multiplies the measured time by a speed that is too high, so every depth it reports comes out a little over the true value.",
    },
    {
        "id": "ks4-sound-waves-hearing-h13",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why an ultrasound scanner sends out short separate pulses rather than a continuous note.",
        "options": [
            "A continuous note would heat the tissue it passed through, and the warming would blur the picture on the screen",
            "A continuous note would gradually lose its frequency, so the scanner would no longer recognise what came back",
            "A continuous note would overlap with its own echoes, so the return time of any particular part could not be measured",
            "A continuous note would be absorbed rather than reflected, so nothing at all would come back to the probe",
        ],
        "correct_index": 2,
        "why": "Depth is found from the time an echo takes to return, and that time can only be measured if the outgoing sound has stopped before the echo arrives.",
    },
    {
        "id": "ks4-sound-waves-hearing-h14",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "figure": "ks4-fig-echo-sounder-display",
        "text": "The diagram shows the display from a fishing boat's echo sounder as the boat moves along. Suggest what produces the fainter mark labelled X.",
        "options": [
            "A layer of colder water, which stops the pulse completely and prevents it reaching the seabed at all",
            "The surface of the sea, from which the pulse reflects downwards again on its way back to the boat",
            "A shoal of fish, which reflects part of the pulse back before the rest reaches the seabed",
            "The hull of the boat, which vibrates as the pulse leaves and sends a signal of its own to the detector",
        ],
        "correct_index": 2,
        "why": "X is a partial reflection from something between the boat and the seabed, and it covers only part of the boat's path. A shoal of fish reflects part of each pulse back sooner and more weakly than the seabed, while the rest of the pulse carries on to the seabed, which still shows underneath.",
    },
    {
        "id": "ks4-sound-waves-hearing-h15",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "An ultrasound scan of the lungs gives a very poor image. Suggest why.",
        "options": [
            "The lungs are full of air, and ultrasound is strongly reflected at the boundary between tissue and air",
            "The lungs move as the patient breathes, and a moving organ alters the frequency of every pulse returning from it",
            "The lungs are surrounded by the ribs, which absorb the whole pulse before it reaches the tissue behind",
            "The lungs are the least dense organ in the body, so no boundary within them reflects any of the pulse",
        ],
        "correct_index": 0,
        "why": "A large difference in density gives a strong reflection, so almost all the pulse bounces off the tissue–air boundary and nothing reaches the structures beyond.",
    },
    {
        "id": "ks4-sound-waves-hearing-h16",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A student says: 'Ultrasound is safer than X-rays, so every medical image should be taken with ultrasound instead.' Evaluate this statement.",
        "options": [
            "Agree entirely, because ultrasound produces a clearer image of every part of the body than X-rays can manage",
            "Disagree, because ultrasound is the more hazardous of the two and X-rays should therefore be preferred wherever possible",
            "Agree entirely, because the only reason X-rays are still used is that ultrasound equipment is far more expensive to buy",
            "Disagree in part: ultrasound is non-ionising, but it hardly penetrates bone or air, so X-rays remain better for some images",
        ],
        "correct_index": 3,
        "why": "The safety claim is right, but suitability matters too: ultrasound is reflected almost completely at bone and air, so a fractured skull still needs X-rays.",
    },
    {
        "id": "ks4-sound-waves-hearing-h17",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "An ultrasound pulse passes from soft tissue into bone, in which it travels faster. State what happens to its frequency and to its wavelength.",
        "options": [
            "The frequency rises and the wavelength stays the same, because more compressions now arrive each second",
            "The frequency stays the same and the wavelength increases, because the speed has risen and v = f × wavelength",
            "The frequency stays the same and the wavelength decreases, because a faster wave covers more ground each cycle",
            "Both fall together, because the pulse loses energy as it crosses the boundary into the denser material",
        ],
        "correct_index": 1,
        "why": "Frequency is fixed by the source, so if v rises then the wavelength must rise with it to satisfy v = f × wavelength.",
    },
    {
        "id": "ks4-sound-waves-hearing-h18",
        "subtopic_slug": "sound-waves-hearing",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A pupil claims that because sound travels faster in water than in air, a shout under water would reach a listener at a higher pitch. Evaluate this claim.",
        "options": [
            "Correct, because a faster wave delivers more compressions to the ear each second and so sounds higher",
            "Correct, because the speed and the pitch of a sound are two different names for the same property of a wave",
            "Incorrect, because the pitch depends on the frequency, which is set by the source and is unchanged by the water",
            "Incorrect, because sound travels more slowly in water than it does in air, so the note would sound lower",
        ],
        "correct_index": 2,
        "why": "The speed does rise, but the extra speed goes into a longer wavelength; the number of vibrations arriving each second is unchanged, so the pitch is the same.",
    },
]
