"""Physics · Waves — the MRB-338 expansion: infrared, surfaces and black bodies.

Subtopic 6.6.5 (physics only) turns on one pairing that pupils keep breaking:
a good absorber is also a good emitter, and a good reflector is a poor one at
both. So a matt black surface is not simply 'the hot one' — it is the one that
gains fastest in sunlight AND loses fastest in the dark, and several rows here
take it from the cooling side rather than the heating side. The second half is
the black body proper: a perfect absorber that is also the maximum emitter for
its temperature, with a spectrum that depends on temperature alone and a peak
that moves to shorter wavelengths as it heats. Stars carry that idea outwards.
The Earth's own radiation budget belongs to `radiation-balance-temperature`.
"""

TOPIC = "waves"
SUBJECT = "physics"

QUESTIONS = [
    # ── easier ──────────────────────────────────────────────────────────
    {
        "id": "ks4-infrared-black-bodies-e05",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what is meant by thermal radiation.",
        "options": [
            "The infrared an object emits because of its temperature",
            "The sound an object gives out as it is warmed up",
            "The heat carried away by the air moving past an object",
            "The energy passed along a solid from particle to particle",
        ],
        "correct_index": 0,
        "why": "Thermal radiation is the infrared every object above absolute zero emits, and it needs no material to travel through.",
    },
    {
        "id": "ks4-infrared-black-bodies-e06",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "A matt black block and a shiny silver block are held at the same temperature. State which sends out more energy each second.",
        "options": [
            "The shiny silver block",
            "The matt black block",
            "Neither; they send out the same",
            "Neither; a block at a steady temperature sends out nothing",
        ],
        "correct_index": 1,
        "why": "Emission and absorption go together: the surface that absorbs best also radiates best at any given temperature.",
    },
    {
        "id": "ks4-infrared-black-bodies-e07",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the part of the electromagnetic spectrum in which an object at room temperature emits most strongly.",
        "options": [
            "Ultraviolet, just beyond the violet end",
            "Visible light, the part the eye detects",
            "Infrared, just beyond the red end",
            "Radio waves, the longest wavelengths of all",
        ],
        "correct_index": 2,
        "why": "At everyday temperatures the peak of the emission lies well into the infrared, which is why nothing in a room glows visibly.",
    },
    {
        "id": "ks4-infrared-black-bodies-e08",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "An object absorbs radiation faster than it emits it. State what happens to its temperature.",
        "options": [
            "It falls",
            "It rises",
            "It stays the same",
            "It falls and then rises again",
        ],
        "correct_index": 1,
        "why": "More energy is arriving than leaving, so the store of energy in the object grows and its temperature climbs.",
    },
    {
        "id": "ks4-infrared-black-bodies-e09",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what a perfect black body does to the radiation that falls on it.",
        "options": [
            "It reflects all of it",
            "It absorbs all of it",
            "It transmits all of it",
            "It absorbs half and reflects half",
        ],
        "correct_index": 1,
        "why": "A perfect black body reflects nothing at all, which is why it is called black.",
    },
    {
        "id": "ks4-infrared-black-bodies-e10",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State how much radiation a perfect black body emits compared with any other object at the same temperature.",
        "options": [
            "Less than any of them",
            "Exactly the same as all of them",
            "More than any of them",
            "None at all, since it only absorbs",
        ],
        "correct_index": 2,
        "why": "A perfect absorber is also a perfect emitter, so nothing at that temperature can radiate more than a black body does.",
    },
    {
        "id": "ks4-infrared-black-bodies-e11",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what happens to the total amount of radiation an object emits each second as it gets hotter.",
        "options": [
            "It decreases",
            "It stays the same",
            "It increases",
            "It first rises and then falls away",
        ],
        "correct_index": 2,
        "why": "A hotter object radiates more energy every second, which is why a cooling object slows down as it approaches room temperature.",
    },
    {
        "id": "ks4-infrared-black-bodies-e12",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what happens to the wavelength at which an object emits most strongly as it gets hotter.",
        "options": [
            "It gets shorter",
            "It gets longer",
            "It does not change",
            "It doubles each time",
        ],
        "correct_index": 0,
        "why": "The peak of the emission moves towards shorter wavelengths as the temperature rises, which is why a hot object glows red and then white.",
    },
    {
        "id": "ks4-infrared-black-bodies-e13",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State the colour of the hottest stars.",
        "options": [
            "Red",
            "Orange",
            "Yellow",
            "Blue-white",
        ],
        "correct_index": 3,
        "why": "The hotter a star is, the shorter its peak wavelength, so the hottest stars peak at the blue end and look blue-white.",
    },
    {
        "id": "ks4-infrared-black-bodies-e14",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State which radiation a thermal imaging camera detects.",
        "options": [
            "Ultraviolet",
            "Infrared",
            "Microwaves",
            "Gamma rays",
        ],
        "correct_index": 1,
        "why": "Every object emits infrared, and a warmer one emits more, so an infrared detector builds a picture from temperature differences.",
    },
    {
        "id": "ks4-infrared-black-bodies-e15",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State the best surface finish for the panel of a solar water heater.",
        "options": [
            "Polished silver",
            "Glossy white",
            "Matt black",
            "Bare untreated metal",
        ],
        "correct_index": 2,
        "why": "The panel's job is to take in as much of the Sun's radiation as possible, and a matt black surface is the best absorber.",
    },
    {
        "id": "ks4-infrared-black-bodies-e16",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State whether a perfect black body exists in practice.",
        "options": [
            "Yes; any object painted matt black is a perfect black body",
            "Yes; every star in the sky is a perfect black body",
            "No; it is an idea that some objects only come close to",
            "No; and nothing made has ever come anywhere near it",
        ],
        "correct_index": 2,
        "why": "A perfect black body is a theoretical object; real surfaces always reflect a little, though a cavity with a small hole comes very close.",
    },
    {
        "id": "ks4-infrared-black-bodies-e17",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State one use of a thermal imaging camera.",
        "options": [
            "Measuring how fast a vehicle is travelling along a road",
            "Finding where a building is losing energy",
            "Checking the chemical purity of a metal sample",
            "Recording the sound made by a running machine",
        ],
        "correct_index": 1,
        "why": "Warm patches on a wall or roof emit more infrared than the rest, so they show up brightly on a thermal image.",
    },
    {
        "id": "ks4-infrared-black-bodies-e18",
        "subtopic_slug": "infrared-black-bodies",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State the temperature at which an object would stop emitting radiation altogether.",
        "options": [
            "0 °C",
            "Room temperature",
            "Absolute zero",
            "100 °C",
        ],
        "correct_index": 2,
        "why": "Every object above absolute zero emits radiation, so only at absolute zero would the emission stop.",
    },

    # ── standard ────────────────────────────────────────────────────────
    {
        "id": "ks4-infrared-black-bodies-s05",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Two cars stand side by side in bright sunshine, one white and one black. Explain why the black one becomes hotter inside.",
        "options": [
            "The black paint is a thicker layer, so it holds far more of the energy arriving from the Sun within the bodywork of the car",
            "The black paint conducts the arriving energy into the car faster than white paint is able to",
            "The black surface absorbs more of the radiation arriving from the Sun, while the white surface reflects much of it",
            "The black surface is cooler at the start, so it has further to warm before the two cars are level",
        ],
        "correct_index": 2,
        "why": "A dark surface reflects little of the radiation reaching it, so more of the Sun's energy is transferred into the car.",
    },
    {
        "id": "ks4-infrared-black-bodies-s06",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A survival blanket given to a runner at the end of a race is shiny silver on both sides. Explain how it keeps the runner warm.",
        "options": [
            "It is a poor emitter and reflects the runner's own infrared back, so less energy is radiated away",
            "It is a good absorber, so it takes in energy from the cold air all around and then passes that energy on to the runner",
            "It is a good conductor, so it spreads the runner's body heat evenly over the whole of the skin",
            "It is thick enough to trap a layer of warm air, which is what stops the runner cooling down",
        ],
        "correct_index": 0,
        "why": "The shiny surface radiates very little and reflects the infrared coming from the body, so the runner's energy is kept rather than lost.",
    },
    {
        "id": "ks4-infrared-black-bodies-s07",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A hot kettle left in a cool kitchen eventually stops cooling and stays at room temperature. Explain why it stops.",
        "options": [
            "It has run out of energy to emit, so no more radiation can leave its surface",
            "It is emitting and absorbing at the same rate once it reaches the temperature of its surroundings",
            "It has stopped emitting completely, because emission only happens above room temperature",
            "Its surface has cooled, and a cool surface is unable to emit any infrared radiation",
        ],
        "correct_index": 1,
        "why": "Cooling slows as the difference shrinks; at room temperature the kettle still radiates, but it absorbs just as much from its surroundings.",
    },
    {
        "id": "ks4-infrared-black-bodies-s08",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "The filament of a lamp glows white hot while the glass bulb around it stays dark. Explain why.",
        "options": [
            "The glass is a poor conductor, so no energy can reach it from the filament inside the bulb",
            "The glass is transparent, and a transparent material can never emit any radiation whatever",
            "The filament is at a far higher temperature, so its emission peaks in the visible while the cooler glass peaks in the infrared",
            "The filament is made of a special metal that gives out visible light, while all ordinary materials are able to emit only infrared",
        ],
        "correct_index": 2,
        "why": "Both emit, but where the peak sits depends on temperature: at a few thousand degrees the peak is in the visible, and at a hundred it is well into the infrared.",
    },
    {
        "id": "ks4-infrared-black-bodies-s09",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A fire warms a person standing across the room, even though air is a poor conductor. Explain how the energy reaches them.",
        "options": [
            "The air itself carries the energy right across the room as it is pushed outwards by the flames of the fire",
            "The energy travels as infrared radiation, which crosses the room without needing the air at all",
            "The energy is conducted along the floor and rises up into the person standing on it",
            "The energy is carried across by the sound of the crackling fire, which the body absorbs and turns into warmth",
        ],
        "correct_index": 1,
        "why": "Radiation needs no medium, so infrared from the fire crosses the room directly and is absorbed by whatever it lands on.",
    },
    {
        "id": "ks4-infrared-black-bodies-s10",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Compare a star at about 3000 K with one at about 6000 K.",
        "options": [
            "The 3000 K star looks blue and radiates more energy each second from each square metre of its surface",
            "The 6000 K star looks red and radiates less energy each second from each square metre of its surface",
            "The two look the same colour, and the hotter one simply radiates more energy from each square metre",
            "The 6000 K star looks yellower and radiates more energy each second from each square metre of its surface",
        ],
        "correct_index": 3,
        "why": "Raising the temperature does two things at once: the peak moves to shorter wavelengths, and the total radiated each second rises sharply.",
    },
    {
        "id": "ks4-infrared-black-bodies-s11",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A dying ember in a fire glows dull red while the Sun looks yellow-white. Explain the difference.",
        "options": [
            "The ember is far cooler, so its peak lies at the long-wavelength end of the visible and it looks red",
            "The ember is made of carbon, which can only ever emit light at the red end of the spectrum",
            "The ember is smaller, and a small object can only emit a narrow band of the wavelengths available",
            "The ember is further from the eye, and light reddens as it travels across a room towards an observer",
        ],
        "correct_index": 0,
        "why": "Colour here is a thermometer: at ember temperatures only the longest visible wavelengths are emitted strongly, while the far hotter Sun emits right across the visible.",
    },
    {
        "id": "ks4-infrared-black-bodies-s12",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a perfect absorber of radiation is described as a black body.",
        "options": [
            "Because it is always painted matt black, and only matt black paint is able to absorb radiation completely",
            "Because it reflects none of the light falling on it, so there is nothing for the eye to see",
            "Because it emits only black light, which the human eye has no way of detecting",
            "Because it is at a very low temperature, and cold objects always appear black to the eye",
        ],
        "correct_index": 1,
        "why": "Something is seen by the light it reflects; an object that reflects none looks black, whatever it may be emitting of its own.",
    },
    {
        "id": "ks4-infrared-black-bodies-s13",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "The cooling fins on a motorcycle engine are often finished in matt black. Explain why.",
        "options": [
            "Matt black is a better emitter of infrared, so the fins radiate the engine's energy away faster",
            "Matt black is a better absorber of infrared, so the fins take in more energy from the passing air",
            "Matt black is a better conductor of energy, so it carries the engine's energy out to the tips of the fins",
            "Matt black is a better reflector of sunlight, so the engine is not heated further while it is running",
        ],
        "correct_index": 0,
        "why": "The fins exist to lose energy, and the surface that emits best at a given temperature is the matt dark one.",
    },
    {
        "id": "ks4-infrared-black-bodies-s14",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "On a thermal image of a person outdoors in winter, the face appears much brighter than the coat. Explain why.",
        "options": [
            "The coat is a better emitter than skin, so it sends out more infrared and appears darker on the image",
            "The face is nearer to the camera than the coat, and nearer objects always appear brighter on a thermal image",
            "The face reflects the infrared coming from the surroundings, while the fabric of the coat absorbs all of it",
            "The outer surface of the coat is much cooler than the skin, so it emits far less infrared than the face does",
        ],
        "correct_index": 3,
        "why": "Insulation keeps the coat's outside close to the air temperature, while bare skin stays near body temperature and so radiates far more.",
    },
    {
        "id": "ks4-infrared-black-bodies-s15",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A book has sat on a table in a warm room for hours. Explain why it is still emitting radiation even though its temperature is not changing.",
        "options": [
            "Every object above absolute zero emits, and the book is also absorbing at exactly the same rate",
            "The book stopped emitting some time ago, which is exactly why its temperature is no longer changing",
            "The book emits only when it is warmer than the room, and it is still slightly warmer than the air",
            "The book emits only the radiation it absorbed earlier, and it will stop once that supply runs out",
        ],
        "correct_index": 0,
        "why": "A steady temperature means the two rates are equal, not that either has stopped; emission and absorption go on all the time.",
    },
    {
        "id": "ks4-infrared-black-bodies-s16",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "An infrared telescope is cooled to a very low temperature before it is used. Suggest why.",
        "options": [
            "A cold detector is more sensitive to visible light, which is what an infrared telescope really records",
            "A warm telescope would emit infrared of its own, which would swamp the faint signal from distant objects",
            "A warm telescope would expand, and the change in its size would blur the image it forms",
            "A cold telescope absorbs infrared more strongly, so more of the arriving radiation reaches its detector",
        ],
        "correct_index": 1,
        "why": "The instrument is itself an object above absolute zero; unless it is made very cold, its own emission is far brighter than the sources it is looking at.",
    },
    {
        "id": "ks4-infrared-black-bodies-s17",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why the same matt black surface is both the best absorber and the best emitter of radiation.",
        "options": [
            "Because a surface that takes energy in easily must give it out slowly, and the two effects balance out",
            "Because the colour black attracts radiation towards it, whichever direction that radiation is travelling",
            "Because how readily a surface exchanges radiation with its surroundings is always one property, working both ways",
            "Because black surfaces are always rougher, and a rough surface has more area for radiation to enter by",
        ],
        "correct_index": 2,
        "why": "Absorbing and emitting are the same interaction run in opposite directions, so a surface that is good at one is necessarily good at the other.",
    },
    {
        "id": "ks4-infrared-black-bodies-s18",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A piece of iron in a furnace is invisible in the dark at first, then glows. Explain what has changed.",
        "options": [
            "It has begun to burn, and the light seen is the flame of the iron reacting with the air",
            "It has started to emit for the first time, having emitted nothing while it was still cold",
            "It has become hot enough for its peak emission to move out of the infrared and into the visible",
            "It has begun to reflect the light of the furnace, which it was too cold to reflect before",
        ],
        "correct_index": 2,
        "why": "Cold iron emits, but entirely in the infrared, which the eye cannot see; heating it moves enough of the emission into the visible for it to glow.",
    },

    # ── harder ──────────────────────────────────────────────────────────
    {
        "id": "ks4-infrared-black-bodies-h05",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "An object is absorbing radiation faster than it emits it. Predict what happens over the next few hours and explain what brings the change to an end.",
        "options": [
            "It warms without any limit whatever, because nothing about an object can ever stop it taking in more energy than it gives out to its surroundings",
            "It warms, and as it warms it emits faster, until the emission rate matches the absorption rate and the temperature steadies",
            "It warms briefly and then cools again, because a warmer object always absorbs less than a cooler one does",
            "It stays at the same temperature throughout, because the extra energy absorbed is stored rather than felt",
        ],
        "correct_index": 1,
        "why": "Emission rises steeply with temperature while the absorption from the surroundings does not, so the two rates converge and the object settles at a new steady temperature.",
    },
    {
        "id": "ks4-infrared-black-bodies-h06",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Two identical black bodies are held at 300 K and at 600 K. Compare the radiation each emits.",
        "options": [
            "The hotter one emits more energy each second and peaks at a shorter wavelength than the cooler one",
            "The hotter one emits more energy every second but it peaks at a longer wavelength than the cooler one does at the same instant",
            "The hotter one emits exactly twice as much energy each second, at exactly half the wavelength",
            "Both emit the same total each second, and only the wavelength of the peak is different",
        ],
        "correct_index": 0,
        "why": "Raising the temperature increases the total emitted every second and moves the peak of the spectrum towards shorter wavelengths at the same time.",
    },
    {
        "id": "ks4-infrared-black-bodies-h07",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A student claims a shiny silver object can never get hot in sunlight, because it reflects everything. Evaluate this claim.",
        "options": [
            "Correct, because a shiny surface reflects every wavelength that reaches it and can absorb nothing whatever",
            "Correct, because the energy a shiny surface does absorb is immediately reflected back out again unchanged",
            "Incorrect, because a shiny surface absorbs everything and reflects nothing, so it heats faster than a matt one",
            "Incorrect, because it reflects most but not all, and being a poor emitter it also finds it harder to lose what it gains",
        ],
        "correct_index": 3,
        "why": "No real surface reflects everything; and the same property that makes it a poor absorber makes it a poor emitter, so it does not shed the energy it takes in quickly either.",
    },
    {
        "id": "ks4-infrared-black-bodies-h08",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Parts of a spacecraft are wrapped in shiny gold-coloured foil. Suggest why.",
        "options": [
            "The foil is a very good conductor, so it carries energy quickly away from all the instruments it surrounds",
            "The foil reflects the Sun's radiation and is a poor emitter, so it limits both heating and cooling",
            "The foil absorbs the Sun's radiation very strongly, so the instruments inside it are kept warm out in space",
            "The foil is thick enough to trap a layer of air, which insulates the instruments inside it",
        ],
        "correct_index": 1,
        "why": "In space there is no air to conduct or convect, so radiation is the only route in or out, and a shiny surface controls it in both directions.",
    },
    {
        "id": "ks4-infrared-black-bodies-h09",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A car windscreen frosts over on a clear night but not on a cloudy one, even when the air temperature is the same. Suggest why.",
        "options": [
            "Cloud presses down on the air, and the higher pressure stops water vapour freezing onto the glass",
            "Under clear skies the glass radiates to the cold sky and receives little back, so it cools below the air temperature",
            "Under clear skies the glass absorbs starlight, which cools the surface below the temperature of the air",
            "Cloud reflects the radiation given off by the glass away into space, which is the reason the glass then stays warmer overnight",
        ],
        "correct_index": 1,
        "why": "The glass emits infrared upwards all night; a clear sky sends almost nothing back, while cloud radiates downwards and keeps the surface near air temperature.",
    },
    {
        "id": "ks4-infrared-black-bodies-h10",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A matt black block and a polished metal block are held at the same high temperature. Compare what an observer sees and what a thermometer reads.",
        "options": [
            "Both radiate identically, so they look the same and read the same on a thermometer held against each",
            "The polished block looks brighter, because polished surfaces emit far more strongly at any temperature",
            "The thermometer reads the same for both, but the matt black block glows more brightly because it emits more",
            "The thermometer reads higher for the matt black block, because a good emitter is always at a higher temperature",
        ],
        "correct_index": 2,
        "why": "Temperature is a property of the block, not of its finish; how much radiation leaves each square metre at that temperature is what the surface controls.",
    },
    {
        "id": "ks4-infrared-black-bodies-h11",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "An astronomer finds a star whose peak emission lies in the ultraviolet. Predict how its surface temperature compares with the Sun's and explain.",
        "options": [
            "Cooler, because ultraviolet has a shorter wavelength and short wavelengths carry less energy than long ones",
            "The same, because every star is a black body and all black bodies peak at the same wavelength",
            "Cooler, because only a cool star can emit at a wavelength the human eye is unable to detect at all",
            "Hotter, because the peak moves to shorter wavelengths as the temperature rises, and the Sun peaks in the visible",
        ],
        "correct_index": 3,
        "why": "The peak wavelength is a direct reading of temperature, and ultraviolet is shorter than visible, so the star must be hotter than the Sun.",
    },
    {
        "id": "ks4-infrared-black-bodies-h12",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A vacuum flask has a vacuum between its two walls as well as a silvered finish. State what the vacuum does that the silvering does not.",
        "options": [
            "It stops conduction and convection across the gap, which the silvering has no effect on",
            "It stops radiation crossing the gap, which the silvering is unable to reduce on its own",
            "It keeps the silvering from tarnishing, which would otherwise spoil its ability to reflect",
            "It lowers the temperature of the inner wall, which slows every kind of energy transfer at once",
        ],
        "correct_index": 0,
        "why": "The three routes are dealt with separately: no particles in the gap means no conduction or convection, and the shiny surfaces handle the radiation.",
    },
    {
        "id": "ks4-infrared-black-bodies-h13",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A pupil argues that a black body must end up colder than everything else in a room, because it absorbs all the radiation and reflects none. Evaluate this.",
        "options": [
            "Correct, because absorbing radiation always lowers the temperature of the surface that takes it in",
            "Correct, because a body that reflects nothing has no way of sending energy back to its surroundings",
            "Incorrect, because it emits as freely as it absorbs, so it settles at the temperature of the room like anything else",
            "Incorrect, because it ends up hotter than everything else in the room, since it takes in all the radiation arriving",
        ],
        "correct_index": 2,
        "why": "The argument only counts the energy going in; being the best absorber also makes it the best emitter, so it reaches the same equilibrium as its surroundings.",
    },
    {
        "id": "ks4-infrared-black-bodies-h14",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A thermal camera shows a polished steel door as cooler than the painted wooden door beside it, though both are at room temperature. Explain the reading.",
        "options": [
            "The steel really is cooler, because metal conducts energy away from its surface faster than wood does",
            "The steel is a poor emitter, so it sends out less infrared than the wood at the same temperature and the camera reads it as cooler",
            "The steel is a good emitter, so it has already radiated away more of its energy than the wooden door has",
            "The camera is unable to detect any radiation whatever from a bare metal surface, so it simply shows every such surface as cold by default",
        ],
        "correct_index": 1,
        "why": "A thermal camera measures emitted infrared and converts it to a temperature assuming a good emitter, so a shiny surface is always read as cooler than it is.",
    },
    {
        "id": "ks4-infrared-black-bodies-h15",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Compare how a matt black surface and a polished one behave when each is hotter than its surroundings and when each is colder.",
        "options": [
            "The matt black surface loses energy faster when hotter and gains it faster when colder; the polished one is always slower at both",
            "The matt black surface loses energy faster when hotter but gains it more slowly when colder than its surroundings",
            "The polished surface loses energy faster when hotter but gains it more slowly when colder than its surroundings",
            "Both behave identically when colder than their surroundings, and differ only when they are hotter than them",
        ],
        "correct_index": 0,
        "why": "One property governs the exchange in both directions, so the better emitter is also the better absorber, whichever way the energy happens to be flowing.",
    },
    {
        "id": "ks4-infrared-black-bodies-h16",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "The matt black pipes of a solar water heater are mounted behind a sheet of glass. Suggest why the glass is there.",
        "options": [
            "It focuses the Sun's radiation onto the pipes, in the way a lens concentrates light to a point",
            "It filters out the wavelengths the pipes cannot absorb, so that only useful radiation reaches them",
            "It lets sunlight through to the pipes while cutting the energy the warm pipes lose to the moving air outside",
            "It reflects the Sun's radiation back up into the sky once the water inside the pipes is hot enough",
        ],
        "correct_index": 2,
        "why": "The pipes need to keep what they absorb, and a cover stops the wind carrying energy away while still admitting the incoming radiation.",
    },
    {
        "id": "ks4-infrared-black-bodies-h17",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A shed roof painted matt black warms quickly on a sunny day but is also the first to cool after sunset. Explain why one surface does both.",
        "options": [
            "The dark paint absorbs strongly by day, and it always emits just as strongly once there is no sunlight arriving",
            "The dark paint absorbs strongly by day, and by night it reflects the cold of the sky back down into the shed",
            "The dark paint is thin, so it warms quickly in the Sun and then conducts its energy away into the night air",
            "The dark paint absorbs by day and stops absorbing at night, which is what makes the roof cool so quickly",
        ],
        "correct_index": 0,
        "why": "Absorption and emission are the same property, so the finish that gains fastest in sunlight is also the one that loses fastest in the dark.",
    },
    {
        "id": "ks4-infrared-black-bodies-h18",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A student says a hotter object emits only short wavelengths. Evaluate this statement.",
        "options": [
            "Correct, because raising the temperature moves the whole of the emission to shorter wavelengths together",
            "Correct, because the long wavelengths are absorbed again by the object before they can leave its surface",
            "Incorrect, because a hotter object emits only the long wavelengths, and it is in fact a cool object that emits the short ones instead",
            "Incorrect, because it emits across a broad range of wavelengths; what moves to the short end is the peak of the spectrum",
        ],
        "correct_index": 3,
        "why": "A black body emits at every wavelength at once; heating it raises the emission everywhere and shifts where the maximum lies, but it does not switch the long wavelengths off.",
    },

    # ── standard ────────────────────────────────────────────────────────
    {
        "id": "ks4-infrared-black-bodies-s19",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Two students plan to compare the cooling rates of a matt black beaker and a shiny beaker, both holding hot water. State one variable, other than the surface finish, that they must keep the same for a fair test.",
        "options": [
            "The colour of the room's walls, since a coloured wall could change how fast any nearby object radiates its own heat away",
            "The brand name printed on each beaker, since a different printed brand name might well affect how the water itself cools",
            "The day of the week that the whole test happens to be run on, since radiation behaves consistently on certain days",
            "The starting temperature and volume of water in each beaker, since either one being different would affect the cooling rate",
        ],
        "correct_index": 3,
        "why": "If the beakers start with different amounts of water at different temperatures, any difference in cooling could be caused by that rather than by the surface finish being compared.",
    },
    {
        "id": "ks4-infrared-black-bodies-s20",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A heat sink is built with many thin metal fins rather than as one thick block of the same mass and finish. Explain why the fins lose energy by radiation faster.",
        "options": [
            "The fins give the heat sink a much greater surface area exposed to the surroundings, so more energy is radiated each second",
            "The fins make the metal itself a better emitter of infrared, even though the surface finish has not been changed in any way",
            "The fins lower the overall temperature of the metal, and a cooler object radiates energy away more quickly regardless",
            "The fins reduce how much of the metal is exposed to the air, which speeds up how fast radiation is able to leave it",
        ],
        "correct_index": 0,
        "why": "Radiation is emitted from a surface, so spreading the same mass of metal over many thin fins increases the total surface area from which energy can leave each second.",
    },
    {
        "id": "ks4-infrared-black-bodies-s21",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A thermal camera shows a person clearly in a completely dark room, yet the naked eye sees nothing at all. Explain why.",
        "options": [
            "The camera adds its own light to the room, which the eye is simply too slow to notice or respond to in time",
            "The person's skin starts emitting infrared once a camera is pointed towards them, which the eye cannot trigger",
            "The eye is limited to detecting visible light, while a person at body temperature emits almost entirely in the infrared instead",
            "The room is not truly dark to infrared radiation, since infrared carries its own built-in source of illumination regardless",
        ],
        "correct_index": 2,
        "why": "A person at body temperature emits mostly infrared rather than visible light, and the human eye has no way of detecting infrared at all, however dark the room is.",
    },
    {
        "id": "ks4-infrared-black-bodies-s22",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A firefighter's thermal imaging camera can locate a person through thick smoke, when the firefighter's own eyes cannot see through it at all. Explain why.",
        "options": [
            "The longer wavelengths of infrared are scattered and absorbed by the smoke particles far less than visible light is",
            "The camera simply removes the smoke from the image electronically, in a way the human eye is unable to do",
            "The smoke itself blocks visible light completely but happens to be entirely transparent to sound waves instead",
            "The infrared given out by a person burns a path straight through smoke, which visible light is too weak to manage",
        ],
        "correct_index": 0,
        "why": "Smoke particles scatter shorter visible wavelengths strongly, but the longer infrared wavelengths pass through far more easily, so the camera keeps a usable image.",
    },
    {
        "id": "ks4-infrared-black-bodies-s23",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A weather thermometer is kept inside a white louvred box rather than left out in direct sunshine. Explain why this gives a more accurate reading of the air temperature.",
        "options": [
            "The white box reflects sound waves away from the thermometer, which would otherwise disturb its reading of the air",
            "The white box magnifies the scale of the thermometer, making the true air temperature easier for a person to read off",
            "The white, louvred box stops the thermometer absorbing sunlight directly, which would otherwise heat it above the true air temperature",
            "The white box traps a layer of still air right next to the bulb of the thermometer, which lowers its reading below the true air temperature",
        ],
        "correct_index": 2,
        "why": "A thermometer left in direct sunlight absorbs solar radiation and reads its own temperature rather than the air's, so shielding it with a reflective box keeps the reading closer to the true air temperature.",
    },
    {
        "id": "ks4-infrared-black-bodies-s24",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "The bulb of a thermometer used to detect radiant heat from a source is coated in a thin layer of matt black paint. Suggest why.",
        "options": [
            "The matt black coating stops the glass bulb itself from cracking as it warms up quickly during the whole experiment",
            "The matt black coating makes the bulb into a strong, consistent absorber of the radiation reaching it, giving a reliable reading",
            "The matt black coating slows down how quickly the thermometer is able to respond to any radiation reaching it",
            "The matt black coating changes the temperature scale printed on the thermometer's glass to make small changes far easier to see",
        ],
        "correct_index": 1,
        "why": "A matt black surface absorbs radiation efficiently and consistently, whatever the source, which makes it a dependable detector for comparing how much radiation is arriving.",
    },
    {
        "id": "ks4-infrared-black-bodies-s25",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "An electric hob ring set to a low power feels warm nearby but produces no visible glow at all, while the same ring on full power glows orange. Explain the difference.",
        "options": [
            "At low power the ring stops emitting any radiation completely, and the warmth felt instead comes from the surrounding air",
            "At low power the ring is cooler, so its emission still peaks in the infrared and stays below the level needed to glow visibly",
            "At low power the ring instead emits sound energy, which the hand can feel as warmth without the eye seeing anything",
            "At low power the ring reflects light from around the kitchen rather than emitting any of its own, unlike it does on full power",
        ],
        "correct_index": 1,
        "why": "A cooler surface still emits, but its peak wavelength stays in the infrared; only once it is hot enough does enough of the emission spill over into the visible band to be seen glowing.",
    },
    {
        "id": "ks4-infrared-black-bodies-s26",
        "subtopic_slug": "infrared-black-bodies",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what is meant by describing the radiation emitted by a hot object as a continuous spectrum.",
        "options": [
            "The object emits radiation at every wavelength across a broad, unbroken range at once, rather than at a single wavelength alone",
            "The object emits radiation without ever once stopping, day and night, for as long as it remains above absolute zero",
            "The object emits radiation at one single exact wavelength, which then shifts smoothly along as the temperature changes",
            "The object emits radiation continuously but in a single direction, rather than spreading outward in every direction at once",
        ],
        "correct_index": 0,
        "why": "A continuous spectrum means the emission is spread smoothly across a broad band of wavelengths at the same time, not concentrated at a single one.",
    },
    # ── harder ──────────────────────────────────────────────────────────
    {
        "id": "ks4-infrared-black-bodies-h19",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "An infrared photograph taken through an ordinary glass window shows the glass itself looking almost black, even though the same window looks perfectly transparent to visible light. Explain this difference.",
        "options": [
            "The camera's sensor cannot record anything through glass whatsoever, so it simply shows black wherever glass is present",
            "Ordinary glass reflects almost all infrared straight back the way it came, which the camera reads in the same way as black",
            "Ordinary glass absorbs and blocks a great deal of infrared, even though it transmits visible light with very little loss",
            "The window looks black simply because it is colder than the objects around it, not because of anything to do with glass",
        ],
        "correct_index": 2,
        "why": "How well a material transmits radiation depends on wavelength, and ordinary glass, though transparent to visible light, is a poor transmitter of much of the infrared band.",
    },
    {
        "id": "ks4-infrared-black-bodies-h20",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A metal spoon left standing in a mug of hot tea feels warm at the handle within seconds, while a wooden spoon in an identical mug stays cool at the handle far longer. A student says this must be because the metal spoon absorbs and re-emits infrared better than the wood does. Evaluate this explanation.",
        "options": [
            "Correct, because a metal surface is a far better absorber and emitter of infrared than a wooden one is",
            "Correct, because infrared travels fastest through the densest material, and metal is far denser than wood",
            "Incorrect, because the true reason is conduction: metal conducts energy along its length far better than wood, which is a poor conductor",
            "Incorrect, because neither spoon can become warm from the tea without direct contact between their bulbs and the drinker's hand itself",
        ],
        "correct_index": 2,
        "why": "The handle heats quickly because metal is a good thermal conductor and carries energy up from the bowl of the spoon; this has nothing to do with infrared absorption or emission at all.",
    },
    {
        "id": "ks4-infrared-black-bodies-h21",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Two thermometers, one with a shiny bulb and one with a matt black bulb, are both left in direct sunlight with no shielding at all. A student claims the shiny one must give the more accurate reading of the true air temperature. Evaluate this claim.",
        "options": [
            "Correct, because the shiny bulb absorbs solar radiation far less than the matt black one, so it over-reads by a smaller amount",
            "Correct, because the shiny bulb reflects heat downward onto the ground, cancelling out the effect of the sunlight completely",
            "Incorrect, because a shiny bulb absorbs solar radiation more strongly than a matt black bulb placed beside it regardless",
            "Incorrect, because neither bulb's finish makes the slightest difference once both are sitting in the same direct sunlight",
        ],
        "correct_index": 0,
        "why": "Without any shield, both thermometers over-read in direct sun, but the shiny bulb absorbs less of the arriving radiation than the matt black one, so its reading is relatively closer to the true air temperature.",
    },
    {
        "id": "ks4-infrared-black-bodies-h22",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Two students compare the cooling of hot water in a matt black glass beaker and a shiny metal beaker, and conclude that surface finish alone explains the difference they measure. Explain why their conclusion is not safe.",
        "options": [
            "It is perfectly safe, because glass and metal beakers conduct energy away from hot water at exactly the same steady rate",
            "It is not safe, because glass and metal conduct energy through their walls at very different rates, a second uncontrolled variable",
            "It is not safe, because a metal beaker simply cannot hold hot water for long enough for any meaningful comparison to be made",
            "It is perfectly safe, because the single property of a beaker that can ever affect its cooling by radiation is the surface finish",
        ],
        "correct_index": 1,
        "why": "Changing both the surface finish and the material of the beaker at once means any difference in cooling could be due to the different thermal conductivity of glass and metal, not the surface finish being tested.",
    },
    {
        "id": "ks4-infrared-black-bodies-h23",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A poker left in a fire feels warm long before it glows, then turns dull red, then bright orange the longer it is left in. A student argues the poker only begins emitting radiation once it first turns visibly red. Evaluate this argument.",
        "options": [
            "Correct, because a cool object below red heat has no way of emitting any radiation of its own accord whatsoever",
            "Correct, because the fire itself begins to radiate its own energy across into the poker once the poker has started to glow visibly",
            "Incorrect, because the poker emits infrared from the moment it enters the fire; the glow appears once its peak reaches the visible band",
            "Incorrect, because the poker was already glowing red before it was ever placed anywhere near the fire in the first place",
        ],
        "correct_index": 2,
        "why": "Every object above absolute zero emits continuously; the poker radiates in the infrared from the start, and only produces a visible glow once it is hot enough for its peak emission to reach the visible band.",
    },
    {
        "id": "ks4-infrared-black-bodies-h24",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A satellite dish is built with a shiny metal collecting surface, even though a matt black surface would absorb the very faint incoming radio signal more completely. Suggest why engineers still choose the shiny finish.",
        "options": [
            "The shiny surface is there to geometrically reflect and focus the incoming signal onto the receiver, not to absorb it as heat",
            "The shiny surface is simply cheaper to manufacture at the large sizes that satellite dishes are usually built to",
            "The shiny surface stops the dish from being seen from a distance, which protects the signal from outside interference",
            "The shiny surface is chosen purely for its appearance, since the dish's electrical performance does not depend on its finish",
        ],
        "correct_index": 0,
        "why": "A dish works by reflecting and concentrating the incoming wave onto a receiver at its focus, which is a geometric job that a shiny, reflective surface performs far better than a good absorber ever could.",
    },
    {
        "id": "ks4-infrared-black-bodies-h25",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A hollow metal cube has four different faces: matt black, matt white, shiny (polished) metal, and dull grey, all filled with the same hot water. A detector is held at a fixed distance from each face in turn. Predict which face gives the highest reading and which gives the lowest.",
        "options": [
            "Matt white gives the highest reading and shiny metal gives the lowest, since colour alone decides how well any surface emits",
            "Matt black gives the highest reading and shiny metal gives the lowest, since dark, matt surfaces emit best and shiny surfaces emit worst",
            "Dull grey gives the highest reading and matt black gives the lowest, since a mid-tone surface beats either extreme regardless of finish",
            "All four faces give the same reading, since every face is at the same water temperature regardless of its finish",
        ],
        "correct_index": 1,
        "why": "Emission depends on both colour and texture together, and a dark, matt surface is the best combination for emitting, while a bright, polished one is the worst, whatever their individual colour alone might suggest.",
    },
    {
        "id": "ks4-infrared-black-bodies-h26",
        "subtopic_slug": "infrared-black-bodies",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A weather balloon's instrument package is wrapped in white fabric, even though a black fabric would absorb far more sunlight to power its solar cells. Suggest why keeping the instruments cool is judged more important than maximising solar absorption here.",
        "options": [
            "White fabric weighs noticeably less than an equivalent black fabric of the same size, which matters far more to a balloon than solar power could",
            "Delicate instruments can be damaged or give false readings if they overheat, so limiting absorption protects them, even at a power cost",
            "White fabric is simply easier for ground crews to spot against the sky, which matters more to them than the power supply ever does",
            "Black fabric would prevent any sunlight from reaching the solar cells, so white is the sole finish able to generate power",
        ],
        "correct_index": 1,
        "why": "Overheating can damage sensitive instruments or distort their readings, so engineers sometimes deliberately accept less absorbed solar energy in order to keep a package within a safe temperature range.",
    },
]
