"""Physics · Waves — the MRB-338 expansion: lenses.

Subtopic 6.6.3 (physics only) is the one place in the course where a pupil has
to hold several facts in a fixed relationship at once: the shape of the lens,
where the object sits relative to f and 2f, and what image comes out of that.
So the rows walk the object inwards — beyond 2f, at 2f, between f and 2f, at f,
inside f — and keep asking what changes. The three construction rays are asked
in words, because no stem here may lean on a drawing. Magnification is worked
in both directions and from both pairs of quantities, with the unit conversions
that catch people out, and the working always sits in the `why`, never in an
option. The eye and the instruments that use lenses close the leaf.
"""

TOPIC = "waves"
SUBJECT = "physics"

QUESTIONS = [
    # ── easier ──────────────────────────────────────────────────────────
    {
        "id": "ks4-lenses-e05",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State the shape of a converging lens.",
        "options": [
            "Thicker in the middle than at the edges",
            "Thinner in the middle than at the edges",
            "The same thickness all the way across",
            "Flat on both of its faces",
        ],
        "correct_index": 0,
        "why": "A converging lens bulges outwards, so it is thickest at its centre; that shape is what brings parallel rays together.",
    },
    {
        "id": "ks4-lenses-e06",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what a diverging lens does to rays of light travelling parallel to its principal axis.",
        "options": [
            "It brings them together at a point beyond the lens",
            "It spreads them apart so that they travel outwards",
            "It sends them all back the way they came",
            "It lets them pass through without changing them",
        ],
        "correct_index": 1,
        "why": "A diverging lens spreads parallel rays outwards, so they appear afterwards to be coming from a point behind the lens.",
    },
    {
        "id": "ks4-lenses-e07",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State where the focal point of a diverging lens lies.",
        "options": [
            "On the far side of the lens from the incoming light",
            "On the same side as the incoming light",
            "Exactly at the centre of the lens itself",
            "At the very edge of the rim of the lens",
        ],
        "correct_index": 1,
        "why": "The spread rays only appear to come from the focal point, and that point is on the side the light arrived from, which is why it is called virtual.",
    },
    {
        "id": "ks4-lenses-e08",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State the type of image a diverging lens forms, wherever the object is placed.",
        "options": [
            "Real, inverted and always magnified",
            "Real, upright and always diminished",
            "Always virtual, upright and diminished",
            "Virtual, inverted and always magnified",
        ],
        "correct_index": 2,
        "why": "A diverging lens never brings rays to a meeting point, so its image is always virtual, the same way up as the object, and smaller.",
    },
    {
        "id": "ks4-lenses-e09",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what happens to a ray of light that passes through the exact centre of a lens.",
        "options": [
            "It is bent towards the principal axis",
            "It is bent away from the principal axis",
            "It always carries straight on, undeviated",
            "It is reflected back along its own path",
        ],
        "correct_index": 2,
        "why": "At the centre the two faces of the lens are parallel, so a ray through it emerges along the direction it came in on.",
    },
    {
        "id": "ks4-lenses-e10",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "A ray travelling parallel to the principal axis passes through a converging lens. State the path it takes afterwards.",
        "options": [
            "It goes on through the focal point on the far side",
            "It goes on parallel to the axis, as it arrived",
            "It goes back through the focal point on the near side",
            "It goes off at right angles to the principal axis",
        ],
        "correct_index": 0,
        "why": "This is the first of the three construction rays: parallel in, through the focal point out.",
    },
    {
        "id": "ks4-lenses-e11",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "A ray passes through the focal point on the near side of a converging lens. State the path it takes after the lens.",
        "options": [
            "It travels on through the focal point on the far side",
            "It travels on parallel to the principal axis",
            "It travels back along the path it came in on",
            "It crosses the principal axis at twice the focal length",
        ],
        "correct_index": 1,
        "why": "This is the reverse of the parallel ray: through the focal point in, parallel to the axis out.",
    },
    {
        "id": "ks4-lenses-e12",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State the unit of magnification.",
        "options": [
            "The metre",
            "The centimetre",
            "The dioptre",
            "It has no unit",
        ],
        "correct_index": 3,
        "why": "Magnification is one length divided by another, so the units cancel and the answer is a plain number.",
    },
    {
        "id": "ks4-lenses-e13",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State how magnification is calculated from the heights of an object and its image.",
        "options": [
            "Object height divided by image height",
            "Image height divided by object height",
            "Image height multiplied by object height",
            "Image height added to object height",
        ],
        "correct_index": 1,
        "why": "Magnification is image height ÷ object height, so a value above 1 means the image is larger than the object.",
    },
    {
        "id": "ks4-lenses-e14",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what is meant by a real image.",
        "options": [
            "One that the rays only appear to come from",
            "One formed where the rays actually meet",
            "One that is always the same way up as the object",
            "One that is always larger than the object",
        ],
        "correct_index": 1,
        "why": "The rays genuinely cross at a real image, which is why it can be caught on a screen placed there.",
    },
    {
        "id": "ks4-lenses-e15",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State which type of lens a camera uses to form its picture.",
        "options": [
            "A converging lens",
            "A diverging lens",
            "A flat sheet of glass",
            "A curved mirror",
        ],
        "correct_index": 0,
        "why": "A camera needs a real image on its sensor, and only a converging lens can bring rays together to make one.",
    },
    {
        "id": "ks4-lenses-e16",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the part of the eye on which the image is formed.",
        "options": [
            "The cornea",
            "The pupil",
            "The iris",
            "The retina",
        ],
        "correct_index": 3,
        "why": "The cornea and eye lens together focus light onto the retina at the back of the eye.",
    },
    {
        "id": "ks4-lenses-e17",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the muscles that change the shape of the lens in the eye.",
        "options": [
            "The ciliary muscles",
            "The optic muscles",
            "The retinal muscles",
            "The corneal muscles",
        ],
        "correct_index": 0,
        "why": "The ciliary muscles alter the curvature of the eye lens, which changes its focal length so that near and far objects can both be focused.",
    },
    {
        "id": "ks4-lenses-e18",
        "subtopic_slug": "lenses",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State the other name for a converging lens.",
        "options": [
            "A concave lens",
            "A convex lens",
            "A plane lens",
            "A prism lens",
        ],
        "correct_index": 1,
        "why": "Converging lenses are convex — they bulge outwards; diverging lenses are concave and curve inwards.",
    },

    # ── standard ────────────────────────────────────────────────────────
    {
        "id": "ks4-lenses-s05",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "An object is placed exactly two focal lengths from a converging lens. Describe the image formed.",
        "options": [
            "Real, inverted and the same size as the object, two focal lengths beyond the lens",
            "Real, upright and twice the size of the object, one focal length beyond the lens",
            "Virtual, upright and the same size as the object, on the same side as the object itself",
            "Virtual, inverted and half the size of the object, two focal lengths beyond the lens",
        ],
        "correct_index": 0,
        "why": "At 2f the object and image distances are equal, so the magnification is exactly 1 and the image is inverted at 2f on the other side.",
    },
    {
        "id": "ks4-lenses-s06",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A converging lens forms a real image that is larger than the object. State what this tells you about where the object must be.",
        "options": [
            "Nearer to the lens than the focal point is, so that the rays are still spreading as they leave",
            "Further from the lens than twice the focal length, which is where all magnified images are formed",
            "Exactly at the focal point of the lens, which is the position that gives the greatest magnification",
            "Between one and two focal lengths from the lens",
        ],
        "correct_index": 3,
        "why": "Only in the band between f and 2f does a converging lens give a real image bigger than the object; inside f the image would be virtual and beyond 2f it would be diminished.",
    },
    {
        "id": "ks4-lenses-s07",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "An object stands 20 cm from a lens and its image is formed 60 cm from the lens. Calculate the magnification.",
        "options": [
            "0.33",
            "3.0",
            "40",
            "1200",
        ],
        "correct_index": 1,
        "why": "Magnification is image distance ÷ object distance = 60 ÷ 20 = 3.0.",
    },
    {
        "id": "ks4-lenses-s08",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A microscope makes a cell of width 0.050 mm appear 4.0 mm wide. Calculate the magnification.",
        "options": [
            "0.0125",
            "80",
            "0.20",
            "8.0",
        ],
        "correct_index": 1,
        "why": "Magnification is image width ÷ object width = 4.0 ÷ 0.050 = 80.",
    },
    {
        "id": "ks4-lenses-s09",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a diverging lens cannot form an image that can be caught on a screen.",
        "options": [
            "It spreads the rays apart, so they never meet and there is no point at which a screen would catch them",
            "It absorbs so much of the light passing through it that too little is left to show up on a screen",
            "It forms its image behind the screen, so the screen would have to be moved past the lens to catch it",
            "It forms an image that is far too small to be seen, however close the screen is placed to the lens",
        ],
        "correct_index": 0,
        "why": "A screen shows an image only where rays actually cross; a diverging lens always leaves them spreading, so its image is virtual.",
    },
    {
        "id": "ks4-lenses-s10",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A lens forms an image with a magnification of 0.25. State what this tells you about the image.",
        "options": [
            "It is a quarter of the height of the object",
            "It is four times the height of the object",
            "It is a quarter of the way to the focal point",
            "It is upright, whatever the height of the object",
        ],
        "correct_index": 0,
        "why": "A magnification below 1 means the image is smaller than the object, by that factor.",
    },
    {
        "id": "ks4-lenses-s11",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A camera focused on a distant hill must have its lens moved before a nearby flower is sharp. Explain why.",
        "options": [
            "The flower reflects far less light than the distant hill does, so the lens is moved to gather enough of it for a picture",
            "The flower is smaller than the hill, so the lens is moved to magnify it enough to fill the sensor",
            "Light from the flower arrives spreading rather than parallel, so it is brought to a focus further from the lens",
            "Light from the flower arrives spreading rather than parallel, so it is brought to a focus nearer the lens",
        ],
        "correct_index": 2,
        "why": "Parallel light from a distant object focuses at f; light from a near object diverges as it arrives and so meets further beyond the lens, and the sensor must be there.",
    },
    {
        "id": "ks4-lenses-s12",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Describe the image formed on the retina of a normal eye looking at a distant tree.",
        "options": [
            "Virtual, upright and diminished, since the eye always sees things the right way up",
            "Real, upright and diminished, since the cornea turns the image round before the lens",
            "Virtual, inverted and magnified, since the lens of the eye is a very powerful converging lens",
            "Real, inverted and diminished, since a converging lens forms a real image of a distant object",
        ],
        "correct_index": 3,
        "why": "The eye works like a camera: the image on the retina is real, inverted and much smaller than the object, and the brain interprets it the right way up.",
    },
    {
        "id": "ks4-lenses-s13",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain how the eye changes focus from a distant object to a book held close.",
        "options": [
            "The ciliary muscles contract, making the lens fatter, which shortens its focal length",
            "The ciliary muscles contract, making the lens thinner, which lengthens its focal length",
            "The whole lens is moved forward in the eye, in the way a camera lens is moved to focus",
            "The pupil widens to let in more light, which brings the near object into focus on the retina",
        ],
        "correct_index": 0,
        "why": "The eye cannot move its lens, so it changes its shape instead: a fatter lens is more powerful and focuses the diverging light from a near object onto the retina.",
    },
    {
        "id": "ks4-lenses-s14",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "State where light from a distant object is brought to a focus in the eye of a short-sighted person who is not wearing glasses.",
        "options": [
            "Behind the retina",
            "In front of the retina",
            "Exactly on the retina",
            "On the front surface of the cornea",
        ],
        "correct_index": 1,
        "why": "A short-sighted eye is too powerful for its length, so the rays cross before they reach the retina and have spread again by the time they get there.",
    },
    {
        "id": "ks4-lenses-s15",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a magnifying glass only works when it is held quite close to the object being examined.",
        "options": [
            "The object has to be nearer than the focal point, or the lens will not give a magnified upright image",
            "The object has to be further away than the focal point, or the light will never reach the lens",
            "The object has to touch the glass, because any air gap would spoil the image the lens forms",
            "The object has to be within arm's reach, so the eye and the lens move together",
        ],
        "correct_index": 0,
        "why": "Inside the focal length the refracted rays are still spreading, so they form a virtual, upright, magnified image; outside it the image turns real and inverted.",
    },
    {
        "id": "ks4-lenses-s16",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "An object 5.0 mm tall produces an image 2.0 cm tall. Calculate the magnification.",
        "options": [
            "0.25",
            "2.5",
            "4.0",
            "0.40",
        ],
        "correct_index": 2,
        "why": "2.0 cm is 20 mm, so the magnification is 20 ÷ 5.0 = 4.0; both heights must be in the same unit first.",
    },
    {
        "id": "ks4-lenses-s17",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A telescope uses an objective lens of long focal length and an eyepiece of short focal length. Explain why the two differ.",
        "options": [
            "The long focal length gathers the light and the short one spreads it, so brightness is evened out",
            "The objective forms a small image of a distant object, and the short-focus eyepiece then magnifies that image strongly",
            "The objective must be long so that it can reach further out towards the object being observed by the telescope",
            "The two focal lengths must differ so that the light passes through each lens at a different speed in turn",
        ],
        "correct_index": 1,
        "why": "The objective makes a real image inside the tube; the eyepiece is used as a magnifying glass on it, and a shorter focal length magnifies more.",
    },
    {
        "id": "ks4-lenses-s18",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Two converging lenses are the same size, but one is far more strongly curved than the other. Compare their focal lengths.",
        "options": [
            "The more curved lens has the longer focal length, because it bends the light over a greater distance",
            "The more curved lens has the shorter focal length, because it bends the light more strongly",
            "The two have the same focal length, because they are made from glass of the same kind",
            "The two have the same focal length, because they are both the same size across",
        ],
        "correct_index": 1,
        "why": "A steeper surface refracts each ray through a larger angle, so the rays meet closer to the lens, which is a shorter focal length.",
    },

    # ── harder ──────────────────────────────────────────────────────────
    {
        "id": "ks4-lenses-h05",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "An object stands 25 cm from a converging lens and the magnification is 2.0. Calculate the distance from the lens to the image.",
        "options": [
            "12.5 cm",
            "27 cm",
            "50 cm",
            "23 cm",
        ],
        "correct_index": 2,
        "why": "Magnification is image distance ÷ object distance, so the image distance is 2.0 × 25 = 50 cm.",
    },
    {
        "id": "ks4-lenses-h06",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A lens forms an image 24 cm from it at a magnification of 0.50. Calculate how far the object is from the lens.",
        "options": [
            "12 cm",
            "48 cm",
            "24.5 cm",
            "2.1 cm",
        ],
        "correct_index": 1,
        "why": "Magnification is image distance ÷ object distance, so the object distance is 24 ÷ 0.50 = 48 cm.",
    },
    {
        "id": "ks4-lenses-h07",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A projector throws a 1.8 m tall picture of a slide 3.0 cm tall. The slide sits 12 cm from the lens. Calculate the distance from the lens to the screen.",
        "options": [
            "0.20 m",
            "7.2 m",
            "60 m",
            "1.9 m",
        ],
        "correct_index": 1,
        "why": "1.8 m is 180 cm, so the magnification is 180 ÷ 3.0 = 60, and the image distance is 60 × 12 = 720 cm, which is 7.2 m.",
    },
    {
        "id": "ks4-lenses-h08",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A student writes: 'A converging lens always forms a real image, because it always brings rays together.' Evaluate this statement.",
        "options": [
            "Correct, because every ray leaving a converging lens is bent inwards and must therefore meet the others somewhere beyond it",
            "Correct, because a converging lens is defined as one that produces an image that can be caught on a screen",
            "Incorrect, because a converging lens produces a virtual image whenever the object is nearer than the focal point",
            "Incorrect, because a converging lens produces a virtual image whenever the object is further away than twice the focal length",
        ],
        "correct_index": 2,
        "why": "The lens does bend every ray inwards, but if the object is inside f the rays are still spreading when they leave, so they only appear to come from a point behind the object.",
    },
    {
        "id": "ks4-lenses-h09",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "An object is moved steadily from well beyond 2f towards the focal point of a converging lens. Predict what happens to the real image.",
        "options": [
            "It moves further from the lens and grows steadily larger",
            "It moves closer to the lens and grows steadily larger",
            "It moves further from the lens and shrinks steadily smaller",
            "It stays where it is and simply becomes brighter as the object approaches",
        ],
        "correct_index": 0,
        "why": "As the object approaches f the light reaching the lens diverges more, so it is brought to a focus further away, and the magnification rises with the image distance.",
    },
    {
        "id": "ks4-lenses-h10",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why the real image formed by a converging lens is upside down.",
        "options": [
            "The lens turns the light through half a turn as it passes, which inverts everything that goes through it",
            "Light from the top of the object crosses the axis at the centre of the lens and arrives below the axis",
            "The image is only inverted because a screen has to be held the other way round to catch it properly",
            "The glass of the lens reverses the order of the colours in the light, which the eye reads as an inversion",
        ],
        "correct_index": 1,
        "why": "The undeviated ray through the centre carries the top of the object across the axis to the far side, so the image is formed the other way up.",
    },
    {
        "id": "ks4-lenses-h11",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Compare the images a converging lens forms when the object is inside the focal length with those it forms when the object is beyond twice the focal length.",
        "options": [
            "Inside f the image is virtual, upright and magnified; beyond 2f it is real, inverted and diminished",
            "Inside f the image is real, inverted and magnified; beyond 2f it is virtual, upright and diminished",
            "Inside f the image is virtual, inverted and diminished; beyond 2f it is real, upright and magnified",
            "Both images are real and inverted, and the only difference between them is the size that each one comes out",
        ],
        "correct_index": 0,
        "why": "Crossing the focal point flips every property at once: real becomes virtual, inverted becomes upright, and the image grows instead of shrinking.",
    },
    {
        "id": "ks4-lenses-h12",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A microscope uses two converging lenses one after the other. Explain why the magnification is larger than either lens would give alone.",
        "options": [
            "The two lenses share the light between them, and the sum of the two amounts is what reaches the eye",
            "The second lens magnifies the image made by the first, so the two magnifications multiply together",
            "The two lenses have their focal points at the same place, and that doubles the power of the pair",
            "The second lens corrects the inversion of the first, and an upright image always looks larger",
        ],
        "correct_index": 1,
        "why": "The objective's real image becomes the object for the eyepiece, so a magnification of, say, 10 followed by one of 10 gives 100 overall.",
    },
    {
        "id": "ks4-lenses-h13",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "An object placed 30 cm from a converging lens forms a real image the same size as the object. Determine the focal length of the lens.",
        "options": [
            "60 cm",
            "30 cm",
            "15 cm",
            "7.5 cm",
        ],
        "correct_index": 2,
        "why": "An image the same size as the object is formed only when the object sits at 2f, so 2f = 30 cm and f = 15 cm.",
    },
    {
        "id": "ks4-lenses-h14",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Half of a converging lens is covered with black card. Predict the effect on the real image it forms.",
        "options": [
            "Only half of the image is formed, and the covered half of the picture is missing entirely",
            "The whole image is still formed, but it is dimmer because less light reaches it",
            "The image is turned the right way up, because only one half of the lens now inverts it",
            "No image is formed at all, because a lens must be complete to bring rays to a focus",
        ],
        "correct_index": 1,
        "why": "Rays from every point of the object pass through every part of the lens, so the uncovered half still forms the complete image using fewer rays.",
    },
    {
        "id": "ks4-lenses-h15",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A pupil says that a magnifying glass 'makes the object bigger'. Explain what is wrong with this description.",
        "options": [
            "The object is unchanged; it is the image formed by the lens that is larger than the object",
            "The object is unchanged; it is the focal length of the lens that is larger than the object",
            "The object really is made larger, but only for as long as the lens is held in front of it",
            "The object is unchanged, and the lens does no magnifying but simply brightens what is seen",
        ],
        "correct_index": 0,
        "why": "A lens cannot alter the thing being looked at; magnification describes the size of the image relative to the object.",
    },
    {
        "id": "ks4-lenses-h16",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A long-sighted person's eyes look noticeably larger to someone facing them. Suggest why.",
        "options": [
            "The converging lenses in the glasses form a magnified virtual image of the wearer's eyes",
            "The diverging lenses in the glasses form a magnified virtual image of the wearer's eyes",
            "The eyes of a long-sighted person really are larger, which is what causes the condition",
            "The glass of the lenses reflects extra light onto the eyes, which makes them appear larger",
        ],
        "correct_index": 0,
        "why": "Long sight is corrected with converging lenses, and the wearer's eyes lie well inside the focal length, so an observer sees an enlarged virtual image of them.",
    },
    {
        "id": "ks4-lenses-h17",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "An object 8.0 mm tall gives an image 2.4 cm tall formed 54 cm from the lens. Calculate the distance from the object to the lens.",
        "options": [
            "162 cm",
            "18 cm",
            "6.8 cm",
            "45 cm",
        ],
        "correct_index": 1,
        "why": "2.4 cm is 24 mm, so the magnification is 24 ÷ 8.0 = 3.0, and the object distance is 54 ÷ 3.0 = 18 cm.",
    },
    {
        "id": "ks4-lenses-h18",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A converging lens is used as a magnifying glass and the object is then moved slowly outwards past the focal point. Predict what happens to the image.",
        "options": [
            "The upright magnified image grows, then no image forms at the focal point, and beyond it the image is real and inverted",
            "The upright magnified image shrinks steadily, and once past the focal point it becomes upright and diminished instead",
            "The upright magnified image stays exactly as it is, because the lens itself has not been altered in any way",
            "The upright magnified image becomes inverted at once, and it goes on growing steadily as the object moves out",
        ],
        "correct_index": 0,
        "why": "At the focal point the refracted rays emerge parallel and never meet, which is the boundary between the virtual upright image inside f and the real inverted one beyond it.",
    },

    # ── standard ────────────────────────────────────────────────────────
    {
        "id": "ks4-lenses-s19",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A camera's zoom lens is set to a longer focal length while photographing a distant building, without the camera moving. Explain the effect on the image formed on the sensor.",
        "options": [
            "The image becomes smaller, because a longer focal length brings the real image closer to the lens than before it was adjusted",
            "The image becomes dimmer, because a longer focal length lets noticeably less of the scene's light reach the sensor at once",
            "The image becomes larger, because a longer focal length places the real image of a distant object further from the lens",
            "The image stays the same, because the distance from the camera to the building has not altered in the slightest",
        ],
        "correct_index": 2,
        "why": "For a distant object the real image forms close to the focal point, so a longer focal length pushes that point further out and the image grows in proportion.",
    },
    {
        "id": "ks4-lenses-s20",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A diverging lens forms a virtual image with a magnification of 0.40 from an object 5.0 cm tall. Calculate the height of the image.",
        "options": [
            "12.5 cm, from dividing the object height by the magnification given",
            "5.4 cm, from adding the magnification onto the object height given",
            "0.080 cm, from dividing the magnification by the object height given",
            "2.0 cm, from multiplying the object height by the magnification given",
        ],
        "correct_index": 3,
        "why": "Image height = magnification x object height = 0.40 x 5.0 = 2.0 cm.",
    },
    {
        "id": "ks4-lenses-s21",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "An object stands 140 mm from a lens, and its real image forms 42 cm from the lens. Calculate the magnification.",
        "options": [
            "3.0, from converting 140 mm to 14 cm and dividing 42 cm by that",
            "0.33, from converting 140 mm to 14 cm and dividing that by 42 cm",
            "58, from treating 140 mm and 42 cm as though they were already the same unit and dividing",
            "588, from multiplying 140 by 42 without converting either value's unit first",
        ],
        "correct_index": 0,
        "why": "140 mm is 14 cm, so the magnification is 42 divided by 14, which is 3.0; the two distances must be in the same unit first.",
    },
    {
        "id": "ks4-lenses-s22",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a ray of light passing through a lens, away from its very centre, changes direction twice rather than once.",
        "options": [
            "Because the lens is curved on just one side, so that single curved surface bends the ray in two separate stages as it passes",
            "Because the ray reflects once inside the glass before refracting back out again through the very same face it entered by",
            "Because the glass is denser at its centre than at its edges, which causes a second, smaller bend partway through the lens",
            "Because the ray refracts once entering the glass at the first surface and again leaving the glass at the second surface",
        ],
        "correct_index": 3,
        "why": "A lens has two surfaces, and refraction happens wherever the ray crosses from one material into another, so a ray bends once at each face.",
    },
    {
        "id": "ks4-lenses-s23",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Two identical thin converging lenses are held in contact, touching, along the same axis. Suggest the effect on the focal length of the pair compared with using one of the lenses alone.",
        "options": [
            "The pair has the same focal length as one lens alone, since two touching lenses cannot add anything to one another",
            "The pair has a shorter focal length, because the two lenses together bend the light more strongly than one alone does",
            "The pair has a longer focal length, because light must cross twice as much glass before either lens can properly bend it",
            "The pair no longer has a single focal length of its own, because two separate lenses cannot act together as though one",
        ],
        "correct_index": 1,
        "why": "Each lens adds its own converging effect, so a ray leaving the first lens is bent further by the second, bringing the rays to a focus sooner and giving a shorter combined focal length.",
    },
    {
        "id": "ks4-lenses-s24",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A converging lens is used to focus sunlight onto a piece of dark paper until it begins to smoke. Explain why this only happens when the paper is held at one particular distance from the lens.",
        "options": [
            "Because the Sun supplies enough energy to burn paper for a single brief instant, wherever the paper happens to be held",
            "Because that one distance is where the real image of the Sun forms, concentrating the arriving sunlight onto the smallest area",
            "Because the paper becomes flammable once it has already absorbed a fixed, fairly large total amount of sunlight",
            "Because the lens allows sunlight through once it has first been held completely still for several seconds",
        ],
        "correct_index": 1,
        "why": "The rays from the Sun are brought together at the image distance, so only there is the light concentrated enough to raise the paper's temperature quickly.",
    },
    {
        "id": "ks4-lenses-s25",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Compare the possible values of magnification for the real image formed by a converging lens with those for the image formed by a diverging lens.",
        "options": [
            "A converging lens gives a magnification above 1 in every case, while a diverging lens gives exactly 1 for any object",
            "Both lenses can give more or less any value of magnification, so there is no real difference between what each can produce",
            "A converging lens gives a magnification below 1 in every case, while a diverging lens gives one above 1 for any object",
            "A converging lens can give a magnification below, equal to, or above 1; a diverging lens always gives one below 1",
        ],
        "correct_index": 3,
        "why": "Where a converging lens places the object, relative to f and 2f, decides whether its real image is diminished, the same size, or magnified, but a diverging lens only ever diminishes.",
    },
    {
        "id": "ks4-lenses-s26",
        "subtopic_slug": "lenses",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A converging lens is used as a magnifying glass and forms a virtual image with a magnification of 3.5 from an object 8.0 cm away. Calculate how far the image appears to be from the lens.",
        "options": [
            "2.3 cm, from dividing the object distance given by the magnification given",
            "28 cm, from multiplying the object distance given by the magnification given",
            "11.5 cm, from adding the magnification given onto the object distance given",
            "0.44 cm, from dividing the magnification given by the object distance given",
        ],
        "correct_index": 1,
        "why": "Magnification = image distance / object distance, so the image distance is 3.5 x 8.0, which is 28 cm.",
    },
    # ── harder ──────────────────────────────────────────────────────────
    {
        "id": "ks4-lenses-h19",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A converging lens forms a real, inverted image of a candle flame on a screen. A small card is then held in front of the candle, blocking only the lower half of the flame, without touching the lens. Predict the effect on the image on the screen.",
        "options": [
            "The whole image disappears at once, because blocking any part of the object stops the lens from forming an image altogether",
            "The image becomes dimmer all over but keeps its full height, since light from every part of the flame passes through every part of the lens",
            "The lower half of the image disappears, since the image stays orientated the same way up as whichever part of the object is covered",
            "The upper half of the image disappears, since the image is inverted, so covering the bottom of the object removes the top of the image",
        ],
        "correct_index": 3,
        "why": "The image is inverted, so the part of the image corresponding to the bottom of the object is the part that is now missing, which is the top of the picture on the screen.",
    },
    {
        "id": "ks4-lenses-h20",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A student wants an extremely powerful magnifying glass and proposes a lens of an extremely short focal length. Evaluate this proposal, given that the object must stay within the focal length of the lens being used.",
        "options": [
            "A poor proposal: an extremely short focal length forces the object, and the eye, to be held impractically close to the lens",
            "A poor proposal: a short focal length gives a smaller magnification than a long one does, no matter the object's distance",
            "A sound proposal, since a shorter focal length has no measurable effect on how close the object needs to be held to the lens",
            "A sound proposal, because the shortness of the focal length affects the sharpness of the image, but not its usefulness",
        ],
        "correct_index": 0,
        "why": "The object has to sit inside the focal length for a magnifying glass to work, so an extremely short focal length leaves almost no room to hold the object or view it comfortably.",
    },
    {
        "id": "ks4-lenses-h21",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Compare where the object lies, relative to the focal length of the objective lens, for a telescope observing a distant star and for a microscope observing a nearby cell.",
        "options": [
            "For the telescope the object sits just beyond f; for the microscope it is instead effectively at infinity, very far beyond 2f",
            "In both instruments the object is placed well inside f, so that each objective on its own forms a virtual, magnified first image of it",
            "For the telescope the object is effectively at infinity, far beyond 2f; for the microscope it is placed just beyond f, between f and 2f",
            "In both instruments the object is placed exactly at 2f, so that each objective forms an image exactly the same size as the object",
        ],
        "correct_index": 2,
        "why": "A star is so far away that its light arrives essentially parallel, placing it far beyond 2f, while a microscope's specimen is deliberately set just outside the objective's focal length to give a large real image for the eyepiece to magnify further.",
    },
    {
        "id": "ks4-lenses-h22",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A student claims a diverging lens is useless next to a converging one, since it can only ever make things look smaller. Evaluate this claim, using the wide-angle lens fitted to a door peephole viewer as a counter-example.",
        "options": [
            "The claim is correct: a peephole viewer works because the diverging lens inside it is broken and lets almost no light through",
            "The claim is correct: the diverging lens in a peephole viewer forms a real image, and that is why it proves useful there",
            "The claim is incorrect: the diverging lens in a peephole viewer magnifies the corridor instead, which the original claim overlooks",
            "The claim is incorrect: the peephole viewer deliberately diminishes the corridor outside so that a wide view fits into a small image",
        ],
        "correct_index": 3,
        "why": "A diminished image is exactly what is wanted here, since it lets the whole width of the corridor be seen through a very small opening in the door.",
    },
    {
        "id": "ks4-lenses-h23",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Sunlight is focused by a converging lens onto a fixed spot on some dark paper, held at the lens's focal length from it. The same lens is then swapped for one of the same focal length but a much larger diameter. Predict the effect on the brightness of the spot.",
        "options": [
            "The spot becomes brighter, because the wider lens collects more sunlight and focuses all of it onto the same small area",
            "The spot disappears completely, because a wider lens can no longer bring the Sun's parallel rays to a single focal point",
            "The spot becomes dimmer instead, because a wider lens spreads the same total amount of light over a larger area at the focal point",
            "The spot stays exactly the same, because its brightness depends on the focal length and not on the width of the lens",
        ],
        "correct_index": 0,
        "why": "A wider lens intercepts more of the Sun's rays, and since the focal length is unchanged, they are all still brought to the same small spot, so more energy arrives there each second.",
    },
    {
        "id": "ks4-lenses-h24",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "State the two values that the magnification of the real image, formed by a converging lens, approaches as the object is moved from just beyond the focal length out to a very great distance.",
        "options": [
            "It approaches 1 when the object is just beyond f, and again approaches close to 1 once the object is moved very far away indeed",
            "It approaches zero instead when the object is just beyond f, and approaches a very large value once the object is very far away",
            "It stays close to 1 throughout, whether the object is placed just beyond f or is very far away indeed from the lens itself",
            "It approaches a very large value when the object is just beyond f, and approaches nearly zero once the object is very far away",
        ],
        "correct_index": 3,
        "why": "Just beyond f the real image forms a long way off and is strongly magnified, while for a very distant object the image shrinks towards a point close to f, so the magnification falls towards nearly zero.",
    },
    {
        "id": "ks4-lenses-h25",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A single converging lens is used first as a magnifying glass to read small print, and later, without changing the lens, to project a landscape onto a screen. Explain how the same lens can do both jobs.",
        "options": [
            "It cannot really do both jobs; the lens used for reading must be a different one from the lens used for the screen",
            "The lens itself changes its own shape between the two uses, and that change is what switches it from a magnifier into a projector",
            "Both jobs use exactly the same object position; it is the distance from the lens to the eye or the screen that differs",
            "Moving the object from inside the lens's focal length to beyond it switches the lens between forming a virtual and a real image",
        ],
        "correct_index": 3,
        "why": "A converging lens's behaviour is set entirely by where the object sits relative to its focal length, so repositioning the object alone is enough to change a magnifying glass into a projector.",
    },
    {
        "id": "ks4-lenses-h26",
        "subtopic_slug": "lenses",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why, for a converging lens forming a real image of a fixed object, only one particular screen position gives a sharp picture.",
        "options": [
            "Because the screen reflects light clearly once it has been held at exactly the same height above the bench as the lens itself",
            "Because the lens lets light through in short, irregular bursts, and the screen has to be timed very carefully to catch each of these",
            "Because the rays leaving the lens all cross at one specific point, and anywhere else they have not yet met or have already spread apart again",
            "Because the eye is able to focus on a screen once that screen has itself been placed at a distance equal to the focal length",
        ],
        "correct_index": 2,
        "why": "The image is where the refracted rays genuinely converge; a screen placed nearer or further catches those rays before they have met or after they have crossed and begun to diverge, which blurs the picture.",
    },
]
