"""rainford_sow.py — map Rainford High School's real KS4 scheme of work onto
the platform's subtopic keys, and emit it as override rows.

Run it:

    python3 rainford_sow.py

Writes one file, generated, never hand-edited:

    supabase/seeds/20260906234500_rainford_ks4_overrides.sql
        → public.scheme_of_work_overrides — the PER-SCHOOL table, scoped by
          school_id, for Rainford High School only.

── ⚠️ THIS IS ONE SCHOOL'S SEQUENCE. IT IS NEVER THE PLATFORM DEFAULT. ──

Mide's standing ruling of 2026-07-26, quoted in `ks3_data/school_schemes.py`:

    "Rainford's SOW is reference evidence, never a template — the platform
     must be school-agnostic."

The platform default is the AQA-spec order in `public.scheme_of_work_entries`,
generated by `ks4_seed_sow.py` from the site's own curriculum data. This file
writes to a DIFFERENT TABLE, and touches nothing that table owns. It does not
import, read, modify or re-derive `ks4_seed_sow`'s output; it borrows only
`ks4_data.classify()` to check that every slug it names is a real KS4 subtopic
of the right subject.

── THE SOURCE ──────────────────────────────────────────────────────────

    Rainford SOW/NEW Ks4 SOW.xlsx, sheet "KS4 SOW " (trailing space).

Untracked, and outside this repo's tree. It is a real teacher's working
spreadsheet, not an export, and it is shaped like one:

  · Column A is the year group, written once per year and blank thereafter —
    forward-filled.
  · Three side-by-side four-column subject blocks: lesson number, unit banner,
    Higher, Foundation. The unit banner is also written once and blank
    thereafter — forward-filled per subject block.
  · The lesson numbers run CONTINUOUSLY from Year 9 to Year 11, 1..120. They
    are not weeks and they do not restart, so they are discarded and the rows
    are renumbered — see "academic_week" below.
  · Rainford BEGINS KS4 IN YEAR 9. All three years are key_stage='KS4'.

⚠️ One cell in the sheet holds a single SPACE and nothing else — row 123,
the Chemistry Foundation column, on the row whose Biology entry is
"Inheritance varation & evolution  test". There is no lesson number, no unit
and no Higher text beside it. It is a stray keystroke, not a lesson, and
`_cell()` normalises a whitespace-only cell to None so it never becomes a row.
That is why Year 11 Chemistry comes out at 44 lessons and not the 45 a naive
count reports.

── HOW A LESSON BECOMES A ROW ──────────────────────────────────────────

Rainford's sheet is a list of TAUGHT LESSONS. Ours is a list of scheme rows.
One taught lesson becomes one row, in the tier whose column it came from:

    Higher column entry      → one row with tier='higher'
    Foundation column entry  → one row with tier='foundation'

Usually the two columns hold the same text and a lesson yields two rows, one
per tier. Where they differ, the two rows carry different text and may map to
different subtopics. Where Foundation is blank and Higher is not — the
"[HT ONLY]" lessons — the lesson yields a Higher row and no Foundation row,
which is exactly what it means.

**A test, a quiz and a review lesson all become rows too.** They are real
weeks of a real timetable and dropping them would shift every lesson after
them by one, silently rewriting the sequence. They get `subtopic = NULL` and
a reason in `notes`.

── academic_week — RENUMBERED FROM 1, PER (year, subject, tier) ─────────

`academic_week` in this table is a teaching ORDER inside one block, which is
what the constraint comment says it is. Rainford's own 1..120 running numbers
are neither weeks nor per-block, so they are dropped and each block is
renumbered densely from 1.

The block is (year_group, subject, TIER) and not just (year_group, subject).
Tier is in the table's unique key, so the two tiers do not collide — but more
importantly a Foundation class does not teach the "[HT ONLY]" lessons, so its
tenth taught lesson is genuinely a different lesson from Higher's tenth. Dense
per-tier renumbering says that; shared numbering with holes in the Foundation
side would claim Foundation teaches a 45th lesson it never sees. Rainford's
own running lesson number is preserved verbatim in `notes`, so nothing about
the original numbering is lost.

Longest block: Year 11 Biology Higher, 55. Migration `20260906230500` widened
this table's KS4 ceiling to 60 for exactly this, and `MAX_ACADEMIC_WEEK`
asserts against it rather than trusting it.

── tier and pathway ────────────────────────────────────────────────────

**tier is read off the column. pathway is NULL on every row, deliberately.**

This is the one modelling decision in the file and it deserves its reasoning
written down, because the honest answer is that Rainford's sheet does not
distinguish Combined from Triple as a sequence at all.

What the sheet actually does is mark individual lessons. A Triple-only lesson
carries a "(BIO)", "(CHEM)" or "(PHYS)" prefix in its text — 74 of the 343
lesson rows do — and the rest are taught to everybody. There is ONE sequence
per tier, and a Triple class takes it whole while a Combined class skips the
marked lessons. The prefix reading was checked against the platform's own
`ks4_data.classify()` and it holds: `check_triple_prefix()` runs on every
build and prints the agreement, and every prefixed entry that maps to a
subtopic maps to one the site independently flags `triple_only`.

Three representations were considered:

  (a) pathway NULL on every row. One sequence, both pathways, exactly as
      Rainford wrote it.
  (b) Emit each block twice, once 'combined' and once 'triple', with the
      marked lessons deleted from the combined copy.
  (c) pathway='triple' on the marked rows and 'combined' on the rest.

(b) was rejected as INVENTION. Deleting 74 lessons renumbers every week after
each deletion, so the combined sequence it produced would be a sequence
Rainford has never written down and no Rainford teacher would recognise. The
brief for this work is explicit that a wrong mapping is worse than a gap, and
a fabricated week order is a wrong mapping of the whole document.

(c) was rejected as a lie about the same thing in smaller print: it would say
a Combined class does not teach "Group 1" simply because the row above it
happened to be Triple-only, and it would leave two interleaved sequences whose
week numbers each count the other's lessons.

(a) is what is emitted, and it loses nothing. The Triple-only marking survives
in two independent places: verbatim, in the entry text stored in `notes`
(the prefix is kept byte-for-byte), and structurally, in `ks4_data.classify()`
for every row that carries a subtopic slug. A reader can recover which lessons
are Triple-only from either.

── WHAT THE COLUMNS CARRY ──────────────────────────────────────────────

    school_id      subselect on schools.name — never a hardcoded uuid, since
                   test and prod ids differ. (Rainford also has slug
                   'rainford-high'; the name is used because that is what this
                   work was specified against and because `schools.slug` is
                   NULL for other rows in the same table.)
    key_stage      'KS4' for all three years, Year 9 included.
    year_group     9, 10 or 11.
    tier           'higher' or 'foundation', from the column.
    pathway        NULL — see above.
    subject_id     subselect on subjects.name.
    academic_week  1..n within (year, subject, tier).
    topic          Rainford's unit banner, verbatim ("Unit 1 Cell biology").
                   NOT NULL in this table, and every row has one.
    subtopic       the platform subtopic slug, or NULL where the lesson has no
                   platform equivalent. NULL rows are named at the foot of the
                   SQL, one line each.
    notes          "L<Rainford's running lesson number> · <verbatim entry
                   text>", plus the reason when subtopic is NULL. The verbatim
                   text is what makes the mapping auditable after the fact.

── THE MAPPING DICT IS THE REVIEWABLE ARTEFACT ─────────────────────────

`MAP` below is the whole of the judgement in this file, laid out one line per
Rainford entry so it can be read and checked. Two rules produced it:

  R1 — a verbatim or near-verbatim platform title wins. "Metabolism" →
       `metabolism`; "(CHEM) Atom Economy" → `atom-economy`.
  R2 — where one Rainford lesson covers two platform pages, it maps to the
       FIRST-NAMED of them, and the second is recorded in
       `docs/ks4/rainford-sow-mapping.md` as a compound entry. "Land use &
       deforestation" → `land-use`; `deforestation` is noted, not mapped.
       Mapping such a lesson to one page is partial. Mapping it to neither
       would be worse for the teacher, who would see nothing at all.

Two entries deviate from R2 on purpose and are called out here rather than
buried:

  · 'Speed, distance time graphs' → `distance-time-graphs`, not the
    first-named `distance-speed-velocity`. The very next Rainford lesson is
    'Velocity', which is `distance-speed-velocity`; following R2 would point
    both lessons at one page and leave the graphs page unreferenced.
  · '(PHYS) Circular Motion' sits in Rainford's Unit 8 Space physics, where
    the unit context argues for `gravity-stable-orbits`. R1 wins on the
    title, and `motion-in-a-circle`'s own summary — "why circular motion
    involves constant speed but changing velocity, and the centripetal
    force" — is what that lesson teaches. Flagged for Mide.

Anything with no honest platform equivalent is NOT guessed. It carries an
`absent(...)` or `ambiguous(...)` marker giving the reason, becomes a row with
`subtopic = NULL`, and is listed by name at the foot of the SQL and in the
report. `ASSESSMENT` is the third such marker, for the tests, quizzes and
review lessons that have no content page by definition.

── WHAT FAILS THE RUN ──────────────────────────────────────────────────

Nothing here is best-effort. `main()` refuses to write a file if:

  · a Rainford entry appears in the workbook that `MAP` has no key for — so a
    new lesson typed into the spreadsheet stops the run rather than vanishing;
  · a key in `MAP` matches nothing in the workbook — a stale mapping that has
    quietly stopped meaning anything;
  · any slug named in `MAP` is not a KS4 subtopic, or belongs to a different
    subject than the block it is mapped from;
  · any block's length exceeds MAX_ACADEMIC_WEEK.
"""

import collections
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import ks4_data

WORKBOOK = ("/Users/midebadmus/Documents/GitHub/mrbadmus-site/"
            "Rainford SOW/NEW Ks4 SOW.xlsx")
SHEET = "KS4 SOW "          # ⚠️ the trailing space is real

SEED_DIR = os.path.join("supabase", "seeds")
SEED_FILE = "20260906234500_rainford_ks4_overrides.sql"

SCHOOL_NAME = "Rainford High School"

# The table CHECK, since migration 20260906230500:
#   academic_week between 1 and (case when key_stage='KS3' then 39 else 60 end)
# Raising this constant alone changes nothing — the CHECK is in the database.
MAX_ACADEMIC_WEEK = 60

YEARS = (9, 10, 11)
SUBJECTS = ("biology", "chemistry", "physics")
TIERS = ("higher", "foundation")

SUBJECT_TITLES = {
    "biology": "Biology",
    "chemistry": "Chemistry",
    "physics": "Physics",
}

# subject → (lesson-number col, unit col, Higher col, Foundation col), 1-based.
COLUMNS = {
    "biology": (2, 3, 4, 5),
    "chemistry": (6, 7, 8, 9),
    "physics": (10, 11, 12, 13),
}

# The measured shape of the sheet, asserted after parsing. If the spreadsheet
# is edited these numbers move and the run says so rather than quietly
# emitting a different scheme.
#
# ⚠️ ('Year 11', 'chemistry') is 44 here and 45 in the brief this file was
# written from. The difference is the stray single-space cell described in the
# module docstring, and 44 is the number of lessons Rainford actually teaches.
EXPECTED_ROWS = {
    (9, "biology"): 19, (9, "chemistry"): 20, (9, "physics"): 17,
    (10, "biology"): 46, (10, "chemistry"): 48, (10, "physics"): 47,
    (11, "biology"): 55, (11, "chemistry"): 44, (11, "physics"): 46,
}


# ── the three ways a lesson can have no platform page ────────────────────

class Unmapped(object):
    """A deliberate non-mapping, carrying the reason it is one.

    This is the "None" the mapping dict could have used, with the why kept
    next to the what. A wrong slug points a teacher at the wrong lesson and
    says nothing; an Unmapped points at nothing and says why.
    """

    __slots__ = ("kind", "why")

    def __init__(self, kind, why):
        self.kind = kind
        self.why = why

    def __repr__(self):
        return "Unmapped(%r, %r)" % (self.kind, self.why)


ASSESSMENT = Unmapped(
    "assessment",
    "a test, quiz or review lesson — it teaches no new spec content, so no "
    "subtopic page corresponds to it")


def absent(why):
    """Real AQA content that the platform has no subtopic page for."""
    return Unmapped("absent", why)


def ambiguous(why):
    """Content that spans two or more subtopic pages with no clear primary."""
    return Unmapped("ambiguous", why)


# ── the disambiguator ────────────────────────────────────────────────────
#
# One Rainford entry text means two different things depending on which unit
# it sits in. Consulted BEFORE MAP; everything else falls through to MAP.
UNIT_MAP = {
    # Rainford teaches Power twice — P = E/t in Unit 1 Energy, and P = VI /
    # P = I²R in Unit 2 Electricity. The platform has a page for each, and
    # they are different pages with the same title.
    ("physics", "Unit 2 Electricity", "Power"): "power-electricity",
}



# ═══════════════════════════════════════════════════════════════════════════
# MAP — Rainford's entry text → platform subtopic slug
# ═══════════════════════════════════════════════════════════════════════════
#
# ⚠️ THIS DICT IS THE REVIEWABLE ARTEFACT. Read it left to right: the string on
# the left is what a Rainford teacher wrote in the spreadsheet, byte for byte,
# including its typos and its double spaces. The value on the right is the
# platform subtopic page that lesson teaches, or a marker saying why there
# isn't one.
#
# Keyed by subject, because "Quiz & application" and "Power" occur in more than
# one science and a flat dict would let one subject's answer leak into another.
# The Higher and Foundation columns share this dict: where they hold the same
# text they map to the same slug, and where they differ each text is its own
# key.
#
# Order is the order the lessons are taught, Year 9 first.

MAP = {
    "biology": {
        'Eukarytotes (Animal & plant cells)':                                                 "animal-plant-cells",
        'Cell differentiation & specialisation':                                              "cell-specialisation",
        'Stem cells':                                                                         "stem-cells",
        'Uses of stem cells (w/ therapuetic cloning)':                                        "stem-cells",
        'Mitosis & the cell cycle':                                                           "chromosomes-mitosis",
        'Prokaryotes':                                                                        "eukaryotes-prokaryotes",
        'Use of a light microscopes RP':                                                      "microscopy",
        'Types of microscope':                                                                "microscopy",
        'Magnification':                                                                      "microscopy",
        'Quiz & application':                                                                 ASSESSMENT,
        'Diffusion & factors effecting diffusion':                                            "transport-in-cells",
        'Osmosis':                                                                            "transport-in-cells",
        'Osmosis RP':                                                                         "transport-in-cells",
        'Osmosis RP 2':                                                                       "transport-in-cells",
        'Active transport':                                                                   "transport-in-cells",
        'Surface area : volume ratio':                                                        "transport-in-cells",
        'Exchange surfaces':                                                                  "transport-in-cells",
        'Cell biology test':                                                                  ASSESSMENT,
        'Test review':                                                                        ASSESSMENT,
        'Levels of Organisation - Cells, Tissues & Organs (w/digestive system)':              "principles-of-organisation",
        'Villi & Bile':                                                                       "digestive-system",
        'Food tests':                                                                         "digestive-system",
        'Food tests RP':                                                                      "digestive-system",
        'Food tests Part 2':                                                                  "digestive-system",
        'Food tests RP2':                                                                     "digestive-system",
        'Enzymes lock & key & digestive enzymes':                                             "enzymes",
        'Factors affecting enzymes':                                                          "enzymes",
        'Amylase RP':                                                                         "enzymes",
        'Amylase RP 2':                                                                       "enzymes",
        'Heart & circulatory system':                                                         "heart-blood-vessels",
        'Blood & Vessels':                                                                    "blood",
        'CHD & treatments':                                                                   "coronary-heart-disease",
        'Breathing & gas exchange': absent(
            'AQA 4.2.2.3 "the lungs" — breathing and alveolar gas exchange. '
            'No platform subtopic covers it; the nearest, '
            'transport-in-cells, is cell-level exchange, not the '
            'ventilation system.'),
        'Structure of a leaf & gas exchange':                                                 "plant-tissues",
        'Transport in plants': ambiguous(
            'names neither platform title. "Transport in plants" is '
            'transpiration AND translocation in equal measure, and picking '
            'one would silently hide the other.'),
        'Organisation test':                                                                  ASSESSMENT,
        'Non-commincable disease, health issues & risk factors':                              "health-disease",
        'Cancer and Lifestyle':                                                               "cancer",
        'Cancer and lifestyle':                                                               "cancer",
        'Viral Diseases - Measlea, HIV, TMV':                                                 "viral-diseases",
        'Bacterial Diseases':                                                                 "bacterial-diseases",
        'Protist Diseases & fungal diseases':                                                 "fungal-protist-diseases",
        'Human defence systems':                                                              "communicable-diseases-defence",
        'Vaccination':                                                                        "vaccination",
        '(BIO) Monoclonal antibodies':                                                        "monoclonal-antibodies",
        'Antibiotics & painkillers':                                                          "antibiotics-painkillers",
        '(BIO) Culturing microorganisms RP':                                                  "culturing-microorganisms",
        '(BIO) Culturing microorganisms RP2':                                                 "culturing-microorganisms",
        'Discovery of drugs and Trials':                                                      "drug-discovery-development",
        '(BIO) Plant disease':                                                                "plant-disease-detection-defence",
        'Infection & response test':                                                          ASSESSMENT,
        'Photosynthesis & uses of glucose':                                                   "photosynthesis",
        'Testing a leaf for starch':                                                          "photosynthesis",
        'Limiting factors of photosynthesis':                                                 "rate-of-photosynthesis",
        'Photosynthesis RP':                                                                  "rate-of-photosynthesis",
        'Photosynthesis RP 2':                                                                "rate-of-photosynthesis",
        'Aerobic respiration & uses of energy from respiration':                              "aerobic-respiration",
        'Anaerobic respiration & fermentation':                                               "anaerobic-respiration",
        'Response to exercise':                                                               "response-to-exercise",
        'Metabolism':                                                                         "metabolism",
        'Bioenergetics test':                                                                 ASSESSMENT,
        'Ecosystems, biotic & abiotic factors':                                               "ecosystems",
        'Types of sampling':                                                                  "sampling-techniques",
        'Sampling RP':                                                                        "sampling-techniques",
        'Sampling RP 2':                                                                      "sampling-techniques",
        'Food chains':                                                                        "food-chains-webs",
        '(BIO) Trophic levels & pyramdid of biomass':                                         "trophic-levels",
        'Adaptations (Animal, plant & extremophiles)':                                        "adaptations",
        'Competition  & predator prey relationships':                                         "population-competition",
        'Carbon cycle':                                                                       "carbon-cycle",
        '(BIO)  Decomposition':                                                               "decomposition",
        '(BIO) Anaerobic decay & biogas':                                                     "decomposition",
        '(BIO) Decay RP':                                                                     "decomposition",
        '(BIO) Decay RP 2':                                                                   "decomposition",
        'Water cycle':                                                                        "water-cycle",
        'Biodiversity & maintaining biodiversity':                                            "biodiversity",
        'Land use & deforestation':                                                           "land-use",
        'Pollution & waste mangement':                                                        "waste-management",
        'Global warming  (w/ BIO- Impact of environmental change)':                           "global-warming",
        '(BIO) Factors effecting food security & intensive farming':                          "factors-affecting-food-security",
        '(BIO) Sustainable fisheries':                                                        "sustainable-fisheries",
        '(BIO) Mycroprotein':                                                                 "role-of-biotechnology",
        '(BIO) Mycoprotein':                                                                  "role-of-biotechnology",
        'Ecology test':                                                                       ASSESSMENT,
        'Homeostasis':                                                                        "homeostasis",
        'Reflex action':                                                                      "reflex-actions",
        'Reaction time RP':                                                                   "reaction-time",
        'Reaction time RP 2':                                                                 "reaction-time",
        '(BIO) The Brain':                                                                    "the-brain",
        '(BIO) The Eye':                                                                      "the-eye",
        '(BIO) Problems with the eye':                                                        "defects-of-the-eye",
        '(BIO) Thermoregulation':                                                             "thermoregulation",
        'Blood glucose & diabetes':                                                           "blood-glucose-diabetes",
        '(BIO) Removing waste product w/deamination': absent(
            'AQA 4.5.3.4 "maintaining water and nitrogen balance" — '
            'deamination and urea. Only metabolism mentions deamination in '
            'passing; there is no excretion page.'),
        '(BIO) Kidney & ADH': absent(
            'AQA 4.5.3.4 — the kidney, nephron and ADH. No platform '
            'subtopic; endocrine-system names ADH only as a hormone.'),
        '(BIO) Kidney failure': absent(
            'AQA 4.5.3.4 — kidney failure, dialysis and transplant. No '
            'platform subtopic.'),
        'Hormones in the menstrual cycle':                                                    "human-reproduction-hormones",
        'Contraception & IVF':                                                                "contraception-fertility",
        'Contraception':                                                                      "contraception-fertility",
        'Negative feedback and adrenaline , thyroxine':                                       "endocrine-system",
        'Plant Hormones': absent(
            'AQA 4.5.4 "plant hormones" — auxin, phototropism, '
            'gravitropism. No platform subtopic mentions any of the three.'),
        'Growth of seedling RP': absent(
            'AQA 4.5.4 RP "the effect of light or gravity on seedling '
            'growth". No platform subtopic; it belongs to the missing '
            'plant-hormones page.'),
        'Growth of seedling RP2': absent(
            'AQA 4.5.4 RP, second period. Same gap as the lesson before it.'),
        'Homeostasis and response  test':                                                     ASSESSMENT,
        'Asexual and sexual reproduction':                                                    "sexual-asexual-reproduction",
        'Meisosis':                                                                           "meiosis",
        'DNA, Genes & Human Genome Project':                                                  "dna-genome",
        '(BIO) Protein synthesis':                                                            "dna-structure",
        'Genetic inheritance':                                                                "genetic-inheritance",
        'Inherited diseases and sex determination':                                           "inherited-disorders",
        '(BIO) Understanding genetics':                                                       "understanding-genetics",
        'Genetic engineering  & selective breeding':                                          "genetic-engineering",
        '(BIO) Cloning':                                                                      "cloning",
        'Variation & Evolution':                                                              "variation",
        '(BIO) Theories of evolution & speciation':                                           "theory-of-evolution",
        'Fossils and extinction':                                                             "fossils-extinction",
        'Classification':                                                                     "classification-living-organisms",
        'Inheritance varation & evolution  test':                                             ASSESSMENT,
    },

    "chemistry": {
        'Structure of the atom':                                                              "subatomic-particles",
        'Electronic Structure':                                                               "electronic-structure",
        'Isotopes':                                                                           "relative-atomic-mass",
        'Development of the Model of the Atom':                                               "model-of-the-atom",
        'Atoms, Elements & Compounds':                                                        "atoms-elements-compounds",
        'Relative Formula Mass (Mr)':                                                         "relative-formula-mass",
        'Conservation of Mass/Balancing Equations':                                           "conservation-of-mass",
        'Mixtures: Filtration & Evaporation':                                                 "mixtures",
        'Mixtures: Simple Distillation':                                                      "mixtures",
        'Quiz & application':                                                                 ASSESSMENT,
        'The periodic table':                                                                 "periodic-table",
        'Development of the periodic table':                                                  "development-periodic-table",
        'Metals and non-metals':                                                              "metals-non-metals",
        'Metallic Bonding/Alloys':                                                            "metallic-bonding",
        'Group 0 & (CHEM) Tranistion metals':                                                 "group-0",
        'Group 1':                                                                            "group-1",
        'Group 7':                                                                            "group-7",
        'Displacement of Halogens':                                                           "group-7",
        'Atomic Structure & Periodic Table Test':                                             ASSESSMENT,
        'Test Review':                                                                        ASSESSMENT,
        'Pure Substances, Formulations & Testing For Gases':                                  "pure-substances",
        'Chromatography RP':                                                                  "chromatography",
        'Chromatography RP 2':                                                                "chromatography",
        '(CHEM) Tests for positive ions (Flame Tests) & Flame Emission Spectroscopy':         "flame-tests",
        '(CHEM) Tests for positive ions (reaction with metal hydroxide)':                     "metal-hydroxides",
        '(CHEM) Tests for negative ions':                                                     "carbonates-halides-sulfates",
        '(CHEM) Tests for ions RP': ambiguous(
            'the AQA required practical "identification of ions by chemical '
            'and spectroscopic means" spans flame-tests, metal-hydroxides '
            'and carbonates-halides-sulfates equally. No one of the three '
            'is the lesson.'),
        'History & Evolution of the Atmosphere':                                              "early-atmosphere",
        'Greenhouse Gases / Climate change':                                                  "greenhouse-gases",
        'Atmospheric Pollutants & Carbon Footprint':                                          "atmospheric-pollutants",
        '(CHEM) Chemical Analysis & Atmosphere Test':                                         ASSESSMENT,
        '(CHEM) Chemical Analysis & Atmosphere Test Review':                                  ASSESSMENT,
        "Using the Earth's Resources & Recycling":                                            "earths-resources",
        'Potable Water RP 1':                                                                 "potable-water",
        'Potable Water RP 2':                                                                 "potable-water",
        'Waste Water Treatment/Evaluate obtaining potable water':                             "potable-water",
        'Alternative methods of extracting metals (HT only)':                                 "alternative-metal-extraction",
        '(CHEM) Corrosion & Alloys':                                                          "corrosion-prevention",
        '(CHEM) Ceramics, polymers and composites':                                           "ceramics-polymers-composites",
        'Life Cycle Assessment':                                                              "life-cycle-assessment",
        '(CHEM) NPK fertilisers':                                                             "npk-fertilisers",
        'Chemical Analysis, Chemistry of the Atmosphere & Using Resources Test':              ASSESSMENT,
        'Chemical Analysis, Chemistry of the Atmosphere & Using Resources Test Review':       ASSESSMENT,
        'Rates of Reaction (Spec point)/Calculating Rates Graphically':                       "calculating-rates",
        'Factors Affecting Rates':                                                            "factors-affecting-rate",
        'Rate of Reaction RP (Measuring the volume of a gas produced)':                       "factors-affecting-rate",
        'Rate of Reaction RP (Measuring a change in colour or turbidity)':                    "factors-affecting-rate",
        'Rates RP Application':                                                               "factors-affecting-rate",
        'Catalysts/Reversible Reactions':                                                     "catalysts",
        'The effect of changing conditions at equilibrium  [HT ONLY]':                        "effect-of-conditions-equilibrium",
        '(CHEM) Haber process':                                                               "haber-process",
        'Rates & Equilibrium Test':                                                           ASSESSMENT,
        'Rates & Equilibrium Test Review':                                                    ASSESSMENT,
        'Covalent Bonding/Dot & Cross Diagrams':                                              "covalent-bonding",
        'Properties of Simple Molecules':                                                     "properties-small-molecules",
        'Crude Oil, Hydrocarbons & Alkanes':                                                  "crude-oil-hydrocarbons",
        'Properties of Hydrocarbons & Fractional Distillation':                               "properties-of-hydrocarbons",
        'Combustion':                                                                         "properties-of-hydrocarbons",
        'Cracking':                                                                           "cracking-alkenes",
        '(CHEM) Reactions of Alkenes':                                                        "reactions-of-alkenes",
        '(CHEM) Alcohols':                                                                    "alcohols",
        '(CHEM) Carboxylic Acids & Esters':                                                   "carboxylic-acids",
        '(CHEM) Addition Polymerisation':                                                     "addition-polymerisation",
        '(CHEM) Condensation Polymerisation':                                                 "condensation-polymerisation",
        '(CHEM) Amino Acids, DNA & Natural Polymers':                                         "amino-acids",
        '(CHEM) Amino Acids':                                                                 "amino-acids",
        'Organic & Bonding Test':                                                             ASSESSMENT,
        'Organic & Bonding Test Review':                                                      ASSESSMENT,
        'Balancing Equations/Relative Formula Mass Recap':                                    "conservation-of-mass",
        'Moles [HT ONLY]':                                                                    "moles",
        'Amount of substance in equations  [HT ONLY]':                                        "amounts-in-equations",
        'Masses to balance equations [HT ONLY]':                                              "amounts-in-equations",
        'Limiting Reactants [HT ONLY]':                                                       "using-moles-calculations",
        '(CHEM) Percentage Yield':                                                            "percentage-yield",
        '(CHEM) Atom Economy':                                                                "atom-economy",
        '(CHEM) Quiz & Application':                                                          ASSESSMENT,
        'Concentration of Solutions':                                                         "concentration-of-solutions",
        '(CHEM) Titrations RP 1':                                                             "titrations",
        '(CHEM) Titration RP 2':                                                              "titrations",
        '(CHEM) Gas Calculations': absent(
            'AQA 4.3.4.3 "use of amount of substance in relation to volumes '
            'of gases" — the molar gas volume, 24 dm3. No platform subtopic '
            "mentions it; the quantitative topic's ten pages stop at "
            'concentration.'),
        'Quantitative Chemistry Test':                                                        ASSESSMENT,
        'Quantitative Chemistry Test Review':                                                 ASSESSMENT,
        'Ionic Bonding':                                                                      "ionic-bonding",
        'Properties of Ionic Compounds':                                                      "properties-ionic-compounds",
        'Reactions of metals with oxygen and water':                                          "reactivity-series",
        'The reactivity series':                                                              "reactivity-series",
        'Extraction of metals/reduction with carbon':                                         "extraction-of-metals",
        'Oxidation and reduction (in terms of electrons) [HT ONLY]':                          "oxidation-reduction",
        'Reactions of acids and metals/Naming salts/Working out chemical formula':            "reactions-of-acids",
        'Reactions of acids and bases/Ionic Equations':                                       "reactions-of-acids",
        'Reactions of Acids and metal carbonates/Making Salts RP Theory':                     "reactions-of-acids",
        'Making Salts RP':                                                                    "salts-neutralisation",
        'pH Scale & Neutralisation':                                                          "ph-scale",
        'Strong & Weak Acids [HT ONLY]':                                                      "strong-weak-acids",
        'Electrolysis of Molten Ionic Compounds':                                             "electrolysis-molten",
        'Electrolysis of Molten Ionic Compounds (Half Equations) [HT ONLY]':                  "half-equations",
        'Electrolysis of Aluminium Oxide':                                                    "electrolysis-extraction",
        'Electrolysis of Aqueous Solutions':                                                  "electrolysis-aqueous",
        'Electrolysis of Aqueous Solutions RP':                                               "electrolysis-aqueous",
        'Chemical Changes Test':                                                              ASSESSMENT,
        'Chemical Changes Test Review':                                                       ASSESSMENT,
        'Exothermic & Endothermic Reactions':                                                 "exothermic-endothermic",
        'Exothermic & Endothermic Reactions RP':                                              "exothermic-endothermic",
        'Reaction Profiles & Catalysts':                                                      "reaction-profiles",
        'Bond Energy Calculations [HT ONLY]':                                                 "bond-energy-calculations",
        '(CHEM) Chemical cells and batteries':                                                "cells-and-batteries",
        '(CHEM) Fuel cells':                                                                  "fuel-cells",
        'Giant Covalent Structures':                                                          "giant-covalent-structures",
        'Graphene & Fullerenes':                                                              "giant-covalent-structures",
        '(CHEM) Nanoparticles':                                                               "nanoparticles",
        'Energy Changes & Giant Covalent Test':                                               ASSESSMENT,
        'Energy Changes & Giant Covalent Test Review':                                        ASSESSMENT,
    },

    "physics": {
        'Energy stores & systems':                                                            "energy-stores-systems",
        'Conservation of energy':                                                             "energy-transfers-in-a-system",
        'Energy transfers in a system':                                                       "energy-transfers-in-a-system",
        'Work done':                                                                          "work-done-energy-transfer",
        'Kinetic energy':                                                                     "changes-in-energy",
        'Elastic potential energy':                                                           "changes-in-energy",
        'Gravitational potential energy':                                                     "changes-in-energy",
        'Quiz & application':                                                                 ASSESSMENT,
        'Power':                                                                              "power",
        'Energy efficiency':                                                                  "efficiency",
        'Thermal conductivity':                                                               "thermal-conductivity",
        'Thermal insulators investigation':                                                   "thermal-conductivity",
        'Non-renewable energy: Fossil Fuels':                                                 "energy-resources",
        'Non-renewable energy: Nuclear':                                                      "energy-resources",
        'Renewable energy':                                                                   "energy-resources",
        'Energy Test':                                                                        ASSESSMENT,
        'Test Review':                                                                        ASSESSMENT,
        'Density':                                                                            "density-of-materials",
        'Density RP':                                                                         "density-of-materials",
        'Changing states of matter':                                                          "changes-of-state",
        'Changing states of matter - Investigation':                                          "changes-of-state",
        'Internal energy':                                                                    "internal-energy",
        'Specific heat capacity':                                                             "temperature-changes-shc",
        'Specific heat capacity RP':                                                          "temperature-changes-shc",
        'Specific latent heat':                                                               "specific-latent-heat",
        'Particle model and pressure':                                                        "particle-motion-pressure",
        '(PHYS) Pressure and volume':                                                         "particle-motion-pressure",
        'Particle model of matter Test':                                                      ASSESSMENT,
        'Atoms, isotopes and excited electrons':                                              "structure-of-atom",
        'History of the atom':                                                                "development-atomic-model",
        'Nuclear radiation':                                                                  "radioactive-decay",
        'Alpha, beta and gamma radiation':                                                    "radioactive-decay",
        'Radioactive decay equations':                                                        "nuclear-equations",
        'Half-life':                                                                          "half-lives",
        'Half-life 2':                                                                        "half-lives",
        'Dangers and uses of nuclear radiation':                                              "radioactive-contamination",
        '(PHYS) Nuclear fission':                                                             "nuclear-fission",
        '(PHYS) Nuclear fusion':                                                              "nuclear-fusion",
        '(PHYS) Nuclear radiation in medicine':                                               "uses-of-nuclear-radiation",
        'Atomic structure Test':                                                              ASSESSMENT,
        'Circuit symbols and building circuits':                                              "circuit-symbols",
        'Current and Charge':                                                                 "electrical-charge-current",
        'Series and parallel investigation':                                                  "series-parallel-circuits",
        'Series Rules':                                                                       "series-parallel-circuits",
        'Parallel Rules':                                                                     "series-parallel-circuits",
        'Resistance and Ohms Law':                                                            "current-resistance-pd",
        'Resistance in series and parallel RP':                                               "series-parallel-circuits",
        'Resistance in a wire RP':                                                            "current-resistance-pd",
        'IV Characteristics - inc components LDR, thermistors etc':                           "resistors",
        'IV Graphs RP Collect Data':                                                          "resistors",
        'IV characteristics Review and draw graphs':                                          "resistors",
        "Harder Ohm's Law Application":                                                       "current-resistance-pd",
        "Extra Ohm's law":                                                                    "current-resistance-pd",
        'AC and DC':                                                                          "direct-alternating-pd",
        'Cables and plugs':                                                                   "mains-electricity",
        'Energy Transfer':                                                                    "energy-transfers-appliances",
        'National Grid':                                                                      "national-grid",
        '(PHYS) Static Charges':                                                              "static-charge",
        '(PHYS) Electric Fields':                                                             "electric-fields",
        'Electrcity Test':                                                                    ASSESSMENT,
        'Waves prop':                                                                         "properties-of-waves",
        'Wave RP':                                                                            "properties-of-waves",
        '(PHYS) Reflection RP':                                                               "properties-em-waves-1",
        'Refraction RP':                                                                      "properties-em-waves-1",
        '(PHYS)Lenses':                                                                       "lenses",
        '(PHYS)Sounds and sonar':                                                             "sound-waves-hearing",
        '(PHYS)Ultrasound':                                                                   "waves-detection-exploration",
        '(PHYS) Seismic SLOP':                                                                "waves-detection-exploration",
        'EM spec and uses':                                                                   "types-of-em-waves",
        'Infrared RP':                                                                        "infrared-black-bodies",
        '(PHYS) Black Body':                                                                  "infrared-black-bodies",
        'Communication and high energy':                                                      "uses-em-waves",
        'Waves Test':                                                                         ASSESSMENT,
        '(PHYS) Origin of the universe and red shift':                                        "red-shift-big-bang",
        '(PHYS) Life Cycle of a Star':                                                        "stellar-evolution",
        '(PHYS) Circular Motion':                                                             "motion-in-a-circle",
        'Mag fields':                                                                         "magnetic-fields",
        'Electromagnets and (PHYS) Uses':                                                     "electromagnetism",
        'Electromagnets':                                                                     "electromagnetism",
        'Motor and FLH rule (HT only)':                                                       "flemings-left-hand-rule",
        'F = BIL, SLOP, DC motor (HT only)':                                                  "electric-motors",
        '(PHYS) Generator':                                                                   "induced-potential",
        '(PHYS) Alternators and dynamos':                                                     "uses-generator-effect",
        '(PHYS) Loudspeakers, microphones and transformers':                                  "loudspeakers-headphones",
        'Mass and Weight':                                                                    "gravity",
        "Hooke's law and RP":                                                                 "forces-elasticity",
        "Hooke's Law graph and Qs":                                                           "forces-elasticity",
        'vectors, scalars, forces N1L':                                                       "scalar-vector-quantities",
        'N3L':                                                                                "newtons-laws",
        'Resolving forces':                                                                   "resolving-forces",
        'Resultant forces':                                                                   "resultant-forces",
        'Parallelogram of forces (HT Only)':                                                  "resolving-forces",
        '(PHYS) Moments':                                                                     "moments-levers-gears",
        'Speed, distance time graphs':                                                        "distance-time-graphs",
        'Spped, distance time graphs':                                                        "distance-time-graphs",
        'Velocity':                                                                           "distance-speed-velocity",
        'Terminal velocity':                                                                  "acceleration",
        'Acceleration':                                                                       "acceleration",
        'F = ma RP':                                                                          "newtons-laws",
        '(PHYS) Braking forces':                                                              "stopping-distance-braking",
        'Momentum':                                                                           "momentum",
        '(PHYS) Changing momentum':                                                           "momentum",
        '(PHYS) Pressure':                                                                    "pressure-in-a-fluid",
        '(PHYS) Atmospheric Pressure':                                                        "pressure-in-a-fluid",
        '(PHYS) Presure in fluids':                                                           "pressure-in-a-fluid",
        'Forces Test':                                                                        ASSESSMENT,
    },

}


# ── SQL helpers ──────────────────────────────────────────────────────────

def q(s):
    """A SQL string literal, or NULL. Single quotes doubled, per the standard."""
    if s is None:
        return "null"
    return "'%s'" % str(s).replace("'", "''")


def school_id_sql(bare=False):
    """school_id by NAME, never a hardcoded uuid.

    uuids differ between the test project and production, so a seed carrying
    one is a seed that applies correctly in exactly one place. Looking the row
    up by its natural key makes the file portable, and a missing school then
    fails loudly on the NOT NULL rather than silently on a NULL subselect.

    `bare` drops the wrapping parentheses, for use as a CTE body.
    """
    sql = "select id from public.schools where name = %s" % q(SCHOOL_NAME)
    return sql if bare else "(%s)" % sql


def subject_id_sql(subject, bare=False):
    """subject_id by NAME — same reasoning as school_id_sql."""
    sql = ("select id from public.subjects where name = %s"
           % q(SUBJECT_TITLES[subject]))
    return sql if bare else "(%s)" % sql


# ── parsing ──────────────────────────────────────────────────────────────

def _cell(ws, row, col):
    """A cell's text, or None.

    ⚠️ Whitespace-only is None. The sheet has one cell holding a single space
    (row 123, Chemistry Foundation) and treating it as text invents a
    45th Year 11 Chemistry lesson with no title, no number and no unit.
    """
    v = ws.cell(row, col).value
    if v is None:
        return None
    v = str(v).strip()
    return v or None


def parse():
    """Every taught lesson in the workbook, one dict per (lesson, tier).

    Both sparse columns — the year in column A and each block's unit banner —
    are forward-filled, which is the only way to read a sheet a human wrote:
    the value is written once and means "and everything below, until the next
    one".
    """
    try:
        import openpyxl
    except ImportError:
        raise SystemExit(
            "rainford_sow: openpyxl is not installed. `pip3 install openpyxl` "
            "(3.1.5 is what this was written against).")

    if not os.path.isfile(WORKBOOK):
        raise SystemExit(
            "rainford_sow: cannot find the workbook at\n    %s\nIt is "
            "untracked and lives in the main checkout, not in a worktree."
            % WORKBOOK)

    wb = openpyxl.load_workbook(WORKBOOK, data_only=True)
    if SHEET not in wb.sheetnames:
        raise SystemExit(
            "rainford_sow: the workbook has no sheet %r. It has: %s. Note the "
            "trailing space in the expected name." % (SHEET, wb.sheetnames))
    ws = wb[SHEET]

    year = None
    unit = dict.fromkeys(SUBJECTS)
    out = []

    for r in range(2, ws.max_row + 1):          # row 1 is the header
        y = ws.cell(r, 1).value
        if y:
            year = int(str(y).strip().split()[-1])
        for subject in SUBJECTS:
            c_no, c_unit, c_high, c_found = COLUMNS[subject]
            u = _cell(ws, r, c_unit)
            if u:
                unit[subject] = u
            lesson_no = ws.cell(r, c_no).value
            entries = {"higher": _cell(ws, r, c_high),
                       "foundation": _cell(ws, r, c_found)}
            if lesson_no is None and not any(entries.values()):
                continue
            for tier in TIERS:
                text = entries[tier]
                if not text:
                    continue                     # HT-only lesson, or a gap
                out.append({
                    "year_group": year,
                    "subject": subject,
                    "tier": tier,
                    "lesson_no": int(lesson_no) if lesson_no else None,
                    "unit": unit[subject],
                    "text": text,
                })
    return out


# ── mapping ──────────────────────────────────────────────────────────────

def resolve(subject, unit, text):
    """(slug, unmapped) for one entry. Exactly one of the two is not None.

    Raises on an entry MAP has never seen. A lesson typed into the spreadsheet
    after this file was written must stop the run: silently emitting it with a
    NULL subtopic would look identical to a considered decision not to map it.
    """
    key = (subject, unit, text)
    if key in UNIT_MAP:
        return UNIT_MAP[key], None
    try:
        value = MAP[subject][text]
    except KeyError:
        raise SystemExit(
            "rainford_sow: %s entry %r (unit %r) is in the workbook but not "
            "in MAP. Add it — to a slug if it has a platform page, or to "
            "absent()/ambiguous()/ASSESSMENT if it does not. It must not be "
            "left to fall through." % (subject, text, unit))
    if isinstance(value, Unmapped):
        return None, value
    return value, None


def check_map(rows):
    """MAP and the workbook must describe the same set of lessons.

    Both directions matter. An entry with no key is caught in resolve(); a key
    with no entry is caught here, and is a mapping that has quietly stopped
    meaning anything — the lesson was renamed or deleted and the decision
    about it now applies to nothing.
    """
    seen = collections.defaultdict(set)
    for r in rows:
        seen[r["subject"]].add(r["text"])

    problems = []
    for subject in SUBJECTS:
        for text in MAP[subject]:
            if text not in seen[subject]:
                problems.append(
                    "MAP[%r] has %r, which no longer appears in the workbook"
                    % (subject, text))
    for (subject, unit, text) in UNIT_MAP:
        if text not in seen[subject]:
            problems.append(
                "UNIT_MAP names %s %r (unit %r), which no longer appears in "
                "the workbook" % (subject, text, unit))
    if problems:
        raise SystemExit(
            "rainford_sow: %d stale mapping(s)\n  · %s"
            % (len(problems), "\n  · ".join(problems)))


def check_slugs():
    """Every slug in MAP must be a real KS4 subtopic OF THAT SUBJECT.

    `ks4_data.classify()` is the site's own curriculum projection, so this
    checks the mapping against the pages that actually exist rather than
    against a second list that could drift from them. The subject check is the
    one that catches a copy-paste between blocks: `chromatography` is a real
    slug, and it is not a physics one.
    """
    cls = ks4_data.classify()
    problems = []
    for subject in SUBJECTS:
        for text, value in MAP[subject].items():
            if isinstance(value, Unmapped):
                continue
            meta = cls.get(value)
            if meta is None:
                problems.append("%s %r → %r is not a KS4 subtopic slug"
                                % (subject, text, value))
            elif meta["subject"] != subject:
                problems.append(
                    "%s %r → %r, which is a %s subtopic"
                    % (subject, text, value, meta["subject"]))
    for (subject, unit, text), value in UNIT_MAP.items():
        meta = cls.get(value)
        if meta is None or meta["subject"] != subject:
            problems.append("UNIT_MAP %s/%s %r → %r is not a %s subtopic"
                            % (subject, unit, text, value, subject))
    if problems:
        raise SystemExit(
            "rainford_sow: %d bad slug(s)\n  · %s"
            % (len(problems), "\n  · ".join(problems)))


def check_shape(rows):
    """The parsed sheet must still have the shape it was mapped against."""
    counts = collections.Counter()
    for r in rows:
        if r["tier"] == "higher":
            counts[(r["year_group"], r["subject"])] += 1
    if dict(counts) != EXPECTED_ROWS:
        raise SystemExit(
            "rainford_sow: the workbook's shape has changed.\n  expected %s\n"
            "  got      %s\nRe-read the sheet before trusting the mapping."
            % (sorted(EXPECTED_ROWS.items()), sorted(counts.items())))


def check_triple_prefix(rows):
    """Does "(BIO)"/"(CHEM)"/"(PHYS)" really mean Triple-only?

    The brief that commissioned this file said the prefixes *appear* to mark
    Triple-only content and asked for the reading to be verified rather than
    assumed. This measures it: for every prefixed entry that maps to a
    subtopic, does the site independently flag that subtopic `triple_only`?

    Returns (prefixed_total, prefixed_agreeing, unprefixed_but_triple), which
    main() prints. It never raises — the prefix is Rainford's notation, not a
    platform invariant, and a disagreement is a finding for the report rather
    than a broken build.
    """
    cls = ks4_data.classify()
    prefixed = prefixed_triple = unprefixed_triple = 0
    seen = set()
    for r in rows:
        key = (r["subject"], r["text"])
        if key in seen:
            continue
        seen.add(key)
        slug, _ = resolve(r["subject"], r["unit"], r["text"])
        if slug is None:
            continue
        marked = r["text"].lstrip().startswith(("(BIO)", "(CHEM)", "(PHYS)"))
        triple = cls[slug]["triple_only"]
        if marked:
            prefixed += 1
            prefixed_triple += int(triple)
        elif triple:
            unprefixed_triple += 1
    return prefixed, prefixed_triple, unprefixed_triple


# ── building the blocks ──────────────────────────────────────────────────

def build(rows):
    """(year, subject, tier) → the block's rows, renumbered from 1.

    The sheet is already in teaching order, so "renumber" is literally
    enumerate: the nth entry of a block is that block's nth taught lesson.
    """
    blocks = collections.OrderedDict()
    for year in YEARS:
        for subject in SUBJECTS:
            for tier in TIERS:
                block = [r for r in rows
                         if r["year_group"] == year
                         and r["subject"] == subject
                         and r["tier"] == tier]
                if not block:
                    continue
                if len(block) > MAX_ACADEMIC_WEEK:
                    raise SystemExit(
                        "rainford_sow: Year %d %s %s has %d lessons and "
                        "academic_week's KS4 ceiling is %d. The ceiling is a "
                        "database CHECK — raise it in a migration first."
                        % (year, subject, tier, len(block),
                           MAX_ACADEMIC_WEEK))
                out = []
                for week, r in enumerate(block, start=1):
                    slug, unmapped = resolve(r["subject"], r["unit"],
                                             r["text"])
                    note = "L%s · %s" % (r["lesson_no"] or "?", r["text"])
                    if unmapped is not None:
                        note += "  [no subtopic: %s]" % unmapped.kind
                    out.append(dict(r, academic_week=week, subtopic=slug,
                                    unmapped=unmapped, notes=note))
                blocks[(year, subject, tier)] = out
    return blocks


def unmapped_entries(blocks):
    """Every distinct unplaced lesson, in teaching order, with its tiers.

    Deduplicated on (year, subject, lesson number, text): a lesson whose two
    columns hold the same words is one lesson, and listing it twice would
    overstate the gap.
    """
    seen = collections.OrderedDict()
    for (year, subject, tier), rows in blocks.items():
        for r in rows:
            if r["unmapped"] is None:
                continue
            key = (year, subject, r["lesson_no"], r["text"])
            entry = seen.setdefault(key, dict(r, tiers=[]))
            entry["tiers"].append(tier)
    return list(seen.values())


# ── rendering ────────────────────────────────────────────────────────────

def header(path, blocks, unplaced, triple_stats):
    total = sum(len(v) for v in blocks.values())
    placed = total - sum(1 for v in blocks.values() for r in v
                         if r["unmapped"] is not None)
    prefixed, agreeing, unprefixed_triple = triple_stats

    L = []
    A = L.append
    A("-- ═══════════════════════════════════════════════════════════════════════")
    A("-- Rainford High School — the school's OWN KS4 scheme of work.")
    A("--")
    A("-- ⚠️ GENERATED FILE — DO NOT EDIT BY HAND.")
    A("--    Regenerate with:  python3 rainford_sow.py")
    A("--    Source of truth:  Rainford SOW/NEW Ks4 SOW.xlsx, sheet 'KS4 SOW '")
    A("--    Mapping:          rainford_sow.py MAP  ← review THAT, not this file")
    A("--    Written to:       %s" % path)
    A("--    Target table:     public.scheme_of_work_overrides")
    A("--                      (PER-SCHOOL — every row carries school_id)")
    A("--")
    A("-- ═══════════════════════════════════════════════════════════════════════")
    A("-- ⚠️ THIS IS ONE SCHOOL'S SEQUENCE AND IS NEVER THE PLATFORM DEFAULT.")
    A("-- ═══════════════════════════════════════════════════════════════════════")
    A("--")
    A("-- Mide's standing ruling of 2026-07-26: \"Rainford's SOW is reference")
    A("-- evidence, never a template — the platform must be school-agnostic.\"")
    A("--")
    A("-- The platform default is the AQA-spec order in")
    A("-- public.scheme_of_work_entries, written by ks4_seed_sow.py. This file")
    A("-- writes to a DIFFERENT TABLE and deletes only rows that already carry")
    A("-- Rainford's school_id and key_stage='KS4'. It cannot reach the global")
    A("-- table, KS3 rows, or any other school's rows.")
    A("--")
    A("-- Rainford BEGINS KS4 IN YEAR 9, so year_group runs 9, 10, 11.")
    A("--")
    A("-- tier comes from the spreadsheet column the lesson was written in.")
    A("-- pathway is NULL on every row: Rainford's sheet is ONE sequence per")
    A("-- tier, in which Triple-only lessons are marked inline with a (BIO),")
    A("-- (CHEM) or (PHYS) prefix rather than split into a second sequence.")
    A("-- Splitting it here would have meant inventing a Combined week order")
    A("-- Rainford has never written down. The marking is not lost: the prefix")
    A("-- survives verbatim in notes, and every mapped row's subtopic carries")
    A("-- the site's own triple_only flag.")
    A("--")
    A("--   Prefix check: %d mapped entries carry a (BIO)/(CHEM)/(PHYS) prefix;"
      % prefixed)
    A("--   %d of them map to a subtopic the site independently flags"
      % agreeing)
    A("--   triple_only. %d unprefixed entries map to a triple_only subtopic."
      % unprefixed_triple)
    A("--")
    A("-- academic_week is a teaching ORDER, renumbered from 1 inside each")
    A("-- (year_group, subject, tier) block. Rainford's own running lesson")
    A("-- numbers (1..120, continuous across all three years) are NOT weeks and")
    A("-- are preserved in notes instead. Ceiling: %d, per the CHECK added by"
      % MAX_ACADEMIC_WEEK)
    A("-- migration 20260906230500.")
    A("--")
    A("-- Idempotent: every Rainford KS4 override row is deleted and rewritten,")
    A("-- inside one transaction. Re-running is safe and is how a change lands.")
    A("--")
    A("-- Rows emitted per block:")
    A("--")
    A("--   %-6s %-9s %-11s %s" % ("year", "subject", "tier", "lessons"))
    for (year, subject, tier), rows in blocks.items():
        A("--   %-6s %-9s %-11s %3d"
          % ("Y%d" % year, SUBJECT_TITLES[subject], tier, len(rows)))
    A("--")
    A("--   %d rows · %d carry a subtopic · %d do not (named at the foot of"
      % (total, placed, total - placed))
    A("--   this file, every one of them, with the reason).")
    A("--")
    A("-- ═══════════════════════════════════════════════════════════════════════")
    A("")
    A("")
    return "\n".join(L)


def render(blocks, unplaced, triple_stats):
    out = [header(os.path.join(SEED_DIR, SEED_FILE), blocks, unplaced,
                  triple_stats)]

    out.append("begin;\n")
    out.append("""
-- Preconditions. Failing here with a sentence beats failing later with a
-- NOT NULL violation on a subselect that quietly returned NULL.
do $$
begin
  if not exists (select 1 from public.schools where name = %(school)s) then
    raise exception 'Rainford KS4 seed: no school named %%. Insert the school '
                    'row before seeding its scheme of work.', %(school)s;
  end if;
  if (select count(*) from public.subjects
       where name in ('Biology', 'Chemistry', 'Physics')) <> 3 then
    raise exception 'Rainford KS4 seed: public.subjects is missing one of '
                    'Biology / Chemistry / Physics. Seed subjects first.';
  end if;
end $$;

-- Idempotency: this file owns every KS4 override row for this school, and
-- nothing else. KS3 rows, other schools' rows and the global table are all
-- outside the WHERE clause.
delete from public.scheme_of_work_overrides
 where key_stage = 'KS4'
   and school_id = %(school_id)s;
""" % {"school": q(SCHOOL_NAME), "school_id": school_id_sql()})

    for (year, subject, tier), rows in blocks.items():
        out.append(
            "\n-- \u2500\u2500 Year %d \u00b7 %s \u00b7 %s \u2014 %d lessons "
            "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
            % (year, SUBJECT_TITLES[subject], tier, len(rows)))
        # The two natural-key lookups are hoisted into CTEs rather than
        # repeated on every row. Same rule as ks4_seed_sow's subject_id_sql —
        # by NAME, never a uuid, because test and prod ids differ — but stated
        # once per block, so the rows below read as the scheme of work they
        # are rather than as 670 copies of the same subselect.
        out.append(
            "with school as (%s),\n"
            "     subject as (%s)\n"
            % (school_id_sql(bare=True), subject_id_sql(subject, bare=True)))
        out.append(
            "insert into public.scheme_of_work_overrides\n"
            "  (school_id, key_stage, year_group, tier, pathway, subject_id,\n"
            "   academic_week, topic, subtopic, notes)\n"
            "select school.id, 'KS4', %d, %s, null, subject.id,\n"
            "       v.academic_week, v.topic, v.subtopic, v.notes\n"
            "  from school, subject, (values\n"
            % (year, q(tier)))
        vals = []
        unit = None
        for n, r in enumerate(rows):
            if r["unit"] != unit:
                unit = r["unit"]
                vals.append("  -- %s" % unit)
            if n == 0:
                # Types stated once, on the first tuple. Without them a block
                # whose subtopic column is NULL throughout infers `unknown`
                # and the insert leans on an implicit coercion.
                vals.append(
                    "  (%d::smallint, %s::text, %s::text, %s::text)"
                    % (r["academic_week"], q(r["unit"]), q(r["subtopic"]),
                       q(r["notes"])))
            else:
                vals.append(
                    "  (%d, %s, %s, %s)"
                    % (r["academic_week"], q(r["unit"]), q(r["subtopic"]),
                       q(r["notes"])))
        out.append(_join_values(vals)
                   + "\n) as v (academic_week, topic, subtopic, notes);\n")


    out.append("\ncommit;\n")
    out.append(omitted_comment(blocks, unplaced))
    return "".join(out)


def omitted_comment(blocks, unplaced):
    """Every lesson with no subtopic, named, at the foot of the file.

    It sits AFTER the commit deliberately. It is not something the database
    does; it is the record of what this seed could not say, kept next to what
    it did say so the two cannot be separated. Every one of these lessons IS
    in the table — the row exists and holds the school's real teaching order —
    it simply has subtopic = NULL.
    """
    by_kind = collections.Counter(e["unmapped"].kind for e in unplaced)

    L = ["", ""]
    A = L.append
    A("-- ═══════════════════════════════════════════════════════════════════════")
    A("-- ⚠️ UNMAPPED — %d distinct lessons with subtopic = NULL." % len(unplaced))
    A("-- ═══════════════════════════════════════════════════════════════════════")
    A("--")
    if not unplaced:
        A("-- None. Every lesson in the sheet reached a platform subtopic.")
        A("--")
        return "\n".join(L) + "\n"
    A("-- These rows ARE in the table. They hold Rainford's real teaching order")
    A("-- and their verbatim titles; only `subtopic` is NULL, because no")
    A("-- platform page honestly corresponds. Nothing here was guessed at: a")
    A("-- wrong slug points a teacher at the wrong lesson and says nothing")
    A("-- about it, which is worse than a gap that names itself.")
    A("--")
    A("-- By reason:")
    A("--")
    for kind in ("assessment", "absent", "ambiguous"):
        if by_kind.get(kind):
            A("--   %-11s %3d" % (kind, by_kind[kind]))
    A("--")
    A("-- Full list — year, subject, Rainford's own lesson number, verbatim")
    A("-- text, and the tier column(s) it was written in:")
    subject = year = None
    for e in unplaced:
        if (e["year_group"], e["subject"]) != (year, subject):
            year, subject = e["year_group"], e["subject"]
            A("--")
            A("--   ── Year %d · %s ──" % (year, SUBJECT_TITLES[subject]))
        tiers = "H+F" if len(e["tiers"]) == 2 else e["tiers"][0][0].upper()
        A("--     L%-4s %-3s [%s]  %s"
          % (e["lesson_no"] or "?", tiers, e["unmapped"].kind, e["text"]))
        if e["unmapped"].kind != "assessment":
            A("--            ↳ %s" % e["unmapped"].why)
    A("--")
    A("-- ═══════════════════════════════════════════════════════════════════════")
    return "\n".join(L) + "\n"


def _join_values(lines):
    """Comma-separate the value tuples, leaving comment lines uncommaed."""
    out = []
    idxs = [i for i, l in enumerate(lines) if not l.lstrip().startswith("--")]
    last = idxs[-1] if idxs else None
    for i, l in enumerate(lines):
        if l.lstrip().startswith("--") or i == last:
            out.append(l)
        else:
            out.append(l + ",")
    return "\n".join(out)


# ── run ──────────────────────────────────────────────────────────────────

def main():
    print("\nrainford_sow — Rainford High School's KS4 scheme, as override "
          "rows\n" + "=" * 70)

    os.makedirs(SEED_DIR, exist_ok=True)

    rows = parse()
    check_shape(rows)
    check_slugs()
    check_map(rows)

    blocks = build(rows)
    unplaced = unmapped_entries(blocks)
    triple_stats = check_triple_prefix(rows)

    path = os.path.join(SEED_DIR, SEED_FILE)
    with open(path, "w", encoding="utf-8") as f:
        f.write(render(blocks, unplaced, triple_stats))

    _report(path, rows, blocks, unplaced, triple_stats)
    return 0


def _report(path, rows, blocks, unplaced, triple_stats):
    total = sum(len(v) for v in blocks.values())
    placed = total - sum(1 for v in blocks.values() for r in v
                         if r["unmapped"] is not None)
    prefixed, agreeing, unprefixed_triple = triple_stats

    print("\n  workbook  ← %s" % WORKBOOK)
    print("  written   → %s\n" % path)

    print("  %-6s %-9s %-11s %7s %7s" % ("year", "subject", "tier", "rows",
                                         "max wk"))
    for (year, subject, tier), block in blocks.items():
        print("  %-6s %-9s %-11s %7d %7d"
              % ("Y%d" % year, SUBJECT_TITLES[subject], tier, len(block),
                 max(r["academic_week"] for r in block)))

    print("\n  %d rows · %d with a subtopic · %d without"
          % (total, placed, total - placed))
    print("  taught lessons in the sheet: %d (Higher %d, Foundation %d)"
          % (len(rows),
             sum(1 for r in rows if r["tier"] == "higher"),
             sum(1 for r in rows if r["tier"] == "foundation")))
    print("  ceiling %d per block (table CHECK); largest block %d."
          % (MAX_ACADEMIC_WEEK,
             max(len(v) for v in blocks.values())))

    print("\n  Triple prefix check: %d mapped entries carry (BIO)/(CHEM)/"
          "(PHYS);" % prefixed)
    print("    %d of those map to a triple_only subtopic; %d unprefixed "
          "entries do too." % (agreeing, unprefixed_triple))

    by_kind = collections.Counter(e["unmapped"].kind for e in unplaced)
    print("\n  ⚠️ UNMAPPED — %d distinct lessons (%s):"
          % (len(unplaced),
             ", ".join("%s %d" % (k, by_kind[k]) for k in sorted(by_kind))))
    subject = year = None
    for e in unplaced:
        if e["unmapped"].kind == "assessment":
            continue
        if (e["year_group"], e["subject"]) != (year, subject):
            year, subject = e["year_group"], e["subject"]
            print("     ── Year %d · %s ──" % (year, SUBJECT_TITLES[subject]))
        print("       L%-4s [%s]  %s"
              % (e["lesson_no"] or "?", e["unmapped"].kind, e["text"]))
    print("     (%d assessment/review lessons omitted from this list; they "
          "are\n      all named in the SQL.)" % by_kind.get("assessment", 0))


if __name__ == "__main__":
    raise SystemExit(main())
