"""Chemistry · Chemical analysis — the MRB-338 expansion for `metal-hydroxides`.

The precipitate colours carry the recall — copper(II) blue, iron(II) green,
iron(III) brown, and aluminium, calcium and magnesium all white — and the whole
weight of the reasoning falls on the one discriminator that separates the three
whites: aluminium hydroxide dissolves in excess sodium hydroxide and the other
two do not.

Alongside that sit the ionic equations, the hydroxide formulae, the ammonium
ion (no precipitate at all, but ammonia on warming, turning damp red litmus
blue) and the combination of this test with a flame test. Formulae are FLAT.
"""

TOPIC = "analysis"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": 'ks4-metal-hydroxides-e05',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the colour of a precipitate of iron(III) hydroxide.',
        "options": [
            'Brown',
            'Green',
            'Blue',
            'Yellow',
        ],
        "correct_index": 0,
        "why": 'Iron(III) hydroxide is brown; green belongs to iron(II) and yellow '
               'to silver iodide in the halide test.',
    },
    {
        "id": 'ks4-metal-hydroxides-e06',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Magnesium chloride solution is treated with sodium hydroxide. State the colour of the solid that appears.',
        "options": [
            'A blue solid',
            'A white solid',
            'A brown solid',
            'A green solid',
        ],
        "correct_index": 1,
        "why": 'Magnesium hydroxide is white, as are the precipitates of calcium '
               'and aluminium.',
    },
    {
        "id": 'ks4-metal-hydroxides-e07',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the formula of the aluminium compound precipitated by sodium hydroxide.',
        "options": [
            'Al(OH)2',
            'AlOH',
            'Al(OH)3',
            'Al2(OH)3',
        ],
        "correct_index": 2,
        "why": 'Aluminium forms a 3+ ion, so three hydroxide ions are needed and '
               'the white solid is Al(OH)3.',
    },
    {
        "id": 'ks4-metal-hydroxides-e08',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the charge carried by a hydroxide ion.',
        "options": [
            '2-',
            '1+',
            '3-',
            '1-',
        ],
        "correct_index": 3,
        "why": 'A hydroxide ion carries a single negative charge, which is why a 2+ '
               'metal ion needs two of them and a 3+ ion needs three.',
    },
    {
        "id": 'ks4-metal-hydroxides-e09',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State what is meant by a precipitate.',
        "options": [
            'An insoluble solid formed when two solutions are mixed',
            'A gas given off when two solutions are mixed together',
            'A solid that dissolves as soon as the solutions are mixed',
            'A colour change that is seen whenever two solutions are mixed together',
        ],
        "correct_index": 0,
        "why": 'The two dissolved ions form a compound that will not dissolve, so '
               'it appears as a fine solid suspended in the liquid.',
    },
    {
        "id": 'ks4-metal-hydroxides-e10',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the colour change of damp red litmus paper held in ammonia gas.',
        "options": [
            'Red to white',
            'Red to blue',
            'Red to green',
            'No change',
        ],
        "correct_index": 1,
        "why": 'Ammonia is alkaline in water, so it turns damp red litmus paper blue.',
    },
    {
        "id": 'ks4-metal-hydroxides-e11',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the formula of the hydroxide formed by iron(III) ions.',
        "options": [
            'Fe(OH)2',
            'FeOH',
            'Fe(OH)3',
            'Fe2(OH)3',
        ],
        "correct_index": 2,
        "why": 'A 3+ ion needs three hydroxide ions to balance the charge, giving '
               'Fe(OH)3.',
    },
    {
        "id": 'ks4-metal-hydroxides-e12',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State why sodium hydroxide solution must be handled with care in this test.',
        "options": [
            'It is highly flammable and catches fire easily',
            'It gives off a toxic gas even at ordinary room temperature',
            'It explodes when it is mixed with any acid',
            'It is corrosive and damages skin and eyes',
        ],
        "correct_index": 3,
        "why": 'Sodium hydroxide solution is corrosive, so eye protection is worn '
               'and spills are washed off at once.',
    },
    {
        "id": 'ks4-metal-hydroxides-s05',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Predict what is seen when sodium hydroxide solution is added to iron(III) chloride solution.',
        "options": [
            'A brown precipitate forms and stays in the tube',
            'A green precipitate forms and then dissolves again in excess',
            'A blue precipitate forms and stays in the tube',
            'No precipitate forms but a gas is given off slowly',
        ],
        "correct_index": 0,
        "why": 'Iron(III) ions give the brown precipitate Fe(OH)3, which does not '
               'dissolve in excess alkali.',
    },
    {
        "id": 'ks4-metal-hydroxides-s06',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Sodium hydroxide is added to magnesium chloride solution and then more is added. Predict what is seen at each stage.',
        "options": [
            'A white precipitate forms and then dissolves in the excess',
            'A white precipitate forms and remains when excess is added',
            'No precipitate forms until a large excess has been added',
            'A brown precipitate forms and remains when excess is added',
        ],
        "correct_index": 1,
        "why": 'Magnesium hydroxide is white and is not amphoteric, so adding '
               'excess alkali leaves the precipitate unchanged.',
    },
    {
        "id": 'ks4-metal-hydroxides-s07',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain what is meant by describing aluminium hydroxide as amphoteric.',
        "options": [
            'It dissolves in water but not in any other solvent',
            'It changes colour depending on the pH of the solution around it',
            'It reacts with both acids and with excess alkalis',
            'It can act as a catalyst for its own decomposition',
        ],
        "correct_index": 2,
        "why": 'Reacting with both acid and excess alkali is what makes aluminium '
               'hydroxide dissolve where calcium and magnesium hydroxides do not.',
    },
    {
        "id": 'ks4-metal-hydroxides-s08',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the ionic equation for copper(II) ions reacting with hydroxide ions.',
        "options": [
            'Cu2+ + OH- to CuOH',
            'Cu+ + 2OH- to Cu(OH)2',
            'Cu2+ + 3OH- to Cu(OH)3',
            'Cu2+ + 2OH- to Cu(OH)2',
        ],
        "correct_index": 3,
        "why": 'Two hydroxide ions balance the 2+ charge on the copper ion, giving '
               'the blue solid Cu(OH)2.',
    },
    {
        "id": 'ks4-metal-hydroxides-s09',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Iron(II) sulfate solution forms a green solid with hydroxide ions. State the ionic equation for this.',
        "options": [
            'Fe2+ + 2OH- to Fe(OH)2',
            'Fe3+ + 3OH- to Fe(OH)3',
            'Fe2+ + OH- to FeOH',
            'Fe2+ + 3OH- to Fe(OH)3',
        ],
        "correct_index": 0,
        "why": 'Iron(II) carries a 2+ charge, so two hydroxide ions are needed and '
               'the green solid Fe(OH)2 is formed.',
    },
    {
        "id": 'ks4-metal-hydroxides-s10',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why the litmus paper used in the ammonium ion test must be damp.',
        "options": [
            'The water holds the paper against the mouth of the tube',
            'Ammonia must dissolve in water before it acts as an alkali',
            'The water stops the litmus paper being burnt by the heat',
            'Damp paper picks up more of the gas than dry paper can',
        ],
        "correct_index": 1,
        "why": 'An indicator responds to hydroxide ions in solution, and those only '
               'appear once the ammonia has dissolved in the water on the paper.',
    },
    {
        "id": 'ks4-metal-hydroxides-s11',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why the mixture must be warmed when testing for the ammonium ion.',
        "options": [
            'Warming makes the sodium hydroxide dissolve in the water',
            'Warming changes the colour of the litmus paper being used',
            'Warming drives off enough ammonia gas to be detected',
            'Warming prevents any precipitate forming and hiding the gas from view',
        ],
        "correct_index": 2,
        "why": 'Ammonia is very soluble in water, so without warming it stays '
               'dissolved and too little escapes to reach the paper.',
    },
    {
        "id": 'ks4-metal-hydroxides-s12',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Describe the full method for testing a solution for a metal ion with sodium hydroxide.',
        "options": [
            'Add excess at once and note the colour of the final mixture formed',
            'Add a few drops, warm the tube and test the gas with damp litmus',
            'Add an equal volume, filter the mixture and weigh the solid obtained',
            'Add a few drops, note any precipitate, then add excess and note again',
        ],
        "correct_index": 3,
        "why": 'The first few drops give the colour and the excess gives the '
               'aluminium discriminator, so both stages are needed.',
    },
    {
        "id": 'ks4-metal-hydroxides-s13',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why the sample must be in solution before sodium hydroxide is added.',
        "options": [
            'The metal ions must be free in solution to meet hydroxide ions',
            'A solid would react too violently with the alkali added',
            'A solid would change the colour of the precipitate formed',
            'The solution stops the sodium hydroxide from evaporating away too soon',
        ],
        "correct_index": 0,
        "why": 'Precipitation happens when dissolved ions meet, so ions locked in a '
               'solid lattice cannot take part.',
    },
    {
        "id": 'ks4-metal-hydroxides-s14',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": "Deduce the metal ion in a solution that produces a brown solid with sodium hydroxide, and give that solid's formula.",
        "options": [
            'Iron(II), and the precipitate is Fe(OH)2',
            'Iron(III), and the precipitate is Fe(OH)3',
            'Copper(II), and the precipitate is Cu(OH)2',
            'Aluminium, and the precipitate is Al(OH)3',
        ],
        "correct_index": 1,
        "why": 'Brown is the colour of iron(III) hydroxide, and a 3+ ion needs '
               'three hydroxide ions.',
    },
    {
        "id": 'ks4-metal-hydroxides-s15',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain how the sodium hydroxide test separates iron(II) from iron(III).',
        "options": [
            'One gives a precipitate and the other gives none at all',
            'One precipitate dissolves in excess and the other does not',
            'One gives a green precipitate and the other a brown one',
            'One gives off a gas on warming and the other stays quiet',
        ],
        "correct_index": 2,
        "why": 'Both form a precipitate, but the colours differ clearly, so the '
               'colour alone distinguishes the two oxidation states.',
    },
    {
        "id": 'ks4-metal-hydroxides-s16',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why the colour of the precipitate alone cannot separate calcium, magnesium and aluminium.',
        "options": [
            'All three dissolve again before the colour can be seen',
            'All three form precipitates that are the same shade of grey',
            'All three give off a gas that hides the colour of the solid from view',
            'All three form precipitates that are white in colour',
        ],
        "correct_index": 3,
        "why": 'A single white result covers three ions, which is why the behaviour '
               'in excess alkali and a flame test are needed as well.',
    },
    {
        "id": 'ks4-metal-hydroxides-s17',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Describe what happens when excess sodium hydroxide is added to a white precipitate of calcium hydroxide.',
        "options": [
            'It stays as a white solid suspended in the mixture',
            'It dissolves completely and the mixture turns clear again',
            'It turns brown as the calcium is oxidised by the alkali',
            'It gives off ammonia gas, which turns litmus paper blue',
        ],
        "correct_index": 0,
        "why": 'Calcium hydroxide is not amphoteric, so excess alkali leaves it '
               'unchanged, unlike aluminium hydroxide.',
    },
    {
        "id": 'ks4-metal-hydroxides-s18',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why ammonium ions give no precipitate with sodium hydroxide solution.',
        "options": [
            'Ammonium hydroxide is insoluble and sinks out of sight',
            'The product formed is a gas and a liquid, not a solid',
            'Ammonium ions carry no charge, so nothing can react',
            'Sodium hydroxide is too dilute to precipitate ammonium',
        ],
        "correct_index": 1,
        "why": 'Hydroxide ions take a hydrogen ion from the ammonium ion to give '
               'ammonia and water, and neither of those is an insoluble solid.',
    },
    {
        "id": 'ks4-metal-hydroxides-s19',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Ammonium chloride is warmed with sodium hydroxide. State the equation for the reaction of the ammonium ion.',
        "options": [
            'NH4+ + OH- to NH4OH',
            'NH4+ + 2OH- to NH3 + 2H2O',
            'NH4+ + OH- to NH3 + H2O',
            'NH3 + OH- to NH4+ + H2O',
        ],
        "correct_index": 2,
        "why": 'One hydroxide ion removes one hydrogen ion, leaving ammonia gas and '
               'a molecule of water.',
    },
    {
        "id": 'ks4-metal-hydroxides-s20',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A compound in solution gives a blue precipitate with sodium hydroxide. Name a compound it could be.',
        "options": [
            'Iron(II) sulfate',
            'Magnesium nitrate',
            'Aluminium sulfate',
            'Copper(II) chloride',
        ],
        "correct_index": 3,
        "why": 'Only copper(II) gives a blue precipitate, so any soluble copper(II) '
               'compound would produce that result.',
    },
    {
        "id": 'ks4-metal-hydroxides-s21',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why a metal ion with a 2+ charge forms a hydroxide of the form M(OH)2.',
        "options": [
            'Two hydroxide ions are needed to balance the 2+ charge',
            'Every metal hydroxide contains exactly two hydroxide ions',
            'The metal ion splits into two parts as it reacts with alkali',
            'Hydroxide ions always join together in pairs before they react at all',
        ],
        "correct_index": 0,
        "why": 'Each hydroxide ion carries a single negative charge, so two of them '
               'neutralise a 2+ metal ion and the compound has no overall charge.',
    },
    {
        "id": 'ks4-metal-hydroxides-s22',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why a flame test and a precipitate test together give a more reliable identification.',
        "options": [
            'Two tests take longer, so the chemist is more careful with them',
            'Two independent results agreeing is stronger than one result',
            'The flame test identifies the negative ion and the other the metal',
            'The two tests always give exactly the same colour as each other',
        ],
        "correct_index": 1,
        "why": 'Each test on its own leaves several ions possible, and the overlap '
               'between the two sets of possibilities is usually a single ion.',
    },
    {
        "id": 'ks4-metal-hydroxides-s23',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why only a few drops of sodium hydroxide are added at the start of the test.',
        "options": [
            'So that the solution does not become too hot to handle',
            'So that none of the sodium hydroxide solution is wasted',
            'So that the colour of any precipitate can be seen clearly',
            'So that the metal ions have time to dissolve properly',
        ],
        "correct_index": 2,
        "why": 'The first few drops show the colour, and adding excess straight away would dissolve an aluminium precipitate before it had been seen.',
    },
    {
        "id": 'ks4-metal-hydroxides-s24',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why calcium hydroxide gives only a faint white precipitate.',
        "options": [
            'Calcium hydroxide is colourless rather than white in solution',
            'Calcium ions react only very slowly with hydroxide ions',
            'Calcium hydroxide breaks down again as soon as it forms',
            'Calcium hydroxide is slightly soluble, so some stays dissolved',
        ],
        "correct_index": 3,
        "why": 'Calcium hydroxide is sparingly soluble, which is also why limewater '
               'exists as a solution at all.',
    },
    {
        "id": 'ks4-metal-hydroxides-s25',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why sodium hydroxide rather than another alkali is chosen for this test.',
        "options": [
            'It is a soluble alkali that supplies plenty of hydroxide ions',
            'It is the only compound in the laboratory that contains hydroxide',
            'Its sodium ion joins the precipitate and makes its colour much brighter',
            'It is the weakest alkali available, so the test is safe to do',
        ],
        "correct_index": 0,
        "why": 'A high concentration of free hydroxide ions is what precipitates '
               'the metal hydroxide, and sodium salts are soluble so nothing else '
               'comes out.',
    },
    {
        "id": 'ks4-metal-hydroxides-s26',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Iron(II) sulfate solution is treated with a few drops of sodium hydroxide. State the observation.',
        "options": [
            'A brown precipitate forms straight away in the tube',
            'A green precipitate forms straight away in the tube',
            'A white precipitate forms and dissolves in excess alkali',
            'No change is seen until the mixture is warmed gently',
        ],
        "correct_index": 1,
        "why": 'Iron(II) gives the green precipitate Fe(OH)2, which only turns '
               'brown at the surface after standing in air.',
    },
    {
        "id": 'ks4-metal-hydroxides-h05',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the equation for aluminium hydroxide dissolving in excess sodium hydroxide.',
        "options": [
            'Al(OH)3 + 3OH- to Al(OH)6 3-',
            'Al(OH)3 to Al3+ + 3OH-',
            'Al(OH)3 + OH- to Al(OH)4-',
            'Al(OH)3 + OH- to Al2O3 + 2H2O',
        ],
        "correct_index": 2,
        "why": 'One further hydroxide ion is taken up to give the soluble aluminate '
               'ion Al(OH)4-, which is why the precipitate disappears.',
    },
    {
        "id": 'ks4-metal-hydroxides-h06',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A solution gives a white precipitate that dissolves when excess sodium hydroxide is added. Deduce the metal ion and justify the deduction.',
        "options": [
            'Magnesium, because magnesium hydroxide is amphoteric',
            'Calcium, because calcium hydroxide is soluble in water',
            'Iron(II), because its precipitate changes in air',
            'Aluminium, because only its hydroxide reacts with excess alkali',
        ],
        "correct_index": 3,
        "why": 'Of the three white precipitates only aluminium hydroxide is '
               'amphoteric, so dissolving in excess alkali identifies aluminium on '
               'its own.',
    },
    {
        "id": 'ks4-metal-hydroxides-h07',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why iron forms the two different hydroxides Fe(OH)2 and Fe(OH)3.',
        "options": [
            'Iron can form ions of two different charges, 2+ and 3+',
            'One hydroxide forms in the cold and the other only on warming',
            'Iron(II) and iron(III) are two completely different elements',
            'One forms with sodium hydroxide and one with potassium hydroxide',
        ],
        "correct_index": 0,
        "why": 'The number of hydroxide ions needed matches the charge on the iron '
               'ion, so the 2+ ion gives two and the 3+ ion gives three.',
    },
    {
        "id": 'ks4-metal-hydroxides-h08',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A magnesium salt and a calcium salt both give a white precipitate that stays in excess alkali. Determine a further test that separates them.',
        "options": [
            'Add more sodium hydroxide and see which precipitate dissolves',
            'Carry out a flame test and look for an orange-red colour',
            'Warm each mixture and test the gas with damp red litmus paper',
            'Filter each mixture and compare the masses of solid collected',
        ],
        "correct_index": 1,
        "why": 'Calcium gives an orange-red flame and magnesium gives no flame '
               'colour at all, so the flame test separates the pair that the '
               'precipitate cannot.',
    },
    {
        "id": 'ks4-metal-hydroxides-h09',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why the sodium hydroxide test says nothing about the negative ion in a compound.',
        "options": [
            'The negative ion is destroyed by the alkali that is added',
            'The negative ion stays in the solid and cannot be detected',
            'The precipitate is formed by the metal ion and hydroxide only',
            'Negative ions never react with anything in a solution at all',
        ],
        "correct_index": 2,
        "why": 'The negative ion remains dissolved as a spectator, so a separate '
               'anion test is needed before the compound can be named.',
    },
    {
        "id": 'ks4-metal-hydroxides-h10',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Calculate the mass of copper(II) hydroxide formed when 0.020 mol of copper(II) ions is fully precipitated. Mr of Cu(OH)2 = 97.5.',
        "options": [
            '4.88 g',
            '0.98 g',
            '19.5 g',
            '1.95 g',
        ],
        "correct_index": 3,
        "why": '0.020 mol of ions gives 0.020 mol of Cu(OH)2, and 0.020 × 97.5 = '
               '1.95 g.',
    },
    {
        "id": 'ks4-metal-hydroxides-h11',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Evaluate the claim that a white precipitate with sodium hydroxide shows aluminium is present.',
        "options": [
            'Unsafe, because calcium and magnesium also give white ones',
            'Sound, because only aluminium gives a white precipitate',
            'Sound, because the white colour rules out every other ion',
            'Unsafe, because aluminium gives a brown precipitate instead',
        ],
        "correct_index": 0,
        "why": 'Three different ions give a white precipitate, so aluminium is '
               'confirmed only when the precipitate then dissolves in excess '
               'alkali.',
    },
    {
        "id": 'ks4-metal-hydroxides-h12',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A student adds sodium hydroxide until a white precipitate just appears and then stops. Explain what evidence they have failed to collect.',
        "options": [
            'The colour of the precipitate, which they never recorded',
            'Whether the precipitate dissolves when excess is added',
            'The mass of the precipitate, which they never weighed',
            'Whether a gas is released when the tube is warmed up',
        ],
        "correct_index": 1,
        "why": 'The behaviour in excess alkali is the only part of this test that '
               'separates aluminium from calcium and magnesium.',
    },
    {
        "id": 'ks4-metal-hydroxides-h13',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Compare what happens when excess sodium hydroxide is added to solutions of aluminium, calcium and magnesium ions.',
        "options": [
            'All three precipitates dissolve again in the excess alkali',
            'Only the calcium precipitate dissolves in the excess alkali',
            'Only the aluminium precipitate dissolves in the excess alkali',
            'None of the three precipitates is changed by excess alkali',
        ],
        "correct_index": 2,
        "why": 'Aluminium hydroxide is amphoteric and forms the soluble aluminate '
               'ion, while calcium and magnesium hydroxides are unaffected.',
    },
    {
        "id": 'ks4-metal-hydroxides-h14',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why the ammonium ion is detected without any precipitate forming at all.',
        "options": [
            'The precipitate forms but is colourless and cannot be seen',
            'The precipitate forms and then dissolves again immediately',
            'Ammonium ions react only with acids and never with any alkali at all',
            'The products are a soluble gas and water, neither a solid',
        ],
        "correct_index": 3,
        "why": 'The hydroxide ion removes a hydrogen ion rather than combining with '
               'a metal ion, so the evidence is the gas released instead.',
    },
    {
        "id": 'ks4-metal-hydroxides-h15',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the formula and charge of the ion formed when aluminium hydroxide dissolves in excess alkali.',
        "options": [
            'Al(OH)4-',
            'Al3+',
            'Al(OH)2+',
            'AlO3 3-',
        ],
        "correct_index": 0,
        "why": 'The aluminate ion Al(OH)4- carries a single negative charge and is '
               'soluble, which is why the white solid disappears.',
    },
    {
        "id": 'ks4-metal-hydroxides-h16',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Group 1 metals are not among the ions this precipitate test can find. Explain why.',
        "options": [
            'Their ions carry no charge and cannot react with hydroxide',
            'Their hydroxides are soluble, so no solid can appear',
            'Their ions are too small to form a solid with hydroxide',
            'Their hydroxides decompose the moment that they form',
        ],
        "correct_index": 1,
        "why": 'A precipitate only appears when the product will not dissolve, and '
               'group 1 hydroxides are all soluble in water.',
    },
    {
        "id": 'ks4-metal-hydroxides-h17',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why a 3+ metal ion takes three hydroxide ions while a 2+ ion takes only two.',
        "options": [
            'Larger charges attract hydroxide ions from further away',
            'A 3+ ion is bigger, so more hydroxide ions fit around it',
            'The compound formed must have no overall electrical charge',
            'Hydroxide ions carry a 2- charge, so fewer are ever needed',
        ],
        "correct_index": 2,
        "why": 'Each hydroxide ion carries one negative charge, so the number '
               'needed always equals the positive charge on the metal ion.',
    },
    {
        "id": 'ks4-metal-hydroxides-h18',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A solution contains both copper(II) and iron(III) ions. Predict what is seen when sodium hydroxide is added.',
        "options": [
            'A clear blue solution with no solid appearing at all',
            'Only a blue solid, because copper reacts far more quickly',
            'Only a brown solid, because iron(III) prevents copper reacting',
            'A mixed blue and brown solid, so neither colour is clean',
        ],
        "correct_index": 3,
        "why": 'Both hydroxides are insoluble and both precipitate together, so the '
               'mixed colour makes either ion hard to confirm from this test alone.',
    },
    {
        "id": 'ks4-metal-hydroxides-h19',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why a precipitate test is judged against a white background.',
        "options": [
            'A pale colour is far easier to judge against a plain background',
            'A white background keeps the test tube at a steady temperature',
            'A white background reflects light into the solution and warms it',
            'A white background stops the precipitate settling to the bottom',
        ],
        "correct_index": 0,
        "why": 'Distinguishing a faint white precipitate from a clear solution, or '
               'green from brown, depends on seeing the colour without any '
               'distraction behind it.',
    },
    {
        "id": 'ks4-metal-hydroxides-h20',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Evaluate whether the sodium hydroxide test alone could show that a solution is copper(II) sulfate.',
        "options": [
            'Yes, because a blue precipitate is unique to copper(II) sulfate',
            'No, because it identifies copper(II) but not the sulfate ion',
            'Yes, because sulfates are the only salts that give precipitates',
            'No, because copper(II) gives no precipitate with sodium hydroxide',
        ],
        "correct_index": 1,
        "why": 'The blue precipitate names the metal ion only, so barium chloride '
               'after acidifying is still needed to confirm the sulfate.',
    },
    {
        "id": 'ks4-metal-hydroxides-h21',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Determine the number of moles of hydroxide ions needed to precipitate 0.050 mol of iron(III) ions completely.',
        "options": [
            '0.050 mol',
            '0.100 mol',
            '0.150 mol',
            '0.017 mol',
        ],
        "correct_index": 2,
        "why": 'Each iron(III) ion needs three hydroxide ions, so 0.050 × 3 = 0.150 '
               'mol.',
    },
    {
        "id": 'ks4-metal-hydroxides-h22',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why most metal hydroxide precipitates do not redissolve when more water is added.',
        "options": [
            'They react with water to form a new solid straight away',
            'They are held onto the glass of the tube by an electrostatic charge',
            'They are denser than water and so cannot be dissolved',
            'They are insoluble, so more water does not dissolve them',
        ],
        "correct_index": 3,
        "why": 'Insoluble means very little dissolves in any volume of water, which '
               'is why only the amphoteric aluminium hydroxide disappears in excess '
               'alkali.',
    },
    {
        "id": 'ks4-metal-hydroxides-h23',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A student adds sodium hydroxide to a solution and sees no precipitate whatever. Suggest what the solution could contain.',
        "options": [
            'Sodium ions or ammonium ions, neither of which precipitates',
            'Iron(III) ions, whose precipitate is too pale to be seen',
            'Aluminium ions, which never react with sodium hydroxide',
            'Copper(II) ions, whose precipitate dissolves straight away',
        ],
        "correct_index": 0,
        "why": 'Group 1 hydroxides are soluble and the ammonium ion gives a gas '
               'instead, so neither produces a solid.',
    },
    {
        "id": 'ks4-metal-hydroxides-h24',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why damp red litmus, rather than damp blue litmus, is used to test the gas in the ammonium test.',
        "options": [
            'Red paper is cheaper and easier to obtain for a school',
            'A change from red to blue shows clearly that the gas is alkaline',
            'Blue litmus would be bleached white by the gas',
            'Red litmus reacts with ammonia but blue does not',
        ],
        "correct_index": 1,
        "why": 'Blue litmus is already blue, so an alkaline gas would produce no '
               'visible change and the positive result would be missed.',
    },
    {
        "id": 'ks4-metal-hydroxides-h25',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why a flame test would not detect an ammonium ion in a compound.',
        "options": [
            'The ammonium ion burns away before the flame can excite it',
            'The ammonium ion emits light outside the visible range only',
            'The ammonium ion contains no metal to emit coloured light',
            'The ammonium ion is always masked by traces of sodium',
        ],
        "correct_index": 2,
        "why": 'Flame colours come from excited electrons in metal ions, and '
               'ammonium is a polyatomic ion made only of nitrogen and hydrogen.',
    },
    {
        "id": 'ks4-metal-hydroxides-h26',
        "subtopic_slug": 'metal-hydroxides',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A sample containing 0.010 mol of iron(III) ions is precipitated completely as Fe(OH)3, Mr = 107. Determine the mass of solid obtained.',
        "options": [
            '10.7 g',
            '0.36 g',
            '3.21 g',
            '1.07 g',
        ],
        "correct_index": 3,
        "why": '0.010 mol of ions gives 0.010 mol of Fe(OH)3, and 0.010 × 107 = '
               '1.07 g.',
    },
]
