"""Chemistry · Chemical analysis — the MRB-338 expansion for `pure-substances`.

Purity is one idea — a single element or compound, with a sharp fixed melting
and boiling point — worked across the places it actually bites: the melting
point apparatus and the width of the range it gives, the depression and
elevation an impurity causes, percentage purity arithmetic, and the named
industrial cases (semiconductor silicon, refined copper, cast iron, 18 carat
gold) where purity is the whole point.

Weight falls on standard and harder because the recall is thin and the
reasoning is not: most rows ask a student to read a temperature behaviour and
say what it means, or to separate purity from yield, identity and pressure.
"""

TOPIC = "analysis"
SUBJECT = "chemistry"

QUESTIONS = [
    # ── easier ──────────────────────────────────────────────────────────
    {
        "id": "ks4-pure-substances-e06",
        "subtopic_slug": "pure-substances",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the effect that an impurity has on the melting point of a solid.",
        "options": [
            "It lowers the melting point and spreads it over a range",
            "It raises the melting point and spreads melting over a wide range",
            "It lowers the melting point but keeps it sharp and fixed",
            "It leaves the melting point completely unchanged",
        ],
        "correct_index": 0,
        "why": "An impurity disrupts the regular arrangement of particles, so melting "
               "starts below the pure value and finishes over a range.",
    },
    {
        "id": "ks4-pure-substances-e07",
        "subtopic_slug": "pure-substances",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which of these is a mixture rather than a pure substance?",
        "options": [
            "Nitrogen gas taken from a cylinder",
            "Distilled water collected from a still",
            "Clean air taken from a mountain top",
            "Copper metal cut from a long length of household wiring",
        ],
        "correct_index": 2,
        "why": "Air is a mixture of nitrogen, oxygen, argon and carbon dioxide, however "
               "clean it is.",
    },
    {
        "id": "ks4-pure-substances-e08",
        "subtopic_slug": "pure-substances",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what is meant by the melting range of a sample.",
        "options": [
            "The gap between the start and the finish of melting",
            "The gap between the melting point and the boiling point",
            "The number of degrees above the published value",
            "The time taken for the whole sample to melt fully",
        ],
        "correct_index": 0,
        "why": "The melting range runs from the temperature at which the first liquid "
               "appears to the temperature at which the last solid disappears.",
    },
    {
        "id": "ks4-pure-substances-e09",
        "subtopic_slug": "pure-substances",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Define the term mixture.",
        "options": [
            "Two or more elements chemically joined together",
            "A single compound built from two or more different elements",
            "A substance built from only one type of atom",
            "Two or more substances not chemically joined together",
        ],
        "correct_index": 3,
        "why": "The substances in a mixture are only mingled, so no chemical bonds join "
               "them and each keeps its own properties.",
    },
    {
        "id": "ks4-pure-substances-e10",
        "subtopic_slug": "pure-substances",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "A liquid boils steadily at one unchanging temperature. State what this shows about it.",
        "options": [
            "It is a pure substance rather than a mixture",
            "It is a mixture of two very similar liquids",
            "It is a solution of a solid dissolved evenly throughout water",
            "It is being heated far too quickly to measure",
        ],
        "correct_index": 0,
        "why": "A fixed, unchanging boiling temperature is the mark of a single element "
               "or compound.",
    },
    {
        "id": "ks4-pure-substances-e11",
        "subtopic_slug": "pure-substances",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the melting point of pure copper.",
        "options": [
            "419 °C",
            "660 °C",
            "1085 °C",
            "1538 °C",
        ],
        "correct_index": 2,
        "why": "Pure copper melts at 1085 °C; 1538 °C is iron, 660 °C is aluminium and "
               "419 °C is zinc.",
    },
    {
        "id": "ks4-pure-substances-e12",
        "subtopic_slug": "pure-substances",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State one advantage of using a melting point test to check purity.",
        "options": [
            "It measures the concentration of every impurity",
            "Only a very small sample of the solid is needed",
            "It works even on a sample that is still wet",
            "It names the substance with no data book needed",
        ],
        "correct_index": 1,
        "why": "A melting point determination needs only a few milligrams and takes a "
               "few minutes, which is why it is used so widely.",
    },
    # ── standard ────────────────────────────────────────────────────────
    {
        "id": "ks4-pure-substances-s08",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why an impurity lowers the melting point of a solid.",
        "options": [
            "The impurity reacts with the solid and weakens all of its bonds",
            "The impurity particles are heavier, so they need less energy to move",
            "The impurity absorbs heat, so the solid never reaches its true value",
            "The impurity disrupts the regular lattice, so less energy is needed",
        ],
        "correct_index": 3,
        "why": "Foreign particles break up the regular arrangement of the lattice, so the "
               "forces holding it together are overcome at a lower temperature.",
    },
    {
        "id": "ks4-pure-substances-s09",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Pure ethanol boils at 78 °C. A sample begins to boil at 80 °C and the temperature keeps rising as boiling continues. Explain what this shows.",
        "options": [
            "The sample is pure ethanol read with a badly calibrated thermometer",
            "The sample is a mixture, because boiling is spread over a range",
            "The sample is pure ethanol boiled at a lower than normal pressure",
            "The sample is a different pure liquid whose fixed boiling point is 80 °C",
        ],
        "correct_index": 1,
        "why": "A boiling temperature that drifts upwards shows more than one substance "
               "is present — the more volatile component leaves first.",
    },
    {
        "id": "ks4-pure-substances-s10",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how a chemist uses melting point apparatus to check whether a white solid is pure.",
        "options": [
            "Melt the whole sample quickly and record the highest temperature reached",
            "Heat the sample until it boils and record the temperature of the vapour",
            "Heat a small sample slowly and record the start and finish of melting",
            "Weigh the sample before and after heating and find the loss in mass",
        ],
        "correct_index": 2,
        "why": "The gap between the first drop of liquid and complete melting is what "
               "reveals impurity, so both temperatures must be recorded.",
    },
    {
        "id": "ks4-pure-substances-s11",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A bottle of a chemical is labelled '99.8% pure'. Explain why the contents are still not a pure substance in the chemical sense.",
        "options": [
            "0.2% is something else, and pure means nothing else is present",
            "A percentage purity can never be measured accurately enough to trust",
            "Purity is only about being safe to use, so a percentage figure means nothing at all",
            "The 0.2% is only water, and water never counts as an impurity",
        ],
        "correct_index": 0,
        "why": "A pure substance contains only one element or compound, so 0.2% of "
               "anything else makes it a mixture however small the proportion.",
    },
    {
        "id": "ks4-pure-substances-s12",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Silicon used to make computer chips is refined to extremely high purity. Explain why.",
        "options": [
            "Impurities would make the silicon melt at too high a temperature",
            "Impurities would make the silicon far too soft to cut into thin wafers",
            "Impurities would react with the silicon and turn it back into sand",
            "Impurities would disturb the electrical properties the chip relies on",
        ],
        "correct_index": 3,
        "why": "Semiconductor behaviour depends on the number of charge carriers, so even "
               "trace foreign atoms change how the chip conducts.",
    },
    {
        "id": "ks4-pure-substances-s13",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Tap water, distilled water and sea water are each heated until they boil. Predict which of them boils at the fixed value published for pure water.",
        "options": [
            "Tap water, because it has been treated and made safe to drink",
            "Distilled water, because it is one compound with nothing dissolved",
            "Sea water, because dissolved salt makes water boil sooner",
            "All three, because they are all water and water always behaves alike",
        ],
        "correct_index": 1,
        "why": "Only distilled water is a single compound; the dissolved solids in tap "
               "water and sea water raise the boiling point above the pure value.",
    },
    {
        "id": "ks4-pure-substances-s14",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student says stainless steel is pure because it contains no dirt. Explain why a chemist would disagree.",
        "options": [
            "Steel is a compound of iron and carbon, and compounds are not pure",
            "Steel is pure while it is solid but becomes a mixture once melted",
            "Steel is an alloy of several metals, so more than one element is there",
            "Steel rusts slowly in damp air, and a substance that reacts cannot be pure",
        ],
        "correct_index": 2,
        "why": "Stainless steel contains iron, chromium, nickel and carbon mixed "
               "together, so it is a mixture however clean it looks.",
    },
    {
        "id": "ks4-pure-substances-s15",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a measured boiling point should always be reported together with the pressure at which it was taken.",
        "options": [
            "Boiling point changes with pressure, so the value alone is incomplete",
            "Pressure changes the identity of the liquid, so the substance differs",
            "Pressure affects the thermometer reading rather than the liquid itself",
            "Boiling point changes with the volume of liquid placed in the flask",
        ],
        "correct_index": 0,
        "why": "A liquid boils when its vapour pressure equals the external pressure, so "
               "at lower pressure it boils at a lower temperature.",
    },
    {
        "id": "ks4-pure-substances-s16",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "One sample of a solid melts from 118 °C to 121 °C. A second sample of the same solid melts from 110 °C to 121 °C. Deduce which contains more impurity.",
        "options": [
            "The first, because its melting began at the higher of the two temperatures",
            "Neither, because both samples finished melting at 121 °C",
            "The first, because a narrow range always means more impurity",
            "The second, because its melting range is much wider",
        ],
        "correct_index": 3,
        "why": "More impurity depresses the start of melting further, so the wider the "
               "range the less pure the sample.",
    },
    {
        "id": "ks4-pure-substances-s17",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how melting point data can be used to identify an unknown white solid.",
        "options": [
            "Melt it and compare its colour with the colours in a data book",
            "Measure its melting point and compare it with published values",
            "Measure how long it takes to melt and compare that with a standard",
            "Melt it, let it set, and compare the crystals with reference crystals",
        ],
        "correct_index": 1,
        "why": "Each pure compound has a characteristic melting point, so a sharp value "
               "matching a published one points to that compound.",
    },
    {
        "id": "ks4-pure-substances-s18",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a melting point matching the data book does not by itself prove a sample is that substance.",
        "options": [
            "Data book values are measured at a pressure no school can reproduce",
            "Melting points drift over time, so old data book values are unusable",
            "Other compounds can share the same melting point, so more is needed",
            "A melting point only shows how pure a sample is and never which it is",
        ],
        "correct_index": 2,
        "why": "Different compounds can melt at the same temperature, so identification "
               "needs a second piece of evidence such as a chromatogram.",
    },
    {
        "id": "ks4-pure-substances-s19",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Antifreeze is added to the water in a car radiator. Explain, in terms of purity, why the liquid no longer freezes at 0 °C.",
        "options": [
            "The mixture is impure, and impurity lowers the freezing point",
            "The antifreeze coats the water and stops ice crystals touching it",
            "The antifreeze warms the water, so it never reaches 0 °C at all",
            "The mixture is impure, and impurity raises the freezing point",
        ],
        "correct_index": 0,
        "why": "Adding a second substance depresses the freezing point, so the coolant "
               "stays liquid well below 0 °C.",
    },
    {
        "id": "ks4-pure-substances-s20",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a pure substance has a fixed composition but a mixture does not.",
        "options": [
            "A mixture's particles are always moving, so its composition keeps shifting",
            "A mixture always contains water, and the amount of water varies",
            "A pure substance is always solid, so its composition cannot change",
            "A pure substance is one compound, so its elements are in a fixed ratio",
        ],
        "correct_index": 3,
        "why": "A compound's formula fixes the ratio of its elements, whereas the "
               "components of a mixture can be combined in any proportion.",
    },
    {
        "id": "ks4-pure-substances-s21",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Sugar sold for use in food must meet a purity standard. Suggest why.",
        "options": [
            "Pure sugar is sweeter, so less of it is needed in each product",
            "Impurities could affect the flavour and could be harmful to eat",
            "Pure sugar dissolves faster, so factories can work more quickly",
            "Impurities would make the sugar melt long before it ever reached the shops",
        ],
        "correct_index": 1,
        "why": "Food standards set purity limits because unwanted substances can change "
               "the taste and may be toxic.",
    },
    {
        "id": "ks4-pure-substances-s22",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Nitrogen gas, air and brass are compared. Identify which is a pure substance and justify the choice.",
        "options": [
            "Air, because the gases in it are mixed evenly all the way through",
            "Brass, because it is a single solid with one uniform appearance",
            "Nitrogen, because it contains only one type of element throughout",
            "All three, because none of them contains any visible impurity",
        ],
        "correct_index": 2,
        "why": "Nitrogen gas is a single element; air is a mixture of gases and brass is "
               "a mixture of copper and zinc.",
    },
    {
        "id": "ks4-pure-substances-s23",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student heats a solid slowly and finds it starts to melt at 96 °C and is fully molten at 97 °C. Explain what this suggests.",
        "options": [
            "It is close to pure, because the melting range is very narrow",
            "It is badly impure, because melting took two temperatures to state",
            "It is a mixture, because pure solids melt without any range at all",
            "It is impure, because a pure solid melts over a range of about 5 °C",
        ],
        "correct_index": 0,
        "why": "A range of about one degree is the mark of a nearly pure solid; impurity "
               "would spread melting over several degrees.",
    },
    {
        "id": "ks4-pure-substances-s24",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why heating a sample too quickly makes a melting point measurement unreliable.",
        "options": [
            "Fast heating decomposes the sample into two different compounds",
            "Fast heating drives off impurities, so the sample changes as it melts",
            "Fast heating melts the glass tube and lets the sample leak away",
            "The temperature passes the start and finish of melting too quickly",
        ],
        "correct_index": 3,
        "why": "The two temperatures that define the melting range go past before they can be read, so the range recorded is not the true one.",
    },
    {
        "id": "ks4-pure-substances-s25",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why 24 carat gold is a pure substance but 18 carat gold is not.",
        "options": [
            "24 carat gold has been cleaned, 18 carat still holds dirt",
            "24 carat gold is gold only, while 18 carat gold has other metals in it",
            "24 carat gold is a compound, 18 carat is an element",
            "24 carat gold is harder, and only hard metals are pure",
        ],
        "correct_index": 1,
        "why": "18 carat gold is an alloy containing about a quarter copper and silver, "
               "so more than one element is present.",
    },
    {
        "id": "ks4-pure-substances-s26",
        "subtopic_slug": "pure-substances",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe and explain the effect on the boiling point of water of dissolving salt in it.",
        "options": [
            "It falls, because the dissolved salt takes energy from the water",
            "It is unchanged, because only the water part of the mixture boils",
            "It rises, because the liquid is no longer a pure single substance",
            "It falls, because dissolved solids weaken the bonds between molecules",
        ],
        "correct_index": 2,
        "why": "Dissolved salt raises the boiling point — an impure liquid boils above "
               "the pure value, just as it melts below it.",
    },
    # ── harder ──────────────────────────────────────────────────────────
    {
        "id": "ks4-pure-substances-h07",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A chemist thinks a white solid is benzoic acid, which melts at 122 °C. She mixes a little of the solid with pure benzoic acid and the mixture melts from 110 °C to 118 °C. Deduce what this shows.",
        "options": [
            "The solid is benzoic acid, since mixing always lowers a value",
            "The solid is benzoic acid, since the mixture melted below 122 °C",
            "The solid is not benzoic acid, because mixing depressed the melting point",
            "The result proves nothing, since two solids cannot be melted",
        ],
        "correct_index": 2,
        "why": "Mixing two samples of the same compound leaves the sharp melting point "
               "unchanged; a depressed, widened range shows the added solid is an impurity.",
    },
    {
        "id": "ks4-pure-substances-h08",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a substance that decomposes on heating cannot have its purity checked by a melting point test.",
        "options": [
            "It breaks down before melting, so no true melting point exists",
            "Decomposition always happens at exactly the melting temperature",
            "The products of decomposition are always pure substances instead",
            "A decomposing solid melts at a sharp temperature every single time",
        ],
        "correct_index": 0,
        "why": "Many compounds char or break down below their melting temperature, so the "
               "thermometer never records a genuine melting point.",
    },
    {
        "id": "ks4-pure-substances-h09",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two colourless liquids each boil steadily at the same temperature at standard pressure. Suggest how a chemist could find out whether they are the same substance.",
        "options": [
            "Measure each melting point, since identical liquids melt differently",
            "Boil each one a second time, since a repeat reading settles it",
            "Warm each one gently, since the same substance always warms faster",
            "Compare a second property, such as density or an infrared spectrum",
        ],
        "correct_index": 3,
        "why": "One matching physical constant is not conclusive, so a second independent "
               "measurement is needed before the liquids can be called the same.",
    },
    {
        "id": "ks4-pure-substances-h10",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Water boils at 100 °C at sea level but at about 93 °C on a high mountain. Explain why this does not show that the water on the mountain is impure.",
        "options": [
            "The water is colder up there, so it needs less heat before it boils",
            "Boiling point depends on external pressure, which is lower up there",
            "Thermometers read low in thin air, so the true value is unchanged",
            "Impurity raises a boiling point, so 93 °C shows the water is purer",
        ],
        "correct_index": 1,
        "why": "Lower atmospheric pressure means the liquid's vapour pressure matches it "
               "sooner, and pure water still boils at a single fixed value there.",
    },
    {
        "id": "ks4-pure-substances-h11",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two different compounds each melt sharply at 145 °C. Predict the melting behaviour of a mixture made from equal masses of the two.",
        "options": [
            "It melts sharply at 145 °C, exactly as both components do",
            "It melts sharply at 290 °C, the sum of the two separate values",
            "It melts below 145 °C and over a range of temperatures",
            "It does not melt at all, because the two solids cancel each other out entirely",
        ],
        "correct_index": 2,
        "why": "Each compound acts as an impurity in the other, so the mixture melts "
               "lower and over a range even though both pure values are the same.",
    },
    {
        "id": "ks4-pure-substances-h12",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A drug batch of mass 200 g is found to be 99.5% pure. Calculate the mass of impurity in the batch.",
        "options": [
            "1.0 g",
            "0.5 g",
            "2.0 g",
            "199 g",
        ],
        "correct_index": 0,
        "why": "The impurity is 0.5% of the batch, and 200 × 0.5 ÷ 100 = 1.0 g.",
    },
    {
        "id": "ks4-pure-substances-h13",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 50 g sample of a compound is found to contain 0.40 g of impurity. Calculate the percentage purity of the sample.",
        "options": [
            "0.80%",
            "99.6%",
            "49.6%",
            "99.2%",
        ],
        "correct_index": 3,
        "why": "The impurity is 0.40 ÷ 50 × 100 = 0.80%, so the purity is 100 − 0.80 = 99.2%.",
    },
    {
        "id": "ks4-pure-substances-h14",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Ethanol boils at 78 °C and water at 100 °C. Explain why one simple distillation does not separate a mixture of the two completely.",
        "options": [
            "Ethanol and water react on heating to form a new single compound",
            "Some water evaporates alongside the ethanol below its boiling point",
            "Ethanol and water share the same boiling point once they are mixed",
            "The mixture boils at a fixed temperature, so nothing separates at all",
        ],
        "correct_index": 1,
        "why": "Water evaporates appreciably well below its boiling point, so the "
               "distillate is ethanol contaminated with water.",
    },
    {
        "id": "ks4-pure-substances-h15",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A solute dissolved in a liquid makes it freeze lower and boil higher than the pure liquid does. Explain both effects.",
        "options": [
            "Impurities always make a substance harder to heat in either direction",
            "Impurities add mass, so both changes of state simply take longer",
            "Impurities disrupt the solid lattice and hold back escaping vapour",
            "Impurities take in energy while freezing and give it out while boiling",
        ],
        "correct_index": 2,
        "why": "Foreign particles get in the way of the ordered solid forming, so it freezes "
               "lower, and they lower the vapour pressure, so it boils higher.",
    },
    {
        "id": "ks4-pure-substances-h16",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A liquid thought to be propanone boils at 56 °C, the published value, but leaves a solid residue when evaporated to dryness. Evaluate whether the liquid is pure.",
        "options": [
            "It is pure, because the boiling point matched the published value",
            "It is pure, because a residue forms whenever any liquid is evaporated",
            "It cannot be judged, because propanone always leaves a solid residue behind",
            "It is impure, because a pure liquid leaves nothing behind on evaporating",
        ],
        "correct_index": 3,
        "why": "A small amount of dissolved solid barely shifts the boiling point, so the "
               "residue is the stronger evidence and the liquid is not pure.",
    },
    {
        "id": "ks4-pure-substances-h17",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "One sample gives a melting range of 0.5 °C and another gives a range of 6 °C. Explain what the width of a melting range indicates.",
        "options": [
            "A narrow range means a purer sample, because impurity spreads melting",
            "A narrow range means a purer sample, because impurity sharpens melting",
            "A wide range means a purer sample, because pure solids melt gradually",
            "The width depends only on the mass of sample placed in the tube",
        ],
        "correct_index": 0,
        "why": "Impurity depresses the start of melting more than the finish, so the range "
               "widens in proportion to how impure the sample is.",
    },
    {
        "id": "ks4-pure-substances-h18",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Sea water freezes at about −2 °C. Explain why this is below the freezing point of pure water.",
        "options": [
            "The salt in sea water gives out heat as the water begins to freeze",
            "Sea water is a mixture, and dissolved salt depresses the freezing point",
            "Sea water is denser, and denser liquids always freeze at lower values",
            "Sea water is constantly moving, and moving water cannot freeze at all",
        ],
        "correct_index": 1,
        "why": "Dissolved ions interfere with the building of the ice lattice, so a lower "
               "temperature is needed before the water freezes.",
    },
    {
        "id": "ks4-pure-substances-h19",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a chemist reporting a newly made compound gives both a melting point and a chromatogram.",
        "options": [
            "A chromatogram measures a melting point more precisely than apparatus",
            "A melting point measures purity and a chromatogram measures mass",
            "One test suggests purity and the other shows how many substances are there",
            "Two tests are required by law before a new compound is reported",
        ],
        "correct_index": 2,
        "why": "A sharp melting point suggests purity, while a chromatogram showing a "
               "single spot supports it and would reveal a second component.",
    },
    {
        "id": "ks4-pure-substances-h20",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Copper for electrical wiring is refined to 99.99% purity. Suggest why such a high purity is needed.",
        "options": [
            "Impurities raise the resistance, so the wire would waste more energy",
            "Impurities would make the copper melt inside the wall of a house",
            "Impurities would make the copper corrode into copper oxide at once",
            "Impurities would stop the copper being drawn out into a wire at all",
        ],
        "correct_index": 0,
        "why": "Foreign atoms scatter the delocalised electrons, so even a small amount of "
               "impurity noticeably raises the resistance of a long cable.",
    },
    {
        "id": "ks4-pure-substances-h21",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student makes a compound, records a sharp melting point at the published value, but recovers only 40% of the mass expected. Evaluate what the two results together show.",
        "options": [
            "The product is impure and the reaction went almost to completion",
            "The product is impure and very little of the reaction took place",
            "Nothing can be judged, because yield and purity measure the same thing",
            "The product is pure and only part of the expected mass was made",
        ],
        "correct_index": 3,
        "why": "Percentage yield is about how much was made and percentage purity is about "
               "what it contains, so a small amount of very pure product is possible.",
    },
    {
        "id": "ks4-pure-substances-h22",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A 250 g sample of rock salt contains 247.5 g of sodium chloride. Calculate the percentage purity of the sample.",
        "options": [
            "97.5%",
            "99.0%",
            "2.5%",
            "1.0%",
        ],
        "correct_index": 1,
        "why": "247.5 ÷ 250 × 100 = 99.0%, so 1.0% of the rock salt is something other "
               "than sodium chloride.",
    },
    {
        "id": "ks4-pure-substances-h23",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A drug company must choose between a melting point test and chromatography for checking every batch it makes. Evaluate the two choices.",
        "options": [
            "Chromatography is cheaper and faster, so it should always be chosen",
            "A melting point is the only lawful test, so the choice is already made",
            "A melting point is quick and cheap, but chromatography detects far more",
            "Both give exactly the same information, so the cheaper one always wins",
        ],
        "correct_index": 2,
        "why": "A melting point screens a batch in minutes, while chromatography "
               "identifies individual impurities that a melting point would miss.",
    },
    {
        "id": "ks4-pure-substances-h24",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Pure iron melts at 1538 °C. Cast iron, which contains about 4% carbon, melts at about 1150 °C. Explain this difference.",
        "options": [
            "Cast iron is a mixture, and impurity lowers the melting point",
            "Carbon burns in the furnace and the heat released melts the iron",
            "Carbon atoms are lighter, so the mixture needs a much hotter furnace to melt",
            "Cast iron has been melted before, so it melts more easily each time",
        ],
        "correct_index": 0,
        "why": "Carbon atoms disrupt the regular iron lattice, so far less energy is "
               "needed to break it apart — the same depression any impurity causes.",
    },
    {
        "id": "ks4-pure-substances-h25",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "After recrystallisation a sample's melting range narrows from 118–126 °C to 124–126 °C. Deduce the effect of the process on the sample.",
        "options": [
            "It has converted the sample into a different compound entirely",
            "It has removed much of the impurity, leaving a purer sample behind",
            "It has added a solvent that raised the start of the melting range",
            "It has made the sample less pure, because the range moved upwards",
        ],
        "correct_index": 1,
        "why": "Recrystallisation leaves impurities behind in the solution, so the "
               "crystals melt over a narrower range closer to the true value.",
    },
    {
        "id": "ks4-pure-substances-h26",
        "subtopic_slug": "pure-substances",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Limestone from a quarry is 92% pure calcium carbonate. Calculate the mass of calcium carbonate in an 80 g sample.",
        "options": [
            "92.0 g",
            "86.4 g",
            "6.4 g",
            "73.6 g",
        ],
        "correct_index": 3,
        "why": "80 × 92 ÷ 100 = 73.6 g, so the other 6.4 g of the sample is other minerals.",
    },
]
