"""Chemistry · Chemical analysis — the MRB-338 expansion for
`carbonates-halides-sulfates`.

Three anion tests, and the thing students actually lose marks on is the
ACIDIFYING step: dilute nitric acid before silver nitrate (hydrochloric would
add the very ion being tested for) and dilute hydrochloric acid before barium
chloride (to destroy any carbonate that would give its own white solid). Those
two decisions, and the reasons behind them, carry a large share of the rows.

Around them sit the precipitate colours in order — chloride white, bromide
cream, iodide yellow — the white barium sulfate, effervescence and the
limewater confirmation, the ionic equations, mole arithmetic on the
precipitates, and the combined deductions that use a flame test or a hydroxide
precipitate alongside an anion test. Formulae are FLAT.
"""

TOPIC = "analysis"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": 'ks4-carbonates-halides-sulfates-e05',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the colour of silver chloride.',
        "options": [
            'White',
            'Cream',
            'Pale yellow',
            'Green',
        ],
        "correct_index": 0,
        "why": 'Silver chloride is white; cream is bromide and yellow is iodide.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-e06',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Name the acid used to acidify a sample before silver nitrate is added.',
        "options": [
            'Dilute sulfuric acid',
            'Dilute nitric acid',
            'Dilute hydrochloric acid',
            'Dilute ethanoic acid solution',
        ],
        "correct_index": 1,
        "why": 'Nitric acid removes interfering ions without adding a halide of its '
               'own, which hydrochloric acid would do.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-e07',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Silver chloride is the solid formed in the chloride test. State its formula.',
        "options": [
            'AgCl2',
            'Ag2Cl',
            'AgCl',
            'AgNO3',
        ],
        "correct_index": 2,
        "why": 'A silver ion is 1+ and a chloride ion is 1-, so they combine one to '
               'one as AgCl.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-e08',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the formula of the sulfate ion.',
        "options": [
            'SO3 2-',
            'SO4 -',
            'S 2-',
            'SO4 2-',
        ],
        "correct_index": 3,
        "why": 'A sulfate ion is one sulfur and four oxygen atoms carrying an '
               'overall 2- charge, which is why it pairs one to one with a 2+ '
               'barium ion.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-e09',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State what is seen immediately when dilute acid is added to a carbonate.',
        "options": [
            'The mixture fizzes as gas is given off',
            'A white solid forms and settles slowly',
            'The mixture turns a deep blue colour',
            'The solid dissolves away without any visible change',
        ],
        "correct_index": 0,
        "why": 'Effervescence is the first sign of a carbonate, and the gas is then '
               'confirmed with limewater.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-e10',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Silver ions meet bromide ions in solution. State the formula of the solid produced.',
        "options": [
            'AgBr2',
            'AgBr',
            'Ag2Br',
            'AgBr3',
        ],
        "correct_index": 1,
        "why": 'Bromide is a 1- ion like chloride, so the silver salt is AgBr.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-e11',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Name the term used for the fizzing seen when acid meets a carbonate.',
        "options": [
            'Condensation',
            'Precipitation',
            'Effervescence',
            'Evaporation',
        ],
        "correct_index": 2,
        "why": 'Effervescence is the release of bubbles of gas from a liquid, and '
               'here the gas is carbon dioxide.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-e12',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State why silver nitrate solution is handled with care.',
        "options": [
            'It boils at room temperature',
            'It gives off a flammable gas',
            'It freezes the skin on contact with it',
            'It stains skin and clothing badly',
        ],
        "correct_index": 3,
        "why": 'Silver nitrate leaves dark stains on skin and fabric and is an '
               'irritant, so gloves and eye protection are worn.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s05',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Sodium chloride solution is acidified and silver nitrate is added. State what is seen.',
        "options": [
            'A white precipitate appears in the tube',
            'A cream precipitate appears in the tube',
            'A yellow precipitate appears in the tube',
            'The mixture fizzes strongly and a gas is given off',
        ],
        "correct_index": 0,
        "why": 'Chloride ions give the white solid silver chloride with silver ions.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s06',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A solution gives a cream precipitate with acidified silver nitrate. Identify the ion present.',
        "options": [
            'Chloride',
            'Bromide',
            'Iodide',
            'Sulfate',
        ],
        "correct_index": 1,
        "why": 'Cream is the colour of silver bromide, sitting between the white of '
               'the chloride and the yellow of the iodide.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s07',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the ionic equation for the formation of the chloride precipitate.',
        "options": [
            'Ag2+ + 2Cl- to AgCl2',
            'Ag+ + 2Cl- to AgCl2',
            'Ag+ + Cl- to AgCl',
            'Ag+ + Cl2 to AgCl2',
        ],
        "correct_index": 2,
        "why": 'Both ions carry a single charge, so one of each combines to give '
               'the insoluble solid AgCl.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s08',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the ionic equation for the formation of the sulfate precipitate.',
        "options": [
            'Ba+ + SO4 2- to BaSO4',
            'Ba2+ + 2SO4 2- to Ba(SO4)2',
            'Ba2+ + SO4 - to BaSO4',
            'Ba2+ + SO4 2- to BaSO4',
        ],
        "correct_index": 3,
        "why": 'A 2+ barium ion and a 2- sulfate ion combine one to one to give the '
               'insoluble white solid BaSO4.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s09',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain the choice of nitric acid rather than hydrochloric acid in the halide test.',
        "options": [
            'Hydrochloric acid would add chloride ions to the sample',
            'Nitric acid is a stronger acid and works much faster',
            'Nitric acid dissolves silver nitrate better than water does',
            'Hydrochloric acid would react with the silver nitrate itself',
        ],
        "correct_index": 0,
        "why": 'Adding chloride would give a white precipitate whatever the sample '
               'contained, so the result would mean nothing.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s10',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Describe the full test for sulfate ions in a solution.',
        "options": [
            'Add dilute nitric acid, then silver nitrate solution',
            'Add dilute hydrochloric acid, then barium chloride solution',
            'Add dilute sulfuric acid, then barium chloride solution',
            'Add sodium hydroxide solution, then warm the mixture',
        ],
        "correct_index": 1,
        "why": 'The acid removes any carbonate first, so a white precipitate '
               'afterwards can only be barium sulfate.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s11',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why the gas released from a carbonate is passed through limewater.',
        "options": [
            'To remove the gas safely from the laboratory air',
            'To measure exactly how much gas has been produced',
            'To confirm that the gas given off is carbon dioxide',
            'To turn the gas back into a solid carbonate compound again',
        ],
        "correct_index": 2,
        "why": 'Fizzing alone only shows a gas; the limewater turning milky is what '
               'identifies it as carbon dioxide.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s12',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the word equation for sodium carbonate reacting with hydrochloric acid.',
        "options": [
            'sodium carbonate + hydrochloric acid to sodium chloride + hydrogen',
            'sodium carbonate + hydrochloric acid to sodium hydroxide + carbon dioxide',
            'sodium carbonate + dilute hydrochloric acid to sodium oxide + water + carbon dioxide',
            'sodium carbonate + hydrochloric acid to sodium chloride + water + carbon dioxide',
        ],
        "correct_index": 3,
        "why": 'A carbonate with an acid always gives a salt, water and carbon '
               'dioxide.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s13',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why a precipitate makes a better positive result than a faint colour change would.',
        "options": [
            'A solid appearing is unmistakable and does not depend on judgement',
            'A precipitate can be weighed but a colour change cannot',
            'A colour change happens too slowly to be seen in a lesson',
            'A precipitate forms with every ion, so nothing is ever missed',
        ],
        "correct_index": 0,
        "why": 'The appearance of a solid from two clear solutions is an '
               'unambiguous observation, and its colour then names the halide.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s14',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Potassium iodide solution is acidified with nitric acid and silver nitrate is added. Predict the observation.',
        "options": [
            'A white precipitate forms in the tube',
            'A yellow precipitate forms in the tube',
            'A cream precipitate forms in the tube',
            'No precipitate forms and the tube stays clear',
        ],
        "correct_index": 1,
        "why": 'Iodide ions give silver iodide, which is the yellow member of the '
               'three halide precipitates.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s15',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Barium compounds are toxic, yet barium sulfate is swallowed for a medical X-ray. Explain why this is safe.',
        "options": [
            'Barium sulfate is broken down in the stomach at once',
            'Barium sulfate contains far less barium than other salts',
            'Barium sulfate is insoluble, so it is not absorbed',
            'Barium sulfate is only harmful when it is breathed in',
        ],
        "correct_index": 2,
        "why": 'The same insolubility that makes barium sulfate a precipitate in '
               'the test keeps it out of the bloodstream in a patient.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s16',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A white solid could be a sulfate or a carbonate. State the single test that tells them apart.',
        "options": [
            'Add water: a carbonate dissolves and a sulfate does not',
            'Heat it: a sulfate melts and a carbonate stays solid',
            'Add silver nitrate: only a sulfate ever gives any precipitate at all',
            'Add acid: a carbonate fizzes and a sulfate does not',
        ],
        "correct_index": 3,
        "why": 'Effervescence with dilute acid separates the two at once, and '
               'barium chloride afterwards confirms the sulfate.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s17',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why acid is added before barium chloride in the sulfate test.',
        "options": [
            'The acid destroys any carbonate that would also give a white solid',
            'The acid makes the barium chloride dissolve in the water',
            'The acid speeds up a very slow reaction',
            'The acid changes the colour of the precipitate',
        ],
        "correct_index": 0,
        "why": 'Barium carbonate is white too, so without the acid a carbonate '
               'would be mistaken for a sulfate.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s18',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A solid fizzes with dilute acid but gives no precipitate with acidified silver nitrate. Deduce what it contains and what it does not.',
        "options": [
            'It contains a halide and contains no carbonate',
            'It contains a carbonate and contains no halide',
            'It contains both a carbonate and a halide ion at the same time',
            'It contains a sulfate and nothing else at all',
        ],
        "correct_index": 1,
        "why": 'Effervescence is the carbonate result, and the absence of any '
               'silver precipitate rules out chloride, bromide and iodide.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s19',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Give the name and the colour of the solid formed when bromide ions meet silver ions.',
        "options": [
            'Silver bromide, which is yellow',
            'Barium bromide, which is cream',
            'Silver bromide, which is cream',
            'Silver bromate, which is white',
        ],
        "correct_index": 2,
        "why": 'The compound is silver bromide, AgBr, and cream is its '
               'characteristic colour.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s20',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why an ionic equation is written for a precipitation rather than a full equation.',
        "options": [
            'It is shorter and so takes much less time to write out',
            'A full equation cannot be balanced for a precipitation',
            'It hides the spectator ions, which are not really present',
            'It shows only the ions that actually form the solid',
        ],
        "correct_index": 3,
        "why": 'The other ions stay dissolved and unchanged, so leaving them out '
               'shows what the reaction really is.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s21',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the order of the halide precipitate colours going down the group from chloride to iodide.',
        "options": [
            'White, then cream, then yellow',
            'Yellow, then cream, then white',
            'Cream, then white, then yellow',
            'White, then yellow, and then cream last',
        ],
        "correct_index": 0,
        "why": 'Silver chloride is white, silver bromide cream and silver iodide '
               'yellow, deepening steadily down the group.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s22',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Describe how a sample of limestone could be shown to contain carbonate ions.',
        "options": [
            'Add silver nitrate and look for a white precipitate',
            'Add dilute acid and pass the gas into limewater',
            'Add barium chloride and look for a white precipitate',
            'Add sodium hydroxide and warm the mixture gently',
        ],
        "correct_index": 1,
        "why": 'Limestone is mostly calcium carbonate, so it fizzes with acid and '
               'the gas turns limewater milky.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s23',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A solution gives no precipitate at all with acidified silver nitrate. State what this shows.',
        "options": [
            'No metal ions of any kind are present in it',
            'The solution must have been acidified too strongly',
            'No chloride, bromide or iodide ions are present',
            'The solution contains a sulfate ion instead',
        ],
        "correct_index": 2,
        "why": 'The reagent precipitates all three halides, so a clear tube rules '
               'out each of them and says nothing about any other ion.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s24',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Barium chloride is added to magnesium sulfate solution that has been acidified. Predict the observation.',
        "options": [
            'A cream precipitate of barium bromide appears',
            'The mixture fizzes and a gas is given off',
            'No change is seen because both salts dissolve',
            'A white precipitate of barium sulfate appears',
        ],
        "correct_index": 3,
        "why": 'The sulfate ion is present whatever metal it came from, so barium '
               'sulfate precipitates.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s25',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why these three tests are described as tests for the negative ion.',
        "options": [
            'The precipitate or gas comes from the negative ion in each',
            'The metal ion is removed by the acid before the test starts',
            'Negative ions are the only ions that form precipitates at all',
            'The tests work only on compounds that have no metal in them',
        ],
        "correct_index": 0,
        "why": 'Silver, barium and the acid all react with the anion, so the metal '
               'ion needs a flame test or a hydroxide test of its own.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-s26',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Describe the sequence a chemist follows to identify an unknown white solid completely.',
        "options": [
            'Test only for the negative ion, since that names the compound',
            'Identify the metal ion first, then test for the negative ion',
            'Weigh the solid, then heat it and weigh it a second time',
            'Measure its melting point and look the value up in a book',
        ],
        "correct_index": 1,
        "why": 'A compound is both ions together, so a flame or hydroxide test and '
               'an anion test are both needed before it can be named.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h05',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Cream and yellow precipitates can be hard to tell apart by eye. Suggest what a chemist should do about this.',
        "options": [
            'Record whichever colour seems the more likely of the two',
            'Add more silver nitrate until the colour becomes deeper',
            'Run known bromide and iodide samples alongside for comparison',
            'Leave the tube overnight so the colour has time to develop fully',
        ],
        "correct_index": 2,
        "why": 'Side by side under the same light and conditions, the two colours '
               'are far easier to separate than either is on its own.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h06',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Calculate the mass of barium sulfate precipitated from 0.020 mol of sulfate ions. Mr of BaSO4 = 233.',
        "options": [
            '2.33 g',
            '23.3 g',
            '0.47 g',
            '4.66 g',
        ],
        "correct_index": 3,
        "why": '0.020 mol of sulfate gives 0.020 mol of BaSO4, and 0.020 × 233 = '
               '4.66 g.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h07',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Sulfur dioxide also turns limewater milky. Explain the problem this creates for the carbonate test.',
        "options": [
            'A sulfite would give the same result and be read as a carbonate',
            'The limewater would be used up before the carbon dioxide arrived',
            'Sulfur dioxide dissolves the precipitate as fast as it forms',
            'The gas would escape before it could reach the limewater at all',
        ],
        "correct_index": 0,
        "why": 'Both gases give a white solid with limewater, so a milky result '
               'confirms carbon dioxide only once a sulfite has been ruled out.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h08',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Determine the ionic equation for a carbonate ion reacting with acid.',
        "options": [
            'CO3 2- + H+ to H2O + CO2',
            'CO3 2- + 2H+ to H2O + CO2',
            'CO3 2- + 2H+ to 2H2O + CO2',
            'CO3 2- + 2OH- to H2O + CO2',
        ],
        "correct_index": 1,
        "why": 'Two hydrogen ions balance the 2- charge and give one water molecule '
               'and one carbon dioxide molecule.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h09',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A student adds barium chloride without acidifying and gets a white solid that then fizzes when acid is added. Deduce what was present.',
        "options": [
            'A sulfate, since barium sulfate is the white solid formed',
            'A chloride, since silver nitrate solution was not needed to precipitate it',
            'A carbonate, since barium carbonate reacts with the acid',
            'Both a sulfate and a chloride were present together',
        ],
        "correct_index": 2,
        "why": 'Barium sulfate does not react with dilute acid, so a white solid '
               'that fizzes must have been barium carbonate.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h10',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why acidified silver nitrate gives no precipitate with a solution of sodium nitrate.',
        "options": [
            'Sodium ions react with the nitric acid that was added first',
            'Nitrate ions are too large to react with any silver ion',
            'The sodium prevents the silver reaching the nitrate ions',
            'Silver nitrate is itself soluble, so nothing can come out',
        ],
        "correct_index": 3,
        "why": 'A precipitate needs an insoluble product, and every common nitrate '
               'is soluble, so there is no halide present to give one.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h11',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Evaluate the claim that a white precipitate with silver nitrate proves that chloride is present.',
        "options": [
            'Unsafe unless the sample was acidified with nitric acid first',
            'Sound, because no other ion ever gives a white silver precipitate at all',
            'Sound, because acidifying makes no difference to the result',
            'Unsafe, because bromide also gives a white precipitate here',
        ],
        "correct_index": 0,
        "why": 'Carbonate and sulfate both give silver precipitates of their own, so without acidifying first the result does not identify chloride.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h12',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Calculate the mass of silver chloride precipitated from 0.010 mol of chloride ions. Mr of AgCl = 143.5.',
        "options": [
            '14.4 g',
            '1.44 g',
            '0.72 g',
            '2.87 g',
        ],
        "correct_index": 1,
        "why": '0.010 mol of chloride gives 0.010 mol of AgCl, and 0.010 × 143.5 = '
               '1.44 g to three significant figures.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h13',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why the carbonate test can be done on a solid but the halide test needs a solution.',
        "options": [
            'A solid carbonate is always soluble and a solid halide never is',
            'Silver nitrate is a solid too, so two solids cannot be mixed',
            'Acid attacks a solid carbonate, but ions must meet in solution',
            'The halide test needs heat, which a solution provides evenly',
        ],
        "correct_index": 2,
        "why": 'Precipitation requires free ions, so the sample must dissolve, '
               'whereas acid reacts with a carbonate at the surface of the solid.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h14',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A compound gives a blue precipitate with sodium hydroxide and a white precipitate with acidified barium chloride. Deduce the compound.',
        "options": [
            'Copper(II) chloride',
            'Iron(II) sulfate',
            'Barium sulfate',
            'Copper(II) sulfate',
        ],
        "correct_index": 3,
        "why": 'Blue names copper(II) and the white barium precipitate names '
               'sulfate, so the compound is copper(II) sulfate.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h15',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why dilute rather than concentrated acid is used to acidify a sample before an anion test.',
        "options": [
            'Dilute acid is enough to do the job and far safer to use',
            'Concentrated acid would not react with a carbonate at all',
            'Dilute acid dissolves the precipitate once it has formed',
            'Concentrated acid changes the colour of every precipitate',
        ],
        "correct_index": 0,
        "why": 'Only a small excess of hydrogen ions is needed to remove the '
               'interfering ion, and concentrated acid adds hazard for no benefit.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h16',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": '0.030 mol of chloride ions is precipitated completely as silver chloride. Calculate the moles of silver ions used.',
        "options": [
            '0.015 mol',
            '0.030 mol',
            '0.060 mol',
            '0.090 mol',
        ],
        "correct_index": 1,
        "why": 'Silver and chloride combine one to one, so 0.030 mol of chloride '
               'needs 0.030 mol of silver ions.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h17',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Compare the carbonate test with the sulfate test, stating what is the same and what differs.',
        "options": [
            'Both begin with acid, and neither needs a second reagent after it',
            'Both give a gas, but one needs limewater and one needs barium',
            'Both begin with acid, but one gives a gas and one a solid',
            'Both need silver nitrate, but the colours of the solids differ',
        ],
        "correct_index": 2,
        "why": 'Dilute hydrochloric acid starts each, but the carbonate result is '
               'effervescence and the sulfate result is a white precipitate.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h18',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why an anion test and a flame test are both needed before a compound can be named.',
        "options": [
            'One test is unreliable, so a second is a check',
            'The flame test finds the anion and the other the metal',
            'Two tests are needed because acid destroys one',
            'A compound has a positive and a negative ion, and each needs a test',
        ],
        "correct_index": 3,
        "why": "Neither test sees the other's ion, so only the two together give "
               "both halves of the compound's name.",
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h19',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A white solid gives no flame colour, fizzes with dilute acid, and gives a white precipitate with sodium hydroxide that stays in excess. Deduce the compound.',
        "options": [
            'Magnesium carbonate',
            'Calcium carbonate',
            'Aluminium hydroxide',
            'Sodium carbonate',
        ],
        "correct_index": 0,
        "why": 'Calcium would have given an orange-red flame and aluminium would '
               'have dissolved in excess alkali, so the metal ion is magnesium.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h20',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Evaluate whether the halide test could distinguish sodium chloride from potassium chloride.',
        "options": [
            'Yes, because sodium and potassium give different precipitates',
            'No, because the test responds to the chloride ion in both',
            'Yes, because potassium chloride gives no precipitate at all',
            'No, because neither compound dissolves well enough to test',
        ],
        "correct_index": 1,
        "why": 'Both give the same white silver chloride, so a flame test is what '
               'separates the two metal ions.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h21',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Calcium carbonate is added to dilute nitric acid. Determine the balanced symbol equation.',
        "options": [
            'CaCO3 + HNO3 to CaNO3 + H2O + CO2',
            'CaCO3 + 2HNO3 to Ca(NO3)2 + H2 + CO2',
            'CaCO3 + 2HNO3 to Ca(NO3)2 + H2O + CO2',
            'CaCO3 + 3HNO3 to Ca(NO3)3 + H2O + CO2',
        ],
        "correct_index": 2,
        "why": 'Calcium forms a 2+ ion, so two nitrate ions are needed, and the '
               'carbonate becomes water and carbon dioxide.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h22',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why a solid sample must be dissolved before the sulfate test is carried out.',
        "options": [
            'A solid would react with the acid and be destroyed too soon',
            'Barium chloride will only react with a substance that is warm',
            'A solid sample would settle and hide any precipitate formed',
            'The sulfate ions must be free in solution to meet barium ions',
        ],
        "correct_index": 3,
        "why": 'Precipitation is a reaction between dissolved ions, so ions held in '
               'a solid lattice cannot take part.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h23',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why a chemist carries out each anion test on a fresh portion of the sample.',
        "options": [
            'A reagent added earlier would interfere with the next test',
            'A sample loses its ions within a few minutes of being made',
            'Each test needs the sample at a different temperature',
            'Using one portion would leave nothing to send for checking',
        ],
        "correct_index": 0,
        "why": 'Chloride added for the sulfate test, or barium added earlier, would '
               'give a false result in a test done on the same portion afterwards.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h24',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Acidified barium chloride gives a white solid with a solution, while acidified silver nitrate gives none. Deduce the ions present and absent.',
        "options": [
            'Chloride is present and the sulfate is absent',
            'Sulfate is present and the halides are all absent',
            'Carbonate is present and the sulfate ion is absent',
            'Sulfate and chloride are both present together',
        ],
        "correct_index": 1,
        "why": 'The barium result is positive for sulfate and the silver result is '
               'negative for all three halides.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h25',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why a result is recorded as a white precipitate rather than as the solution turning cloudy.',
        "options": [
            'Cloudiness always fades, whereas a precipitate is permanent',
            'A precipitate can be seen and cloudiness cannot be seen at all',
            'Naming the solid says what formed, which cloudiness does not',
            'The two words mean the same thing, so either one may be written down',
        ],
        "correct_index": 2,
        "why": 'The observation that earns credit identifies a solid product of the '
               'reaction, which is the evidence the test depends on.',
    },
    {
        "id": 'ks4-carbonates-halides-sulfates-h26',
        "subtopic_slug": 'carbonates-halides-sulfates',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": '0.050 mol of calcium carbonate reacts fully with dilute acid. Determine the mass of gas released. Mr of CO2 = 44.',
        "options": [
            '1.1 g',
            '4.4 g',
            '22 g',
            '2.2 g',
        ],
        "correct_index": 3,
        "why": 'Each mole of carbonate releases one mole of carbon dioxide, so '
               '0.050 × 44 = 2.2 g.',
    },
]
