"""Chemistry · Chemical analysis — the MRB-338 expansion for `instrumental-methods`.

Flame emission spectroscopy carries most of the weight, because it is the one
instrumental method AQA asks students to describe: sample in solution, into a
flame, electrons excited, light through a grating, a spectrum whose LINE
POSITION gives the element and whose LINE INTENSITY gives the concentration.

Around it sit the wavelengths (sodium 589 nm, lithium 671 nm, calcium 422 and
616 nm), the advantages and disadvantages taken one at a time rather than as a
list, calibration and proportional intensity, and the honest comparison with a
chemical test — an instrument is more sensitive and objective, and it is also
expensive, needs a trained operator and does not travel to a river bank.
"""

TOPIC = "analysis"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": 'ks4-instrumental-methods-e05',
        "subtopic_slug": 'instrumental-methods',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Visible light runs from about 400 nm at the violet end to about 700 nm at the red end. The sodium emission line is yellow. State its wavelength.',
        "options": [
            '589 nm',
            '404 nm',
            '671 nm',
            '422 nm',
        ],
        "correct_index": 0,
        "why": 'Yellow light lies a little past the middle of the visible range, and 589 nm is the only option there; 404 nm and 422 nm are violet and 671 nm is red.',
    },
    {
        "id": 'ks4-instrumental-methods-e06',
        "subtopic_slug": 'instrumental-methods',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State the unit normally used for the wavelength of a spectral line.',
        "options": [
            'Millimetres',
            'Nanometres',
            'Micrograms per litre of solution',
            'Millilitres',
        ],
        "correct_index": 1,
        "why": 'Visible light has wavelengths of a few hundred nanometres, so nm is '
               'the convenient unit for a spectral line.',
    },
    {
        "id": 'ks4-instrumental-methods-e07',
        "subtopic_slug": 'instrumental-methods',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State what the intensity of a spectral line shows.',
        "options": [
            'Which element the sample contains',
            'How hot the flame was at the time of the run',
            'How much of that element is present',
            'How pure the water in the sample was',
        ],
        "correct_index": 2,
        "why": 'The position of a line identifies the element and its brightness '
               'measures how much of that element is there.',
    },
    {
        "id": 'ks4-instrumental-methods-e08',
        "subtopic_slug": 'instrumental-methods',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State what an emission spectrum is.',
        "options": [
            'A graph of temperature against time for a flame',
            'A list of every element in the periodic table',
            'A measure of how bright a flame appears to be',
            'A pattern of lines at particular wavelengths',
        ],
        "correct_index": 3,
        "why": 'A spectrum is the display of which wavelengths of light a sample '
               'gives out, drawn as a set of separate lines.',
    },
    {
        "id": 'ks4-instrumental-methods-e09',
        "subtopic_slug": 'instrumental-methods',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State what a mass spectrometer measures in order to identify a particle.',
        "options": [
            'Its mass',
            'Its colour',
            'Its melting point',
            'Its wavelength',
        ],
        "correct_index": 0,
        "why": 'A mass spectrometer separates particles according to their mass, '
               'and the mass is what names the molecule.',
    },
    {
        "id": 'ks4-instrumental-methods-e10',
        "subtopic_slug": 'instrumental-methods',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State whether flame emission spectroscopy gives qualitative results, quantitative results, or both.',
        "options": [
            'Qualitative results only',
            'Both kinds of result',
            'Quantitative results only',
            'Neither kind of result at all',
        ],
        "correct_index": 1,
        "why": 'It names the element from the line positions and measures how much '
               'is present from the line intensities.',
    },
    {
        "id": 'ks4-instrumental-methods-e11',
        "subtopic_slug": 'instrumental-methods',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State one reason why instrumental analysis is costly for a laboratory.',
        "options": [
            'The results must be checked by a second laboratory',
            'The results take several weeks to appear',
            'Trained operators are needed to run it',
            'Only one element at a time can ever be measured by it',
        ],
        "correct_index": 2,
        "why": 'The instrument itself is expensive and it also needs skilled staff '
               'and regular calibration, which add to the running cost.',
    },
    {
        "id": 'ks4-instrumental-methods-e12',
        "subtopic_slug": 'instrumental-methods',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State what must be done to a solid sample before flame emission spectroscopy.',
        "options": [
            'It must be heated until it melts fully',
            'It must be ground down into a very fine dry powder first',
            'It must be weighed to the nearest gram',
            'It must be dissolved to make a solution',
        ],
        "correct_index": 3,
        "why": 'The solution is drawn into the flame as a fine spray, so the sample '
               'has to be in solution first.',
    },
    {
        "id": 'ks4-instrumental-methods-s05',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Describe what happens to the sample at the start of flame emission spectroscopy.',
        "options": [
            'It is drawn as a fine spray into a hot flame',
            'It is burned in a crucible and the ash is collected',
            'It is placed on a wire loop and held in the flame',
            'It is passed through a grating before the flame',
        ],
        "correct_index": 0,
        "why": 'Spraying the solution in gives a steady supply of ions to the '
               'flame, which is what makes the emission steady enough to measure.',
    },
    {
        "id": 'ks4-instrumental-methods-s06',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why the light from the flame is passed through a diffraction grating.',
        "options": [
            'To make the light brighter before it reaches the detector',
            'To separate the light into the wavelengths it contains',
            'To remove any light that comes from the flame itself as well',
            'To focus all of the light onto a single small point',
        ],
        "correct_index": 1,
        "why": 'Splitting the light lets the instrument measure each wavelength on '
               'its own, which is how several elements can be read from one sample.',
    },
    {
        "id": 'ks4-instrumental-methods-s07',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Reference emission lines: lithium 671 nm, sodium 589 nm, calcium 422 nm, copper 325 nm. A spectrum from a water sample shows a line at 671 nm. Identify the element present.',
        "options": [
            'Sodium',
            'Calcium',
            'Lithium',
            'Copper',
        ],
        "correct_index": 2,
        "why": '671 nm matches the reference line given for lithium, and none of the other elements listed emits there.',
    },
    {
        "id": 'ks4-instrumental-methods-s08',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Calcium emits at 422 nm and at 616 nm, sodium at 589 nm, magnesium at 285 nm and copper at 325 nm. A sample gives peaks at 422 nm and 616 nm. Name the element it contains.',
        "options": [
            'Sodium',
            'Magnesium',
            'Copper',
            'Calcium',
        ],
        "correct_index": 3,
        "why": 'Both peaks match the pair of wavelengths given for calcium, and matching a whole pattern is firmer evidence than matching a single line.',
    },
    {
        "id": 'ks4-instrumental-methods-s09',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why a spectrum showing several sets of lines indicates several elements.',
        "options": [
            'Each element produces its own pattern of lines',
            'Each line is produced by one atom in the sample',
            'More lines always means the sample was more concentrated',
            'Extra lines appear whenever the flame is made hotter',
        ],
        "correct_index": 0,
        "why": 'Wavelengths depend on the spacing of the energy levels in that '
               'element, so a second pattern means a second element is present.',
    },
    {
        "id": 'ks4-instrumental-methods-s10',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why an instrument analyses a batch of samples faster than a set of chemical tests would.',
        "options": [
            'The instrument works at a much higher temperature',
            'Each sample is measured automatically in seconds',
            'Chemical tests must always be repeated three separate times over',
            'The instrument tests fewer elements in each sample',
        ],
        "correct_index": 1,
        "why": 'Once calibrated, the machine reads sample after sample without a '
               'chemist setting up separate apparatus for each test.',
    },
    {
        "id": 'ks4-instrumental-methods-s11',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why an instrumental method can work with a much smaller sample than a chemical test.',
        "options": [
            'Instruments use the whole sample rather than only part',
            'Small samples give brighter lines than large samples do',
            'A detector responds to far less material than the eye can',
            'Chemical tests need a large sample to be safe to carry out',
        ],
        "correct_index": 2,
        "why": 'A chemical test must produce a change a person can see, whereas a '
               'detector registers emission far below that level.',
    },
    {
        "id": 'ks4-instrumental-methods-s12',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Describe how a calibration graph is used to find the concentration of an unknown sample.',
        "options": [
            'Measure its concentration and read the intensity off the graph',
            'Compare its colour with the colours plotted on the graph',
            'Count how many lines it gives and read that off the graph',
            'Measure its intensity and read the concentration off the graph',
        ],
        "correct_index": 3,
        "why": 'The graph of intensity against known concentration converts a '
               'measured intensity into a concentration for any sample run the same '
               'way.',
    },
    {
        "id": 'ks4-instrumental-methods-s13',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why an instrument gives the same result whoever is operating it.',
        "options": [
            'The instrument measures a number rather than judging a colour',
            'The operator is trained to give the same answer too',
            'Instruments are checked by two chemists',
            'The sample changes little between runs',
        ],
        "correct_index": 0,
        "why": "A measured wavelength and intensity do not depend on the operator's "
               'eyesight or judgement, which is what makes the method objective.',
    },
    {
        "id": 'ks4-instrumental-methods-s14',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why a farmer sends soil samples away for instrumental analysis.',
        "options": [
            'To find the total mass of soil present in the whole field',
            'To find how much of each mineral nutrient the soil holds',
            'To find out which crops were grown in that same field in the last year',
            'To find whether the soil contains any water at all',
        ],
        "correct_index": 1,
        "why": 'Knowing the concentration of each nutrient tells the farmer which '
               'fertiliser formulation the field actually needs.',
    },
    {
        "id": 'ks4-instrumental-methods-s15',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why instrumental methods are used to monitor metal levels in rivers.',
        "options": [
            'They can be carried out by anyone without any training',
            'They work only on water and not on any other liquid',
            'They detect very small concentrations and measure them',
            'They change the water so pollution is removed as well',
        ],
        "correct_index": 2,
        "why": 'Pollution matters at levels of a few parts per million, far below '
               'anything a colour change would reveal.',
    },
    {
        "id": 'ks4-instrumental-methods-s16',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State what infrared spectroscopy is used to identify in a molecule.',
        "options": [
            'The metal ions in it',
            'Its total mass',
            'Its colour',
            'The functional groups it contains',
        ],
        "correct_index": 3,
        "why": 'Different bonds absorb infrared radiation at different frequencies, '
               'so the spectrum reveals which functional groups are present.',
    },
    {
        "id": 'ks4-instrumental-methods-s17',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'State what gas chromatography does to a mixture.',
        "options": [
            'It separates the mixture into its components',
            'It converts the mixture into a single compound',
            'It measures the total mass of the whole mixture',
            'It removes every component except the largest one',
        ],
        "correct_index": 0,
        "why": 'Like paper chromatography it separates the components, and it is '
               'often joined to a mass spectrometer that then identifies each one.',
    },
    {
        "id": 'ks4-instrumental-methods-s18',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why a flame emission spectrometer needs a flame at all.',
        "options": [
            'The flame burns away the water from the sample first',
            'The flame supplies energy that excites the electrons',
            'The flame provides the light that the sample reflects',
            'The flame keeps the detector warm enough to work',
        ],
        "correct_index": 1,
        "why": 'No light is emitted until electrons have been raised to higher '
               'energy levels, and the flame is where that energy comes from.',
    },
    {
        "id": 'ks4-instrumental-methods-s19',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why the wavelengths emitted are characteristic of one particular element.',
        "options": [
            'Each element burns at its own particular temperature',
            'Each element is present at its own concentration',
            'Each element has its own spacing of energy levels',
            'Each element absorbs a different colour of light from the flame',
        ],
        "correct_index": 2,
        "why": 'The energy given out as an electron falls equals the gap it falls '
               'across, and those gaps differ from element to element.',
    },
    {
        "id": 'ks4-instrumental-methods-s20',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why a school laboratory does not usually own a flame emission spectrometer.',
        "options": [
            'The instrument is not accurate enough for school work',
            'The instrument cannot be used on ordinary tap water',
            'The instrument is banned from use by school pupils',
            'The instrument is expensive to buy and to maintain',
        ],
        "correct_index": 3,
        "why": 'Cost, maintenance and the need for a trained operator are the '
               'practical disadvantages that keep instrumental methods out of most '
               'schools.',
    },
    {
        "id": 'ks4-instrumental-methods-s21',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why instrumental analysis has become far more widely used in recent decades.',
        "options": [
            'Instruments became cheaper, faster and more reliable',
            'Chemical tests were found to give the wrong answers',
            'Governments made chemical testing against the law',
            'Chemists stopped being trained in practical work',
        ],
        "correct_index": 0,
        "why": 'Better electronics and computing have made instruments cheaper and '
               'easier to run, so they have replaced chemical tests in many '
               'laboratories.',
    },
    {
        "id": 'ks4-instrumental-methods-s22',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A water company reports 12 mg of sodium per litre. Explain which feature of the spectrum gave that figure.',
        "options": [
            'The position of the sodium line along the spectrum',
            'The intensity of the sodium line in the spectrum',
            'The number of lines the sodium produced in total',
            'The width of the sodium line across the spectrum',
        ],
        "correct_index": 1,
        "why": 'Position identifies the element; a concentration can only come from '
               'how bright the line is, read against a calibration.',
    },
    {
        "id": 'ks4-instrumental-methods-s23',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why a measured spectrum is compared with reference spectra.',
        "options": [
            'The reference makes the measured lines much brighter to read',
            'The reference removes any lines caused by the flame itself',
            'The reference tells the chemist which element the lines match',
            'The reference shows how long the measurement should take',
        ],
        "correct_index": 2,
        "why": 'Identification means matching the pattern of wavelengths against '
               'known patterns already recorded for each element.',
    },
    {
        "id": 'ks4-instrumental-methods-s24',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Describe one advantage of using instrumental analysis to check the mineral content of a food.',
        "options": [
            'It tells the manufacturer how the food will taste',
            'It removes any minerals that should not be there',
            'It works without needing a sample of the food',
            'It measures how much of each mineral is present',
        ],
        "correct_index": 3,
        "why": 'A nutrition label has to state quantities, so a quantitative method '
               'is the only kind that can support it.',
    },
    {
        "id": 'ks4-instrumental-methods-s25',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain what is meant by saying an instrumental method is more sensitive than a chemical test.',
        "options": [
            'It detects a much smaller amount of the substance',
            'It is more easily damaged by rough handling',
            'It responds more quickly to a change in temperature',
            'It needs a more careful operator to run it properly',
        ],
        "correct_index": 0,
        "why": 'Sensitivity is about the smallest quantity that can be detected, '
               'and instruments reach parts per million or better.',
    },
    {
        "id": 'ks4-instrumental-methods-s26',
        "subtopic_slug": 'instrumental-methods',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why a scientist testing water at a river bank may still use a chemical test kit.',
        "options": [
            'A chemical test gives a more accurate concentration',
            'The instrument is not portable and needs mains power',
            'A chemical test can measure parts per billion easily',
            'The instrument would be damaged by ordinary river water',
        ],
        "correct_index": 1,
        "why": 'Portability is a genuine advantage of a simple chemical test, even '
               'though the instrument in the laboratory is far more sensitive.',
    },
    {
        "id": 'ks4-instrumental-methods-h05',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why the intensity of an emission line increases as the concentration of the element increases.',
        "options": [
            'Each ion emits more strongly when others are nearby',
            'A concentrated solution is drawn into the flame faster',
            'More ions are in the flame, so more light is emitted',
            'Higher concentration shifts the line to a brighter colour',
        ],
        "correct_index": 2,
        "why": 'Every excited ion contributes light of the same wavelength, so the '
               'total emitted at that wavelength rises with the number present.',
    },
    {
        "id": 'ks4-instrumental-methods-h06',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A calibration graph is a straight line through the origin. A sample gives half the intensity of a 20 mg per dm3 standard. Determine its concentration.',
        "options": [
            '5 mg per dm3',
            '20 mg per dm3',
            '40 mg per dm3',
            '10 mg per dm3',
        ],
        "correct_index": 3,
        "why": 'Intensity is proportional to concentration, so half the intensity '
               'means half the concentration: 20 ÷ 2 = 10 mg per dm3.',
    },
    {
        "id": 'ks4-instrumental-methods-h07',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why a spectrum records both the position and the brightness of each line.',
        "options": [
            'Position gives the element and brightness gives the amount',
            'Position gives the amount and brightness gives the element',
            'Both are needed only to check that the instrument works',
            'Position gives the element and brightness gives the temperature',
        ],
        "correct_index": 0,
        "why": 'The two measurements answer the two different questions, which is '
               'why one run is both a qualitative and a quantitative analysis.',
    },
    {
        "id": 'ks4-instrumental-methods-h08',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": "A sample's sodium line is three times as intense as that of a 5.0 mg per dm3 standard. Determine the concentration of sodium in the sample.",
        "options": [
            '1.7 mg per dm3',
            '15 mg per dm3',
            '8.0 mg per dm3',
            '5.0 mg per dm3',
        ],
        "correct_index": 1,
        "why": 'Intensity is proportional to concentration, so 5.0 × 3 = 15 mg per '
               'dm3.',
    },
    {
        "id": 'ks4-instrumental-methods-h09',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Identify the statement that is true of flame emission spectroscopy but not of a visual flame test.',
        "options": [
            'It uses a flame to supply energy to the sample',
            'It identifies the metal ion rather than the negative ion',
            'It gives a numerical measure of how much is present',
            'It can be carried out with a Bunsen burner and a nichrome wire',
        ],
        "correct_index": 2,
        "why": 'Both use a flame and both look at the metal ion, and a burner and wire are the flame test itself; only the instrument returns a quantity.',
    },
    {
        "id": 'ks4-instrumental-methods-h10',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Evaluate whether a hospital should buy a spectrometer for measuring electrolytes in blood.',
        "options": [
            'No, because a flame test would give the same information',
            'No, because blood cannot be analysed by any instrument',
            'Yes, because it is the cheapest method available to a hospital',
            'Yes, because the numbers it gives are needed to treat patients',
        ],
        "correct_index": 3,
        "why": 'Treatment depends on how far a sodium or potassium level is from '
               'normal, which only a quantitative method can supply.',
    },
    {
        "id": 'ks4-instrumental-methods-h11',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why a simple chemical test may still be preferred for a quick check on a factory floor.',
        "options": [
            'It is quick, cheap and needs no specialist equipment',
            'It gives a more precise concentration than an instrument',
            'It detects far smaller quantities than an instrument does',
            'It removes the need for any trained staff in the factory',
        ],
        "correct_index": 0,
        "why": "When the question is only 'is it present', a test costing pennies "
               'and answering in seconds is the sensible choice.',
    },
    {
        "id": 'ks4-instrumental-methods-h12',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why a result from an instrument must still be interpreted by a trained chemist.',
        "options": [
            'The instrument cannot print its results without help',
            'A reading can be wrong if the method was set up badly',
            'The instrument gives its answer in a secret code',
            'A trained chemist can make the instrument more sensitive',
        ],
        "correct_index": 1,
        "why": 'Contamination, a bad calibration or an unsuitable dilution all '
               'produce a confident number that is nevertheless wrong.',
    },
    {
        "id": 'ks4-instrumental-methods-h13',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why an emission spectrum is often described as a fingerprint of an element.',
        "options": [
            'The spectrum is recorded on a print of the sample',
            'Every element gives exactly one line in its spectrum',
            'The pattern of lines is unique to that one element',
            'The spectrum changes slightly each single time the sample is run',
        ],
        "correct_index": 2,
        "why": 'No two elements share the same set of energy level gaps, so no two '
               'share the same complete pattern of wavelengths.',
    },
    {
        "id": 'ks4-instrumental-methods-h14',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A river sample is reported to contain a metal at 0.8 parts per million. Explain what that figure means.',
        "options": [
            '0.8 g of the metal in a million litres',
            '0.8% of the water is the metal present',
            'The metal was found in 0.8 of a million samples',
            '0.8 g of the metal in every million grams of water',
        ],
        "correct_index": 3,
        "why": 'Parts per million is a ratio by mass, so 0.8 ppm is 0.8 g in 1 000 '
               '000 g, which is about 0.8 mg in each litre of water.',
    },
    {
        "id": 'ks4-instrumental-methods-h15',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why an element gives the same emission lines whichever compound the sample came from.',
        "options": [
            "The lines come from the element's own electron levels",
            'Every compound of an element has the same formula mass',
            'The flame converts every compound into the same oxide',
            'The negative ion emits light at the same wavelengths',
        ],
        "correct_index": 0,
        "why": "It is the metal's electrons that are excited and emit, so the "
               'partner ion in the original compound makes no difference.',
    },
    {
        "id": 'ks4-instrumental-methods-h16',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why mass spectrometry rather than flame emission spectroscopy is used to identify an unknown organic molecule.',
        "options": [
            'Organic molecules are too small for a flame to excite',
            'Flame emission spectroscopy is used for metal ions',
            'Mass spectrometry works only on coloured substances',
            'Organic molecules give no lines in any spectrum at all',
        ],
        "correct_index": 1,
        "why": 'Flame emission reads metal ions, whereas a mass spectrometer '
               'measures the mass of the molecule and of the fragments it breaks '
               'into.',
    },
    {
        "id": 'ks4-instrumental-methods-h17',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A sample is diluted ten times before analysis. Determine what must be done to the concentration read from the calibration graph.',
        "options": [
            'Divide it by ten to get the original concentration',
            'Leave it unchanged, since dilution does not matter',
            'Multiply it by ten to get the original concentration',
            'Subtract ten from it to get the original concentration',
        ],
        "correct_index": 2,
        "why": 'The graph gives the concentration of the diluted solution, so the '
               'original was ten times greater.',
    },
    {
        "id": 'ks4-instrumental-methods-h18',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why a spectrometer measures a wavelength rather than recording the colour seen.',
        "options": [
            'A colour cannot be produced by a hot metal ion',
            'Wavelengths are easier for a person to remember',
            'Colours are only produced by mixtures of elements',
            'A wavelength is a number that everyone agrees on',
        ],
        "correct_index": 3,
        "why": 'Two people can name the same colour differently, but a wavelength '
               'in nanometres is the same measurement wherever it is made.',
    },
    {
        "id": 'ks4-instrumental-methods-h19',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'A calibration graph is plotted from standards of 0, 5, 10 and 20 mg per dm3. Explain why the zero standard is included.',
        "options": [
            'It shows the reading given when none of the element is there',
            'It makes the line on the graph much easier to draw straight',
            'It proves that the instrument can detect very low amounts',
            'It is needed because every graph must start at the origin',
        ],
        "correct_index": 0,
        "why": 'The blank shows any background signal, so it can be allowed for '
               'rather than counted as part of the sample.',
    },
    {
        "id": 'ks4-instrumental-methods-h20',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why an instrumental result is usually reported together with an uncertainty.',
        "options": [
            'The instrument gives a different answer every time',
            'No measurement is exact, so the range matters',
            'An uncertainty is required by law for all results',
            'It shows that the chemist was unsure of the method',
        ],
        "correct_index": 1,
        "why": 'Every measurement carries some spread, and a user of the result '
               'needs to know how far it can be trusted before acting on it.',
    },
    {
        "id": 'ks4-instrumental-methods-h21',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why a detector can register an element present at only a few parts per million.',
        "options": [
            'It concentrates the sample many times before the run',
            'It counts the atoms of the element one at a time',
            'It responds to light far too faint for the eye to see',
            'It removes every other element before the measurement',
        ],
        "correct_index": 2,
        "why": 'Sensitivity comes from the detector responding to very low light '
               'levels, well below the threshold at which a person sees any colour.',
    },
    {
        "id": 'ks4-instrumental-methods-h22',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Two samples give lines at exactly the same wavelength but with different intensities. Deduce what is the same and what differs.',
        "options": [
            'Different elements, present at the same concentration',
            'The same element, measured at different temperatures',
            'Different elements, one of which is much more concentrated',
            'The same element, present at different concentrations',
        ],
        "correct_index": 3,
        "why": 'Wavelength fixes the identity and intensity fixes the amount, so '
               'matching wavelengths with different brightness means the same '
               'element, more of it.',
    },
    {
        "id": 'ks4-instrumental-methods-h23',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain why a flame emission spectrometer would not detect a chloride ion in a sample.',
        "options": [
            'The method reads emission from metal ions only',
            'Chloride ions are destroyed by the heat of the flame',
            'Chloride ions emit light outside the visible range',
            'Chloride ions are too heavy to reach the flame at all',
        ],
        "correct_index": 0,
        "why": 'It is the instrumental version of the flame test, so it shares the '
               "flame test's blindness to the negative ion.",
    },
    {
        "id": 'ks4-instrumental-methods-h24',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Suggest why pure water is run through the instrument before a batch of samples.',
        "options": [
            'To warm the instrument up to its working temperature',
            'To check that the apparatus is giving no signal of its own',
            'To dilute any sample that turns out to be too concentrated',
            'To wash the diffraction grating clean before the run',
        ],
        "correct_index": 1,
        "why": 'A blank run shows any contamination or background emission, so a '
               'false positive can be spotted before the real samples are measured.',
    },
    {
        "id": 'ks4-instrumental-methods-h25',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Explain how instrumental analysis of a food can reveal an ingredient that is not listed on the label.',
        "options": [
            'It reads the label and compares it with the contents',
            'It removes anything that should not be in the food',
            'It detects substances present in very small amounts',
            'It measures only the ingredients that are listed',
        ],
        "correct_index": 2,
        "why": 'Sensitivity down to parts per million means an undeclared additive '
               'shows up even when it makes up a tiny fraction of the food.',
    },
    {
        "id": 'ks4-instrumental-methods-h26',
        "subtopic_slug": 'instrumental-methods',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": True,
        "text": 'Compare what infrared spectroscopy identifies with what flame emission spectroscopy identifies.',
        "options": [
            'Infrared finds metal ions, flame emission finds functional groups',
            'Both find metal ions, but infrared is the more sensitive method',
            'Both find functional groups, but flame emission is much faster',
            'Infrared finds functional groups, flame emission finds metal ions',
        ],
        "correct_index": 3,
        "why": 'The two answer different questions, which is why a full analysis '
               'often uses more than one instrument on the same sample.',
    },
]
