"""Chemistry · Bonding, structure and properties — the MRB-338 expansion for `ionic-bonding`.

This leaf is the electron accounting of an ionic bond: which particles move,
which way, how many, and what the ions are left holding. So the weight sits on
charge — reading it off a group number, reading a group number back off a
formula, and balancing the two sides to zero — because every formula in the
leaf is decided by charge and nothing else.

The rest goes to the two things a pupil gets wrong first: that the transfer IS
the bond (it only makes the ions), and that losing electrons ought to leave a
negative particle. Named compounds carry the applied rows — calcium chloride,
potassium sulfide, aluminium oxide and chloride, sodium nitride, magnesium
sulfide, calcium bromide — and the harder rows take the same charge arithmetic
into elements the course never names: barium, strontium, zinc, iron, silver,
caesium, rubidium, and hydrogen behaving as a 1- ion.
"""

TOPIC = "bonding"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": 'ks4-ionic-bonding-e05',
        "subtopic_slug": 'ionic-bonding',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Aluminium is in Group 3. State the charge on the ion that an aluminium atom forms.',
        "options": [
            '3+, because an aluminium atom loses three electrons',
            '3-, because an aluminium atom gains three electrons',
            '1+, because it loses one of its outer electrons',
            '6+, because it loses electrons from two shells',
        ],
        "correct_index": 0,
        "why": 'A Group 3 metal empties an outer shell holding three electrons, so the ion it leaves behind carries 3+.',
    },
    {
        "id": 'ks4-ionic-bonding-e06',
        "subtopic_slug": 'ionic-bonding',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Name the ion that a sulfur atom forms when it takes electrons from a metal.',
        "options": [
            'The sulfate ion, formed by taking two electrons',
            'The sulfide ion, formed by taking two electrons',
            'The sulfite ion, formed by taking one electron',
            'The sulfur ion, formed by taking two electrons',
        ],
        "correct_index": 1,
        "why": 'A non-metal ion takes the ending -ide, so sulfur becomes the sulfide ion, S2-.',
    },
    {
        "id": 'ks4-ionic-bonding-e07',
        "subtopic_slug": 'ionic-bonding',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'State which particles move from one atom to another when an ionic bond forms.',
        "options": [
            'Protons, which move from the metal to the non-metal atom',
            'Electrons, which move from the non-metal atom to the metal',
            'Electrons, which move from the metal to the non-metal',
            'Neutrons, which move from the metal to the non-metal',
        ],
        "correct_index": 2,
        "why": 'Only outer electrons move: the metal gives them up and the non-metal takes them in.',
    },
    {
        "id": 'ks4-ionic-bonding-e08',
        "subtopic_slug": 'ionic-bonding',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A sodium ion has the electronic structure 2.8. Name the noble gas that has this same electronic structure.',
        "options": [
            'Argon',
            'Helium',
            'Krypton',
            'Neon',
        ],
        "correct_index": 3,
        "why": 'Neon has ten electrons arranged 2.8, which is what a sodium atom is left with once it loses its outer electron.',
    },
    {
        "id": 'ks4-ionic-bonding-e09',
        "subtopic_slug": 'ionic-bonding',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why a metal atom becomes a positively charged ion when it forms an ionic bond.',
        "options": [
            'It loses negatively charged electrons, so the protons left in its nucleus outnumber its electrons',
            'It gains protons from the non-metal atom it is bonding with',
            'It takes in extra electrons, which are positively charged',
            'It loses a neutron from its nucleus, leaving a positive charge',
        ],
        "correct_index": 0,
        "why": 'Electrons are negative, so an atom that gives some away is left with more protons than electrons.',
    },
    {
        "id": 'ks4-ionic-bonding-e10',
        "subtopic_slug": 'ionic-bonding',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Nitrogen is in Group 5. State how many electrons a nitrogen atom gains when it forms an ion.',
        "options": [
            'Five, so that its outer shell empties',
            'Three, so that its outer shell is filled to eight electrons',
            'Two, so that its outer shell holds seven',
            'Eight, so that it has a full shell',
        ],
        "correct_index": 1,
        "why": 'A nitrogen atom has five outer electrons, so three more complete the shell and give the N3- ion.',
    },
    {
        "id": 'ks4-ionic-bonding-e11',
        "subtopic_slug": 'ionic-bonding',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'State which type of element forms the negative ions in an ionic compound.',
        "options": [
            'Metals, because they lose electrons and end up carrying a negative charge overall',
            'Metals, because a metal atom pulls electrons away from a non-metal atom',
            'Non-metals, because they gain the electrons the metal loses',
            'Noble gases, because they already hold eight electrons',
        ],
        "correct_index": 2,
        "why": 'A non-metal atom takes in the electrons the metal gives up, so it ends up negatively charged.',
    },
    {
        "id": 'ks4-ionic-bonding-e12',
        "subtopic_slug": 'ionic-bonding',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'In a dot-and-cross diagram, state what the dots and the crosses are used to show.',
        "options": [
            'Dots stand for electrons and crosses stand for the protons in each nucleus',
            'Dots stand for full shells and crosses for shells that are empty',
            'Dots and crosses show which shell each electron occupies now',
            'Dots and crosses show which atom each electron came from',
        ],
        "correct_index": 3,
        "why": 'The two symbols are only there to record the origin of each electron once the transfer has happened.',
    },
    {
        "id": 'ks4-ionic-bonding-s05',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why both atoms end up with the electron arrangement of a noble gas when sodium chloride forms.',
        "options": [
            'Sodium empties its outer shell to leave 2.8 and chlorine fills its outer shell to reach 2.8.8',
            'Both atoms share the outer electron between them so that each one counts eight',
            'Sodium gains seven electrons from chlorine so that both shells hold eight',
            'Chlorine passes one electron to sodium, filling the sodium outer shell',
        ],
        "correct_index": 0,
        "why": 'One electron moves from sodium to chlorine, which empties one outer shell and completes the other.',
    },
    {
        "id": 'ks4-ionic-bonding-s06',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Calcium forms Ca2+ ions and chlorine forms Cl- ions. Deduce the formula of calcium chloride.',
        "options": [
            'CaCl, because one calcium ion pairs with one chloride ion whatever their charges are',
            'CaCl2, because two 1- ions are needed to balance one 2+ ion',
            'Ca2Cl, because calcium has twice the charge of chloride',
            'CaCl3, because three chloride ions fit around each calcium',
        ],
        "correct_index": 1,
        "why": 'The charges have to cancel: 2+ on the calcium ion needs 2- in total, which is two chloride ions.',
    },
    {
        "id": 'ks4-ionic-bonding-s07',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Aluminium forms Al3+ ions and oxygen forms O2- ions. Deduce the formula of aluminium oxide.',
        "options": [
            'AlO, because a single aluminium ion is enough on its own to cancel out a single oxide ion',
            'Al3O2, because the charge on the aluminium ion is 2+ and each oxide ion is 3-',
            'Al2O3, because 6+ from two aluminium ions cancels 6- from three oxide ions',
            'AlO3, because three oxide ions surround each aluminium ion',
        ],
        "correct_index": 2,
        "why": 'Six is the smallest charge both ions divide into, so two Al3+ ions balance three O2- ions.',
    },
    {
        "id": 'ks4-ionic-bonding-s08',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Describe what each atom does with its outer electrons when sodium reacts with chlorine.',
        "options": [
            'Chlorine hands its outer electron to sodium, so chlorine is left positive and sodium negative',
            'Each atom gives one outer electron to the other, so both end up neutral again',
            'Both atoms pull their outer electrons in towards their own nucleus',
            'Sodium gives one outer electron to chlorine, which takes it in',
        ],
        "correct_index": 3,
        "why": 'Sodium has one outer electron to lose and chlorine has room for exactly one more, so one electron moves.',
    },
    {
        "id": 'ks4-ionic-bonding-s09',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Sulfur has six electrons in its outer shell. Deduce the electronic structure of the sulfide ion, S2-.',
        "options": [
            '2.8.8',
            '2.8.4',
            '2.8.6',
            '2.8',
        ],
        "correct_index": 0,
        "why": 'Sulfur is 2.8.6, so gaining two electrons takes the outer shell up to eight and gives 2.8.8.',
    },
    {
        "id": 'ks4-ionic-bonding-s10',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Potassium forms K+ ions and sulfur forms S2- ions. Deduce the formula of potassium sulfide.',
        "options": [
            'KS, because a compound of two elements takes one ion of each unless it is told otherwise',
            'K2S, because two 1+ ions are needed to cancel one 2- ion',
            'KS2, because sulfur carries twice the charge potassium does',
            'K2S2, because the two charges are 1+ and 2- in turn',
        ],
        "correct_index": 1,
        "why": 'One sulfide ion carries 2-, so two potassium ions at 1+ each are needed to balance it.',
    },
    {
        "id": 'ks4-ionic-bonding-s11',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Sodium forms Na+ ions and nitrogen forms N3- ions. Deduce the formula of sodium nitride.',
        "options": [
            'NaN3, because the nitride ion carries a charge of 3- and sodium carries a charge of 1+',
            'Na3N2, because the charges on the ions are 1+ and 3-',
            'Na3N, because three 1+ ions balance one 3- ion',
            'NaN, because one ion of each is present',
        ],
        "correct_index": 2,
        "why": 'A nitride ion carries 3-, so three sodium ions at 1+ each are needed to reach an overall charge of zero.',
    },
    {
        "id": 'ks4-ionic-bonding-s12',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A magnesium ion (Mg2+) and a sulfide ion (S2-) combine to form magnesium sulfide. Determine the ratio in which they combine and give the resulting formula.',
        "options": [
            'Mg2S2, because the magnesium ion carries 2+ and the sulfide ion carries 2- in the compound',
            'Mg2S, because two magnesium ions are needed for each sulfide ion',
            'MgS2, because sulfur takes two electrons from the metal',
            'MgS, because 2+ cancels 2- exactly',
        ],
        "correct_index": 3,
        "why": 'The two charges are equal in size and opposite in sign, so one ion of each cancels to zero.',
    },
    {
        "id": 'ks4-ionic-bonding-s13',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why the number of electrons the metal atoms lose must equal the number the non-metal atoms gain.',
        "options": [
            'Every electron lost by a metal atom is taken in by a non-metal atom, so the charges balance to zero',
            'Metal atoms lose more electrons than non-metals gain, and the rest are left loose',
            'The two numbers are equal because both kinds of atom have eight outer electrons',
            'Non-metals gain twice as many electrons as metals lose in every compound',
        ],
        "correct_index": 0,
        "why": 'Electrons are not created or destroyed in the transfer, and an ionic compound has no overall charge.',
    },
    {
        "id": 'ks4-ionic-bonding-s14',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why the electron that moves from a sodium atom to a chlorine atom does not move back again.',
        "options": [
            'The electron joins the chlorine nucleus, so it can no longer move anywhere in the structure',
            'Both particles now hold a full outer shell, which is a more stable arrangement than before',
            'The sodium ion has no shell left that an electron could return into',
            'The two ions repel each other, so nothing can pass between them',
        ],
        "correct_index": 1,
        "why": 'The transfer leaves both particles with full outer shells, and going back would undo that stability.',
    },
    {
        "id": 'ks4-ionic-bonding-s15',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'In a dot-and-cross diagram of sodium chloride, explain why the sodium ion is drawn with an empty outer shell.',
        "options": [
            'Because its outer electrons have been pulled into its nucleus and are drawn there instead now',
            'Because a positive ion is drawn without any electrons at all in any of its shells',
            'Because the one electron that was in that shell has been transferred away',
            'Because sodium ions have only two shells, so the third is left blank',
        ],
        "correct_index": 2,
        "why": 'Sodium is 2.8.1, so once the single third-shell electron leaves, the shell is empty and 2.8 remains.',
    },
    {
        "id": 'ks4-ionic-bonding-s16',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A metal M forms M+ ions and a non-metal X forms X2- ions. Deduce the formula of the compound they form.',
        "options": [
            'MX2, because the non-metal carries the larger charge and so needs the larger number in the formula',
            'MX, because a compound always contains one ion of each element',
            'M2X2, because each charge is doubled',
            'M2X, because two 1+ ions balance one 2- ion',
        ],
        "correct_index": 3,
        "why": 'Two M+ ions carry 2+ between them, which is exactly what one X2- ion needs to cancel.',
    },
    {
        "id": 'ks4-ionic-bonding-s17',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Potassium has one electron in its outer shell. Explain why it forms a K+ ion and not a K2+ ion.',
        "options": [
            'Removing one electron empties the outer shell, and the next electron would have to come from a full shell',
            'Potassium is not able to lose more than one electron under any conditions',
            'A second electron would be taken by the non-metal instead of by potassium',
            'Potassium has only one electron in total, so there is no second one to lose',
        ],
        "correct_index": 0,
        "why": 'The single outer electron leaves easily; pulling one out of the full shell beneath would take far more energy.',
    },
    {
        "id": 'ks4-ionic-bonding-s18',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'An aluminium ion carries a charge of 3+ and a chloride ion carries a charge of 1-. Work out how many of each ion combine to give aluminium chloride a formula, then write that formula.',
        "options": [
            'Al3Cl, because the aluminium ion carries a charge of 3+ and needs three times as much of itself',
            'AlCl3, because three 1- ions are needed to balance one 3+ ion',
            'AlCl, because one ion of each element is present in it',
            'Al2Cl3, because the charges present are 3+ and 1-',
        ],
        "correct_index": 1,
        "why": 'One Al3+ ion carries 3+, so three chloride ions at 1- each bring the total charge to zero.',
    },
    {
        "id": 'ks4-ionic-bonding-s19',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Calcium is in Group 2 and calcium bromide has the formula CaBr2. Deduce the charge on a bromide ion.',
        "options": [
            'A charge of 2-, the same size as the charge on the calcium ion it is balancing here',
            'A charge of 2+, because there are two bromide ions in the formula',
            'A charge of 1-, because two of them share the 2- needed',
            'A charge of 4-, because two ions carry twice 2-',
        ],
        "correct_index": 2,
        "why": 'A calcium ion carries 2+, so the two bromide ions must supply 2- between them: 1- each.',
    },
    {
        "id": 'ks4-ionic-bonding-s20',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why an ionic compound has no overall charge even though it is made entirely of charged particles.',
        "options": [
            'Because the ions lose their charges as soon as they have been pulled together into the compound',
            'Because the positive ions outnumber the negative ones, which cancels the charge out',
            'Because the electrons carry the charge, not the ions',
            'Because the total positive charge equals the total negative charge',
        ],
        "correct_index": 3,
        "why": 'Every electron the metal loses is gained by a non-metal, so the two totals are always equal and opposite.',
    },
    {
        "id": 'ks4-ionic-bonding-s21',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A calcium atom has two electrons in its fourth shell and 20 electrons in total. Deduce the number of electrons in a Ca2+ ion.',
        "options": [
            '18 electrons',
            '20 electrons',
            '22 electrons',
            '2 electrons',
        ],
        "correct_index": 0,
        "why": 'The ion has lost two of the twenty electrons, so eighteen are left; the 20 protons do not change.',
    },
    {
        "id": 'ks4-ionic-bonding-s22',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "figure": "ks4-fig-ionic-mgo-ions",
        "text": "The diagram shows the ions in magnesium oxide. Explain what the two crosses on the oxide ion show.",
        "options": [
            'They mark the two electrons that were transferred to the oxygen atom from the magnesium atom',
            'They mark the two electrons oxygen keeps for itself while the rest are shared',
            'They mark the two protons the oxide ion has gained in the transfer',
            'They mark the two shells that the oxide ion now has',
        ],
        "correct_index": 0,
        "why": "Crosses record electrons that started on the other atom. Magnesium lost its two outer electrons to the oxygen atom, so the oxide ion holds two crosses.",
    },
    {
        "id": 'ks4-ionic-bonding-s23',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'State the total number of electrons transferred when one magnesium atom reacts with one oxygen atom.',
        "options": [
            'Four, because magnesium loses two electrons and oxygen separately gains two of its own',
            'Eight, because the oxygen atom ends up with eight outer electrons',
            'Two, both of them leaving the magnesium atom',
            'Six, because oxygen has six outer electrons',
        ],
        "correct_index": 2,
        "why": 'Magnesium loses two electrons and oxygen gains those same two, so only two electrons move in total.',
    },
    {
        "id": 'ks4-ionic-bonding-s24',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why sodium and potassium both form ions with a 1+ charge although their atoms hold different numbers of electrons.',
        "options": [
            'Because a 1+ charge is the largest charge that any metal atom is able to end up carrying',
            'Because both atoms lose the same fraction of the electrons they started with',
            'Because both atoms hold the same total of electrons',
            'Because each has one electron in its outer shell to lose',
        ],
        "correct_index": 3,
        "why": 'The charge depends on how many outer electrons leave, and both Group 1 atoms have one to give.',
    },
    {
        "id": 'ks4-ionic-bonding-s25',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why a sodium ion holds 10 electrons but still contains 11 protons.',
        "options": [
            'One electron has been transferred away, and the number of protons in a nucleus does not change',
            'One proton is lost along with the electron when the ion forms',
            'A sodium atom holds 10 electrons and 11 protons before it reacts',
            'The eleventh electron has moved into the nucleus to join the protons',
        ],
        "correct_index": 0,
        "why": 'Forming an ion moves outer electrons only; the nucleus is untouched, so 11 protons and 10 electrons give 1+.',
    },
    {
        "id": 'ks4-ionic-bonding-s26',
        "subtopic_slug": 'ionic-bonding',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'State what is written outside the square brackets drawn around each ion in a dot-and-cross diagram.',
        "options": [
            'The number of electrons that particular ion has altogether, counted across all of its shells',
            'The charge on that ion, such as + or 2-',
            'The noble gas the ion now matches',
            'The group the element came from',
        ],
        "correct_index": 1,
        "why": 'The brackets hold the ion and the charge is written just outside them, showing what the transfer left behind.',
    },
    {
        "id": 'ks4-ionic-bonding-h05',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Magnesium nitride has the formula Mg3N2. Deduce the charges on the two ions it contains.',
        "options": [
            'Mg3+ and N2-, reading the charge on each ion straight off the number written beside it',
            'Mg2+ and N3-, because three lots of 2+ cancel two lots of 3-',
            'Mg+ and N-, because the formula is already balanced',
            'Mg6+ and N6-, because both totals come to six',
        ],
        "correct_index": 1,
        "why": 'Three Mg2+ ions carry 6+ and two N3- ions carry 6-, which is why the ratio is three to two.',
    },
    {
        "id": 'ks4-ionic-bonding-h06',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why a chloride ion carries a negative charge even though the chlorine atom it came from carried none.',
        "options": [
            'Because the chlorine atom has taken a proton from the metal, and protons are the particles that carry charge',
            'Because a chlorine atom starts with more protons than electrons and one extra evens it out',
            'Because the atom has lost an electron, and losing a particle leaves a negative charge behind',
            'Because it has gained an electron, so its electrons now outnumber its protons',
        ],
        "correct_index": 3,
        "why": 'A neutral atom has equal protons and electrons; one extra electron tips the balance to 1-.',
    },
    {
        "id": 'ks4-ionic-bonding-h07',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Compare what happens to the outer shell of a potassium atom and to that of an oxygen atom when potassium oxide forms.',
        "options": [
            'Potassium empties its outer shell by losing one electron, while oxygen fills its outer shell by gaining two',
            'Both atoms empty their outer shells and the electrons are left between them',
            'Potassium fills its outer shell with two electrons and oxygen empties its own',
            'Both outer shells end up holding eight electrons taken from each other',
        ],
        "correct_index": 0,
        "why": 'Potassium is 2.8.8.1 and loses that single electron; oxygen is 2.6 and takes two to reach 2.8.',
    },
    {
        "id": 'ks4-ionic-bonding-h08',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Barium chloride has the formula BaCl2. Predict the formula of barium oxide.',
        "options": [
            'Ba2O',
            'BaO',
            'BaO2',
            'Ba2O3',
        ],
        "correct_index": 1,
        "why": 'Two 1- chloride ions balance barium, so barium is 2+, and one 2- oxide ion cancels it alone.',
    },
    {
        "id": 'ks4-ionic-bonding-h09',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A sodium ion and a fluoride ion both have the electronic structure 2.8. Explain how their charges can still differ.',
        "options": [
            'Sodium lost an electron while fluorine shared one instead',
            'Sodium has fewer shells, so its charge comes out positive',
            'They hold the same electrons but a different number of protons',
            'They contain the same protons but a different number of shells',
        ],
        "correct_index": 2,
        "why": 'Sodium has 11 protons against 10 electrons, giving 1+; fluorine has 9 against 10, giving 1-.',
    },
    {
        "id": 'ks4-ionic-bonding-h10',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Evaluate this statement: "An ionic compound contains equal numbers of positive and negative ions."',
        "options": [
            'It is correct, because the total positive charge and the total negative charge in a compound are equal to each other',
            'It is correct, because each metal atom hands its electrons to exactly one non-metal atom',
            'It is wrong, because the metal ions in an ionic compound always outnumber the non-metal ions',
            'It is wrong: sodium sulfide holds two sodium ions per sulfide ion',
        ],
        "correct_index": 3,
        "why": 'Equal CHARGES are required, not equal numbers, so two Na+ ions are needed for one S2- ion.',
    },
    {
        "id": 'ks4-ionic-bonding-h11',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A compound of two elements has the formula XY2 and contains X2+ ions. Deduce which group of the periodic table Y is in.',
        "options": [
            'Group 7',
            'Group 2',
            'Group 6',
            'Group 4',
        ],
        "correct_index": 0,
        "why": 'Two Y ions must supply 2- between them, so each carries 1-, which is the Group 7 charge.',
    },
    {
        "id": 'ks4-ionic-bonding-h12',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Evaluate this statement: "In an ionic compound the metal ion and the non-metal ion share the transferred electron."',
        "options": [
            'It is correct, because the electron spends part of its time on the metal ion and part of it on the non-metal ion',
            'It is wrong: the electron is handed over completely and belongs to the non-metal ion',
            'It is correct, because both ions end up with a full outer shell from that electron',
            'It is wrong: the electron is held between the two ions and belongs to neither',
        ],
        "correct_index": 1,
        "why": 'Transfer is complete, which is why both particles carry a charge; sharing would leave both neutral.',
    },
    {
        "id": 'ks4-ionic-bonding-h13',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Strontium sits directly below calcium in Group 2. Predict the formula of strontium nitride.',
        "options": [
            'SrN, because one strontium ion is able to cancel out one nitride ion between the two of them',
            'Sr2N3, because strontium carries 2+ and nitrogen carries 3-',
            'Sr3N2, because three 2+ ions balance two 3- ions',
            'Sr3N, because three strontium ions surround each nitride ion',
        ],
        "correct_index": 2,
        "why": 'Strontium forms Sr2+ like calcium, and 6+ from three of them cancels 6- from two N3- ions.',
    },
    {
        "id": 'ks4-ionic-bonding-h14',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Zinc forms Zn2+ ions. Predict the formula of zinc oxide and the formula of zinc chloride.',
        "options": [
            'Zn2O and Zn2Cl, because two zinc ions are needed in each of the two compounds that are named',
            'ZnO2 and ZnCl2, because both oxygen and chlorine take two electrons each',
            'Zn2O3 and ZnCl3, because zinc behaves in the same way as aluminium does',
            'ZnO and ZnCl2',
        ],
        "correct_index": 3,
        "why": 'One O2- cancels Zn2+ on its own, but two Cl- ions are needed because each carries only 1-.',
    },
    {
        "id": 'ks4-ionic-bonding-h15',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Potassium and calcium sit next to each other in the periodic table. Explain why potassium forms a 1+ ion but calcium forms a 2+ ion.',
        "options": [
            'Potassium has one outer electron to lose and calcium has two, and each empties its outer shell',
            'Calcium is the heavier atom, so it is able to carry the larger charge of the two',
            'Calcium loses electrons from two shells while potassium loses from one',
            'Potassium gains one electron and calcium gains two instead',
        ],
        "correct_index": 0,
        "why": 'The charge is set by how many outer electrons leave: one for a Group 1 atom, two for a Group 2 atom.',
    },
    {
        "id": 'ks4-ionic-bonding-h16',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A student predicts that phosphorus forms a P5+ ion because phosphorus is in Group 5. Explain the error.',
        "options": [
            'Phosphorus is in Group 5 but sits in the third period, so the charge on its ion comes out as 3+ instead',
            'Phosphorus forms a P5- ion, gaining as many electrons as its group number',
            'Phosphorus is a non-metal, so it gains three electrons to reach eight and forms P3-',
            'Phosphorus forms no ion at all, because five is an odd number of electrons',
        ],
        "correct_index": 2,
        "why": 'A non-metal fills its outer shell rather than emptying it, so Group 5 gains three and the ion is 3-.',
    },
    {
        "id": 'ks4-ionic-bonding-h17',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Suggest why a compound made only of Na+ ions, with no negative ions present, could not exist.',
        "options": [
            'Because sodium ions would give their charges up to each other and turn back into ordinary atoms again',
            'Because a compound must contain at least two different elements joined together',
            'Because sodium ions are too small to be held together on their own',
            'Because like charges repel, and nothing would balance the charge',
        ],
        "correct_index": 3,
        "why": 'An ionic compound is held together by opposite charges attracting and must come out neutral overall.',
    },
    {
        "id": 'ks4-ionic-bonding-h18',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Evaluate this statement: "When electrons move from the metal to the non-metal, the metal is left with fewer protons than before."',
        "options": [
            'It is correct, because a proton leaves the nucleus alongside each electron that is transferred away',
            'It is correct, because the charge on the metal ion counts the protons it has lost',
            'It is wrong, because the metal gains protons from the non-metal as the electrons leave',
            'It is wrong: only electrons move, so the proton number never changes',
        ],
        "correct_index": 3,
        "why": 'Ion formation touches outer electrons alone; the nucleus, and so the proton number, is unchanged.',
    },
    {
        "id": 'ks4-ionic-bonding-h19',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Sodium hydride contains Na+ ions and H- ions. Suggest why hydrogen forms a 1- ion in this compound.',
        "options": [
            'A hydrogen atom has one electron and needs one more to fill its only shell, which holds two',
            'A hydrogen atom has seven outer electrons, so it takes one more to reach eight',
            'A hydrogen atom loses its electron, and losing one gives a 1- charge',
            'A hydrogen atom is a non-metal, and every non-metal ion carries 1-',
        ],
        "correct_index": 0,
        "why": 'Hydrogen has a single shell with room for two electrons, so gaining one completes it and gives H-.',
    },
    {
        "id": 'ks4-ionic-bonding-h20',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Evaluate this statement: "A sodium atom and a sodium ion behave the same way chemically, because both are sodium."',
        "options": [
            'It is correct, because the number of protons is what decides how a particle behaves in a reaction',
            'It is wrong: the ion has a full outer shell and a charge, so it behaves quite differently',
            'It is correct, because the two particles hold the same number of electrons as each other',
            'It is wrong, because the ion contains one proton fewer than the atom does',
        ],
        "correct_index": 1,
        "why": 'Sodium metal reacts vigorously with water while the Na+ ion in table salt does not react at all.',
    },
    {
        "id": 'ks4-ionic-bonding-h21',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Silver bromide contains Ag+ ions and Br- ions. Deduce its formula and explain why it is not Ag2Br.',
        "options": [
            'Ag2Br, because two silver ions are needed for each bromide ion in order to balance the charges out',
            'AgBr2, because bromine takes two electrons from each silver atom',
            'AgBr, because one 1+ ion cancels one 1- ion',
            'Ag2Br2, because each ion carries one unit of charge',
        ],
        "correct_index": 2,
        "why": 'The charges are equal in size, so one of each balances; Ag2Br would leave an overall charge of 1+.',
    },
    {
        "id": 'ks4-ionic-bonding-h22',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Calcium fluoride is used to make lenses. Deduce its formula and the number of electrons each calcium atom transfers.',
        "options": [
            'Ca2F, with each calcium atom transferring one electron to the fluorine atom that is next to it',
            'CaF, with each calcium atom transferring one electron',
            'CaF3, with each calcium atom transferring three electrons',
            'CaF2, with each calcium atom transferring two electrons',
        ],
        "correct_index": 3,
        "why": 'Calcium loses both outer electrons to give Ca2+, and one goes to each of two fluorine atoms.',
    },
    {
        "id": 'ks4-ionic-bonding-h23',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Potassium oxide has the formula K2O. Deduce the total number of electrons transferred as one unit of it forms.',
        "options": [
            'Two electrons',
            'One electron',
            'Four electrons',
            'Six electrons',
        ],
        "correct_index": 0,
        "why": 'Each potassium atom gives up one electron and the oxygen atom takes both, so two electrons move.',
    },
    {
        "id": 'ks4-ionic-bonding-h24',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Iron can form Fe2+ ions or Fe3+ ions. Deduce the formula of each of the two chlorides of iron.',
        "options": [
            'Fe2Cl and Fe3Cl, taking the number of iron ions straight from the charge that each ion carries',
            'FeCl2 from Fe2+ and FeCl3 from Fe3+',
            'FeCl2 from Fe3+ and FeCl3 from Fe2+',
            'FeCl and FeCl2, because one chloride ion balances the first of the two iron ions',
        ],
        "correct_index": 1,
        "why": 'Each chloride ion carries 1-, so 2+ needs two of them and 3+ needs three.',
    },
    {
        "id": 'ks4-ionic-bonding-h25',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Rubidium is in Group 1 and selenium is in Group 6. Predict the formula of rubidium selenide.',
        "options": [
            'RbSe, because one ion of each element is present whenever a metal reacts with a non-metal',
            'Rb6Se, because selenium is in Group 6 of the periodic table',
            'Rb2Se, because two 1+ ions balance one 2- ion',
            'RbSe2, because selenium carries the larger charge',
        ],
        "correct_index": 2,
        "why": 'Group 1 gives Rb+ and Group 6 gives Se2-, so two rubidium ions are needed for each selenide ion.',
    },
    {
        "id": 'ks4-ionic-bonding-h26',
        "subtopic_slug": 'ionic-bonding',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Compare what a Group 1 metal atom and a Group 7 non-metal atom each do to reach a noble gas electron arrangement.',
        "options": [
            'Both of them gain electrons, the metal taking seven of them and the non-metal taking just one',
            'Both of them lose electrons, the metal losing one and the non-metal losing seven',
            'The metal gains one electron and the non-metal loses one',
            'The metal loses one electron and the non-metal gains one',
        ],
        "correct_index": 3,
        "why": 'Emptying an outer shell holding one electron and filling one holding seven both reach eight.',
    },
]
