"""Chemistry · Bonding, structure and properties — the MRB-338 expansion for `chemical-bonds`.

This leaf answers one question in as many ways as the spec allows: given the
elements, WHICH of the three bonds forms, and why those elements produce it.
So the weight sits on prediction and deduction — from the elements present,
from a property signature (what conducts, when, and at what temperature), and
from the odd substance out of four.

The rest goes to the electron accounting that separates the three: transfer
makes ions, sharing leaves both atoms neutral, and release into a delocalised
sea leaves positive ions only. Named real substances carry the applied rows —
brass, magnesium oxide, zinc sulfide, lithium nitride, calcium chloride,
carbon dioxide, ammonia — and the misconception rows come at the errors from
the wrong side: that an element cannot contain bonds, that hydrogen behaves as
a metal, that anything containing a metal conducts.
"""

TOPIC = "bonding"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": 'ks4-chemical-bonds-e05',
        "subtopic_slug": 'chemical-bonds',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Name the group of the periodic table whose atoms have no tendency to form chemical bonds.',
        "options": [
            'Group 0',
            'Group 1',
            'Group 7',
            'Group 4',
        ],
        "correct_index": 0,
        "why": 'Group 0 atoms already have a full outer shell, so bonding would gain them nothing.',
    },
    {
        "id": 'ks4-chemical-bonds-e06',
        "subtopic_slug": 'chemical-bonds',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'State the type of bonding formed when a metal reacts with a non-metal.',
        "options": [
            'Covalent, because the two kinds of atom share a pair of electrons',
            'Ionic, because electrons transfer from the metal to the non-metal',
            'Metallic, because one of the two elements taking part is a metal',
            'Intermolecular, because the two kinds of atom attract each other',
        ],
        "correct_index": 1,
        "why": 'A metal gives electrons away and a non-metal takes them, so ions form and attract each other.',
    },
    {
        "id": 'ks4-chemical-bonds-e07',
        "subtopic_slug": 'chemical-bonds',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Name the type of bonding present in carbon dioxide.',
        "options": [
            'Ionic bonding, because carbon gives its outer electrons away to the two oxygen atoms',
            'Metallic bonding, because carbon releases electrons into a delocalised sea',
            'Covalent bonding',
            'Intermolecular bonding, because the molecules attract',
        ],
        "correct_index": 2,
        "why": 'Carbon and oxygen are both non-metals, so the only route to full outer shells is sharing electrons.',
    },
    {
        "id": 'ks4-chemical-bonds-e08',
        "subtopic_slug": 'chemical-bonds',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Name the two of the three types of bonding that need a metal to be present.',
        "options": [
            'Covalent and ionic, because a non-metal atom takes electrons in both of them',
            'Covalent and metallic, because electrons are spread out in both of them',
            'Ionic and intermolecular, because charged particles attract in both',
            'Ionic and metallic',
        ],
        "correct_index": 3,
        "why": 'Ionic bonding needs a metal to supply the electrons and metallic bonding needs metal atoms; covalent bonding needs neither.',
    },
    {
        "id": 'ks4-chemical-bonds-e09',
        "subtopic_slug": 'chemical-bonds',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Brass is a mixture of copper and zinc. State the type of bonding it contains.',
        "options": [
            'Metallic, because both elements present are metals that release their outer electrons',
            'Ionic, because copper gives electrons to zinc',
            'Covalent, because the two metals share electrons',
            'No bonding, because a mixture is not bonded',
        ],
        "correct_index": 0,
        "why": 'Mixing two metals changes nothing about the bonding: both release outer electrons into one shared sea.',
    },
    {
        "id": 'ks4-chemical-bonds-e10',
        "subtopic_slug": 'chemical-bonds',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Identify the type of bonding in magnesium oxide, MgO.',
        "options": [
            'Metallic, because magnesium is a metal in Group 2',
            'Covalent, because oxygen is a non-metal here',
            'Ionic, because a metal is bonded to a non-metal',
            'Metallic, because oxygen supplies the electrons',
        ],
        "correct_index": 2,
        "why": 'Magnesium is a metal and oxygen a non-metal, so electrons transfer and the bonding is ionic.',
    },
    {
        "id": 'ks4-chemical-bonds-e11',
        "subtopic_slug": 'chemical-bonds',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'State which of the three types of bonding transfers electrons from one atom to another.',
        "options": [
            'Covalent bonding, in which a pair is moved across',
            'Metallic bonding, in which the sea takes them over',
            'Ionic bonding only',
            'All three of them do',
        ],
        "correct_index": 2,
        "why": 'Only ionic bonding moves electrons from one atom to another; sharing and delocalising do not.',
    },
    {
        "id": 'ks4-chemical-bonds-e12',
        "subtopic_slug": 'chemical-bonds',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Name the kind of attraction that holds the particles together in all three types of chemical bond.',
        "options": [
            'Gravitational attraction, which acts between the masses of the particles involved',
            'Electrostatic attraction',
            'Magnetic attraction',
            'Nuclear attraction',
        ],
        "correct_index": 1,
        "why": 'Every chemical bond is an electrostatic attraction between particles of opposite charge.',
    },
    {
        "id": 'ks4-chemical-bonds-s05',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A substance melts at -95 °C and does not conduct electricity as a solid, as a liquid or when dissolved. Deduce the type of bonding it contains.',
        "options": [
            'Ionic bonding, because it dissolves easily',
            'Ionic bonding, because a melting point as low as that shows the ions are held together only weakly in the lattice',
            'Metallic bonding, because a substance that conducts nothing has no delocalised electrons left',
            'Covalent bonding, in small molecules that are weakly attracted to each other',
        ],
        "correct_index": 3,
        "why": 'Nothing charged is ever free to move, and the melting point is very low, so it must be small covalent molecules.',
    },
    {
        "id": 'ks4-chemical-bonds-s06',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A white solid does not conduct electricity, but a solution made by dissolving it in water does. Deduce the type of bonding it contains.',
        "options": [
            'Metallic bonding, because the water frees the electron sea that was trapped',
            'Ionic bonding, because dissolving frees its ions to move',
            'Covalent bonding, because the water shares electrons with it',
            'Metallic bonding, because only metals conduct at all',
        ],
        "correct_index": 1,
        "why": 'Charge carriers appear only once it dissolves, which is what happens when a lattice releases its ions.',
    },
    {
        "id": 'ks4-chemical-bonds-s07',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A hard solid melts at 1610 °C and does not conduct electricity in any state. Deduce the type of bonding it contains.',
        "options": [
            'Ionic bonding, because such a high melting point can only come from charged ions attracting one another',
            'Metallic bonding, because a high melting point means a strong electron sea holds it',
            'Covalent bonding, running throughout a giant structure',
            'Ionic bonding, because hard solids are brittle',
        ],
        "correct_index": 2,
        "why": 'Molten ionic compounds conduct and metals conduct as solids, so a substance that never conducts must be giant covalent.',
    },
    {
        "id": 'ks4-chemical-bonds-s08',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Hydrogen sits at the top of Group 1, yet it bonds covalently to oxygen in water. Explain why.',
        "options": [
            'Oxygen is a non-metal, so it releases electrons into a sea that hydrogen then shares with it',
            'Hydrogen has one outer electron, so it can only ever transfer that electron away',
            'Water contains three atoms, and a bond between three atoms has to be a shared one',
            'Hydrogen is a non-metal, so neither atom gives electrons up and they share instead',
        ],
        "correct_index": 3,
        "why": 'Group number does not decide bond type; hydrogen is a non-metal, and two non-metals can only share.',
    },
    {
        "id": 'ks4-chemical-bonds-s09',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Identify which of these substances contains metallic bonding: solid iodine, zinc, calcium fluoride or ammonia.',
        "options": [
            'Zinc, because a pure metal releases its outer electrons into a delocalised sea',
            'Calcium fluoride, because the calcium atoms in it release their outer electrons into a shared sea',
            'Solid iodine, because a grey solid with a shine on it must be held together by metallic bonding',
            'Ammonia, because nitrogen releases electrons',
        ],
        "correct_index": 0,
        "why": 'Metallic bonding needs metal atoms alone; calcium fluoride pairs a metal with a non-metal, so it is ionic.',
    },
    {
        "id": 'ks4-chemical-bonds-s10',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why a mixture of two different metals still contains metallic bonding.',
        "options": [
            'Because the two metals react together chemically to form a new compound in which the bonding is metallic',
            'Because the larger metal atoms each share a pair of their electrons with the smaller atoms around them',
            'Because every atom present is a metal atom, so every atom releases outer electrons into one sea',
            'Because one of the two metals transfers its outer electrons to the other, leaving positive ions behind',
        ],
        "correct_index": 2,
        "why": 'Bond type is decided by the kinds of atom present, and two metals together still release electrons into one shared sea.',
    },
    {
        "id": 'ks4-chemical-bonds-s11',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Compare what happens to the two outer electrons of a magnesium atom when it bonds with oxygen and when it bonds with more magnesium.',
        "options": [
            'They are given to oxygen in the compound, and given to a neighbouring magnesium atom in the metal instead',
            'They are shared with oxygen in the compound, and released into the electron sea in the metal',
            'They go to oxygen in the compound; they join a delocalised sea in the metal',
            'They stay in their shell in both cases, because magnesium never loses electrons',
        ],
        "correct_index": 2,
        "why": 'Magnesium loses both outer electrons either way — to the oxygen in the compound, to the shared sea in the metal.',
    },
    {
        "id": 'ks4-chemical-bonds-s12',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why a compound made of two non-metals cannot contain ionic bonding.',
        "options": [
            'Because neither atom will give electrons away, so there is nothing to make the ions from',
            'Because non-metal atoms are far too small to be able to carry any electric charge of their own in a compound',
            'Because a non-metal atom already has a full outer shell and so needs no further electrons',
            'Because ionic bonding needs three or more different elements to be present',
        ],
        "correct_index": 0,
        "why": 'Ions form when a metal hands electrons over; between two non-metals there is no donor, so they share.',
    },
    {
        "id": 'ks4-chemical-bonds-s13',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Cobalt melts at 1495 °C and conducts electricity while it is still a solid. Deduce the type of bonding it contains.',
        "options": [
            'Simple molecular, because it is an element',
            'Ionic, because the melting point is high',
            'Giant covalent, because it is a hard solid',
            'Metallic, because delocalised electrons are already free to move in the solid',
        ],
        "correct_index": 3,
        "why": 'Conducting as a solid rules out every structure except a metal, whose delocalised electrons move without melting.',
    },
    {
        "id": 'ks4-chemical-bonds-s14',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Sulfur dioxide is made from two different elements. Explain why its bonding is covalent rather than ionic.',
        "options": [
            'Because sulfur and oxygen are both non-metals, so electrons are shared rather than transferred',
            'Because the two elements sit in different groups of the periodic table, and atoms from different groups transfer electrons',
            'Because sulfur is a metal and metals always share their outer electrons with non-metals',
            'Because there are two oxygen atoms, and two atoms of one element cannot form ions',
        ],
        "correct_index": 0,
        "why": 'What matters is that both elements are non-metals, not that they are different from each other.',
    },
    {
        "id": 'ks4-chemical-bonds-s15',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Predict the type of bonding in calcium chloride and justify your prediction from the elements present.',
        "options": [
            'Covalent, because calcium needs two more electrons and chlorine needs one more electron',
            'Ionic, because calcium is a metal and chlorine a non-metal',
            'Metallic, because calcium is a metal in Group 2',
            'Covalent, because two chlorine atoms are present',
        ],
        "correct_index": 1,
        "why": 'A metal with a non-metal transfers electrons, giving Ca2+ and Cl- ions held by electrostatic attraction.',
    },
    {
        "id": 'ks4-chemical-bonds-s16',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A student says that a pure element cannot contain any chemical bonds, because bonds only form between different elements. Explain why this is wrong.',
        "options": [
            'Bonds form between atoms whether or not they are the same element: oxygen gas is O2 and copper is a metallic lattice',
            'Bonds do form in elements, but only in the ones that are gases at room temperature',
            'Bonds form in elements, but they are ionic rather than covalent, because a single element has no partner to share a pair of electrons with',
            'Bonds only form in elements once the element has been heated above its melting point',
        ],
        "correct_index": 0,
        "why": 'Atoms of one element bond to each other perfectly well — covalently in O2, metallically in a block of copper.',
    },
    {
        "id": 'ks4-chemical-bonds-s17',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Identify the pair of elements that would form an ionic compound.',
        "options": [
            'Nitrogen and hydrogen, because nitrogen needs three more outer electrons to fill its shell completely',
            'Carbon and sulfur, because carbon needs four electrons and sulfur can supply them',
            'Copper and tin, because one metal can hand its electrons to another metal',
            'Lithium and oxygen',
        ],
        "correct_index": 3,
        "why": 'Only lithium and oxygen pair a metal with a non-metal, which is what makes an ionic compound.',
    },
    {
        "id": 'ks4-chemical-bonds-s18',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Describe how the behaviour of the outer electrons differs between covalent bonding and metallic bonding.',
        "options": [
            'In covalent bonding they are lost completely to one of the two atoms; in metallic bonding they are shared in pairs',
            'In covalent bonding they stay in their own shells; in metallic bonding they are shared in pairs between neighbours',
            'In covalent bonding they are shared between two atoms; in metallic bonding they roam the whole lattice',
            'In covalent bonding they roam freely; in metallic bonding they belong to one atom each',
        ],
        "correct_index": 2,
        "why": 'A covalent pair is held between two particular atoms; delocalised electrons belong to the whole metal.',
    },
    {
        "id": 'ks4-chemical-bonds-s19',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Potassium iodide conducts electricity only once it has been melted, while potassium itself conducts as a solid. Deduce the bonding in each.',
        "options": [
            'Both are metallic, though the compound has far fewer delocalised electrons in it',
            'Both are ionic, but the compound has to melt before its ions are made',
            'Potassium iodide is metallic and potassium is ionic',
            'Potassium iodide is ionic and potassium is metallic',
        ],
        "correct_index": 3,
        "why": 'Ionic compounds need melting to free their ions; a metal has delocalised electrons that move in the solid.',
    },
    {
        "id": 'ks4-chemical-bonds-s20',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Suggest the type of bonding in a substance that is a gas at room temperature and conducts electricity in no state at all.',
        "options": [
            'Ionic, because its ions are too far apart in a gas to carry any charge between them',
            'Metallic, because its delocalised electrons have spread out into the gas as it boiled',
            'Covalent, in small molecules',
            'Giant covalent, because no charge can move',
        ],
        "correct_index": 2,
        "why": 'Only small covalent molecules boil below room temperature, and an uncharged molecule cannot carry current.',
    },
    {
        "id": 'ks4-chemical-bonds-s21',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Identify which substance has a different type of bonding from the other three: magnesium chloride, sodium oxide, calcium fluoride, carbon dioxide.',
        "options": [
            'Magnesium chloride, because it is the only one whose metal comes from Group 2 of the table',
            'Carbon dioxide, because it is the only one made of two non-metals',
            'Sodium oxide, because sodium is the most reactive metal listed',
            'Calcium fluoride, because fluorine is the most reactive non-metal',
        ],
        "correct_index": 1,
        "why": 'The first three pair a metal with a non-metal and are ionic; carbon dioxide is two non-metals, so covalent.',
    },
    {
        "id": 'ks4-chemical-bonds-s22',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why the number of atoms shown in a formula tells you nothing about the type of bonding.',
        "options": [
            'Because the type of bonding depends on which elements are present, not on how many atoms are shown',
            'Because a formula with three atoms in it is always covalent, while a formula with only two of them is always ionic instead',
            'Because every formula is written to show the simplest whole-number ratio of the atoms rather than the bonding',
            'Because the number of atoms shown changes with the temperature of the substance',
        ],
        "correct_index": 0,
        "why": 'MgCl2 and CO2 both show three atoms, yet one is ionic and one covalent — the elements decide it.',
    },
    {
        "id": 'ks4-chemical-bonds-s23',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A student says every substance containing a metal must conduct electricity. Explain the error.',
        "options": [
            'A metal compound conducts better than the metal, because it contains ions as well',
            'A metal conducts, but only after it has been melted so that its delocalised electrons are released',
            'No substance containing a metal conducts, because the metal ions are held in fixed lattice positions',
            'A solid ionic compound contains a metal but conducts nothing, because its ions cannot move',
        ],
        "correct_index": 3,
        "why": 'Sodium chloride contains a metal and conducts nothing as a solid: its charge carriers are fixed ions.',
    },
    {
        "id": 'ks4-chemical-bonds-s24',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Chlorine gas contains no metal atoms at all. Explain why its atoms still form chemical bonds with one another.',
        "options": [
            'Each atom is one electron short of a full outer shell, and sharing a pair fills both shells at once',
            'Each atom already has seven outer electrons, so one of the two atoms hands all seven of them to the other',
            'Chlorine atoms each carry a small charge, and that charge pulls neighbouring atoms strongly towards them',
            'Chlorine atoms release their outer electrons into a delocalised sea between them',
        ],
        "correct_index": 0,
        "why": 'Atoms bond to complete their outer shells, and two chlorine atoms can do that by sharing one pair.',
    },
    {
        "id": 'ks4-chemical-bonds-s25',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Predict the type of bonding in zinc sulfide and justify your prediction.',
        "options": [
            'Metallic, because zinc is a transition metal and sulfur can join its electron sea as well',
            'Covalent, because sulfur needs two electrons and zinc can share two with it',
            'Ionic, because a metal is bonded to a non-metal',
            'Intermolecular, because both particles are large',
        ],
        "correct_index": 2,
        "why": 'Zinc is a metal and sulfur a non-metal, so electrons transfer and the compound is ionic.',
    },
    {
        "id": 'ks4-chemical-bonds-s26',
        "subtopic_slug": 'chemical-bonds',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Identify the type of bonding in ammonia, NH3, and state what happens to the outer electrons.',
        "options": [
            'Ionic: nitrogen takes three electrons from the three hydrogen atoms it is joined to',
            'Covalent: nitrogen shares three pairs of electrons, one with each hydrogen atom',
            'Metallic: nitrogen releases its outer electrons into a sea the hydrogen atoms share',
            'Ionic: each hydrogen atom takes one electron from the nitrogen atom beside it',
        ],
        "correct_index": 1,
        "why": 'Nitrogen and hydrogen are both non-metals, so three shared pairs give nitrogen eight and each hydrogen two.',
    },
    {
        "id": 'ks4-chemical-bonds-h05',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Evaluate this statement: "A compound of a metal and a non-metal conducts electricity, because it contains charged ions."',
        "options": [
            'It is correct: the ions carry the charge whatever state the compound happens to be in, because a charge needs no room to move',
            'It is wrong: the compound contains no ions of any kind until the moment when it is melted or dissolved in water',
            'It is half right: the ions exist in the solid but cannot move, so it conducts only when molten or dissolved',
            'It is wrong: an ionic compound conducts using delocalised electrons rather than ions',
        ],
        "correct_index": 2,
        "why": 'The ions are there in the solid, but conduction needs them to MOVE, which only melting or dissolving allows.',
    },
    {
        "id": 'ks4-chemical-bonds-h06',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A brittle solid melts at 1291 °C, conducts nothing as a solid, and conducts well once molten. Deduce its bonding and justify each clue.',
        "options": [
            'Metallic: the high melting point shows a strong electron sea, and a molten metal conducts electricity well',
            'Giant covalent: the high melting point shows strong covalent bonds running throughout the whole structure',
            'Simple molecular: the brittleness shows only weak forces acting between the separate molecules present',
            'Ionic: the high melting point fits strong forces between ions, and molten conduction fits mobile ions',
        ],
        "correct_index": 3,
        "why": 'A metal would conduct as a solid and a giant covalent solid would not conduct at all — only ionic fits all three clues.',
    },
    {
        "id": 'ks4-chemical-bonds-h07',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Compare the bonding in sodium metal, in sodium chloride and in chlorine gas.',
        "options": [
            'Metallic, then ionic, then covalent',
            'Ionic in all three, because sodium and chlorine both form ions in every substance they are in',
            'Metallic, then covalent, then ionic, because chlorine is the more reactive of the two elements',
            'Covalent, then ionic, then metallic, because sodium shares electrons when it is on its own',
        ],
        "correct_index": 0,
        "why": 'A metal alone is metallic, a metal with a non-metal is ionic, and two non-metal atoms together are covalent.',
    },
    {
        "id": 'ks4-chemical-bonds-h08',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A student predicts that carbon and oxygen bond ionically, because oxygen takes electrons from other atoms. Evaluate the prediction.',
        "options": [
            'It is correct, because oxygen forms an oxide ion whenever it bonds to another element',
            'It is wrong, because carbon has four outer electrons and four is too many to give away',
            'It is wrong: oxygen takes electrons from metals, but carbon is a non-metal and gives up none, so they share',
            'It is correct, because the two elements are in different groups of the periodic table',
        ],
        "correct_index": 2,
        "why": 'Oxygen only makes O2- ions when a metal supplies the electrons; with a non-metal such as carbon it shares instead.',
    },
    {
        "id": 'ks4-chemical-bonds-h09',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'White phosphorus is a soft solid that melts at 44 °C and conducts electricity in no state. Suggest why its bonding cannot be metallic.',
        "options": [
            'A metal would be shiny, and a soft solid such as this one cannot be polished to a metallic shine',
            'A metal has delocalised electrons, so it would conduct as a solid and melt far higher',
            'A metal cannot exist as an element on its own, so phosphorus has to be a compound of some kind',
            'A metal has a melting point lower than 100 °C, so 44 °C is already too high for any metal',
        ],
        "correct_index": 1,
        "why": 'Metallic bonding supplies mobile electrons and a strong lattice, so a non-conducting solid melting at 44 °C is not a metal.',
    },
    {
        "id": 'ks4-chemical-bonds-h10',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why metallic bonding can occur in a single pure element, while ionic bonding cannot.',
        "options": [
            'Ionic bonding can occur in a pure element as well, provided that the element is heated strongly enough',
            'Ionic bonding needs a metal, and no element is a metal on its own until it is mixed with another',
            'Metallic bonding needs only one element because metal atoms are all exactly the same size as each other',
            'Ionic bonding needs a donor and an acceptor, so two different elements are required; a metal supplies both the ions and the electron sea itself',
        ],
        "correct_index": 3,
        "why": 'Ions of opposite charge need one atom to give and another to take; a metal makes its own ions and its own electron sea.',
    },
    {
        "id": 'ks4-chemical-bonds-h11',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Substance A melts at 993 °C and conducts once molten. Substance B melts at -23 °C and never conducts. Deduce which is ionic.',
        "options": [
            'B, because a low melting point means its ions are held loosely enough to move about freely in the solid',
            'Both, because every compound with a melting point above room temperature contains ions',
            'A, because the high melting point and molten conduction both point to a lattice of ions',
            'Neither, because conduction proves that delocalised electrons and not ions are present',
        ],
        "correct_index": 2,
        "why": 'A needs a great deal of energy to separate its particles and gains charge carriers on melting — the ionic pattern exactly.',
    },
    {
        "id": 'ks4-chemical-bonds-h12',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why the number of outer electrons an atom has decides whether it loses, gains or shares them.',
        "options": [
            'An atom takes whichever route reaches a full outer shell for the least energy: a few electrons are easier to lose than many are to gain',
            'An atom with more than four outer electrons must lose them, and one with fewer than four must gain them instead',
            'An atom always loses electrons if it can, because a smaller atom is more stable than a larger one',
            'An atom shares electrons whenever it has an even number of them and transfers them when it has an odd number',
        ],
        "correct_index": 0,
        "why": 'Emptying a nearly empty outer shell is cheap, filling a nearly full one is cheap, and sharing serves two atoms that both need more.',
    },
    {
        "id": 'ks4-chemical-bonds-h13',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Evaluate this statement: "An alloy has a different type of bonding from the pure metal it is made from."',
        "options": [
            'It is correct: adding a second element makes new ionic bonds between the two different kinds of atom present',
            'It is wrong: the bonding is still metallic, because every atom present still releases its outer electrons',
            'It is correct: an alloy counts as a compound, and a compound of two metals is not able to have metallic bonding',
            'It is wrong: an alloy contains no bonding of any kind, because the atoms in a mixture are not joined together',
        ],
        "correct_index": 1,
        "why": 'Mixing metals changes the geometry of the lattice, not the bonding: positive ions in one shared electron sea.',
    },
    {
        "id": 'ks4-chemical-bonds-h14',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Lithium is in Group 1 and nitrogen in Group 5. Predict the bonding in lithium nitride and justify it from the periodic table.',
        "options": [
            'Covalent, because nitrogen needs three electrons and can share one with each of three lithium atoms',
            'Metallic, because lithium is a metal and metals impose their own bonding on any compound',
            'Ionic, because lithium is a metal and nitrogen a non-metal',
            'Covalent, because three lithium atoms are needed for one nitrogen atom',
        ],
        "correct_index": 2,
        "why": 'Group 1 is a metal and Group 5 a non-metal, so electrons transfer: Li+ ions and N3- ions attract electrostatically.',
    },
    {
        "id": 'ks4-chemical-bonds-h15',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why a bond between two atoms of the same non-metal element must be covalent.',
        "options": [
            'Identical atoms pull on electrons equally, so neither can take them from the other and both must share',
            'Identical atoms repel each other, so the only bond they can form is a weak shared one',
            'Identical atoms have identical masses, and two equal masses cannot transfer electrons between them',
            'Identical atoms have full outer shells, so no electrons need to move between them at all',
        ],
        "correct_index": 0,
        "why": 'Transfer needs one atom to hold electrons more weakly than the other, and two atoms of one element cannot differ.',
    },
    {
        "id": 'ks4-chemical-bonds-h16',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A substance is a liquid at room temperature and conducts electricity well. Deduce its type of bonding.',
        "options": [
            'Ionic, because a liquid ionic compound has ions that are free to move about in it',
            'Metallic, because it conducts without having been heated at all',
            'Covalent, because most liquids at room temperature are small molecules',
            'Giant covalent, because it conducts and has melted already',
        ],
        "correct_index": 1,
        "why": 'An ionic compound would have to be heated above 700 °C to be liquid; mercury is a metal, liquid and conducting at 20 °C.',
    },
    {
        "id": 'ks4-chemical-bonds-h17',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'All three types of bonding are electrostatic attractions. State what is attracted to what in each of them.',
        "options": [
            'Ionic: nucleus to nucleus. Covalent: ion to ion. Metallic: ion to ion',
            'Ionic: ion to ion. Covalent: both nuclei to the shared pair. Metallic: ions to the electron sea',
            'Ionic: ion to ion. Covalent: one nucleus to the other. Metallic: the electrons to each other',
            'Ionic: atom to atom. Covalent: atom to atom. Metallic: atom to atom',
        ],
        "correct_index": 1,
        "why": 'Each bond is opposite charges attracting: ion to ion, two nuclei to one shared pair, and ions to the delocalised sea.',
    },
    {
        "id": 'ks4-chemical-bonds-h18',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Compare the charged particles present in solid copper with those present in solid copper chloride.',
        "options": [
            'Both contain delocalised electrons, although the compound holds far fewer of them than the metal',
            'Both contain positive ions and negative ions, but only the compound has delocalised electrons moving through it as well',
            'Copper has neutral atoms only; copper chloride has positive ions and delocalised electrons',
            'Copper has positive ions and delocalised electrons; copper chloride has positive and negative ions',
        ],
        "correct_index": 3,
        "why": 'Metallic bonding leaves positive ions in an electron sea; ionic bonding makes ions of both signs and no free electrons.',
    },
    {
        "id": 'ks4-chemical-bonds-h19',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Suggest why the state of a substance at room temperature is not enough on its own to identify its bonding.',
        "options": [
            'Because a solid at room temperature could be ionic, metallic or giant covalent, so a second clue such as conduction is needed',
            'Because the state of a substance changes from one day to the next as the room warms and cools again',
            'Because a substance in any state can be made to conduct electricity if a large enough voltage is applied across it, whatever its bonding',
            'Because gases are the only substances whose bonding can be identified from their state alone',
        ],
        "correct_index": 0,
        "why": 'Three bond types all give solids at room temperature, so the state narrows the choice without settling it.',
    },
    {
        "id": 'ks4-chemical-bonds-h20',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why magnesium and calcium do not form an ionic compound with each other.',
        "options": [
            'Both are metals, so both lose electrons, and there is no atom present to accept them',
            'Both are in Group 2, and two elements from one group are unable to bond at all',
            'Both form 2+ ions, and two ions of the same charge cannot be held next to each other',
            'Calcium is below magnesium in the group, so it takes the electrons and the bond between them is covalent',
        ],
        "correct_index": 0,
        "why": 'Ionic bonding needs a giver and a taker; two metals both give, so they simply form a metallic mixture.',
    },
    {
        "id": 'ks4-chemical-bonds-h21',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Compare how a full outer shell is achieved by the chlorine atom in potassium chloride and by the chlorine atom in hydrogen chloride.',
        "options": [
            'In both compounds chlorine takes one electron completely, so it becomes a chloride ion in each of them',
            'In potassium chloride it takes an electron and becomes Cl-; in hydrogen chloride it shares a pair and stays neutral',
            'In potassium chloride it shares a pair with the metal; in hydrogen chloride it takes an electron from hydrogen',
            'In both compounds chlorine shares a pair of electrons, so no ion is formed in either of them',
        ],
        "correct_index": 1,
        "why": 'Potassium is a metal and hands an electron over; hydrogen is a non-metal, so chlorine can only share with it.',
    },
    {
        "id": 'ks4-chemical-bonds-h22',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why knowing that a substance is made of two non-metals lets you predict its bonding but not its melting point.',
        "options": [
            'Because covalent substances have no fixed melting point, so it cannot be predicted from anything',
            'Because two non-metals may bond covalently or ionically, so the melting point could take any value at all',
            'Because the melting point of a covalent substance depends only on how many atoms its formula contains',
            'Because two non-metals always bond covalently, but the melting point depends on whether the covalent bonds run through a giant structure or stop at the edge of small molecules',
        ],
        "correct_index": 3,
        "why": 'CO2 and SiO2 are both two non-metals and both covalent, yet one is a gas and the other melts near 1710 °C.',
    },
    {
        "id": 'ks4-chemical-bonds-h23',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'State which of the three types of bonding produce positive ions, and explain why the third does not.',
        "options": [
            'All three do, but the positive ions in a covalent substance are too small to be detected',
            'Covalent and metallic both do; ionic does not, because its electrons are simply transferred across rather than lost',
            'Only ionic does; metallic leaves neutral atoms, because the electrons stay inside the metal structure',
            'Ionic and metallic both do; covalent does not, because a shared pair is counted by both atoms and neither loses charge',
        ],
        "correct_index": 3,
        "why": 'Ionic and metallic bonding both strip outer electrons from atoms; sharing moves no electron away from either atom.',
    },
    {
        "id": 'ks4-chemical-bonds-h24',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Suggest why the idea of reaching a full outer shell explains the bonding of Group 2 and Group 6 atoms but predicts no bonding for Group 0.',
        "options": [
            'Because Group 0 atoms are too large for any other atom to reach their outer shell electrons',
            'Because Group 0 atoms have full outer shells already, so they have nothing to gain by bonding',
            'Because Group 0 atoms hold eight outer electrons, and eight is too many for any atom to accept',
            'Because Group 0 atoms are unreactive gases, and a gas is unable to form bonds of any kind',
        ],
        "correct_index": 1,
        "why": 'Bonding is driven by the need for a full outer shell, and a Group 0 atom already has one.',
    },
    {
        "id": 'ks4-chemical-bonds-h25',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Evaluate this statement: "Covalent bonding happens because non-metal atoms are unable to form ions."',
        "options": [
            'It is correct: a non-metal atom cannot carry a charge, so sharing is the only option open to it',
            'It is wrong: non-metals do form ions when a metal supplies the electrons, but between two non-metals neither gives any up',
            'It is wrong: non-metals form ions easily, and covalent bonding happens only in metals',
            'It is correct: only metals can form ions, which is why every ionic compound is made of two metals',
        ],
        "correct_index": 1,
        "why": 'Chloride and oxide ions are non-metal ions; covalent bonding happens because neither of two non-metals will donate.',
    },
    {
        "id": 'ks4-chemical-bonds-h26',
        "subtopic_slug": 'chemical-bonds',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A newly discovered element sits in Group 2. Predict the bonding in the compound it forms with fluorine, and the bonding in a block of the element itself.',
        "options": [
            'Covalent with fluorine, because both need electrons; ionic in the block, because the atoms form ions',
            'Ionic with fluorine, because a metal meets a non-metal; ionic in the block as well, because a metal always contains ions of its own',
            'Metallic with fluorine, because the metal imposes its bonding; covalent in the block, because the atoms are identical',
            'Ionic with fluorine, because a metal meets a non-metal; metallic in the block, because only metal atoms are present',
        ],
        "correct_index": 3,
        "why": 'Group 2 is a metal, so with fluorine it transfers electrons, and on its own it releases them into a delocalised sea.',
    },
]
