"""Chemistry · Bonding, structure and properties — the MRB-338 expansion for `metallic-bonding`.

This leaf is the MODEL and not its applications: where the delocalised
electrons came from, what the positive ions are doing, and what exactly is
attracted to what. The applied and comparative rows — choosing a metal for a
job, the named alloys, thermal conduction in a pan — belong to `metals-alloys`
and are deliberately left there, so that the two leaves of one topic do not ask
the same thing twice.

The weight therefore sits on the electron sea: how many electrons an atom puts
into it, what charge that leaves on the ion, why ions of one charge do not
repel each other apart, and why the sea keeps holding a layer that has moved.
Melting points across Group 1 and across the metals carry the reasoning rows;
sodium, iron and tungsten are avoided because the rows already shipped use them.
"""

TOPIC = "bonding"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": "ks4-metallic-bonding-e05",
        "subtopic_slug": "metallic-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the two kinds of particle present in a metallic structure.",
        "options": [
            "Positive ions and delocalised electrons",
            "Positive ions and negative ions",
            "Neutral atoms and delocalised electrons",
            "Neutral atoms and negative ions",
        ],
        "correct_index": 0,
        "why": "A metal is a lattice of positive ions sitting in a sea of delocalised electrons, and nothing else.",
    },
    {
        "id": "ks4-metallic-bonding-e06",
        "subtopic_slug": "metallic-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State where the delocalised electrons in a metal came from.",
        "options": [
            "From the nucleus of each metal atom",
            "From the outer shell of each metal atom",
            "From the air surrounding the metal",
            "From the inner shells of each metal atom",
        ],
        "correct_index": 1,
        "why": "Each metal atom releases the electrons in its outer shell, and those electrons become delocalised.",
    },
    {
        "id": "ks4-metallic-bonding-e07",
        "subtopic_slug": "metallic-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how the positive ions in a metal are arranged.",
        "options": [
            "At random, drifting past one another as they please",
            "In pairs, each ion bonded to one partner ion",
            "In a regular lattice of rows and layers",
            "In separate small molecules of a fixed size and shape",
        ],
        "correct_index": 2,
        "why": "The positive ions sit in a regular repeating lattice, arranged in layers that can slide over one another.",
    },
    {
        "id": "ks4-metallic-bonding-e08",
        "subtopic_slug": "metallic-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State whether a metal's structure contains separate molecules.",
        "options": [
            "Yes, each of two atoms joined by a shared pair",
            "No, the lattice runs throughout the whole sample",
            "Yes, but only once the metal has been melted",
            "Yes, each holding a fixed number of atoms",
        ],
        "correct_index": 1,
        "why": "A metal is a giant structure: the lattice of ions and the electron sea continue through the sample, so there are no molecules.",
    },
    {
        "id": "ks4-metallic-bonding-e09",
        "subtopic_slug": "metallic-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State whether the metallic bond is strong or weak, and give the reason.",
        "options": [
            "Strong, because the attraction between the ions and the sea is large",
            "Weak, because the electrons are quite free to wander away from the ions",
            "Weak, because nothing joins one metal ion directly to the next one in the lattice",
            "Strong, because each ion is joined to its neighbour by a shared pair",
        ],
        "correct_index": 0,
        "why": "The electrostatic attraction between the positive ions and the sea of delocalised electrons is strong.",
    },
    {
        "id": "ks4-metallic-bonding-e10",
        "subtopic_slug": "metallic-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State which particles in a solid metal stay in fixed positions.",
        "options": [
            "The delocalised electrons",
            "The positive metal ions",
            "Both the ions and the electrons",
            "Neither the ions nor the electrons",
        ],
        "correct_index": 1,
        "why": "The positive ions hold their places in the lattice; it is the delocalised electrons that move.",
    },
    {
        "id": "ks4-metallic-bonding-e11",
        "subtopic_slug": "metallic-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the particle that a metal atom becomes once it has given up its outer electrons.",
        "options": [
            "A neutron",
            "A negative ion",
            "A positive ion",
            "A neutral atom still",
        ],
        "correct_index": 2,
        "why": "Losing negative electrons leaves more protons than electrons, so the particle left behind is a positive ion.",
    },
    {
        "id": "ks4-metallic-bonding-e12",
        "subtopic_slug": "metallic-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the model of metallic bonding in which ions are pictured sitting in a sea.",
        "options": [
            "The shared pair model",
            "The plum pudding model",
            "The lattice transfer model",
            "The electron sea model",
        ],
        "correct_index": 3,
        "why": "Metallic bonding is described by the electron sea model: positive ions surrounded by freely moving electrons.",
    },
    {
        "id": "ks4-metallic-bonding-s05",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A metal is cooled to a very low temperature. Predict whether it still conducts electricity, and explain.",
        "options": [
            "Yes, because its delocalised electrons are still free to move",
            "No, cooling locks the electrons in place",
            "No, because a current needs the metal to be warm to flow",
            "Yes, cooling frees more electrons",
        ],
        "correct_index": 0,
        "why": "Cooling does not remove the delocalised electrons or fix them in place, so the metal goes on conducting.",
    },
    {
        "id": "ks4-metallic-bonding-s06",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain what happens inside a metal as it is bent, so that it does not snap.",
        "options": [
            "The bonds between neighbouring ions bend without snapping apart",
            "Layers of ions slide, and the electron sea re-surrounds them",
            "The ions are soft enough to be squashed by the bending force",
            "The electrons are pushed aside, letting the ions pass each other",
        ],
        "correct_index": 1,
        "why": "Bending shifts whole layers of positive ions, and the delocalised electrons surround them in their new places.",
    },
    {
        "id": "ks4-metallic-bonding-s07",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why far more energy is needed to boil a metal than to melt it.",
        "options": [
            "Boiling pulls the ions right away from the electron sea",
            "Boiling has to break the covalent bonds between the ions",
            "Boiling removes the delocalised electrons from the metal first",
            "Boiling turns the positive ions into neutral atoms again",
        ],
        "correct_index": 0,
        "why": "Melting only breaks up the regular lattice, while boiling has to separate the ions from the electron sea altogether.",
    },
    {
        "id": "ks4-metallic-bonding-s08",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a metal transfers thermal energy quickly.",
        "options": [
            "Its positive ions travel from the hot end to the cool end carrying energy",
            "Its lattice is so very tightly packed that the energy passes straight through it",
            "Its surface is shiny, and a shiny surface takes in thermal energy more quickly",
            "Its delocalised electrons carry the energy rapidly through the structure",
        ],
        "correct_index": 3,
        "why": "The delocalised electrons move freely and carry thermal energy from the hot part of the metal to the cooler part.",
    },
    {
        "id": "ks4-metallic-bonding-s09",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Magnesium is in Group 2. State the number of electrons each magnesium atom releases into the electron sea.",
        "options": [
            "2 electrons",
            "1 electron",
            "6 electrons",
            "12 electrons",
        ],
        "correct_index": 0,
        "why": "A Group 2 atom has two electrons in its outer shell, and both are released into the delocalised sea.",
    },
    {
        "id": "ks4-metallic-bonding-s10",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the metallic bond is not described as an attraction between neighbouring atoms.",
        "options": [
            "Because the atoms are too far apart in the lattice to attract each other",
            "Because the attraction acts between the ions and the sea of electrons",
            "Because atoms carry no charge, so no attraction can exist between any of them",
            "Because the attraction acts between one positive ion and the next one",
        ],
        "correct_index": 1,
        "why": "The atoms have become positive ions, and the bond is their attraction to the delocalised electrons around them.",
    },
    {
        "id": "ks4-metallic-bonding-s11",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Potassium is in Group 1. Deduce the charge on each potassium ion in a block of the metal.",
        "options": [
            "1-",
            "2+",
            "1+",
            "7-",
        ],
        "correct_index": 2,
        "why": "A Group 1 atom releases its single outer electron, leaving an ion with a charge of 1+.",
    },
    {
        "id": "ks4-metallic-bonding-s12",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a metal does not fall apart when one of its layers of ions slides.",
        "options": [
            "The ions lock together again as soon as the sliding movement stops",
            "The ions are held by covalent bonds, which stretch rather than snap",
            "The layer slides back to exactly where it started from afterwards",
            "The electron sea always surrounds the ions, wherever they end up",
        ],
        "correct_index": 3,
        "why": "The delocalised electrons surround the ions wherever they sit, so the attraction holding the metal together survives the slide.",
    },
    {
        "id": "ks4-metallic-bonding-s13",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what it means to say that a metal is ductile, and explain why metals are.",
        "options": [
            "It can be drawn into a wire, because its layers of ions can slide",
            "It can be melted easily, because its ions are held only weakly",
            "It can carry a current, because its electrons are free to move about",
            "It can be shattered easily, because its layers of ions are free to slip apart",
        ],
        "correct_index": 0,
        "why": "Ductile means it can be drawn out into a wire, which the sliding of the layers of ions allows.",
    },
    {
        "id": "ks4-metallic-bonding-s14",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Aluminium is in Group 3. Deduce the charge on an aluminium ion in the metal and the number of electrons it gives to the sea.",
        "options": [
            "3- and three electrons",
            "3+ and three electrons",
            "1+ and one electron",
            "5+ and five electrons",
        ],
        "correct_index": 1,
        "why": "A Group 3 atom releases all three outer electrons, so it is left as a 3+ ion.",
    },
    {
        "id": "ks4-metallic-bonding-s15",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain what the word delocalised means when it is used about the electrons in a metal.",
        "options": [
            "They have been removed from the metal and lost to the air around it",
            "They are shared between two atoms, exactly as in a covalent bond",
            "They belong to no one atom and can move through the whole structure",
            "They sit still in fixed places between one metal ion and the next",
        ],
        "correct_index": 2,
        "why": "A delocalised electron is no longer tied to one atom, and is free to move throughout the metal.",
    },
    {
        "id": "ks4-metallic-bonding-s16",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the charge on the electron sea in a metal, and give the reason.",
        "options": [
            "Positive, because it surrounds the ions",
            "Neutral, because the charges cancel",
            "Neutral, because it holds no charges",
            "Negative, because it is made of electrons",
        ],
        "correct_index": 3,
        "why": "The sea consists of electrons, and every electron carries a negative charge.",
    },
    {
        "id": "ks4-metallic-bonding-s17",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A block of metal contains positive ions, yet it carries no overall charge. Explain how both of these can be true.",
        "options": [
            "The negative electrons in the sea exactly balance the positive ions",
            "The ions lose their charge as soon as the block has been formed",
            "The positive charges are hidden deep inside the block, away from the surface",
            "Half of the ions carry a positive charge and half of them a negative one",
        ],
        "correct_index": 0,
        "why": "Every electron in the sea came from an ion, so the negative and positive charges cancel exactly.",
    },
    {
        "id": "ks4-metallic-bonding-s18",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what a correct diagram of metallic bonding should show.",
        "options": [
            "Neutral atoms in a regular pattern with no electrons ever drawn between them",
            "Positive ions in a regular pattern with electrons drawn between them",
            "Positive and negative ions alternating in a regular repeating pattern",
            "Separate molecules of two atoms each, spaced out across the whole page",
        ],
        "correct_index": 1,
        "why": "The diagram needs positive ions marked with their charge, in a regular lattice, with delocalised electrons between them.",
    },
    {
        "id": "ks4-metallic-bonding-s19",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a metal whose ions attract the electron sea more strongly melts at a higher temperature.",
        "options": [
            "The stronger attraction makes the ions themselves much harder to heat",
            "A stronger attraction pulls the ions closer, and closer ions melt later",
            "More energy is needed before the ions can be separated from the sea",
            "The extra attraction stops the delocalised electrons carrying any energy",
        ],
        "correct_index": 2,
        "why": "Melting means overcoming the attraction between the ions and the electron sea, so a stronger attraction needs more energy.",
    },
    {
        "id": "ks4-metallic-bonding-s20",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Calcium melts at 842 °C and potassium at 63 °C. Suggest why calcium has the stronger metallic bonding.",
        "options": [
            "Calcium atoms are heavier, and a heavier ion is harder to pull free",
            "Calcium is a solid and potassium a gas at ordinary room temperature",
            "Calcium sits lower in the periodic table, so its lattice is packed tighter",
            "Calcium releases two electrons per atom and leaves a 2+ ion behind",
        ],
        "correct_index": 3,
        "why": "Each calcium atom gives two electrons to the sea and forms a 2+ ion, so the attraction is much stronger than potassium's.",
    },
    {
        "id": "ks4-metallic-bonding-s21",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a metal still conducts electricity after it has been bent into a new shape.",
        "options": [
            "The same ions and delocalised electrons are present, and the sea is unbroken",
            "Bending warms the metal, which helps the current pass",
            "The bend is too small a change to affect anything inside the metal",
            "The electrons are pushed to the outside of the bend",
        ],
        "correct_index": 0,
        "why": "Bending only moves layers of ions; the delocalised electrons are still there and still free to carry charge.",
    },
    {
        "id": "ks4-metallic-bonding-s22",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what the delocalised electrons do when a voltage is applied across a piece of metal.",
        "options": [
            "They stop moving altogether and hold the positive ions still in their places",
            "They drift through the lattice in one direction, carrying charge",
            "They pair up with the positive ions and travel along with them",
            "They leave the metal entirely and travel through the air instead",
        ],
        "correct_index": 1,
        "why": "A voltage makes the delocalised electrons drift in one direction through the lattice, which is an electric current.",
    },
    {
        "id": "ks4-metallic-bonding-s23",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a metal is described as a giant structure rather than a molecular one.",
        "options": [
            "Because a single piece of metal is far bigger than a single molecule",
            "Because its ions are larger than a molecule's atoms",
            "Because the lattice repeats throughout the sample with no separate molecules",
            "Because it is built from two elements, not one",
        ],
        "correct_index": 2,
        "why": "The lattice of ions and the electron sea continue right through the sample, so there are no separate molecules.",
    },
    {
        "id": "ks4-metallic-bonding-s24",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the metallic bond becomes stronger as the charge on the metal ion increases.",
        "options": [
            "A larger charge makes each ion bigger",
            "A larger charge stops the delocalised electrons moving about freely",
            "A larger charge means fewer electrons have been released to the sea",
            "A larger charge attracts the electron sea more strongly",
        ],
        "correct_index": 3,
        "why": "Electrostatic attraction grows with charge, so a 2+ or 3+ ion holds the electron sea more tightly than a 1+ ion.",
    },
    {
        "id": "ks4-metallic-bonding-s25",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the size of a metal ion affects the strength of the metallic bonding.",
        "options": [
            "A smaller ion lets the sea sit closer to it, so the attraction is stronger",
            "A larger ion carries a larger charge",
            "A larger ion holds more delocalised electrons inside its own shells",
            "A smaller ion has fewer protons to pull with",
        ],
        "correct_index": 0,
        "why": "The closer the electron sea sits to the centre of each ion, the stronger the electrostatic attraction between them.",
    },
    {
        "id": "ks4-metallic-bonding-s26",
        "subtopic_slug": "metallic-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student draws a metallic lattice as neutral atoms with electrons moving between them. Explain the error.",
        "options": [
            "The electrons should be drawn sitting still rather than moving about",
            "The atoms have released their outer electrons, so they are positive ions",
            "The atoms should have been drawn in separate pairs rather than in one lattice",
            "The electrons should have been drawn inside the atoms rather than between them",
        ],
        "correct_index": 1,
        "why": "The electrons in the sea came from the atoms themselves, so what is left in the lattice are positive ions.",
    },
    {
        "id": "ks4-metallic-bonding-h05",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Lithium, sodium and potassium melt at 181 °C, 98 °C and 63 °C. Explain the trend down the group.",
        "options": [
            "The ions grow larger, so the sea sits further out and attracts less strongly",
            "The ions release more electrons each",
            "The ions grow heavier, and a heavier ion is easier to shake loose",
            "The ions grow smaller, leaving less room for the sea",
        ],
        "correct_index": 0,
        "why": "Down Group 1 the ions get larger, so the electron sea is further from each nucleus and the attraction weakens.",
    },
    {
        "id": "ks4-metallic-bonding-h06",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Magnesium melts at 650 °C and sodium at 98 °C, although the two elements are neighbours in the same period. Explain.",
        "options": [
            "Magnesium has more shells of electrons, which holds its lattice together",
            "Magnesium gives two electrons per atom and forms a 2+ ion, not a 1+ one",
            "Magnesium ions are larger, so more of them are packed into the lattice",
            "Magnesium is less reactive, and a less reactive metal always melts higher",
        ],
        "correct_index": 1,
        "why": "Magnesium puts twice as many electrons into the sea and its ions carry twice the charge, so the attraction is far stronger.",
    },
    {
        "id": "ks4-metallic-bonding-h07",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate this statement: 'A metal conducts electricity because its positive ions push the electrons along.'",
        "options": [
            "It is right, because the ions repel the electrons away down the wire",
            "It is right, because the ions and the electrons travel along together",
            "It is wrong: the ions never leave their places and the electrons drift themselves",
            "It is wrong: it is the ions that drift along and the electrons that hold still",
        ],
        "correct_index": 2,
        "why": "The positive ions stay in the lattice; the delocalised electrons move through it under the applied voltage.",
    },
    {
        "id": "ks4-metallic-bonding-h08",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Predict what would happen to a metal's electrical conductivity if its outer electrons stayed on their own atoms, and explain.",
        "options": [
            "It would improve, because each atom could pass its electron to the next",
            "It would be unchanged, because a current does not depend on electrons",
            "It would improve, because the atoms would be closer to one another",
            "It would stop, because there would be no charged particles free to move",
        ],
        "correct_index": 3,
        "why": "Conduction needs charged particles free to move, and in a metal those are precisely the delocalised electrons.",
    },
    {
        "id": "ks4-metallic-bonding-h09",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Molten copper still conducts electricity. Deduce what this shows about its delocalised electrons.",
        "options": [
            "They are still present and still free to move and carry charge",
            "They are destroyed on melting and replaced by moving positive ions",
            "They become fixed in place, and the ions carry the current instead",
            "They leave the copper and travel through the air above the melt",
        ],
        "correct_index": 0,
        "why": "Melting breaks up the regular lattice but does not remove the delocalised electrons, so the liquid metal still conducts.",
    },
    {
        "id": "ks4-metallic-bonding-h10",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the metallic bond has no particular direction, unlike a covalent bond.",
        "options": [
            "Because the metal ions are much too far apart for any direction to matter",
            "Because the electron sea surrounds every ion equally on all sides",
            "Because the ions carry no charge, and only charge gives a direction",
            "Because a metal contains only one element rather than two of them",
        ],
        "correct_index": 1,
        "why": "The sea surrounds each ion from every side, so the attraction acts in all directions rather than towards one partner.",
    },
    {
        "id": "ks4-metallic-bonding-h11",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A sample of magnesium contains 500 magnesium atoms. Determine the number of electrons in its delocalised sea.",
        "options": [
            "250 electrons",
            "500 electrons",
            "1000 electrons",
            "6000 electrons",
        ],
        "correct_index": 2,
        "why": "Each magnesium atom releases two outer electrons, so 500 atoms supply 1000 electrons to the sea.",
    },
    {
        "id": "ks4-metallic-bonding-h12",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate this statement: 'Metallic bonding is really a kind of covalent bonding, because the electrons are shared in both.'",
        "options": [
            "It is right, because in both of them no electrons are transferred",
            "It is right, because both bonds are formed from pairs of electrons",
            "It is wrong: no electrons are shared in a metal, they are transferred",
            "It is wrong: a covalent pair is held between two particular atoms",
        ],
        "correct_index": 3,
        "why": "A covalent pair is localised between two atoms, while a metal's electrons are delocalised across the whole lattice.",
    },
    {
        "id": "ks4-metallic-bonding-h13",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A piece of metal is hammered into a thin sheet. Explain why its electrical conductivity is unchanged.",
        "options": [
            "Because the same ions and the same delocalised electrons are still present",
            "Because the hammering adds energy, which makes up for any loss of conduction",
            "Because a thinner sheet lets the current travel over a much shorter distance",
            "Because the hammering packs the electrons more tightly into the sheet",
        ],
        "correct_index": 0,
        "why": "Hammering only rearranges the layers of ions; the delocalised electrons are unchanged, so conduction is unchanged.",
    },
    {
        "id": "ks4-metallic-bonding-h14",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a metal whose ions carry a larger charge tends to be harder as well as higher melting.",
        "options": [
            "The larger charge makes the ions repel one another into a rigid pattern",
            "The stronger attraction resists both separating the ions and shifting them",
            "The larger charge leaves fewer electrons in the sea to lubricate the layers",
            "A bigger charge makes each one of the ions physically larger and stiffer",
        ],
        "correct_index": 1,
        "why": "Both melting and deforming mean moving ions against their attraction to the sea, so a stronger attraction resists each.",
    },
    {
        "id": "ks4-metallic-bonding-h15",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the number of electrons released into the sea by 100 sodium atoms with the number released by 100 aluminium atoms.",
        "options": [
            "100 against 100",
            "300 against 100",
            "100 against 300",
            "100 against 200",
        ],
        "correct_index": 2,
        "why": "Sodium is Group 1 and releases one electron per atom; aluminium is Group 3 and releases three.",
    },
    {
        "id": "ks4-metallic-bonding-h16",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Chromium melts at 1907 °C and caesium at 28 °C. Deduce which has the stronger metallic bonding, and explain how you know.",
        "options": [
            "Caesium, because a lower melting point means the ions are held tighter",
            "Caesium, because its ions are larger and so take up more of the lattice",
            "Neither, because the metallic bond is the same strength in every metal",
            "Chromium, because far more energy is needed to separate ions from sea",
        ],
        "correct_index": 3,
        "why": "Melting point measures the energy needed to overcome the attraction, so the higher melting metal is the more strongly bonded.",
    },
    {
        "id": "ks4-metallic-bonding-h17",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the electrical conductivity of a metal is described as a property of its structure rather than of its atoms.",
        "options": [
            "Because conduction needs a lattice and a sea, which many atoms make together",
            "Because one metal atom on its own already holds a sea of delocalised electrons",
            "Because the atoms of a metal are identical to those of a non-metal",
            "Because each atom carries its own conductivity, which then simply adds up",
        ],
        "correct_index": 0,
        "why": "Delocalised electrons and a lattice of ions only exist once many atoms are bonded, so conduction is a property of the structure.",
    },
    {
        "id": "ks4-metallic-bonding-h18",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate this statement: 'A metal contains no charged particles, because a block of metal carries no charge.'",
        "options": [
            "It is right, because the atoms in a metal never lose any electrons",
            "It is wrong: it holds positive ions and electrons whose charges cancel",
            "It is right, because the delocalised electrons carry no charge of their own here",
            "It is wrong: it holds positive and negative ions in exactly equal numbers",
        ],
        "correct_index": 1,
        "why": "A metal is full of charged particles; the negative electrons simply balance the positive ions, giving no overall charge.",
    },
    {
        "id": "ks4-metallic-bonding-h19",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the positive ions in a metal do not repel one another apart, although they all carry the same charge.",
        "options": [
            "They sit far too far apart in the lattice for any repulsion between them to be felt",
            "They are held in place by strong covalent bonds to each of their neighbours",
            "The negative electron sea between them attracts them all and holds them",
            "Their repulsion is real but far too weak to matter",
        ],
        "correct_index": 2,
        "why": "The delocalised electrons lie between the ions and attract every one of them, which outweighs the repulsion between the ions.",
    },
    {
        "id": "ks4-metallic-bonding-h20",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Gold can be beaten into a sheet only a few atoms thick. Deduce what this shows about the layers of ions in gold.",
        "options": [
            "They break away from one another and are then pressed back together again",
            "They are held by bonds that stretch a long way before they finally snap",
            "They are squashed thinner and thinner as the hammering goes on",
            "They slide over one another very easily while the sea keeps holding them",
        ],
        "correct_index": 3,
        "why": "Gold's layers of positive ions slip past each other readily, and the electron sea re-surrounds them, so the sheet holds together.",
    },
    {
        "id": "ks4-metallic-bonding-h21",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Predict the effect on a metal's melting point of replacing its ions with ions of the same charge but twice the radius.",
        "options": [
            "It would fall, because the sea sits further out and attracts less strongly",
            "It would rise, because a larger ion needs more energy before it can be moved aside",
            "It would be unchanged, because the charge carried by the ions has not altered",
            "It would rise, because larger ions pack more tightly",
        ],
        "correct_index": 0,
        "why": "Electrostatic attraction weakens with distance, so larger ions of the same charge hold the electron sea less tightly.",
    },
    {
        "id": "ks4-metallic-bonding-h22",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A sample of aluminium contains 200 aluminium ions. Deduce the total charge held by its electron sea.",
        "options": [
            "200-",
            "600-",
            "600+",
            "200+",
        ],
        "correct_index": 1,
        "why": "Each aluminium ion is 3+, so 200 ions carry 600+, and the sea must carry 600- for the metal to be neutral.",
    },
    {
        "id": "ks4-metallic-bonding-h23",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student says a metal melts when its delocalised electrons escape from the structure. Evaluate this statement.",
        "options": [
            "It is right, because the ions fall apart once the electrons have gone",
            "It is right, because the electrons carry the heat energy out of the metal",
            "It is wrong: molten metal still conducts, so the electrons never left it",
            "It is wrong: the electrons escape long before the metal's melting point is reached",
        ],
        "correct_index": 2,
        "why": "A molten metal conducts electricity, which shows the delocalised electrons remain; melting only breaks up the regular lattice.",
    },
    {
        "id": "ks4-metallic-bonding-h24",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the particles present in a solid block of magnesium with those present in the same magnesium once it has melted.",
        "options": [
            "Ions and electrons in the solid; neutral atoms only in the melt",
            "Neutral atoms in the solid; ions and electrons only in the melt",
            "Both hold neutral atoms, but the melt has them more widely spread",
            "Both hold ions and electrons, but the melt has no fixed lattice",
        ],
        "correct_index": 3,
        "why": "Melting does not change the particles: Mg2+ ions and delocalised electrons are present in both, but the lattice is no longer regular.",
    },
    {
        "id": "ks4-metallic-bonding-h25",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a diagram showing the electrons fixed in place between the ions would be a misleading picture of a metal.",
        "options": [
            "Because the electrons are delocalised, and only their movement conducts",
            "Because the electrons should be drawn inside the ions instead",
            "Because the ions ought to be drawn moving about rather than the electrons",
            "Because a metal holds far too many electrons for a diagram to show them",
        ],
        "correct_index": 0,
        "why": "Fixed electrons could not carry a current; the model depends on their being free to move through the whole structure.",
    },
    {
        "id": "ks4-metallic-bonding-h26",
        "subtopic_slug": "metallic-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A metal is described as having a giant structure. Explain what the word giant is telling you.",
        "options": [
            "That its atoms are unusually large compared with those of any non-metal",
            "That the lattice repeats through the sample, with no set number of ions",
            "That any piece of the metal has to be large enough to be seen by the naked eye",
            "That its ions carry a larger charge than the ions of other substances",
        ],
        "correct_index": 1,
        "why": "Giant describes the structure, not the particles: the lattice continues throughout with no fixed number of ions in it.",
    },
]
