"""Chemistry · Bonding, structure and properties — the MRB-338 expansion for `covalent-bonding`.

This leaf is the accountancy of the shared pair: how many pairs an atom needs,
how many it therefore makes, and what is left over on the atom once it has made
them. So the weight sits on counting — bonds, shared pairs, lone pairs and
outer electrons — because most of what the specification asks about covalent
bonding is one of those four counts asked in a different voice.

The rest goes to the two errors a pupil makes first: that sharing is a slow
kind of transfer, and that a dot and a cross mark two different sorts of
electron. Named molecules carry the applied rows — hydrazine, chloroform,
hydrogen cyanide, methanal, propene, ethyne, phosphine and hydrogen selenide —
so the same group-number arithmetic is met in compounds the course never names.
"""

TOPIC = "bonding"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": "ks4-covalent-bonding-e05",
        "subtopic_slug": "covalent-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the number of electron pairs shared in one single covalent bond.",
        "options": [
            "One pair, shared between the two bonded atoms",
            "Two pairs, one supplied by each of the atoms",
            "Four pairs, one for each shell that surrounds them",
            "No pairs, because the electrons are handed over",
        ],
        "correct_index": 0,
        "why": "A single covalent bond is one shared pair of electrons; two shared pairs would make it a double bond.",
    },
    {
        "id": "ks4-covalent-bonding-e06",
        "subtopic_slug": "covalent-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the part of an atom that supplies the electrons used for covalent bonding.",
        "options": [
            "The outer shell",
            "The nucleus",
            "The innermost shell",
            "The neutrons",
        ],
        "correct_index": 0,
        "why": "Only the electrons in an atom's outer shell take part in bonding; the inner shells and the nucleus are untouched.",
    },
    {
        "id": "ks4-covalent-bonding-e07",
        "subtopic_slug": "covalent-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the number of electrons in one shared pair.",
        "options": [
            "1 electron",
            "4 electrons",
            "2 electrons",
            "8 electrons",
        ],
        "correct_index": 2,
        "why": "A pair is two electrons, and both of them are counted by each of the two bonded atoms.",
    },
    {
        "id": "ks4-covalent-bonding-e08",
        "subtopic_slug": "covalent-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name a pair of outer electrons on an atom that is not used for bonding.",
        "options": [
            "A delocalised pair, free to roam right through the whole substance",
            "A transferred pair, handed to a second atom",
            "A bonding pair, counted by both of the atoms",
            "A lone pair, which stays on that one atom",
        ],
        "correct_index": 3,
        "why": "A pair of outer electrons not used in a bond is called a lone pair, and it belongs to one atom only.",
    },
    {
        "id": "ks4-covalent-bonding-e09",
        "subtopic_slug": "covalent-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the number of covalent bonds a hydrogen atom can form.",
        "options": [
            "1, because one shared pair fills its only shell",
            "2, because a shell is full once it holds eight electrons",
            "4, the same number as a carbon atom forms",
            "0, because it has too few electrons to share",
        ],
        "correct_index": 0,
        "why": "Hydrogen has one shell, which is full at two electrons, so one shared pair is all it can use.",
    },
    {
        "id": "ks4-covalent-bonding-e10",
        "subtopic_slug": "covalent-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the molecule in which two atoms share three pairs of electrons.",
        "options": [
            "Nitrogen, N2",
            "Oxygen, O2",
            "Hydrogen, H2",
            "Chlorine, Cl2",
        ],
        "correct_index": 0,
        "why": "Each nitrogen atom needs three more electrons, so the two atoms share three pairs and form a triple bond.",
    },
    {
        "id": "ks4-covalent-bonding-e11",
        "subtopic_slug": "covalent-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "An oxygen atom has six electrons in its outer shell. State the number of covalent bonds it forms.",
        "options": [
            "6 bonds",
            "8 bonds",
            "2 bonds",
            "1 bond",
        ],
        "correct_index": 2,
        "why": "Oxygen needs two more electrons to reach eight, so it forms two covalent bonds.",
    },
    {
        "id": "ks4-covalent-bonding-e12",
        "subtopic_slug": "covalent-bonding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a single line drawn between two atoms in a displayed formula represents.",
        "options": [
            "One electron passed from one atom to the other atom",
            "The empty space that separates the two bonded atoms from each other",
            "One full outer shell belonging to the left-hand atom",
            "One shared pair of electrons, that is one covalent bond",
        ],
        "correct_index": 3,
        "why": "Each line in a displayed formula stands for one covalent bond, which is one shared pair of electrons.",
    },
    {
        "id": "ks4-covalent-bonding-s05",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how the electrons are shared in a molecule of water, H2O.",
        "options": [
            "Oxygen forms two bonds, one with each hydrogen atom",
            "Oxygen forms one bond and the two hydrogen atoms then bond to each other",
            "Oxygen hands two electrons to the hydrogen atoms, which keep them",
            "Each hydrogen forms two bonds to the oxygen",
        ],
        "correct_index": 0,
        "why": "Oxygen needs two more electrons, so it shares one pair with each hydrogen atom and reaches eight.",
    },
    {
        "id": "ks4-covalent-bonding-s06",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A nitrogen atom has five outer electrons. Determine the number of bonding pairs and lone pairs around the nitrogen atom in ammonia.",
        "options": [
            "Five bonding pairs and no lone pairs",
            "Three bonding pairs and one lone pair",
            "Two bonding pairs and two lone pairs",
            "Four bonding pairs and one lone pair",
        ],
        "correct_index": 1,
        "why": "Nitrogen uses three of its five outer electrons for bonds to hydrogen, leaving the other two as one lone pair.",
    },
    {
        "id": "ks4-covalent-bonding-s07",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a hydrogen atom forms one covalent bond and no more.",
        "options": [
            "It has only one electron, and an atom can share no more than it owns",
            "It is the smallest atom there is, so there is no room around it for a second bond",
            "Its first shell is full at two electrons, so one shared pair finishes it",
            "It sits in Group 1, so it needs seven more electrons",
        ],
        "correct_index": 2,
        "why": "Hydrogen's only shell holds two electrons, and one shared pair already brings its count to two.",
    },
    {
        "id": "ks4-covalent-bonding-s08",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Phosphorus is in Group 5. Deduce the formula of the compound it forms with hydrogen.",
        "options": [
            "PH5",
            "P5H",
            "PH2",
            "PH3",
        ],
        "correct_index": 3,
        "why": "A Group 5 atom has five outer electrons and needs three more, so it forms three bonds to hydrogen.",
    },
    {
        "id": "ks4-covalent-bonding-s09",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Sulfur is in Group 6. Deduce the formula of hydrogen sulfide.",
        "options": [
            "H2S",
            "H6S",
            "HS",
            "H4S",
        ],
        "correct_index": 0,
        "why": "Sulfur has six outer electrons and needs two more, so two hydrogen atoms each share a pair with it.",
    },
    {
        "id": "ks4-covalent-bonding-s10",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Ethene, C2H4, holds one carbon-carbon double bond and four carbon-hydrogen single bonds. Determine the total number of shared electron pairs.",
        "options": [
            "4 shared pairs",
            "6 shared pairs",
            "5 shared pairs",
            "8 shared pairs",
        ],
        "correct_index": 1,
        "why": "The double bond counts as two shared pairs, and the four single bonds add four more, giving six.",
    },
    {
        "id": "ks4-covalent-bonding-s11",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a carbon atom forms four covalent bonds.",
        "options": [
            "It has four shells of electrons, and each of those shells contributes one bond",
            "It sits in Period 2, and every Period 2 atom makes four bonds",
            "It holds four outer electrons and needs four more to reach eight",
            "It gives four electrons away and then takes four different ones back",
        ],
        "correct_index": 2,
        "why": "Carbon has four outer electrons and needs four more for a full shell, so it shares four pairs.",
    },
    {
        "id": "ks4-covalent-bonding-s12",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the two atoms in a fluorine molecule share one pair of electrons rather than two.",
        "options": [
            "A second shared pair would have to come out of the shell below",
            "Each atom has seven outer electrons and needs only one more",
            "Fluorine is a gas at room temperature, and a gas can form only single bonds",
            "Sharing two pairs would leave the molecule with an overall charge",
        ],
        "correct_index": 1,
        "why": "Each fluorine atom is one electron short of eight, so a single shared pair fills both outer shells.",
    },
    {
        "id": "ks4-covalent-bonding-s13",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A water molecule has two bonding pairs and two lone pairs around its oxygen atom. Determine the number of outer electrons the oxygen atom counts.",
        "options": [
            "8 electrons",
            "4 electrons",
            "6 electrons",
            "2 electrons",
        ],
        "correct_index": 0,
        "why": "Four pairs around the atom is eight electrons, and a shared pair is counted in full by both atoms.",
    },
    {
        "id": "ks4-covalent-bonding-s14",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the number of bonding pairs around the central atom in methane with the number in water.",
        "options": [
            "Two in methane and four in water",
            "Four in methane and two in water",
            "Four in both",
            "One in methane and one in water",
        ],
        "correct_index": 1,
        "why": "Carbon needs four more electrons and forms four bonds; oxygen needs two more and forms two.",
    },
    {
        "id": "ks4-covalent-bonding-s15",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Ethane has the formula C2H6, with a single bond between the two carbon atoms. Determine the total number of covalent bonds in one molecule.",
        "options": [
            "6 bonds",
            "8 bonds",
            "7 bonds",
            "4 bonds",
        ],
        "correct_index": 2,
        "why": "Six carbon-hydrogen bonds plus the one carbon-carbon bond makes seven bonds in total.",
    },
    {
        "id": "ks4-covalent-bonding-s16",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a chlorine atom forms one covalent bond while a carbon atom forms four.",
        "options": [
            "Chlorine atoms are the heavier of the two, and a heavier atom forms fewer bonds",
            "Chlorine is a gas and carbon a solid, and solids form more bonds",
            "Chlorine has one outer electron while carbon has four of them",
            "Chlorine needs one more electron and carbon needs four more",
        ],
        "correct_index": 3,
        "why": "The number of bonds equals the number of electrons the atom still needs: one for chlorine, four for carbon.",
    },
    {
        "id": "ks4-covalent-bonding-s17",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "In tetrachloromethane, CCl4, state the number of electrons the carbon atom counts in its outer shell.",
        "options": [
            "8 electrons",
            "4 electrons",
            "16 electrons",
            "12 electrons",
        ],
        "correct_index": 0,
        "why": "Four bonding pairs around the carbon atom is eight electrons, which is a full outer shell.",
    },
    {
        "id": "ks4-covalent-bonding-s18",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student draws methane with four dots on the carbon and one cross on each hydrogen, none of them between the atoms. Explain what is wrong.",
        "options": [
            "The crosses ought to be dots as well, since all electrons are identical",
            "Each electron pair must be drawn between two atoms, as a shared pair",
            "The carbon should be drawn carrying eight dots before any bonding starts",
            "The four hydrogen atoms should have been drawn touching one another in a ring",
        ],
        "correct_index": 1,
        "why": "A covalent bond is drawn as a pair sitting between the two atoms, showing that both of them count it.",
    },
    {
        "id": "ks4-covalent-bonding-s19",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Hydrogen cyanide, HCN, has a single bond from hydrogen to carbon and a triple bond from carbon to nitrogen. Determine the total number of shared pairs.",
        "options": [
            "2 shared pairs",
            "3 shared pairs",
            "4 shared pairs",
            "6 shared pairs",
        ],
        "correct_index": 2,
        "why": "One pair in the single bond plus three in the triple bond gives four shared pairs altogether.",
    },
    {
        "id": "ks4-covalent-bonding-s20",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why an oxygen molecule contains a double bond while a chlorine molecule contains a single bond.",
        "options": [
            "Oxygen molecules are the smaller, so their atoms are pulled in closer",
            "Oxygen atoms have two shells of electrons while chlorine atoms have three of them",
            "Oxygen is the more reactive element, and reactive elements bond twice",
            "Each oxygen atom needs two more electrons and each chlorine only one",
        ],
        "correct_index": 3,
        "why": "An atom forms one bond for every electron it still needs: two for oxygen, one for chlorine.",
    },
    {
        "id": "ks4-covalent-bonding-s21",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Methanol has the formula CH3OH. Deduce the total number of covalent bonds in one molecule.",
        "options": [
            "5 bonds",
            "6 bonds",
            "4 bonds",
            "3 bonds",
        ],
        "correct_index": 0,
        "why": "Three carbon-hydrogen bonds, one carbon-oxygen bond and one oxygen-hydrogen bond make five in total.",
    },
    {
        "id": "ks4-covalent-bonding-s22",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student says that in a covalent bond one atom lends an electron to the other and later takes it back. Explain why this is wrong.",
        "options": [
            "The electron is lent for good, and so it is never taken back",
            "Nothing is lent: the pair sits between the atoms and both count it",
            "Two electrons are lent rather than one, and both are returned together",
            "The lending happens only in molecules built from two different elements",
        ],
        "correct_index": 1,
        "why": "In covalent bonding the pair is shared continuously between the two atoms; no electron changes owner.",
    },
    {
        "id": "ks4-covalent-bonding-s23",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Carbon dioxide is written O=C=O. State the total number of covalent bonds the carbon atom forms.",
        "options": [
            "2 bonds",
            "6 bonds",
            "4 bonds",
            "8 bonds",
        ],
        "correct_index": 2,
        "why": "Each double bond counts as two covalent bonds, so the carbon atom forms four in total.",
    },
    {
        "id": "ks4-covalent-bonding-s24",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the number of electrons shared in a single bond with the number shared in a triple bond.",
        "options": [
            "1 against 3",
            "2 against 3",
            "4 against 8",
            "2 against 6",
        ],
        "correct_index": 3,
        "why": "One shared pair is two electrons, so three shared pairs is six.",
    },
    {
        "id": "ks4-covalent-bonding-s25",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two hydrogen atoms bond together. State what happens to the total number of electrons present, and explain how each atom reaches a full shell.",
        "options": [
            "It stays at two, and each atom counts both of them",
            "It doubles to four, because the sharing creates a second pair of them",
            "It falls to one, since an electron is given away",
            "It rises to eight, which is the number a full outer shell holds",
        ],
        "correct_index": 0,
        "why": "No electrons are made or lost; the two are shared, and each hydrogen atom counts both, filling its shell.",
    },
    {
        "id": "ks4-covalent-bonding-s26",
        "subtopic_slug": "covalent-bonding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a covalent bond cannot be broken by warming a substance gently.",
        "options": [
            "Warming makes the shared pair move faster, which tightens the bond further",
            "A covalent bond is strong and takes a lot of energy to break",
            "Heat cannot reach the shared pair, which sits inside the molecule",
            "The bond carries no charge, and only charged particles respond to heat",
        ],
        "correct_index": 1,
        "why": "Covalent bonds are strong, so a large amount of energy is needed to break one.",
    },
    {
        "id": "ks4-covalent-bonding-h05",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Propene, CH2=CHCH3, has one carbon-carbon double bond and one carbon-carbon single bond. Determine the total number of shared electron pairs in one molecule.",
        "options": [
            "9 pairs",
            "6 pairs",
            "8 pairs",
            "12 pairs",
        ],
        "correct_index": 0,
        "why": "Six carbon-hydrogen pairs, two for the double bond and one for the single bond gives nine pairs.",
    },
    {
        "id": "ks4-covalent-bonding-h06",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Deduce which needs more energy to be split into separate atoms, a molecule of oxygen or a molecule of fluorine, and explain.",
        "options": [
            "Fluorine, because its atoms are the smaller and so sit rather closer together",
            "Oxygen, because two shared pairs hold its atoms rather than one",
            "Fluorine, because it is the more reactive of the two elements here",
            "Neither, because every covalent bond takes the same energy to break",
        ],
        "correct_index": 1,
        "why": "Oxygen atoms each need two electrons and form a double bond, while fluorine forms only a single bond.",
    },
    {
        "id": "ks4-covalent-bonding-h07",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Hydrazine, N2H4, has a single bond between its two nitrogen atoms and two hydrogen atoms on each. Determine the number of lone pairs in one molecule.",
        "options": [
            "4 lone pairs",
            "0 lone pairs",
            "2 lone pairs",
            "6 lone pairs",
        ],
        "correct_index": 2,
        "why": "Each nitrogen forms three bonds, using three of its five outer electrons, so each keeps one lone pair.",
    },
    {
        "id": "ks4-covalent-bonding-h08",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate this statement: 'A double bond is twice as easy to break as a single bond, because it is made of two separate parts.'",
        "options": [
            "It is right, because splitting one of the two pairs breaks the whole bond apart",
            "It is right, because each of the two pairs holds half as strongly as one alone",
            "It is wrong: a double bond takes less energy to break, not more",
            "It is wrong: two shared pairs hold the atoms, so more energy is needed",
        ],
        "correct_index": 3,
        "why": "Both shared pairs must be broken to separate the atoms, so a double bond is harder to break than a single one.",
    },
    {
        "id": "ks4-covalent-bonding-h09",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Carbon, silicon and germanium are all in Group 4. Predict the formula of the compound each forms with hydrogen.",
        "options": [
            "CH4, SiH4 and GeH4",
            "CH2, SiH2 and GeH2",
            "C4H, Si4H and Ge4H",
            "CH4, SiH3 and GeH2",
        ],
        "correct_index": 0,
        "why": "Every Group 4 atom has four outer electrons and needs four more, so each forms four bonds to hydrogen.",
    },
    {
        "id": "ks4-covalent-bonding-h10",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Phosphine and ammonia have the same arrangement of electron pairs around their central atom. Explain why, using the periodic table.",
        "options": [
            "Both compounds contain hydrogen, which fixes how the pairs sit",
            "Both central atoms sit in Group 5, so each makes three bonds and keeps one lone pair",
            "Both central atoms sit in Period 3, so each has the same shells",
            "Both compounds are gases, and gas molecules sit the same way",
        ],
        "correct_index": 1,
        "why": "Nitrogen and phosphorus are both Group 5, so each has five outer electrons: three bonds and one lone pair.",
    },
    {
        "id": "ks4-covalent-bonding-h11",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Carbon disulfide, CS2, contains only double bonds. Deduce the number of electrons each sulfur atom shares with the carbon atom, and explain.",
        "options": [
            "2 electrons, because a single pair is shared with the partner atom",
            "8 electrons, which is the full outer shell that a sulfur atom ends up with",
            "4 electrons, because sulfur needs two more to fill its shell",
            "6 electrons, matching the six outer electrons sulfur begins with",
        ],
        "correct_index": 2,
        "why": "Sulfur has six outer electrons and needs two more, so it forms a double bond of two shared pairs.",
    },
    {
        "id": "ks4-covalent-bonding-h12",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate this statement: 'Because the two atoms share the pair, each atom ends up with half an electron more than it began with.'",
        "options": [
            "It is right, because half of the shared pair belongs to each of them",
            "It is right, because the pair spends half of its time on each atom",
            "It is wrong: each atom counts one of the two shared electrons as its own",
            "It is wrong: each atom counts both shared electrons, not half of them",
        ],
        "correct_index": 3,
        "why": "A shared pair is counted in full by both atoms, which is how each of them reaches a full outer shell.",
    },
    {
        "id": "ks4-covalent-bonding-h13",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A hydrocarbon molecule contains three carbon atoms and eight hydrogen atoms. Deduce whether it can contain a carbon-carbon double bond, and explain.",
        "options": [
            "No, because every carbon already uses all four bonds on single bonds",
            "Yes, because three carbon atoms leave room for exactly one double bond",
            "Yes, because eight hydrogen atoms is far too many for single bonds alone",
            "No, because a double bond needs an even number of carbon atoms",
        ],
        "correct_index": 0,
        "why": "Eight hydrogen atoms plus two carbon-carbon single bonds uses all four bonds on every carbon, leaving none spare.",
    },
    {
        "id": "ks4-covalent-bonding-h14",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the number of shared pairs in one molecule of carbon dioxide with the number in one molecule of water.",
        "options": [
            "2 in carbon dioxide and 4 in water",
            "4 in carbon dioxide and 2 in water",
            "3 in carbon dioxide and 3 in water",
            "4 in carbon dioxide and 4 in water",
        ],
        "correct_index": 1,
        "why": "Carbon dioxide has two double bonds, which is four pairs; water has two single bonds, which is two pairs.",
    },
    {
        "id": "ks4-covalent-bonding-h15",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a dot-and-cross diagram uses two different symbols, although every electron is identical.",
        "options": [
            "To show that shared electrons behave differently from unshared ones",
            "To separate the negative electrons from the positive ones",
            "To record which atom each electron came from, which the diagram would not otherwise show",
            "To mark which electrons can move away from the molecule",
        ],
        "correct_index": 2,
        "why": "The two symbols are a bookkeeping device showing the origin of each electron; the electrons themselves are identical.",
    },
    {
        "id": "ks4-covalent-bonding-h16",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Chloroform has the formula CHCl3, and each chlorine atom forms one covalent bond. Determine the total number of lone pairs on the chlorine atoms.",
        "options": [
            "3 lone pairs",
            "6 lone pairs",
            "12 lone pairs",
            "9 lone pairs",
        ],
        "correct_index": 3,
        "why": "Each chlorine has seven outer electrons and uses one in a bond, leaving three lone pairs, so nine in total.",
    },
    {
        "id": "ks4-covalent-bonding-h17",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Packets of crisps are filled with nitrogen gas rather than air. Suggest why the bonding in the nitrogen molecule makes it suitable.",
        "options": [
            "Its triple bond takes so much energy to break that nitrogen reacts with very little",
            "Its molecules are heavier than the molecules of air, so they settle and seal the bag",
            "Its single bond is a weak one, so the molecules slip easily between the crisps",
            "Its atoms carry no charge, and a particle with no charge cannot spoil food",
        ],
        "correct_index": 0,
        "why": "Three shared pairs hold the nitrogen atoms together, so a great deal of energy is needed before nitrogen will react.",
    },
    {
        "id": "ks4-covalent-bonding-h18",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A molecule contains one carbon atom, two hydrogen atoms and one oxygen atom. Deduce the bonds the carbon atom must form.",
        "options": [
            "Three single bonds to hydrogen and one further single bond to the oxygen",
            "Two single bonds to hydrogen and a double bond to oxygen",
            "Two single bonds to hydrogen and a single bond to the oxygen",
            "One single bond to hydrogen and a triple bond to the oxygen",
        ],
        "correct_index": 1,
        "why": "Carbon must reach four bonds and oxygen two, so two single bonds to hydrogen leave a double bond to oxygen.",
    },
    {
        "id": "ks4-covalent-bonding-h19",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "In hydrogen peroxide, H-O-O-H, each oxygen atom forms two covalent bonds. Determine the number of lone pairs on each oxygen atom.",
        "options": [
            "1 lone pair",
            "3 lone pairs",
            "2 lone pairs",
            "0 lone pairs",
        ],
        "correct_index": 2,
        "why": "Oxygen has six outer electrons and uses two in bonds, leaving four electrons as two lone pairs.",
    },
    {
        "id": "ks4-covalent-bonding-h20",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate this statement: 'An atom that has formed a covalent bond still owns the same number of electrons as before.'",
        "options": [
            "It is wrong: the atom gains one electron from its bonding partner",
            "It is wrong: the atom gives one electron away to its bonding partner",
            "It is right, but it holds only for an atom that forms a single bond",
            "It is right: no electrons are lost or gained, they are shared instead",
        ],
        "correct_index": 3,
        "why": "Covalent bonding shares electrons rather than transferring them, so neither atom's own electron count changes.",
    },
    {
        "id": "ks4-covalent-bonding-h21",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Determine the total number of electrons involved in the bonding of one methane molecule.",
        "options": [
            "8 electrons",
            "4 electrons",
            "10 electrons",
            "16 electrons",
        ],
        "correct_index": 0,
        "why": "Methane has four bonds, each a shared pair, so eight electrons are involved in the bonding.",
    },
    {
        "id": "ks4-covalent-bonding-h22",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Selenium sits directly below sulfur in Group 6. Predict the formula of the compound selenium forms with hydrogen, and justify it.",
        "options": [
            "H6Se, one hydrogen atom for each outer electron selenium holds",
            "H2Se, because selenium needs two more electrons to fill its shell",
            "HSe, because one shared pair joins the two atoms together",
            "H4Se, because selenium has four electrons free for bonding",
        ],
        "correct_index": 1,
        "why": "A Group 6 atom has six outer electrons and needs two more, so it forms two bonds to hydrogen.",
    },
    {
        "id": "ks4-covalent-bonding-h23",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student draws carbon dioxide with one shared pair between the carbon and each oxygen. Explain why the diagram cannot be right.",
        "options": [
            "The two oxygen atoms should have been drawn bonded to each other instead",
            "The shared pairs belong on the carbon atom rather than between the atoms",
            "Carbon would count only four outer electrons, not the eight it needs",
            "Carbon dioxide holds no shared pairs, since its electrons are transferred over",
        ],
        "correct_index": 2,
        "why": "Two single bonds leave carbon with four outer electrons, so double bonds are needed for it to reach eight.",
    },
    {
        "id": "ks4-covalent-bonding-h24",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Ethane, ethene and ethyne each contain two carbon atoms and hold six, four and two hydrogen atoms. Explain the pattern.",
        "options": [
            "The carbon atoms grow steadily smaller, so fewer hydrogen atoms fit",
            "The molecules grow steadily more reactive, and a more reactive molecule holds less hydrogen",
            "The carbon atoms form five bonds, then six, then seven",
            "The carbon-carbon bond goes from single to double to triple, leaving fewer bonds for hydrogen",
        ],
        "correct_index": 3,
        "why": "Each carbon always forms four bonds, so every extra bond used between the carbons is one fewer available for hydrogen.",
    },
    {
        "id": "ks4-covalent-bonding-h25",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the formula of a covalent compound can be predicted from the periodic table before any experiment is done.",
        "options": [
            "Because the group number gives the outer electrons, and so the bonds each atom forms",
            "Because elements sharing a period of the table share one formula",
            "Because the atomic number gives the number of bonds an atom forms",
            "Because a covalent compound copies the formula of the one above it",
        ],
        "correct_index": 0,
        "why": "The group number gives the number of outer electrons, which fixes how many more the atom needs and so how many bonds it makes.",
    },
    {
        "id": "ks4-covalent-bonding-h26",
        "subtopic_slug": "covalent-bonding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Nitrogen trichloride contains one nitrogen atom and three chlorine atoms. Determine the total number of outer-shell electrons a correct dot-and-cross diagram would show.",
        "options": [
            "8 electrons",
            "26 electrons",
            "12 electrons",
            "32 electrons",
        ],
        "correct_index": 1,
        "why": "Nitrogen brings five outer electrons and each chlorine brings seven, so five plus twenty-one is twenty-six.",
    },
]
