"""Chemistry · Bonding, structure and properties — the MRB-338 expansion for `properties-small-molecules`.

Everything in this leaf turns on one distinction: the strong covalent bonds
INSIDE a molecule against the weak forces BETWEEN molecules, and the fact that
melting and boiling overcome the second and leave the first untouched. So the
weight sits there — on what is and is not broken, on what a boiling point is
therefore evidence about, and on the size-of-molecule trend that follows.

Non-conduction is the second strand, and it is kept honest: a molecule has no
charge, so the pure substance conducts in no state, but dissolving can make
ions where there were none. The halogens, the noble gases, ethanol against
ethane and hydrogen sulfide against water carry the comparative rows, so the
same reasoning is met in substances the shipped rows do not use.
"""

TOPIC = "bonding"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": "ks4-properties-small-molecules-e05",
        "subtopic_slug": "properties-small-molecules",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State whether a simple molecular substance contains any free electrons or any free ions.",
        "options": [
            "It contains neither of them",
            "It contains free electrons but no free ions",
            "It contains free ions but no free electrons",
            "It contains both of them in equal numbers",
        ],
        "correct_index": 0,
        "why": "Its particles are uncharged whole molecules, so there is no free electron and no free ion anywhere in it.",
    },
    {
        "id": "ks4-properties-small-molecules-e06",
        "subtopic_slug": "properties-small-molecules",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State which is the stronger: the covalent bonds inside a molecule, or the forces between molecules.",
        "options": [
            "The forces between the molecules",
            "The covalent bonds inside the molecule",
            "They are of exactly equal strength always",
            "It depends on the temperature",
        ],
        "correct_index": 1,
        "why": "Covalent bonds within a molecule are strong; the intermolecular forces between separate molecules are weak.",
    },
    {
        "id": "ks4-properties-small-molecules-e07",
        "subtopic_slug": "properties-small-molecules",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Sulfur dioxide boils at -10 °C. State what this low value is evidence about.",
        "options": [
            "The strength of the covalent bonds inside each molecule",
            "The weakness of the forces between its separate molecules",
            "The number of atoms contained in each of its molecules",
            "The charge carried by each carbon dioxide molecule",
        ],
        "correct_index": 1,
        "why": "A boiling point measures what is overcome on boiling, which is the intermolecular force and never the covalent bond.",
    },
    {
        "id": "ks4-properties-small-molecules-e08",
        "subtopic_slug": "properties-small-molecules",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "As a simple molecular substance is heated, state which gives way first: the covalent bonds or the intermolecular forces.",
        "options": [
            "The covalent bonds inside each molecule",
            "Both of them give way at the same moment",
            "The intermolecular forces between the molecules",
            "Neither, because heating breaks nothing at all",
        ],
        "correct_index": 2,
        "why": "The forces between molecules are much the weaker, so they are overcome long before a covalent bond is touched.",
    },
    {
        "id": "ks4-properties-small-molecules-e09",
        "subtopic_slug": "properties-small-molecules",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the type of structure that carbon dioxide has.",
        "options": [
            "Simple molecular",
            "Giant covalent",
            "Giant ionic",
            "Giant metallic",
        ],
        "correct_index": 0,
        "why": "Carbon dioxide is made of small, separate CO2 molecules, which is a simple molecular structure.",
    },
    {
        "id": "ks4-properties-small-molecules-e10",
        "subtopic_slug": "properties-small-molecules",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State why a molecule cannot carry an electric current.",
        "options": [
            "It is far too small",
            "It has no overall charge",
            "It cannot move freely",
            "It is hemmed in on every side",
        ],
        "correct_index": 1,
        "why": "Carrying a current needs charged particles that can move, and a molecule carries no charge at all.",
    },
    {
        "id": "ks4-properties-small-molecules-e11",
        "subtopic_slug": "properties-small-molecules",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State which of the two kinds of force survives unbroken when a simple molecular substance melts.",
        "options": [
            "The covalent bonds inside each molecule",
            "The weak forces between the molecules",
            "The attraction between ions in a lattice",
            "The attraction of ions for an electron sea",
        ],
        "correct_index": 0,
        "why": "Melting overcomes the weak intermolecular forces, and the covalent bonds inside each molecule are left untouched.",
    },
    {
        "id": "ks4-properties-small-molecules-e12",
        "subtopic_slug": "properties-small-molecules",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State whether every molecule of one simple molecular substance contains the same number of atoms.",
        "options": [
            "No, the number changes as the substance is heated",
            "No, the molecules vary in size throughout the sample",
            "No, only the smallest molecules have a fixed number",
            "Yes, each molecule holds the same fixed number",
        ],
        "correct_index": 3,
        "why": "A simple molecular substance is built from identical molecules, each containing the same fixed number of atoms.",
    },
    {
        "id": "ks4-properties-small-molecules-s05",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Hydrogen boils at -253 °C, methane at -161 °C and water at 100 °C. Deduce the order of increasing strength of the forces between their molecules.",
        "options": [
            "Hydrogen, then methane, then water",
            "Water, then methane, then hydrogen",
            "Methane, then hydrogen, then water",
            "Hydrogen, then water, then methane",
        ],
        "correct_index": 0,
        "why": "The higher the boiling point, the more energy is needed to separate the molecules, so the stronger the forces between them.",
    },
    {
        "id": "ks4-properties-small-molecules-s06",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a molecule of oxygen carries no overall electric charge.",
        "options": [
            "Its atoms transfer electrons, and the two charges cancel out",
            "Its atoms share electrons, so neither of them becomes an ion",
            "Its electrons are delocalised, so the charge spreads out evenly",
            "Its atoms are identical to each other, and identical atoms are always neutral",
        ],
        "correct_index": 1,
        "why": "Covalent bonding shares electrons rather than transferring them, so no ions form and the molecule stays neutral.",
    },
    {
        "id": "ks4-properties-small-molecules-s07",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Nitrogen is a gas at room temperature, although the bond inside an N2 molecule is one of the strongest known. Explain how both of these are true.",
        "options": [
            "The bond is strong, but there is only one of it in the molecule",
            "The bond weakens as soon as nitrogen has been warmed to room temperature",
            "The bond is strong, but the forces between the molecules are weak",
            "The bond is strong, but nitrogen molecules are too light to stay liquid",
        ],
        "correct_index": 2,
        "why": "Boiling separates whole molecules, so it is the weak forces between N2 molecules that decide the boiling point, not the triple bond.",
    },
    {
        "id": "ks4-properties-small-molecules-s08",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Iodine dissolves well in hexane but hardly at all in water. Suggest what this shows about choosing a solvent.",
        "options": [
            "A substance dissolves best in whichever solvent is the cheaper one",
            "A substance dissolves best in a solvent with a higher boiling point",
            "A substance dissolves best in water, whichever else is available",
            "A substance dissolves best in a solvent that is similar to itself",
        ],
        "correct_index": 3,
        "why": "A solute dissolves most readily in a solvent whose molecules are like its own, which is why iodine prefers hexane to water.",
    },
    {
        "id": "ks4-properties-small-molecules-s09",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why solid carbon dioxide does not conduct electricity.",
        "options": [
            "Its particles are uncharged molecules, with no free electrons or ions",
            "Its molecules are locked in place and too cold to move about",
            "Its covalent bonds hold the electrons so tightly that none can move",
            "Its molecules are much too far apart for a current to jump between them",
        ],
        "correct_index": 0,
        "why": "Conduction needs mobile charged particles, and solid carbon dioxide has neither free electrons nor ions.",
    },
    {
        "id": "ks4-properties-small-molecules-s10",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Chlorine boils at -34 °C and bromine at 59 °C. Explain the difference.",
        "options": [
            "Bromine has the stronger covalent bond inside each molecule",
            "Bromine molecules are larger, so the forces between them are stronger",
            "Bromine is a liquid, and a liquid always boils at a higher temperature",
            "Bromine is less reactive, so its molecules cling together more tightly",
        ],
        "correct_index": 1,
        "why": "Larger molecules with more electrons attract each other more strongly, so more energy is needed to separate them.",
    },
    {
        "id": "ks4-properties-small-molecules-s11",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the formula of a simple molecular substance is the same whether it is a solid, a liquid or a gas.",
        "options": [
            "Because the molecules themselves are never altered by a change of state",
            "Because a formula is only ever written for a substance in one state",
            "Because the molecules gain atoms in one state and lose them in another",
            "Because the formula gives only the simplest ratio of the atoms present",
        ],
        "correct_index": 0,
        "why": "A change of state moves molecules apart or together but never changes what any molecule is made of.",
    },
    {
        "id": "ks4-properties-small-molecules-s12",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happens to an individual molecule when a simple molecular substance melts.",
        "options": [
            "It splits into separate atoms",
            "It joins on to the molecule beside it",
            "It loses an atom to its neighbour",
            "It stays exactly as it was",
        ],
        "correct_index": 3,
        "why": "Melting is a physical change: the molecules move apart from one another but each molecule is unaltered.",
    },
    {
        "id": "ks4-properties-small-molecules-s13",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why most simple molecular substances are gases or liquids at room temperature.",
        "options": [
            "The weak forces between their molecules are overcome at room temperature",
            "Their covalent bonds are too weak to hold a solid together",
            "Their molecules are far too light to stay solid",
            "Their molecules repel each other and so cannot form a solid",
        ],
        "correct_index": 0,
        "why": "Only weak forces hold the molecules together, and the energy available at room temperature is enough to overcome them.",
    },
    {
        "id": "ks4-properties-small-molecules-s14",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Ammonia boils at -33 °C and phosphine at -88 °C. Deduce which has the stronger forces between its molecules.",
        "options": [
            "Phosphine",
            "Ammonia",
            "They are equal",
            "It cannot be told from boiling points",
        ],
        "correct_index": 1,
        "why": "Ammonia needs a higher temperature before its molecules separate, so the forces holding them together are stronger.",
    },
    {
        "id": "ks4-properties-small-molecules-s15",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what energy must be supplied for in order to turn liquid methane into methane gas.",
        "options": [
            "Breaking the carbon-hydrogen bonds",
            "Splitting each molecule into atoms",
            "Separating the molecules from one another",
            "Removing electrons from each molecule",
        ],
        "correct_index": 2,
        "why": "Boiling supplies the energy needed to overcome the weak forces holding the methane molecules near one another.",
    },
    {
        "id": "ks4-properties-small-molecules-s16",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the melting point of a simple molecular substance is evidence about the forces between its molecules rather than about the bonds within them.",
        "options": [
            "Because a covalent bond has no strength that could ever be measured",
            "Because the bonds inside a molecule all have exactly the same strength",
            "Because melting happens only at the surface, where there are no bonds to break",
            "Because melting separates the molecules and leaves the bonds alone",
        ],
        "correct_index": 3,
        "why": "What is overcome at the melting point is the intermolecular force, so that is the only thing the melting point measures.",
    },
    {
        "id": "ks4-properties-small-molecules-s17",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Hydrogen sulfide boils at -60 °C while water boils at 100 °C, although both have two hydrogen atoms joined to a Group 6 atom. Suggest what this shows.",
        "options": [
            "That the forces between water molecules are unusually strong",
            "That the covalent bonds in hydrogen sulfide must be far weaker",
            "That hydrogen sulfide molecules contain fewer atoms than water's",
            "That water is a compound while hydrogen sulfide is an element",
        ],
        "correct_index": 0,
        "why": "The two molecules are a similar size, so the much higher boiling point shows water's intermolecular forces are exceptionally strong.",
    },
    {
        "id": "ks4-properties-small-molecules-s18",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Sugar dissolves readily in water, yet the solution does not conduct electricity. Explain why.",
        "options": [
            "The sugar has not dissolved, it has only spread through the water",
            "The sugar molecules stay whole and uncharged in the solution",
            "The water molecules surround the sugar and block the current",
            "The sugar molecules are far too large to move through the water",
        ],
        "correct_index": 1,
        "why": "Dissolving sugar separates whole molecules, and a molecule carries no charge, so nothing is present to carry a current.",
    },
    {
        "id": "ks4-properties-small-molecules-s19",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the two kinds of force present in a sample of liquid ammonia, and state which is overcome on boiling.",
        "options": [
            "Ionic bonds and covalent bonds; the ionic bonds are overcome",
            "Covalent bonds and intermolecular forces; the bonds are overcome",
            "Covalent bonds and intermolecular forces; the forces are overcome",
            "Metallic bonds and intermolecular forces; the bonds are overcome",
        ],
        "correct_index": 2,
        "why": "Covalent bonds hold each NH3 molecule together and weak intermolecular forces hold the molecules near each other; boiling overcomes the latter.",
    },
    {
        "id": "ks4-properties-small-molecules-s20",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a simple molecular substance can be given a formula such as CO2 with exact numbers in it.",
        "options": [
            "Because the formula gives only the simplest ratio of the atoms",
            "Because the numbers are an average taken across the whole sample",
            "Because the numbers show how many bonds each atom makes",
            "Because every molecule holds that exact number of atoms",
        ],
        "correct_index": 3,
        "why": "A molecular formula counts the atoms in one real molecule, and every molecule of the substance is identical.",
    },
    {
        "id": "ks4-properties-small-molecules-s21",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A simple molecular substance is boiled and then cooled back to a liquid. Explain why it is chemically unchanged.",
        "options": [
            "Only the forces between molecules were overcome, and they reform",
            "The covalent bonds broke on boiling and then reformed on cooling",
            "The molecules split into atoms and then rejoined in the same way",
            "The substance did change, but the change cannot be seen by the naked eye",
        ],
        "correct_index": 0,
        "why": "Boiling and condensing are physical changes: the molecules themselves are never altered, only their separation.",
    },
    {
        "id": "ks4-properties-small-molecules-s22",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a water molecule is called small, although it contains three atoms.",
        "options": [
            "Because three atoms is fewer than most molecules hold",
            "Because small means a fixed unit of a few atoms, not a giant network",
            "Because the atoms in it are among the smallest that there are",
            "Because it is too small to be seen even under a microscope",
        ],
        "correct_index": 1,
        "why": "Small molecular describes a discrete unit of a few atoms, in contrast with a giant structure of millions bonded throughout.",
    },
    {
        "id": "ks4-properties-small-molecules-s23",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a molecule holding more electrons gives its substance a higher boiling point.",
        "options": [
            "More electrons make the covalent bonds inside it much stronger",
            "More electrons give the molecule an overall negative charge",
            "More electrons make the attraction between molecules stronger",
            "More electrons make the molecule heavier and harder to lift",
        ],
        "correct_index": 2,
        "why": "The intermolecular forces grow stronger as the number of electrons in each molecule rises, so more energy is needed to separate them.",
    },
    {
        "id": "ks4-properties-small-molecules-s24",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Neon boils at -246 °C and xenon at -108 °C. Suggest why.",
        "options": [
            "Xenon particles form covalent bonds while neon particles do not",
            "Xenon is more reactive, so its particles hold on to each other",
            "Xenon particles carry a charge, so they attract each other strongly",
            "Xenon particles are larger, so the forces between them are stronger",
        ],
        "correct_index": 3,
        "why": "Xenon's larger particles hold many more electrons, so the weak attractions between them are stronger than neon's.",
    },
    {
        "id": "ks4-properties-small-molecules-s25",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a pure simple molecular substance does not conduct electricity even after it has been melted.",
        "options": [
            "Melting frees whole molecules, and a molecule carries no charge",
            "Melting does not supply enough energy to free any electrons",
            "Melting makes the molecules move too fast to carry a current",
            "Melting leaves the molecules much too far apart to pass charge on",
        ],
        "correct_index": 0,
        "why": "Melting an ionic solid frees charged ions, but melting a molecular solid only frees uncharged molecules.",
    },
    {
        "id": "ks4-properties-small-molecules-s26",
        "subtopic_slug": "properties-small-molecules",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what must happen to the arrangement of the molecules for a simple molecular liquid to become a gas.",
        "options": [
            "They must break apart into their separate atoms and spread out",
            "They must move far apart from one another and spread out",
            "They must line up in a regular pattern and then move apart",
            "They must join together into larger molecules and then rise",
        ],
        "correct_index": 1,
        "why": "Boiling separates the molecules so they are widely spaced and free to move throughout the container.",
    },
    {
        "id": "ks4-properties-small-molecules-h05",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Breaking the covalent bond in hydrogen takes about 436 kJ per mole, while boiling liquid hydrogen takes about 0.9 kJ per mole. Determine roughly how many times more energy the bond needs.",
        "options": [
            "About 500 times",
            "About 5 times",
            "About 50 times",
            "About 5000 times",
        ],
        "correct_index": 0,
        "why": "436 divided by 0.9 is about 480, so the covalent bond needs roughly five hundred times the energy that boiling does.",
    },
    {
        "id": "ks4-properties-small-molecules-h06",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Predict what would happen to water if the forces between its molecules were as weak as those between methane molecules.",
        "options": [
            "It would freeze solid and stay solid at room temperature",
            "It would boil far below room temperature and be a gas",
            "It would boil at a higher temperature than it does now",
            "It would break apart into hydrogen and oxygen gases",
        ],
        "correct_index": 1,
        "why": "Methane boils at -161 °C, so water with forces that weak would have long since boiled at ordinary temperatures.",
    },
    {
        "id": "ks4-properties-small-molecules-h07",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A colourless substance boils at 21 °C and conducts electricity in no state. Deduce its structure and state which clue rules out a giant covalent one.",
        "options": [
            "Giant ionic; the lack of conduction rules out a giant covalent one",
            "Giant metallic; the lack of colour rules out a giant covalent one",
            "Simple molecular; the low boiling point rules out a giant covalent one",
            "Simple molecular; the lack of conduction rules out a giant covalent one",
        ],
        "correct_index": 2,
        "why": "A giant covalent structure needs many strong bonds broken and melts very high, so a boiling point of 21 °C rules it out.",
    },
    {
        "id": "ks4-properties-small-molecules-h08",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the boiling point of a simple molecular substance says nothing about how strong its covalent bonds are.",
        "options": [
            "Because boiling breaks the weaker of the two, and that is the bond",
            "Because a covalent bond has the same strength in every substance",
            "Because boiling points are measured far too roughly to show bond strength",
            "Because boiling separates molecules and never breaks a covalent bond",
        ],
        "correct_index": 3,
        "why": "The boiling point measures only what is overcome at that temperature, which is the intermolecular force and never the bond.",
    },
    {
        "id": "ks4-properties-small-molecules-h09",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A carbon dioxide molecule holds more electrons than a water molecule, yet carbon dioxide is a gas at 20 °C and water is a liquid. Suggest what this shows.",
        "options": [
            "That the number of electrons is not the only thing that sets the forces",
            "That carbon dioxide molecules must therefore hold fewer electrons",
            "That the covalent bonds in water must be stronger",
            "That electrons play no part in the forces here",
        ],
        "correct_index": 0,
        "why": "Usually more electrons means stronger forces, so water breaking the pattern shows something else about water's molecules matters too.",
    },
    {
        "id": "ks4-properties-small-molecules-h10",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Sugar solution does not conduct electricity while salt solution does, although both look identical. Explain the difference.",
        "options": [
            "The sugar has not dissolved as completely as the salt has dissolved",
            "The sugar has dissolved into whole molecules, the salt into free ions",
            "The sugar solution is the more dilute of the two solutions made",
            "The sugar molecules are larger and so move too slowly to conduct",
        ],
        "correct_index": 1,
        "why": "Conduction needs mobile charged particles: salt supplies ions on dissolving, while sugar supplies uncharged molecules.",
    },
    {
        "id": "ks4-properties-small-molecules-h11",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Predict the effect on the melting point of a simple molecular substance of replacing each molecule with one twice the size.",
        "options": [
            "It would fall, because larger molecules pack together less neatly",
            "It would be unchanged, because melting point depends on the bonds",
            "It would rise, because the forces between molecules grow stronger",
            "It would fall, because the larger molecules hold their heat less well",
        ],
        "correct_index": 2,
        "why": "Larger molecules carry more electrons, so the intermolecular attractions are stronger and more energy is needed to separate them.",
    },
    {
        "id": "ks4-properties-small-molecules-h12",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Iodine is a solid at room temperature although it is a simple molecular substance. Suggest why, and state what is overcome when it melts.",
        "options": [
            "Its molecules are large, so melting breaks the covalent bonds inside them",
            "Its structure is giant covalent, so melting breaks many strong bonds",
            "Its molecules carry a charge, and melting overcomes that attraction",
            "Its molecules are large, but melting still overcomes only weak forces",
        ],
        "correct_index": 3,
        "why": "Iodine molecules hold many electrons, so the forces between them are strong enough to give a solid, but melting still overcomes only those forces.",
    },
    {
        "id": "ks4-properties-small-molecules-h13",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate this statement: 'Because a simple molecular substance melts so easily, its molecules must be falling apart into atoms.'",
        "options": [
            "It is wrong: the molecules stay whole and simply move apart",
            "It is right, because the atoms are what spread out on melting",
            "It is right, because melting always breaks something inside the substance",
            "It is wrong: the atoms rejoin in a new order as the substance melts",
        ],
        "correct_index": 0,
        "why": "Melting is physical: the weak forces between molecules are overcome, but each molecule keeps every one of its atoms.",
    },
    {
        "id": "ks4-properties-small-molecules-h14",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Fluorine boils at -188 °C, chlorine at -34 °C, bromine at 59 °C and iodine at 184 °C. Explain this trend.",
        "options": [
            "The molecules get larger, so their covalent bonds get much stronger",
            "The molecules get larger, so the forces between them get stronger",
            "The elements get less reactive, so their molecules cling together more",
            "The molecules get heavier, so they sink and cannot escape as a gas",
        ],
        "correct_index": 1,
        "why": "Down the group the molecules hold more electrons, so the intermolecular attractions strengthen and the boiling point climbs.",
    },
    {
        "id": "ks4-properties-small-molecules-h15",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a boiling point of 78 °C on its own makes it unlikely that a substance is ionic.",
        "options": [
            "Because an ionic compound must contain a metal, and metals boil higher",
            "Because an ionic compound cannot be boiled, but only melted",
            "Because ionic compounds boil at far higher temperatures than that",
            "Because ionic compounds only ever boil below room temperature",
        ],
        "correct_index": 2,
        "why": "An ionic lattice needs very strong attractions overcome throughout, so its boiling point runs to many hundreds of degrees.",
    },
    {
        "id": "ks4-properties-small-molecules-h16",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare what is overcome when ice melts with what is broken when water is split into hydrogen and oxygen.",
        "options": [
            "Strong covalent bonds inside molecules; weak forces between them",
            "Weak forces in both cases, but far more of them in the splitting",
            "Strong covalent bonds in both cases, but fewer in the melting",
            "Weak forces between molecules; strong covalent bonds inside them",
        ],
        "correct_index": 3,
        "why": "Melting is physical and overcomes only intermolecular forces; splitting water is chemical and breaks the covalent bonds themselves.",
    },
    {
        "id": "ks4-properties-small-molecules-h17",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the melting point of a simple molecular substance does not depend on how large the sample is.",
        "options": [
            "Because the forces act between individual molecules, whatever the amount",
            "Because a larger sample takes in heat more quickly than a small one",
            "Because melting point is always measured on a sample of the same mass",
            "Because the extra molecules in a larger sample melt one after another",
        ],
        "correct_index": 0,
        "why": "Melting point is set by the strength of the force between one molecule and its neighbours, which is the same in any quantity.",
    },
    {
        "id": "ks4-properties-small-molecules-h18",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student claims that ammonia boiling below water proves the nitrogen-hydrogen bond is weaker than the oxygen-hydrogen bond. Evaluate the claim.",
        "options": [
            "It follows, because a weaker bond always gives a lower boiling point",
            "It does not follow: boiling compares forces between molecules, not bonds",
            "It follows, because boiling breaks the weakest bond in the substance",
            "It does not follow: boiling points cannot be compared between compounds",
        ],
        "correct_index": 1,
        "why": "Boiling never breaks a covalent bond, so a boiling point is evidence about intermolecular forces and about nothing else.",
    },
    {
        "id": "ks4-properties-small-molecules-h19",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Ethanol has the formula C2H5OH. Determine the total number of atoms in three molecules of ethanol.",
        "options": [
            "18 atoms",
            "24 atoms",
            "27 atoms",
            "9 atoms",
        ],
        "correct_index": 2,
        "why": "One ethanol molecule holds two carbon, six hydrogen and one oxygen atom, which is nine, and three molecules hold twenty-seven.",
    },
    {
        "id": "ks4-properties-small-molecules-h20",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain how simple molecular substances can be solids, liquids or gases at room temperature, when they all have weak forces between their molecules.",
        "options": [
            "Because some of them have giant structures rather than small molecules",
            "Because room temperature itself varies from one laboratory to another",
            "Because their covalent bonds differ, and that sets the state they take",
            "Because weak forces still vary in strength from substance to substance",
        ],
        "correct_index": 3,
        "why": "Weak is a comparison with covalent bonds; among molecular substances the forces still range widely, and so do their melting points.",
    },
    {
        "id": "ks4-properties-small-molecules-h21",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Water boils at 100 °C and hydrogen peroxide at 150 °C, although both are built from hydrogen and oxygen only. Explain how this is possible.",
        "options": [
            "They are different molecules, with different forces acting between them",
            "They contain different elements, which is what sets a boiling point",
            "Hydrogen peroxide has stronger covalent bonds, which must be broken",
            "Hydrogen peroxide is a mixture, so it boils over a range of temperatures",
        ],
        "correct_index": 0,
        "why": "A boiling point belongs to the molecule, not to the elements in it, and a larger hydrogen peroxide molecule attracts its neighbours more strongly.",
    },
    {
        "id": "ks4-properties-small-molecules-h22",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the weak forces in a simple molecular substance are described as acting between molecules rather than between atoms.",
        "options": [
            "Because atoms are far too small for any force to act between them",
            "Because the atoms within a molecule are already held by covalent bonds",
            "Because the atoms within a molecule are too tightly packed to attract",
            "Because a force can only ever act between two completely identical particles",
        ],
        "correct_index": 1,
        "why": "Within a molecule the atoms are joined covalently; the weak attractions act between one whole molecule and the next.",
    },
    {
        "id": "ks4-properties-small-molecules-h23",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Deduce which would be easier to turn into a gas: a substance whose molecules hold 10 electrons, or one whose molecules hold 60.",
        "options": [
            "The one with 60 electrons",
            "Both would be equally easy",
            "The one with 10 electrons",
            "It depends only on the covalent bonds inside",
        ],
        "correct_index": 2,
        "why": "Fewer electrons per molecule means weaker forces between molecules, so less energy is needed to separate them.",
    },
    {
        "id": "ks4-properties-small-molecules-h24",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a simple molecular substance is described as having separate molecules rather than a continuous network.",
        "options": [
            "Because the molecules are too far apart for a network to form",
            "Because the molecules keep moving and cannot settle into a network",
            "Because a network can only ever be built out of metal atoms",
            "Because the covalent bonds stop at the edge of each molecule",
        ],
        "correct_index": 3,
        "why": "In a molecular substance the covalent bonding stops where the molecule ends, so the sample is many separate units rather than one network.",
    },
    {
        "id": "ks4-properties-small-molecules-h25",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate this statement: 'A covalent molecular substance never produces a solution that conducts electricity.'",
        "options": [
            "It is wrong: some, such as hydrogen chloride, form ions on dissolving",
            "It is right, because a molecule can never be made to carry a charge",
            "It is right, because dissolving cannot alter the particles present",
            "It is wrong: every molecular substance gives a conducting solution",
        ],
        "correct_index": 0,
        "why": "Most molecular substances dissolve as whole molecules, but a few react with water to make ions, and those solutions do conduct.",
    },
    {
        "id": "ks4-properties-small-molecules-h26",
        "subtopic_slug": "properties-small-molecules",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Ethanol boils at 78 °C and ethane at -89 °C, although both molecules contain two carbon atoms. Deduce which has the stronger forces between its molecules.",
        "options": [
            "Ethane",
            "Ethanol",
            "They are equal",
            "It cannot be deduced from this",
        ],
        "correct_index": 1,
        "why": "Ethanol needs a far higher temperature before its molecules separate, so the attractions between them must be much stronger.",
    },
]
