"""Chemistry · Bonding, structure and properties — the MRB-338 expansion for `giant-covalent-structures`.

Every property here is traced back to one number: how many other atoms each
atom is bonded to. Four in diamond leaves nothing over, so it is rigid and
insulating; three in graphite leaves one electron delocalised and one weak
seam between the layers, so it conducts and it slides. The weight therefore
sits on that four-against-three, asked from the structure side and from the
property side, with silicon dioxide and silicon carbide carrying the rows that
test whether a pupil can apply it away from carbon.

⚠️ Graphene, the fullerenes and the nanotubes are deliberately ABSENT. They are
AQA chemistry-only content and this subtopic is not triple-only, so those rows
live in `nanoparticles`, which is. Diamond, graphite and silicon dioxide are
the whole of what a combined-science pupil is taught here.
"""

TOPIC = "bonding"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": "ks4-giant-covalent-structures-e05",
        "subtopic_slug": "giant-covalent-structures",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the number of other carbon atoms each carbon atom is bonded to in diamond.",
        "options": [
            "4",
            "2",
            "3",
            "6",
        ],
        "correct_index": 0,
        "why": "Each carbon atom in diamond forms four covalent bonds, using all four of its outer electrons.",
    },
    {
        "id": "ks4-giant-covalent-structures-e06",
        "subtopic_slug": "giant-covalent-structures",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the form of pure carbon in which every atom is bonded to only three neighbours.",
        "options": [
            "Diamond",
            "Graphite",
            "Silicon dioxide",
            "Carbon dioxide",
        ],
        "correct_index": 1,
        "why": "Graphite's carbon atoms each bond to three others within a layer, leaving one outer electron delocalised.",
    },
    {
        "id": "ks4-giant-covalent-structures-e07",
        "subtopic_slug": "giant-covalent-structures",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the two forms of pure carbon that have giant covalent structures.",
        "options": [
            "Diamond and quartz",
            "Graphite and quartz",
            "Diamond and graphite",
            "Graphite and dry ice",
        ],
        "correct_index": 2,
        "why": "Diamond and graphite are both giant covalent structures made only of carbon atoms.",
    },
    {
        "id": "ks4-giant-covalent-structures-e08",
        "subtopic_slug": "giant-covalent-structures",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the number of outer electrons a carbon atom in diamond has left over after bonding.",
        "options": [
            "0",
            "1",
            "2",
            "4",
        ],
        "correct_index": 0,
        "why": "All four of a carbon atom's outer electrons are used in bonds in diamond, so none is left over to carry charge.",
    },
    {
        "id": "ks4-giant-covalent-structures-e09",
        "subtopic_slug": "giant-covalent-structures",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the particle that is delocalised in graphite and lets it conduct electricity.",
        "options": [
            "The fourth outer electron of each carbon atom",
            "A positive carbon ion left in the layer",
            "A proton released from each carbon nucleus",
            "A negative carbon ion between the layers",
        ],
        "correct_index": 0,
        "why": "Each carbon uses three outer electrons for bonds, and the fourth is delocalised and free to move.",
    },
    {
        "id": "ks4-giant-covalent-structures-e10",
        "subtopic_slug": "giant-covalent-structures",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what has to be broken before a giant covalent structure will melt.",
        "options": [
            "The weak forces acting between its separate small molecules",
            "Many strong covalent bonds, running right through the structure",
            "The attraction between its positive ions and its electron sea",
            "The attraction between its oppositely charged ions in the lattice",
        ],
        "correct_index": 1,
        "why": "There are no separate molecules to pull apart, so melting has to break covalent bonds throughout the solid.",
    },
    {
        "id": "ks4-giant-covalent-structures-e11",
        "subtopic_slug": "giant-covalent-structures",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the shape of the rings that the carbon atoms form within a layer of graphite.",
        "options": [
            "Triangular",
            "Square",
            "Hexagonal",
            "Circular",
        ],
        "correct_index": 2,
        "why": "The carbon atoms in a graphite layer are joined into flat hexagonal rings of six atoms.",
    },
    {
        "id": "ks4-giant-covalent-structures-e12",
        "subtopic_slug": "giant-covalent-structures",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the two elements present in silicon dioxide.",
        "options": [
            "Silicon and carbon",
            "Sodium and oxygen",
            "Sulfur and oxygen",
            "Silicon and oxygen",
        ],
        "correct_index": 3,
        "why": "The name silicon dioxide gives the elements directly: silicon joined to oxygen, with the formula SiO2.",
    },
    {
        "id": "ks4-giant-covalent-structures-s05",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why no single atom in diamond can be pushed out of its place.",
        "options": [
            "It is bonded to four others, holding it from every direction",
            "It is bonded to three others, with a spare electron holding it",
            "It is far heavier than the atoms around it in the lattice",
            "It carries a charge that its neighbours pull against equally",
        ],
        "correct_index": 0,
        "why": "Four covalent bonds hold every carbon atom from all sides at once, so nothing can shift it within the lattice.",
    },
    {
        "id": "ks4-giant-covalent-structures-s06",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why graphite feels slippery when it is rubbed between the fingers.",
        "options": [
            "Its covalent bonds are weak, so the whole structure gives way easily",
            "Its layers slide over each other, held only by weak forces",
            "Its delocalised electrons act as a lubricant between the atoms",
            "Its atoms are rounded, so they roll over one another like beads",
        ],
        "correct_index": 1,
        "why": "Only weak forces hold one layer of graphite to the next, so the layers slip past one another readily.",
    },
    {
        "id": "ks4-giant-covalent-structures-s07",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Deduce the number of covalent bonds that must be broken to free one carbon atom from the middle of a diamond.",
        "options": [
            "1",
            "2",
            "4",
            "8",
        ],
        "correct_index": 2,
        "why": "Each carbon atom in diamond is joined to four neighbours, so all four of those bonds have to be broken.",
    },
    {
        "id": "ks4-giant-covalent-structures-s08",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Diamond contains no ions. Name the other thing it lacks that any conductor needs.",
        "options": [
            "Free electrons",
            "Covalent bonds",
            "A regular lattice",
            "Layers that can slide",
        ],
        "correct_index": 0,
        "why": "Conduction needs a mobile charge, and diamond has neither free ions nor free electrons, because all four are bonded.",
    },
    {
        "id": "ks4-giant-covalent-structures-s09",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State where the delocalised electrons in graphite are free to move.",
        "options": [
            "Between and along its layers",
            "Only within a single hexagonal ring",
            "Only along the edges of the sample",
            "Between the nucleus and the shells of an atom",
        ],
        "correct_index": 0,
        "why": "Graphite's spare outer electrons are delocalised across the layers, and their movement is what carries a current.",
    },
    {
        "id": "ks4-giant-covalent-structures-s10",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the number of covalent bonds each carbon atom forms in diamond with the number it forms in graphite.",
        "options": [
            "3 in diamond and 4 in graphite",
            "4 in diamond and 3 in graphite",
            "4 in both of them",
            "2 in diamond and 3 in graphite",
        ],
        "correct_index": 1,
        "why": "Diamond uses all four outer electrons in bonds; graphite uses three and leaves the fourth delocalised.",
    },
    {
        "id": "ks4-giant-covalent-structures-s11",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain how graphite can have a very high melting point although its layers slide over one another so easily.",
        "options": [
            "Sliding a layer and melting the solid both break the same bonds",
            "Melting has to overcome the weak forces between layers many times over",
            "Melting breaks the strong bonds inside a layer, not the weak ones between",
            "Graphite does not melt but merely softens as it is heated up to that point",
        ],
        "correct_index": 2,
        "why": "Sliding only overcomes the weak forces between layers, while melting must break the strong covalent bonds within them.",
    },
    {
        "id": "ks4-giant-covalent-structures-s12",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "In silicon dioxide, SiO2, each silicon atom is bonded to four oxygen atoms. Deduce the number of silicon atoms each oxygen atom is bonded to.",
        "options": [
            "1",
            "4",
            "2",
            "6",
        ],
        "correct_index": 2,
        "why": "There are twice as many oxygen atoms as silicon atoms, so each oxygen shares itself between just two silicons.",
    },
    {
        "id": "ks4-giant-covalent-structures-s13",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain what is meant by saying that diamond and graphite are allotropes of one another.",
        "options": [
            "They are the same element arranged in two different structures",
            "They are two different elements with the same kind of structure",
            "They are the same compound, but made by two quite different methods",
            "They are two forms of carbon that contain different isotopes of it",
        ],
        "correct_index": 0,
        "why": "Allotropes are different structural forms of the same element, which is exactly how diamond and graphite differ.",
    },
    {
        "id": "ks4-giant-covalent-structures-s14",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what must be true of the forces between graphite's layers if graphite is to work as a lubricant.",
        "options": [
            "They must be weak enough to let the layers slide",
            "They must be strong enough to hold the layers rigid",
            "They must be covalent bonds running between the layers",
            "They must be attractions between oppositely charged layers",
        ],
        "correct_index": 0,
        "why": "A lubricant works by letting surfaces move over one another, which needs the layers only weakly held.",
    },
    {
        "id": "ks4-giant-covalent-structures-s15",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why silicon dioxide is described as giant covalent rather than simple molecular.",
        "options": [
            "Because it contains two different elements rather than only one of them",
            "Because its molecules each contain three atoms rather than two",
            "Because its covalent bonds continue throughout the whole structure",
            "Because it is a solid, and every single solid has a giant structure",
        ],
        "correct_index": 2,
        "why": "There are no separate SiO2 molecules; the silicon-oxygen bonding extends in every direction through the solid.",
    },
    {
        "id": "ks4-giant-covalent-structures-s16",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a giant covalent structure cannot be given a formula that counts the atoms in one unit of it.",
        "options": [
            "Because the atoms in it are far too small to be counted individually",
            "Because its atoms keep changing places whenever the substance is heated",
            "Because it contains too many atoms for anyone to be able to count",
            "Because there is no separate molecule, only one continuous network",
        ],
        "correct_index": 3,
        "why": "The bonding runs on without end, so there is no discrete molecule whose atoms could be counted.",
    },
    {
        "id": "ks4-giant-covalent-structures-s17",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe the arrangement of the carbon atoms in diamond.",
        "options": [
            "In a rigid three-dimensional network, each bonded to four others",
            "In flat sheets stacked one above another with gaps between",
            "In separate cage-shaped units of sixty carbon atoms each",
            "In pairs, with each carbon atom joined to a single partner atom",
        ],
        "correct_index": 0,
        "why": "Diamond's carbon atoms form a tetrahedral network extending in all three dimensions, with four bonds on every atom.",
    },
    {
        "id": "ks4-giant-covalent-structures-s18",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe the arrangement of the carbon atoms in graphite.",
        "options": [
            "In a rigid network with every atom bonded to four others",
            "In flat hexagonal sheets stacked one above another",
            "In a regular lattice of positive ions and free electrons",
            "In separate small molecules of six carbon atoms each",
        ],
        "correct_index": 1,
        "why": "Graphite's carbon atoms lie in flat layers of hexagonal rings, with the layers stacked and only weakly held together.",
    },
    {
        "id": "ks4-giant-covalent-structures-s19",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Silicon is in Group 4, like carbon. Suggest why pure silicon has a giant covalent structure.",
        "options": [
            "Because it is a metal and metals build giant lattices of ions",
            "Because it has two outer electrons and so forms long chains",
            "Because it has four outer electrons and so bonds to four neighbours",
            "Because it is heavier than carbon, so it forms networks",
        ],
        "correct_index": 2,
        "why": "Four outer electrons let each silicon atom bond to four others, which builds a network rather than a small molecule.",
    },
    {
        "id": "ks4-giant-covalent-structures-s20",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why most giant covalent structures do not conduct electricity.",
        "options": [
            "Their atoms are locked in place and cannot carry charge along",
            "Their covalent bonds all break as soon as a current begins to pass through",
            "Their structures are far too large for a current to travel right across",
            "Their outer electrons are only ever used in bonds, and they contain no ions",
        ],
        "correct_index": 3,
        "why": "Conduction needs free electrons or free ions, and a typical giant covalent structure has neither.",
    },
    {
        "id": "ks4-giant-covalent-structures-s21",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the hardness of diamond with that of graphite, and explain the difference.",
        "options": [
            "Diamond is the harder, because its atoms are bonded in all directions",
            "Graphite is the harder, because it holds delocalised electrons",
            "They are equally hard, because both of them are made only of carbon",
            "Diamond is the harder of them, because all its atoms are packed in flat layers",
        ],
        "correct_index": 0,
        "why": "Diamond's bonds hold every atom rigidly from every side, while graphite's layers have only weak forces between them.",
    },
    {
        "id": "ks4-giant-covalent-structures-s22",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The tip of a masonry drill is coated with diamond rather than graphite. Explain why.",
        "options": [
            "Diamond conducts electricity, which helps the drill motor to run",
            "Diamond is rigid in every direction, while graphite's layers slide",
            "Diamond melts at a lower temperature, so it can be shaped to fit",
            "Diamond is the cheaper of the two and is much easier to obtain in bulk",
        ],
        "correct_index": 1,
        "why": "A cutting tip must resist being worn away, and only diamond's three-dimensional bonding gives that rigidity.",
    },
    {
        "id": "ks4-giant-covalent-structures-s23",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why melting diamond needs far more energy than melting ice.",
        "options": [
            "Diamond contains far more atoms in each of its molecules",
            "Diamond starts from a much lower temperature and so must be heated further",
            "Diamond's bonds must be broken; ice's weak forces are only overcome",
            "Diamond's atoms are heavier, so more energy is needed to move them",
        ],
        "correct_index": 2,
        "why": "Melting ice overcomes weak forces between whole molecules, while melting diamond breaks strong covalent bonds themselves.",
    },
    {
        "id": "ks4-giant-covalent-structures-s24",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how many of each carbon atom's four outer electrons are used for bonding in graphite, and how many are not.",
        "options": [
            "Two used and two not used",
            "Four used and none left over",
            "One used and three not used",
            "Three used and one not used",
        ],
        "correct_index": 3,
        "why": "Graphite's carbon atoms bond to three neighbours each, so exactly one outer electron per atom is left delocalised.",
    },
    {
        "id": "ks4-giant-covalent-structures-s25",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why silicon dioxide has properties very like diamond's, although it contains no carbon.",
        "options": [
            "Because it too is giant covalent, with strong bonds throughout",
            "Because it too is made of a single element bonded to itself",
            "Because its atoms are the very same size as diamond's carbon atoms",
            "Because it is also transparent, and clear solids all behave alike",
        ],
        "correct_index": 0,
        "why": "Properties follow from structure, and silicon dioxide has the same kind of rigid covalent network that diamond has.",
    },
    {
        "id": "ks4-giant-covalent-structures-s26",
        "subtopic_slug": "giant-covalent-structures",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Diamond, graphite and silicon dioxide are all giant covalent. State the property that all three share.",
        "options": [
            "They are all very hard to melt",
            "They all conduct electricity well",
            "They are all soft and slippery to touch",
            "They all dissolve readily in cold water",
        ],
        "correct_index": 0,
        "why": "Strong covalent bonds run throughout all three, so all three need a great deal of energy before they melt.",
    },
    {
        "id": "ks4-giant-covalent-structures-h05",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Each carbon atom in diamond forms four bonds, and each bond is shared between two atoms. Determine the number of covalent bonds among 500 carbon atoms.",
        "options": [
            "1000",
            "250",
            "500",
            "2000",
        ],
        "correct_index": 0,
        "why": "500 atoms with four bonds each gives 2000 bond ends, and each bond uses two ends, so there are 1000 bonds.",
    },
    {
        "id": "ks4-giant-covalent-structures-h06",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Each carbon atom in a graphite layer forms three bonds, each shared between two atoms. Determine the number of bonds in a layer of 600 carbon atoms.",
        "options": [
            "300",
            "900",
            "600",
            "1800",
        ],
        "correct_index": 1,
        "why": "600 atoms with three bonds each gives 1800 bond ends, and two ends make one bond, so there are 900 bonds.",
    },
    {
        "id": "ks4-giant-covalent-structures-h07",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Diamond resists being scratched and also resists being melted. Explain what these two facts have in common.",
        "options": [
            "Both depend on the same delocalised electrons holding the atoms",
            "Both would need the same network of strong covalent bonds disturbed",
            "Both depend on how tightly the layers of atoms are stacked together",
            "Each is decided by how heavy the individual carbon atoms are",
        ],
        "correct_index": 1,
        "why": "Scratching moves atoms and melting separates them, and each has to work against the same rigid covalent network.",
    },
    {
        "id": "ks4-giant-covalent-structures-h08",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a diamond can only be cut using another diamond.",
        "options": [
            "Because nothing else can reach the temperature needed to cut one",
            "Because only carbon can form a chemical bond to another carbon atom",
            "Because a diamond will only ever dissolve in a solution made of another diamond",
            "Because no other material is hard enough to scratch its bonded network",
        ],
        "correct_index": 3,
        "why": "Cutting means forcing atoms apart, and only a material at least as hard as diamond can do that to diamond.",
    },
    {
        "id": "ks4-giant-covalent-structures-h09",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "In silicon carbide each silicon atom is bonded to four carbon atoms and each carbon to four silicon atoms. Predict two of its properties.",
        "options": [
            "Very hard and very high melting, from strong bonds throughout",
            "Very soft and very low melting, from weak forces between layers",
            "Very hard but low melting, because the layers in it can slide apart",
            "Soft but high melting, because the bonds in it are strong yet few in number",
        ],
        "correct_index": 0,
        "why": "Four bonds on every atom builds the same rigid three-dimensional network diamond has, with the same consequences.",
    },
    {
        "id": "ks4-giant-covalent-structures-h10",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Graphite blocks are used as the brushes that carry current into the spinning part of an electric motor. Suggest two properties that suit them to the job.",
        "options": [
            "It conducts electricity, and it is hard enough to resist being worn",
            "It conducts electricity, and its layers slide against the moving part",
            "It insulates well, and its layers slide against the moving part",
            "It melts at a low temperature, and it also conducts electricity well",
        ],
        "correct_index": 1,
        "why": "The delocalised electrons carry the current while the sliding layers let the brush rub against a turning surface.",
    },
    {
        "id": "ks4-giant-covalent-structures-h11",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Predict what would happen to graphite's ability to conduct electricity if each of its carbon atoms formed four bonds instead of three.",
        "options": [
            "It would conduct better, because the extra bonds would carry the charge",
            "It would conduct just as well as before, since the atoms are unchanged",
            "It would stop conducting, since no electron would be left delocalised",
            "It would stop conducting, because its layers could no longer slide",
        ],
        "correct_index": 2,
        "why": "Graphite conducts through its one spare outer electron per atom, and a fourth bond would use that electron up.",
    },
    {
        "id": "ks4-giant-covalent-structures-h12",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why diamond counts as a giant covalent structure although it contains only one element.",
        "options": [
            "Because only carbon can build a giant structure",
            "Because a structure is giant once it holds a million atoms",
            "Because diamond is a compound of carbon with itself",
            "Because giant covalent describes the bonding, not the elements present",
        ],
        "correct_index": 3,
        "why": "The classification depends on covalent bonds extending throughout the solid, whatever elements happen to be in it.",
    },
    {
        "id": "ks4-giant-covalent-structures-h13",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student argues that because graphite's layers are held by weak forces, graphite must melt at a low temperature. Evaluate the argument.",
        "options": [
            "It is wrong: melting must break the strong bonds inside each layer",
            "It is right, because melting always overcomes the weakest forces first",
            "It is right, because the layers separate as soon as graphite is warmed",
            "It is wrong: graphite's layers are held to each other by covalent bonds",
        ],
        "correct_index": 0,
        "why": "Separating the layers is not melting; melting needs the covalent bonds within each layer broken, which takes far more energy.",
    },
    {
        "id": "ks4-giant-covalent-structures-h14",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Determine the number of delocalised electrons present in a piece of graphite containing 100 carbon atoms.",
        "options": [
            "25",
            "100",
            "300",
            "400",
        ],
        "correct_index": 1,
        "why": "Every carbon atom leaves exactly one of its four outer electrons delocalised, so 100 atoms give 100 electrons.",
    },
    {
        "id": "ks4-giant-covalent-structures-h15",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare what has to be broken to melt silicon dioxide with what has to be broken to melt diamond.",
        "options": [
            "Weak forces between molecules in one; covalent bonds in the other",
            "Ionic attractions in one; covalent bonds in the other of the two",
            "Silicon-oxygen covalent bonds in one; carbon-carbon covalent bonds in the other",
            "Covalent bonds in the one; the attraction of ions for electrons in the other",
        ],
        "correct_index": 2,
        "why": "Both are giant covalent, so melting either one means breaking strong covalent bonds right through the structure.",
    },
    {
        "id": "ks4-giant-covalent-structures-h16",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a giant covalent structure cannot be dissolved in water in the way an ionic compound can.",
        "options": [
            "Because water is simply not able to reach inside a giant covalent structure",
            "Because it is always far denser than water and so sinks instead",
            "Because its atoms are already surrounded and cannot take on more",
            "Because it holds no ions for water to attract away from the network",
        ],
        "correct_index": 3,
        "why": "Dissolving an ionic solid works by water attracting its ions away, and a covalent network offers water no ions at all.",
    },
    {
        "id": "ks4-giant-covalent-structures-h17",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why graphite is described as containing both strong and weak forces.",
        "options": [
            "Strong covalent bonds within each layer, weak forces between layers",
            "Weak covalent bonds within each of the layers, strong forces between them",
            "Strong bonds at the surface of the sample, weak bonds deep inside it",
            "Strong bonds while it is still cold, and weak ones once it has been heated",
        ],
        "correct_index": 0,
        "why": "The two kinds of force in graphite are what give it a high melting point and a slippery feel at the same time.",
    },
    {
        "id": "ks4-giant-covalent-structures-h18",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Predict what would happen to diamond's hardness if its atoms were rearranged into flat layers like graphite's.",
        "options": [
            "It would grow harder, because layers resist a blow better",
            "It would grow much softer, because the layers could slide",
            "It would be unchanged, because the atoms are still carbon",
            "It would grow harder, because each atom would form more bonds",
        ],
        "correct_index": 1,
        "why": "Hardness comes from bonds holding atoms in every direction, and layers held weakly to each other slide instead.",
    },
    {
        "id": "ks4-giant-covalent-structures-h19",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate this statement: 'A giant covalent structure never conducts electricity.'",
        "options": [
            "It is right, because a covalent structure holds no charged particles",
            "It is right, because all of the outer electrons there are used in bonds",
            "It is wrong: graphite bonds only three of its four outer electrons, so one is free",
            "It is wrong: every giant covalent structure will conduct once it is molten",
        ],
        "correct_index": 2,
        "why": "The rule holds for diamond and silicon dioxide, but graphite is the standing exception because of its spare electron.",
    },
    {
        "id": "ks4-giant-covalent-structures-h20",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Sand is mainly silicon dioxide. Suggest why sand does not melt in an ordinary Bunsen flame.",
        "options": [
            "The grains are too small for the flame to heat them right through",
            "Sand has no melting point, because it is a mixture of many substances",
            "The flame drives off the oxygen, leaving behind silicon that cannot melt",
            "The flame supplies too little energy to break its covalent network",
        ],
        "correct_index": 3,
        "why": "Silicon dioxide melts near 1710 °C, which is well above the temperature a Bunsen flame can reach.",
    },
    {
        "id": "ks4-giant-covalent-structures-h21",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A tiny chip of diamond scratches glass just as well as a large gemstone does. Explain why.",
        "options": [
            "The hardness comes from the bonding, which is the same in any piece",
            "The chip is sharper, and a sharp edge always cuts more effectively",
            "The chip and the gemstone contain exactly the same number of atoms",
            "The chip is lighter, so it presses on the glass more gently overall",
        ],
        "correct_index": 0,
        "why": "Hardness is a property of the covalent network, so every piece of diamond is as hard as every other.",
    },
    {
        "id": "ks4-giant-covalent-structures-h22",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the number of delocalised electrons in 1000 carbon atoms of graphite with the number in 1000 carbon atoms of diamond.",
        "options": [
            "0 in graphite and 1000 in diamond",
            "1000 in graphite and 0 in diamond",
            "1000 in each of the two",
            "4000 in graphite and 1000 in diamond",
        ],
        "correct_index": 1,
        "why": "Graphite leaves one outer electron per atom delocalised; diamond uses all four of every atom's outer electrons in bonds.",
    },
    {
        "id": "ks4-giant-covalent-structures-h23",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Diamond is denser than graphite. Suggest why, given how the atoms are arranged in each.",
        "options": [
            "Diamond's atoms are heavier than the carbon atoms in graphite",
            "Diamond's atoms are arranged in layers that are pressed very close together",
            "Diamond's atoms are bonded in every direction, with no gaps between layers",
            "Diamond's atoms carry a charge, which pulls them closer together",
        ],
        "correct_index": 2,
        "why": "Graphite has relatively wide gaps between its weakly held layers, while diamond's network packs its atoms throughout.",
    },
    {
        "id": "ks4-giant-covalent-structures-h24",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate this statement: 'Graphite conducts electricity, so it must contain ions that are free to move.'",
        "options": [
            "It is right, because only a moving ion can ever carry a current",
            "It is right, because graphite's own carbon atoms become ions on heating",
            "It is wrong: graphite conducts only once it has been dissolved in water",
            "It is wrong: the moving charges in graphite are delocalised electrons",
        ],
        "correct_index": 3,
        "why": "Graphite contains no ions at all; its conduction comes from the one delocalised electron each carbon atom leaves over.",
    },
    {
        "id": "ks4-giant-covalent-structures-h25",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Predict what would happen to graphite's usefulness as a lubricant if the forces between its layers were as strong as the bonds within them.",
        "options": [
            "It would be lost, because the layers could no longer slide apart",
            "It would improve, because the layers would slide more smoothly",
            "It would be unaffected, since lubricating depends only on conduction",
            "It would improve, because a stronger structure would last far longer",
        ],
        "correct_index": 0,
        "why": "Graphite lubricates only because its layers are weakly held; bonding them strongly would give a rigid solid instead.",
    },
    {
        "id": "ks4-giant-covalent-structures-h26",
        "subtopic_slug": "giant-covalent-structures",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain how diamond and graphite can both have very high melting points when only one of them conducts electricity.",
        "options": [
            "Melting depends on a spare electron; conducting depends on the covalent bonds",
            "Melting depends on the covalent bonds; conducting depends on a spare electron",
            "Melting and conducting both depend on the number of layers present",
            "Melting depends on the mass of the sample; conducting depends on its own shape",
        ],
        "correct_index": 1,
        "why": "Both structures have strong covalent bonds throughout, so both melt high; only graphite leaves an electron over to conduct.",
    },
]
