"""Chemistry · Energy changes — the MRB-338 expansion, subtopic
`reaction-profiles`.

The 23 shipped rows read Ea and ΔH off numeric profiles in both directions and
drill the Ea-is-not-ΔH confusion hard, but not one of them mentions a catalyst,
which is a third of the spec point's prose. The new weight therefore falls on
the catalyst material — the alternative lower-barrier pathway, the peak moving
while the two levels do not, enzymes and the named industrial catalysts, and
catalysed-against-uncatalysed calculations in both directions — with the rest
going to angles the leaf had not used: symbolic rearrangement of the Ea/ΔH
relationships, multi-step profiles where a level has to be derived before the
question can be answered, three-way comparison, and named real reactions
(thermite, methane, sodium azide, hydrogen peroxide) that separate how much
energy a reaction releases from how fast it goes.
"""

TOPIC = "energy-changes"
SUBJECT = "chemistry"

QUESTIONS = [
    # ── easier ───────────────────────────────────────────────────────────
    {
        "id": "ks4-reaction-profiles-e09",
        "subtopic_slug": "reaction-profiles",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how a catalyst increases the rate of a reaction.",
        "options": [
            "By providing an alternative reaction pathway that has a lower activation energy",
            "By transferring extra energy to the reactant particles so that they collide harder",
            "By lowering the energy level of the products so that more energy is given out",
            "By raising the energy level of the reactants so that they start closer to the peak",
        ],
        "correct_index": 0,
        "why": "A catalyst offers a different route to the same products over a smaller energy barrier, so a greater proportion of collisions are successful.",
    },
    {
        "id": "ks4-reaction-profiles-e10",
        "subtopic_slug": "reaction-profiles",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the type of substance that acts as a biological catalyst in living organisms.",
        "options": [
            "Hormones, which are released into the bloodstream so that they speed up the reactions in cells",
            "Antibodies, which lock onto the reactants and speed up the reactions going on in cells",
            "Antibiotics, which are taken up by cells to speed up their reactions",
            "Enzymes, which are the proteins that speed up specific reactions inside cells",
        ],
        "correct_index": 3,
        "why": "Enzymes are proteins that act as catalysts, lowering the activation energy of the reactions they control.",
    },
    {
        "id": "ks4-reaction-profiles-e11",
        "subtopic_slug": "reaction-profiles",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the metal used as the catalyst in the Haber process.",
        "options": [
            "Nickel, which is chosen because it lowers the barrier for reactions of nitrogen",
            "Iron, which lowers the activation energy for the reaction of nitrogen with hydrogen",
            "Copper, which lowers the activation energy for reactions between two gases held at high pressure",
            "Zinc, which is chosen because it lowers the barrier for reactions forming ammonia",
        ],
        "correct_index": 1,
        "why": "Iron is the catalyst in the Haber process: it lowers the activation energy so that ammonia forms fast enough at a workable temperature.",
    },
    {
        "id": "ks4-reaction-profiles-e12",
        "subtopic_slug": "reaction-profiles",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happens to the mass of a catalyst during the reaction it speeds up.",
        "options": [
            "It falls steadily, because some of the catalyst is used up in forming the products",
            "It rises, because the catalyst joins onto the products as they are being made",
            "It stays the same, because the catalyst is not used up by the reaction",
            "It falls at first and then returns to its starting value once the products form",
        ],
        "correct_index": 2,
        "why": "A catalyst takes part in the reaction but is left chemically unchanged at the end, so the mass recovered is the mass that was added.",
    },

    # ── standard ─────────────────────────────────────────────────────────
    {
        "id": "ks4-reaction-profiles-s09",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reaction profile shows the reactants at 160 kJ/mol. Without a catalyst the peak is at 310 kJ/mol; with a catalyst it is at 255 kJ/mol. Calculate the activation energy of the catalysed reaction.",
        "options": [
            "55 kJ/mol",
            "150 kJ/mol",
            "95 kJ/mol",
            "255 kJ/mol",
        ],
        "correct_index": 2,
        "why": "Activation energy is measured from the reactant level up to the peak, so the catalysed barrier is 255 − 160 = 95 kJ/mol.",
    },
    {
        "id": "ks4-reaction-profiles-s10",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain, in terms of colliding particles, why a catalyst makes a reaction faster at a fixed temperature.",
        "options": [
            "A greater proportion of the collisions now have at least the lower activation energy needed",
            "Each collision between the particles now carries much more energy than it did before the catalyst",
            "The particles collide more often because the catalyst pushes them closer together",
            "Every collision becomes successful once the catalyst has been added to the mixture",
        ],
        "correct_index": 0,
        "why": "The catalyst lowers the barrier rather than changing the particles, so a larger fraction of the collisions already happening carry enough energy to react.",
    },
    {
        "id": "ks4-reaction-profiles-s11",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A catalyst is added to an endothermic reaction. Predict the effect on the rate and on the overall energy change.",
        "options": [
            "The rate increases and the overall energy change becomes negative instead of positive",
            "The rate increases and the overall energy change stays positive and unchanged",
            "The rate increases and the overall energy change falls by the drop in the barrier",
            "The rate is unchanged, because catalysts work on exothermic reactions rather than endothermic ones",
        ],
        "correct_index": 1,
        "why": "A catalyst lowers only the barrier between the two levels, so the reaction goes faster while ΔH keeps the same positive value.",
    },
    {
        "id": "ks4-reaction-profiles-s12",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student says that a catalyst works by raising the energy of the reactant particles. Explain why this is wrong.",
        "options": [
            "A catalyst lowers the product energy level instead, which is what shortens the climb",
            "A catalyst leaves both energy levels where they are and offers a route with a lower barrier",
            "A catalyst raises the energy of the products rather than the reactants, making the drop smaller",
            "A catalyst raises the peak instead, so that the barrier is cleared sooner and the reaction speeds up",
        ],
        "correct_index": 1,
        "why": "A catalyst changes the route, not the chemicals: the reactant and product levels are untouched and the activation energy falls.",
    },
    {
        "id": "ks4-reaction-profiles-s13",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Vegetable oils are hardened by reacting them with hydrogen over a nickel catalyst. The reaction is exothermic. Predict how the energy released per mole would differ if no nickel were used.",
        "options": [
            "It would be greater, because none of the energy would be taken up by the nickel",
            "It would be smaller, because the reaction would run at a lower temperature without nickel",
            "No energy would be released at any stage, because the reaction is unable to happen without the nickel",
            "It would be the same, because the nickel changes the barrier and not the energy levels",
        ],
        "correct_index": 3,
        "why": "A catalyst leaves the reactant and product levels untouched, so ΔH — and the energy released per mole — is the same with or without it.",
    },
    {
        "id": "ks4-reaction-profiles-s14",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two identical flasks of hydrogen peroxide solution decompose to oxygen and water, and manganese(IV) oxide is added to one of them. Compare the final volume of oxygen and the time taken in the two flasks.",
        "options": [
            "The same final volume of oxygen, collected in a shorter time in the flask with the catalyst",
            "A larger final volume of oxygen, collected in a shorter time in the flask with the catalyst",
            "The same final volume of oxygen, collected in the same time, because the catalyst is used up early",
            "A smaller final volume of oxygen in a shorter time, because some oxygen stays on the catalyst",
        ],
        "correct_index": 0,
        "why": "A catalyst lowers the activation energy so that the same amount of product is made sooner; it changes the rate, not the amount.",
    },
    {
        "id": "ks4-reaction-profiles-s15",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The reactants on a reaction profile lie at energy E and the activation energy is Ea. Determine the energy of the peak of the curve.",
        "options": [
            "E − Ea, since the barrier is measured downwards from the reactant level",
            "Ea − E, since the reactant level is subtracted from the height of the barrier",
            "E + Ea, since the barrier is measured upwards from the reactant level",
            "E + 2Ea, since the curve climbs the barrier and then falls back down it",
        ],
        "correct_index": 2,
        "why": "The activation energy is the height of the peak above the reactant level, so the peak sits at E + Ea.",
    },
    {
        "id": "ks4-reaction-profiles-s16",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The peak of a reaction profile is at 520 kJ/mol and the products are at 465 kJ/mol. Determine the activation energy of the reverse reaction.",
        "options": [
            "465 kJ/mol",
            "985 kJ/mol",
            "55 kJ/mol",
            "520 kJ/mol",
        ],
        "correct_index": 2,
        "why": "The reverse reaction sets off from the product level and must climb to the same peak: 520 − 465 = 55 kJ/mol.",
    },
    {
        "id": "ks4-reaction-profiles-s17",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Three reactions run at the same temperature have activation energies of 25 kJ/mol, 95 kJ/mol and 180 kJ/mol. Predict the order of their rates, fastest first.",
        "options": [
            "180, 95 then 25, because a bigger barrier means more energy is available to react",
            "25, 95 then 180, because a smaller barrier lets a bigger fraction of collisions succeed",
            "95, 25 then 180, because a middling barrier suits the particles in the mixture best",
            "They react at the same rate, because activation energy sets the energy released and not the speed",
        ],
        "correct_index": 1,
        "why": "The lower the activation energy, the greater the proportion of collisions carrying enough energy to react, so the faster the reaction.",
    },
    {
        "id": "ks4-reaction-profiles-s18",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The thermite reaction between aluminium and iron(III) oxide is started with a burning magnesium fuse and then gives out a great deal of energy. Describe the reaction profile you would expect for it.",
        "options": [
            "A low peak just above the reactants, with the products ending well below the level they started from",
            "A high peak above the reactants, with the products ending well above the level of the reactants",
            "A high peak above the reactants, with the products ending well below the reactant level",
            "No peak, with the curve falling steadily from the reactants down to the products",
        ],
        "correct_index": 2,
        "why": "The fuse is needed because the barrier is high, and the large energy release means the products finish far below the reactants.",
    },
    {
        "id": "ks4-reaction-profiles-s19",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Without a catalyst, a reaction profile shows the reactants at 275 kJ/mol, the peak at 400 kJ/mol and the products at 140 kJ/mol. A catalyst lowers the peak to 345 kJ/mol. Determine ΔH for the catalysed reaction.",
        "options": [
            "−80 kJ/mol",
            "−135 kJ/mol",
            "+135 kJ/mol",
            "−190 kJ/mol",
        ],
        "correct_index": 1,
        "why": "A catalyst does not move the reactant or product levels, so ΔH is still 140 − 275 = −135 kJ/mol.",
    },
    {
        "id": "ks4-reaction-profiles-s20",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Enzymes allow reactions in the human body to go quickly at about 37 °C. Explain how an enzyme achieves this.",
        "options": [
            "It raises the temperature of the cell so that collisions carry more energy than before",
            "It gives each reactant particle extra energy so that a collision becomes successful",
            "It raises the activation energy so that the reaction can be held at body temperature",
            "It lowers the activation energy so that enough collisions succeed at body temperature",
        ],
        "correct_index": 3,
        "why": "An enzyme is a biological catalyst: it lowers the barrier, so a much larger fraction of the collisions happening at 37 °C are successful.",
    },
    {
        "id": "ks4-reaction-profiles-s21",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the profile of a catalysed reaction still shows a peak rather than a flat line.",
        "options": [
            "The catalyst itself has to be heated up first, before it will begin to act on the reactant particles",
            "Bonds in the reactants still have to be broken, so some energy is still needed to start it",
            "The peak is drawn there by convention, although a catalysed reaction has no barrier left to climb",
            "The products still have to be broken apart before the reactants are able to form them",
        ],
        "correct_index": 1,
        "why": "A catalyst lowers the barrier but cannot remove it — existing bonds must still be broken before new ones can form.",
    },
    {
        "id": "ks4-reaction-profiles-s22",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The catalyst in a car's catalytic converter speeds up the oxidation of carbon monoxide in the exhaust gases as they pass through it. Explain how it achieves this.",
        "options": [
            "It heats the exhaust gases so that the collisions between them carry far more energy",
            "It absorbs the carbon monoxide onto its surface and stores it there until the engine has cooled down",
            "It raises the energy of the carbon monoxide so that it starts much closer to the peak",
            "It offers the gases a route with a lower activation energy, so far more collisions succeed",
        ],
        "correct_index": 3,
        "why": "The converter's catalyst lowers the activation energy, so a far greater proportion of the collisions in the short time available are successful.",
    },
    {
        "id": "ks4-reaction-profiles-s23",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "With a catalyst, a reaction has its reactants at 205 kJ/mol and its peak at 285 kJ/mol. Without the catalyst the activation energy was 128 kJ/mol. Calculate the reduction in activation energy the catalyst produces.",
        "options": [
            "80 kJ/mol",
            "128 kJ/mol",
            "205 kJ/mol",
            "48 kJ/mol",
        ],
        "correct_index": 3,
        "why": "The catalysed barrier is 285 − 205 = 80 kJ/mol, so the catalyst has lowered the activation energy by 128 − 80 = 48 kJ/mol.",
    },
    {
        "id": "ks4-reaction-profiles-s24",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "In one reaction the chemicals start at 480 kJ/mol, climb to 605 kJ/mol and finish at 315 kJ/mol. Determine the forward activation energy and the type of reaction.",
        "options": [
            "290 kJ/mol, exothermic",
            "125 kJ/mol, endothermic",
            "125 kJ/mol, exothermic",
            "165 kJ/mol, exothermic",
        ],
        "correct_index": 2,
        "why": "The climb from 480 kJ/mol to the peak at 605 kJ/mol is 125 kJ/mol, and the products finish below the reactants, so energy is given out.",
    },
    {
        "id": "ks4-reaction-profiles-s25",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The sodium azide in a car airbag decomposes completely within about 40 milliseconds of the crash sensor firing. Suggest what this shows about the activation energy of the decomposition.",
        "options": [
            "It is low, so a very large proportion of collisions are successful once the reaction starts",
            "It is high, so the collisions between the particles release a very large amount of energy in one instant",
            "It is zero, because a reaction that fast has no energy barrier to be climbed",
            "It is high, because a high barrier makes the particles react as quickly as they can",
        ],
        "correct_index": 0,
        "why": "How fast a reaction goes is set by its barrier, not by ΔH, and a reaction complete in milliseconds at ordinary temperature must have a low one.",
    },
    {
        "id": "ks4-reaction-profiles-s26",
        "subtopic_slug": "reaction-profiles",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two profiles are drawn for one reaction. In the first the reactants are at 90 kJ/mol, the peak at 300 kJ/mol and the products at 30 kJ/mol. In the second the reactants are at 90 kJ/mol, the peak at 220 kJ/mol and the products at 30 kJ/mol. Suggest what has been done in the second.",
        "options": [
            "A catalyst has been added: only the peak has moved, and both levels stay where they were",
            "The mixture has been heated, which lowers the barrier while leaving both levels unchanged",
            "A different set of products has been made, which needs less energy to be reached",
            "More reactant has been used, so a smaller barrier is left for each of the colliding particles to climb",
        ],
        "correct_index": 0,
        "why": "The reactant and product levels, and so ΔH, are identical in the two profiles, and a change to the peak alone is the signature of a catalyst.",
    },

    # ── harder ───────────────────────────────────────────────────────────
    {
        "id": "ks4-reaction-profiles-h08",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reaction has a forward activation energy of 210 kJ/mol and ΔH = +65 kJ/mol. A catalyst brings the forward activation energy down to 150 kJ/mol. Determine the activation energy of the reverse reaction along the catalysed route.",
        "options": [
            "215 kJ/mol",
            "85 kJ/mol",
            "145 kJ/mol",
            "60 kJ/mol",
        ],
        "correct_index": 1,
        "why": "The catalysed peak lies 150 kJ/mol above the reactants and the products sit 65 kJ/mol above them, so from the products the climb is 150 − 65 = 85 kJ/mol.",
    },
    {
        "id": "ks4-reaction-profiles-h09",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A catalyst lowers the forward activation energy of a reaction by 40 kJ/mol. Determine the change in the activation energy of the reverse reaction.",
        "options": [
            "It also falls by 40 kJ/mol, because the peak drops while both levels stay put",
            "It rises by 40 kJ/mol, because the forward route has taken that energy from it",
            "It is unchanged, because a catalyst acts on the forward reaction rather than the reverse",
            "It falls by 80 kJ/mol, because the drop counts once on the way up and once on the way down",
        ],
        "correct_index": 0,
        "why": "Both barriers are measured up to the same peak, so lowering that peak by 40 kJ/mol lowers the forward and the reverse activation energies equally.",
    },
    {
        "id": "ks4-reaction-profiles-h10",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "For one reaction the chemicals start at 340 kJ/mol and the overall energy change is −120 kJ/mol. Climbing back from the products to the peak takes 190 kJ/mol. Calculate the forward activation energy.",
        "options": [
            "190 kJ/mol",
            "310 kJ/mol",
            "70 kJ/mol",
            "120 kJ/mol",
        ],
        "correct_index": 2,
        "why": "The products lie at 340 − 120 = 220 kJ/mol; the peak is 190 kJ/mol above them, at 410 kJ/mol, which is 410 − 340 = 70 kJ/mol above the reactants.",
    },
    {
        "id": "ks4-reaction-profiles-h11",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Three reactions run at the same temperature. A has Ea = 30 kJ/mol and ΔH = −25 kJ/mol; B has Ea = 30 kJ/mol and ΔH = −310 kJ/mol; C has Ea = 185 kJ/mol and ΔH = −310 kJ/mol. Determine which releases the most energy per mole and which is slowest.",
        "options": [
            "C releases the most on its own, and C is also the fastest of the three",
            "B releases the most on its own, and A is the slowest of the three",
            "A releases the most, because its barrier is the smallest of the three, and A is also the fastest",
            "B and C release the most and release it equally, and C is the slowest of the three",
        ],
        "correct_index": 3,
        "why": "ΔH sets the energy released, so B and C give out 310 kJ/mol each; the barrier sets the rate, so C's 185 kJ/mol climb makes it the slowest.",
    },
    {
        "id": "ks4-reaction-profiles-h12",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A manufacturer claims that adding a catalyst to a batch reaction will produce more product from the same mass of reactants. Evaluate this claim.",
        "options": [
            "It is wrong: the same amount of product is made, and the catalyst only makes it arrive sooner",
            "It is right: a lower barrier lets a larger share of the reactant particles turn into product in the end",
            "It is right: the catalyst adds to the mass of the product because it is built into it",
            "It is wrong: less product is made, because some of the reactant is turned into the catalyst itself",
        ],
        "correct_index": 0,
        "why": "A catalyst changes the rate, not the amount: the same reactants reach the same products, and only the time taken is shorter.",
    },
    {
        "id": "ks4-reaction-profiles-h13",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "An uncatalysed profile has reactants at 180 kJ/mol, a peak at 425 kJ/mol and products at 95 kJ/mol. A catalyst brings the peak down to 330 kJ/mol. Determine the catalysed forward and reverse activation energies.",
        "options": [
            "150 kJ/mol forward and 330 kJ/mol reverse",
            "150 kJ/mol forward and 235 kJ/mol reverse",
            "95 kJ/mol forward and 235 kJ/mol reverse",
            "245 kJ/mol forward and 330 kJ/mol reverse",
        ],
        "correct_index": 1,
        "why": "The catalysed peak of 330 kJ/mol is 330 − 180 = 150 kJ/mol above the reactants and 330 − 95 = 235 kJ/mol above the products.",
    },
    {
        "id": "ks4-reaction-profiles-h14",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Write the activation energy of the reverse reaction in terms of the forward activation energy Ea and the overall energy change ΔH.",
        "options": [
            "Ea + ΔH, since the climb back begins from the product level",
            "Ea − ΔH, since the climb back begins from the product level",
            "ΔH − Ea, since the reverse reaction runs from the products down",
            "Ea on its own, since the barrier is the same height in both directions",
        ],
        "correct_index": 1,
        "why": "The peak is Ea above the reactants and the products sit ΔH above them, so the climb from the products is Ea − ΔH.",
    },
    {
        "id": "ks4-reaction-profiles-h15",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "An endothermic reaction has its reactants at 120 kJ/mol, ΔH = +75 kJ/mol and an activation energy of 140 kJ/mol. A catalyst lowers the activation energy to 95 kJ/mol. Determine the new peak energy and ΔH.",
        "options": [
            "215 kJ/mol and ΔH = +30 kJ/mol",
            "260 kJ/mol and ΔH = +75 kJ/mol",
            "170 kJ/mol and ΔH = +30 kJ/mol",
            "215 kJ/mol and ΔH = +75 kJ/mol",
        ],
        "correct_index": 3,
        "why": "The peak sits one activation energy above the reactants, at 120 + 95 = 215 kJ/mol, and a catalyst leaves both levels — and so ΔH — untouched.",
    },
    {
        "id": "ks4-reaction-profiles-h16",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Methane burns in air with ΔH of about −890 kJ/mol, but a gas hob needs a spark to light it. Sodium reacts with water on contact at room temperature with ΔH of about −184 kJ/mol. Compare the activation energies of the two reactions.",
        "options": [
            "Sodium's is much the higher, because the reaction that releases less energy is the one needing a bigger push",
            "They are about equal, because the activation energy of a reaction is set by the energy that it releases",
            "Methane's is much the higher, showing that the barrier and the energy released are independent",
            "Methane's is much the lower, because the reaction releasing more energy clears its barrier sooner",
        ],
        "correct_index": 2,
        "why": "Methane needs a spark because its barrier is high and sodium reacts unaided because its barrier is low, and neither fact follows from how negative ΔH is.",
    },
    {
        "id": "ks4-reaction-profiles-h17",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two curves are drawn on one set of axes. Both start at 250 kJ/mol and both finish at 310 kJ/mol; one peaks at 400 kJ/mol and the other at 355 kJ/mol. A student says the lower curve shows the reaction releasing less energy. Evaluate that statement.",
        "options": [
            "It is wrong: both take in 60 kJ/mol, and the lower curve shows a smaller barrier rather than a smaller ΔH",
            "It is right: a lower peak means less energy has to be put in, so less comes out at the end",
            "It is right: the curve with the lower peak has a smaller overall energy change of 45 kJ/mol",
            "It is wrong: both release 60 kJ/mol, since the products of both curves finish below the reactants they came from",
        ],
        "correct_index": 0,
        "why": "Both curves run from 250 kJ/mol up to 310 kJ/mol, so both take energy in; the 45 kJ/mol difference in peak height is a difference of barrier only.",
    },
    {
        "id": "ks4-reaction-profiles-h18",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reaction has a forward activation energy of 60 kJ/mol and ΔH = −140 kJ/mol. Compare the rate of the forward reaction with the rate of the reverse reaction at the same temperature.",
        "options": [
            "The reverse is much faster, because its barrier of 200 kJ/mol gives its particles more energy to use",
            "They go at the same rate, because the barrier is measured down from the peak in both directions",
            "The forward is much faster, because its barrier of 60 kJ/mol is far below the reverse barrier of 80 kJ/mol",
            "The forward is much faster, because its barrier of 60 kJ/mol is far below the reverse barrier of 200 kJ/mol",
        ],
        "correct_index": 3,
        "why": "The reverse climb is Ea − ΔH = 60 + 140 = 200 kJ/mol, so far fewer reverse collisions carry enough energy to clear it.",
    },
    {
        "id": "ks4-reaction-profiles-h19",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "An exothermic industrial reaction is too slow at room temperature. Evaluate the use of a catalyst rather than a furnace to speed it up.",
        "options": [
            "The catalyst raises the barrier, and doing that costs far less than the fuel that a furnace would burn",
            "The furnace is the better choice, because heating lowers the barrier permanently",
            "The catalyst lowers the barrier without the fuel cost of heating, and it is not used up",
            "The catalyst changes ΔH so that more energy is released, which pays for the furnace",
        ],
        "correct_index": 2,
        "why": "A catalyst gives a faster reaction by lowering the activation energy and is recovered chemically unchanged, so it avoids the running cost of heating.",
    },
    {
        "id": "ks4-reaction-profiles-h20",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "For a catalysed reaction the peak lies at 270 kJ/mol and the catalysed activation energy is 85 kJ/mol. The overall energy change is −145 kJ/mol. Determine the energy level of the products.",
        "options": [
            "125 kJ/mol",
            "40 kJ/mol",
            "185 kJ/mol",
            "415 kJ/mol",
        ],
        "correct_index": 1,
        "why": "The reactants sit one activation energy below the peak, at 270 − 85 = 185 kJ/mol, so the products are at 185 − 145 = 40 kJ/mol.",
    },
    {
        "id": "ks4-reaction-profiles-h21",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Adding a catalyst lowers a reaction's peak by 62 kJ/mol, leaving a catalysed activation energy of 74 kJ/mol. The reaction has ΔH = +28 kJ/mol. Determine the uncatalysed forward and reverse activation energies.",
        "options": [
            "136 kJ/mol forward and 164 kJ/mol reverse",
            "12 kJ/mol forward and 46 kJ/mol reverse",
            "136 kJ/mol forward and 108 kJ/mol reverse",
            "74 kJ/mol forward and 46 kJ/mol reverse",
        ],
        "correct_index": 2,
        "why": "The uncatalysed barrier is 74 + 62 = 136 kJ/mol, and the reverse climb is that minus ΔH: 136 − 28 = 108 kJ/mol.",
    },
    {
        "id": "ks4-reaction-profiles-h22",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "At the same temperature, one catalyst lowers a reaction's activation energy from 120 kJ/mol to 70 kJ/mol, while another lowers a different reaction's from 95 kJ/mol to 80 kJ/mol. Predict which catalyst produces the greater increase in rate, and explain.",
        "options": [
            "The second, because it leaves the higher barrier, which the particles then clear with far more energy",
            "The second, because its reaction had the lower barrier to begin with and so responds more strongly to a catalyst",
            "Neither, because the increase in rate depends on the final barrier rather than on the fall in it",
            "The first, because its barrier falls furthest, so the largest extra share of collisions succeeds",
        ],
        "correct_index": 3,
        "why": "The size of the increase in rate follows the size of the drop in the barrier, so a 50 kJ/mol fall raises the rate far more than a 15 kJ/mol fall.",
    },
    {
        "id": "ks4-reaction-profiles-h23",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Nitrogen and hydrogen are combined industrially at about 450 °C over a metal catalyst, while bacteria in root nodules combine them at ordinary soil temperatures using an enzyme. Suggest what this shows about the two catalysts.",
        "options": [
            "The metal lowers the barrier further, which is the reason that industry is able to run the reaction so much hotter",
            "The enzyme lowers the barrier much further, which is why no heating is needed for the same rate",
            "The enzyme raises the barrier, which is the reason the bacteria need no heating to make it work for them",
            "Both lower the barrier by the same amount, and the difference in temperature comes from their ΔH values",
        ],
        "correct_index": 1,
        "why": "A reaction that runs quickly at a far lower temperature must be crossing a far lower barrier, so the enzyme is the more effective catalyst.",
    },
    {
        "id": "ks4-reaction-profiles-h24",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "The peak of a profile lies P kJ/mol above the product level, and the reaction is exothermic with an overall energy change of −Q kJ/mol. Determine the forward activation energy.",
        "options": [
            "P + Q, adding the drop down to the products onto the climb up from them",
            "P − Q, since the reactants start Q kJ/mol above the product level",
            "Q − P, since the products lie below the peak by exactly that amount",
            "P on its own, since the peak is the same height above each of the two levels",
        ],
        "correct_index": 1,
        "why": "The products lie Q kJ/mol below the reactants and the peak is P kJ/mol above the products, so the forward climb is P − Q.",
    },
    {
        "id": "ks4-reaction-profiles-h25",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "One reaction has a peak barely above its reactant level and products far below it. Another has a peak far above its reactant level and products only slightly below it. Compare the rates and the energy released.",
        "options": [
            "The first is slower and releases more energy; the second is faster and releases less",
            "Both go at the same rate; the first releases more energy and the second releases less",
            "The first is faster and releases more energy; the second is slower and releases less",
            "The first is faster and releases less energy; the second is slower and releases more",
        ],
        "correct_index": 2,
        "why": "A low barrier makes a reaction fast and a large drop to the products makes it release a lot of energy, so the first reaction wins on both counts.",
    },
    {
        "id": "ks4-reaction-profiles-h26",
        "subtopic_slug": "reaction-profiles",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "To show the effect of a catalyst, a student redraws a profile by keeping the peak at the same height and raising the reactant level instead. Identify what is wrong with this.",
        "options": [
            "Raising the reactant level changes ΔH, which a catalyst cannot do; the peak itself must come down",
            "Raising the reactant level lowers the barrier too far, so the reaction would need no energy to start",
            "Raising the reactant level suits a catalyst, but the peak should have been raised by the same amount",
            "Raising the reactant level suits a catalyst, but the product level should have been raised as well",
        ],
        "correct_index": 0,
        "why": "A catalyst offers a lower-energy route, which lowers the peak; the reactant and product levels — and so ΔH — stay exactly where they are.",
    },
]
