"""Chemistry · Organic chemistry — the MRB-338 expansion for `alcohols`.

The twelve shipped rows own the -OH group, ethanol's formula, ethanol in
drinks, the gas released with sodium, why ethanol mixes with water, the
combustion equation, wine turning sour, the fermentation equation, the
hydration-against-fermentation purity comparison, the 15 per cent ceiling,
the butanol-against-butane boiling point and methanol's toxicity.

This file takes the first four members as a SERIES — methanol, ethanol,
propanol and butanol by name, by formula and by the general formula
CnH2n+1OH — and the fermentation process as a method rather than as one
equation: the yeast, the sugar, the warm temperature and why a hotter vat is
worse, the anaerobic condition and why it is needed, the carbon dioxide given
off, and the distillation that follows because the product is dilute. It also
covers what alcohols are USED for beyond drinks (solvents and fuels), the
neutral pH of an alcohol solution, the oxidation product, and the
calculations a pupil can do on them — relative formula mass, percentage by
mass, mass of ethanol from a mass of glucose.

⚠️ Making ethanol by ADDING steam to ethene belongs to
`reactions-of-alkenes`; what ethanoic acid then does belongs to
`carboxylic-acids`. Formulae are written flat (C2H5OH, C6H12O6).
"""

TOPIC = "organic"
SUBJECT = "chemistry"

QUESTIONS = [
    # ---------------------------------------------------------------- easier
    {
        "id": "ks4-alcohols-e05",
        "subtopic_slug": "alcohols",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the alcohol whose molecules contain one carbon atom.",
        "options": [
            "Propanol",
            "Ethanol",
            "Methane",
            "Methanol",
        ],
        "correct_index": 3,
        "why": "'Meth-' means one carbon atom and '-ol' marks the alcohol group.",
    },
    {
        "id": "ks4-alcohols-e06",
        "subtopic_slug": "alcohols",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State the formula of methanol.",
        "options": [
            "CH3OH",
            "CH4",
            "C2H5OH",
            "CH3COOH",
        ],
        "correct_index": 0,
        "why": "One carbon atom carrying three hydrogens and one hydroxyl group gives CH3OH.",
    },
    {
        "id": "ks4-alcohols-e07",
        "subtopic_slug": "alcohols",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the alcohol whose molecules contain four carbon atoms.",
        "options": [
            "Butane",
            "Butene",
            "Butanol",
            "Propanol",
        ],
        "correct_index": 2,
        "why": "'But-' counts four carbon atoms and '-ol' shows the hydroxyl group.",
    },
    {
        "id": "ks4-alcohols-e08",
        "subtopic_slug": "alcohols",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Give the general formula of the alcohols.",
        "options": [
            "CnH2n+2",
            "CnH2n+1OH",
            "CnH2n",
            "CnH2nCOOH",
        ],
        "correct_index": 1,
        "why": "An alkyl chain of CnH2n+1 carries the -OH group.",
    },
    {
        "id": "ks4-alcohols-e09",
        "subtopic_slug": "alcohols",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the microorganism used to ferment sugar into ethanol.",
        "options": [
            "Mould",
            "Algae",
            "A virus",
            "Yeast",
        ],
        "correct_index": 3,
        "why": "Yeast supplies the enzymes that convert sugar into ethanol and carbon dioxide.",
    },
    {
        "id": "ks4-alcohols-e10",
        "subtopic_slug": "alcohols",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State the pH of a solution of ethanol in water.",
        "options": [
            "About 2, because the hydroxyl group releases hydrogen ions into the water",
            "About 4",
            "About 13, because the hydroxyl group makes the solution strongly alkaline",
            "About 7",
        ],
        "correct_index": 3,
        "why": "Alcohols dissolve to give neutral solutions; the -OH group does not ionise in water.",
    },
    {
        "id": "ks4-alcohols-e11",
        "subtopic_slug": "alcohols",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Give one use of alcohols other than in drinks.",
        "options": [
            "As a metal for making cooking pans, because it conducts heat extremely well",
            "As a building material for road surfaces and the flat roofs of large buildings",
            "As a solvent",
            "As a fertiliser spread on fields to supply nitrogen to a growing crop of wheat",
        ],
        "correct_index": 2,
        "why": "Alcohols are widely used as solvents and as fuels.",
    },
    {
        "id": "ks4-alcohols-e12",
        "subtopic_slug": "alcohols",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the sugar that yeast ferments to make ethanol.",
        "options": [
            "Glucose",
            "Cellulose",
            "Starch",
            "Protein",
        ],
        "correct_index": 0,
        "why": "Glucose, C6H12O6, is broken down by the enzymes in yeast.",
    },
    # -------------------------------------------------------------- standard
    {
        "id": "ks4-alcohols-s05",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Give the formula of propanol.",
        "options": [
            "C3H8",
            "C2H5OH",
            "C3H6OH",
            "C3H7OH",
        ],
        "correct_index": 3,
        "why": "Three carbons give the alkyl group C3H7, which carries the -OH.",
    },
    {
        "id": "ks4-alcohols-s06",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Give the conditions needed for fermentation to take place.",
        "options": [
            "A high temperature of about 300 degrees Celsius, high pressure and a solid catalyst",
            "A strong acid, a cold room, and a steady stream of oxygen bubbled through the vat",
            "Yeast, a warm temperature of about 30 degrees Celsius, and no air",
            "Sunlight and chlorophyll",
        ],
        "correct_index": 2,
        "why": "Yeast works best at body-warm temperatures in an aqueous mixture without oxygen.",
    },
    {
        "id": "ks4-alcohols-s07",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why air must be kept out of a fermentation vessel.",
        "options": [
            "Because air would cool the mixture below the temperature the yeast needs to work",
            "Because the nitrogen in air reacts with the sugar before the yeast can reach it",
            "Because with oxygen the yeast respires aerobically and makes no ethanol",
            "Because air would dissolve the yeast",
        ],
        "correct_index": 2,
        "why": "Anaerobic respiration in yeast is what produces ethanol; with air it gives carbon dioxide and water.",
    },
    {
        "id": "ks4-alcohols-s08",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the gas that bubbles out of the mixture during fermentation.",
        "options": [
            "Hydrogen",
            "Carbon dioxide",
            "Oxygen",
            "Methane",
        ],
        "correct_index": 1,
        "why": "Each glucose molecule gives two molecules of ethanol and two of carbon dioxide.",
    },
    {
        "id": "ks4-alcohols-s09",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Describe what is seen when a small piece of sodium is dropped into ethanol.",
        "options": [
            "It fizzes steadily and the sodium gradually disappears",
            "Nothing happens, because sodium reacts with water but not with any alcohol",
            "The mixture turns deep blue and a solid settles at the bottom of the beaker",
            "The ethanol boils away instantly and leaves the sodium behind unchanged",
        ],
        "correct_index": 0,
        "why": "The hydrogen released makes the bubbles, and the sodium is used up in the reaction.",
    },
    {
        "id": "ks4-alcohols-s10",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why ethanol is chosen as the solvent in perfumes and inks.",
        "options": [
            "It dissolves substances that water cannot, and it evaporates readily",
            "It is the cheapest liquid that can be bought anywhere in large quantities",
            "It stays on the skin for a very long time because it hardly evaporates at all",
            "It reacts with the perfume",
        ],
        "correct_index": 0,
        "why": "Its -OH group and its carbon chain let it dissolve both watery and oily substances, and it dries quickly.",
    },
    {
        "id": "ks4-alcohols-s11",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "State why chemists place the alcohols in one homologous series.",
        "options": [
            "Because every one of them is a liquid at ordinary room temperature and pressure",
            "Because they share the -OH group and one general formula, differing by CH2",
            "Because all of them can be made by fermenting a sugar with a suitable yeast",
            "Because they all dissolve in water",
        ],
        "correct_index": 1,
        "why": "A shared functional group and general formula are what define a homologous series.",
    },
    {
        "id": "ks4-alcohols-s12",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Which equation represents the complete combustion of methanol?",
        "options": [
            "CH3OH + O2 goes to CO2 + 2H2O",
            "CH3OH + 2O2 goes to CO + 2H2O",
            "2CH3OH + 3O2 goes to 2CO2 + 4H2O",
            "2CH3OH + O2 goes to 2CO2 + 4H2",
        ],
        "correct_index": 2,
        "why": "Two methanol molecules give 2CO2 and 4H2O, and the oxygen balances at 3O2.",
    },
    {
        "id": "ks4-alcohols-s13",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why the liquid from a fermentation vessel is distilled before it is sold as a spirit.",
        "options": [
            "Because the mixture is dilute, and distillation separates the ethanol from the water",
            "Because distillation turns the water in the mixture into more ethanol",
            "Because the yeast must be killed by heating the mixture up to its boiling point",
            "Because the carbon dioxide has to be driven out of the liquid before it is bottled",
        ],
        "correct_index": 0,
        "why": "Ethanol boils at 78 degrees Celsius, well below water, so it can be collected first.",
    },
    {
        "id": "ks4-alcohols-s14",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Predict how the boiling points of methanol, ethanol and propanol compare.",
        "options": [
            "They fall as the carbon chain gets longer, because a longer molecule is lighter",
            "They rise and then fall again at propanol",
            "They are all identical, because each of the three holds exactly one -OH group",
            "They rise as the carbon chain gets longer",
        ],
        "correct_index": 3,
        "why": "Longer chains mean stronger forces between the molecules, so more energy is needed to separate them.",
    },
    {
        "id": "ks4-alcohols-s15",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the compound formed when ethanol is oxidised.",
        "options": [
            "Ethanoic acid",
            "Ethene",
            "Ethane",
            "Methanol",
        ],
        "correct_index": 0,
        "why": "Oxidation converts the alcohol group into a carboxyl group, giving ethanoic acid.",
    },
    {
        "id": "ks4-alcohols-s16",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why an alcohol cannot be classed as a hydrocarbon.",
        "options": [
            "Because its molecules contain an oxygen atom as well as carbon and hydrogen",
            "Because it dissolves in water, and a hydrocarbon is never soluble in water",
            "Because it is made in a laboratory rather than being taken out of crude oil",
            "Because it burns to give carbon dioxide",
        ],
        "correct_index": 0,
        "why": "A hydrocarbon contains carbon and hydrogen only, and the -OH group brings in oxygen.",
    },
    {
        "id": "ks4-alcohols-s17",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "An alcohol is burned in a spirit burner. Name the two products formed in a good supply of air.",
        "options": [
            "Carbon monoxide and hydrogen gas, which escape from the top of the burner",
            "Carbon dioxide and water",
            "Soot and steam, together with a small amount of unburned alcohol vapour",
            "Hydrogen and oxygen",
        ],
        "correct_index": 1,
        "why": "Complete combustion oxidises the carbon to carbon dioxide and the hydrogen to water.",
    },
    {
        "id": "ks4-alcohols-s18",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Describe the arrangement of the atoms in a molecule of ethanol.",
        "options": [
            "Two carbon atoms joined by a double bond, with an -OH group on each of them",
            "A ring of carbon atoms with the oxygen atom sitting in the middle of the ring",
            "One carbon atom holding two -OH groups and three hydrogen atoms besides them",
            "Two carbon atoms joined by a single bond, one of them carrying an -OH group",
        ],
        "correct_index": 3,
        "why": "C2H5OH is a two-carbon chain, saturated, with the hydroxyl group on the end carbon.",
    },
    {
        "id": "ks4-alcohols-s19",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Work out the mass of one mole of ethanol, C2H5OH, using C = 12, H = 1 and O = 16.",
        "options": [
            "44",
            "30",
            "48",
            "46",
        ],
        "correct_index": 3,
        "why": "(2 x 12) + (6 x 1) + 16 = 46.",
    },
    {
        "id": "ks4-alcohols-s20",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why some countries add ethanol to the fuel sold for cars.",
        "options": [
            "Because ethanol is a gas and mixes with the air more easily than petrol vapour does",
            "Because ethanol releases no carbon dioxide of any kind when it is burned in an engine",
            "Because ethanol can be grown as a crop, so it is a renewable fuel",
            "Because ethanol cannot catch fire",
        ],
        "correct_index": 2,
        "why": "Sugar cane and other crops can be fermented, so the fuel does not have to come from crude oil.",
    },
    {
        "id": "ks4-alcohols-s21",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Predict whether propanol dissolves in water, and justify your prediction.",
        "options": [
            "No, because its carbon chain keeps it away from the water molecules entirely",
            "No, because an alcohol reacts with water instead of dissolving in it",
            "Yes, because its -OH group is attracted to water molecules",
            "Yes, because it is a gas",
        ],
        "correct_index": 2,
        "why": "The hydroxyl group lets the molecule hydrogen bond with water, so the short alcohols are soluble.",
    },
    {
        "id": "ks4-alcohols-s22",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Fermentation is kept at about 30 degrees Celsius. Explain why a much hotter vat would be a mistake.",
        "options": [
            "The sugar would dissolve too quickly for the yeast to reach any of it in time",
            "The ethanol would turn back into sugar as soon as the temperature climbed",
            "The enzymes in the yeast would denature, so fermentation would stop",
            "The carbon dioxide would dissolve",
        ],
        "correct_index": 2,
        "why": "Enzymes lose their shape above roughly 40 degrees Celsius and stop working.",
    },
    {
        "id": "ks4-alcohols-s23",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name both products of the fermentation of glucose.",
        "options": [
            "Ethanol and carbon dioxide",
            "Ethanol and oxygen, which bubbles out of the mixture as the reaction proceeds",
            "Ethanoic acid and water, which stay behind in the vessel as a dilute solution",
            "Methanol and hydrogen",
        ],
        "correct_index": 0,
        "why": "C6H12O6 gives 2C2H5OH and 2CO2.",
    },
    {
        "id": "ks4-alcohols-s24",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Give one advantage of the fermentation route to ethanol over the route that starts from crude oil.",
        "options": [
            "The raw material is a crop, which can be grown again each year",
            "The reaction is finished within a few minutes of the yeast being added to the sugar",
            "The ethanol produced needs no purification of any sort before it can be sold",
            "It works at high pressure",
        ],
        "correct_index": 0,
        "why": "Sugar crops are renewable, while the ethene route depends on a finite resource.",
    },
    {
        "id": "ks4-alcohols-s25",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why methanol, ethanol and propanol take part in the same kinds of reaction.",
        "options": [
            "Because each of them contains exactly the same number of carbon atoms per molecule",
            "Because all three of them are made by the same industrial process from one feedstock",
            "Because they all share the -OH functional group",
            "Because they have the same boiling point",
        ],
        "correct_index": 2,
        "why": "The functional group decides the chemistry, and all alcohols carry the hydroxyl group.",
    },
    {
        "id": "ks4-alcohols-s26",
        "subtopic_slug": "alcohols",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Predict what happens to the amount of sugar in a fermentation vessel as the days pass.",
        "options": [
            "It rises, because the yeast makes more sugar as it grows in the warm mixture",
            "It falls, because the yeast converts it into ethanol and carbon dioxide",
            "It stays the same, because the yeast uses only the water in the mixture",
            "It falls and then rises again once the yeast has died in the vessel",
        ],
        "correct_index": 1,
        "why": "Sugar is the reactant, so its amount drops as the products build up.",
    },
    # ---------------------------------------------------------------- harder
    {
        "id": "ks4-alcohols-h05",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Deduce the formula of the alcohol whose molecules hold five carbon atoms.",
        "options": [
            "C5H12OH",
            "C5H11OH",
            "C5H10OH",
            "C4H9OH",
        ],
        "correct_index": 1,
        "why": "CnH2n+1OH with n = 5 gives the alkyl group C5H11.",
    },
    {
        "id": "ks4-alcohols-h06",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A vat holds 180 g of glucose (Mr 180) and all of it ferments. Work out the mass of ethanol (Mr 46) produced.",
        "options": [
            "46 g",
            "92 g",
            "180 g",
            "134 g",
        ],
        "correct_index": 1,
        "why": "One mole of glucose gives two moles of ethanol, so 2 x 46 = 92 g.",
    },
    {
        "id": "ks4-alcohols-h07",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why fermentation is run in batches while the industrial route from ethene runs without stopping.",
        "options": [
            "Because the yeast used in fermentation would block the pipes of a continuous plant",
            "Because fermentation is finished in seconds and a continuous plant would be wasted on it",
            "Because fermentation needs a vessel of sugar and yeast left to work and then emptied",
            "Because fermentation needs no vessel",
        ],
        "correct_index": 2,
        "why": "Each batch is fermented, drained and started again; the hydration plant is fed continuously.",
    },
    {
        "id": "ks4-alcohols-h08",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Evaluate the claim that ethanol made from sugar cane is a carbon-neutral fuel.",
        "options": [
            "Fully justified, because the crop takes in exactly as much carbon dioxide as burning it releases",
            "Fully justified, because ethanol contains no carbon",
            "Not justified at all, because burning ethanol releases no carbon dioxide whatsoever",
            "Not fully justified, because fuel is burned to farm, transport and distil the ethanol",
        ],
        "correct_index": 3,
        "why": "The growing crop absorbs carbon dioxide, but the farming and distilling stages add more.",
    },
    {
        "id": "ks4-alcohols-h09",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Determine the balanced equation for the complete combustion of propanol, C3H7OH.",
        "options": [
            "C3H7OH + 4O2 goes to 3CO2 + 4H2O",
            "2C3H7OH + 9O2 goes to 6CO2 + 8H2O",
            "2C3H7OH + 7O2 goes to 6CO2 + 8H2O",
            "C3H7OH + 5O2 goes to 3CO2 + 3H2O",
        ],
        "correct_index": 1,
        "why": "Two molecules give 6CO2 and 8H2O, needing twenty oxygen atoms; two come from the alcohol, so 9O2 supply the rest.",
    },
    {
        "id": "ks4-alcohols-h10",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A fermented mixture is distilled and the first liquid to come over is collected. Explain why it is richer in ethanol than the vessel was.",
        "options": [
            "Because ethanol does not boil",
            "Because the water in the mixture is turned into ethanol as the mixture is heated",
            "Because ethanol is denser than water and settles at the bottom before it is heated",
            "Because ethanol boils at 78 degrees Celsius, well below the boiling point of water",
        ],
        "correct_index": 3,
        "why": "The more volatile component vaporises first, so the early distillate is concentrated in ethanol.",
    },
    {
        "id": "ks4-alcohols-h11",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Deduce the total number of hydrogen atoms in a molecule of the alcohol with eight carbon atoms.",
        "options": [
            "16",
            "18",
            "17",
            "19",
        ],
        "correct_index": 1,
        "why": "C8H17OH holds seventeen hydrogens on the chain and one more in the hydroxyl group.",
    },
    {
        "id": "ks4-alcohols-h12",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why methanol and butanol both give off the same gas when sodium is added to them.",
        "options": [
            "Because both of them contain the same number of carbon atoms in their chains",
            "Because both of them carry the -OH group, which is where the reaction happens",
            "Because sodium releases that gas from any liquid it is dropped into",
            "Because both are liquids at room temperature and sodium reacts only with liquids",
        ],
        "correct_index": 1,
        "why": "The sodium reacts with the hydrogen of the hydroxyl group, whatever the chain length.",
    },
    {
        "id": "ks4-alcohols-h13",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Predict the gas given off when sodium is dropped into propanol, and justify your prediction.",
        "options": [
            "Hydrogen, because propanol carries an -OH group just as ethanol does",
            "Oxygen, because the -OH group in the propanol molecule contains an oxygen atom",
            "Carbon dioxide, because the carbon chain of the alcohol is broken up by the sodium",
            "No gas is produced",
        ],
        "correct_index": 0,
        "why": "Every alcohol reacts with sodium in the same way, releasing hydrogen from the hydroxyl group.",
    },
    {
        "id": "ks4-alcohols-h14",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Evaluate this claim: 'Fermentation is the better industrial route to ethanol in every case.'",
        "options": [
            "Correct, because fermentation uses a renewable crop and nothing else matters",
            "Too strong — it uses a renewable crop, but it is slow, works in batches and gives a dilute product",
            "Incorrect, because fermentation cannot produce ethanol without a crude oil feedstock",
            "Correct, because fermentation produces pure ethanol straight from the vessel",
        ],
        "correct_index": 1,
        "why": "Each route wins on different grounds, so a claim that one is always better cannot stand.",
    },
    {
        "id": "ks4-alcohols-h15",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "In ethanol, C2H5OH, the oxygen accounts for 16 of the 46 mass units. Give that as a percentage.",
        "options": [
            "34.8%",
            "16.0%",
            "26.1%",
            "52.2%",
        ],
        "correct_index": 0,
        "why": "16 divided by 46, multiplied by 100, gives 34.8%.",
    },
    {
        "id": "ks4-alcohols-h16",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "An alcohol solution is neutral even though its molecules contain an -OH group. Explain why.",
        "options": [
            "Because the water in the solution cancels out the alkali that the alcohol produces",
            "Because the -OH group stays attached to the molecule instead of forming ions in water",
            "Because the -OH group is neutralised by the carbon chain on the other side of it",
            "Because alcohols do not dissolve",
        ],
        "correct_index": 1,
        "why": "Neither hydrogen ions nor hydroxide ions are released, so the solution stays at about pH 7.",
    },
    {
        "id": "ks4-alcohols-h17",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why ethanol burns with a clean flame while a petrol fire is often smoky.",
        "options": [
            "Because petrol contains sulfur",
            "Because ethanol holds no carbon atoms and so cannot produce any soot as it burns",
            "Because ethanol burns at a far lower temperature than any hydrocarbon fuel can do",
            "Because ethanol already holds an oxygen atom, so its carbon is oxidised more fully",
        ],
        "correct_index": 3,
        "why": "The oxygen built into the molecule helps combustion go to completion, so little carbon is left unburned.",
    },
    {
        "id": "ks4-alcohols-h18",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Identify which of these formulae belongs to an alcohol: C3H8, C3H6, C3H7OH or C2H4Br2.",
        "options": [
            "C3H7OH",
            "C3H6",
            "C3H8",
            "C2H4Br2",
        ],
        "correct_index": 0,
        "why": "Only C3H7OH carries the hydroxyl group that defines an alcohol.",
    },
    {
        "id": "ks4-alcohols-h19",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why chemists write ethanol as C2H5OH rather than as C2H6O.",
        "options": [
            "Because C2H6O counts the atoms wrongly and gives one hydrogen atom too many",
            "Because the two formulae describe molecules of two different relative formula masses",
            "Because C2H6O is the formula of a completely different compound from ethanol",
            "Because writing the -OH separately shows the functional group",
        ],
        "correct_index": 3,
        "why": "Both count the same atoms, but C2H5OH makes the hydroxyl group visible.",
    },
    {
        "id": "ks4-alcohols-h20",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "One mole of ethanol is burned completely. Calculate the amount of carbon dioxide produced, in moles.",
        "options": [
            "1 mol",
            "6 mol",
            "3 mol",
            "2 mol",
        ],
        "correct_index": 3,
        "why": "Ethanol holds two carbon atoms, and each becomes one molecule of carbon dioxide.",
    },
    {
        "id": "ks4-alcohols-h21",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Compare the products formed when ethanol burns completely with those formed when ethane burns completely.",
        "options": [
            "Ethanol gives carbon dioxide and water; ethane gives carbon monoxide and hydrogen",
            "Ethane gives carbon dioxide and water; ethanol gives an acid and water instead",
            "Ethanol gives water only, because the oxygen in it keeps any carbon from burning",
            "Both give carbon dioxide and water",
        ],
        "correct_index": 3,
        "why": "Both molecules hold only carbon, hydrogen and (for ethanol) oxygen, so the products match.",
    },
    {
        "id": "ks4-alcohols-h22",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Spirits such as whisky are about 40% ethanol. Explain the extra step needed after fermentation to reach that strength.",
        "options": [
            "More sugar is stirred in so that the yeast can carry on working for several more weeks",
            "The mixture is left standing until the water at the bottom evaporates away by itself",
            "The liquid is distilled, which concentrates the ethanol",
            "A second, stronger yeast is added",
        ],
        "correct_index": 2,
        "why": "Fermentation stops well below 40%, so the dilute product must be distilled.",
    },
    {
        "id": "ks4-alcohols-h23",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Predict which of methanol and butanol evaporates more readily at room temperature, and explain.",
        "options": [
            "Butanol, because its longer chain lets it escape from the surface of the liquid faster",
            "Neither, because two alcohols always evaporate at exactly the same rate as each other",
            "Methanol, because its smaller molecules attract one another less strongly",
            "Butanol, because it holds more hydrogen",
        ],
        "correct_index": 2,
        "why": "Weaker forces between smaller molecules mean a lower boiling point and faster evaporation.",
    },
    {
        "id": "ks4-alcohols-h24",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Deduce which alcohol has molecules weighing 60 units, given C = 12, H = 1 and O = 16.",
        "options": [
            "CH3OH",
            "C3H7OH",
            "C2H5OH",
            "C4H9OH",
        ],
        "correct_index": 1,
        "why": "(3 x 12) + (8 x 1) + 16 = 60, which is propanol.",
    },
    {
        "id": "ks4-alcohols-h25",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why hand gels are made with ethanol rather than with water.",
        "options": [
            "Because ethanol kills microorganisms and dries quickly from the skin",
            "Because ethanol is thicker than water and therefore stays on the hands far longer",
            "Because ethanol is cheaper to buy in bulk than clean water is in most countries",
            "Because water would react with the skin",
        ],
        "correct_index": 0,
        "why": "Ethanol destroys bacteria and viruses on contact and evaporates without needing a towel.",
    },
    {
        "id": "ks4-alcohols-h26",
        "subtopic_slug": "alcohols",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A pupil labels a bottle of ethanol with the formula C2H6. Identify the error and give the correct formula.",
        "options": [
            "C2H6 is correct, because the oxygen atom in ethanol is not written into its formula",
            "C2H6 is ethene; ethanol is C2H4OH, because an alcohol holds one oxygen atom",
            "C2H6 is ethane; ethanol is C2H5OH",
            "C2H6 is methanol; ethanol is CH3OH",
        ],
        "correct_index": 2,
        "why": "C2H6 has no oxygen at all, so it names the alkane rather than the alcohol.",
    },
]
