"""Chemistry · Organic Chemistry — the MRB-338 expansion, subtopic
`addition-polymerisation`.

The baseline twelve cover the monomer requirement (a C=C double bond),
naming poly(propene)/PVC, the "one product only" feature, repeat units
both forwards and backwards, the bromine-water anomaly for poly(ethene),
landfill/incineration environmental cost, an Mr-of-the-chain calculation,
atom economy versus a competing route, and the solid-versus-gas physical
change on polymerising. This file goes wider: more named monomers
(styrene, PTFE, vinyl acetate), HDPE vs LDPE and chain packing, plastics'
properties linked to structure, recycling logistics, further Mr/mole
calculations, and depth on why addition polymers resist biodegradation.
"""

TOPIC = "organic"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": "ks4-addition-polymerisation-e05",
        "subtopic_slug": "addition-polymerisation",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the polymer made from the monomer styrene.",
        "options": [
            "Poly(styrene)",
            "Poly(ethene), the wrong monomer",
            "Poly(propene), a different plastic",
            "PVC, made from chloroethene",
        ],
        "correct_index": 0,
        "why": "Addition polymers are named poly(monomer), so styrene gives poly(styrene).",
    },
    {
        "id": "ks4-addition-polymerisation-e06",
        "subtopic_slug": "addition-polymerisation",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the monomer used to make PTFE, the non-stick coating on frying pans.",
        "options": [
            "Ethene, the simplest alkene",
            "Tetrafluoroethene",
            "Propene, with a methyl branch",
            "Chloroethene, the PVC monomer",
        ],
        "correct_index": 1,
        "why": "PTFE is poly(tetrafluoroethene): every hydrogen on the ethene skeleton is replaced by fluorine.",
    },
    {
        "id": "ks4-addition-polymerisation-e07",
        "subtopic_slug": "addition-polymerisation",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what happens to the carbon–carbon double bonds of the monomers during addition polymerisation.",
        "options": [
            "They break down into a separate gas",
            "They stay as double bonds in the chain",
            "They open up to form new single bonds",
            "They turn into triple bonds instead",
        ],
        "correct_index": 2,
        "why": "Each double bond opens so the carbon can bond to the next monomer, building a long saturated chain.",
    },
    {
        "id": "ks4-addition-polymerisation-e08",
        "subtopic_slug": "addition-polymerisation",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State one method commonly used to dispose of waste plastic that does not involve recycling it.",
        "options": [
            "Fractional distillation",
            "Neutralisation with an alkali",
            "Electrolysis of the plastic",
            "Landfill burial of the waste",
        ],
        "correct_index": 3,
        "why": "Burying waste plastic in landfill is a common, low-cost, but land-consuming disposal method.",
    },
    {
        "id": "ks4-addition-polymerisation-e09",
        "subtopic_slug": "addition-polymerisation",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State one reason plastic bags are usually made from poly(ethene) rather than a metal.",
        "options": [
            "It is flexible and lightweight",
            "It conducts electricity well",
            "It melts far above steel's melting point",
            "It is denser than most metals",
        ],
        "correct_index": 0,
        "why": "The tangled but flexible chains of poly(ethene) let it bend into a thin, light bag.",
    },
    {
        "id": "ks4-addition-polymerisation-e10",
        "subtopic_slug": "addition-polymerisation",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what must be sorted before mixed plastic waste can be effectively recycled.",
        "options": [
            "The colour of the lorry used",
            "The polymer type",
            "The outside temperature that day",
            "The day of the week collected",
        ],
        "correct_index": 1,
        "why": "Different polymers melt and reprocess differently, so mixed types must be separated first.",
    },
    {
        "id": "ks4-addition-polymerisation-e11",
        "subtopic_slug": "addition-polymerisation",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State whether an addition polymer such as poly(ethene) conducts electricity.",
        "options": [
            "Only once fully melted down",
            "Only once dissolved in water",
            "No, it acts as an insulator",
            "Yes, as well as most metals",
        ],
        "correct_index": 2,
        "why": "Poly(ethene) has no free ions or delocalised electrons, so it insulates rather than conducts.",
    },
    {
        "id": "ks4-addition-polymerisation-e12",
        "subtopic_slug": "addition-polymerisation",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State the raw material from which most monomers used in addition polymerisation are obtained.",
        "options": [
            "Sea water, once evaporated",
            "Iron ore, mined underground",
            "Limestone, quarried from rock",
            "Crude oil",
        ],
        "correct_index": 3,
        "why": "Alkenes such as ethene and propene are cracked from fractions of crude oil.",
    },
    {
        "id": "ks4-addition-polymerisation-s05",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Vinyl acetate, CH2=CHOCOCH3, is polymerised to make PVA glue. Give the repeat unit's structure in words.",
        "options": [
            "A two-carbon chain, one carbon carrying a group",
            "A two-carbon chain with two groups on one carbon",
            "A three-carbon chain with a group in the middle",
            "A four-carbon chain with a group on every carbon",
        ],
        "correct_index": 0,
        "why": "The double bond opens across the two backbone carbons, and the side group stays attached to one of them.",
    },
    {
        "id": "ks4-addition-polymerisation-s06",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why low-density poly(ethene) (LDPE) is more flexible than high-density poly(ethene) (HDPE).",
        "options": [
            "LDPE has shorter chains than HDPE overall",
            "LDPE has branched chains that pack loosely",
            "LDPE has ionic bonds joining its chains",
            "LDPE has far fewer carbon atoms per chain",
        ],
        "correct_index": 1,
        "why": "Branching in LDPE stops the chains lining up as closely, giving weaker forces between them and more flexibility.",
    },
    {
        "id": "ks4-addition-polymerisation-s07",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why HDPE is used for rigid items such as plastic bottles and buckets while LDPE is used for thin films.",
        "options": [
            "HDPE has no carbon–carbon bonds present",
            "HDPE melts at a far lower temperature",
            "HDPE's straight chains pack more closely",
            "HDPE's monomer carries no hydrogen atoms",
        ],
        "correct_index": 2,
        "why": "Straighter chains in HDPE pack more closely, increasing intermolecular forces and giving a stiffer, stronger material.",
    },
    {
        "id": "ks4-addition-polymerisation-s08",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain, in terms of intermolecular forces, why longer polymer chains generally make a plastic stronger.",
        "options": [
            "Longer chains contain stronger backbone bonds",
            "Longer chains are simply heavier overall",
            "Longer chains always carry more double bonds",
            "Longer chains give more area for forces to act along",
        ],
        "correct_index": 3,
        "why": "More contact between longer chains means more intermolecular forces adding up, which takes more energy to overcome.",
    },
    {
        "id": "ks4-addition-polymerisation-s09",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Give one economic advantage of recycling addition polymers rather than making new ones from crude oil.",
        "options": [
            "It reduces demand on a finite resource",
            "It gives higher quality than new plastic",
            "It needs no electricity to carry out",
            "It ends the need to buy any monomer",
        ],
        "correct_index": 0,
        "why": "Reusing existing plastic conserves crude oil, which is a finite resource that is becoming more costly to extract.",
    },
    {
        "id": "ks4-addition-polymerisation-s10",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Give one limitation of recycling mixed plastic waste, even once it has been sorted by type.",
        "options": [
            "Sorted plastic reverts to monomer by itself",
            "Melting repeatedly shortens the chains",
            "Sorted plastic can never be melted again",
            "It produces more crude oil than it uses",
        ],
        "correct_index": 1,
        "why": "Heating and reprocessing can break some chains, so recycled plastic is often used for a lower-grade product.",
    },
    {
        "id": "ks4-addition-polymerisation-s11",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A repeat unit is drawn as (–CHCl–CH2–)n. Identify the monomer it was made from.",
        "options": [
            "Ethene, CH2=CH2",
            "1,2-dichloroethene, CHCl=CHCl",
            "Chloroethene, CH2=CHCl",
            "Propene, CH2=CHCH3",
        ],
        "correct_index": 2,
        "why": "Splitting the repeat unit back into a two-carbon unit with one chlorine reproduces the chloroethene monomer.",
    },
    {
        "id": "ks4-addition-polymerisation-s12",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why an addition polymer's repeat unit always has exactly the same atoms as its monomer.",
        "options": [
            "The repeat unit gains hydrogen atoms as it forms",
            "The monomer loses one chlorine as it joins",
            "Half of the atoms are lost as a molecule",
            "No atoms are lost; the double bond just opens",
        ],
        "correct_index": 3,
        "why": "Addition polymerisation has only one product, so every atom in the monomer ends up in the polymer.",
    },
    {
        "id": "ks4-addition-polymerisation-s13",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Predict what would be seen if bromine water were shaken with the liquid monomer propene, before it is polymerised.",
        "options": [
            "The bromine water decolourises",
            "A white precipitate forms at once",
            "The mixture turns bright blue",
            "No visible change takes place",
        ],
        "correct_index": 0,
        "why": "Propene is unsaturated, so it decolourises bromine water in an addition reaction, unlike the saturated polymer.",
    },
    {
        "id": "ks4-addition-polymerisation-s14",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "State why poly(ethene) does not react with bromine water even though ethene does.",
        "options": [
            "It contains chlorine that blocks reaction",
            "It has no double bonds once polymerised",
            "It reacts with air's oxygen first instead",
            "It is far too dense to react with it",
        ],
        "correct_index": 1,
        "why": "The double bonds are used up joining the monomers, leaving a fully saturated chain with nothing left for bromine to add across.",
    },
    {
        "id": "ks4-addition-polymerisation-s15",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "500 molecules of propene, Mr 42, polymerise completely into a single chain of poly(propene). Calculate the relative formula mass of the chain.",
        "options": [
            "42,000",
            "500",
            "21,000",
            "10,500",
        ],
        "correct_index": 2,
        "why": "500 x 42 = 21,000, since every monomer's mass is carried unchanged into the chain.",
    },
    {
        "id": "ks4-addition-polymerisation-s16",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A poly(ethene) chain has a relative formula mass of 56,000. Ethene has Mr 28. Calculate how many ethene monomers it contains.",
        "options": [
            "56",
            "28,000",
            "1,568,000",
            "2,000",
        ],
        "correct_index": 3,
        "why": "56,000 ÷ 28 = 2,000 monomer units, since the chain's mass is the sum of every monomer's mass.",
    },
    {
        "id": "ks4-addition-polymerisation-s17",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest one reason a supermarket might switch from single-use poly(ethene) bags to paper bags instead.",
        "options": [
            "Paper breaks down naturally over time",
            "Paper is cheaper to manufacture",
            "Paper conducts electricity well",
            "Paper is stronger at equal thickness",
        ],
        "correct_index": 0,
        "why": "Paper is made of natural polymers that microorganisms can break down, unlike most addition polymers.",
    },
    {
        "id": "ks4-addition-polymerisation-s18",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Give one reason a manufacturer might still choose an addition polymer over paper for packaging, despite the environmental cost.",
        "options": [
            "It cannot be printed with any label",
            "It resists water better than paper does",
            "It biodegrades faster than paper does",
            "It costs less to make than paper always",
        ],
        "correct_index": 1,
        "why": "Many addition polymers resist water and physical damage far better than paper, which matters for some products.",
    },
    {
        "id": "ks4-addition-polymerisation-s19",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why melting and remoulding an addition polymer, rather than a thermosetting polymer, allows it to be recycled by reshaping.",
        "options": [
            "It loses its carbon atoms once heated",
            "It has cross-links that break on heating",
            "Heat weakens the forces between its chains",
            "It is a liquid at room temperature already",
        ],
        "correct_index": 2,
        "why": "Without permanent cross-links, heating overcomes the forces between separate chains, letting the plastic be reshaped and reused.",
    },
    {
        "id": "ks4-addition-polymerisation-s20",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A repeat unit is drawn as (–CH2–CHC6H5–)n. Identify the monomer used to make this polymer.",
        "options": [
            "Ethene, CH2=CH2",
            "Propene, CH2=CHCH3",
            "Chloroethene, CH2=CHCl",
            "Styrene, CH2=CHC6H5",
        ],
        "correct_index": 3,
        "why": "Reversing the addition reaction on the repeat unit reproduces the styrene monomer with its benzene ring side group.",
    },
    {
        "id": "ks4-addition-polymerisation-s21",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "State why expanded polystyrene, used in packaging and disposable cups, feels much lighter than solid poly(styrene).",
        "options": [
            "It traps tiny pockets of air inside it",
            "It has lost most of its hydrogen atoms",
            "It is made from a lighter monomer",
            "It has no carbon atoms in its chain",
        ],
        "correct_index": 0,
        "why": "Expanding the polystyrene traps air bubbles inside it, dramatically lowering its overall density.",
    },
    {
        "id": "ks4-addition-polymerisation-s22",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "State one problem caused by plastic waste that ends up in the ocean rather than being disposed of properly.",
        "options": [
            "It dissolves without leaving any trace",
            "It fragments into microplastics animals eat",
            "It turns back into crude oil at the seabed",
            "It reacts with seawater to form a salt",
        ],
        "correct_index": 1,
        "why": "Ocean plastic slowly fragments into microplastics, which persist and can be swallowed by marine life.",
    },
    {
        "id": "ks4-addition-polymerisation-s23",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a car tyre, which contains a polymer, is much stiffer than a poly(ethene) carrier bag.",
        "options": [
            "The tyre's polymer has no carbon bonds",
            "The tyre's polymer is a gas before shaping",
            "The tyre's polymer is cross-linked by sulfur",
            "The tyre's polymer has a far lower Mr",
        ],
        "correct_index": 2,
        "why": "Vulcanisation adds sulfur cross-links between rubber chains, making the material far stiffer and less flexible.",
    },
    {
        "id": "ks4-addition-polymerisation-s24",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A scientist compares two samples of poly(ethene) with identical average chain length. State what else could still make one sample stronger than the other.",
        "options": [
            "The shape of the storage container used",
            "The day of the week it was made",
            "The colour dye added to the sample",
            "The amount of branching in the chains",
        ],
        "correct_index": 3,
        "why": "Even at the same chain length, more branching reduces packing and weakens the intermolecular forces between chains.",
    },
    {
        "id": "ks4-addition-polymerisation-s25",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Give one reason why sorting plastic waste by hand or by machine, before recycling, adds to its overall cost.",
        "options": [
            "It needs labour or specialist machinery",
            "It requires dissolving plastic in acid",
            "It leaves the sorted plastic heavier",
            "It always destroys the polymer's structure",
        ],
        "correct_index": 0,
        "why": "Telling different polymers apart reliably needs either trained workers or automated sensors, both of which cost money.",
    },
    {
        "id": "ks4-addition-polymerisation-s26",
        "subtopic_slug": "addition-polymerisation",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why using a plant-based alternative to crude oil for making the SAME addition-polymer monomers would not change the final plastic's biodegradability.",
        "options": [
            "Plant-based monomers cannot polymerise",
            "The polymer's structure, not its source, decides this",
            "Plant-based monomers give a different repeat unit",
            "Plant-based monomers form weaker double bonds",
        ],
        "correct_index": 1,
        "why": "If the resulting polymer chain is chemically identical, its resistance to microbial breakdown is unchanged regardless of the monomer's origin.",
    },
    {
        "id": "ks4-addition-polymerisation-h05",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Evaluate switching a factory's poly(ethene) production from a crude-oil feedstock to a bio-based ethene feedstock, in terms of the polymer's final properties.",
        "options": [
            "Its repeat unit changes completely as a result",
            "It becomes impossible to recycle afterward",
            "Identical ethene gives an identical polymer",
            "It becomes biodegradable unlike the oil version",
        ],
        "correct_index": 2,
        "why": "Ethene is ethene regardless of source, so the addition polymer produced has identical structure and properties either way.",
    },
    {
        "id": "ks4-addition-polymerisation-h06",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A 100% pure sample of poly(propene) is made from propene with 100% atom economy. Explain what this tells you about the mass relationship between reactant and product.",
        "options": [
            "The mass ratio depends on the temperature",
            "This tells you nothing about the mass ratio",
            "Only half the monomer's mass is retained",
            "Monomer mass used equals polymer mass made",
        ],
        "correct_index": 3,
        "why": "100% atom economy means every atom of reactant becomes part of the one product, so mass is conserved exactly.",
    },
    {
        "id": "ks4-addition-polymerisation-h07",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Compare pyrolysis (heating plastic waste without oxygen to break it into smaller hydrocarbons) with simply incinerating it, as ways to deal with waste addition polymers.",
        "options": [
            "Pyrolysis recovers feedstock, burning gives heat",
            "Both give identical products in this case",
            "Incineration recovers monomers, pyrolysis heat",
            "Neither releases any gas to the atmosphere",
        ],
        "correct_index": 0,
        "why": "Pyrolysis breaks chains into smaller hydrocarbon molecules that can be reused chemically, whereas incineration simply burns the material for energy.",
    },
    {
        "id": "ks4-addition-polymerisation-h08",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A student argues that because addition polymers are unreactive, they must be completely safe to leave in the environment indefinitely. Evaluate this claim.",
        "options": [
            "It is correct; unreactive things cause no harm",
            "It ignores harm from physical fragmentation",
            "It is wrong since the polymer is reactive",
            "It is wrong since the polymer dissolves fast",
        ],
        "correct_index": 1,
        "why": "Chemical stability does not prevent physical breakdown into microplastics, which can still be ingested by wildlife and persist for centuries.",
    },
    {
        "id": "ks4-addition-polymerisation-h09",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A company blends two addition polymers, HDPE and LDPE, in a 1:1 ratio by mass to make a new material. Predict how its flexibility compares with pure HDPE.",
        "options": [
            "Its flexibility depends only on colour",
            "It is exactly as rigid as pure HDPE",
            "It is likely more flexible than HDPE",
            "It cannot flex while containing HDPE",
        ],
        "correct_index": 2,
        "why": "Introducing branched LDPE chains disrupts the close packing HDPE relies on for rigidity, generally increasing flexibility.",
    },
    {
        "id": "ks4-addition-polymerisation-h10",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "1.4 kg of propene, Mr 42, is polymerised completely and with 100% yield. Calculate the mass of poly(propene) produced.",
        "options": [
            "2.8 kg",
            "0.7 kg",
            "42 kg",
            "1.4 kg",
        ],
        "correct_index": 3,
        "why": "With 100% atom economy and 100% yield, the mass of product equals the mass of monomer used: 1.4 kg.",
    },
    {
        "id": "ks4-addition-polymerisation-h11",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A polymer chain of poly(chloroethene), Mr 62.5 per repeat unit, has a total relative formula mass of 625,000. Calculate the number of monomer units it contains.",
        "options": [
            "10,000",
            "1,000",
            "62,500",
            "100,000",
        ],
        "correct_index": 0,
        "why": "625,000 ÷ 62.5 = 10,000 repeat units, each contributing the same mass as one chloroethene monomer.",
    },
    {
        "id": "ks4-addition-polymerisation-h12",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why chemists describe addition polymerisation as having a 'theoretical' atom economy of 100%, but a real reaction's overall yield is usually lower.",
        "options": [
            "Atom economy overstates monomer mass used",
            "Not every monomer reacts, and some is lost",
            "Yield and atom economy are the same thing",
            "The real product differs from the theory",
        ],
        "correct_index": 1,
        "why": "Atom economy is a theoretical mass ratio for a complete reaction; actual yield also depends on how much monomer reacts and how much product is recovered.",
    },
    {
        "id": "ks4-addition-polymerisation-h13",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why manufacturers sometimes add a UV stabiliser to addition polymers used outdoors, such as in guttering.",
        "options": [
            "To lower the polymer's melting point",
            "To make it a condensation polymer instead",
            "To slow UV damage to the chains outdoors",
            "To make the polymer conduct electricity",
        ],
        "correct_index": 2,
        "why": "UV light can gradually break bonds in exposed polymer chains, so a stabiliser is added to extend the product's outdoor lifespan.",
    },
    {
        "id": "ks4-addition-polymerisation-h14",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A life-cycle assessment compares a poly(ethene) bag used once with a cotton bag reused 100 times. Explain why the comparison must consider more than just the raw material each is made from.",
        "options": [
            "Cotton cannot have a larger impact ever",
            "It only ever considers the disposal stage",
            "Raw material is the only factor that matters",
            "Manufacture, transport and use all add impact",
        ],
        "correct_index": 3,
        "why": "A full life-cycle assessment tracks extraction, manufacture, use and disposal, since impact at any of these stages can dominate the total.",
    },
    {
        "id": "ks4-addition-polymerisation-h15",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain, at the molecular level, why increasing the average chain length of an addition polymer tends to increase its melting point.",
        "options": [
            "Longer chains give more area for chain forces",
            "Longer chains always hold more double bonds",
            "Longer chains carry a lower relative mass",
            "Longer chains have stronger backbone bonds",
        ],
        "correct_index": 0,
        "why": "More chain length means more points of contact for van der Waals forces between neighbouring chains, raising the energy needed to melt the material.",
    },
    {
        "id": "ks4-addition-polymerisation-h16",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A researcher develops a new catalyst that produces poly(ethene) with much less chain branching than the standard process. Predict the effect on the polymer's density.",
        "options": [
            "Density falls to zero as a result",
            "Density likely rises as chains pack closer",
            "It will only change with the dye used",
            "It cannot change unless the monomer does",
        ],
        "correct_index": 1,
        "why": "Less branching allows chains to pack more closely, increasing intermolecular forces and typically increasing density, as seen going from LDPE to HDPE.",
    },
    {
        "id": "ks4-addition-polymerisation-h17",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why 'chemical recycling' (breaking a polymer back down into its monomers) can, in principle, avoid the downcycling problem seen in simple melt-and-reshape recycling.",
        "options": [
            "Chemical recycling always makes a new element",
            "It cannot apply to any addition polymer",
            "Fresh monomer replaces old, damaged chains",
            "Melting and reshaping gives a stronger material",
        ],
        "correct_index": 2,
        "why": "Going back to the monomer removes any chain damage from previous use, so the new polymer made from it need not be lower quality.",
    },
    {
        "id": "ks4-addition-polymerisation-h18",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A student proposes testing an unlabelled plastic sample with bromine water to check whether it is an addition polymer. Evaluate this test.",
        "options": [
            "It works on any carbon-based material",
            "It works, since every polymer decolourises it",
            "It works only if dissolved in water first",
            "It fails since a polymer is saturated",
        ],
        "correct_index": 3,
        "why": "Once polymerised, the double bonds are used up, so the finished addition polymer behaves as a saturated compound and gives no reaction with bromine water.",
    },
    {
        "id": "ks4-addition-polymerisation-h19",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Two samples of poly(ethene) have identical chain length and identical branching, but sample A was cooled slowly while sample B was cooled rapidly during manufacture. Suggest why sample A might be denser.",
        "options": [
            "Slow cooling lets chains pack more neatly",
            "Cooling speed cannot affect chain packing",
            "Slow cooling removes carbon from the chains",
            "It changes the polymer type completely",
        ],
        "correct_index": 0,
        "why": "Slower cooling allows chains more time to settle into ordered, tightly packed arrangements, which raises density.",
    },
    {
        "id": "ks4-addition-polymerisation-h20",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a fully halogenated addition polymer such as PTFE resists chemical attack far better than poly(ethene).",
        "options": [
            "It has no carbon in its backbone",
            "Strong C–F bonds shield the backbone",
            "It is one molecule, not a real polymer",
            "It reacts with every acid and alkali",
        ],
        "correct_index": 1,
        "why": "Carbon–fluorine bonds are very strong and the fluorine atoms shield the backbone, making PTFE exceptionally chemically resistant.",
    },
    {
        "id": "ks4-addition-polymerisation-h21",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A government bans single-use poly(ethene) bags and requires biodegradable alternatives. Evaluate whether an alternative addition polymer, engineered with weaker points along its backbone to fragment faster, fully solves the original environmental problem.",
        "options": [
            "Fragmenting counts as full biodegradation",
            "It cannot reduce environmental harm at all",
            "Fragments may still persist as microplastics",
            "It removes any need for waste disposal",
        ],
        "correct_index": 2,
        "why": "Fragmenting faster is not the same as true biodegradation; unless microorganisms can fully break the fragments down, microplastic pollution can persist.",
    },
    {
        "id": "ks4-addition-polymerisation-h22",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "0.5 mol of ethene, Mr 28, is polymerised completely into poly(ethene) chains averaging 5,000 monomer units each. Calculate the number of polymer chains formed.",
        "options": [
            "5,000",
            "0.5",
            "5 x 10^23",
            "1 x 10^20",
        ],
        "correct_index": 3,
        "why": "0.5 mol contains 0.5 x 6.02x10^23 ≈ 3.01x10^23 monomers; dividing by 5,000 monomers per chain gives about 6x10^19, closest to 1x10^20.",
    },
    {
        "id": "ks4-addition-polymerisation-h23",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why a manufacturer switching from making single-use cutlery in poly(styrene) to a compostable plant-based polymer would still need to check the new material's mechanical strength.",
        "options": [
            "Strength and biodegradability are unrelated",
            "It cannot be shaped into cutlery at all",
            "Strength only matters for addition polymers",
            "Any compostable polymer beats poly(styrene)",
        ],
        "correct_index": 0,
        "why": "Being compostable says nothing about strength or rigidity, which depend on chain structure and must be tested separately for the intended use.",
    },
    {
        "id": "ks4-addition-polymerisation-h24",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a mixture of different addition polymers, melted together without sorting, usually produces a weaker material than either pure polymer alone.",
        "options": [
            "It creates new covalent bonds between them",
            "Unlike chains pack together less regularly",
            "Mixing polymers always doubles the strength",
            "It removes carbon atoms from the mixture",
        ],
        "correct_index": 1,
        "why": "Different polymer chains are less compatible and pack together poorly, reducing the intermolecular forces that give the material strength.",
    },
    {
        "id": "ks4-addition-polymerisation-h25",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A student claims that because addition polymers are made from crude oil, banning crude oil extraction would immediately end all plastic pollution. Evaluate this claim.",
        "options": [
            "Pollution comes only from ongoing extraction",
            "Oil cannot actually be used to make plastic",
            "It ignores plastic already in the environment",
            "Existing plastic would vanish at once",
        ],
        "correct_index": 2,
        "why": "Stopping extraction would not remove the enormous stock of plastic already produced and discarded, which persists in the environment for a long time.",
    },
    {
        "id": "ks4-addition-polymerisation-h26",
        "subtopic_slug": "addition-polymerisation",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why increasing the pressure and temperature used to manufacture poly(ethene) can shift production from LDPE towards HDPE-like straighter chains.",
        "options": [
            "Conditions have no effect on branching",
            "Temperature changes the polymer's identity",
            "Pressure adds carbon to the monomer",
            "Conditions control how much branching forms",
        ],
        "correct_index": 3,
        "why": "The specific catalyst and conditions used control how much branching occurs during polymerisation, which is what distinguishes LDPE from HDPE.",
    },
]
