"""Chemistry · Organic Chemistry — the MRB-338 expansion, subtopic
`amino-acids`.

The baseline twelve cover the two functional groups every amino acid
carries, the R-group as the point of difference, glycine as the
simplest amino acid, proteins as polymers of amino acids, amphoteric
behaviour, peptide bonds and dipeptide/tripeptide naming, condensation
water loss, hydrolysis breaking proteins back down, an Mr calculation
on a dipeptide, mutation changing a protein's function, hydrolysis
products, and biodegradability compared with poly(ethene). This file
goes wider: essential vs non-essential amino acids, primary/secondary/
tertiary protein structure, enzymes and antibodies as protein examples,
denaturation, more peptide-bond and Mr calculations, and the general
condensation-polymer pattern amino acids share with other biopolymers.
"""

TOPIC = "organic"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": "ks4-amino-acids-e05",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State the general term for an amino acid that the human body cannot make and must obtain from food.",
        "options": [
            "An essential amino acid",
            "A non-essential amino acid",
            "A denatured amino acid",
            "A synthetic amino acid",
        ],
        "correct_index": 0,
        "why": "Essential amino acids cannot be synthesised by the body, so they must come from the diet.",
    },
    {
        "id": "ks4-amino-acids-e06",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Name the type of biological molecule that acts as a catalyst and is itself built from amino acids.",
        "options": [
            "A lipid",
            "An enzyme",
            "A nucleotide",
            "A carbohydrate",
        ],
        "correct_index": 1,
        "why": "Enzymes are proteins, and all proteins are polymers built from chains of amino acid monomers.",
    },
    {
        "id": "ks4-amino-acids-e07",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Give the definition biologists use for a protein's primary structure.",
        "options": [
            "The bonds holding several chains together",
            "The overall three-dimensional shape",
            "The order of amino acids in the chain",
            "The folding into a coiled shape",
        ],
        "correct_index": 2,
        "why": "Primary structure is simply the sequence of amino acids joined along the protein chain.",
    },
    {
        "id": "ks4-amino-acids-e08",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State what happens to a protein's shape when it is denatured by high temperature.",
        "options": [
            "Nothing changes in its shape",
            "Its amino acid sequence reverses",
            "It splits into separate elements",
            "Its folded shape is permanently lost",
        ],
        "correct_index": 3,
        "why": "Heat disrupts the bonds holding the folded shape together, so the protein loses its structure permanently.",
    },
    {
        "id": "ks4-amino-acids-e09",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Name the type of protein that recognises and binds to a specific foreign substance in the body.",
        "options": [
            "An antibody",
            "A hormone",
            "A carbohydrate",
            "A monomer",
        ],
        "correct_index": 0,
        "why": "Antibodies are proteins built from amino acids that bind to specific antigens on pathogens.",
    },
    {
        "id": "ks4-amino-acids-e10",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State the small molecule that is always released when two amino acids join together.",
        "options": [
            "Methane",
            "Water",
            "Ethanol",
            "Nitrogen",
        ],
        "correct_index": 1,
        "why": "Amino acids join by condensation, always releasing a water molecule for every peptide bond formed.",
    },
    {
        "id": "ks4-amino-acids-e11",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State what type of reaction is needed to break a protein back down into its individual amino acids.",
        "options": [
            "Neutralisation",
            "Electrolysis",
            "Hydrolysis",
            "Oxidation",
        ],
        "correct_index": 2,
        "why": "Hydrolysis uses water to break the peptide bonds, releasing the individual amino acid monomers.",
    },
    {
        "id": "ks4-amino-acids-e12",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State the group of amino acids from which every protein in the human body is built.",
        "options": [
            "Only two different amino acids",
            "Exactly one hundred amino acids",
            "A single, universal amino acid",
            "About twenty different amino acids",
        ],
        "correct_index": 3,
        "why": "Around twenty different amino acids combine in varying sequences to build every protein in the body.",
    },
    {
        "id": "ks4-amino-acids-e13",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State the type of bond that joins two amino acids together in a chain.",
        "options": [
            "A peptide bond",
            "A metallic bond",
            "A hydrogen bond",
            "An ionic bond",
        ],
        "correct_index": 0,
        "why": "The covalent bond formed between amino acids during condensation is specifically called a peptide bond.",
    },
    {
        "id": "ks4-amino-acids-e14",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Name the general class of biological molecule that a chain of many amino acids forms.",
        "options": [
            "A carbohydrate",
            "A protein",
            "A nucleic acid",
            "A lipid",
        ],
        "correct_index": 1,
        "why": "Proteins are, by definition, polymers built from long chains of amino acid monomers.",
    },
    {
        "id": "ks4-amino-acids-e15",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State the term for the process by which heat or extreme pH permanently changes a protein's shape.",
        "options": [
            "Fermentation",
            "Hydrolysis",
            "Denaturation",
            "Neutralisation",
        ],
        "correct_index": 2,
        "why": "Denaturation describes the permanent loss of a protein's folded shape caused by heat or extreme pH.",
    },
    {
        "id": "ks4-amino-acids-e16",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State the name given to a chain built from many amino acids joined together.",
        "options": [
            "A fatty acid",
            "A nucleotide",
            "A monosaccharide",
            "A polypeptide",
        ],
        "correct_index": 3,
        "why": "A long chain of many amino acids linked by peptide bonds is called a polypeptide.",
    },
    {
        "id": "ks4-amino-acids-e17",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "State what an amino acid's R group determines about that amino acid.",
        "options": [
            "Which of the twenty amino acids it is",
            "Whether it can form a peptide bond",
            "Its overall electrical charge only",
            "Nothing distinguishes one amino acid from another",
        ],
        "correct_index": 0,
        "why": "Every amino acid shares the same core structure, so the R group is what makes each of the twenty amino acids distinct.",
    },
    {
        "id": "ks4-amino-acids-e18",
        "subtopic_slug": "amino-acids",
        "band": "easier",
        "tier": "higher",
        "triple_only": True,
        "text": "Name the molecule formed when exactly two amino acids join together.",
        "options": [
            "A tripeptide",
            "A dipeptide",
            "A polypeptide",
            "A monomer",
        ],
        "correct_index": 1,
        "why": "Two amino acids joined by one peptide bond form a dipeptide.",
    },
    {
        "id": "ks4-amino-acids-s05",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why the secondary structure of a protein, such as an alpha helix, forms.",
        "options": [
            "Water molecules coil the chain physically",
            "Ionic bonds attract distant amino acids",
            "Hydrogen bonds form along the backbone",
            "Peptide bonds twist as they form initially",
        ],
        "correct_index": 2,
        "why": "Hydrogen bonding between nearby parts of the backbone pulls the chain into a regular coiled or folded shape.",
    },
    {
        "id": "ks4-amino-acids-s06",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why the tertiary structure of an enzyme is essential for it to function.",
        "options": [
            "It adds more amino acids to the chain",
            "It changes the enzyme's primary sequence",
            "It removes the enzyme's peptide bonds",
            "It fixes the enzyme's active site shape",
        ],
        "correct_index": 3,
        "why": "The overall 3D folding creates a precisely shaped active site that fits only its specific substrate.",
    },
    {
        "id": "ks4-amino-acids-s07",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why denaturing an enzyme by extreme pH usually stops it working, even though its amino acid sequence is unchanged.",
        "options": [
            "The active site's shape is destroyed",
            "It loses its ability to dissolve in water",
            "Its molecular formula changes entirely",
            "It converts into a different amino acid",
        ],
        "correct_index": 0,
        "why": "Extreme pH disrupts the bonds holding the folded shape, distorting the active site so the substrate no longer fits.",
    },
    {
        "id": "ks4-amino-acids-s08",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Two different amino acids, A and B, can join in two different orders. Explain why AB and BA are different dipeptides.",
        "options": [
            "AB and BA have different peptide bond types",
            "AB and BA have a different amino acid order",
            "AB and BA contain different atoms overall",
            "AB and BA release different small molecules",
        ],
        "correct_index": 1,
        "why": "The sequence of amino acids determines the identity of the peptide, so swapping the order gives a genuinely different molecule.",
    },
    {
        "id": "ks4-amino-acids-s09",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A polypeptide contains 12 peptide bonds along its backbone. Calculate the number of amino acid monomers it must contain.",
        "options": [
            "12 monomers",
            "11 monomers",
            "13 monomers",
            "24 monomers",
        ],
        "correct_index": 2,
        "why": "A chain of n monomers has n minus 1 peptide bonds, so 12 bonds means 13 monomers.",
    },
    {
        "id": "ks4-amino-acids-s10",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why replacing one amino acid in an enzyme's sequence with a different one can stop the enzyme working, even though only one monomer has changed.",
        "options": [
            "It converts the enzyme into a carbohydrate",
            "It always removes the enzyme's active site",
            "It stops the chain folding correctly at all",
            "It can distort the folded shape and active site",
        ],
        "correct_index": 3,
        "why": "Even a single substitution can change how the chain folds, distorting the active site enough to stop the substrate binding.",
    },
    {
        "id": "ks4-amino-acids-s11",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why proteins, unlike addition polymers such as poly(ethene), can be broken down by enzymes in the digestive system.",
        "options": [
            "Peptide bonds can be hydrolysed by enzymes",
            "Proteins are far too small to be digested",
            "Proteins contain no covalent bonds at all",
            "Digestive enzymes only ever act on plastics",
        ],
        "correct_index": 0,
        "why": "Specific enzymes recognise and hydrolyse peptide bonds, something addition polymers' carbon backbones do not offer.",
    },
    {
        "id": "ks4-amino-acids-s12",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Glycine, H2NCH2COOH, has Mr 75. Calculate the relative formula mass of a tripeptide made from three glycine molecules.",
        "options": [
            "225",
            "189",
            "150",
            "203",
        ],
        "correct_index": 1,
        "why": "3 x 75 = 225, minus two water molecules (2 x 18 = 36) lost forming two peptide bonds, gives 189.",
    },
    {
        "id": "ks4-amino-acids-s13",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why cooking an egg white permanently changes its texture, in terms of its protein content.",
        "options": [
            "Heat removes all peptide bonds fully",
            "Heat replaces the amino acids present",
            "Heat denatures the proteins irreversibly",
            "Heat converts the protein into a fat",
        ],
        "correct_index": 2,
        "why": "The heat breaks the bonds maintaining the folded protein shape, and the egg-white proteins cannot refold once cooled.",
    },
    {
        "id": "ks4-amino-acids-s14",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why a vegetarian diet that lacks certain essential amino acids can still supply them if enough different plant proteins are eaten.",
        "options": [
            "The body can make any amino acid from sugar",
            "Essential amino acids are not truly needed",
            "Plants only ever contain non-essential amino acids",
            "Different plant proteins can together supply all",
        ],
        "correct_index": 3,
        "why": "Combining plant sources with different amino acid profiles can together provide every essential amino acid needed.",
    },
    {
        "id": "ks4-amino-acids-s15",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why amino acids are described as having both an acidic and a basic group.",
        "options": [
            "They contain both a –COOH and an –NH2 group",
            "They react only with strong acids present",
            "They contain two separate –COOH groups only",
            "They react only with strong alkalis present",
        ],
        "correct_index": 0,
        "why": "The –COOH group can donate a proton while the –NH2 group can accept one, giving amino acids their amphoteric behaviour.",
    },
    {
        "id": "ks4-amino-acids-s16",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "A protein is a co-polymer built from many different amino acid monomers. Explain what this means, compared with poly(ethene) made from only one monomer.",
        "options": [
            "A co-polymer never contains peptide bonds",
            "A co-polymer combines two or more monomer types",
            "A co-polymer cannot fold into a fixed shape",
            "A co-polymer always has a shorter chain",
        ],
        "correct_index": 1,
        "why": "Unlike poly(ethene), which repeats one monomer, a protein's chain mixes different amino acid monomers in sequence.",
    },
    {
        "id": "ks4-amino-acids-s17",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why a mutation that changes just one base in a gene can sometimes change an enzyme's shape completely.",
        "options": [
            "It converts the gene into a different protein",
            "It stops all future genes being expressed",
            "It can swap one amino acid in the sequence",
            "It always deletes the whole gene entirely",
        ],
        "correct_index": 2,
        "why": "A single base change can code for a different amino acid at that point, which can in turn alter how the chain folds.",
    },
    {
        "id": "ks4-amino-acids-s18",
        "subtopic_slug": "amino-acids",
        "band": "standard",
        "tier": "higher",
        "triple_only": True,
        "text": "State one similarity between a protein and starch, in terms of how their monomers join together.",
        "options": [
            "Both are made from exactly the same monomer",
            "Both contain a nitrogen atom in every monomer",
            "Both form only single, unbranched chains",
            "Both join their monomers by condensation",
        ],
        "correct_index": 3,
        "why": "Proteins and starch are both condensation polymers, joining their monomers with the loss of a water molecule each time.",
    },
    {
        "id": "ks4-amino-acids-h05",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why a protein's tertiary structure, not just its primary structure, determines whether an enzyme can catalyse a specific reaction.",
        "options": [
            "The 3D fold creates the working active site",
            "Tertiary structure has no effect on function",
            "Primary structure alone fixes the active site",
            "Only the amino acid sequence decides this",
        ],
        "correct_index": 0,
        "why": "The precise 3D folding brings the right amino acids together to form an active site shaped for one specific substrate.",
    },
    {
        "id": "ks4-amino-acids-h06",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A dipeptide of Mr 189 is completely hydrolysed. Explain what determines the total mass of the two products formed.",
        "options": [
            "One amino acid always loses all its mass",
            "The 189 splits with water added back in",
            "Hydrolysis always halves the total mass exactly",
            "The mass is fixed regardless of hydrolysis",
        ],
        "correct_index": 1,
        "why": "Hydrolysis reverses condensation, adding back the water molecule that was lost, so the two amino acids' total mass exceeds the dipeptide's mass by 18.",
    },
    {
        "id": "ks4-amino-acids-h07",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Evaluate the claim that all condensation polymers, including proteins, DNA and polyesters, are biodegradable simply because they can be hydrolysed.",
        "options": [
            "Hydrolysis and biodegradation are unrelated ideas",
            "It is entirely true for every condensation polymer",
            "Being hydrolysable does not guarantee microbial breakdown",
            "It is false because none of them hydrolyse",
        ],
        "correct_index": 2,
        "why": "Hydrolysis in principle is not the same as being broken down by microorganisms in practice, which also depends on enzymes being available.",
    },
    {
        "id": "ks4-amino-acids-h08",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A student claims that because both proteins and addition polymers are polymers, they must share the same type of bond joining their monomers. Evaluate this claim.",
        "options": [
            "It is correct only for very short protein chains",
            "It is incorrect only because proteins are not polymers",
            "It is correct, since all polymers bond identically",
            "It is incorrect: proteins use peptide bonds, addition polymers use only carbon backbones",
        ],
        "correct_index": 3,
        "why": "Being a polymer only means repeating monomer units; how those units bond (condensation versus addition) differs fundamentally between the two.",
    },
    {
        "id": "ks4-amino-acids-h09",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why two proteins built from the exact same twenty amino acids, in the same overall proportions, can still fold into completely different shapes and functions.",
        "options": [
            "The order of amino acids along the chain differs",
            "Proportions always fix the resulting shape",
            "Different proteins cannot share the same amino acids",
            "Shape depends only on the total chain length",
        ],
        "correct_index": 0,
        "why": "The specific sequence, not just which amino acids are present, determines how the chain folds and therefore what it does.",
    },
    {
        "id": "ks4-amino-acids-h10",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "0.2 mol of a single amino acid, Mr 89, polymerises completely into one long protein chain, losing one water molecule per peptide bond formed. Calculate the mass of water released, assuming a very long chain.",
        "options": [
            "0.2 g",
            "3.6 g",
            "1.8 g",
            "17.8 g",
        ],
        "correct_index": 1,
        "why": "For a very long chain, essentially every monomer forms one bond: 0.2 mol x 18 g/mol ≈ 3.6 g of water.",
    },
    {
        "id": "ks4-amino-acids-h11",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why an enzyme denatured by boiling cannot simply be cooled back down to refold into its original active shape.",
        "options": [
            "Boiling converts the enzyme into a carbohydrate",
            "Cooling always restores the original fold",
            "The bonds maintaining the fold break irreversibly",
            "Boiling changes the enzyme's amino acid sequence",
        ],
        "correct_index": 2,
        "why": "The interactions holding the tertiary structure together are broken by the heat and generally do not reform correctly on cooling.",
    },
    {
        "id": "ks4-amino-acids-h12",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Compare the effect of changing one amino acid near an enzyme's active site with changing one amino acid far from it, on the enzyme's function.",
        "options": [
            "A distant change always disrupts function more",
            "Neither location ever affects the enzyme's function",
            "Both changes always affect function identically",
            "A change near the active site is more likely to disrupt function",
        ],
        "correct_index": 3,
        "why": "Amino acids near the active site are more likely to directly affect its shape, while distant ones may have little effect on folding there.",
    },
    {
        "id": "ks4-amino-acids-h13",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A pharmaceutical company designs a drug that mimics the shape of a natural substrate to block an enzyme's active site. Explain why the drug's own amino-acid-like shape must be very precise.",
        "options": [
            "The active site only accepts one specific shape",
            "Enzymes accept absolutely any molecular shape",
            "Shape has no bearing on enzyme binding at all",
            "Only the drug's overall mass matters for binding",
        ],
        "correct_index": 0,
        "why": "Enzymes are shape-specific, so a blocking drug must closely match the substrate's shape to fit and occupy the active site.",
    },
    {
        "id": "ks4-amino-acids-h14",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why DNA and proteins are both classed as condensation polymers, despite having very different monomers and very different biological roles.",
        "options": [
            "Both carry genetic information in their sequence",
            "Both lose a small molecule joining monomers",
            "Both are built from exactly the same monomer",
            "Both fold into an identical overall shape",
        ],
        "correct_index": 1,
        "why": "The defining feature of a condensation polymer is monomers joining with loss of a small molecule, which both DNA and proteins share.",
    },
    {
        "id": "ks4-amino-acids-h15",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "A polypeptide of Mr 943 is formed from ten identical amino acid monomers joined in a single chain. Calculate the Mr of one monomer.",
        "options": [
            "89.0",
            "94.3",
            "104.5",
            "112.6",
        ],
        "correct_index": 2,
        "why": "Ten monomers form nine peptide bonds, losing nine water molecules (162): (943 + 162) / 10 = 104.5.",
    },
    {
        "id": "ks4-amino-acids-h16",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why comparing two proteins' primary structures alone cannot always predict whether they will have the same function.",
        "options": [
            "Two proteins can never share the same function",
            "Primary structure always guarantees the same fold",
            "Function depends only on total amino acid count",
            "Folding can still differ even with a similar sequence",
        ],
        "correct_index": 3,
        "why": "Sequence strongly influences folding, but factors during folding can still lead to different final shapes and therefore functions.",
    },
    {
        "id": "ks4-amino-acids-h17",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Evaluate the statement that hydrolysing a protein always releases exactly twenty different amino acids.",
        "options": [
            "It depends on which amino acids that protein actually contains",
            "It is wrong because hydrolysis never releases amino acids",
            "It is wrong because proteins contain no amino acids",
            "It is correct for every protein without exception",
        ],
        "correct_index": 0,
        "why": "A given protein only contains the specific amino acids present in its own sequence, not necessarily all twenty possible ones.",
    },
    {
        "id": "ks4-amino-acids-h18",
        "subtopic_slug": "amino-acids",
        "band": "harder",
        "tier": "higher",
        "triple_only": True,
        "text": "Explain why an enzyme's optimum temperature is not simply 'the hotter the better', even though warming usually speeds up reactions.",
        "options": [
            "Temperature has no effect on enzyme activity",
            "Heat above the optimum denatures the enzyme",
            "Cold temperatures always denature enzymes fully",
            "Enzymes work identically at every temperature",
        ],
        "correct_index": 1,
        "why": "Beyond the optimum, rising temperature increasingly denatures the enzyme, so activity falls even though collisions are more frequent.",
    },
]
