"""Chemistry · Organic chemistry — the MRB-338 expansion for
`properties-of-hydrocarbons`.

The twenty shipped rows own the PHYSICAL trends — state, viscosity,
volatility, flammability and boiling point against chain length — together
with the blue-flame/yellow-flame observation and two combustion calculations.
Those trends are therefore not re-asked here; a row that merely re-worded
them would collide with the shipped twenty and with `fractional-distillation`
at the same time.

What this file takes is the other half of AQA 7.1.3, which the shipped rows
only glance at: COMBUSTION AS OXIDATION and what comes out of it. Carbon
monoxide by name, why it is dangerous and how it harms the body; soot and the
problems it causes; the sulfur impurity that burns to sulfur dioxide and
falls as acid rain; oxidation of the carbon and of the hydrogen named as
such; equations for incomplete combustion; and the practical judgements that
follow — ventilation, servicing a burner, removing sulfur from a fuel,
choosing a cleaner fuel, and why a pressurised cylinder holds so much propane.

⚠️ The chain-length trends stay with the shipped rows, and the column stays
with `fractional-distillation`. Formulae are written flat (C3H8, CO2, SO2).
"""

TOPIC = "organic"
SUBJECT = "chemistry"

QUESTIONS = [
    # ---------------------------------------------------------------- easier
    {
        "id": "ks4-properties-of-hydrocarbons-e06",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the toxic gas formed when a fuel burns in too little oxygen.",
        "options": [
            "Carbon monoxide",
            "Carbon dioxide",
            "Hydrogen",
            "Nitrogen",
        ],
        "correct_index": 0,
        "why": "Incomplete combustion oxidises the carbon only part of the way, giving carbon monoxide.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-e07",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give the property of carbon monoxide that makes a leak so hard to notice.",
        "options": [
            "It has a strong smell of rotten eggs that most people cannot detect at low levels",
            "It is bright green, but only when the room it collects in is completely dark",
            "It is heavier than every other gas in the air, so it collects unseen at floor level in the room",
            "It has no colour and no smell at all",
        ],
        "correct_index": 3,
        "why": "Carbon monoxide is colourless and odourless, so only an alarm will detect it.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-e08",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the black solid deposited when a fuel burns with a smoky flame.",
        "options": [
            "Ash from the burner",
            "Sulfur",
            "Soot, which is solid carbon",
            "Rust",
        ],
        "correct_index": 2,
        "why": "Unburnt carbon particles from incomplete combustion settle as soot.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-e09",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the gas formed when sulfur present in a fuel is burned.",
        "options": [
            "Hydrogen sulfide",
            "Sulfur dioxide",
            "Sulfuric acid",
            "Sulfur trioxide",
        ],
        "correct_index": 1,
        "why": "Sulfur impurities burn in air to give sulfur dioxide, SO2.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-e10",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the reaction in which a fuel reacts with oxygen and releases energy.",
        "options": [
            "Neutralisation",
            "Electrolysis",
            "Combustion",
            "Distillation",
        ],
        "correct_index": 2,
        "why": "Burning a fuel in oxygen is combustion, an exothermic oxidation reaction.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-e11",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the gas from the air that a fuel needs in order to burn.",
        "options": [
            "Nitrogen",
            "Argon",
            "Oxygen",
            "Carbon dioxide",
        ],
        "correct_index": 2,
        "why": "Combustion is a reaction with oxygen, which makes up about a fifth of the air.",
    },
    # -------------------------------------------------------------- standard
    {
        "id": "ks4-properties-of-hydrocarbons-s09",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give the word equation for the complete combustion of methane in a plentiful supply of air.",
        "options": [
            "Methane plus oxygen goes to carbon monoxide plus hydrogen, with soot left over as well",
            "Methane plus oxygen goes to carbon dioxide plus water",
            "Methane plus carbon dioxide goes to oxygen plus water, releasing energy to the surroundings",
            "Methane plus water goes to carbon dioxide plus hydrogen and a small amount of sulfur dioxide as well",
        ],
        "correct_index": 1,
        "why": "Complete combustion oxidises the carbon to carbon dioxide and the hydrogen to water.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s10",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A gas fire in a home is serviced every year to keep its flame blue. Explain why that matters.",
        "options": [
            "A yellow flame shows incomplete combustion, which makes poisonous carbon monoxide",
            "A blue flame burns the sulfur in the gas, which a yellow flame leaves behind unburned instead",
            "A blue flame is hotter, and a hot flame uses up much less gas than a cool one does",
            "A yellow flame means the gas supply is much too strong for the burner it is fitted to",
        ],
        "correct_index": 0,
        "why": "A yellow, sooty flame means too little air, so carbon monoxide is being produced.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s11",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain how breathing in carbon monoxide harms a person.",
        "options": [
            "It burns the lining of the lungs, because it is still reacting with oxygen at the moment when it is inhaled",
            "It binds to haemoglobin, so the blood carries much less oxygen",
            "It dissolves in the blood to make an acid that then attacks the walls of the blood vessels",
            "It replaces the nitrogen in the air",
        ],
        "correct_index": 1,
        "why": "Carbon monoxide attaches to haemoglobin in place of oxygen, starving the body of oxygen.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s12",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Methane burns in a limited supply of oxygen so that carbon monoxide is the only carbon-containing product. Which equation represents this?",
        "options": [
            "CH4 + 2O2 goes to CO2 + 2H2O",
            "CH4 + O2 goes to C + 2H2O",
            "2CH4 + 5O2 goes to 2CO + 4H2O",
            "2CH4 + 3O2 goes to 2CO + 4H2O",
        ],
        "correct_index": 3,
        "why": "2CH4 + 3O2 gives 2CO + 4H2O, which balances for carbon, hydrogen and oxygen.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s13",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain how burning a fuel that contains sulfur can damage trees and stonework far from the chimney.",
        "options": [
            "The soot from the fuel settles on the leaves and stops the trees taking in any light",
            "Sulfur dioxide dissolves in rain water, and the acid rain falls elsewhere",
            "Sulfur dioxide is denser than air, so it sinks straight down and burns everything growing below it",
            "The carbon dioxide released reacts with the stone",
        ],
        "correct_index": 1,
        "why": "Sulfur dioxide dissolves in cloud droplets to form acid rain, which falls far downwind.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s14",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why refineries remove sulfur compounds from fuels before selling them.",
        "options": [
            "Because sulfur stops the fuel burning until it has all been taken out of the mixture first",
            "Because sulfur would make the fuel far too viscous to be pumped along any pipeline",
            "Because sulfur has a strong smell",
            "Because burning the sulfur would form sulfur dioxide and cause acid rain",
        ],
        "correct_index": 3,
        "why": "Taking the sulfur out beforehand stops sulfur dioxide being released when the fuel is burned.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s15",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "During combustion the carbon in a fuel gains oxygen. Name this type of reaction.",
        "options": [
            "Oxidation",
            "Reduction",
            "Neutralisation",
            "Displacement",
        ],
        "correct_index": 0,
        "why": "Gaining oxygen is oxidation, which is what happens to both the carbon and the hydrogen.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s16",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "An engineer finds a thick black deposit inside a boiler. Deduce what it shows about how the boiler is running.",
        "options": [
            "It is not getting enough air, so combustion is incomplete",
            "It is burning far too much air for the amount of fuel that is reaching the burner",
            "It is burning a fuel whose molecules have chains that are much too short for the job it does",
            "It is running at too low a pressure",
        ],
        "correct_index": 0,
        "why": "Carbon deposits form when there is too little oxygen for the carbon to be fully oxidised.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s17",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give two problems caused by the soot released when fuels burn incompletely.",
        "options": [
            "It smells unpleasant and it is explosive",
            "It makes rain acidic and it poisons the blood of anyone who breathes any of it in",
            "It raises the temperature of the atmosphere and it dissolves the stonework of buildings",
            "It dirties buildings and it can cause breathing problems",
        ],
        "correct_index": 3,
        "why": "Soot blackens buildings and the fine particles irritate and damage the lungs.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s18",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Fuel D has four carbon atoms per molecule and fuel E has sixteen. Predict which is the easier to set alight, and explain.",
        "options": [
            "E, because a molecule with more atoms in it always holds a great deal more energy",
            "E, because longer molecules are drawn towards a flame more strongly than short ones",
            "D, because shorter chains evaporate more readily and it is the vapour that ignites",
            "Neither, because chain length makes no difference at all to how a fuel behaves",
        ],
        "correct_index": 2,
        "why": "A fuel must vaporise before it burns, and the shorter chain is far more volatile.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s19",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Using a camping stove inside a closed tent has killed people. Explain the danger.",
        "options": [
            "The tent traps the heat from the stove until the fabric of the tent itself eventually catches fire",
            "Poor ventilation gives incomplete combustion, so carbon monoxide builds up",
            "The stove uses up all the nitrogen in the tent, and nitrogen is needed for breathing",
            "The fuel leaks out of the stove and soaks into the ground sheet where it cannot be seen",
        ],
        "correct_index": 1,
        "why": "With little fresh air the stove produces carbon monoxide, which is toxic and undetectable.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s20",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why natural gas is often described as a cleaner fuel than coal.",
        "options": [
            "It burns with very little soot and contains almost no sulfur",
            "It releases no carbon dioxide at all, whichever way it happens to be burned",
            "It can only ever burn completely, however little air happens to reach the burner itself",
            "It contains no carbon",
        ],
        "correct_index": 0,
        "why": "Methane burns cleanly and carries few sulfur impurities, so less soot and sulfur dioxide form.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s21",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The hydrogen in a hydrocarbon is oxidised when the fuel burns. Name the product formed from it.",
        "options": [
            "Hydrogen peroxide",
            "Hydrogen gas",
            "Water",
            "A hydroxide",
        ],
        "correct_index": 2,
        "why": "Oxidised hydrogen becomes water, which leaves the flame as steam.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s22",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Propane boils at minus 42 degrees Celsius and hexadecane boils at 287 degrees Celsius. Deduce which is sold as a gas in cylinders.",
        "options": [
            "Propane, because it is a gas at ordinary temperatures",
            "Hexadecane, because a high boiling point means it is already a gas at room temperature",
            "Both of them, because any hydrocarbon can be supplied as a gas if it is put under enough pressure",
            "Neither, because a gas cannot be stored",
        ],
        "correct_index": 0,
        "why": "A boiling point well below room temperature means propane is a gas unless it is compressed.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s23",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give the meaning of the word 'flammable' when it is used to describe a fuel.",
        "options": [
            "It burns to give out a very large amount of energy for every single gram of it that is burned",
            "It flows easily along a pipe even when the weather outside is extremely cold",
            "It evaporates quickly at room temperature without needing to be warmed up first",
            "It catches fire easily",
        ],
        "correct_index": 3,
        "why": "Flammability is how readily a substance ignites, which for a fuel depends on how easily it vaporises.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s24",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a hydrocarbon with a very high boiling point is hard to burn in an ordinary burner.",
        "options": [
            "It contains no hydrogen, so there is nothing in it for the oxygen in the air to react with at all",
            "It has already reacted with the oxygen in the air before it ever reaches the burner",
            "It is too dense to be lifted up the wick of the burner by the fuel supply",
            "It barely vaporises, and a fuel has to be a vapour before it will ignite",
        ],
        "correct_index": 3,
        "why": "Burning happens in the vapour, so an involatile hydrocarbon will not ignite readily.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-s25",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the product of complete combustion that turns limewater milky.",
        "options": [
            "Carbon dioxide",
            "Carbon monoxide",
            "Sulfur dioxide",
            "Water vapour",
        ],
        "correct_index": 0,
        "why": "Limewater turning milky is the standard test for carbon dioxide.",
    },
    # ---------------------------------------------------------------- harder
    {
        "id": "ks4-properties-of-hydrocarbons-h08",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Propane, C3H8, burns so that carbon monoxide is the only carbon-containing product. Determine the balanced equation.",
        "options": [
            "C3H8 + 5O2 goes to 3CO2 + 4H2O",
            "2C3H8 + 7O2 goes to 6CO + 8H2O",
            "C3H8 + 3O2 goes to 3CO + 4H2O",
            "2C3H8 + 9O2 goes to 6CO + 8H2O",
        ],
        "correct_index": 1,
        "why": "Two propane molecules give 6CO and 8H2O, needing 14 oxygen atoms, which is 7O2.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h09",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A boiler burns methane with too little air. Name the three carbon-containing products that may be formed.",
        "options": [
            "Carbon dioxide, methane and sulfur dioxide, in amounts that depend on the air supply reaching it",
            "Carbon dioxide, carbon monoxide and carbon",
            "Carbon monoxide, hydrogen and water, together with a little unburned methane as well",
            "Carbon, hydrogen and oxygen",
        ],
        "correct_index": 1,
        "why": "As the air supply falls the carbon is oxidised less and less fully: CO2, then CO, then soot.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h10",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the danger posed by carbon monoxide with that posed by carbon dioxide in a poorly ventilated room.",
        "options": [
            "Carbon monoxide is toxic in small amounts; carbon dioxide is only harmful at much higher levels",
            "Carbon dioxide is the more dangerous, because a person cannot see or smell it at all",
            "Both are equally toxic, because a molecule of each contains exactly the same elements",
            "Neither is dangerous indoors, since both of them are always released by anyone breathing out",
        ],
        "correct_index": 0,
        "why": "Carbon monoxide poisons by binding to haemoglobin; carbon dioxide only harms by displacing oxygen at high concentration.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h11",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "One mole of octane, C8H18, burns completely. Calculate the amount of carbon dioxide formed, in moles.",
        "options": [
            "1 mol",
            "8 mol",
            "18 mol",
            "9 mol",
        ],
        "correct_index": 1,
        "why": "Each of the eight carbon atoms becomes one molecule of carbon dioxide, so 8 mol form.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h12",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe, using the idea of oxidation, what happens to the two elements in a hydrocarbon when it burns fully.",
        "options": [
            "Only the carbon is oxidised; the hydrogen is reduced to hydrogen gas and escapes from the flame unburned",
            "Both are reduced, the carbon to soot and the hydrogen to hydrogen gas, with energy given out",
            "Neither is oxidised, because burning simply separates the atoms from one another again",
            "Both are oxidised: the carbon to carbon dioxide and the hydrogen to water",
        ],
        "correct_index": 3,
        "why": "Complete combustion fully oxidises both elements, which is why only CO2 and H2O are formed.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h13",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Power stations are fitted with equipment that removes sulfur dioxide from waste gases. Evaluate whether this is worth its cost.",
        "options": [
            "Not worth it, because sulfur dioxide is harmless once it has left the chimney and spread out into the air",
            "Not worth it, since the sulfur dioxide would be washed out of the air by rain in any case",
            "Worth it, because it prevents acid rain damaging lakes, trees and buildings",
            "Worth it, because it stops carbon dioxide being released",
        ],
        "correct_index": 2,
        "why": "The damage acid rain does to ecosystems and stonework outweighs the cost of removing the gas.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h14",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Hydrocarbon M has five carbon atoms per molecule and hydrocarbon N has twenty. Compare them for flammability, viscosity and boiling point.",
        "options": [
            "M is more flammable and more viscous than N, but the two of them boil at the same temperature",
            "M is less flammable and more viscous than N, and M also has the higher boiling point",
            "M is more flammable, less viscous and boils lower than N",
            "They match on all three, because both of them are hydrocarbons built from the very same two elements",
        ],
        "correct_index": 2,
        "why": "Shorter chains mean weaker forces between molecules: easier to ignite, runnier, lower boiling point.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h15",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate this claim: 'A burner running with a yellow, smoky flame is wasting fuel.'",
        "options": [
            "Supported — incomplete combustion leaves carbon only partly oxidised, so less energy is released",
            "Rejected, because the soot is collected afterwards and burned again in the same burner",
            "Rejected, because a yellow flame is hotter than a blue one and so wastes nothing at all",
            "Supported, because a yellow flame uses no oxygen",
        ],
        "correct_index": 0,
        "why": "Unburnt carbon and carbon monoxide still hold chemical energy that the burner never releases.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h16",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A fuel oil contains 1.0% sulfur by mass. Calculate the mass of sulfur in 200 g of the fuel.",
        "options": [
            "0.2 g",
            "20 g",
            "100 g",
            "2 g",
        ],
        "correct_index": 3,
        "why": "1.0% of 200 g is 200 x 0.010 = 2 g.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h17",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a hydrocarbon that is a gas at room temperature is stored in a strong pressurised cylinder.",
        "options": [
            "The pressure turns it into a liquid, so far more of it fits in the cylinder",
            "The pressure makes the molecules react with one another to form a much longer chain",
            "The pressure raises its temperature until it is hot enough to be burned straight away",
            "The pressure stops the gas reacting with the metal walls of the steel cylinder it is kept in",
        ],
        "correct_index": 0,
        "why": "Compressing the gas liquefies it, and a liquid takes up a tiny fraction of the volume.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h18",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A Bunsen burner's air hole is closed. Predict the change in the flame and explain it in terms of combustion.",
        "options": [
            "It turns a deeper blue, because the gas is now burning in pure oxygen instead of in air",
            "It goes out at once, because a flame cannot burn without any air hole open anywhere",
            "It turns yellow and sooty, because less oxygen reaches the gas so combustion is incomplete",
            "It stays exactly as it was, because the air hole only alters the noise the burner makes",
        ],
        "correct_index": 2,
        "why": "Closing the air hole starves the flame of oxygen, so glowing carbon particles colour it yellow.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h19",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A paraffin heater is to be used indoors. Explain which condition matters most for the safety of the people in the room.",
        "options": [
            "The heater must be raised off the floor, so that the flame is well away from the carpet",
            "The heater must be refilled while it is alight, so that the flame is never once allowed to go out",
            "The fuel must be stored cold",
            "The room must be well ventilated, or carbon monoxide will build up",
        ],
        "correct_index": 3,
        "why": "A good air supply keeps combustion complete; without it the heater produces carbon monoxide.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h20",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why hydrogen is described as a clean fuel when it is compared with a hydrocarbon.",
        "options": [
            "Because it releases far more energy for every gram burned than any other fuel does",
            "Because burning it gives water only, with no carbon dioxide, carbon monoxide or soot",
            "Because it can be burned safely in a room that has no ventilation of any kind at all",
            "Because it is a gas",
        ],
        "correct_index": 1,
        "why": "Hydrogen contains no carbon and no sulfur, so its only combustion product is water.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h21",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Opening the air hole of a burner raises the temperature reached by a beaker of water above it. Explain why.",
        "options": [
            "More air cools the flame, and a cooler flame transfers its energy to the water a great deal more slowly",
            "More oxygen makes combustion complete, so more energy is released from the same fuel",
            "More air blows the flame against the glass, which is what heats the water in the beaker",
            "More air adds nitrogen to the flame, and burning nitrogen releases a great deal of energy",
        ],
        "correct_index": 1,
        "why": "Fully oxidising the carbon releases all the fuel's energy instead of leaving it locked in soot and carbon monoxide.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h22",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student argues that every hydrocarbon is equally good as a fuel because they all contain the same two elements. Evaluate that argument.",
        "options": [
            "Correct, because the elements present are the only thing at all that decides how a fuel behaves",
            "Correct, so long as the two fuels being compared are burned in the very same burner",
            "Incorrect — chain length decides volatility, and so decides how readily the fuel burns",
            "Incorrect, because some hydrocarbons contain no carbon at all",
        ],
        "correct_index": 2,
        "why": "Bitumen and propane hold the same elements but behave completely differently as fuels.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h23",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why very long hydrocarbon chains are sold as lubricating oils rather than as fuels.",
        "options": [
            "They are so volatile that they would evaporate out of an engine long before it was ever started",
            "They contain no carbon atoms, so there is nothing in them that could burn in a engine",
            "They are viscous and barely vaporise, so they stay in place instead of igniting",
            "They have no boiling point",
        ],
        "correct_index": 2,
        "why": "High viscosity keeps the oil between moving parts, and low volatility stops it burning off.",
    },
    {
        "id": "ks4-properties-of-hydrocarbons-h24",
        "subtopic_slug": "properties-of-hydrocarbons",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Burning a sulfur-containing fuel releases both sulfur dioxide and carbon dioxide. Compare the environmental problem each of them causes.",
        "options": [
            "Sulfur dioxide adds to global warming, while carbon dioxide is the gas that causes acid rain",
            "Both of them cause acid rain, and neither of them has any effect on the climate whatsoever",
            "Neither causes a problem once the waste gases have left the top of the chimney and spread out into the air",
            "Sulfur dioxide causes acid rain; carbon dioxide adds to global warming",
        ],
        "correct_index": 3,
        "why": "Sulfur dioxide acidifies rain; carbon dioxide is a greenhouse gas that warms the atmosphere.",
    },
]
