"""Chemistry · Rates & Equilibrium — the MRB-338 expansion, subtopic
`factors-affecting-rate`.

The baseline twelve cover each of the four rate factors once, plus fair
testing and one combined-change comparison. This file goes wider: the
"roughly doubles every 10 °C" rule applied to bigger temperature jumps,
named real-world surface-area examples beyond the marble-chip standard, the
factors that simply do not apply to a given reaction (no concentration for
two solids, no meaningful pressure change for a reaction in solution),
reading short data tables for a proportionality pattern, and evaluating
flawed experimental reasoning — an uncontrolled variable, a dilution that
does not do what was intended, or a comparison between two different
reactions rather than one reaction under two conditions. The "why both
concentration and pressure work by packing more particles into the same
volume" comparison sits here, not in `collision-theory`, which owns the
activation-energy mechanism behind every factor instead.
"""

TOPIC = "rates-equilibrium"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": "ks4-factors-affecting-rate-e05",
        "subtopic_slug": "factors-affecting-rate",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how heating a mixture of two dissolved reactants affects how quickly they react together.",
        "options": [
            "It increases the rate of the reaction",
            "It decreases the rate of the reaction",
            "It has no effect on the rate of the reaction",
            "It stops the reaction from taking place",
        ],
        "correct_index": 0,
        "why": "Warmer particles move faster and collide more often and more energetically, so the reaction speeds up.",
    },
    {
        "id": "ks4-factors-affecting-rate-e06",
        "subtopic_slug": "factors-affecting-rate",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State one advantage of storing perishable food in a freezer rather than only in a refrigerator.",
        "options": [
            "A freezer removes all the water from food, which is the way to stop it spoiling",
            "A freezer is colder, so the reactions that spoil food run even more slowly, giving a longer storage time",
            "A freezer kills every bacterium in the food immediately once it is placed inside",
            "A freezer raises the activation energy of spoilage reactions above what bacteria can supply",
        ],
        "correct_index": 1,
        "why": "The lower the temperature, the slower the chemical reactions that cause food to spoil, so a colder freezer keeps food edible for longer than a fridge.",
    },
    {
        "id": "ks4-factors-affecting-rate-e07",
        "subtopic_slug": "factors-affecting-rate",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the effect of increasing the concentration of a reactant on the rate of a reaction in solution.",
        "options": [
            "It decreases the rate of the reaction",
            "It has no effect on the rate of the reaction",
            "It increases the rate of the reaction",
            "It changes the total mass of product made",
        ],
        "correct_index": 2,
        "why": "A more concentrated solution packs more particles into each cubic centimetre, so collisions happen more often.",
    },
    {
        "id": "ks4-factors-affecting-rate-e08",
        "subtopic_slug": "factors-affecting-rate",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happens to the rate of a reaction if several small pieces of a solid reactant are pressed together into one larger lump before the reaction starts.",
        "options": [
            "The rate rises, because a single lump reacts more efficiently than loose pieces",
            "The rate is unchanged, because the total mass of solid is still the same under these particular conditions",
            "The rate falls, because pressing the pieces together raises the activation energy here",
            "The rate falls, because the total surface area exposed to the other reactant is now smaller",
        ],
        "correct_index": 3,
        "why": "Squashing the pieces together hides some of their surface from the other reactant, so fewer particles are exposed for collisions.",
    },
    {
        "id": "ks4-factors-affecting-rate-e09",
        "subtopic_slug": "factors-affecting-rate",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Identify which of the four rate factors only affects a reaction if at least one of the reactants is a gas.",
        "options": [
            "Pressure",
            "Temperature",
            "Surface area",
            "Concentration of a solution",
        ],
        "correct_index": 0,
        "why": "Pressure only meaningfully compresses a gas closer together; it has almost no effect on a solid or a liquid.",
    },
    {
        "id": "ks4-factors-affecting-rate-e10",
        "subtopic_slug": "factors-affecting-rate",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Identify which of the four rate factors cannot meaningfully be applied to a reaction between two solid lumps in direct contact, with no solution or gas involved.",
        "options": [
            "Temperature",
            "Concentration",
            "Surface area",
            "None of them — all four factors apply equally",
        ],
        "correct_index": 1,
        "why": "Concentration describes how crowded particles are in a solution, and there is no solution here for it to describe.",
    },
    {
        "id": "ks4-factors-affecting-rate-e11",
        "subtopic_slug": "factors-affecting-rate",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happens to the total surface area of a solid when it is broken into many smaller pieces of the same total mass.",
        "options": [
            "The total surface area decreases",
            "The total surface area stays exactly the same",
            "The total surface area increases",
            "The total surface area becomes impossible to measure",
        ],
        "correct_index": 2,
        "why": "Breaking a solid up creates many new faces that were previously hidden inside it, adding to the total area exposed.",
    },
    {
        "id": "ks4-factors-affecting-rate-e12",
        "subtopic_slug": "factors-affecting-rate",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Identify the change that would DECREASE the rate of the reaction between magnesium ribbon and dilute acid.",
        "options": [
            "Warming the acid gently before adding the magnesium in this situation",
            "Using magnesium powder instead of a ribbon",
            "Using a more concentrated acid than before",
            "Diluting the acid with extra water before adding the magnesium",
        ],
        "correct_index": 3,
        "why": "Diluting the acid lowers its concentration, so there are fewer acid particles in the same volume to collide with the magnesium.",
    },
    {
        "id": "ks4-factors-affecting-rate-s05",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why doubling the concentration of the hydrochloric acid used in the sodium thiosulfate experiment roughly halves the time taken for the cross to disappear.",
        "options": [
            "Doubling the concentration roughly doubles the rate, and time is inversely related to rate, so the time is roughly halved",
            "Doubling the concentration doubles the total mass of precipitate that eventually forms in the flask",
            "Doubling the concentration raises the temperature of the mixture, which is what speeds the reaction up here",
            "Doubling the concentration halves the activation energy that the colliding particles need to overcome",
        ],
        "correct_index": 0,
        "why": "A faster rate means the same amount of cloudiness forms sooner, so the time for the cross to vanish falls as the rate rises.",
    },
    {
        "id": "ks4-factors-affecting-rate-s06",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reaction is cooled from 40 °C to 20 °C. Using the rule that rate roughly doubles for every 10 °C rise, predict roughly how the time taken changes.",
        "options": [
            "It becomes roughly twice as long as before",
            "It becomes roughly four times as long as before",
            "It stays roughly the same, since cooling barely affects rate",
            "It becomes roughly a quarter of what it was before",
        ],
        "correct_index": 1,
        "why": "Cooling by 20 °C undoes two 10 °C steps, so the rate falls to about a quarter and the reaction takes about four times as long.",
    },
    {
        "id": "ks4-factors-affecting-rate-s07",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student investigates how temperature affects the rate of the reaction between magnesium and hydrochloric acid. Identify the variables that must be kept the same across every run.",
        "options": [
            "The temperature at which the acid is stored before the experiment begins",
            "The colour of the gas syringe and the exact make of the stopwatch used to time each single run",
            "The concentration and volume of acid, and the mass and surface area of the magnesium used",
            "The room in which the experiment is carried out, but nothing about the reactants themselves",
        ],
        "correct_index": 2,
        "why": "Only temperature should change between runs, so everything else that could affect rate has to be held constant.",
    },
    {
        "id": "ks4-factors-affecting-rate-s08",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "More of a gaseous reactant is pumped into a sealed, rigid container that already holds a reaction mixture, without changing its volume. Explain the effect this has on the reaction rate.",
        "options": [
            "The rate is unaffected, because the volume of the container has not changed",
            "The rate decreases, because the extra gas dilutes the reaction mixture already present",
            "The rate increases if the extra gas added is the limiting reactant of the two",
            "The rate increases, because there are now more gas particles in the same fixed volume, raising the pressure",
        ],
        "correct_index": 3,
        "why": "Adding more gas to the same fixed volume packs particles closer together, which is exactly what raising the pressure does.",
    },
    {
        "id": "ks4-factors-affecting-rate-s09",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State why finely powdered icing sugar scattered as a dust in air can burn far more readily than the same mass sitting as a solid lump of sugar.",
        "options": [
            "The dust exposes a vastly greater surface area to the oxygen in the air than the solid lump does",
            "The dust particles are individually hotter than the solid lump before either one is ignited",
            "The dust reacts with nitrogen in the air, while the solid lump reacts with oxygen",
            "The dust has a lower activation energy than the same sugar in one solid lump",
        ],
        "correct_index": 0,
        "why": "Spreading the same mass into a fine dust exposes an enormous surface area, so combustion can happen almost all at once.",
    },
    {
        "id": "ks4-factors-affecting-rate-s10",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why diluting an acid with water, without changing the total amount of acid present, slows down its reaction with a metal.",
        "options": [
            "Diluting removes some of the acid particles entirely by reacting them with the added water",
            "Diluting spreads the same number of acid particles through a bigger volume, so there are fewer of them in each cubic centimetre",
            "Diluting lowers the temperature of the mixture, which is the true reason the reaction slows regardless of the other factors",
            "Diluting raises the activation energy needed for a collision to succeed",
        ],
        "correct_index": 1,
        "why": "The same amount of acid now occupies more space, so its concentration — and the frequency of collisions — falls.",
    },
    {
        "id": "ks4-factors-affecting-rate-s11",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State why crushing an indigestion tablet before dropping it into water makes it react and dissolve faster than dropping the whole tablet in.",
        "options": [
            "Crushing changes the tablet's chemical formula into one that reacts more readily with water at this stage",
            "Crushing raises the temperature of the tablet before it enters the water",
            "Crushing exposes far more of the tablet's surface to the water at once, allowing more contact in the same time",
            "Crushing removes some of the mass of the tablet, so there is less of it left to react",
        ],
        "correct_index": 2,
        "why": "A crushed tablet has far more surface exposed to the water at any one moment than the same tablet left whole.",
    },
    {
        "id": "ks4-factors-affecting-rate-s12",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The same disappearing-cross reaction is run twice, everything else identical except the starting temperature. Run X takes 50 s; run Y takes 22 s. Determine which run used the hotter mixture.",
        "options": [
            "Run X, because a longer time means the particles simply had much longer to collide and so must have been hotter",
            "Neither can be determined, because temperature has no fixed relationship with the time taken",
            "Run Y, because a shorter time means a lower concentration of acid was used instead",
            "Run Y, because a shorter time to disappear means a faster rate, and higher temperature gives a faster rate",
        ],
        "correct_index": 3,
        "why": "A faster rate — and so a shorter time to the same result — points to the hotter of the two mixtures.",
    },
    {
        "id": "ks4-factors-affecting-rate-s13",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A piece of iron wool is left to react slowly with oxygen gas. Predict the effect of increasing the pressure of the oxygen surrounding it, all else unchanged.",
        "options": [
            "The rate increases, because more oxygen particles are packed into the same volume around the iron wool",
            "The rate is unaffected, because pressure changes the rate of a reaction between two gases",
            "The rate decreases, because a higher pressure pushes the oxygen particles away from the iron's own surface",
            "The rate increases if the iron wool is also crushed into a finer form at the same time",
        ],
        "correct_index": 0,
        "why": "One of the two reactants here is a gas, so raising its pressure still increases how many of its particles collide with the iron each second.",
    },
    {
        "id": "ks4-factors-affecting-rate-s14",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a single large iron nail rusts more slowly than the same total mass of iron filings, all else being equal.",
        "options": [
            "The filings are chemically different from the nail, even though both are made of iron in this experiment",
            "The filings expose far more surface area to the oxygen and moisture in the air than the one solid nail does",
            "The nail is protected by a coating that the loose filings do not have",
            "The filings absorb more water from the air than the solid nail can",
        ],
        "correct_index": 1,
        "why": "Splitting the same mass into many small filings creates far more exposed surface for oxygen and water to react with.",
    },
    {
        "id": "ks4-factors-affecting-rate-s15",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A fixed mass of magnesium ribbon is added to a more dilute acid than before, with everything else unchanged. Predict the effect this has on the time taken for all the magnesium to dissolve.",
        "options": [
            "The time taken decreases, because dilute acid reacts with magnesium more efficiently than concentrated acid",
            "The time taken stays exactly the same, because the same total mass of magnesium is used regardless",
            "The time taken increases, because the lower concentration means fewer collisions each second",
            "The magnesium stops dissolving completely once the acid is diluted",
        ],
        "correct_index": 2,
        "why": "A lower concentration means fewer acid particles in each cubic centimetre, so the magnesium takes longer to fully react.",
    },
    {
        "id": "ks4-factors-affecting-rate-s16",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a reaction between two gases held at a very low pressure, close to a vacuum, proceeds extremely slowly compared with the same gases at normal atmospheric pressure.",
        "options": [
            "At very low pressure the particles move far more slowly than they would at normal atmospheric pressure in this particular case",
            "At very low pressure the activation energy of the reaction rises well above its usual value",
            "At very low pressure the two gases stop being able to react with each other chemically",
            "At very low pressure the particles are spread far apart, so they meet each other and collide only very rarely",
        ],
        "correct_index": 3,
        "why": "A near-vacuum leaves very few particles in any given volume, so the chance of two of them meeting in the same place at the same time falls sharply.",
    },
    {
        "id": "ks4-factors-affecting-rate-s17",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Three identical mixtures of magnesium and acid are timed to see how long the reaction takes: at 20 °C it takes 60 s, at 30 °C it takes 38 s, and at 40 °C it takes 24 s. State the general trend this data shows.",
        "options": [
            "As the temperature rises, the time taken falls, so the reaction rate rises",
            "As the temperature rises, the time taken also rises, so the reaction rate must be falling",
            "The time taken is not related to the temperature in this data",
            "The reaction stops completely once the temperature rises above 30 °C",
        ],
        "correct_index": 0,
        "why": "Each 10 °C rise in this data brings a shorter reaction time, showing the rate is increasing as the mixture is warmed.",
    },
    {
        "id": "ks4-factors-affecting-rate-s18",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reaction is sped up by both raising the temperature and increasing the concentration of one reactant at the same time. Predict how this combined change compares with making only one of the two changes.",
        "options": [
            "The rate increases by exactly the same amount as either change on its own",
            "The rate increases by more than either change would achieve on its own",
            "The two changes cancel each other out, leaving the rate roughly unchanged",
            "The change made first has any effect on the final rate",
        ],
        "correct_index": 1,
        "why": "Each change on its own increases the frequency of successful collisions, so making both changes together increases it by more than either alone.",
    },
    {
        "id": "ks4-factors-affecting-rate-s19",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student claims that pressure has the same large effect on a reaction between two solid lumps as it does on a reaction between two gases. Explain why this is wrong.",
        "options": [
            "Solids cannot react with each other under any circumstances, so pressure is irrelevant regardless",
            "Pressure has an even bigger effect on solids than on gases, because solids are denser to begin with under these conditions",
            "The particles in a solid are already packed tightly together, so squeezing the solid barely changes how close together they are",
            "Pressure changes the activation energy of a solid-solid reaction but not of a gas-gas one",
        ],
        "correct_index": 2,
        "why": "A gas can be compressed into a much smaller volume, but the particles in a solid are already touching, so pressure has almost nothing left to change.",
    },
    {
        "id": "ks4-factors-affecting-rate-s20",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A fixed amount of gas is transferred from a small, crowded container into a much larger one at the same temperature. State what happens to the frequency of collisions between the gas particles.",
        "options": [
            "It rises, because the particles now have more room to accelerate before they collide",
            "It stays the same, because the total number of particles has not changed",
            "It falls to zero, because the particles can no longer find each other in a larger space",
            "It falls, because the same particles are now spread out over a much bigger volume",
        ],
        "correct_index": 3,
        "why": "Spreading the same particles through a bigger volume lowers the effective pressure and makes collisions less frequent.",
    },
    {
        "id": "ks4-factors-affecting-rate-s21",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "An unreactive gas is pumped into a sealed, rigid container at constant volume, without changing the amount of either reacting gas already inside. Predict the effect this has on the reaction rate.",
        "options": [
            "The rate is unaffected, because the concentration of the two reacting gases has not actually changed",
            "The rate increases, because the total pressure inside the container has risen",
            "The rate decreases, because the unreactive gas dilutes the reacting particles present",
            "The rate increases, because more particles overall means many more collisions of every possible kind",
        ],
        "correct_index": 0,
        "why": "Even though total pressure rises, the reacting particles are exactly as crowded as before, so their collision frequency is unchanged.",
    },
    {
        "id": "ks4-factors-affecting-rate-s22",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Acid is poured onto a single large lump of marble, and the same total mass is separately poured onto gravel-sized marble chips. Explain why the chips finish reacting far sooner, even though eventually both samples fully react.",
        "options": [
            "The chips contain a different form of calcium carbonate that reacts more readily with acid",
            "The chips offer far more surface area to the acid at once, so collisions happen much more often each second",
            "The lump does not finish reacting nearly as quickly as the chips",
            "The chips absorb heat from the acid faster, raising their own temperature above that of the lump in this particular case",
        ],
        "correct_index": 1,
        "why": "The greater surface area of the chips speeds up how quickly the acid reaches new marble, even though both samples eventually react completely.",
    },
    {
        "id": "ks4-factors-affecting-rate-s23",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reaction between two gases is cooled while its pressure is raised at the same time. Explain why the overall effect on rate cannot be predicted from this information alone.",
        "options": [
            "Cooling and raising pressure cancel out exactly, leaving the rate completely unchanged whatever else is going on",
            "Neither cooling nor pressure has any effect on a reaction between two gases",
            "Cooling would decrease the rate while raising the pressure would increase it, so the two changes pull in opposite directions",
            "The rate must fall, because cooling has the stronger effect on any gas reaction",
        ],
        "correct_index": 2,
        "why": "Without knowing the sizes of the two changes, there is no way to say which effect — the cooling or the extra pressure — wins out.",
    },
    {
        "id": "ks4-factors-affecting-rate-s24",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State why crushing washing powder tablets into a fine powder before adding them to a wash can help stains lift more quickly.",
        "options": [
            "Crushing the tablet changes its own chemical formula into one that dissolves faster",
            "Crushing the tablet raises the temperature of the water it is added to under these particular conditions",
            "The powder floats on the water's surface, unlike a solid tablet, which sinks",
            "The powder exposes far more surface area to the water at once than a solid tablet does",
        ],
        "correct_index": 3,
        "why": "A powdered tablet dissolves and disperses through the water far more quickly than the same tablet left whole, because more of it is exposed at once.",
    },
    {
        "id": "ks4-factors-affecting-rate-s25",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "The same total amount of acid is dissolved in twice the volume of water, while the amount of magnesium is also doubled so the concentration of the acid stays exactly the same as before. Explain what happens to the initial rate.",
        "options": [
            "The initial rate is unchanged, because rate depends on concentration, not on the total amounts of reactants present",
            "The initial rate doubles, because twice as much magnesium is now available to react",
            "The initial rate halves, because the acid is now spread through twice the volume of solution in this experiment",
            "The initial rate cannot be predicted without knowing the exact masses used",
        ],
        "correct_index": 0,
        "why": "Rate is set by how crowded the particles are, not by how much of each reactant is present overall, and the concentration here has been kept the same.",
    },
    {
        "id": "ks4-factors-affecting-rate-s26",
        "subtopic_slug": "factors-affecting-rate",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Reaction A takes 12 s to finish at room temperature. The identical reaction B, heated by 20 °C, takes 3 s. Determine whether this is consistent with the 'roughly doubles every 10 °C' rule.",
        "options": [
            "No — a 20 °C rise should double the rate once, so the predicted time here would be 6 s, not 3 s",
            "Yes — a 20 °C rise is two 10 °C steps, so the rate should be about four times faster, and 12 ÷ 4 = 3 s matches",
            "No — the rule applies to reactions that involve a gas, and this data does not say so",
            "Yes, but because both reactions happened to use exactly the same concentration of acid",
        ],
        "correct_index": 1,
        "why": "Two 10 °C steps give roughly four times the rate, and a quarter of 12 s is 3 s, which is exactly what was observed.",
    },
    {
        "id": "ks4-factors-affecting-rate-h05",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Using the rule that rate roughly doubles for every 10 °C rise, predict roughly how many times faster a reaction becomes after a 30 °C rise in temperature.",
        "options": [
            "About 3 times as fast",
            "About 6 times as fast",
            "About 8 times as fast",
            "About 30 times as fast",
        ],
        "correct_index": 2,
        "why": "A 30 °C rise is three 10 °C steps, and doubling three times gives 2 × 2 × 2 = 8 times the original rate.",
    },
    {
        "id": "ks4-factors-affecting-rate-h06",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reaction takes 80 s to finish at 20 °C. Using the 'roughly doubles every 10 °C' rule, predict roughly how long it would take at 50 °C.",
        "options": [
            "About 40 s",
            "About 20 s",
            "About 27 s",
            "About 10 s",
        ],
        "correct_index": 3,
        "why": "A 30 °C rise is three 10 °C steps, so the rate is about 8 times faster and the time falls to about 80 ÷ 8 = 10 s.",
    },
    {
        "id": "ks4-factors-affecting-rate-h07",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student wants to double the concentration of an acid by adding an equal extra volume of the same acid to the original solution, rather than by removing some of the water. Explain why the new mixture may not actually be twice as concentrated as intended.",
        "options": [
            "Concentration depends on the ratio of acid to the total volume, and adding more acid also increases that total volume rather than leaving it fixed",
            "Adding extra acid lowers the concentration, whatever volume it is added in",
            "Concentration can be doubled by heating the mixture, not by changing the amounts used though this does not match how the chemistry works in this particular case",
            "The new mixture is exactly twice as concentrated, because twice the acid was used",
        ],
        "correct_index": 0,
        "why": "Simply adding more acid increases both the amount of acid and the total volume at once, so the resulting concentration is not a clean doubling.",
    },
    {
        "id": "ks4-factors-affecting-rate-h08",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Four identical experiments are run at 10 °C, 20 °C, 30 °C and 40 °C, and the volume of gas collected in the first 10 s of each is recorded as 4 cm3, 9 cm3, 18 cm3 and 35 cm3. Determine which temperature gave the fastest initial rate.",
        "options": [
            "10 °C, because a cooler mixture reacts more predictably in the first few seconds",
            "40 °C, because it produced the most gas in the same fixed 10 s window",
            "20 °C, because it is the temperature closest to typical room conditions",
            "All four gave the same initial rate, since the differences are too small to matter",
        ],
        "correct_index": 1,
        "why": "The same 10 s window was used for each run, so the run producing the most gas in that time had the fastest initial rate.",
    },
    {
        "id": "ks4-factors-affecting-rate-h09",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain the shared reasoning behind why BOTH increasing the concentration of a solution and increasing the pressure of a gas increase reaction rate.",
        "options": [
            "Both changes lower the activation energy of the reaction by exactly the same amount",
            "Both changes raise the temperature of the reacting mixture, which is the true cause of the faster rate",
            "Both changes pack more particles into the same volume, which raises how often the reacting particles meet",
            "Both changes affect reactions that also involve a solid catalyst",
        ],
        "correct_index": 2,
        "why": "Concentration and pressure are really the same idea applied to a solution and to a gas: more particles in the same space means more frequent collisions.",
    },
    {
        "id": "ks4-factors-affecting-rate-h10",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A fixed amount of gas is compressed at constant temperature so that its volume is exactly halved. Predict roughly how the reaction rate changes.",
        "options": [
            "It roughly halves, because the particles have less room to move around in",
            "It stays roughly the same, since the amount of gas has not changed",
            "It roughly quadruples, because pressure effects on any gas reaction are squared",
            "It roughly doubles, because the same particles now occupy half the space",
        ],
        "correct_index": 3,
        "why": "Halving the volume roughly doubles the concentration of gas particles, which roughly doubles how often they collide.",
    },
    {
        "id": "ks4-factors-affecting-rate-h11",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reaction is timed at four concentrations: 0.5, 1.0, 2.0 and 4.0 mol/dm3, giving times of 80 s, 40 s, 20 s and 10 s. Determine whether this data supports time being roughly inversely proportional to concentration.",
        "options": [
            "Yes — each time the concentration doubles, the time taken roughly halves, right across the whole data set",
            "No — the time taken should stay exactly the same no matter the concentration, so this data must contain an error somewhere",
            "No — the times should have doubled alongside the concentration, not halved",
            "Yes, but for the first two readings; the pattern then breaks down for the last two",
        ],
        "correct_index": 0,
        "why": "Doubling the concentration halves the time in every step of this data, which is exactly what an inverse relationship looks like.",
    },
    {
        "id": "ks4-factors-affecting-rate-h12",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that the 'rate roughly doubles for every 10 °C rise' rule can be relied on to give an exact answer for any reaction.",
        "options": [
            "The claim is correct — every chemical reaction obeys this rule exactly, without exception",
            "The claim is too strong — the rule is only a rough guide, and how much a real reaction speeds up varies between reactions",
            "The claim is wrong the other way — no real reaction ever follows this rule even approximately under these conditions",
            "The claim applies to reactions between two gases, not to any other kind of reaction",
        ],
        "correct_index": 1,
        "why": "The doubling figure is a useful estimate, not a law, and different reactions speed up with temperature by different amounts.",
    },
    {
        "id": "ks4-factors-affecting-rate-h13",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain, in terms of surface area, why a build-up of fine sawdust inside an enclosed wood-working workshop is treated as a fire risk, while the same mass of solid wood is not.",
        "options": [
            "Sawdust is a completely different substance from solid wood, chemically, with a much lower ignition temperature than the wood it came from",
            "The enclosed workshop raises the concentration of oxygen well above its normal level in the air",
            "The sawdust exposes a huge surface area to the oxygen in the air, so it can combust almost all at once if ignited",
            "Solid wood cannot burn under any circumstances, unlike sawdust",
        ],
        "correct_index": 2,
        "why": "Spreading the same mass of wood into fine dust creates an enormous surface area, so far more of it can react with oxygen at once.",
    },
    {
        "id": "ks4-factors-affecting-rate-h14",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reaction between two gases is run first at 1 atmosphere and then at 3 atmospheres, all else identical. Predict roughly how the rate compares between the two runs.",
        "options": [
            "The rate at 3 atmospheres is roughly a third of the rate at 1 atmosphere",
            "The rate is unaffected, because pressure changes how much product forms, not how fast",
            "The rate at 3 atmospheres is roughly nine times as fast as the rate at 1 atmosphere",
            "The rate at 3 atmospheres is roughly three times the rate at 1 atmosphere",
        ],
        "correct_index": 3,
        "why": "Tripling the pressure roughly triples how many gas particles occupy the same volume, and so roughly triples the collision frequency.",
    },
    {
        "id": "ks4-factors-affecting-rate-h15",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reaction's concentration is doubled and its temperature is also raised by 10 °C at the same time, and each change on its own would roughly double the rate. Predict roughly how much faster the reaction becomes with both changes together.",
        "options": [
            "Roughly 4 times as fast",
            "Roughly 2 times as fast",
            "Roughly 6 times as fast",
            "Roughly 20 times as fast",
        ],
        "correct_index": 0,
        "why": "Each change roughly doubles the rate on its own, so making both changes together roughly multiplies the rate by 2 × 2 = 4.",
    },
    {
        "id": "ks4-factors-affecting-rate-h16",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A gas reaction is timed at three pressures: at 1 atmosphere it takes 20 s, at 2 atmospheres it takes 10 s, and at 3 atmospheres it takes about 6.7 s. Determine whether this supports time being roughly inversely proportional to pressure.",
        "options": [
            "No — the time should have doubled as the pressure doubled, not halved",
            "Yes — doubling the pressure roughly halves the time, and tripling it roughly divides the time by three",
            "No — pressure has no real relationship with the time a gas reaction takes whatever else is going on",
            "Yes, but between the first two readings, not the third",
        ],
        "correct_index": 1,
        "why": "20 ÷ 2 = 10 and 20 ÷ 3 ≈ 6.7, matching the times recorded, which is exactly what an inverse relationship predicts.",
    },
    {
        "id": "ks4-factors-affecting-rate-h17",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A report claims that using a greater surface area of reactant increased the total mass of product formed, and concludes that surface area increases the yield of the reaction. Identify the flaw in this conclusion.",
        "options": [
            "Surface area does increase yield, so the conclusion drawn is entirely correct",
            "The report must surely have used a completely different reactant altogether for the two surface areas being compared in this particular case",
            "For a reaction that goes to completion, surface area changes how fast the product forms, not how much of it is eventually made",
            "Yield can not be measured in a reaction that uses a solid reactant of any surface area",
        ],
        "correct_index": 2,
        "why": "As long as the same starting amounts are used, a complete reaction makes the same total product whatever its surface area — only the time taken changes.",
    },
    {
        "id": "ks4-factors-affecting-rate-h18",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "An exothermic reaction is run in two identical flasks: one insulated so it loses almost no heat, the other left uninsulated so heat escapes as the reaction proceeds. Predict how the rate in each flask changes as the reaction goes on.",
        "options": [
            "Both flasks behave identically, because insulation affects how warm the room around them becomes",
            "The uninsulated flask speeds up more, because losing heat increases a reaction's rate",
            "Neither flask changes temperature since exothermic reactions release their stored energy right at the very end of the reaction",
            "The insulated flask can heat itself up further and speed up as it goes, while the uninsulated one stays closer to its starting temperature",
        ],
        "correct_index": 3,
        "why": "An exothermic reaction releases heat as it proceeds, and an insulated flask keeps that heat, warming the mixture and pushing the rate up further still.",
    },
    {
        "id": "ks4-factors-affecting-rate-h19",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reaction takes 100 s at 0.2 mol/dm3, 50 s at 0.4 mol/dm3 and 25 s at 0.8 mol/dm3. Assuming the pattern continues, determine the concentration that would give a time of about 12.5 s.",
        "options": [
            "1.6 mol/dm3",
            "1.0 mol/dm3",
            "3.2 mol/dm3",
            "0.9 mol/dm3",
        ],
        "correct_index": 0,
        "why": "Each doubling of concentration halves the time in this data, so reaching 12.5 s needs one more doubling from 0.8 mol/dm3, giving 1.6 mol/dm3.",
    },
    {
        "id": "ks4-factors-affecting-rate-h20",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student wants to speed up the reaction between a large block of marble and dilute acid, but is not allowed to change the acid's concentration, temperature or pressure. Identify a change that would still work.",
        "options": [
            "Stir the mixture, since stirring is one of the four standard rate factors",
            "Break the marble block into smaller pieces before adding the acid",
            "Swap the acid for an identical volume of the same acid at a different concentration",
            "Warm the acid slightly before pouring it onto the marble",
        ],
        "correct_index": 1,
        "why": "Surface area is the one remaining factor of the four that can still be changed here, by breaking the marble into smaller pieces.",
    },
    {
        "id": "ks4-factors-affecting-rate-h21",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two students repeat an identical experiment — same concentration, same temperature setting on the water bath, and the same surface area of solid — but get times of 18 s and 31 s. Suggest the most likely explanation.",
        "options": [
            "One of the four rate factors must have had no effect in this particular reaction",
            "Rate experiments give wildly different results, however carefully every variable is controlled regardless of the other factors in this particular case",
            "The room, and so the starting temperature of one mixture, was probably not identical to the other, even with the same water bath setting",
            "The reaction must have produced a different product in each of the two repeats",
        ],
        "correct_index": 2,
        "why": "A water bath's dial setting does not guarantee the reaction mixture itself reached exactly the same temperature each time, so temperature is the likely uncontrolled factor.",
    },
    {
        "id": "ks4-factors-affecting-rate-h22",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Experiment P uses 1 g of marble chips in 10 cm3 of acid; experiment Q uses 10 g of the same size chips in 100 cm3 of the same acid, at the same temperature. Predict whether the initial rate per gram of marble is the same in both.",
        "options": [
            "No — experiment Q must react faster overall per gram, because there is simply more marble present in this situation",
            "No — experiment P must react faster per gram, because it uses a smaller total volume of acid",
            "This cannot be predicted without also knowing the exact shape of each individual chip",
            "Yes — the concentration of the acid and the surface-area-to-volume conditions are the same in both experiments",
        ],
        "correct_index": 3,
        "why": "Scaling both the marble and the acid up by the same factor keeps the concentration and the exposed surface area per gram the same, so the rate per gram matches.",
    },
    {
        "id": "ks4-factors-affecting-rate-h23",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "The same volume of a gas-phase reaction mixture, at the same temperature and pressure, is set up in a tall narrow vessel and in a short wide vessel of equal volume. Predict whether the rate differs between the two.",
        "options": [
            "The rate is the same in both, because rate depends on temperature, concentration, pressure and any catalyst surface, not on the shape of the container",
            "The tall narrow vessel reacts faster, because its particles have to travel a shorter distance to collide",
            "The short wide vessel reacts faster, because its much greater surface area of wall lets far more outside heat pass into the reacting mixture itself",
            "The rate cannot be compared unless both vessels are made from exactly the same material",
        ],
        "correct_index": 0,
        "why": "For a purely gas-phase reaction, none of the four rate factors depends on the shape of the vessel holding the same volume of gas.",
    },
    {
        "id": "ks4-factors-affecting-rate-h24",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A water bath is used to warm a reaction mixture from 20 °C up to 60 °C, in which the untreated mixture would have taken 320 s to finish. Identify the calculation that correctly estimates the new time, using the 'roughly doubles every 10 °C' rule.",
        "options": [
            "320 ÷ 8, since a 40 °C rise is four 10 °C steps and each step doubles the rate",
            "320 ÷ 16, since a 40 °C rise is four 10 °C steps and each step doubles the rate",
            "320 ÷ 4, since a 40 °C rise is four 10 °C steps and each step doubles the rate",
            "320 × 16, since a 40 °C rise is four 10 °C steps and each step doubles the rate",
        ],
        "correct_index": 1,
        "why": "Four 10 °C steps make the rate about 16 times faster, and dividing the original time by that same factor gives the new time.",
    },
    {
        "id": "ks4-factors-affecting-rate-h25",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student claims that, because increasing concentration and increasing pressure both work by packing more particles into the same volume, the two factors must always be interchangeable for any reaction. Evaluate this claim.",
        "options": [
            "It is entirely correct — every reaction, its reactants happen to be, has both a workable concentration and a workable pressure that can be changed to speed it right up",
            "It is wrong the other way — the two factors not share any reasoning in common",
            "It is too strong — concentration only applies where a reactant is dissolved in solution, and pressure only applies where a reactant is a gas, so a reaction with neither cannot use either factor",
            "It is correct for reactions that also use a catalyst",
        ],
        "correct_index": 2,
        "why": "The underlying idea is shared, but each factor only applies to the state of matter it describes, so they are not available for every reaction alike.",
    },
    {
        "id": "ks4-factors-affecting-rate-h26",
        "subtopic_slug": "factors-affecting-rate",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student compares magnesium reacting with acid to zinc reacting with the same acid, finds magnesium reacts faster, and concludes that the magnesium experiment must have been run at a higher temperature. Identify the flaw in this reasoning.",
        "options": [
            "The conclusion is correct, because a faster reaction means a higher starting temperature was used",
            "Magnesium and zinc must have been at exactly the same temperature, so no comparison of rate is possible",
            "The flaw is that zinc reacts faster than magnesium, not the other way round",
            "Comparing two different metals does not isolate any of the four rate factors, since the reactants themselves also differ in how reactive they are",
        ],
        "correct_index": 3,
        "why": "Only comparing the SAME reaction under different conditions isolates one rate factor; comparing two different metals changes the chemistry itself, not just a condition.",
    },
]
