"""Chemistry · Rates & Equilibrium — the MRB-338 expansion, subtopic
`reversible-reactions-equilibrium`.

The baseline twelve cover the ⇌ symbol, the closed-system requirement, the
NH4Cl and CuSO4 hydrate demonstrations, the exothermic/endothermic reverse
relationship, and the core "equal rates, not equal amounts" definition of
dynamic equilibrium. This file goes wider at the same, base-tier depth:
classifying named reactions as reversible or not, a second real everyday
example of an open system preventing equilibrium (a fizzy drink losing its
dissolved carbon dioxide), the particle-level picture at each end of the
NH4Cl tube, a limitation of the CuSO4 water test, and telling a chemical
reversible reaction apart from a purely physical change of state. ⚠️ Le
Chatelier and any shift in the POSITION of equilibrium belong only to
`effect-of-conditions-equilibrium`, which is higher tier — nothing here
discusses how a condition change moves an equilibrium, only whether one is
reached at all.
"""

TOPIC = "rates-equilibrium"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": "ks4-reversible-reactions-equilibrium-e05",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State whether most chemical reactions are reversible or irreversible.",
        "options": [
            "Most chemical reactions are irreversible; reversible ones are the exception rather than the rule",
            "Most chemical reactions are reversible; irreversible ones are the exception rather than the rule",
            "Exactly half of all chemical reactions are reversible, and half are irreversible under these particular conditions",
            "Whether a reaction is reversible cannot be known without testing it directly first in this particular case",
        ],
        "correct_index": 0,
        "why": "Reversible reactions such as the CuSO4 and NH4Cl examples are a special case; burning, rusting and most everyday reactions only go one way.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-e06",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State which type of reaction — rusting of iron, or the heating of hydrated copper sulfate — is reversible.",
        "options": [
            "Rusting of iron; heating copper sulfate cannot be reversed under normal conditions",
            "Only heating hydrated copper sulfate; rusting cannot be reversed under normal conditions",
            "Both reactions are reversible under normal conditions under the conditions described in this scenario",
            "Neither reaction is reversible under normal conditions here in this case either way as it stands",
        ],
        "correct_index": 1,
        "why": "Copper sulfate can be dehydrated and rehydrated over and over, while rust does not turn back into clean iron by itself.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-e07",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what type of particles are present at the hot end of a sealed tube where solid ammonium chloride has just been heated.",
        "options": [
            "Solid ammonium chloride, unchanged from before the tube was heated",
            "A liquid mixture of ammonia and hydrogen chloride under these particular conditions",
            "Ammonia and hydrogen chloride gas, since the solid has decomposed there",
            "Solid ammonia and solid hydrogen chloride, formed side by side in this particular case",
        ],
        "correct_index": 2,
        "why": "Heating decomposes the solid into the two gases, which is why no solid remains at the hot end.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-e08",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "An open glass of a fizzy drink slowly goes flat as its dissolved carbon dioxide escapes into the air. State why the reaction that puts fizz back into the drink cannot happen on its own once it is left open.",
        "options": [
            "Carbon dioxide can be added to a drink at the factory where it was originally made here in this case",
            "The drink is too cold for the carbon dioxide to redissolve into it once it has escaped",
            "Fizzy drinks do not involve any reversible reaction here in this case either way in this particular case",
            "The system is open, so the escaped carbon dioxide is not there to react back into the drink",
        ],
        "correct_index": 3,
        "why": "Once the gas has escaped into the open air it cannot react back with the drink, exactly as an open system prevents equilibrium being reached.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-e09",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the difference between a reversible CHEMICAL reaction, such as heating hydrated copper sulfate, and a reversible CHANGE OF STATE, such as melting and freezing water.",
        "options": [
            "The chemical reaction makes a new substance with different properties, while melting and freezing keep the same substance throughout",
            "There is no real difference; both are examples of the same kind of reversible process",
            "A change of state releases far more energy than any reversible chemical reaction",
            "A reversible chemical reaction can happen once, unlike melting and freezing under the conditions this scenario describes, whatever else is different",
        ],
        "correct_index": 0,
        "why": "Copper sulfate is chemically changed into a new substance with new properties, whereas melting or freezing water never stops it being water.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-e10",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the two conditions needed before dynamic equilibrium can be reached.",
        "options": [
            "The reaction must be exothermic, and it must be carried out at a high temperature",
            "The reaction must be reversible, and it must be in a closed system",
            "The reaction must involve at least one gas, and a catalyst must be present",
            "The reaction must be between two solutions, and a precipitate must form",
        ],
        "correct_index": 1,
        "why": "Without both the reaction being able to run both ways and nothing entering or leaving, the forward and reverse rates can never settle into balance.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-e11",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Identify which symbol shows that a reaction is reversible when it is written as a chemical equation.",
        "options": [
            "→",
            "=",
            "⇌",
            "+",
        ],
        "correct_index": 2,
        "why": "The double-headed arrow ⇌ shows that the reaction can proceed in either direction.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-e12",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what must be true of the concentrations of reactants and products once dynamic equilibrium has been reached.",
        "options": [
            "They become exactly equal to each other, and then stay that way",
            "They both fall steadily towards zero over time under these particular conditions",
            "They both rise steadily without ever levelling off under these particular conditions",
            "They stay constant, though they are not necessarily equal to each other",
        ],
        "correct_index": 3,
        "why": "Equilibrium means the forward and reverse rates are equal, which keeps concentrations constant — but that says nothing about them being equal to each other.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s05",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student is given a list of five reactions and asked to identify which are reversible: burning magnesium, rusting of iron, thermal decomposition of hydrated copper sulfate, neutralisation of an acid by an alkali, and the heating of solid ammonium chloride. Identify the two reversible reactions.",
        "options": [
            "The heating of hydrated copper sulfate, and the heating of solid ammonium chloride",
            "Burning magnesium, and rusting of iron under the conditions this scenario describes, whatever else is different",
            "Rusting of iron, and neutralisation of an acid by an alkali",
            "All five of the reactions listed are reversible",
        ],
        "correct_index": 0,
        "why": "Only the copper sulfate and ammonium chloride reactions reform their original substances; the other three only go one way.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s06",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe the full colour sequence you would see if blue hydrated copper sulfate crystals are heated strongly, left to cool, and then have a few drops of water added.",
        "options": [
            "Blue, then green on heating, then white once water is added in this particular case",
            "Blue, then white on heating, then blue again once water is added",
            "White throughout, since hydrated copper sulfate starts out colourless",
            "Blue, then black on heating, then blue again once water is added",
        ],
        "correct_index": 1,
        "why": "Heating drives off the water, turning the crystals white, and adding water back reforms the blue hydrated crystals.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s07",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain one limitation of using white anhydrous copper sulfate turning blue as a test for water.",
        "options": [
            "It detects water if the water is completely pure, with nothing dissolved in it in this particular case",
            "It can be used once, since the copper sulfate cannot be dehydrated a second time",
            "It shows that water is present, but does not tell you exactly how much water is there",
            "It works if the water is added while still boiling hot under the conditions described in this scenario",
        ],
        "correct_index": 2,
        "why": "The colour change confirms water is present, but a simple colour observation does not measure a precise quantity.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s08",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A sealed tube of ammonium chloride is heated at one end. Describe what would be observed if the tube were then opened immediately, before it had cooled down, rather than left to cool first.",
        "options": [
            "The solid would immediately reform inside the open tube, exactly as it would if the tube had been left closed",
            "Opening the tube would have no effect on the gases already inside it",
            "The gases would turn into a liquid the moment the tube was opened",
            "The gases would escape into the air and could no longer recombine to reform the solid at the cool end",
        ],
        "correct_index": 3,
        "why": "Opening the tube turns a closed system into an open one, letting the gases escape before they can react back together.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s09",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the general reaction X ⇌ Y + Z can reach dynamic equilibrium if run in a sealed flask, but not if run in an open beaker where Y is a gas that escapes.",
        "options": [
            "In the open beaker, Y escapes before it can react back with Z to reform X, so the reverse reaction cannot keep pace with the forward one",
            "The reaction runs in the forward direction in either container, the container's shape under the conditions described in this scenario",
            "A sealed flask contains more reactant than an open beaker does, whatever amounts were originally measured out here in this case either way as it stands",
            "Equilibrium depends on temperature, so the shape of the container makes no difference either way under the conditions described in this scenario",
        ],
        "correct_index": 0,
        "why": "For the reverse reaction to balance the forward one, nothing that took part can be allowed to leave the system.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s10",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A closed flask contains a reversible reaction where, at equilibrium, there is three times as much product as reactant, and these amounts stay constant. Explain what this shows about the forward and reverse reactions.",
        "options": [
            "The forward reaction has stopped completely, since there is so much more product than reactant left",
            "They are proceeding at equal rates, even though the amounts present are not equal to each other",
            "The reverse reaction must be running three times faster than the forward reaction",
            "The mixture has not yet reached equilibrium, since the amounts of reactant and product are unequal",
        ],
        "correct_index": 1,
        "why": "Constant, unequal amounts are exactly what equal forward and reverse rates look like — equilibrium concerns rates, not amounts.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s11",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student records the concentration of a product every minute in a closed flask: 0.10, 0.18, 0.24, 0.28, 0.30, 0.30, 0.30 mol/dm3. Determine at which reading dynamic equilibrium was reached.",
        "options": [
            "At the first reading, 0.10 mol/dm3, since that is when the reaction started under these particular conditions",
            "Equilibrium is not reached, since the concentration keeps rising throughout under these particular conditions",
            "At the fifth reading, 0.30 mol/dm3, since the concentration stops changing from that point on",
            "At the third reading, 0.24 mol/dm3, since that is roughly halfway through the data",
        ],
        "correct_index": 2,
        "why": "Equilibrium is shown by the concentration becoming constant, which first happens at the fifth reading here.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s12",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why doubling the size of the sealed flask used for a reversible reaction, while keeping everything else the same, does not stop equilibrium from eventually being reached.",
        "options": [
            "A bigger flask reaches equilibrium sooner than a smaller one, whatever else is true",
            "Equilibrium can be reached in a flask of one exact size, the reaction",
            "The size of the flask determines whether the reaction is reversible in the first place under the conditions described in this scenario",
            "The flask is still a closed system, so nothing escapes and the forward and reverse reactions can still balance out over time",
        ],
        "correct_index": 3,
        "why": "What matters for reaching equilibrium is that the system stays closed, not how big the container happens to be.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s13",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student says that once a reversible reaction has 'finished', nothing further happens inside the flask. Explain why the word 'finished' is misleading here.",
        "options": [
            "At equilibrium the forward and reverse reactions are still both happening, just at equal rates, so the reaction has not really stopped",
            "The word is not misleading — a reversible reaction does stop once equilibrium is reached",
            "The reaction continues if it is exothermic; endothermic reversible reactions do stop",
            "The forward reaction stops, but the reverse reaction keeps going once equilibrium is reached under the conditions described in this scenario",
        ],
        "correct_index": 0,
        "why": "Dynamic equilibrium means both directions are still running — it only looks finished because nothing net seems to change.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s14",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why heating hydrated copper sulfate in an open test tube, rather than a sealed one, still successfully produces the white anhydrous solid, even though no equilibrium is reached.",
        "options": [
            "Equilibrium is not needed for any reaction to take place reversible or otherwise",
            "The water vapour driven off simply escapes into the air, so the forward reaction can run to completion without ever needing to balance against the reverse",
            "The open test tube behaves as a closed system for this particular reaction",
            "The reverse reaction happens faster in an open tube, which is why the forward reaction can still finish",
        ],
        "correct_index": 1,
        "why": "Without the water vapour trapped to react back, the dehydration simply goes to completion rather than settling into a balance.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s15",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A sealed flask starts with pure reactant only. Describe how the rate of the forward reaction changes as the reaction proceeds towards equilibrium.",
        "options": [
            "It rises steadily throughout, without ever levelling off under the conditions described in this scenario",
            "It stays exactly constant from the very first moment the reactants are mixed",
            "It falls, as reactant is gradually used up, until it matches the rising reverse rate",
            "It falls to zero, showing that the forward reaction has completely stopped in this particular case",
        ],
        "correct_index": 2,
        "why": "As reactant is used up there is less of it left to react, so the forward rate falls until it matches the reverse rate at equilibrium.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s16",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why melting ice cannot be classed as an example of the kind of reversible reaction studied in this topic, even though it can clearly be reversed by freezing the water again.",
        "options": [
            "Melting ice can not be reversed, unlike the reactions studied in this topic",
            "Ice melts in an open system, so equilibrium could not be reached in any case under the exact conditions this scenario describes, whatever else about it differs",
            "Freezing water back into ice releases far more energy than it took to melt it",
            "Melting and freezing are changes of state, not chemical reactions — no new substance with different chemical properties is ever formed",
        ],
        "correct_index": 3,
        "why": "A reversible chemical reaction produces a genuinely different substance; melting and freezing water never changes what substance it is.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s17",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a sealed, rigid flask is described as a closed system even though it clearly has walls that could, in principle, be opened.",
        "options": [
            "What matters is that nothing enters or leaves WHILE the reaction is taking place, not that the flask could never be opened at all",
            "A flask counts as closed if it is physically impossible to open under any circumstances",
            "A sealed flask is a closed system if the reaction inside it is exothermic under the exact conditions this scenario describes, whatever else about it differs",
            "Whether a flask counts as closed depends entirely on how big it is, not on whether it is sealed",
        ],
        "correct_index": 0,
        "why": "It is the behaviour DURING the reaction that defines a closed system, not some permanent, unopenable property of the container.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s18",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student mixes reactants for a reversible reaction in a sealed flask and immediately measures the concentrations after just one second. Explain why this single reading cannot show whether equilibrium has been reached.",
        "options": [
            "One second is too short a time for any reversible reaction to begin reacting",
            "A single reading cannot show whether the concentration is still changing; only readings taken over time can show that it has become constant",
            "Equilibrium can be detected by measuring temperature, not by measuring concentration",
            "A sealed flask needs at least an hour before any reading can be trusted",
        ],
        "correct_index": 1,
        "why": "Spotting equilibrium needs a comparison over time, since it is defined by concentrations no longer changing, not by any single value.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s19",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why writing 'NH4Cl(s) → NH3(g) + HCl(g)' with a single forward arrow, rather than ⇌, would be a misleading way to represent this reaction.",
        "options": [
            "A single arrow is used for reactions between two gases, not for reactions producing a solid under the conditions described in this scenario",
            "A single arrow is simply a shorter way of writing the same equation, with no real difference in meaning",
            "A single arrow implies the reaction only ever goes forward, when the gases are actually known to recombine into the solid again on cooling",
            "A single arrow would be correct here, since ammonium chloride's decomposition cannot be reversed",
        ],
        "correct_index": 2,
        "why": "A single arrow suggests the reaction cannot run backwards, which is exactly wrong for a reaction known to reform its starting solid on cooling.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s20",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A sealed flask reaches equilibrium, and a student then takes a single snapshot measurement showing more reactant than product present. Explain why this alone does not mean the forward reaction is 'losing' to the reverse reaction.",
        "options": [
            "The forward reaction is losing whenever there is more reactant present than product at equilibrium",
            "The reverse reaction must have a much higher activation energy than the forward reaction in every such case under the conditions this scenario describes, whatever else is different",
            "This situation can not occur once equilibrium has been reached",
            "At equilibrium, the amounts present are simply whatever makes the two rates equal — it says nothing about one reaction somehow winning over the other",
        ],
        "correct_index": 3,
        "why": "Which side happens to have more material at equilibrium tells you nothing about the reactions 'competing' — only that the two rates have balanced there.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s21",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why testing an unknown colourless liquid with white anhydrous copper sulfate, and seeing no colour change at all, suggests the liquid contains no water.",
        "options": [
            "The colour change relies on water reacting with the anhydrous salt, so no change suggests no water was present to react",
            "Anhydrous copper sulfate changes colour in the presence of a coloured liquid, not a colourless one",
            "A colourless liquid can not contain any water, the test shows under the conditions this scenario describes, whatever else is different",
            "The test works on liquids that are already known to be water beforehand",
        ],
        "correct_index": 0,
        "why": "The test relies specifically on water reacting with the anhydrous salt, so no colour change is evidence that no water reacted.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s22",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why burning a piece of paper is classed as irreversible, while heating hydrated copper sulfate is classed as reversible, in terms of what happens to the products.",
        "options": [
            "Burning paper does not produce any new substances, unlike heating copper sulfate",
            "The gases from burnt paper escape and cannot be recombined into paper, whereas the water driven from copper sulfate can be added back to reform the original hydrate",
            "Copper sulfate cannot be described as reversible either, once examined closely enough",
            "Burning paper releases far less energy than heating copper sulfate does",
        ],
        "correct_index": 1,
        "why": "Copper sulfate's water can be put back to reform the original substance, but the gases from burnt paper are gone for good.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s23",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A closed flask holds a reversible reaction that has just been set up from pure reactant. Explain why the reverse reaction rate is zero at the very first instant.",
        "options": [
            "The reverse reaction is zero throughout the whole of any reversible reaction, at every stage",
            "The forward reaction must also be zero at the very first instant, for the same reason under these particular conditions",
            "No product has yet formed for the reverse reaction to act on, so it cannot proceed until some product exists",
            "The flask must not be a closed system if the reverse rate starts at zero under the conditions described in this scenario",
        ],
        "correct_index": 2,
        "why": "With no product present yet, there is nothing for the reverse reaction to convert back, so its rate starts at zero.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s24",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why chemists usually describe reaching equilibrium as a state that a system 'settles into', rather than an instant at which the reaction suddenly stops changing.",
        "options": [
            "Equilibrium is reached the moment the reactants are first mixed together, before any reaction has even started in this particular case",
            "Equilibrium is a fixed point in time that is the same for every reversible reaction, the conditions in this particular case",
            "The system settles into equilibrium once every last trace of reactant has disappeared completely in this particular case",
            "The forward and reverse rates approach each other gradually over time, rather than becoming equal in one sudden step",
        ],
        "correct_index": 3,
        "why": "The two rates draw closer together as concentrations shift, arriving at balance gradually rather than all at once.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s25",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A teacher asks a class to name a reversible reaction other than the two studied in class. A student suggests dissolving salt in water, then evaporating the water to get the salt back. Explain why this is not a good example for this topic.",
        "options": [
            "Dissolving and evaporating are physical changes, not a chemical reaction — the salt is never changed into a different substance",
            "Salt dissolving in water can not be reversed by evaporation under any circumstances under the conditions described in this scenario",
            "This is an excellent example, since it fits the definition of a reversible reaction perfectly",
            "Dissolving counts as reversible if it happens inside a sealed flask rather than an open beaker under the conditions described in this scenario",
        ],
        "correct_index": 0,
        "why": "The salt itself never changes chemically when it dissolves, so this is a physical process rather than a reversible chemical reaction.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-s26",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a reversible reaction run in a sealed flask eventually stops SHOWING any further visible change, even though the reaction has not actually stopped.",
        "options": [
            "The reaction does stop completely once no further visible change can be seen",
            "Once equilibrium is reached, the forward and reverse reactions keep the concentrations constant, so nothing visible appears to be changing any more",
            "Visible change occurs during the reverse reaction, not during the forward one",
            "A sealed flask prevents any visible change from being observed at any stage",
        ],
        "correct_index": 1,
        "why": "Constant concentrations give the appearance of a finished reaction, even though both directions are still actively taking place.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h05",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A sealed flask contains a reversible reaction that has reached equilibrium. A student then opens the flask briefly, allowing some of the gaseous product to escape, before resealing it. Predict what happens next inside the flask.",
        "options": [
            "Nothing changes since the flask has been resealed and is once again a closed system",
            "The reaction stops permanently, since briefly opening the flask destroys its ability to reach equilibrium ever again",
            "The reaction moves away from its old equilibrium and eventually settles into a new one, since some product has now been removed",
            "The forward reaction stops completely, leaving the reverse reaction still running under the conditions this scenario describes, whatever else is different",
        ],
        "correct_index": 2,
        "why": "Removing some product disturbs the previous balance, so the forward and reverse rates shift and settle into a new equilibrium once the flask is sealed again.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h06",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two identical sealed flasks are set up with the same reversible reaction: flask P from pure reactant, flask Q from pure product, both at the same temperature. Predict how their final compositions at equilibrium compare.",
        "options": [
            "Flask P ends up with more product, since it started with reactant in this particular case",
            "Flask Q ends up with more product, since it started with product under these particular conditions",
            "Flask P can reach equilibrium, since it starts from the reactant side",
            "Both reach the same equilibrium composition, approached from opposite starting points",
        ],
        "correct_index": 3,
        "why": "Equilibrium is a balance point fixed by the conditions, so the same flask reaches the same composition whichever side it is approached from.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h07",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student argues that a reversible reaction in a closed system must always end up with exactly equal amounts of reactant and product, since 'reversible means balanced'. Evaluate this argument.",
        "options": [
            "It is wrong — 'balanced' refers to the forward and reverse RATES being equal, not the amounts of reactant and product present",
            "It is correct — every reversible reaction reaches equal amounts of reactant and product without exception",
            "It is correct for reactions that are exothermic overall",
            "It is wrong the other way — a reversible reaction can not end up with equal amounts of reactant and product under these particular conditions",
        ],
        "correct_index": 0,
        "why": "Equilibrium balances RATES, and the amounts that give that balance can come out equal, unequal, or heavily one-sided depending on the reaction.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h08",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A sealed flask contains a reversible reaction at equilibrium. A tiny radioactive label is added to a small number of the reactant particles, and later, some of that label is found among the product particles too, even though the total concentrations have not changed at all. Explain what this shows.",
        "options": [
            "The experiment must be flawed, since concentrations cannot stay constant if particles are moving between the two sides",
            "The forward and reverse reactions are still actively happening at equilibrium, exchanging particles even though the overall concentrations stay fixed",
            "The reaction has stopped completely, and the labelled particles must have moved by some other means entirely",
            "Radioactive labelling disturbs a reversible reaction so much that its equilibrium is destroyed under the conditions this scenario describes, whatever else is different",
        ],
        "correct_index": 1,
        "why": "Labelled particles crossing over while total concentrations stay constant is direct evidence that both reactions are still running at equilibrium.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h09",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a chemist investigating a new reaction would need to check both that it can run in reverse AND that it is being carried out in a closed system, before claiming it has reached equilibrium — rather than checking just one of these two things.",
        "options": [
            "Checking either condition on its own is sufficient to prove a reaction has reached equilibrium",
            "A closed system alone guarantees equilibrium, the reaction is doing inside it",
            "A reaction that cannot reverse will simply run to completion in an open OR closed system, and a reversible reaction in an open system will still run to completion as products escape — equilibrium needs both conditions together",
            "Reversibility alone guarantees equilibrium, whatever container the reaction happens to be in",
        ],
        "correct_index": 2,
        "why": "Missing either condition removes the possibility of a balance being reached, so both have to be checked, not just one.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h10",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reversible reaction is set up in a sealed flask, and a student notices the colour of the mixture stops changing after ten minutes. They conclude equilibrium has definitely been reached. Evaluate this conclusion.",
        "options": [
            "It is certainly correct, since any stopped colour change proves equilibrium has been reached",
            "It is certainly wrong, since colour can not be used as evidence for reaching equilibrium",
            "It cannot be evaluated without first knowing the exact temperature of the flask under the exact conditions this scenario describes, whatever else about it differs",
            "It is a reasonable but not certain conclusion — a genuinely very slow further change could still be occurring too slowly to notice by eye",
        ],
        "correct_index": 3,
        "why": "A visible colour levelling off is good evidence, but a very slow ongoing change could still escape detection by eye alone.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h11",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a chemist cannot tell, just by looking at the FINAL equilibrium mixture of a reversible reaction, whether it was approached from the reactant side, the product side, or a mixture of both.",
        "options": [
            "The same equilibrium composition is reached regardless of the starting point, so the final mixture carries no record of which side it began from",
            "The final mixture looks completely different depending on which side the reaction started from",
            "A mixture can reach equilibrium if it starts from the reactant side in the first place",
            "The reaction reaches a genuine equilibrium if it started from an exact 50:50 mixture of reactant and product under the conditions described in this scenario",
        ],
        "correct_index": 0,
        "why": "Because the same balance point is reached from any starting composition, the final mixture cannot reveal where it started from.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h12",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student proposes that any reaction which appears to 'stop' before all the reactant is used up must be a reversible reaction at equilibrium. Evaluate this proposal.",
        "options": [
            "It is entirely correct — leftover reactant is explained by a reversible reaction at equilibrium",
            "It is too strong — a reaction can also simply run out of a different, limiting reactant, or genuinely stop for other reasons unrelated to equilibrium",
            "It is entirely wrong — a reversible reaction at equilibrium can not leave any reactant unreacted",
            "It applies to reactions that release energy overall",
        ],
        "correct_index": 1,
        "why": "Leftover reactant has more than one possible explanation, so 'appears to stop early' is not, by itself, proof of equilibrium.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h13",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why, in principle, the reaction 2H2O(l) ⇌ 2H2(g) + O2(g) sealed in a rigid flask could in theory reach equilibrium, whereas the same reaction run in an open beaker never could, however long it is left.",
        "options": [
            "Water can split into hydrogen and oxygen inside a sealed flask, not inside an open beaker",
            "The open beaker reaches equilibrium faster than the sealed flask does, since gases can move more freely",
            "In the sealed flask the gases are trapped and can react back with each other, while in the open beaker they simply escape and are lost",
            "Hydrogen and oxygen gases can not recombine to reform water under any circumstances under the conditions this scenario describes, whatever else is different",
        ],
        "correct_index": 2,
        "why": "Trapping the gases lets the reverse reaction draw on them, which an open beaker simply cannot offer once they have escaped.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h14",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A sealed flask holds a reversible reaction at equilibrium. A student adds a catalyst and observes that the concentrations of reactant and product do not change at all afterwards. Explain why this observation does not mean the catalyst had no effect whatsoever.",
        "options": [
            "The catalyst must be faulty, since a working catalyst should change the concentrations present at equilibrium",
            "This observation proves the flask cannot have been a closed system in the first place",
            "A catalyst can be added before a reaction starts, not once equilibrium has already been reached",
            "The catalyst could still have sped up how quickly the original equilibrium was reached, even though it leaves an already-settled equilibrium's concentrations unchanged",
        ],
        "correct_index": 3,
        "why": "A catalyst speeds up how fast a balance is reached — adding one once the balance already exists leaves that balance itself undisturbed.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h15",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a chemist testing whether a newly-discovered reaction is reversible would want to try starting from the PRODUCT side as well as from the reactant side.",
        "options": [
            "If starting from pure product also produces some reactant, that is direct evidence the reverse reaction genuinely takes place, confirming reversibility",
            "Starting from the product side is the way to observe the forward reaction taking place",
            "A reaction can be confirmed reversible if it is first shown to be exothermic in the forward direction",
            "Testing from the product side is unnecessary, since every reaction that forms a product is automatically reversible under the conditions described in this scenario",
        ],
        "correct_index": 0,
        "why": "Seeing reactant reappear from pure product is the clearest possible evidence that the reverse reaction genuinely happens.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h16",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A sealed flask containing a reversible reaction is left for a week. A student argues that because nothing visible has changed for days, the reaction must have used up all of one reactant completely. Evaluate this argument.",
        "options": [
            "It must be correct, since a reversible reaction uses up all of one reactant eventually",
            "It does not follow — constant concentrations are equally well explained by dynamic equilibrium, with both reactant and product still present",
            "It cannot be evaluated, since reversible reactions not produce any visible change in the first place under the conditions described in this scenario",
            "It is correct if the flask has also been heated at some point during the week",
        ],
        "correct_index": 1,
        "why": "Constant concentrations are exactly what dynamic equilibrium looks like, so 'used up completely' is not the only possible explanation.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h17",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why removing the requirement for a closed system would make the entire idea of dynamic equilibrium meaningless for a reaction where at least one product is a gas.",
        "options": [
            "Dynamic equilibrium does not require the forward and reverse rates to be equal in the first place",
            "A reaction without a closed system simply proceeds twice as fast as one that is properly sealed",
            "The escaping gas could never build up enough concentration for the reverse reaction to match the forward one, so the two rates could never actually balance",
            "Removing a closed system matters for reactions that do not involve any gas",
        ],
        "correct_index": 2,
        "why": "Without the gas building up, the reverse reaction has nothing to work with, so the two rates can never settle into a lasting balance.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h18",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A teacher demonstrates the CuSO4 hydrate cycle five times in a row on the same sample, heating and rehydrating it each time. Explain why this repeatability is good evidence that the reaction is a genuine reversible chemical reaction, rather than the sample simply being replaced each time.",
        "options": [
            "Repeatability proves nothing about whether a reaction is reversible",
            "The sample must be a completely different chemical each time it changes colour",
            "This shows the reaction is reversible if the sample also changes mass with every repeat",
            "The very same sample keeps switching back and forth between two distinct forms, which is exactly the behaviour a reversible reaction predicts",
        ],
        "correct_index": 3,
        "why": "One sample cycling between two forms over and over is strong evidence of a genuine, repeatable reversible reaction rather than a one-off event.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h19",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the statement 'a reversible reaction reaches equilibrium' is more precise than the statement 'a reversible reaction stops changing'.",
        "options": [
            "The first statement correctly describes rates becoming equal while both reactions continue; the second wrongly implies all reaction has ceased",
            "The two statements mean exactly the same thing, so neither is more precise than the other",
            "The second statement is the more precise of the two, since it focuses on what can be observed",
            "Neither statement is accurate, since a reversible reaction fails to settle into any stable state",
        ],
        "correct_index": 0,
        "why": "'Stops changing' misleadingly suggests the reaction has ended, while 'reaches equilibrium' correctly captures that both directions are still ongoing.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h20",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A sealed flask holds a reversible reaction at equilibrium with far more product than reactant present. A student argues this proves the reverse reaction must be very slow. Evaluate this claim.",
        "options": [
            "It is correct — more product than reactant means the reverse reaction is the slower of the two",
            "It does not follow — at equilibrium the two rates are equal regardless of the amounts present, so a large excess of product does not by itself say anything about how slow either rate is",
            "It is correct if the reaction is also known to be exothermic overall",
            "It cannot be evaluated without knowing the temperature of the flask",
        ],
        "correct_index": 1,
        "why": "Equal rates can occur at any ratio of amounts, so the amounts present at equilibrium do not, alone, reveal anything about how fast either rate actually is.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h21",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why chemists studying reversible reactions usually prefer a rigid, sealed container over a flexible one that can expand, when a gas is involved.",
        "options": [
            "A flexible container can not be sealed, so it can not behave as a closed system",
            "Gases cannot take part in any reversible reaction unless the container is rigid",
            "A rigid, sealed container keeps the volume fixed as well as keeping the system closed, avoiding an extra variable that could complicate the reaction",
            "A rigid container speeds up how quickly equilibrium is reached, compared with a flexible one",
        ],
        "correct_index": 2,
        "why": "Fixing the volume as well as sealing the system keeps conditions simpler to interpret, without an expanding or contracting container adding another variable.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h22",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student claims that because NH4Cl(s) ⇌ NH3(g) + HCl(g) is reversible, heating ANY solid must also produce a reversible reaction. Evaluate this generalisation.",
        "options": [
            "It is correct, since heating any solid produces gases that can recombine on cooling",
            "It is correct for solids that are white before being heated",
            "It is correct, because reversibility is a property shared by every thermal decomposition without exception under these particular conditions",
            "It is unjustified — reversibility depends on the specific reaction and its products, not on the general fact of heating a solid",
        ],
        "correct_index": 3,
        "why": "Whether a reaction is reversible depends on that specific reaction's chemistry, not on the broad category of 'heating a solid'.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h23",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A sealed flask contains a reversible reaction at equilibrium. Explain why simply waiting much longer, without changing anything else about the flask, would not change the concentrations present.",
        "options": [
            "At equilibrium the forward and reverse rates are already matched, so waiting longer under unchanged conditions leaves that balance exactly where it is",
            "Waiting longer causes the reaction to run further towards completion, however long equilibrium has already been established",
            "A reversible reaction can stay at equilibrium for a fixed, limited length of time before it changes again",
            "The flask would need to be reheated periodically to keep the concentrations from changing over time under the exact conditions this scenario describes, whatever else about it differs",
        ],
        "correct_index": 0,
        "why": "Once the rates are equal, nothing about simply letting more time pass under the same conditions disturbs that balance.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h24",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student is shown two sealed flasks, both containing the same reversible reaction and both described as 'at equilibrium', but with visibly different colours from each other. Explain how this can be correct.",
        "options": [
            "This cannot be correct — two flasks at equilibrium for the same reaction must look identical to each other here in this case either way as it stands in this particular case",
            "The two flasks could simply have been set up with different starting amounts or at different temperatures, each settling into its own equilibrium composition",
            "One of the two flasks can be at equilibrium; the other must still be reacting",
            "Colour has no connection to concentration, so this observation says nothing meaningful regardless",
        ],
        "correct_index": 1,
        "why": "Different starting conditions can settle into different equilibrium compositions, so two flasks can both be genuinely at equilibrium and still look different.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h25",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why 'reversible' describes a property of the REACTION itself, while 'at equilibrium' describes a state that a particular closed sample of it may or may not currently be in.",
        "options": [
            "The two terms mean exactly the same thing and can be used interchangeably under the conditions described in this scenario",
            "A reaction can be described as reversible once it has already reached equilibrium at least once under these particular conditions",
            "A reaction can be reversible in principle without any given sample of it having actually reached a balance of rates yet",
            "'At equilibrium' describes the reaction itself, while 'reversible' describes the state of one particular sample in this particular case",
        ],
        "correct_index": 2,
        "why": "Reversibility is a fixed fact about the reaction, whereas any one sample of it might still be on its way to equilibrium rather than there yet.",
    },
    {
        "id": "ks4-reversible-reactions-equilibrium-h26",
        "subtopic_slug": "reversible-reactions-equilibrium",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Summarise why a student who can correctly state 'equal rates, not equal amounts' has captured the single most important idea in this entire topic.",
        "options": [
            "It is simply a restatement of the closed-system requirement, with no further meaning beyond that",
            "It applies to the specific NH4Cl and CuSO4 examples, not to reversible reactions in general under the conditions this scenario describes, whatever else is different",
            "It describes what happens before equilibrium is reached, rather than what happens once it has been",
            "It distinguishes dynamic equilibrium from every common misconception about a reaction simply 'stopping' or settling into equal quantities",
        ],
        "correct_index": 3,
        "why": "Almost every misconception in this topic comes from confusing equal AMOUNTS with equal RATES, which this phrase directly corrects.",
    },
]
