"""Chemistry · Using resources — the MRB-338 expansion for `earths-resources`.

The shipped rows already own the renewable/non-renewable sort, the finite
definition and the sustainable-development misconception, so the weight here
falls on the material the spec point has and those rows did not touch: the
named resources themselves (bauxite, limestone, rock salt, latex, liquid air),
the timescales that make a resource finite, and green chemistry with numbers.

Atom economy carries most of the calculation load because it is the one place
this spec point supplies clean arithmetic — a definition, a rearrangement and a
distinction from percentage yield. The harder band is mostly evaluation: a
reserve against a resource, ore grade against tonnage, and the standing
tension that renewable energy technology is itself built from mined metals.
"""

TOPIC = "resources"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": "ks4-earths-resources-e06",
        "subtopic_slug": "earths-resources",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what is meant by a natural resource.",
        "options": [
            "A material or energy source obtained from the natural environment",
            "A material made in a factory from simpler chemical substances",
            "A material that has been recovered from household waste and cleaned for reuse",
            "A material that contains a single element rather than any compound",
        ],
        "correct_index": 0,
        "why": "A natural resource is anything useful taken from the Earth, the "
               "sea, the air or living things, before any manufacturing.",
    },
    {
        "id": "ks4-earths-resources-e07",
        "subtopic_slug": "earths-resources",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Bauxite is mined in large quantities. Which metal is obtained from it?",
        "options": [
            "Iron, which is the metal found in the ore haematite",
            "Copper, which is the metal found in the ore malachite",
            "Titanium, which is the metal found in the ore rutile",
            "Aluminium, which is the metal found in the ore bauxite",
        ],
        "correct_index": 3,
        "why": "Bauxite is an aluminium ore, containing mainly aluminium oxide "
               "mixed with other rock.",
    },
    {
        "id": "ks4-earths-resources-e08",
        "subtopic_slug": "earths-resources",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the process used to separate nitrogen and oxygen from the air.",
        "options": [
            "Filtration of the air through a fine porous membrane",
            "Fractional distillation of the air after it is liquefied",
            "Electrolysis of the air using two inert carbon electrodes",
            "Crystallisation of the air by cooling it slowly in a dish",
        ],
        "correct_index": 1,
        "why": "Air is cooled until it liquefies, then warmed slowly so the gases "
               "boil off separately at their different boiling points.",
    },
    {
        "id": "ks4-earths-resources-e09",
        "subtopic_slug": "earths-resources",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State approximately how long coal, oil and natural gas took to form.",
        "options": [
            "A few hundred years, which is why supplies are being replaced",
            "A few thousand years, which is why new deposits keep appearing",
            "Many millions of years, which is why supplies are not replaced",
            "A few decades, which is why the deposits are so widespread",
        ],
        "correct_index": 2,
        "why": "Fossil fuels formed from buried organisms over many millions of "
               "years, so they are used far faster than they are made.",
    },
    {
        "id": "ks4-earths-resources-e10",
        "subtopic_slug": "earths-resources",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which of these is a renewable feedstock for making a plastic?",
        "options": [
            "Coal that has been ground into a fine powder",
            "Natural gas piped from an offshore gas field",
            "Naphtha separated from a barrel of crude oil",
            "Starch harvested from a crop of maize plants",
        ],
        "correct_index": 3,
        "why": "Maize is grown again each season, so starch is replaced as fast as "
               "it is used; the other three are finite fossil resources.",
    },
    {
        "id": "ks4-earths-resources-e11",
        "subtopic_slug": "earths-resources",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Natural rubber is made from latex. State where latex is obtained.",
        "options": [
            "It is tapped from the trunks of rubber trees",
            "It is pumped from deep underground oil wells",
            "It is dredged from the sediment of river beds",
            "It is condensed from the steam of hot springs",
        ],
        "correct_index": 0,
        "why": "Latex is a milky sap collected by cutting the bark of a rubber "
               "tree, which makes natural rubber a biological resource.",
    },
    {
        "id": "ks4-earths-resources-e12",
        "subtopic_slug": "earths-resources",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which resource is obtained by quarrying rock at the surface?",
        "options": [
            "Natural gas, which is drawn up to the surface through a well drilled into rock",
            "Nitrogen, which is drawn out of the surrounding air",
            "Latex, which is drawn from the bark of a living tree",
            "Limestone, which is broken out of a bed of sedimentary rock",
        ],
        "correct_index": 3,
        "why": "Limestone lies in thick beds near the surface, so it is quarried "
               "rather than drilled for or extracted from air.",
    },
    {
        "id": "ks4-earths-resources-s07",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a metal ore is classed as a finite resource.",
        "options": [
            "Ore bodies formed over geological time and are not being replaced as they are mined",
            "Ore bodies lose their metal content steadily once the rock is exposed to the weather",
            "Ore bodies contain metal compounds rather than the pure metal that industry needs",
            "Ore bodies are spread thinly through the crust rather than gathered in one place",
        ],
        "correct_index": 0,
        "why": "The rate at which new ore forms is negligible compared with the "
               "rate at which it is mined, so the supply only falls.",
    },
    {
        "id": "ks4-earths-resources-s08",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Sustainable development requires three demands to be balanced. Which set names them?",
        "options": [
            "Reaction rate, percentage yield and the purity of the final product",
            "Economic growth, protection of the environment and fairness to people",
            "Mass, energy and charge, since each of the three must be conserved",
            "Extraction, manufacture and disposal, the three stages of a product",
        ],
        "correct_index": 1,
        "why": "Development that meets present needs without denying future ones "
               "has to weigh livelihoods, ecosystems and social fairness together.",
    },
    {
        "id": "ks4-earths-resources-s09",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how adding a catalyst to an industrial process reduces the energy it uses.",
        "options": [
            "It supplies energy directly to the reacting particles, so much less fuel has to be burnt",
            "It raises the yield of the reaction, so the same mass needs fewer batches",
            "It gives a fast enough rate at a lower temperature, so less heating is needed",
            "It lowers the mass of reactant needed, so less material has to be warmed",
        ],
        "correct_index": 2,
        "why": "A catalyst provides an alternative pathway of lower activation "
               "energy, so an acceptable rate is reached at a lower temperature.",
    },
    {
        "id": "ks4-earths-resources-s10",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Calcium carbonate decomposes to calcium oxide and carbon dioxide. Relative formula masses are CaCO3 = 100 and CaO = 56. Calculate the atom economy for calcium oxide.",
        "options": [
            "44%, the share of the starting mass that leaves as the waste gas",
            "56%, the share of the starting mass that ends up as calcium oxide",
            "78%, the mean of the two relative formula masses given in the stem",
            "179%, found by dividing the larger mass by the smaller mass given",
        ],
        "correct_index": 1,
        "why": "Atom economy is the mass of the desired product as a percentage of "
               "the total reactant mass: 56 divided by 100 is 56%.",
    },
    {
        "id": "ks4-earths-resources-s11",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A plastic made from crude oil is designed to biodegrade. A student says this makes it a renewable feedstock. Explain the error.",
        "options": [
            "The feedstock is still crude oil, which is finite however the product behaves",
            "The plastic will biodegrade too slowly for the label to be worth using",
            "A plastic that biodegrades cannot be made from a crude oil feedstock in the first place",
            "The feedstock counts as renewable from the moment the plastic has decayed",
        ],
        "correct_index": 0,
        "why": "Whether a feedstock is renewable depends on where the raw material "
               "came from, not on what happens to the product after use.",
    },
    {
        "id": "ks4-earths-resources-s12",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why replacing a scarce metal in a product with a more abundant one supports sustainability.",
        "options": [
            "The abundant metal will have a lower density, so less mass is needed",
            "The abundant metal can be extracted without using any energy in the process",
            "Demand moves away from a reserve that is close to being exhausted",
            "The scarce metal becomes renewable once demand for it has fallen",
        ],
        "correct_index": 2,
        "why": "Switching demand to a plentiful material leaves the small reserve "
               "for uses where nothing else will do.",
    },
    {
        "id": "ks4-earths-resources-s13",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Forest is cleared to create farmland. Describe the effect on the amount of carbon dioxide in the atmosphere.",
        "options": [
            "It falls, because the crops planted afterwards photosynthesise much faster than trees",
            "It rises, because fewer trees are left to take the gas in by photosynthesis",
            "It stays the same, because carbon dioxide plays no part in tree growth",
            "It falls, because the soil exposed by clearing absorbs the gas directly",
        ],
        "correct_index": 1,
        "why": "Trees remove carbon dioxide as they grow, so removing them lowers "
               "the rate at which the gas is taken out of the air.",
    },
    {
        "id": "ks4-earths-resources-s14",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Worldwide, which use takes the largest share of the fresh water people withdraw?",
        "options": [
            "Washing and drinking in homes, where the water is used every day",
            "Irrigating crops on farmland, where very large volumes are needed",
            "Generating electricity in power stations, where steam is condensed",
            "Cooling reactors in chemical plants, where heat must be removed",
        ],
        "correct_index": 1,
        "why": "Agriculture accounts for roughly 70% of global fresh-water "
               "withdrawal, far more than homes or industry.",
    },
    {
        "id": "ks4-earths-resources-s15",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Crude oil is not used only as a fuel. Describe its other major use.",
        "options": [
            "As a lubricant for machinery, which is the chief non-fuel use it has",
            "As a fertiliser, because the carbon in it feeds growing crops",
            "As a feedstock, supplying the molecules for polymers and medicines",
            "As a solvent, because crude oil dissolves most ionic compounds readily and cheaply",
        ],
        "correct_index": 2,
        "why": "Crude oil is the starting material for most synthetic polymers, "
               "solvents, dyes and medicines, not just for fuels.",
    },
    {
        "id": "ks4-earths-resources-s16",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the time needed to replace a felled tree with the time needed to replace the crude oil burnt in a year.",
        "options": [
            "Decades for the tree and many millions of years for the crude oil",
            "Decades for the tree and roughly the same few decades for the oil",
            "Centuries for the tree and just a few decades for the crude oil",
            "Minutes for the tree and a few hundred years for the crude oil",
        ],
        "correct_index": 0,
        "why": "A replacement tree matures within a human lifetime; crude oil "
               "takes geological time, which is why only one counts as renewable.",
    },
    {
        "id": "ks4-earths-resources-s17",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Apart from the energy it uses, describe one environmental cost of mining a metal ore.",
        "options": [
            "The metal in the ore decays into a different element as it is dug out",
            "The ore becomes radioactive once it has been crushed and separated",
            "Large volumes of waste rock are produced and habitats are destroyed",
            "The ore gives off oxygen, which lowers the oxygen content of the air",
        ],
        "correct_index": 2,
        "why": "Most of the rock removed is not ore, so mining leaves spoil heaps, "
               "scarred land and lost habitat as well as using energy.",
    },
    {
        "id": "ks4-earths-resources-s18",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Distinguish between the atom economy of a reaction and its percentage yield.",
        "options": [
            "Atom economy compares the product with the reactants; yield compares two reactions",
            "Atom economy is measured in the laboratory; yield is worked out from the equation",
            "Atom economy applies to industry; yield applies to school experiments alone",
            "Atom economy compares desired product with total reactants; yield compares actual with maximum",
        ],
        "correct_index": 3,
        "why": "Atom economy is fixed by the balanced equation; percentage yield "
               "depends on how much product was actually obtained.",
    },
    {
        "id": "ks4-earths-resources-s19",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A company finds a market for a by-product it used to throw away. Explain how this makes the process greener.",
        "options": [
            "More of the reactant mass leaves as something useful and less as waste",
            "The reaction becomes faster, so the plant burns its fuel for far fewer hours",
            "The by-product is converted back into the reactants, so less raw material is needed",
            "The percentage yield of the main product rises once the by-product sells",
        ],
        "correct_index": 0,
        "why": "Green chemistry aims to turn as much of the starting material as "
               "possible into something wanted, rather than into waste.",
    },
    {
        "id": "ks4-earths-resources-s20",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Sea water is treated as a resource in its own right. Name the main substance obtained from it on a large scale.",
        "options": [
            "Sulfur, which settles out of sea water when it is left to stand for days",
            "Sodium chloride, which is left behind when the water evaporates",
            "Crude oil, which floats on the surface of the sea and is skimmed off",
            "Nitrogen, which is driven out of sea water by warming it gently in a pan",
        ],
        "correct_index": 1,
        "why": "Sea water is an ionic solution, and evaporating it in shallow pans "
               "leaves solid sodium chloride behind.",
    },
    {
        "id": "ks4-earths-resources-s21",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe one consequence for waste disposal of a rising world population.",
        "options": [
            "Less landfill is needed, because larger populations produce less per person",
            "Waste stops being a problem, because more of it decays in a bigger country",
            "More material is thrown away, so more land is taken up by landfill sites",
            "Waste becomes a renewable resource, because it is produced continuously",
        ],
        "correct_index": 2,
        "why": "More people consuming more products means more discarded material, "
               "and landfill takes land that could be used otherwise.",
    },
    {
        "id": "ks4-earths-resources-s22",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the nitrogen taken from air is not treated as a finite resource in the way a copper ore body is.",
        "options": [
            "Nitrogen is a gas, and a gas cannot be used up by a chemical reaction",
            "Nitrogen is made continuously by reactions happening in the upper air",
            "Copper is a metal, and metals are the one class of finite resource",
            "Air is a huge well-mixed store, so taking nitrogen barely changes it",
        ],
        "correct_index": 3,
        "why": "The atmosphere holds an enormous and constantly mixed mass of "
               "nitrogen, whereas an ore body is a fixed deposit in one place.",
    },
    {
        "id": "ks4-earths-resources-s23",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Air costs nothing to collect, yet separating nitrogen from it is expensive. Explain why.",
        "options": [
            "The air has to be cooled below -196 degrees C, and that needs a lot of energy",
            "The air has to be filtered many times over, and each filter is costly",
            "The nitrogen has to be reacted with a catalyst that is rare and costly",
            "The air has to be compressed into a solid before the gases will part",
        ],
        "correct_index": 0,
        "why": "The gases only separate once the air is liquefied, and refrigerating "
               "air to below -196 degrees C is energy-intensive.",
    },
    {
        "id": "ks4-earths-resources-s24",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A carpet can be woven from wool or from nylon. Suggest one resource advantage of choosing wool.",
        "options": [
            "Wool carries no water cost, because sheep drink nothing but rainwater",
            "Wool is grown again each year and will decay at the end of its life",
            "Wool is stronger than nylon, so a thinner carpet can be woven",
            "Wool needs no processing, so the fleece is woven straight from the sheep",
        ],
        "correct_index": 1,
        "why": "Wool is a renewable biological resource that biodegrades, while "
               "nylon is made from finite crude oil and persists in landfill.",
    },
    {
        "id": "ks4-earths-resources-s25",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Rock salt is mined in Cheshire. State one large-scale industrial use of the sodium chloride obtained.",
        "options": [
            "It is burnt as a fuel in furnaces, because it releases heat steadily",
            "It is smelted with coke to obtain the metal sodium from the ore",
            "It is used as a raw material for chlorine and sodium hydroxide",
            "It is quarried for building stone, because the crystals are hard",
        ],
        "correct_index": 2,
        "why": "Brine made from rock salt is the feedstock for the chlor-alkali "
               "industry, which supplies chlorine and sodium hydroxide.",
    },
    {
        "id": "ks4-earths-resources-s26",
        "subtopic_slug": "earths-resources",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe where the carbon in a plastic has come from when the plastic is made from a renewable feedstock.",
        "options": [
            "From carbon dioxide taken from the air by plants grown recently",
            "From carbonate rocks that were quarried and then heated strongly",
            "From coal seams laid down in swamps many millions of years ago",
            "From the carbon dioxide dissolved in the water of the deep ocean",
        ],
        "correct_index": 0,
        "why": "A plant feedstock builds its molecules from atmospheric carbon "
               "dioxide during this growing season, not from ancient deposits.",
    },
    {
        "id": "ks4-earths-resources-h07",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Hydrogen is made by the reaction CH4 + 2H2O gives CO2 + 4H2. Relative formula masses are CH4 = 16, H2O = 18, CO2 = 44 and H2 = 2. Calculate the atom economy for hydrogen.",
        "options": [
            "15.4%, the mass of the hydrogen as a share of both reactant masses",
            "22.2%, obtained by comparing the hydrogen just with the mass of water used",
            "30.8%, obtained by taking the methane's mass of 16 as the useful product",
            "84.6%, obtained by treating the carbon dioxide as the desired product",
        ],
        "correct_index": 0,
        "why": "The reactants total 16 + 36 = 52 and the hydrogen is 4 x 2 = 8, so "
               "8 divided by 52 is 15.4%.",
    },
    {
        "id": "ks4-earths-resources-h08",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Wind turbines and electric-car batteries cut the use of fossil fuels but need metals such as neodymium and lithium. Evaluate this as a sustainability problem.",
        "options": [
            "There is no problem, because a technology that saves fuel cannot create a resource cost",
            "There is no problem, because the metals used in these devices are all renewable ones",
            "It is a real problem, because generating electricity from wind uses more fuel overall",
            "It is a real tension: fossil fuel use falls, but demand on scarce mined metals rises",
        ],
        "correct_index": 3,
        "why": "Sustainability is judged across the whole system, and these "
               "technologies trade one finite demand for a different one.",
    },
    {
        "id": "ks4-earths-resources-h09",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A bottle can be made from maize starch or from crude oil. Which is the fairest judgement of the maize route?",
        "options": [
            "The maize route is better in every way, since a crop cannot run out",
            "The maize route uses a feedstock that regrows, but the land could grow food",
            "The two routes cannot be compared, because just one of them yields a rigid solid product",
            "The oil route is better in every way, since crops need no processing",
        ],
        "correct_index": 1,
        "why": "A renewable feedstock is a genuine gain, but the land, water and "
               "fertiliser the crop needs are costs the oil route does not have.",
    },
    {
        "id": "ks4-earths-resources-h10",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A geologist reports that a country's copper resource is far larger than its copper reserve. Explain the difference.",
        "options": [
            "The resource is the copper already mined; the reserve is what is left underground",
            "The resource is all the copper present; the reserve is the part worth extracting now",
            "The resource is the pure copper; the reserve is the copper still combined in compounds",
            "The resource is measured by volume of rock; the reserve is measured by mass of metal",
        ],
        "correct_index": 1,
        "why": "A reserve is the part of the resource that can be extracted at a "
               "profit with current technology, so it is always the smaller figure.",
    },
    {
        "id": "ks4-earths-resources-h11",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A chemist claims that a reaction with an atom economy of 100% produces no waste. Evaluate the claim.",
        "options": [
            "Correct, because every atom of the reactants appears in the desired product",
            "Correct, because a 100% atom economy also fixes the percentage yield at 100%",
            "Wrong, because a 100% atom economy is not possible for any real reaction",
            "Wrong, because solvents, unreacted material and energy losses remain",
        ],
        "correct_index": 3,
        "why": "Atom economy only describes the balanced equation; the real plant "
               "still loses product and still uses solvents and energy.",
    },
    {
        "id": "ks4-earths-resources-h12",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A mining company will restore the land and fund a local school. Evaluate whether the mine can be called sustainable development.",
        "options": [
            "No, because taking any finite resource out of the ground rules it out",
            "Yes, because the company has promised benefits to the local community",
            "It can be, if the restored land and the lasting benefits outlive the mine",
            "No, because sustainable development applies to farming and not to mining",
        ],
        "correct_index": 2,
        "why": "The test is whether future generations are left able to meet their "
               "needs, so restoration and durable benefits are what decide it.",
    },
    {
        "id": "ks4-earths-resources-h13",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Coal and copper ore are both finite. Explain why running out of coal is a more permanent loss than running out of copper ore.",
        "options": [
            "Coal is burnt and its carbon is dispersed, whereas copper stays available in objects",
            "Coal is buried much more deeply than copper ore, so it is harder to find any more of it",
            "Coal contains no metal, and a resource has to contain a metal before it can be finite",
            "Coal forms far more slowly than copper ore, so its deposits are much smaller in size than copper's",
        ],
        "correct_index": 0,
        "why": "Burning coal scatters its carbon as carbon dioxide, while copper "
               "atoms remain in the metal objects made from them.",
    },
    {
        "id": "ks4-earths-resources-h14",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "World copper reserves are about 870 million tonnes and production is about 21 million tonnes a year. Calculate how long the reserves would last at that rate.",
        "options": [
            "About 21 years, taking the annual production figure as the answer",
            "About 410 years, which is the same division with the decimal misplaced",
            "About 891 years, obtained by adding the two figures given in the stem",
            "About 41 years, dividing the reserve figure by the annual production",
        ],
        "correct_index": 3,
        "why": "870 divided by 21 is about 41, so the reserves would last roughly "
               "41 years if production stayed constant.",
    },
    {
        "id": "ks4-earths-resources-h15",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Route X runs at 80 degrees C in water with an atom economy of 85%. Route Y runs at 300 degrees C in an organic solvent with an atom economy of 88%. Determine which is the greener route.",
        "options": [
            "Route Y, because the higher atom economy settles the comparison",
            "Route Y, because a hotter reaction converts reactants more completely",
            "Route X, because a slightly lower atom economy is outweighed by milder conditions",
            "Neither, because the two routes cannot be compared without the yields",
        ],
        "correct_index": 2,
        "why": "Three percentage points of atom economy is a small gain beside a "
               "220 degrees C temperature rise and a solvent that must be disposed of.",
    },
    {
        "id": "ks4-earths-resources-h16",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Agriculture takes about 70% of the fresh water withdrawn worldwide and homes take about 10%. Evaluate the claim that household water meters are the main way to protect water supplies.",
        "options": [
            "The claim is sound, because households are the largest single user of water",
            "The claim is weak, because most withdrawal is agricultural and irrigation matters more",
            "The claim is sound, because water saved in homes is returned to farmland",
            "The claim is weak, because metering has no effect on how much people use",
        ],
        "correct_index": 1,
        "why": "Saving a share of the 10% used at home cannot match the effect of "
               "improving irrigation, which is where most of the water goes.",
    },
    {
        "id": "ks4-earths-resources-h17",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Fitting carbon capture to a coal-fired power station lowers its carbon dioxide emissions by about 90% but raises its fuel use by about 25%. Evaluate the fitting.",
        "options": [
            "It is worthwhile, and it also converts the coal into a renewable fuel",
            "It is pointless, because capturing carbon dioxide has no climate benefit",
            "It cuts emissions sharply, but the extra coal burnt shortens the reserve",
            "It is pointless, because burning extra coal cancels the whole saving",
        ],
        "correct_index": 2,
        "why": "A 90% cut in emissions is a real gain, but the 25% extra fuel means "
               "a finite resource is used faster to achieve it.",
    },
    {
        "id": "ks4-earths-resources-h18",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "An ore contains 0.40% copper by mass. Calculate the mass of ore needed to obtain 1.0 tonne of copper.",
        "options": [
            "0.4 tonnes, multiplying the copper mass by the percentage",
            "40 tonnes, multiplying the 0.40 by one hundred",
            "2500 tonnes, the same division with the percentage converted wrongly",
            "250 tonnes, found by dividing the copper mass by 0.0040",
        ],
        "correct_index": 3,
        "why": "1.0 divided by 0.0040 gives 250, so 250 tonnes of this low-grade "
               "ore must be handled for each tonne of copper.",
    },
    {
        "id": "ks4-earths-resources-h19",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A company plans to clear rainforest for an oil-palm plantation, arguing that the palms will absorb carbon dioxide as well. Evaluate the argument.",
        "options": [
            "It holds, because a plantation and a rainforest absorb carbon dioxide equally",
            "It fails, because plantation crops do not photosynthesise once they are farmed",
            "It holds, because the timber felled will store its carbon permanently",
            "It fails, because the cleared forest stored far more carbon than palms will",
        ],
        "correct_index": 3,
        "why": "Mature rainforest holds a large carbon store and a great deal of "
               "biodiversity, neither of which a single-crop plantation replaces.",
    },
    {
        "id": "ks4-earths-resources-h20",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A process is cheap and produces little pollution, but depends on a mineral mined by poorly paid workers in unsafe conditions. Evaluate it against sustainable development.",
        "options": [
            "It qualifies, because the economic and environmental tests are both met",
            "It fails, because sustainable development also requires fairness to people",
            "It qualifies, because working conditions are a matter of law, not chemistry",
            "It fails, because a cheap process cannot protect the environment as well",
        ],
        "correct_index": 1,
        "why": "Sustainable development weighs social fairness alongside cost and "
               "environmental impact, so all three have to hold.",
    },
    {
        "id": "ks4-earths-resources-h21",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A chemist looks for a cheaper material to replace a scarce metal in an electrical contact. Suggest why matching the electrical conductivity is not enough.",
        "options": [
            "The replacement must also match the cost, which is decided by conductivity alone",
            "The replacement must also have the same relative atomic mass as the metal",
            "The replacement must also resist corrosion and wear for the whole service life",
            "The replacement must also be a metal, since no other class of material conducts at a useful rate",
        ],
        "correct_index": 2,
        "why": "A contact that conducts well but corrodes or wears away fails in "
               "service, so every property the job demands has to be matched.",
    },
    {
        "id": "ks4-earths-resources-h22",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reaction has an atom economy of 40%. Calculate the maximum mass of the desired product obtainable from 250 g of reactants.",
        "options": [
            "40 g, reading the atom economy directly as a mass in grams",
            "100 g, which is 40% of the 250 g of reactants supplied",
            "150 g, the mass that leaves the reaction as unwanted products",
            "625 g, obtained by dividing the reactant mass by the percentage",
        ],
        "correct_index": 1,
        "why": "Atom economy gives the share of reactant mass that can appear as "
               "the desired product, and 40% of 250 g is 100 g.",
    },
    {
        "id": "ks4-earths-resources-h23",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A power station burns wood from fast-growing trees that are replanted after felling. Evaluate the claim that the fuel is carbon neutral.",
        "options": [
            "The claim holds exactly, because burning wood releases no carbon dioxide of its own",
            "The claim holds exactly, because the same mass of trees is replanted",
            "The claim is close but not exact, because harvesting and transport burn fuel",
            "The claim fails, because wood releases more carbon dioxide than coal does",
        ],
        "correct_index": 2,
        "why": "Regrowth can reabsorb the carbon dioxide released, but the "
               "machinery, processing and haulage add emissions that it does not.",
    },
    {
        "id": "ks4-earths-resources-h24",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Pumping water into a salt bed to dissolve the salt can cause the ground above to sink. Evaluate whether this makes the use of rock salt unsustainable.",
        "options": [
            "Yes, because any extraction that damages the ground above the bed is unsustainable",
            "Yes, because rock salt cannot be replaced once a salt bed has been emptied of it",
            "Not necessarily, if the cavities are managed so that subsidence is controlled",
            "No, because subsidence affects the land at the surface and not the salt resource lying below",
        ],
        "correct_index": 2,
        "why": "Sustainability turns on whether the damage is limited and the land "
               "remains usable, not on whether extraction happens at all.",
    },
    {
        "id": "ks4-earths-resources-h25",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest how a synthetic fibre made from crude oil could still be the better environmental choice than a natural one.",
        "options": [
            "It would decay faster in landfill, so far less material builds up there over time",
            "It would be made without energy, because synthetic routes need no heating",
            "It would need no farmland to produce it, so crude oil would count as a renewable resource",
            "It could last far longer in use, so less material and land are needed overall",
        ],
        "correct_index": 3,
        "why": "A judgement covers the whole lifetime, so a durable fibre replaced "
               "rarely can beat a renewable one that has to be replaced often.",
    },
    {
        "id": "ks4-earths-resources-h26",
        "subtopic_slug": "earths-resources",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A plant can either treat its waste stream more thoroughly or redesign the reaction so that less waste forms. Determine which is the better green-chemistry improvement, and why.",
        "options": [
            "Treating the waste, because the treated waste can then be sold on",
            "Redesigning the reaction, because waste that never forms needs no treatment",
            "Treating the waste, because redesigning a reaction cannot change its waste",
            "Neither, because the mass of waste is fixed by conservation of mass",
        ],
        "correct_index": 1,
        "why": "Preventing waste is the higher principle: treatment costs energy "
               "and reagents of its own, and still leaves something to dispose of.",
    },
]
