"""Chemistry · Using resources — the MRB-338 expansion for `life-cycle-assessment`.

The shipped rows own the four stages, cradle-to-grave, the hot-spot idea and the
carrier-bag comparison, so the weight here falls on the parts of the spec point
they did not reach: the disposal routes one by one (landfill, recycling,
incineration with energy recovery, composting), what an LCA can and cannot put a
number on, and the reasons two honest assessments of one product disagree — the
boundary drawn, the weighting chosen, and the electricity mix of the country the
data came from.

Break-even arithmetic carries the calculation load, because it is where this
spec point turns a judgement into a number: how many uses a reusable article
needs before its heavier manufacturing impact is paid off. Three rows do it with
different articles and different figures. The harder band is evaluation
throughout, including the abbreviated LCA written for an advertisement.
"""

TOPIC = "resources"
SUBJECT = "chemistry"

QUESTIONS = [
    {
        "id": "ks4-life-cycle-assessment-e06",
        "subtopic_slug": "life-cycle-assessment",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the disposal routes a life cycle assessment considers.",
        "options": [
            "Landfill, recycling, incineration and composting",
            "Landfill and recycling, the two legal routes",
            "Incineration alone, since every product is burnt at the end",
            "Recycling and reuse, which are the two cheapest routes there are",
        ],
        "correct_index": 0,
        "why": "The disposal stage covers whichever route the product actually "
               "takes at the end of its life, and there are four to choose from.",
    },
    {
        "id": "ks4-life-cycle-assessment-e07",
        "subtopic_slug": "life-cycle-assessment",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which environmental cost in a life cycle assessment is easiest to express as a number?",
        "options": [
            "The damage done to the appearance of a landscape near a quarry",
            "The mass of waste sent to landfill over the product's life",
            "The distress caused to people living close to a factory site",
            "The long-term risk that a species will be lost from a habitat",
        ],
        "correct_index": 1,
        "why": "A mass can be weighed and recorded, whereas the other three are "
               "judgements that different analysts would score differently.",
    },
    {
        "id": "ks4-life-cycle-assessment-e08",
        "subtopic_slug": "life-cycle-assessment",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Burning a worn-out product in an incinerator belongs to which stage of a life cycle assessment?",
        "options": [
            "Extracting the raw materials",
            "Manufacturing and packaging",
            "Use over the working lifetime",
            "Disposal at the end of life",
        ],
        "correct_index": 3,
        "why": "Incineration is one of the four disposal routes, so its energy and "
               "emissions are recorded in the disposal stage.",
    },
    {
        "id": "ks4-life-cycle-assessment-e09",
        "subtopic_slug": "life-cycle-assessment",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State roughly how long a plastic carrier bag takes to break down in landfill.",
        "options": [
            "About 45 days, which is why landfill sites stay in use so briefly",
            "About 4 years, which is why landfill needs replacing every decade",
            "About 45 years, which is why landfill is counted as a short-term store",
            "About 450 years, which is why landfill space is taken up for so long",
        ],
        "correct_index": 3,
        "why": "Poly(ethene) is unreactive and not readily broken down by "
               "microorganisms, so a buried bag persists for centuries.",
    },
    {
        "id": "ks4-life-cycle-assessment-e10",
        "subtopic_slug": "life-cycle-assessment",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State one way a government can use a life cycle assessment.",
        "options": [
            "To set rules such as a minimum recycled content for packaging",
            "To decide the retail price at which a product must be sold",
            "To choose the colour that packaging is allowed to be printed in",
            "To work out how many of a product each household should own",
        ],
        "correct_index": 0,
        "why": "An assessment shows where the impact actually falls, which is what "
               "a regulation has to target if it is going to reduce it.",
    },
    {
        "id": "ks4-life-cycle-assessment-e11",
        "subtopic_slug": "life-cycle-assessment",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "The energy used to mould the plastic casing of a kettle is recorded in which stage?",
        "options": [
            "The raw materials stage, because plastic comes from crude oil",
            "The manufacturing stage, because the product is being made",
            "The use stage, because the casing is used for the kettle's life",
            "The disposal stage, because the casing is scrapped in the end",
        ],
        "correct_index": 1,
        "why": "Shaping and assembling a product, and packaging it, all fall in "
               "the manufacturing stage.",
    },
    {
        "id": "ks4-life-cycle-assessment-e12",
        "subtopic_slug": "life-cycle-assessment",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which of these is a renewable raw material for making a carrier bag?",
        "options": [
            "Crude oil from an offshore well",
            "Natural gas piped from a gas field",
            "Trees from a managed plantation",
            "Iron ore dug from an open-cast pit",
        ],
        "correct_index": 2,
        "why": "Trees are replanted and regrow within a human lifetime, so timber "
               "and the paper made from it count as renewable.",
    },
    {
        "id": "ks4-life-cycle-assessment-s07",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a lighter product usually carries a lower transport impact in its life cycle assessment.",
        "options": [
            "A lighter product is made from renewable materials, which release less carbon dioxide in transit",
            "A lighter product is smaller, and a smaller product cannot be damaged during a journey",
            "Speed is higher with a lighter load, so less time is spent on the road",
            "Less fuel is burnt to move each item, so the emissions per item are lower",
        ],
        "correct_index": 3,
        "why": "Transport emissions depend on the mass moved and the distance, so "
               "reducing the mass reduces the fuel burnt per item.",
    },
    {
        "id": "ks4-life-cycle-assessment-s08",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why an assessment of the same product can reach different results in two countries.",
        "options": [
            "The electricity may come mainly from coal in one and from renewables in the other",
            "The four stages of an assessment are each defined quite differently in every country",
            "Products behave differently in different climates, so the use stage cannot be measured",
            "The mass of the product changes when it crosses an international border",
        ],
        "correct_index": 0,
        "why": "The emissions tied to each kilowatt-hour depend on how that "
               "country generates its electricity, and every stage uses energy.",
    },
    {
        "id": "ks4-life-cycle-assessment-s09",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why carrying out a full life cycle assessment of a product is slow and expensive.",
        "options": [
            "The calculations can be done by hand, and hand calculation is a slow business",
            "Data has to be gathered for every stage, from many different suppliers",
            "The product must be manufactured twice so that the results can be compared",
            "Each stage has to be assessed by a separate government department first",
        ],
        "correct_index": 1,
        "why": "A cradle-to-grave study needs energy, water, waste and emissions "
               "figures from everyone in the supply chain, which takes time.",
    },
    {
        "id": "ks4-life-cycle-assessment-s10",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why an assessment paid for by the company that makes the product should be read with care.",
        "options": [
            "A company is not permitted by law to publish any environmental data about products it makes itself",
            "A company would have used different units, so its figures cannot be compared",
            "The company chooses which impacts to include, and may leave out unflattering ones",
            "The company's chemists are less well qualified than government chemists are",
        ],
        "correct_index": 2,
        "why": "Because the boundary and the weighting are choices, whoever makes "
               "them can shape the conclusion without stating a false figure.",
    },
    {
        "id": "ks4-life-cycle-assessment-s11",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a cotton tote bag has to be used many times before it beats a plastic bag.",
        "options": [
            "Cotton is heavier, and the bag's whole impact comes from moving that extra mass around",
            "Cotton decays in landfill, and decay releases more carbon dioxide than plastic does",
            "Cotton is a natural fibre, and natural fibres are judged more strictly",
            "Growing and processing the cotton uses far more energy and water per bag",
        ],
        "correct_index": 3,
        "why": "Its manufacturing impact is large, so it has to be spread over many "
               "uses before the impact per use falls below the plastic bag's.",
    },
    {
        "id": "ks4-life-cycle-assessment-s12",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how reusing an article changes its manufacturing impact per use.",
        "options": [
            "The same manufacturing impact is divided between more uses, so it falls",
            "Washing the article between uses counts as making it again, so the impact rises",
            "The manufacturing impact is unchanged, because it was fixed when it was made",
            "The manufacturing impact moves into the disposal stage once it is reused",
        ],
        "correct_index": 0,
        "why": "Making the article is a one-off cost, so each extra use makes the "
               "share of that cost carried by one use smaller.",
    },
    {
        "id": "ks4-life-cycle-assessment-s13",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why it is hard to combine a product's carbon dioxide emissions and its water use into one score.",
        "options": [
            "Carbon dioxide and water use are both of them measured in litres, so the two simply cancel out",
            "They are measured in different units, so combining them needs a judgement of importance",
            "Water use is not an environmental impact, so it should be discarded from the score completely",
            "Emissions are known accurately but water use cannot be measured",
        ],
        "correct_index": 1,
        "why": "There is no scientific exchange rate between kilograms of gas and "
               "litres of water, so any single score reflects a chosen weighting.",
    },
    {
        "id": "ks4-life-cycle-assessment-s14",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe one advantage of incinerating waste with energy recovery rather than sending it to landfill.",
        "options": [
            "No carbon dioxide is released, because the heat is captured instead of the gas",
            "The waste is destroyed completely, so no ash or residue has to be dealt with",
            "Useful heat or electricity is obtained, and less land is taken up",
            "The material can afterwards be recycled, because burning purifies it",
        ],
        "correct_index": 2,
        "why": "Burning the waste releases energy that can be used, and it avoids "
               "occupying landfill space for centuries.",
    },
    {
        "id": "ks4-life-cycle-assessment-s15",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which kind of product is suited to composting as its disposal route?",
        "options": [
            "A steel food tin, because the metal will corrode away in the soil",
            "A glass jar, because glass is made from sand and returns to sand",
            "An aluminium tray, because aluminium is the commonest metal",
            "A cardboard tray, because microorganisms break the plant fibres down",
        ],
        "correct_index": 3,
        "why": "Composting needs a material that microorganisms can digest, which "
               "plant-based materials such as card and paper are.",
    },
    {
        "id": "ks4-life-cycle-assessment-s16",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A lamp takes 30 kWh to manufacture and uses 5 kWh a year for 10 years. Calculate the percentage of its lifetime energy used in the use stage.",
        "options": [
            "62.5%, since 50 kWh of the 80 kWh total is used in service",
            "37.5%, which is the share used in manufacturing the lamp",
            "50%, since manufacture and use are treated as equal halves",
            "16.7%, comparing 5 kWh with the 30 kWh of manufacture",
        ],
        "correct_index": 0,
        "why": "Use is 5 x 10 = 50 kWh, the total is 30 + 50 = 80 kWh, and 50 "
               "divided by 80 is 62.5%.",
    },
    {
        "id": "ks4-life-cycle-assessment-s17",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Making one thin bag releases 50 g of carbon dioxide and making one sturdy reusable bag releases 800 g. Calculate how many uses the reusable bag needs to match the thin bag.",
        "options": [
            "850 uses, found by adding 800 g to the 50 g",
            "16 uses, found by dividing 800 g by 50 g",
            "8 uses, found by halving the 800 g first",
            "750 uses, found by subtracting 50 g from 800 g",
        ],
        "correct_index": 1,
        "why": "Each use of the reusable bag replaces one thin bag worth 50 g, and "
               "800 divided by 50 is 16.",
    },
    {
        "id": "ks4-life-cycle-assessment-s18",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how a manufacturer uses a life cycle assessment to improve a product.",
        "options": [
            "It reprints the packaging so that the figures from the assessment appear across the front of the label",
            "It repeats the assessment each year until a favourable result is obtained",
            "It finds the stage with the largest impact and redesigns that part",
            "It moves production to a country where assessments are not required",
        ],
        "correct_index": 2,
        "why": "An assessment shows where the impact is concentrated, so effort can "
               "go to the stage where a change makes the most difference.",
    },
    {
        "id": "ks4-life-cycle-assessment-s19",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the conclusion of a life cycle assessment holds only for the assumptions it states.",
        "options": [
            "Because the arithmetic in an assessment is approximate and cannot be checked by anyone outside the firm",
            "Because the four stages are assessed in a different order by every analyst",
            "Because a conclusion about a product is a matter of opinion and not of measurement",
            "Because changing an assumed lifetime or energy source changes the figures",
        ],
        "correct_index": 3,
        "why": "The numbers depend on inputs such as assumed lifetime, reuse count "
               "and electricity mix, so the conclusion travels with them.",
    },
    {
        "id": "ks4-life-cycle-assessment-s20",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which of these activities is recorded in the manufacturing stage of an assessment?",
        "options": [
            "Printing the label and sealing the finished product into its box",
            "Quarrying the limestone that the product is partly made from",
            "Running the product for eight hours on each day of its life",
            "Collecting the product from the kerbside for recycling",
        ],
        "correct_index": 0,
        "why": "Manufacturing covers making the product and its packaging, which "
               "includes printing, filling and sealing.",
    },
    {
        "id": "ks4-life-cycle-assessment-s21",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why labelling a product biodegradable does not settle a comparison on its own.",
        "options": [
            "Biodegradable products cannot be assessed, because their mass changes over time",
            "Biodegradability describes disposal, and the other three stages still count",
            "Biodegradable products break down into substances that cannot be identified",
            "Biodegradability is measured in years, and years cannot enter an assessment",
        ],
        "correct_index": 1,
        "why": "A product can biodegrade well and still take far more energy and "
               "water to make, which the other three stages would show.",
    },
    {
        "id": "ks4-life-cycle-assessment-s22",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a full assessment helps a shopper more than a single green claim on a label.",
        "options": [
            "A label claim is illegal, whereas an assessment has been approved by a regulator",
            "A label claim is written by a chemist, whereas an assessment is written by a shopper",
            "A claim covers just the packaging, and packaging is not part of the product",
            "A claim may be true of one stage while the product does badly at the others",
        ],
        "correct_index": 3,
        "why": "A single true fact about one stage can sit alongside a large impact "
               "somewhere else, which a cradle-to-grave study exposes.",
    },
    {
        "id": "ks4-life-cycle-assessment-s23",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how recycling a product at the end of its life changes its assessment.",
        "options": [
            "The whole assessment is cancelled, because a recycled product has no life cycle",
            "Just the use stage changes, because the product is used twice over",
            "The manufacturing stage is removed, because no new material is needed",
            "The disposal impact falls, and less new raw material is needed elsewhere",
        ],
        "correct_index": 3,
        "why": "Recycling keeps the material out of landfill and reduces the demand "
               "for freshly extracted material in the next product.",
    },
    {
        "id": "ks4-life-cycle-assessment-s24",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the use stage dominates the assessment of a refrigerator but not that of a carrier bag.",
        "options": [
            "A refrigerator draws electricity for years, whereas a bag consumes nothing in use",
            "A refrigerator is heavier, and mass is what the use stage measures",
            "A refrigerator is used indoors, and indoor use is weighted much more heavily",
            "A refrigerator has more parts, so its use stage is divided between them",
        ],
        "correct_index": 0,
        "why": "The use stage records the energy and water a product consumes in "
               "service, and a bag consumes none.",
    },
    {
        "id": "ks4-life-cycle-assessment-s25",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give one impact of a quarry that an assessment struggles to express as a number.",
        "options": [
            "The mass of rock removed from the quarry face each working week",
            "The volume of water pumped out of the quarry during the year",
            "The loss of an attractive landscape that local people valued",
            "The electricity used by the crushers and conveyors on the site",
        ],
        "correct_index": 2,
        "why": "Masses, volumes and energies are measurable, but the value people "
               "place on a view has no agreed scale.",
    },
    {
        "id": "ks4-life-cycle-assessment-s26",
        "subtopic_slug": "life-cycle-assessment",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the impact of a product's packaging is recorded in the manufacturing stage.",
        "options": [
            "Because packaging is thrown away, and everything thrown away is counted as manufacture",
            "Because packaging is made and fitted as part of producing the item for sale",
            "Because packaging is the heaviest part of most products that are sold in shops",
            "Because packaging is bought from a supplier rather than made on the same site",
        ],
        "correct_index": 1,
        "why": "The spec pairs manufacturing with packaging, because the materials "
               "and energy for the wrapper are part of making the product.",
    },
    {
        "id": "ks4-life-cycle-assessment-h07",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A reusable cup releases 1200 g of carbon dioxide to make and 20 g for each wash. A paper cup releases 60 g and is used once. Calculate how many uses make the reusable cup the better choice.",
        "options": [
            "20 uses, from 1200 g divided by the 60 g of a paper cup",
            "30 uses, since 1200 g divided by the 40 g saved per use is 30",
            "60 uses, found by dividing 1200 g by the 20 g cost of a wash",
            "80 uses, found by adding the 20 g wash cost to the 60 g paper cup",
        ],
        "correct_index": 1,
        "why": "Each use saves 60 - 20 = 40 g, so the 1200 g of manufacture is paid "
               "off after 1200 divided by 40 = 30 uses.",
    },
    {
        "id": "ks4-life-cycle-assessment-h08",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "An advertisement quotes an assessment that covers only the disposal of a bottle. Evaluate the use of this assessment in the advertisement.",
        "options": [
            "It is acceptable, because disposal is the stage a shopper has control over",
            "It is acceptable, because a shortened assessment is far quicker for a shopper to read through",
            "It is misleading: one favourable stage is presented as if it were the whole picture",
            "It is misleading, because the disposal stage cannot be assessed for a bottle",
        ],
        "correct_index": 2,
        "why": "An abbreviated assessment can be truthful about the stage it covers "
               "and still mislead, by leaving the other three stages out.",
    },
    {
        "id": "ks4-life-cycle-assessment-h09",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "One assessment of an electric heater uses data from a country supplied mainly by coal, the other from a country supplied mainly by hydroelectricity. Predict how the two results differ.",
        "options": [
            "The two results are identical, because the heater itself is the very same product in each",
            "The coal-supplied study gives the larger emissions, because its electricity is dirtier",
            "The hydroelectric study gives the larger emissions, because building the dams floods whole valleys and forests",
            "Neither study can report emissions, because electricity carries none at the socket",
        ],
        "correct_index": 1,
        "why": "The use stage converts kilowatt-hours into emissions using the local "
               "generating mix, so the same appliance scores differently.",
    },
    {
        "id": "ks4-life-cycle-assessment-h10",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that a life cycle assessment proves which of two products is better.",
        "options": [
            "The claim holds, because an assessment reduces both products to a single number",
            "The claim holds, because all four stages have been measured for each product",
            "The claim is weak, because an assessment cannot compare two products",
            "The claim is weak: what counts as better depends on which impacts are weighted",
        ],
        "correct_index": 3,
        "why": "An assessment supplies the figures, but deciding that water use "
               "matters more than emissions is a judgement, not a measurement.",
    },
    {
        "id": "ks4-life-cycle-assessment-h11",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A tool needs 120 kWh to manufacture and 30 kWh over its working life. Determine where a redesign should be aimed, and why.",
        "options": [
            "At manufacture, because it accounts for 120 of the 150 kWh total",
            "At the use stage, because that is the stage the owner can control",
            "At disposal, because the remaining energy must be hidden there",
            "At both equally, because a redesign has to treat every stage alike",
        ],
        "correct_index": 0,
        "why": "Manufacture is 80% of the lifetime energy, so a given percentage cut "
               "there saves far more than the same cut in use.",
    },
    {
        "id": "ks4-life-cycle-assessment-h12",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A firm replaces plastic packaging with paper. Manufacturing energy rises by 40% but the packaging now composts. Evaluate the change.",
        "options": [
            "It is a genuine trade-off, and which way it falls depends on how the two are weighted",
            "It is clearly an improvement, because composting removes the whole of the disposal impact entirely",
            "It is clearly worse, because a rise in manufacturing energy outweighs any other gain",
            "It changes nothing, because packaging is not assessed in a life cycle assessment",
        ],
        "correct_index": 0,
        "why": "One stage worsens and another improves, so the honest answer names "
               "the trade-off rather than declaring a winner.",
    },
    {
        "id": "ks4-life-cycle-assessment-h13",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why two bags should be compared per hundred shopping trips rather than per bag.",
        "options": [
            "Because a hundred trips is the number a shopping bag is legally expected to survive in use",
            "Because comparing per bag makes the arithmetic harder than it needs to be",
            "Because the bags do the same job for different numbers of trips each",
            "Because the mass of a bag changes each time it is loaded and emptied",
        ],
        "correct_index": 2,
        "why": "A fair comparison measures the impact of delivering the same "
               "service, and a durable bag delivers it many times over.",
    },
    {
        "id": "ks4-life-cycle-assessment-h14",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A council can either recycle a mixed plastic waste stream or incinerate it with energy recovery. Evaluate the two routes.",
        "options": [
            "Recycling is better in every case, because no energy is used to recycle plastic",
            "Incineration is better in every case, because it removes the waste completely",
            "The two routes are identical, because both keep the waste out of landfill sites",
            "Recycling saves raw material but mixed plastics are costly to sort and reprocess",
        ],
        "correct_index": 3,
        "why": "Recycling preserves the material, but a mixed stream may need so "
               "much sorting energy that recovering the heat competes with it.",
    },
    {
        "id": "ks4-life-cycle-assessment-h15",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A redesign cuts a product's lifetime energy from 250 kWh to 190 kWh. Calculate the percentage reduction.",
        "options": [
            "60%, taking the 60 kWh saving as the percentage directly",
            "31.6%, dividing the saving by the new figure rather than the old",
            "24%, dividing the 60 kWh saving by the original 250 kWh",
            "76%, which is the new figure as a percentage of the original",
        ],
        "correct_index": 2,
        "why": "The saving is 250 - 190 = 60 kWh, and 60 divided by 250 is 24%.",
    },
    {
        "id": "ks4-life-cycle-assessment-h16",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A bag is sold as biodegradable, and in landfill it decays without oxygen to release methane. Evaluate how this affects its assessment.",
        "options": [
            "It improves the assessment, because a decaying bag occupies no landfill space",
            "It worsens the disposal stage, because methane is a strong greenhouse gas",
            "It has no effect, because gases released in landfill are not assessed",
            "It improves the assessment, because methane can be recovered as a fuel",
        ],
        "correct_index": 1,
        "why": "Anaerobic decay in a landfill produces methane, which traps far more "
               "heat per molecule than the carbon dioxide it replaces.",
    },
    {
        "id": "ks4-life-cycle-assessment-h17",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Determine which single piece of data matters most in the assessment of a family car, and explain why.",
        "options": [
            "The mass of steel in the body, because extracting iron dominates the impact",
            "The fuel it burns over its whole life, because the use stage dominates a car",
            "The volume of paint sprayed on it, because solvents are released in the factory",
            "The number of tyres fitted, because rubber must be tapped from trees",
        ],
        "correct_index": 1,
        "why": "A car is driven for many years, and the fuel consumed in that time "
               "outweighs the energy of building it.",
    },
    {
        "id": "ks4-life-cycle-assessment-h18",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that a product shipped from abroad must have a worse assessment than one made locally.",
        "options": [
            "The claim holds, because transport is the largest impact for any product",
            "The claim holds, because a local product has no transport stage of its own",
            "The claim is weak, because transport is excluded from a life cycle assessment",
            "The claim is weak: sea freight per tonne is efficient, and manufacture may dominate",
        ],
        "correct_index": 3,
        "why": "Moving a tonne by ship costs little energy per kilometre, so a "
               "cleaner factory abroad can still give the lower total.",
    },
    {
        "id": "ks4-life-cycle-assessment-h19",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A firm calls its product carbon neutral on the basis of its use stage alone. Evaluate the claim.",
        "options": [
            "It is sound, because the use stage lasts far longer than all of the other stages put together",
            "It is sound, because a product that emits nothing in use emits nothing overall",
            "It is unsound, because extraction, manufacture and disposal all release carbon dioxide",
            "It is unsound, because carbon neutrality cannot be assessed for any product",
        ],
        "correct_index": 2,
        "why": "Neutrality is a claim about the whole life cycle, and three of the "
               "four stages have been left out of the calculation.",
    },
    {
        "id": "ks4-life-cycle-assessment-h20",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why an assessment can favour a product that takes more energy to manufacture.",
        "options": [
            "Because it lasts far longer, so its impact is spread across more years of use",
            "Because a higher manufacturing energy shows that better materials were used",
            "Because the manufacturing stage is weighted less than the other three stages",
            "Because energy used in a factory is not counted towards the product's total",
        ],
        "correct_index": 0,
        "why": "A durable article is replaced less often, so the total impact of "
               "meeting the same need over many years can be lower.",
    },
    {
        "id": "ks4-life-cycle-assessment-h21",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "An assessment assumed a product would last ten years, but in practice owners replace it after five. Determine the effect on the assessment's conclusion.",
        "options": [
            "None, since the assumed lifetime is not used at any point in the whole of the assessment calculation",
            "The product looks better, because half as much energy is used while it is in service",
            "The manufacturing impact per year of service doubles, so the conclusion may reverse",
            "The disposal impact halves, because the product is thrown away sooner",
        ],
        "correct_index": 2,
        "why": "The one-off manufacturing impact is spread over five years instead "
               "of ten, which can overturn a narrow verdict.",
    },
    {
        "id": "ks4-life-cycle-assessment-h22",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate comparing a rechargeable battery with a disposable one using the disposal stage alone.",
        "options": [
            "It is valid, because disposal is where the difference between them lies",
            "It is valid, because both batteries are made by the same chemical process",
            "It is invalid: one rechargeable replaces many disposables, which the other stages show",
            "It is invalid, because a rechargeable battery reaches no disposal stage",
        ],
        "correct_index": 2,
        "why": "The rechargeable battery's advantage is that its manufacture serves "
               "hundreds of cycles, and only a full assessment records that.",
    },
    {
        "id": "ks4-life-cycle-assessment-h23",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "An assessment finds a cotton bag must be used 270 times to match a plastic one. A shopper uses a bag twice a week. Calculate how long this takes.",
        "options": [
            "About 135 years, dividing 270 by two and calling the weeks years",
            "About 5 years, dividing 270 by the 52 weeks in a year",
            "About 270 weeks, taking one use per week rather than two",
            "About 2.6 years, since 270 divided by 104 uses a year is 2.6",
        ],
        "correct_index": 3,
        "why": "Twice a week is 104 uses a year, and 270 divided by 104 is about "
               "2.6 years.",
    },
    {
        "id": "ks4-life-cycle-assessment-h24",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate using life cycle assessments to set a legal minimum recycled content for bottles.",
        "options": [
            "It is a poor use, because an assessment describes a product, not a rule",
            "It is a poor use, because recycled content is not one of the things assessed",
            "It is a good use: the assessments show where impact falls and make the target evidence-based",
            "It is a good use, because a legal minimum removes the need for further assessment",
        ],
        "correct_index": 2,
        "why": "Regulation works best when it targets the stage the evidence says "
               "carries the impact, which is what an assessment identifies.",
    },
    {
        "id": "ks4-life-cycle-assessment-h25",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two analysts assess the same product and disagree because one treats land use as a major impact and the other as minor. Explain how this reverses the conclusion.",
        "options": [
            "One analyst must have measured the land area wrongly, which changes the total",
            "Weighting land use heavily penalises the crop-based product over the fossil one",
            "Land use belongs to no stage, so including it makes an assessment invalid",
            "Land use is measured in hectares, and hectares cannot appear in an assessment",
        ],
        "correct_index": 1,
        "why": "A crop-based product uses far more land, so how much that counts for "
               "decides which product comes out ahead.",
    },
    {
        "id": "ks4-life-cycle-assessment-h26",
        "subtopic_slug": "life-cycle-assessment",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that an assessment covering all four stages cannot be challenged.",
        "options": [
            "The claim holds, because covering all four of the stages is by definition a study that is complete",
            "The claim holds, because a complete study reports measurements rather than opinions of any kind",
            "The claim is weak, because no study has ever managed to cover all four stages",
            "The claim is weak: the data, the boundaries and the weightings can each be questioned",
        ],
        "correct_index": 3,
        "why": "Completeness of stages is one test among several; the figures used "
               "and the importance given to each impact are open to scrutiny.",
    },
]
