"""Biology · Homeostasis and Response — the MRB-338 expansion, subtopic
`defects-of-the-eye`.

The baseline twelve cover the negative power of a concave lens, presbyopia,
where a contact lens sits, the rise in short-sight among young people, the
"long-sight is a long eyeball" error, laser surgery for long sight, a
17-year-old asking about laser surgery, and a stiff over-curved lens.

This file goes wider. It sets out the two defects side by side — which
distances blur, where the image would form, and the two causes of each — and
pairs each with the lens that corrects it, taking converging and diverging as
the property that does the work. It covers the other correction routes named
in the specification: hard and soft contact lenses with their trade-offs,
laser surgery on the cornea and its risks, and replacement-lens surgery. It
adds how an optician measures a prescription, what a dioptre reading means,
why a prescription changes through childhood, and a set of comparison rows on
cost, risk, reversibility and convenience.
"""

TOPIC = "homeostasis"
SUBJECT = "biology"

QUESTIONS = [
    {
        "id": "ks4-defects-of-the-eye-e05",
        "subtopic_slug": "defects-of-the-eye",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Which distances does a person with short sight see clearly?",
        "options": [
            "Near ones",
            "Distant ones, though near objects look blurred to them",
            "Both near and distant ones, once their eyes have rested",
            "Neither near nor distant ones, at any time of the day",
        ],
        "correct_index": 0,
        "why": "Short sight, or myopia, means close objects are seen clearly while distant ones are blurred.",
    },
    {
        "id": "ks4-defects-of-the-eye-e06",
        "subtopic_slug": "defects-of-the-eye",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "What is the medical name for short sight?",
        "options": [
            "Hyperopia, which is the term used for the opposite defect",
            "Myopia",
            "Presbyopia, which is the stiffening of the lens with age",
            "Astigmatism, which is caused by an unevenly curved cornea",
        ],
        "correct_index": 1,
        "why": "Myopia is short sight; hyperopia is long sight and presbyopia is the age-related loss of flexibility.",
    },
    {
        "id": "ks4-defects-of-the-eye-e07",
        "subtopic_slug": "defects-of-the-eye",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Which type of lens is used to correct long sight?",
        "options": [
            "A concave lens, which spreads the light rays outwards",
            "A lens with no curve on either of its two surfaces",
            "A convex lens",
            "A lens made of coloured glass to cut down the light",
        ],
        "correct_index": 2,
        "why": "Long sight needs extra converging power, which a convex lens supplies.",
    },
    {
        "id": "ks4-defects-of-the-eye-e08",
        "subtopic_slug": "defects-of-the-eye",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "What does a convex lens do to the light rays passing through it?",
        "options": [
            "It spreads them apart so that they meet further away",
            "It stops some of them and lets the rest through unchanged",
            "It reflects them back out towards the object they came from",
            "It brings them together",
        ],
        "correct_index": 3,
        "why": "A convex lens is a converging lens: it bends parallel rays inwards towards a focus.",
    },
    {
        "id": "ks4-defects-of-the-eye-e09",
        "subtopic_slug": "defects-of-the-eye",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "In an uncorrected short-sighted eye, where is the image of a distant object formed?",
        "options": [
            "In front of the retina",
            "Behind the retina, somewhere towards the back of the eye socket",
            "Exactly on the retina, though the image is dimmer than usual",
            "On the blind spot, where the optic nerve leaves the eyeball",
        ],
        "correct_index": 0,
        "why": "The eye refracts the light too strongly for its length, so the rays cross before they reach the retina.",
    },
    {
        "id": "ks4-defects-of-the-eye-e10",
        "subtopic_slug": "defects-of-the-eye",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Which correction involves changing the shape of the cornea itself?",
        "options": [
            "Wearing a pair of spectacles with the right lens in each side",
            "Laser eye surgery",
            "Wearing soft contact lenses during the day and removing them at night",
            "Having an artificial lens fitted inside the eye by a surgeon",
        ],
        "correct_index": 1,
        "why": "Laser surgery removes a thin layer of corneal tissue to alter how strongly the cornea refracts light.",
    },
    {
        "id": "ks4-defects-of-the-eye-e11",
        "subtopic_slug": "defects-of-the-eye",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "What unit is a spectacle prescription given in?",
        "options": [
            "Millimetres, measured across the width of the lens itself",
            "Degrees, measured at the edge where the lens is thinnest",
            "Dioptres",
            "Lux, the same unit that is used for measuring light intensity",
        ],
        "correct_index": 2,
        "why": "Lens power is measured in dioptres, written as a negative value for a concave lens and a positive one for a convex lens.",
    },
    {
        "id": "ks4-defects-of-the-eye-e12",
        "subtopic_slug": "defects-of-the-eye",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Which of these is a risk of wearing contact lenses that spectacles do not carry?",
        "options": [
            "They may become scratched if they are dropped on a hard floor",
            "They are more expensive to replace than a pair of spectacles",
            "They can slip out of position during a game of sport",
            "An eye infection, because the lens sits on the surface of the eye",
        ],
        "correct_index": 3,
        "why": "A lens worn directly on the cornea can carry bacteria onto it, which is why hygiene matters so much with contact lenses.",
    },
    {
        "id": "ks4-defects-of-the-eye-s05",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Give the two possible causes of short sight.",
        "options": [
            "An eyeball that is too long, or a lens that is too strongly curved",
            "An eyeball that is too short, or a cornea that has become too flat",
            "A lens that has lost its flexibility, or a damaged optic nerve",
            "A retina that has become detached, or a pupil that stays too wide",
        ],
        "correct_index": 0,
        "why": "Either the eye is too long for the refraction it produces, or it refracts too strongly for its length.",
    },
    {
        "id": "ks4-defects-of-the-eye-s06",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain how a convex lens in front of a long-sighted eye brings a near object into focus.",
        "options": [
            "It reduces the light entering the eye so the image looks sharper there",
            "It converges the rays before they enter, so they focus on the retina",
            "It makes the whole image larger so that more of it lands on the fovea",
            "It moves the retina backwards until it lies in line with the new focal point",
        ],
        "correct_index": 1,
        "why": "The eye alone cannot refract the diverging rays from a near object enough, so a converging lens does part of the job first.",
    },
    {
        "id": "ks4-defects-of-the-eye-s07",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A prescription reads minus 1.0 dioptres in one eye and minus 4.5 dioptres in the other. Interpret this.",
        "options": [
            "Both eyes are long-sighted, and the second one more severely so",
            "One eye is short-sighted and the other is long-sighted",
            "Both eyes are short-sighted, and the second one more severely so",
            "One eye is healthy and the other has lost its focusing ability",
        ],
        "correct_index": 2,
        "why": "A negative value means a concave lens is needed, which corrects short sight, and the larger the number the stronger the correction.",
    },
    {
        "id": "ks4-defects-of-the-eye-s08",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a person with long sight may still see distant objects clearly without glasses.",
        "options": [
            "Distant objects are brighter, so the retina can detect them more easily",
            "The pupil narrows for distant objects and that sharpens the image",
            "Distant rays arrive almost parallel, so less refraction is needed",
            "The lens is stiffer for distant vision than it is for close work",
        ],
        "correct_index": 2,
        "why": "The defect is a shortage of refracting power, and distant objects make the smallest demand on it.",
    },
    {
        "id": "ks4-defects-of-the-eye-s09",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Describe one advantage of soft contact lenses over hard ones.",
        "options": [
            "Soft lenses give sharper vision than any other correction available",
            "Soft lenses cannot carry any bacteria onto the eye surface",
            "Soft lenses last for several years before they need replacing",
            "Soft lenses are more comfortable to wear for a long period",
        ],
        "correct_index": 3,
        "why": "Soft lenses mould to the shape of the eye, which most wearers find more comfortable; hard lenses are more durable.",
    },
    {
        "id": "ks4-defects-of-the-eye-s10",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why a footballer might prefer contact lenses to spectacles.",
        "options": [
            "Contact lenses correct a stronger prescription than any spectacles can",
            "Contact lenses need no cleaning between one match and the next",
            "Contact lenses will not be knocked off or broken during play",
            "Contact lenses protect the eye from being hit by the ball",
        ],
        "correct_index": 2,
        "why": "A lens worn on the eye stays in place during hard physical activity, and there is no frame to break.",
    },
    {
        "id": "ks4-defects-of-the-eye-s11",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "An optician asks a patient to read letters on a chart six metres away. Explain what this tests.",
        "options": [
            "Whether the patient can bring distant objects into a clear focus",
            "Whether the patient can distinguish one colour from another one",
            "Whether the patient's pupil responds to the light in the room",
            "Whether the patient's eyes move together when they are following an object",
        ],
        "correct_index": 0,
        "why": "At that distance the rays are near enough parallel, so the test shows whether the eye focuses distant light on the retina.",
    },
    {
        "id": "ks4-defects-of-the-eye-s12",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why laser surgery for short sight makes the cornea flatter.",
        "options": [
            "A flatter cornea lets more light pass through into the eyeball",
            "A flatter cornea moves the whole lens further from the retina",
            "A flatter cornea refracts less strongly, so the focus moves back to the retina",
            "A flatter cornea is easier for the ciliary muscle to work against",
        ],
        "correct_index": 2,
        "why": "Short sight is too much refraction for the length of the eye, so reducing the corneal curvature moves the image back onto the retina.",
    },
    {
        "id": "ks4-defects-of-the-eye-s13",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Describe what happens in replacement lens surgery.",
        "options": [
            "A thin layer is removed from the front surface of the cornea",
            "The eye's own lens is taken out and an artificial one is put in",
            "A small lens is fixed to the outside of the eyeball with fine stitches",
            "The muscles around the lens are tightened so it can change shape",
        ],
        "correct_index": 1,
        "why": "The natural lens is removed and a plastic lens of the required power is placed inside the eye.",
    },
    {
        "id": "ks4-defects-of-the-eye-s14",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why replacement lens surgery carries more risk than wearing spectacles.",
        "options": [
            "Spectacles can be taken off, so their effect is never permanent",
            "Surgery inside the eye may damage the retina or let in infection",
            "An artificial lens has to be replaced again every year or so",
            "Spectacle lenses are made of a material that cannot break",
        ],
        "correct_index": 1,
        "why": "Any operation opening the eye brings a risk of infection and of damage to the delicate structures inside it.",
    },
    {
        "id": "ks4-defects-of-the-eye-s15",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a child's spectacle prescription is usually checked every year.",
        "options": [
            "Spectacle lenses wear thin after about a year of regular use",
            "An annual check is needed before new frames can be supplied",
            "Children lose the ability to focus if they wear glasses for long",
            "The eye grows as the child does, so the correction needed changes",
        ],
        "correct_index": 3,
        "why": "A growing eyeball changes length, which changes where the image falls and so changes the lens power required.",
    },
    {
        "id": "ks4-defects-of-the-eye-s16",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why glasses remain the most common correction despite laser surgery being available.",
        "options": [
            "Glasses correct defects that laser surgery is unable to correct",
            "Glasses are cheap, carry no surgical risk and can be changed later",
            "Laser surgery has to be repeated every few years to keep working",
            "Laser surgery is only offered to patients who are over seventy",
        ],
        "correct_index": 1,
        "why": "Spectacles need no operation, cost far less and can simply be swapped when a prescription changes.",
    },
    {
        "id": "ks4-defects-of-the-eye-s17",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A patient has been fitted with an artificial lens that cannot change shape. Predict how this affects their vision.",
        "options": [
            "They see nothing clearly until the ciliary muscle has grown stronger",
            "They see clearly at one range and need glasses for the other",
            "They see clearly at every distance without any further help",
            "They see clearly only in bright light and never in dim light",
        ],
        "correct_index": 1,
        "why": "A fixed lens cannot accommodate, so the eye is corrected for one range and reading glasses are usually still needed.",
    },
    {
        "id": "ks4-defects-of-the-eye-s18",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a concave lens is described as having a negative power.",
        "options": [
            "It is thinner in the middle than it is around the outer edge",
            "It weakens the eye's own focusing ability over a period of years",
            "It spreads rays apart, the opposite of what a convex lens does",
            "It is worn by people whose sight is worse than the average for their age",
        ],
        "correct_index": 2,
        "why": "The sign records the direction of the effect: converging power is counted positive and diverging power negative.",
    },
    {
        "id": "ks4-defects-of-the-eye-s19",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "A patient reports that their vision has been blurred in the distance since they were about twelve. Determine the most likely defect.",
        "options": [
            "Long sight, because it appears in childhood rather than later",
            "Presbyopia, because the lens stiffens throughout childhood",
            "A detached retina, which always develops during adolescence",
            "Short sight, which often develops during the school years",
        ],
        "correct_index": 3,
        "why": "Myopia commonly appears and worsens while the eye is still growing, and it is distant vision that blurs.",
    },
    {
        "id": "ks4-defects-of-the-eye-s20",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why an optician tries several different lenses in a frame during a sight test.",
        "options": [
            "To find the weakest lens that brings the chart into clear focus",
            "To let the patient choose the lens they find most comfortable",
            "To check that the patient's pupils are the same size as each other",
            "To make sure the frame is the right width for the patient's face",
        ],
        "correct_index": 0,
        "why": "The prescription is the lens power that corrects the focus, and it is found by testing rather than calculated from the eye.",
    },
    {
        "id": "ks4-defects-of-the-eye-s21",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why hard contact lenses can give sharper vision than soft ones.",
        "options": [
            "They are made of a material that lets in more light than soft ones",
            "They hold a precise shape rather than moulding to the eye surface",
            "They sit further from the cornea and so magnify the image more",
            "They can be worn overnight, which allows the eye to adjust itself to them",
        ],
        "correct_index": 1,
        "why": "A rigid lens keeps its own curvature, so it gives a more exact correction than a lens that follows the shape underneath it.",
    },
    {
        "id": "ks4-defects-of-the-eye-s22",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why someone whose eyeball is slightly too short struggles most when threading a needle.",
        "options": [
            "The needle is too thin to reflect enough light into the eye",
            "Near work needs the most refraction, which that eye cannot supply",
            "The pupil narrows for close work and lets too little light through",
            "The lens flattens for close work, which makes the problem worse",
        ],
        "correct_index": 1,
        "why": "A short eyeball provides too little refraction for its length, and close objects are the ones needing the most.",
    },
    {
        "id": "ks4-defects-of-the-eye-s23",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why contact lens wearers are told never to rinse their lenses in tap water.",
        "options": [
            "Tap water would dissolve the material the lens is made from",
            "Tap water would make the lens cloudy and hard to see through",
            "Tap water can carry microorganisms that then infect the cornea",
            "Tap water changes the power of the lens by softening its surface",
        ],
        "correct_index": 2,
        "why": "Tap water is not sterile, and a lens carries whatever is on it straight onto the surface of the eye.",
    },
    {
        "id": "ks4-defects-of-the-eye-s24",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Describe how the two defects differ in where the image would form without correction.",
        "options": [
            "Both form the image in front of the retina, but at quite different distances",
            "Short sight forms it in front of the retina; long sight behind it",
            "Short sight forms it behind the retina; long sight in front of it",
            "Both form the image behind the retina, though only for near objects",
        ],
        "correct_index": 1,
        "why": "Too much refraction for the length of the eye brings the focus forward, and too little pushes it back.",
    },
    {
        "id": "ks4-defects-of-the-eye-s25",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why an adult in their fifties may need reading glasses although their distance vision is unchanged.",
        "options": [
            "The retina loses cones with age, and cones are used for reading",
            "The pupil widens with age and lets in too much light for reading",
            "The eyeball shortens with age, which affects close work first",
            "The lens has stiffened, so it can no longer round itself up for close work",
        ],
        "correct_index": 3,
        "why": "Accommodation for near objects depends on an elastic lens, and it is that elasticity which is lost with age.",
    },
    {
        "id": "ks4-defects-of-the-eye-s26",
        "subtopic_slug": "defects-of-the-eye",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest one reason why some people cannot be offered laser surgery even when they want it.",
        "options": [
            "Their cornea may be too thin for tissue to be safely removed",
            "Their prescription may be written in dioptres rather than degrees",
            "They may already own a pair of spectacles that still work well",
            "They may need to wear contact lenses for sport at the weekend",
        ],
        "correct_index": 0,
        "why": "The procedure removes corneal tissue, so there has to be enough of it to leave a strong cornea behind.",
    },
    {
        "id": "ks4-defects-of-the-eye-h05",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A student writes: 'A convex lens corrects short sight by spreading the rays out before they enter the eye.' Identify the correction needed.",
        "options": [
            "Short sight is corrected by a concave lens, which is what diverges rays",
            "Short sight is corrected by a convex lens, but it converges the rays",
            "Short sight needs no lens at all, only a change in the eye's length",
            "Short sight is corrected by a concave lens, which converges the rays",
        ],
        "correct_index": 0,
        "why": "Diverging the rays first is the right idea, but it is a concave lens that does it.",
    },
    {
        "id": "ks4-defects-of-the-eye-h06",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why the same person can be short-sighted at sixteen and also need reading glasses at sixty.",
        "options": [
            "Short sight turns into long sight once a person reaches middle age",
            "Their eyeball shortens again as the tissues of the eye lose water",
            "The two have separate causes: eye length, and the ageing of the lens",
            "The first prescription was wrong and the second one corrects it",
        ],
        "correct_index": 2,
        "why": "Myopia is about the length of the eye against its refracting power; presbyopia is a loss of lens flexibility, and both can be present.",
    },
    {
        "id": "ks4-defects-of-the-eye-h07",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Predict what a short-sighted person would see through a pair of glasses made for long sight.",
        "options": [
            "Their distance vision would be even more blurred than before",
            "Their distance vision would become clear for the first time",
            "Their near vision would blur but their distance vision would sharpen up",
            "Nothing would change, since a lens only works for one eye at a time",
        ],
        "correct_index": 0,
        "why": "A convex lens adds still more converging power to an eye that already refracts too strongly, so the focus moves even further forward.",
    },
    {
        "id": "ks4-defects-of-the-eye-h08",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Compare laser surgery with wearing contact lenses in terms of what can be undone afterwards.",
        "options": [
            "Neither can be undone once the patient has begun the treatment",
            "Laser surgery can be reversed, while contact lens wear cannot be",
            "Both can be reversed, though laser surgery takes several months",
            "Contact lenses can simply be stopped; the surgery is permanent",
        ],
        "correct_index": 3,
        "why": "Removing corneal tissue cannot be put back, whereas a wearer can stop using contact lenses whenever they choose.",
    },
    {
        "id": "ks4-defects-of-the-eye-h09",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "In one class of 30 pupils, 12 wear glasses. Calculate the percentage who wear them.",
        "options": [
            "12%, taking the number of wearers as a percentage on its own",
            "40%",
            "2.5%, obtained by dividing the class size by the number wearing them",
            "18%, obtained by subtracting the wearers from the size of the class",
        ],
        "correct_index": 1,
        "why": "12 divided by 30 is 0.4, which is 40%.",
    },
    {
        "id": "ks4-defects-of-the-eye-h10",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why a person with very severe short sight may be offered a replacement lens rather than laser surgery.",
        "options": [
            "Replacement lenses are cheaper than the laser treatment is",
            "A replacement lens can be taken out again if it does not suit them",
            "Laser surgery cannot be carried out on anyone who is short-sighted",
            "The correction needed is more than reshaping the cornea can provide",
        ],
        "correct_index": 3,
        "why": "There is a limit to how much the cornea can safely be flattened, so a very strong correction has to come from inside the eye.",
    },
    {
        "id": "ks4-defects-of-the-eye-h11",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a person's vision is blurred rather than dark when their eye focuses the image in the wrong place.",
        "options": [
            "The light still reaches the retina, but spread out rather than in focus",
            "The retina detects only part of the light that arrives at the eye",
            "The pupil closes down to protect the retina from an unfocused image",
            "The brain refuses to interpret an image it cannot make sense of",
        ],
        "correct_index": 0,
        "why": "Every ray still lands on the retina; they simply do not meet at a point, so each point of the object is smeared out.",
    },
    {
        "id": "ks4-defects-of-the-eye-h12",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Determine which patient would need the strongest concave lens: one whose focus falls a long way short of the retina, or one whose focus falls only just short of it.",
        "options": [
            "The second, because a small error is harder to correct with precision",
            "The first, because the focus has to be moved back much further",
            "Both would need exactly the same strength of lens as each other",
            "Neither, because a concave lens is not used for this defect",
        ],
        "correct_index": 1,
        "why": "The further forward the focus falls, the more diverging power is needed to push it back onto the retina.",
    },
    {
        "id": "ks4-defects-of-the-eye-h13",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Evaluate the claim that laser surgery is always the best choice for an adult with a stable prescription.",
        "options": [
            "Sound, since it removes the need for glasses for the rest of their life",
            "Unsound, because a stable prescription rules the surgery out entirely",
            "Sound, since the risks of the surgery are the same as wearing lenses",
            "Too strong — it suits many people, but cost and surgical risk still count",
        ],
        "correct_index": 3,
        "why": "A stable prescription makes someone a suitable candidate, but suitability is not the same as it being best for everyone.",
    },
    {
        "id": "ks4-defects-of-the-eye-h14",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why an optician would be concerned if a young adult's prescription changed by a large amount in six months.",
        "options": [
            "Lenses cannot be made accurately for a prescription that keeps changing",
            "A rapid change may point to a problem needing medical investigation",
            "A change of that size means the first test must have been done wrongly",
            "It shows that the patient has not been wearing their glasses enough",
        ],
        "correct_index": 1,
        "why": "Adult prescriptions usually settle, so a sudden large shift is a sign worth investigating rather than simply correcting.",
    },
    {
        "id": "ks4-defects-of-the-eye-h15",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A patient is fitted with contact lenses and their vision is clear, but after a week the eye is red and painful. Determine the most likely explanation.",
        "options": [
            "The lens power is slightly too strong for that particular eye",
            "The eye has grown used to the lens and no longer needs it",
            "An infection or irritation has developed on the eye surface",
            "The cornea has changed shape to match the curve of the lens",
        ],
        "correct_index": 2,
        "why": "Clear vision shows the power is right, so redness and pain point to infection or irritation rather than a focusing fault.",
    },
    {
        "id": "ks4-defects-of-the-eye-h16",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why correcting a defect with a lens does not cure the eye itself.",
        "options": [
            "The lens is worn in front of the eye and changes nothing inside it",
            "The lens works for distant objects but leaves near ones uncorrected",
            "The lens corrects the image while the pupil stays at one particular size",
            "The lens has to be replaced each year, so the effect is temporary",
        ],
        "correct_index": 0,
        "why": "A spectacle or contact lens adjusts the light arriving; the length of the eyeball and the state of its own lens are unchanged.",
    },
    {
        "id": "ks4-defects-of-the-eye-h17",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Two patients are corrected to the same standard of vision, one with spectacles and one after laser surgery. Compare the ongoing costs they face.",
        "options": [
            "Both face the same cost, since each needs an annual check-up",
            "The spectacle wearer pays more, as the surgery has no further cost",
            "The surgery patient pays more, because the effect wears off in time",
            "The spectacle wearer keeps paying for new lenses; the surgery was one payment",
        ],
        "correct_index": 3,
        "why": "Spectacles are cheap at the start but are replaced repeatedly, while the surgery is a single large cost.",
    },
    {
        "id": "ks4-defects-of-the-eye-h18",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Determine what would happen to a corrected short-sighted eye if the person's eyeball then grew longer still.",
        "options": [
            "Their vision would improve, as the eye moved towards a normal length",
            "The existing lens would become too weak and vision would blur again",
            "Their vision would be unaffected, because the lens does all the work",
            "The existing lens would become too strong and objects would look larger",
        ],
        "correct_index": 1,
        "why": "A longer eye pushes the focus further in front of the retina, so a stronger diverging lens would be needed than before.",
    },
    {
        "id": "ks4-defects-of-the-eye-h19",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why the number of young people needing glasses for distance vision has risen in many countries.",
        "options": [
            "Eye tests have become less accurate than they were in the recent past",
            "Children spend longer on close work and less time outdoors",
            "Modern lighting is brighter and damages the growing eyeball",
            "Diets now contain less of the vitamin the retina needs",
        ],
        "correct_index": 1,
        "why": "Long periods of close work with little time outdoors is the pattern most strongly associated with the rise in myopia.",
    },
    {
        "id": "ks4-defects-of-the-eye-h20",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a study showing that children who read more are more short-sighted does not prove that reading causes short sight.",
        "options": [
            "Reading is done indoors, and indoor lighting is the true cause here",
            "The children may have been tested with different eye charts",
            "Short sight could make a child prefer reading to distant activities",
            "A study of children cannot be applied to anybody who is older",
        ],
        "correct_index": 2,
        "why": "The association could run the other way round, so correlation on its own does not establish which is cause and which is effect.",
    },
    {
        "id": "ks4-defects-of-the-eye-h21",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A lens of plus 2.0 dioptres is replaced by one of plus 5.0 dioptres. Calculate the increase in power.",
        "options": [
            "10.0 dioptres, found by multiplying the two lens powers together",
            "2.5 dioptres, found by dividing the larger power by the smaller",
            "7.0 dioptres, found by adding the two lens powers to each other",
            "3.0 dioptres",
        ],
        "correct_index": 3,
        "why": "5.0 minus 2.0 gives 3.0.",
    },
    {
        "id": "ks4-defects-of-the-eye-h22",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a patient whose lens has been replaced no longer experiences the age-related loss of near focus.",
        "options": [
            "The artificial lens is more flexible than a natural lens ever was",
            "The ciliary muscle is strengthened during the operation itself",
            "The artificial lens cannot stiffen, though it cannot accommodate either",
            "The cornea takes over the accommodation once the lens is replaced",
        ],
        "correct_index": 2,
        "why": "The problem of a stiffening natural lens is removed with the lens, but the replacement does not change shape at all.",
    },
    {
        "id": "ks4-defects-of-the-eye-h23",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Determine which correction would suit a patient who wants clear vision for sport but cannot risk any surgery.",
        "options": [
            "Laser reshaping of the cornea, done one eye at a time",
            "A replacement lens fitted inside the eye by a surgeon",
            "Contact lenses, which stay in place and need no operation",
            "No correction at all, since sport does not call for very sharp vision",
        ],
        "correct_index": 2,
        "why": "Contact lenses give the practical advantages of surgery for sport without anything being done to the eye permanently.",
    },
    {
        "id": "ks4-defects-of-the-eye-h24",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A student says that because both defects are corrected with a lens, they must have the same cause. Evaluate this claim.",
        "options": [
            "Sound, since any focusing fault comes from the shape of the lens",
            "Unsound — one eye refracts too strongly and the other too weakly",
            "Sound, because both are caused by an eyeball of the wrong length",
            "Unsound, because long sight is not corrected with a lens at all",
        ],
        "correct_index": 1,
        "why": "Using the same kind of remedy says nothing about the cause, and the two defects lie in opposite directions.",
    },
    {
        "id": "ks4-defects-of-the-eye-h25",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why an optician measures each eye separately rather than giving one prescription for both.",
        "options": [
            "The two eyes can differ, and each needs the correction that suits it",
            "One eye is used for distance and the other for close work",
            "Measuring separately takes less time than testing them together",
            "The brain uses only one eye at a time when it forms an image",
        ],
        "correct_index": 0,
        "why": "Eye length and refracting power are not always the same on both sides, so each eye is prescribed for on its own.",
    },
    {
        "id": "ks4-defects-of-the-eye-h26",
        "subtopic_slug": "defects-of-the-eye",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why someone who has worn the same glasses for ten years may find their vision has worsened even though the lenses are undamaged.",
        "options": [
            "Lenses lose their power slowly over a period of several years",
            "Wearing glasses for a long time weakens the muscles of the eye",
            "The frames have bent and moved the lenses out of position",
            "Their eyes have changed, so the old prescription no longer fits",
        ],
        "correct_index": 3,
        "why": "The lens is unchanged; it is the eye that has altered, so the correction it was made for is no longer the right one.",
    },
]
