"""Biology · Homeostasis and Response — the MRB-338 expansion, subtopic
`reaction-time`.

The baseline twelve cover the definition, what the ruler drop measures, the
fastest kind of stimulus, a typical adult value, a ruler comparison, the
weakness of a single caffeine measurement, alcohol at the synapse, a
percentage increase after a sleepless night, two ruler-drop conversions, a
mean of five trials and the accuracy of a computer test.

This file goes wider. It takes the ruler-drop investigation as a method —
the variables that must be held the same, practice runs, anomalous results,
the resolution of the ruler and why a distance has to be converted to a time
— and the design of a fair comparison, including a control group and the
random interval a computer test uses to stop the subject anticipating. It
covers the factors that change reaction time (age, tiredness, distraction,
practice, illness, drugs), the difference between a simple and a choice
reaction, and the road-safety consequence: thinking distance, its place in
the stopping distance, and why it grows with speed. Several rows read values
from a set of trial results.
"""

TOPIC = "homeostasis"
SUBJECT = "biology"

QUESTIONS = [
    {
        "id": "ks4-reaction-time-e05",
        "subtopic_slug": "reaction-time",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which of these would be expected to make a person's reaction time longer?",
        "options": [
            "Drinking a cup of strong coffee about twenty minutes before the test begins",
            "Practising the test several times before the readings are taken",
            "Being tired",
            "Sitting quietly in a room with no noise or other distractions",
        ],
        "correct_index": 2,
        "why": "Tiredness slows the nervous system, while caffeine and practice both tend to shorten reaction time.",
    },
    {
        "id": "ks4-reaction-time-e06",
        "subtopic_slug": "reaction-time",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "In the ruler drop test, where should the catcher's fingers be before the ruler is released?",
        "options": [
            "Open, level with the zero mark on the ruler",
            "Closed lightly around the middle of the ruler so that it cannot slip",
            "Open, level with the highest number marked on the whole ruler",
            "Resting on the edge of the table underneath the falling ruler",
        ],
        "correct_index": 0,
        "why": "Starting level with zero means the measurement read at the fingers is the distance the ruler has actually fallen.",
    },
    {
        "id": "ks4-reaction-time-e07",
        "subtopic_slug": "reaction-time",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Why is caffeine described as a stimulant?",
        "options": [
            "It is added to drinks that are sold in most supermarkets and cafes",
            "It increases the activity at synapses in the nervous system",
            "It provides the body with extra energy in the form of sugar",
            "It sends the drinker off to sleep much more quickly than they otherwise would",
        ],
        "correct_index": 1,
        "why": "A stimulant raises the activity of the nervous system, which is why caffeine tends to shorten reaction time.",
    },
    {
        "id": "ks4-reaction-time-e08",
        "subtopic_slug": "reaction-time",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "What name is given to the distance a car travels while the driver is reacting?",
        "options": [
            "The braking distance, which is measured from the brakes going on",
            "The stopping distance, measured from seeing the hazard to coming to a halt",
            "The safe following distance recommended in the Highway Code",
            "The thinking distance",
        ],
        "correct_index": 3,
        "why": "Thinking distance is the distance covered during the driver's reaction time, before the brakes are applied at all.",
    },
    {
        "id": "ks4-reaction-time-e09",
        "subtopic_slug": "reaction-time",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which piece of equipment is used to measure the ruler drop distance?",
        "options": [
            "The scale of millimetres and centimetres printed on the ruler",
            "A stopwatch started as the ruler is let go of by the helper",
            "A light gate placed just above the fingers of the catcher",
            "A metre rule held horizontally across the top of the table",
        ],
        "correct_index": 0,
        "why": "The ruler is its own measuring scale: the reading at the fingers gives the distance fallen.",
    },
    {
        "id": "ks4-reaction-time-e10",
        "subtopic_slug": "reaction-time",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which of these is a choice reaction rather than a simple one?",
        "options": [
            "Catching a ruler as soon as it is seen to start falling downwards",
            "Pressing a button the moment a single lamp comes on in front of you",
            "Pressing the left-hand button for a red light and the right one for green",
            "Releasing a stopwatch the instant a whistle is heard being blown",
        ],
        "correct_index": 2,
        "why": "A choice reaction requires the subject to decide between responses, which takes longer than responding to one signal.",
    },
    {
        "id": "ks4-reaction-time-e11",
        "subtopic_slug": "reaction-time",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "What should be done with a result that is very different from all the others?",
        "options": [
            "Include it in the mean so that no measured data is thrown away",
            "Treat it as an anomaly and leave it out of the mean",
            "Replace it with the value that was expected before the test began",
            "Repeat the whole investigation from the very beginning with a new subject",
        ],
        "correct_index": 1,
        "why": "An anomalous result is not typical of the others, so including it would pull the mean away from the true value.",
    },
    {
        "id": "ks4-reaction-time-e12",
        "subtopic_slug": "reaction-time",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Which variable must be kept the same each time the ruler drop test is repeated?",
        "options": [
            "The number of people who are watching the test being carried out",
            "The temperature of the room where the test is being carried out",
            "The time of day at which each of the readings happens to be taken",
            "The hand used to catch the ruler",
        ],
        "correct_index": 3,
        "why": "Reaction time differs between a person's two hands, so changing hands would change the result for a reason nothing to do with the test.",
    },
    {
        "id": "ks4-reaction-time-s05",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the person dropping the ruler should not count down out loud before letting go.",
        "options": [
            "Counting out loud would distract the person who is catching it",
            "Counting takes time, which would be added on to the reaction time",
            "The catcher could anticipate the drop and appear to react faster",
            "The person dropping it might let go on the wrong number quite by mistake",
        ],
        "correct_index": 2,
        "why": "If the catcher knows when the ruler will fall they can begin moving before it does, so the test no longer measures a reaction.",
    },
    {
        "id": "ks4-reaction-time-s06",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a computer reaction test leaves a random gap before the signal appears.",
        "options": [
            "A random gap gives the computer time to load the next screen",
            "It makes the test last long enough for a mean to be worth taking",
            "It allows the subject to rest between one trial and the next one",
            "It stops the subject guessing when the signal is about to come",
        ],
        "correct_index": 3,
        "why": "A predictable gap lets the subject start their response early, which measures anticipation instead of reaction.",
    },
    {
        "id": "ks4-reaction-time-s07",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a distance must be converted before the ruler drop test gives a reaction time.",
        "options": [
            "The ruler measures how far it fell, not how long it was falling",
            "Distances are measured in centimetres and times in seconds",
            "The ruler falls at a constant speed that has to be measured first",
            "The conversion removes the error made in reading the scale",
        ],
        "correct_index": 0,
        "why": "The raw measurement is a length, and a table or an equation is needed to turn it into the time the ruler took to fall.",
    },
    {
        "id": "ks4-reaction-time-s08",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "In a caffeine investigation, one group drinks coffee and another drinks a hot drink with no caffeine in it. Explain the purpose of the second group.",
        "options": [
            "It provides a comparison, so any change can be linked to caffeine",
            "It doubles the number of readings taken, which makes the mean much fairer",
            "It gives those subjects something to do while the others are tested",
            "It allows the investigation to be repeated on a completely new day",
        ],
        "correct_index": 0,
        "why": "A control group experiences everything except the factor being tested, so a difference between the groups can be attributed to it.",
    },
    {
        "id": "ks4-reaction-time-s09",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a subject's first ruler drop attempt is often much worse than the later ones.",
        "options": [
            "The ruler is colder at the start and so falls more slowly",
            "Their nervous system needs time to warm up before it works",
            "The person dropping the ruler is not yet holding it steadily",
            "They have not yet got used to what they are being asked to do",
        ],
        "correct_index": 3,
        "why": "Familiarity with the task improves performance, which is why a practice attempt is taken before the recorded trials.",
    },
    {
        "id": "ks4-reaction-time-s10",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why thinking distance increases when a car is driven faster, even though the driver's reaction time has not changed.",
        "options": [
            "A faster car takes longer for the driver to notice a hazard ahead",
            "Reaction time is longer at speed because the driver is concentrating harder",
            "The car travels further during that same reaction time",
            "The brakes take longer to act on a car that is moving quickly",
        ],
        "correct_index": 2,
        "why": "Thinking distance is speed multiplied by reaction time, so at twice the speed twice the distance is covered in the same time.",
    },
    {
        "id": "ks4-reaction-time-s11",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the two parts that add together to give the total stopping distance of a car.",
        "options": [
            "The distance travelled while reacting, and the distance travelled while braking",
            "The distance to the hazard, and the distance travelled after stopping",
            "The distance covered at full speed, and the distance covered slowing",
            "The driver's reaction time, and the distance the car then travels",
        ],
        "correct_index": 0,
        "why": "Stopping distance is thinking distance plus braking distance; the last option adds a time to a distance.",
    },
    {
        "id": "ks4-reaction-time-s12",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why using a mobile phone increases a driver's thinking distance.",
        "options": [
            "The phone gives out a signal that interferes with the nervous system",
            "Holding a phone makes it harder to turn the steering wheel quickly",
            "Attention is divided, so the hazard is noticed and acted on later",
            "The driver has to look down, which means that the car is travelling much faster",
        ],
        "correct_index": 2,
        "why": "A distracted driver takes longer to register the hazard and begin responding, and the car covers more ground meanwhile.",
    },
    {
        "id": "ks4-reaction-time-s13",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A ruler is marked in millimetres. Explain what this tells you about the measurement it can give.",
        "options": [
            "Readings can be taken only when the ruler falls a whole centimetre",
            "The reading cannot be trusted unless a magnifying glass is used",
            "The scale is too coarse for any useful result to be obtained",
            "The distance can be read to the nearest millimetre and no closer",
        ],
        "correct_index": 3,
        "why": "The resolution of an instrument is the smallest change it can show, and here that is one millimetre.",
    },
    {
        "id": "ks4-reaction-time-s14",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a subject's reaction time is not exactly the same in every trial.",
        "options": [
            "The ruler is dropped from a slightly different height each time",
            "Attention and concentration vary a little from one trial to the next",
            "The nervous system conducts impulses at a different speed each time",
            "Reaction time can only be measured to the nearest tenth of a second",
        ],
        "correct_index": 1,
        "why": "Small changes in attention, tiredness and readiness alter the result, which is why a mean of several trials is used.",
    },
    {
        "id": "ks4-reaction-time-s15",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why an investigation into alcohol and reaction time would not be carried out in a school laboratory.",
        "options": [
            "Alcohol has no measurable effect on the reaction time of a healthy teenager",
            "The equipment needed to measure the effect is too expensive to buy",
            "Giving alcohol to the subjects would not be safe or lawful there",
            "Reaction time cannot be measured accurately in a school laboratory",
        ],
        "correct_index": 2,
        "why": "Ethical and legal limits, not scientific ones, are what rule this investigation out in a school.",
    },
    {
        "id": "ks4-reaction-time-s16",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the same person should drop the ruler for every trial in a comparison.",
        "options": [
            "A different dropper might release it in a slightly different way",
            "Only one person in the group knows how to hold the ruler still",
            "It saves time, because the equipment does not have to be passed on",
            "A different dropper would hold the ruler at a different height",
        ],
        "correct_index": 0,
        "why": "Keeping the dropper the same removes one source of difference between the trials being compared.",
    },
    {
        "id": "ks4-reaction-time-s17",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why older adults tend to have slightly longer reaction times than teenagers.",
        "options": [
            "Older adults have fewer receptors in the skin of their fingertips",
            "Older adults have had far more practice at catching things",
            "Conduction and processing in the nervous system slow with age",
            "Older adults usually take part in these tests later in the day",
        ],
        "correct_index": 2,
        "why": "Impulse conduction and the processing between detection and response both become a little slower as a person ages.",
    },
    {
        "id": "ks4-reaction-time-s18",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student wants to compare reaction times before and after exercise. Suggest one variable they must control.",
        "options": [
            "The colour of the ruler that is used in each of the two tests",
            "The subject tested, since different people react at quite different rates",
            "The number of people watching each of the two tests being done",
            "The day of the week on which each of the tests is carried out",
        ],
        "correct_index": 1,
        "why": "Comparing a before and an after value only works if the same person is measured both times.",
    },
    {
        "id": "ks4-reaction-time-s19",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Five trials give 0.18 s, 0.20 s, 0.19 s, 0.45 s and 0.21 s. Identify the anomalous result.",
        "options": [
            "0.18 s, because it is the smallest value in the whole set",
            "0.20 s, because it is the value that appears closest to the middle",
            "0.45 s",
            "0.21 s, because it is larger than three of the other four values",
        ],
        "correct_index": 2,
        "why": "That value is far away from the tight cluster of the other four, which is what marks a result as anomalous.",
    },
    {
        "id": "ks4-reaction-time-s20",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a sprinter who moves before the starting pistol is disqualified for a false start.",
        "options": [
            "They must have heard the pistol before the other runners did",
            "The starter has to fire the pistol again for the whole field",
            "Moving early means their reaction time was recorded as zero",
            "Nobody can react that quickly, so they must have anticipated it",
        ],
        "correct_index": 3,
        "why": "A movement sooner than the fastest possible reaction time shows the athlete went on expectation rather than on the signal.",
    },
    {
        "id": "ks4-reaction-time-s21",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a choice reaction takes longer than a simple reaction.",
        "options": [
            "There are more receptors involved in detecting the stimulus",
            "The response uses a larger muscle, which takes longer to contract",
            "The brain must decide between responses before acting",
            "The signal has to travel along a longer route to reach the hand",
        ],
        "correct_index": 2,
        "why": "The extra processing needed to choose between two responses adds time on top of detecting and responding.",
    },
    {
        "id": "ks4-reaction-time-s22",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the ruler drop test measures something slightly different from a computer test.",
        "options": [
            "The computer test is not affected by the subject's concentration",
            "The computer test measures the speed of a nerve impulse directly",
            "The ruler test measures a choice reaction and the computer a simple one",
            "The ruler test includes the time taken to close the fingers as well",
        ],
        "correct_index": 3,
        "why": "The ruler result includes the movement of the hand, whereas a button press records the moment the response begins.",
    },
    {
        "id": "ks4-reaction-time-s23",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a driver who has been awake for twenty hours is a danger on the road.",
        "options": [
            "Tiredness makes a driver more likely to drive above the speed limit",
            "A tired driver's eyesight becomes too poor to see any hazard ahead",
            "Tiredness lengthens reaction time, so thinking distance increases",
            "A tired driver brakes harder, which makes the braking distance much longer",
        ],
        "correct_index": 2,
        "why": "Fatigue slows the nervous system, and a longer reaction time means the car travels further before the brakes are touched.",
    },
    {
        "id": "ks4-reaction-time-s24",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a subject should look at the ruler rather than at the person dropping it.",
        "options": [
            "The dropper's face is harder to see clearly in a bright laboratory",
            "Watching the dropper would give a clue about when the release happens",
            "Looking at the ruler means the subject can read the scale more easily",
            "The eye detects a falling object better when it is looked at directly",
        ],
        "correct_index": 1,
        "why": "A movement of the hand or a change of expression would let the subject anticipate the drop rather than react to it.",
    },
    {
        "id": "ks4-reaction-time-s25",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A class collects reaction times from 30 students rather than from one. Explain the advantage.",
        "options": [
            "A larger sample gives a more reliable picture of the whole group",
            "Thirty results can be recorded more quickly than five results can",
            "Using more subjects removes the need to repeat any of the trials",
            "It means every student in the class has taken part in the practical",
        ],
        "correct_index": 0,
        "why": "One person's result may be unusual, so a larger sample gives a value that better represents people in general.",
    },
    {
        "id": "ks4-reaction-time-s26",
        "subtopic_slug": "reaction-time",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why reaction time matters more in a 100 m sprint than in a marathon.",
        "options": [
            "Marathon runners are not given a starting signal to respond to",
            "A sprinter's muscles respond faster than a marathon runner's do",
            "In a race of ten seconds, a tenth of a second is a large share of it",
            "Reaction time gets longer the further an athlete has to run",
        ],
        "correct_index": 2,
        "why": "The same fraction of a second is decisive in a very short race and negligible across more than two hours.",
    },
    {
        "id": "ks4-reaction-time-h05",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student writes: 'Caffeine shortens reaction time because it gives the body more energy for the muscles to use.' Identify the correction needed.",
        "options": [
            "Caffeine acts at the synapses of the nervous system, not as a fuel",
            "Caffeine lengthens reaction time, because it is a depressant drug",
            "Caffeine has no effect on reaction time in an adult of any age",
            "Caffeine supplies energy, but only to the muscles of the arm",
        ],
        "correct_index": 0,
        "why": "Caffeine is a stimulant that raises synaptic activity; it is not an energy source for muscle.",
    },
    {
        "id": "ks4-reaction-time-h06",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A car travels at 20 m/s and the driver's reaction time is 0.7 s. Calculate the thinking distance.",
        "options": [
            "20.7 m, found by adding the speed and the reaction time together",
            "28.6 m, found by dividing the speed by the driver's reaction time",
            "14 m",
            "0.035 m, found by dividing the reaction time by the speed of the car",
        ],
        "correct_index": 2,
        "why": "Thinking distance is speed multiplied by reaction time, and 20 multiplied by 0.7 gives 14.",
    },
    {
        "id": "ks4-reaction-time-h07",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why doubling a car's speed more than doubles its total stopping distance.",
        "options": [
            "The thinking distance doubles, but the braking distance grows a good deal faster",
            "Both parts of the stopping distance are doubled by the change",
            "The braking distance doubles while the thinking distance quadruples",
            "The driver's reaction time doubles as well when the car goes faster",
        ],
        "correct_index": 0,
        "why": "Thinking distance is proportional to speed, but braking distance grows with the square of it, so the total more than doubles.",
    },
    {
        "id": "ks4-reaction-time-h08",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two students measure each other's reaction time and each takes only one reading. Determine the main weakness of their conclusion.",
        "options": [
            "They should have used a computer instead of a falling ruler",
            "A single reading could be unusual, so no mean can be calculated",
            "They should have measured their reaction times on separate days",
            "Two people are too small a sample for any useful test to be carried out",
        ],
        "correct_index": 1,
        "why": "Without repeats there is no way to tell a typical value from a one-off, so the comparison cannot be relied on.",
    },
    {
        "id": "ks4-reaction-time-h09",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Four trials give reaction times of 0.24 s, 0.26 s, 0.22 s and 0.28 s. Calculate the range of the results.",
        "options": [
            "0.06 s",
            "0.25 s, which is the mean of the four readings taken in the trials",
            "1.00 s, which is what the four readings come to when added together",
            "0.28 s, which is the largest single reading in the set of results",
        ],
        "correct_index": 0,
        "why": "The range is the largest value minus the smallest: 0.28 minus 0.22 gives 0.06.",
    },
    {
        "id": "ks4-reaction-time-h10",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Predict what would happen to the ruler drop result if the subject watched a video at the same time.",
        "options": [
            "The ruler would fall a shorter distance, because they are feeling more alert",
            "The result would be unchanged, since catching is an automatic reflex",
            "The ruler would fall further, because their attention is divided",
            "The result would become impossible to measure with any accuracy",
        ],
        "correct_index": 2,
        "why": "Dividing attention lengthens the reaction time, so the ruler falls further before the fingers close on it.",
    },
    {
        "id": "ks4-reaction-time-h11",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that catching the ruler in the drop test is a reflex action.",
        "options": [
            "Sound, since the catcher does not have time to think about it",
            "Sound, because the response happens in less than half a second",
            "Unsound — the catcher sees the ruler and decides to close their hand",
            "Unsound, because a reflex cannot involve the muscles of the hand",
        ],
        "correct_index": 2,
        "why": "A reflex bypasses conscious control, whereas the catcher is responding to something they have consciously seen.",
    },
    {
        "id": "ks4-reaction-time-h12",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a study of caffeine should test each subject at the same time of day.",
        "options": [
            "Caffeine is absorbed more quickly in the morning than it is in the evening",
            "Subjects are more willing to take part early in the morning",
            "The laboratory is quieter at some times of day than at others",
            "Alertness changes through the day, which would affect the results",
        ],
        "correct_index": 3,
        "why": "Natural changes in alertness over a day would otherwise be mixed in with the effect being investigated.",
    },
    {
        "id": "ks4-reaction-time-h13",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Determine which comparison would best show that practice shortens reaction time.",
        "options": [
            "One subject's mean over their first five trials against that of their last five",
            "One subject's single best result against another subject's best one",
            "A group of athletes compared with a group who take no exercise",
            "One subject tested in the morning and again in the late evening",
        ],
        "correct_index": 0,
        "why": "Comparing the same person early and late in a session isolates practice from differences between people.",
    },
    {
        "id": "ks4-reaction-time-h14",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A subject's thinking distance at 30 m/s is 21 m. Calculate their reaction time.",
        "options": [
            "630 s, found by multiplying the distance by the speed of the car",
            "51 s, found by adding the thinking distance to the speed given",
            "1.4 s, found by dividing the speed of the car by the distance",
            "0.7 s",
        ],
        "correct_index": 3,
        "why": "Reaction time is thinking distance divided by speed, and 21 divided by 30 gives 0.7.",
    },
    {
        "id": "ks4-reaction-time-h15",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why reaction time cannot be reduced to zero however much a person trains.",
        "options": [
            "Training makes the muscles tire, which slows the response down",
            "Detecting, processing and responding each take a real amount of time",
            "The ruler always falls a fixed distance before it can be caught",
            "A person can never see a stimulus at the exact instant it appears",
        ],
        "correct_index": 1,
        "why": "Impulses take time to travel, synapses take time to cross and muscles take time to contract, so a floor is always there.",
    },
    {
        "id": "ks4-reaction-time-h16",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare what a longer reaction time does to thinking distance with what worn brakes do to stopping distance.",
        "options": [
            "Both increase the thinking distance and leave the braking distance",
            "Reaction time lengthens the thinking part; worn brakes lengthen the braking part",
            "Both lengthen the braking distance while the thinking part stays fixed",
            "Reaction time lengthens the braking part and worn brakes the thinking",
        ],
        "correct_index": 1,
        "why": "The two act on different halves of the stopping distance, though each makes the total longer.",
    },
    {
        "id": "ks4-reaction-time-h17",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a group's mean reaction time is a fairer figure to quote than the fastest result anybody achieved.",
        "options": [
            "The fastest result may be a lucky one, or an anticipated start",
            "The mean is always a smaller number than the fastest result is",
            "The fastest result cannot be measured accurately with a ruler",
            "A mean can be calculated without needing to repeat any trial",
        ],
        "correct_index": 0,
        "why": "A single extreme value may not be a genuine reaction at all, while a mean reflects the group's typical performance.",
    },
    {
        "id": "ks4-reaction-time-h18",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Determine what a driver could do to reduce their thinking distance on a motorway.",
        "options": [
            "Fit new brake pads and tyres before setting off on the journey",
            "Drive more slowly, and avoid distractions and driving while tired",
            "Brake more firmly as soon as they notice a hazard up ahead",
            "Follow the car in front more closely so that they see its brake lights",
        ],
        "correct_index": 1,
        "why": "Thinking distance depends on speed and on reaction time, so both of those are what a driver can act on.",
    },
    {
        "id": "ks4-reaction-time-h19",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the ruler drop test gives a longer value than a test that measures the moment a finger starts to move.",
        "options": [
            "A ruler falls more slowly than a finger is able to move sideways",
            "The catcher has to see the ruler as well as respond to seeing it",
            "It includes the time taken for the fingers to close on the ruler",
            "The ruler test is usually carried out without any practice attempts first",
        ],
        "correct_index": 2,
        "why": "The ruler is not caught until the hand has actually closed, so the movement time is included in the measured distance.",
    },
    {
        "id": "ks4-reaction-time-h20",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student concludes from one classmate's results that caffeine improves everyone's reaction time. Evaluate this conclusion.",
        "options": [
            "Sound, because the classmate's results showed a clear improvement",
            "Unsound, because caffeine cannot affect the nervous system at all",
            "Sound, provided the classmate had not drunk coffee earlier that day",
            "Unsound — one subject cannot support a claim about everyone",
        ],
        "correct_index": 3,
        "why": "Generalising to everyone needs a large sample; a single subject's result may not be typical.",
    },
    {
        "id": "ks4-reaction-time-h21",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a subject who is told to expect the ruler at any moment gives a fairer result than one who is chatting.",
        "options": [
            "A chatting subject is measuring a choice reaction rather than a simple one",
            "Being ready removes distraction, so the test measures reaction itself",
            "A chatting subject would catch the ruler before it had begun to fall",
            "Talking uses the same part of the brain as catching a falling ruler",
        ],
        "correct_index": 1,
        "why": "The aim is to measure how fast the subject can respond when attending, so distraction has to be removed rather than measured.",
    },
    {
        "id": "ks4-reaction-time-h22",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two groups are compared and their mean reaction times differ by 0.002 s. Determine what conclusion is safe.",
        "options": [
            "The difference is far smaller than the spread within either group",
            "The faster group has a nervous system that conducts its impulses quicker",
            "The difference proves that the factor tested has a real effect",
            "The slower group must have been tested later in the afternoon",
        ],
        "correct_index": 0,
        "why": "A difference much smaller than the variation between trials cannot be distinguished from ordinary scatter.",
    },
    {
        "id": "ks4-reaction-time-h23",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why reaction times measured with a ruler are usually quoted to two decimal places and no more.",
        "options": [
            "A ruler cannot be dropped accurately enough to justify any more",
            "Reaction times are never longer than one second in any subject",
            "Two decimal places is the standard that every scientist has agreed",
            "The conversion from distance to time is not exact beyond that point",
        ],
        "correct_index": 3,
        "why": "Quoting more figures than the measurement supports suggests a precision the method does not have.",
    },
    {
        "id": "ks4-reaction-time-h24",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a professional driver with a fast reaction time can still be unable to stop in time.",
        "options": [
            "A fast reaction time makes a driver brake less firmly than usual",
            "Thinking distance is only part of it; the car still has to brake",
            "Professional drivers travel at speeds where reaction time is irrelevant",
            "A fast reaction time applies to the hands rather than to the feet",
        ],
        "correct_index": 1,
        "why": "Even with no thinking distance at all, the braking distance remains and grows sharply with speed.",
    },
    {
        "id": "ks4-reaction-time-h25",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Determine which change to the ruler drop method would most improve the quality of the data.",
        "options": [
            "Using a longer ruler so that slower reactions can still be caught",
            "Recording the result to the nearest half a centimetre each time",
            "Asking a different person to drop the ruler for each of the trials",
            "Taking more trials and using the mean of the ones that agree",
        ],
        "correct_index": 3,
        "why": "More repeats with an anomaly excluded gives a mean closer to the true value than any single measurement can.",
    },
    {
        "id": "ks4-reaction-time-h26",
        "subtopic_slug": "reaction-time",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a study finding that coffee drinkers react faster does not prove that coffee is the cause.",
        "options": [
            "Coffee drinkers may differ from the others in age or in habits",
            "Reaction time cannot be measured accurately in a large study",
            "Coffee has been shown to lengthen reaction time in every study",
            "The study would need to be repeated on exactly the same people",
        ],
        "correct_index": 0,
        "why": "Two groups that differ in more than the factor of interest cannot show which difference produced the result.",
    },
]
