"""Biology · Infection & response — the MRB-338 expansion, subtopic
`communicable-diseases-defence`.

The original twelve rows take pathogen classification by mechanism
(bacteria/binary fission/toxins), cholera's water route, the antigen
definition, and the skin's acidic secretions at easier; antibody
specificity, phagocytosis, the meaning of "non-communicable", and a
food-hygiene scenario at standard; and bacteria-versus-virus tissue damage,
route-specific control measures, antigenic variation in colds, and a
hospital's paired hygiene measures at harder.

This file stays with the GENERAL immunology and classification this
subtopic owns — the four pathogen groups, the categories of transmission
route, the physical/chemical barriers, and the phagocyte/lymphocyte/
antibody/antigen/memory-cell machinery — rather than any one named disease,
which belongs to its own subtopic elsewhere in this topic. The weight sits
in `standard` and `harder` because the real demand here is applying one
barrier or one immune mechanism to an unfamiliar scenario, and comparing or
evaluating across mechanisms, rather than further recall once the short
list of terms is known.

Length parity is enforced explicitly: keys are written as plain statements
of fact and distractors carry their own justification clauses, so that no
option is systematically the fullest sentence on the page.
"""

TOPIC = "infection-response"
SUBJECT = "biology"

QUESTIONS = [
    {
        "id": 'ks4-communicable-diseases-defence-e05',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'State which type of pathogen grows on or inside host tissue, causing skin and nail infections.',
        "options": [
            'Fungi',
            'Single-celled bacteria',
            'Non-living viruses',
            'Single-celled protists',
        ],
        "correct_index": 0,
        "why": "Fungal pathogens grow directly on or within the host's tissue rather than reproducing freely inside it.",
    },
    {
        "id": 'ks4-communicable-diseases-defence-e06',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Tuberculosis spreads between people mainly by which route?',
        "options": [
            'Contaminated drinking water',
            'Airborne droplets',
            'Direct skin contact',
            'An insect vector',
        ],
        "correct_index": 1,
        "why": 'Tuberculosis bacteria are released in droplets when an infected person coughs, and are then breathed in by others nearby.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-e07',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Hepatitis B is most commonly passed between people by which route?',
        "options": [
            'Airborne droplets released by coughing nearby',
            'Contaminated food',
            'Blood contact, such as shared needles',
            'An insect vector',
        ],
        "correct_index": 2,
        "why": 'Hepatitis B is carried in blood, so sharing needles or receiving unscreened blood are the main routes of infection.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-e08',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'State the job of the cilia lining the trachea.',
        "options": [
            'They produce the acid that kills any pathogen that has been swallowed',
            'They always sweep mucus, with any trapped pathogens, up towards the throat',
            'They produce antibodies against inhaled pathogens',
            'They seal the whole airway shut the moment a pathogen is detected',
        ],
        "correct_index": 1,
        "why": 'Cilia beat rhythmically to move mucus, and the pathogens trapped in it, up and out of the airway to be swallowed.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-e09',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'State the approximate pH of the stomach acid that kills most swallowed pathogens.',
        "options": [
            'pH 2',
            'pH 5',
            'pH 7',
            'pH 9',
        ],
        "correct_index": 0,
        "why": 'Stomach acid is strongly acidic, at around pH 2, which is low enough to destroy most pathogens that are swallowed.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-e10',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'What name is given to the process by which a phagocyte engulfs and destroys a pathogen?',
        "options": [
            'Phagocytosis',
            'Vaccination programme',
            'Antibody production',
            'Diffusion',
        ],
        "correct_index": 0,
        "why": 'Phagocytosis is the name for a phagocyte taking a pathogen inside itself and breaking it down.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-e11',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'State which type of white blood cell produces antibodies.',
        "options": [
            'Red blood cells',
            'Platelets',
            'Phagocytes alone',
            'Only lymphocytes',
        ],
        "correct_index": 3,
        "why": 'Lymphocytes are the white blood cells that make antibodies against a specific antigen.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-e12',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'easier',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'State for how long memory cells can remain in the blood after an infection has cleared.',
        "options": [
            'Until the fever has ended',
            'About one week after the infection has cleared',
            'Many years, or for life',
            'A few hours',
        ],
        "correct_index": 2,
        "why": 'Memory cells can persist in the blood for years, or even for a lifetime, ready to respond quickly if needed again.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s05',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain the difference between a non-specific and a specific immune defence.',
        "options": [
            'A non-specific defence works only against bacteria such as Salmonella, while a specific defence works only against viruses such as HIV',
            'A non-specific defence, such as a phagocyte, attacks any pathogen, while a specific defence, such as an antibody, binds one antigen shape',
            'A non-specific defence, such as a phagocyte, acts only inside body cells, while a specific defence acts only in the bloodstream and the lymph',
            'A non-specific defence needs several days to build up its numbers, while a specific defence acts within just a few minutes of exposure',
        ],
        "correct_index": 1,
        "why": "Phagocytes act against any pathogen without needing to recognise it first, while an antibody's binding site fits only one antigen shape.",
    },
    {
        "id": 'ks4-communicable-diseases-defence-s06',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Damage to the cilia lining the airways, for example from smoking, increases the risk of chest infections. Explain why.',
        "options": [
            'Damaged cilia stop stomach acid reaching the lungs, which is where it is normally needed',
            'Damaged cilia destroy the alveoli directly, removing the site where gas exchange takes place',
            'Damaged cilia can no longer sweep mucus, with any trapped pathogens, out of the airway',
            'Damaged cilia stop the skin barrier forming over any wound on the chest',
        ],
        "correct_index": 2,
        "why": 'Without working cilia, mucus and the pathogens trapped in it stay in the airway instead of being cleared, giving pathogens more chance to reach the lungs.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s07',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why a deep wound carries a greater risk of infection than a graze that barely breaks the skin.',
        "options": [
            'A deep wound bleeds more heavily, which draws pathogens towards the site from the surrounding skin',
            'A deep wound breaks the skin barrier over a larger area and depth, giving pathogens direct access to deeper tissue',
            'A deep wound is said to stop stomach acid from working anywhere else in the whole of the digestive system afterwards',
            'A deep wound is said to destroy phagocytes circulating throughout the whole rest of the entire bloodstream, not just locally',
        ],
        "correct_index": 1,
        "why": "The skin's protection depends on it being unbroken, so a deeper break removes more of that barrier and opens a wider route into the tissue.",
    },
    {
        "id": 'ks4-communicable-diseases-defence-s08',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why a hospital isolates a patient who has a persistent cough.',
        "options": [
            'Coughing shows the patient has a blood-contact infection that could spread through shared equipment',
            'Coughing releases pathogens in airborne droplets that could otherwise reach other patients nearby',
            "Isolation stops the patient's own antibodies reacting badly with hospital staff",
            'Isolation stops pathogens reaching other patients through contaminated hospital food and shared crockery',
        ],
        "correct_index": 1,
        "why": 'Coughing releases pathogens in airborne droplets, so keeping the patient apart from others cuts off that route.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s09',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Blood transfusion services screen every donation for hepatitis B, even though donors report feeling well. Explain why.',
        "options": [
            'Hepatitis B destroys blood cells, so infected blood looks visibly abnormal before it is even tested',
            'A donor can carry the virus with no symptoms at all and pass it on without knowing they are infected',
            'Screening removes antibodies from the blood that would otherwise harm the person receiving it',
            "The virus is present in a donor's blood for only a single day after they are first infected",
        ],
        "correct_index": 1,
        "why": "A person can be infected with hepatitis B and feel entirely well, so an honest donor's own judgement cannot be relied on.",
    },
    {
        "id": 'ks4-communicable-diseases-defence-s10',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why the body responds faster to a second infection with the same pathogen than it did to the first.',
        "options": [
            'The pathogen itself becomes weaker each time it re-infects the same host, so it is destroyed more quickly',
            'Phagocytes are produced in far greater numbers once a first infection has been survived',
            'Memory cells recognise the antigen at once and multiply quickly, skipping the delay the first response needed',
            'The skin barrier becomes thicker after each infection it successfully survives',
        ],
        "correct_index": 2,
        "why": 'The first infection leaves memory cells behind, and those cells respond to the same antigen at once rather than needing time to be found and multiplied.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s11',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A blood test shows a patient has specific antibodies against a particular bacterium. Explain what this shows about their lymphocytes.',
        "options": [
            'A whole population of lymphocytes in their blood supply can now respond to any pathogen the patient later meets',
            "One clone of lymphocytes has recognised that bacterium's antigen and produced antibodies against it",
            'Their phagocytes have permanently stopped responding to any pathogen at all',
            'The bacterium itself has been converted into a harmless antigen inside the blood',
        ],
        "correct_index": 1,
        "why": 'A specific antibody in the blood is the product of one matching lymphocyte clone, not a general change across every lymphocyte.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s12',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Suggest why washing hands before preparing food reduces the spread of communicable disease.',
        "options": [
            'It removes pathogens picked up from other surfaces before they can be transferred onto food',
            'It destroys the genetic material of any bacteria that were already present on the food before it was cooked',
            'It raises the pH of the skin permanently, so bacteria cannot grow there again',
            'It stimulates lymphocytes in the skin to produce antibodies much more quickly than usual',
        ],
        "correct_index": 0,
        "why": 'Handwashing breaks the direct-contact route by removing pathogens before they can be carried onto food that will be eaten.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s13',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why sharing towels at a gym increases the risk of picking up a fungal skin infection.',
        "options": [
            'Sharing towels lowers the pH of the skin low enough for fungi to start growing on it within hours',
            'Direct contact with a contaminated towel can transfer the fungus straight onto the skin',
            'Towels are said to destroy the waxy cuticle that normally protects human skin from any kind of infection',
            'Fungi are said to travel through the air first, and towels simply release them again once they land nearby',
        ],
        "correct_index": 1,
        "why": "A shared towel is a surface that can carry a fungus from one person's skin directly to another's on contact.",
    },
    {
        "id": 'ks4-communicable-diseases-defence-s14',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": "A patient's blood group does not change after they recover from a bacterial infection, even though new antibodies are now present in their blood. Explain why.",
        "options": [
            'Bacteria infect white blood cells only, so red blood cells are never affected by any infection',
            'The patient stops making new red blood cells for the whole duration of the infection',
            "Antibodies are broken down long before they can reach any of the patient's red blood cells",
            "The new antibodies are specific to the bacterium's antigens, not to the antigens on the patient's own red blood cells",
        ],
        "correct_index": 3,
        "why": "An antibody's binding site fits one particular antigen, and the bacterium's antigens are different from the antigens already on the patient's own cells.",
    },
    {
        "id": 'ks4-communicable-diseases-defence-s15',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Suggest why a scratch from a rose thorn can lead to a bacterial infection, even though the skin was intact beforehand.',
        "options": [
            'The scratch breaks the skin barrier, giving bacteria already on the thorn or skin a route into the tissue',
            'The thorn itself carries a toxin that quickly paralyses every phagocyte near the site of the scratch',
            'The scratch destroys the memory cells that were stored at that particular spot on the skin',
            'Chemicals released by the plant turn harmless bacteria already on the skin into pathogens',
        ],
        "correct_index": 0,
        "why": "Once the skin's surface is broken, bacteria that would otherwise be kept out have a direct route into the tissue beneath.",
    },
    {
        "id": 'ks4-communicable-diseases-defence-s16',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why mucus and cilia are described as working together, rather than as two separate defences.',
        "options": [
            'Mucus digests the pathogens after the cilia have already killed them further down inside the airway',
            'Cilia produce the mucus itself, which then absorbs the trapped pathogens directly into the bloodstream instead',
            'Mucus traps pathogens, and the cilia always carry that mucus, with the pathogens in it, up to the throat',
            'Mucus neutralises pathogens chemically before the cilia destroy their antigens completely',
        ],
        "correct_index": 2,
        "why": 'Trapping and clearing are two separate steps that depend on each other: mucus catches the pathogens, and the cilia move that mucus out of the airway.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s17',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A student says that lymphocytes are more useful than phagocytes because they are specific. Explain why phagocytes are still important.',
        "options": [
            'Phagocytes are simply far more numerous than lymphocytes in any sample of blood that is taken',
            'Phagocytes attack a pathogen straight away, while lymphocytes take time to find and multiply the matching clone',
            'Lymphocytes are said to be entirely unable to move around the whole body in order to reach a pathogen, wherever it happens to enter',
            'Phagocytes are what produce the memory cells that lymphocytes rely on for every later infection',
        ],
        "correct_index": 1,
        "why": 'Speed matters in the first hours of an infection, and a phagocyte can act immediately, while a lymphocyte response needs time to build.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s18',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A person who has fully recovered from chickenpox rarely catches it again. Explain why.',
        "options": [
            "The virus is physically unable to survive a second time inside the same host's body",
            'Their skin becomes permanently thicker after the first infection, blocking the virus out',
            'Memory cells from the first infection recognise the virus and destroy it before symptoms can develop again',
            'Painkillers taken during the first illness continue to protect the patient for years afterwards',
        ],
        "correct_index": 2,
        "why": 'The first infection leaves lasting memory cells, which respond fast enough to clear the same virus before it can cause symptoms again.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s19',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why the body takes several days to bring an infection under control the first time it meets a particular pathogen.',
        "options": [
            'Phagocytes ignore every pathogen they have not personally met on a previous occasion',
            'The pathogen must first be identified and named by the brain itself, in detail, before any immune cell of any kind is able to respond',
            'With no memory cells yet made, the matching lymphocyte clone must first be found and then multiply before enough antibody is produced',
            'The skin barrier takes several days to be broken down by any new pathogen',
        ],
        "correct_index": 2,
        "why": 'Without a memory cell already primed, the immune system has to locate the right lymphocyte and build up its numbers before it can produce useful quantities of antibody.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s20',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Suggest why a cut that has scabbed over is less likely to become infected than an open wound left uncovered.',
        "options": [
            'The scab restores a physical barrier over the wound, closing the route pathogens would otherwise use',
            'A scab produces its own fresh antibodies as it hardens over the whole surface of the wound',
            'A scab lowers the pH of the skin enough to kill off any pathogens nearby',
            'A scab stops phagocytes from ever reaching the site, so bacteria find nothing there left to feed on',
        ],
        "correct_index": 0,
        "why": 'A scab re-seals the break in the skin, so it works in the same way as unbroken skin normally does.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s21',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Suggest why a wound made by a dirty knife is more likely to become infected than a wound of the same size made by a sterile scalpel.',
        "options": [
            'Sterile scalpels are said to seal a wound shut automatically the very moment they finish cutting into the skin',
            'A dirty knife is said to destroy the phagocytes present at the site of the cut the very instant it enters',
            'The dirty knife carries pathogens directly into the wound as it cuts, while the sterile scalpel does not',
            'It is only ever the size of a wound, and never how clean the blade used to make it was, that decides infection risk',
        ],
        "correct_index": 2,
        "why": 'A contaminated blade delivers pathogens straight into the wound at the moment the barrier is broken, which a sterile blade does not.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s22',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why a transplant patient taking drugs that suppress their immune system is advised to avoid people who are ill.',
        "options": [
            "The drugs prevent the patient's stomach from producing any acid, however mild the dose given",
            'Their phagocytes and lymphocytes respond more weakly, so they are less able to fight off a pathogen they meet',
            'The drugs are said to make any pathogen that infects the patient far more toxic than it would otherwise ever have been',
            "The drugs destroy the patient's skin barrier over their whole body within days",
        ],
        "correct_index": 1,
        "why": 'Suppressing the immune system weakens both the phagocyte and the lymphocyte response, so an infection that a healthy person would clear easily becomes more dangerous.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s23',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": "A nurse wears gloves when treating a patient's open wound. Explain which of the nurse's own defences this protects.",
        "options": [
            "It boosts the total number of phagocytes circulating in the nurse's own blood for that entire shift",
            "It keeps the nurse's own skin as an unbroken barrier between them and any pathogens in the wound",
            "It stops the nurse's own antigens from triggering a reaction in the patient",
            "It raises the acidity of the nurse's skin enough to kill any pathogen on contact",
        ],
        "correct_index": 1,
        "why": "The glove keeps the skin's barrier intact, standing in for the nurse's own unbroken skin at the point of contact.",
    },
    {
        "id": 'ks4-communicable-diseases-defence-s24',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Suggest why infection spreads far more easily on a packed train carriage than on one carrying only a few passengers.',
        "options": [
            'Crowding lowers the temperature inside the carriage, which favours the growth of any pathogen present',
            'More passengers crowded into the carriage means far more contaminated water is carried on board with them',
            'Passengers are close enough for airborne droplets from a cough or sneeze to reach many more people',
            "A crowded carriage disables the antibodies already present in each passenger's blood",
        ],
        "correct_index": 2,
        "why": 'Droplet spread depends on people being physically close, and crowding puts far more people within that range of each infected passenger.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-s25',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Suggest one reason a farm worker handling livestock faces a higher risk of a blood-contact infection than an office worker.',
        "options": [
            'Farm workers naturally produce far fewer white blood cells overall than an office worker of the same age',
            'They are more likely to be exposed to animal blood or fluids through cuts and grazes on their hands',
            'Livestock only ever carry pathogens that spread through airborne droplets',
            'Farm work permanently lowers the amount of acid the stomach is able to produce each day',
        ],
        "correct_index": 1,
        "why": "Handling animals brings a worker's broken skin into contact with blood and body fluids far more often than office work does.",
    },
    {
        "id": 'ks4-communicable-diseases-defence-s26',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'standard',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why a country with poor sanitation sees a rise in communicable disease overall, not just in diseases spread by water.',
        "options": [
            'Poor sanitation destroys the stomach acid of the entire population within a generation',
            'Poor sanitation stops every vaccine that has already been given from continuing to work',
            'Poor sanitation allows pathogens spread by water, food and contaminated surfaces all to reach people more easily',
            'Poor sanitation only ever affects diseases that are spread by an insect vector',
        ],
        "correct_index": 2,
        "why": 'Poor sanitation weakens several routes at once — water, food and contaminated surfaces — so it raises the risk of disease spread by any of them, not one alone.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h05',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Compare how phagocytes and lymphocytes each contribute to clearing a first-time bacterial infection.',
        "options": [
            'Both act at exactly the same speed, because they are triggered by the same chemical signal',
            'Lymphocytes act first, because they are already present in large numbers, and phagocytes follow more slowly',
            'Phagocytes attack the bacteria immediately without needing to recognise them, while lymphocytes take longer to find and multiply the matching clone',
            'Phagocytes and lymphocytes both need several days before either is able to respond to a new pathogen',
        ],
        "correct_index": 2,
        "why": 'A phagocyte response is fast and non-specific, while a lymphocyte response is specific but needs time to build up the right clone.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h06',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": "A wound becomes infected despite the patient's skin, stomach acid and mucus all working normally elsewhere on the body. Explain why these barriers gave no protection here.",
        "options": [
            'The pathogen had to overcome stomach acid before it could infect a break in the skin elsewhere on the body',
            'Mucus and cilia are said to protect wounds on the skin in exactly the same way they protect the airways',
            'The wound is a direct break in the skin, so the barrier there has already been bypassed at that point',
            'A working barrier is said to stop every pathogen that later reaches unbroken skin somewhere nearby too',
        ],
        "correct_index": 2,
        "why": "A wound removes the skin's protection at that one spot, so a pathogen entering there never has to get past a barrier that is no longer complete.",
    },
    {
        "id": 'ks4-communicable-diseases-defence-h07',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A patient recovers from one bacterial infection and, weeks later, catches a different bacterium just as severely. Explain why the memory cells from the first infection gave no protection against the second.',
        "options": [
            'Memory cells apparently last a small number of weeks before they disappear from the blood completely and permanently, for good, according to this claim',
            'The second bacterium carries different antigens, so the antibodies and memory cells made against the first bacterium do not recognise it',
            'The second infection actively destroyed the memory cells left over from the first',
            'Bacteria become resistant to antibodies once a patient has been infected by any bacterium before',
        ],
        "correct_index": 1,
        "why": 'A memory cell responds to one antigen shape, and a different bacterium presents a different antigen that the existing memory cells do not fit.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h08',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": "Compare the speed and the specificity of a phagocyte's response with a lymphocyte's response, to a pathogen the body has never met before.",
        "options": [
            'The phagocyte responds within minutes but attacks any pathogen; the lymphocyte responds only after several days but targets that one pathogen precisely',
            'The lymphocyte is said to respond within minutes and to target any pathogen it happens to meet, while the phagocyte takes several days longer still to act',
            'Both cell types respond within minutes, but only the phagocyte is ever specific to a single antigen shape',
            'Neither cell type is able to respond to a pathogen the body has never met before',
        ],
        "correct_index": 0,
        "why": 'Speed and specificity trade off between the two cell types: fast and general against slower and precise.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h09',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A patient has a rare condition in which their phagocytes cannot engulf pathogens, but their lymphocytes work normally. Predict which infections they would struggle most to fight off in the first few hours, and explain why.',
        "options": [
            'Any new infection, because the first hours depend on the fast, non-specific phagocyte response that this patient lacks, before lymphocytes can respond',
            'No infection, because lymphocytes on their own are said to provide entirely complete protection during the very first hours of any infection whatsoever, however new',
            'Only infections met for a second time, because memory cells themselves depend directly on phagocytes',
            'Viral infections only, because phagocytes normally attack bacteria and never respond to viruses',
        ],
        "correct_index": 0,
        "why": "The early hours of an infection depend on the fast, non-specific phagocyte response, which this patient's cells cannot carry out.",
    },
    {
        "id": 'ks4-communicable-diseases-defence-h10',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A country builds new water treatment plants and increases food hygiene inspections, but cases of a respiratory disease stay the same. Explain why these measures had no effect on this disease.',
        "options": [
            'Water treatment and food hygiene target the water-borne and food-borne routes, but this disease spreads by airborne droplets, a route neither measure touches',
            'Water treatment plants make respiratory diseases spread faster through the surrounding air',
            'Food hygiene inspections apply only to bacterial diseases, and this respiratory disease happens to be viral',
            'Both measures need several more years before any effect on case numbers becomes visible',
        ],
        "correct_index": 0,
        "why": 'A control measure only reduces transmission along the route it acts on, and droplet spread is not affected by either water treatment or food hygiene.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h11',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Evaluate the claim that improving just one defence, such as the skin, would remove the risk of infectious disease altogether.',
        "options": [
            'It would, because the skin is the one barrier every pathogen must cross to enter the body',
            'It would, because a stronger skin barrier also strengthens the stomach acid and the lymphocyte response',
            "It would not, because a person's blood group is what really determines how easily they catch an infection",
            'It would not, because different defences protect against different pathogens and different routes of entry',
        ],
        "correct_index": 3,
        "why": 'No single defence covers every route and every pathogen, so strengthening one leaves the others exactly as they were.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h12',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A study finds that people who wash their hands regularly still occasionally catch colds. Evaluate whether this shows that handwashing is not an effective defence.',
        "options": [
            'It does, because an effective defence would be expected to stop every infection a person could catch',
            'It does, because any pathogen surviving after washing must have come from inside the body itself',
            'It does not, because colds are apparently caused by a combination of inherited genes passed down through a family, rather than by any actual pathogen at all',
            'It does not, because handwashing reduces spread by contact, but colds also spread by airborne droplets, a route handwashing does not stop',
        ],
        "correct_index": 3,
        "why": 'A defence that works against one route is not expected to stop transmission by a different route, so occasional colds do not show handwashing has failed.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h13',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A school closes its swimming pool after a bacterial infection linked to contaminated water is confirmed, but keeps classrooms open. Evaluate this decision.',
        "options": [
            'Reasonable, because closing the pool removes the contaminated-water route without needing to close a route the outbreak is not using',
            'Unreasonable, because a swimming pool is said to actually carry a far lower overall disease risk than any ordinary classroom ever does, whatever the outbreak',
            'Unreasonable, because the whole school should stay closed until the pathogen is entirely gone',
            'Reasonable, because it was the chlorine added to the pool that caused the infection rather than the water in it',
        ],
        "correct_index": 0,
        "why": 'Closing the specific route the outbreak is using is enough, and there is no reason given to think classrooms are involved in this route at all.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h14',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A pathogen mutates so that its antigens change shape. Explain the effect this has on people who already carry memory cells from an earlier infection with the original strain.',
        "options": [
            'Their memory cells adapt automatically over time to fit the new antigen shape',
            'Their existing memory cells and antibodies no longer fit the changed antigens, so they are not protected against the new strain',
            'The mutation has no real effect at all, because memory cells are said to respond to any pathogen regardless of its antigens',
            'The mutated pathogen becomes unable to infect any person, changed or not',
        ],
        "correct_index": 1,
        "why": "A memory cell's usefulness depends on the antigen matching the shape it was made against, and a mutated antigen no longer fits.",
    },
    {
        "id": 'ks4-communicable-diseases-defence-h15',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": "Compare a person's immune response on first meeting a pathogen with their response to the same, unchanged pathogen ten years later.",
        "options": [
            'Both responses are equally fast, because phagocytes respond instantly to a pathogen either time it is met',
            'The second response is slower, because the immune system grows weaker each time it meets any pathogen',
            'The first response is slow, because the matching lymphocyte clone must be found and multiplied; the second is fast, because memory cells from the first infection are still present',
            'The first response is faster, because an unfamiliar pathogen triggers a stronger phagocyte reaction',
        ],
        "correct_index": 2,
        "why": 'Memory cells persist for years, so a repeat meeting with the same pathogen skips the slow search-and-multiply stage the first infection needed.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h16',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": "A patient's blood test shows a normal number of phagocytes but no working lymphocytes. Predict which kind of protection they would lack.",
        "options": [
            'Protection against every pathogen, because phagocytes are unable to work at all without lymphocytes',
            'Specific, antibody-based immunity and the ability to build lasting memory of a pathogen they have met',
            'Only the skin and mucus barriers, which depend directly on lymphocytes being present',
            'Protection against bacteria specifically, but not against any virus',
        ],
        "correct_index": 1,
        "why": 'Lymphocytes are the source of specific antibodies and of memory cells, so losing them removes both, while the non-specific phagocyte response is unaffected.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h17',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Explain why a cut that is cleaned and covered carries less infection risk than the same cut left uncleaned and uncovered, using two separate defences in your answer.',
        "options": [
            'Cleaning is said to kill every single pathogen present at the wound for good, so covering it up again afterwards makes no further difference to the outcome',
            'Cleaning removes pathogens already on the wound, and covering restores a physical barrier, so both the pathogen load and the route of entry are reduced',
            'Covering the wound stimulates memory cells at that spot, and cleaning has no separate effect of its own',
            'Cleaning and covering both act only by raising the local temperature of the skin',
        ],
        "correct_index": 1,
        "why": 'Cleaning and covering act on two different problems — how many pathogens are present, and whether the barrier is restored — so together they do more than either alone.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h18',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A disease spreads equally by contaminated water and by direct contact. A city fixes its water supply completely, but case numbers fall by only half. Suggest why.',
        "options": [
            'The direct-contact route is unaffected by the water fix, so transmission through that route continues as before',
            'Fixing the water supply should have removed the disease entirely on its own, so the measurement taken here must simply be wrong',
            'Direct contact is said to only ever account for a very small share of any outbreak of this particular kind',
            'The water fix cannot possibly have worked properly, since cases did not fall all the way down to zero afterwards',
        ],
        "correct_index": 0,
        "why": 'A route-specific fix only removes transmission along that route, and a disease with two independent routes will continue to spread along the one left untouched.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h19',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Compare the way the skin and the stomach acid each protect the body from infection.',
        "options": [
            'The skin is said to act as a chemical barrier that dissolves pathogens outright, while stomach acid is treated as a physical barrier that simply blocks them from passing through',
            'Both act as physical barriers, stopping pathogens from ever reaching the tissue beneath any surface',
            'The skin is a physical barrier that stops pathogens reaching tissue beneath it, while stomach acid is a chemical barrier that kills pathogens once swallowed',
            'Both act only against bacteria, and neither has any effect on viruses or fungi',
        ],
        "correct_index": 2,
        "why": 'The skin works mechanically, by blocking entry, while stomach acid works chemically, by destroying pathogens once they are swallowed.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h20',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": "A student argues that once the skin is broken, none of the body's other defences matter. Evaluate this view.",
        "options": [
            'It is correct, because nothing can compensate once the skin barrier itself has been broken',
            'It is incorrect, because phagocytes and lymphocytes can still act against a pathogen that gets past broken skin',
            'It is correct, because phagocytes and lymphocytes respond only to pathogens entering through unbroken skin',
            'It is incorrect, because broken skin always heals before any pathogen manages to enter it',
        ],
        "correct_index": 1,
        "why": 'The skin is only the first line of defence, and internal defences such as phagocytes and lymphocytes still act once a pathogen is inside the body.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h21',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": "Two patients receive identical cuts. One is infected with bacteria that mainly produce toxins; the other with bacteria that invade and destroy cells directly. Compare how each patient's symptoms are most likely to arise.",
        "options": [
            "The first patient's symptoms come mainly from the chemicals the bacteria release; the second's come from the bacteria damaging the cells themselves",
            "Both patients' symptoms come entirely from the immune system's own response, regardless of how the bacteria act",
            "The first patient's symptoms come from direct cell damage, while the second's come from the toxins produced instead",
            'Neither patient develops symptoms until the bacteria eventually reach the bloodstream',
        ],
        "correct_index": 0,
        "why": "The mechanism of harm differs between the two: one bacterium's effect is chemical, released into the surrounding tissue, and the other's is a direct assault on the cells themselves.",
    },
    {
        "id": 'ks4-communicable-diseases-defence-h22',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Suggest why a burns patient, whose skin is destroyed over a large area, faces an unusually high risk of infection compared with a patient with a small cut.',
        "options": [
            'A much larger area of the physical barrier is entirely missing, giving pathogens far more possible routes into the tissue lying beneath',
            "Burns are said to destroy a patient's lymphocytes throughout the whole of their circulatory system, everywhere at once, not just at the burn site",
            'Burns lower the pH of the surrounding skin so sharply that this is said to actively attract many more pathogens to the area from further away',
            'A large burn is said to stop stomach acid being produced anywhere else in the whole of the rest of the body, not only near the burn itself',
        ],
        "correct_index": 0,
        "why": 'The size of the break in the skin decides how much of the barrier is lost, and a large burn removes far more of it than a small cut does.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h23',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A pathogen enters through a wound and starts to multiply faster than the local phagocytes can engulf it. Explain what determines whether the infection is brought under control or becomes established.',
        "options": [
            "Whether the wound happens to sit on the upper half or the lower half of the patient's whole body, rather than on any other single factor",
            'Whether the rate at which the immune system destroys the pathogen exceeds the rate at which the pathogen reproduces at that particular site',
            'Whether the patient has ever received any vaccine at any point earlier in their life',
            "Whether the patient's blood group happens to match the pathogen's own antigens",
        ],
        "correct_index": 1,
        "why": 'An infection becomes established only if the pathogen reproduces faster than it is destroyed; if the immune response keeps ahead, it is cleared instead.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h24',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Compare the total time needed to clear a first-time bacterial infection that is stopped by phagocytes alone with one caused by bacteria that survive phagocytosis and require a lymphocyte response as well.',
        "options": [
            'The first is cleared within hours by phagocytes alone; the second takes days longer, because it also needs the slower lymphocyte and antibody response',
            'Both infections are said to take exactly the same overall time to clear, because phagocytes are claimed to always act first regardless of which particular bacterium happens to be involved',
            'The second is cleared faster, because lymphocytes are able to act before phagocytes are even needed',
            'Neither infection can ever be cleared without a course of antibiotics being given',
        ],
        "correct_index": 0,
        "why": 'A bacterium that phagocytes alone can destroy is cleared quickly, but one that survives phagocytosis needs the slower, additional lymphocyte response before it too is cleared.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h25',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'A student claims that because pathogens spread by several different routes, several completely different sets of internal defences must exist, one for each route. Evaluate this claim.',
        "options": [
            'It is correct, because phagocytes only ever respond to pathogens that enter through broken skin',
            'It is correct, because a fresh set of lymphocytes is produced separately for each transmission route used',
            'It is wrong, because pathogens are only able to use one transmission route across their entire lifetime',
            'It is wrong; the same internal defences, such as phagocytes and lymphocytes, act against a pathogen once it is inside the body, whichever route it used to get there',
        ],
        "correct_index": 3,
        "why": 'Route only decides how a pathogen gets in; once inside, the same phagocyte and lymphocyte defences respond, regardless of which route was used.',
    },
    {
        "id": 'ks4-communicable-diseases-defence-h26',
        "subtopic_slug": 'communicable-diseases-defence',
        "band": 'harder',
        "tier": 'foundation',
        "triple_only": False,
        "text": 'Suggest why a scientist investigating a new outbreak would want to know its transmission route before recommending any control measure.',
        "options": [
            'Knowing the route mostly determines how much a government chooses to spend on treatment rather than prevention',
            'A control measure only works on the route it targets, so choosing the wrong route would fail to slow the outbreak',
            'Knowing the route changes which particular pathogen is actually causing the disease',
            'Unless the route is confirmed as airborne, quarantine is unable to reduce spread of any kind',
        ],
        "correct_index": 1,
        "why": 'A measure such as water treatment or droplet precautions reduces transmission on the route it is aimed at, and does nothing for spread along a different route.',
    },
]
