"""Biology · Infection and response — the MRB-338 expansion, subtopic
`antibiotics-painkillers`.

The baseline twelve cover Fleming and penicillin, the meaning of broad
spectrum, MRSA as a named resistant organism, farm use, the cause-versus-
symptom split, prescribing 'just in case', mutation as the origin of
resistance, species specificity, a hospital restriction policy, the
patient-versus-bacteria error, a new antibiotic not being a permanent
answer, and vaccine against antibiotic.

This file goes wider into the parts of AQA 4.3.1.7 the twelve leave
untouched: what a painkiller actually does and does not do, named
painkillers against named antibiotics, penicillin's action on the cell
wall and the osmotic bursting that follows, antiseptics as a separate
class, why antiviral drugs are hard to design, completing a course and
part courses, sensitivity testing and the choice between a narrow- and a
broad-spectrum drug, keeping new drugs in reserve, the cost and length of
antibiotic development, the historical fall in deaths from bacterial
disease and why it may not continue, and the knock-on risks of resistance
for surgery and for chemotherapy.
"""

TOPIC = "infection-response"
SUBJECT = "biology"

QUESTIONS = [
    {
        "id": "ks4-antibiotics-painkillers-e05",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a painkiller such as paracetamol does when a patient has a bacterial infection.",
        "options": [
            "It relieves symptoms such as pain and fever, while leaving the bacteria themselves unharmed",
            "It kills the bacteria slowly over several days, so the infection clears without any antibiotic being needed",
            "It stops the bacteria from reproducing",
            "It helps the antibiotic reach the infected tissue",
        ],
        "correct_index": 0,
        "why": "Painkillers treat symptoms. They do nothing to the pathogen, which is why an antibiotic is still needed for a bacterial infection.",
    },
    {
        "id": "ks4-antibiotics-painkillers-e06",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Identify which of these drugs is a painkiller rather than an antibiotic.",
        "options": [
            "Penicillin",
            "Paracetamol, a painkiller",
            "Amoxicillin, an antibiotic for chest infections",
            "Erythromycin, an antibiotic used in penicillin allergy",
        ],
        "correct_index": 1,
        "why": "Paracetamol relieves pain and fever. The other three are antibiotics, which act on bacteria.",
    },
    {
        "id": "ks4-antibiotics-painkillers-e07",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State which of these illnesses an antibiotic cannot treat.",
        "options": [
            "Tuberculosis",
            "Salmonella food poisoning",
            "Influenza, which is caused by a virus",
            "A throat infection caused by bacteria, such as strep throat",
        ],
        "correct_index": 2,
        "why": "Antibiotics act on bacteria. Influenza is viral, so an antibiotic has no effect on it.",
    },
    {
        "id": "ks4-antibiotics-painkillers-e08",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the part of a bacterium that penicillin damages.",
        "options": [
            "The plasmid that carries its extra genes",
            "The ribosomes where its proteins are assembled",
            "The flagellum it uses to move through liquid",
            "The cell wall",
        ],
        "correct_index": 3,
        "why": "Penicillin stops a bacterium building its cell wall, which is why it damages bacteria and not human cells, which have no wall.",
    },
    {
        "id": "ks4-antibiotics-painkillers-e09",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happened to the number of deaths from bacterial disease in the UK after antibiotics came into use.",
        "options": [
            "It fell greatly, and many infections that had been fatal became treatable",
            "It rose, because people stopped taking care over hygiene once such drugs existed",
            "It stayed the same",
            "It fell briefly",
        ],
        "correct_index": 0,
        "why": "Antibiotics produced a large fall in deaths from bacterial disease, which is why resistance is now treated as such a serious threat.",
    },
    {
        "id": "ks4-antibiotics-painkillers-e10",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State why it is difficult to develop a drug that kills a virus without harming the patient.",
        "options": [
            "Viruses reproduce far too quickly for any drug to keep up with them",
            "Viruses reproduce inside the patient's own cells",
            "Viruses have a thick cell wall that most drugs cannot get through",
            "Viruses are much larger than bacteria, so a drug cannot enter them",
        ],
        "correct_index": 1,
        "why": "A virus replicates inside host cells, so a drug that damages the virus tends to damage the cell around it as well.",
    },
    {
        "id": "ks4-antibiotics-painkillers-e11",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a patient should do if their symptoms improve halfway through a course of antibiotics.",
        "options": [
            "Stop taking them and keep the rest for a future illness",
            "Halve the dose for the remaining days",
            "Finish the whole course exactly as the doctor prescribed it, even though the symptoms have improved",
            "Stop at once, because the infection has gone",
        ],
        "correct_index": 2,
        "why": "Symptoms ease before the last bacteria are cleared, so finishing the course reduces the chance of the infection returning.",
    },
    {
        "id": "ks4-antibiotics-painkillers-e12",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what is meant by an antiseptic.",
        "options": [
            "A drug taken by mouth that kills bacteria inside the body",
            "A drug that relieves pain without treating the infection itself",
            "A vaccine",
            "A chemical used on the skin to kill microorganisms",
        ],
        "correct_index": 3,
        "why": "Antiseptics are used on living surfaces such as skin. Antibiotics are taken to treat an infection inside the body.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s05",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why taking a painkiller does not shorten a bacterial illness.",
        "options": [
            "It treats the symptoms only, so the bacteria continue to reproduce",
            "It weakens the patient's own white blood cells, so the illness lasts longer than it otherwise would",
            "It makes the bacteria reproduce faster than they otherwise would inside the body",
            "It is absorbed too slowly",
        ],
        "correct_index": 0,
        "why": "A painkiller changes how the patient feels, not how many bacteria are present, so the infection runs its course unchanged.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s06",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a doctor will not prescribe an antibiotic for a common cold.",
        "options": [
            "Colds are too mild to need one",
            "A cold is caused by a virus, and antibiotics act on bacteria rather than on viruses",
            "Antibiotics would make the cold last longer",
            "The patient would become allergic to the drug",
        ],
        "correct_index": 1,
        "why": "The drug would have no effect on the virus causing the cold, and prescribing it would expose the patient's bacteria to the drug for nothing.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s07",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A doctor takes a swab from an infected wound and sends it to a laboratory before prescribing. Explain why.",
        "options": [
            "So that the laboratory can produce a vaccine against the bacterium that is growing in the wound",
            "So that the patient can be given a painkiller matched to the severity of the pain they feel",
            "So the bacterium can be identified and a suitable antibiotic chosen",
            "So that the wound can be cleaned with an antiseptic before any drug is given",
        ],
        "correct_index": 2,
        "why": "Antibiotics differ in which species they act on, so identifying the bacterium lets the doctor prescribe one that will work.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s08",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a doctor chooses a particular antibiotic for an infection rather than any antibiotic.",
        "options": [
            "Different antibiotics are produced by different companies, so the choice comes down to price alone",
            "One antibiotic is as effective as another, so the choice makes little difference",
            "Choosing at random spreads resistance more widely",
            "Species of bacteria differ, so an antibiotic that kills one may not affect another",
        ],
        "correct_index": 3,
        "why": "An antibiotic acts on a particular structure or process, and a species that lacks that target is unaffected by the drug.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s09",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why stopping a course of antibiotics early can allow an infection to return.",
        "options": [
            "The least affected bacteria may survive and multiply again",
            "The drug already in the blood turns into a substance that feeds the bacteria",
            "The patient's white blood cells stop working once the tablets have been stopped early",
            "The bacteria that were killed are able to repair themselves and start dividing again",
        ],
        "correct_index": 0,
        "why": "The bacteria hardest to kill are the last to go, so a shortened course can leave exactly those behind to rebuild the infection.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s10",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why an antiviral drug is harder to design than an antibiotic.",
        "options": [
            "A virus has a cell wall that is much tougher than a bacterial cell wall is",
            "A virus replicates inside body cells, so a drug that harms it easily harms the cell too",
            "Viruses are smaller than bacteria, so a drug cannot find them",
            "Antibiotics are natural products, while antivirals must be built from scratch in a laboratory each time",
        ],
        "correct_index": 1,
        "why": "A bacterium has structures of its own to attack; a virus uses the host cell's, so there is far less that a drug can target safely.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s11",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe the difference between an antiseptic and an antibiotic.",
        "options": [
            "An antiseptic is used inside the body, while an antibiotic is used on the skin and on surfaces",
            "An antiseptic kills viruses, while an antibiotic kills bacteria that are growing inside cells",
            "An antiseptic kills microbes outside the body; an antibiotic treats infection inside it",
            "They are two names for the same kind of drug",
        ],
        "correct_index": 2,
        "why": "Antiseptics are applied to skin and surfaces to reduce the number of microbes present; antibiotics are taken to treat an infection already inside the body.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s12",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain how good handwashing in a hospital reduces the amount of antibiotic that has to be prescribed.",
        "options": [
            "Soap contains a weak antibiotic that treats infections before they start",
            "Washing removes the resistance genes from bacteria living on the skin",
            "Clean hands make any antibiotic that is later prescribed work faster",
            "Fewer pathogens are passed between patients, so fewer people develop infections that need treating with antibiotics",
        ],
        "correct_index": 3,
        "why": "Preventing transmission reduces the number of infections, and every infection prevented is a course of antibiotics not needed.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s13",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the rise of antibiotic-resistant bacteria makes routine surgery more risky.",
        "options": [
            "Operations depend on antibiotics to prevent and treat infection afterwards, and a resistant infection may not respond to them",
            "Surgical instruments become resistant to the antiseptics used to clean them, so wounds are no longer sterile when they are closed",
            "Resistant bacteria make an anaesthetic wear off much sooner than expected",
            "A wound made during surgery heals more slowly in a resistant patient",
        ],
        "correct_index": 0,
        "why": "Surgery opens a route into the body, and modern practice relies on antibiotics to deal with any infection that follows.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s14",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how damage to its cell wall causes a bacterium to burst.",
        "options": [
            "The wall holds the genetic material in place, and without it the DNA leaks out of the cell",
            "Water enters by osmosis and the cell cannot resist the pressure",
            "The wall keeps out the water, so without it the cell dries out completely and collapses inwards",
            "The wall is the site of respiration",
        ],
        "correct_index": 1,
        "why": "The wall normally resists the pressure built up as water enters by osmosis; without it the membrane cannot hold and the cell bursts.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s15",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why an antibiotic given at too low a dose may fail to clear an infection.",
        "options": [
            "A low dose is broken down by the liver before any of it can reach the blood",
            "A low dose makes the patient's own cells absorb the drug instead of the bacteria",
            "Too little drug reaches the bacteria to kill them, so some survive and multiply",
            "A low dose causes the bacteria to produce more toxin than they otherwise would have done",
        ],
        "correct_index": 2,
        "why": "Bacteria that survive a dose too low to kill them go on reproducing, and those survivors are the least affected by the drug.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s16",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why doctors keep some newly developed antibiotics in reserve rather than prescribing them routinely.",
        "options": [
            "New antibiotics cost less when they are used for a small number of patients each year",
            "New antibiotics lose their effect if they are stored for too long before being used",
            "Routine use would make the patients who took them resistant to the drug themselves",
            "Limiting use slows the selection of bacteria resistant to them",
        ],
        "correct_index": 3,
        "why": "The less a drug is used, the less selection pressure there is for resistance to it, so it stays effective for the cases that need it most.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s17",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why an antibiotic has no effect on athlete's foot.",
        "options": [
            "Athlete's foot is caused by a fungus, which antibiotics do not act on",
            "Athlete's foot is caused by a protist, and protists are unaffected by any medicine",
            "Antibiotics work on the skin surface, and the fungus grows below it",
            "Antibiotics act on viruses",
        ],
        "correct_index": 0,
        "why": "Antibiotics act on bacteria. A fungal skin infection needs an antifungal treatment instead.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s18",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A patient with a viral throat infection is advised to rest, drink fluids and take a painkiller. Explain why no antibiotic is given.",
        "options": [
            "An antibiotic would react with the painkiller and make the patient feel much worse",
            "The illness is viral, so an antibiotic would not help",
            "An antibiotic is kept back because the patient is not yet ill enough to need one",
            "The patient must first be tested for an allergy before any antibiotic is prescribed",
        ],
        "correct_index": 1,
        "why": "Antibiotics act on bacteria, so for a viral throat infection the sensible treatment relieves symptoms while the immune system clears the virus.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s19",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why developing a new antibiotic takes many years and a great deal of money.",
        "options": [
            "The mould that makes it grows slowly",
            "Companies are not allowed to sell an antibiotic until ten years have passed",
            "A candidate drug must be tested for toxicity, efficacy and dose in cells, in animals and then in people, and most candidates fail",
            "New antibiotics have to be approved in every country separately before use",
        ],
        "correct_index": 2,
        "why": "The testing pathway is long and most candidates are rejected along it, so the cost of the successes includes the cost of all the failures.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s20",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why antibiotic-resistant bacteria spread quickly on a hospital ward.",
        "options": [
            "Hospital patients produce fewer white blood cells than healthy people do, so bacteria are able to spread between them",
            "The antiseptics used in hospitals are themselves what create the resistant bacteria in the first place",
            "Resistant bacteria grow faster in a warm building than they do outdoors",
            "Many patients are treated with antibiotics close together, and staff and equipment move between them",
        ],
        "correct_index": 3,
        "why": "A ward combines heavy antibiotic use, which selects resistant strains, with close contact, which moves them from patient to patient.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s21",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain how giving antibiotics routinely to farm animals can affect human health.",
        "options": [
            "Resistant bacteria selected in the animals can reach people through food or contact",
            "Antibiotic remains in the meat and treats any infection the person eating it happens to have",
            "The animals pass their own antibodies to people, which stops human antibiotics working",
            "Farm animals cannot catch human diseases",
        ],
        "correct_index": 0,
        "why": "Selection happens wherever the drug is used, and resistant bacteria do not stay on the farm.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s22",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A patient's pain returns a few hours after taking a painkiller. Explain what this shows about their infection.",
        "options": [
            "The infection has become resistant to the painkiller",
            "Nothing has changed about the infection; the painkiller has simply worn off, because it treats the symptom rather than the cause",
            "The infection has spread to a new part of the body",
            "The painkiller has killed some bacteria but not others",
        ],
        "correct_index": 1,
        "why": "Pain returning as a dose wears off is expected, because the drug was never acting on the pathogen in the first place.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s23",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the fall in deaths from bacterial disease since the 1940s may not continue.",
        "options": [
            "Bacteria are becoming physically larger, so a standard dose of the drug no longer covers them",
            "Fewer people are willing to take medicines of any kind than were willing in the 1940s",
            "Resistant strains are becoming more common",
            "Antibiotics are gradually losing their strength as they are stored for longer periods",
        ],
        "correct_index": 2,
        "why": "The fall depended on antibiotics working; as resistant strains spread, infections that were routinely treatable become harder to cure.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s24",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a patient should not take antibiotic tablets left over from an earlier illness.",
        "options": [
            "Tablets kept at home become poisonous within a few weeks of the box being opened for the first time",
            "Leftover tablets contain just the coating, because the active drug dissolves away first",
            "Any leftover tablets will have been fully used by the bacteria of the first infection",
            "The new illness may not be bacterial, and a part course selects for resistant bacteria",
        ],
        "correct_index": 3,
        "why": "A leftover supply is by definition too short for a full course, and the illness it is being used on has not been diagnosed.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s25",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A laboratory tests one bacterial sample against several different antibiotics. Explain why.",
        "options": [
            "To find which antibiotic that bacterium is sensitive to",
            "To check that the patient is not allergic to any of the antibiotics being considered",
            "To work out how large a dose of each antibiotic the patient will need to be given",
            "To produce a mixture of all the antibiotics that were tested for the patient to take",
        ],
        "correct_index": 0,
        "why": "A sensitivity test shows which drugs stop that strain growing, so the doctor can prescribe one the bacterium is not resistant to.",
    },
    {
        "id": "ks4-antibiotics-painkillers-s26",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A GP writes a prescription but asks the patient to wait three days before collecting it. Suggest why.",
        "options": [
            "Waiting allows the bacteria to grow enough for the drug to find them",
            "Many infections clear on their own, so waiting avoids using an antibiotic that is not needed",
            "Waiting makes the antibiotic cheaper for the health service to buy",
            "A prescription collected later contains a stronger dose than one collected the same day, which works better",
        ],
        "correct_index": 1,
        "why": "Most mild infections resolve without treatment, so delaying collection avoids unnecessary use while still giving the patient a route to the drug.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h05",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare what an antibiotic and a painkiller each act on during a bacterial infection.",
        "options": [
            "The antibiotic acts on the patient's nerves, while the painkiller acts on the bacteria themselves",
            "Both act on the bacteria, although the painkiller is much slower to take effect than the antibiotic is",
            "The antibiotic acts on the bacteria; the painkiller acts on the patient's sensation of pain",
            "Both act on the patient",
        ],
        "correct_index": 2,
        "why": "One targets the cause and the other the symptom, which is why the two are prescribed together rather than as alternatives.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h06",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain, in terms of natural selection, how repeated courses of an antibiotic produce a resistant population.",
        "options": [
            "Each course teaches the surviving bacteria how to break the drug down",
            "The antibiotic causes the mutations that make the bacteria resistant",
            "The bacteria pass the drug on to their offspring, who then tolerate it",
            "Random mutation makes a few bacteria resistant; the antibiotic kills the rest, so the resistant ones reproduce and become the majority",
        ],
        "correct_index": 3,
        "why": "The variation comes first, from random mutation; the drug then acts as the selection pressure that decides which bacteria reproduce.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h07",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that antibiotic resistance will soon make all antibiotics useless.",
        "options": [
            "It overstates the case; resistance is a serious and growing problem, but new drugs and careful prescribing can keep some antibiotics working",
            "It is correct, because resistance to one antibiotic gives a bacterium resistance to all the others as well, however differently those others act on it",
            "It is correct, because bacteria pass resistance to their offspring",
            "It is wrong, because a resistant bacterium cannot survive outside a hospital",
        ],
        "correct_index": 0,
        "why": "Resistance is specific to particular drugs and particular strains, so it erodes the usefulness of antibiotics rather than removing it outright.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h08",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A farm stops giving antibiotics routinely, and resistant bacteria in its herd become less common. Explain why.",
        "options": [
            "Without the drug present the resistant bacteria lose the ability to reproduce, so their numbers fall away over the following months",
            "With no antibiotic selecting for them, resistant bacteria have no advantage, so their share of the population falls",
            "The antibiotic that had been used is gradually washed out of the animals' tissues, which destroys the resistant bacteria with it",
            "The herd becomes immune",
        ],
        "correct_index": 1,
        "why": "Resistance is only an advantage while the drug is present; remove the selection pressure and resistant strains compete on equal terms again.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h09",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A patient's infection clears with antibiotic A but returns and no longer responds to it. Explain the most likely reason.",
        "options": [
            "The patient has become resistant to antibiotic A after taking one course of it",
            "Antibiotic A loses its effect permanently once a patient has taken it once before",
            "The surviving bacteria were the resistant ones, and they have multiplied",
            "The infection has turned into a viral one, which antibiotic A cannot treat, because a bacterium can change into a virus",
        ],
        "correct_index": 2,
        "why": "The course removed the sensitive bacteria and left the resistant ones, so the population that regrew is resistant.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h10",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that taking a painkiller at the same time as an antibiotic slows the antibiotic down.",
        "options": [
            "It is correct, because the two drugs compete for the same place on the bacterial cell wall",
            "It is correct, because the painkiller lowers the fever that helps the antibiotic work",
            "It is wrong, because a painkiller makes the antibiotic reach the bacteria faster than usual",
            "It is wrong; the two act on different things",
        ],
        "correct_index": 3,
        "why": "The painkiller acts on the patient's perception of pain and the antibiotic on the bacteria, so they are not in competition.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h11",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a broad-spectrum antibiotic may add more to the resistance problem than a narrow-spectrum one.",
        "options": [
            "It exposes many species of bacteria to the drug, so resistance can be selected in more of them",
            "It is a much stronger drug, so it causes more mutations in the bacteria it reaches",
            "It stays in the body far longer, and a longer stay gives any bacterium more time in which to become resistant to it",
            "It is given at a lower dose",
        ],
        "correct_index": 0,
        "why": "Selection acts on every species the drug reaches, so the wider the spectrum, the wider the range of bacteria in which resistance can be selected.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h12",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a patient who feels better after three days should still finish a seven-day course.",
        "options": [
            "The tablets taken in the last four days are the ones that treat the symptoms of the illness",
            "Bacteria may still remain, and the least affected survive a part course",
            "An unfinished course means the patient must start the whole course again from the beginning",
            "Feeling better after three days shows the drug has not begun working yet on the infection",
        ],
        "correct_index": 1,
        "why": "Symptoms ease once numbers fall, well before the last bacteria are gone, and those last survivors are the ones most able to withstand the drug.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h13",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "In a sensitivity test, antibiotic A clears a 5 mm zone around its disc, antibiotic B an 18 mm zone and antibiotic C no zone. Deduce which antibiotic should be prescribed.",
        "options": [
            "Antibiotic C, because no zone means the bacteria were destroyed completely",
            "Antibiotic A, because a small zone shows a gentle drug that causes fewer side effects",
            "Antibiotic B, because the largest clear zone shows the bacteria were most strongly inhibited by it",
            "None of them",
        ],
        "correct_index": 2,
        "why": "The clear zone is where the bacteria failed to grow, so the largest zone identifies the drug this strain is most sensitive to.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h14",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student writes that bacteria learn to fight off an antibiotic. Explain why this is not how resistance arises.",
        "options": [
            "Resistance arises because each bacterium gradually strengthens its cell wall during the course of the treatment it is given",
            "Resistance arises because the antibiotic itself alters the genes of any bacteria that it fails to kill outright",
            "Resistance arises because bacteria copy genes from the patient's cells",
            "Resistance comes from random mutations that already exist; the antibiotic selects the bacteria that carry them",
        ],
        "correct_index": 3,
        "why": "Nothing about the bacterium responds to the drug on purpose. The mutation is random and comes first; the drug only decides which bacteria survive.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h15",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a hospital nurses a patient carrying MRSA in a side room away from other patients.",
        "options": [
            "Isolating them limits spread of a strain that would be difficult to treat in other patients",
            "A side room is warmer, and MRSA does not survive long in a warm room, so the strain dies out",
            "MRSA can be treated properly in a side room because the antibiotic dose can be raised safely there",
            "Patients with MRSA produce a toxin that damages the other patients on the ward directly through the air",
        ],
        "correct_index": 0,
        "why": "Isolation is a transmission measure. It does not treat the patient, but it keeps a hard-to-treat strain away from people who are already ill.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h16",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A new compound kills bacteria in a dish. Evaluate the claim that it will therefore work as an antibiotic in patients.",
        "options": [
            "The claim is sound, because a compound that kills bacteria in a dish will behave in the same way inside the body of a patient who is already infected",
            "The claim is premature; the compound must still be shown to be non-toxic, to reach the infection in the body and to work at a safe dose",
            "The claim is wrong, because nothing that works in a dish can work in a living patient",
            "The claim is sound, provided the dish was kept at body temperature during the test",
        ],
        "correct_index": 1,
        "why": "Killing bacteria is only the first requirement. Most candidates fail later on toxicity, absorption or dose, which is why the testing pathway exists.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h17",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why one country reducing its antibiotic use does not remove resistance from that country.",
        "options": [
            "Resistance genes are carried in the soil of neighbouring countries and blow across in the wind",
            "A country's own bacteria keep their resistance for a fixed period of one hundred years afterwards",
            "Resistant bacteria arrive with people, animals and food from elsewhere",
            "Reducing use in one country raises the rate at which bacteria mutate in the countries nearby",
        ],
        "correct_index": 2,
        "why": "Bacteria travel with their hosts and with trade, so resistance selected anywhere can be imported everywhere.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h18",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the consequences for a patient of an infection with a sensitive strain and one with a resistant strain.",
        "options": [
            "A resistant infection is less severe, because a resistant bacterium spends its energy on resisting the drug and not on growing",
            "The two are identical, because resistance changes how a bacterium spreads rather than how it is treated",
            "A resistant infection is easier to treat, because it responds to more antibiotics",
            "A sensitive strain clears with a first-choice drug; a resistant one may need longer or stronger treatment",
        ],
        "correct_index": 3,
        "why": "Resistance changes the treatment rather than the bacterium's ability to cause disease, so the illness lasts longer and needs second-choice drugs.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h19",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why an infection picked up in hospital may be harder to clear than the same kind of infection picked up at home.",
        "options": [
            "Hospital strains are more often resistant",
            "Hospital air contains more bacteria, and those bacteria multiply much faster in a warm building",
            "A hospital patient is given a lower dose of antibiotic than a patient at home would receive",
            "Bacteria in a hospital reproduce sexually, which makes them more difficult to kill with a drug",
        ],
        "correct_index": 0,
        "why": "Heavy antibiotic use in hospitals selects resistant strains, so infections acquired there are more likely to resist first-choice drugs.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h20",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why resistance appears in bacteria much faster than a comparable change appears in a large animal population.",
        "options": [
            "Bacteria are exposed to more chemicals in their surroundings than a large animal is exposed to",
            "Bacteria divide every twenty minutes or so, so many generations and many mutations occur in a short time",
            "Bacteria choose to change their DNA when they meet a substance that would otherwise kill them",
            "Bacteria have a much larger genome, so there is far more DNA in which a helpful mutation can arise in one generation",
        ],
        "correct_index": 1,
        "why": "Natural selection works generation by generation, and a bacterium can pass through thousands of generations in the time a large animal needs for one.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h21",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that improving hand hygiene is more useful than developing new antibiotics.",
        "options": [
            "The claim is sound, because an infection that has already started can be cleared by washing hands properly",
            "The claim is wrong, because hand hygiene has no measurable effect on how infections spread between patients",
            "Both matter: hygiene prevents infections arising, while new drugs treat those that do",
            "The claim is sound, because a new antibiotic would be resistant to hand washing",
        ],
        "correct_index": 2,
        "why": "The two work at different points. Hygiene reduces how many infections start; antibiotics deal with the ones that still happen.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h22",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why an antibiotic that kills bacteria efficiently in early testing may still be abandoned before reaching patients.",
        "options": [
            "The bacteria used in the test become resistant to it during the test itself",
            "Regulators approve only drugs discovered from moulds, as penicillin was",
            "An efficient antibiotic is too expensive to manufacture",
            "It may prove toxic, may be broken down before it reaches the infection, or may cause side effects that outweigh its benefit",
        ],
        "correct_index": 3,
        "why": "Efficacy against bacteria is only one of the requirements; toxicity, how the body handles the drug and side effects all end candidate drugs.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h23",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why antibiotic resistance makes cancer treatment with chemotherapy more dangerous.",
        "options": [
            "Chemotherapy weakens the immune system, so patients depend on antibiotics to control infections that a resistant strain may survive",
            "Chemotherapy drugs stop working when an antibiotic is taken at the same time as them",
            "Resistant bacteria feed on chemotherapy drugs and grow much faster because of them",
            "Chemotherapy causes the bacteria living in the patient's gut to mutate into resistant forms, which then spread through the rest of the body and cause infection",
        ],
        "correct_index": 0,
        "why": "Chemotherapy patients rely on antibiotics to cover a weakened immune system, so a resistant infection removes the safety net the treatment depends on.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h24",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain one disadvantage of using a broad-spectrum antibiotic when the species causing an infection is already known.",
        "options": [
            "A broad-spectrum antibiotic is far weaker against the species causing the infection than a narrow one would be at the same dose",
            "It kills harmless gut bacteria as well, which can cause further problems for the patient",
            "A broad-spectrum drug must be injected rather than swallowed, which means a stay in hospital for each patient who needs one",
            "It works too quickly",
        ],
        "correct_index": 1,
        "why": "A broad-spectrum drug cannot distinguish the pathogen from the harmless bacteria a patient normally carries, and losing those causes problems of its own.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h25",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why resistance to one antibiotic does not necessarily mean resistance to another.",
        "options": [
            "A bacterium is able to carry resistance to one drug at a time, and it loses the first resistance as soon as it gains a second one",
            "Resistance is inherited from the patient, so it applies to whichever drug the patient has taken",
            "Different antibiotics attack different targets, so a mutation protecting against one may not protect against another",
            "Resistance applies to the dose rather than to the drug",
        ],
        "correct_index": 2,
        "why": "Resistance is a change in a particular target or process, so it protects against drugs acting there and leaves other drugs effective.",
    },
    {
        "id": "ks4-antibiotics-painkillers-h26",
        "subtopic_slug": "antibiotics-painkillers",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that antibiotic resistance would disappear if every country stopped using antibiotics for one year.",
        "options": [
            "The claim is sound, because resistance genes are lost from a population within a few weeks of the drug being withdrawn",
            "The claim is sound, because bacteria return to their original form once the drug that selected them is gone",
            "The claim is wrong, because resistance would instead increase sharply during a year without antibiotics being used",
            "It is wrong; resistance genes persist even without selection",
        ],
        "correct_index": 3,
        "why": "Removing the drug removes the advantage resistance gives, but the genes remain in the population and are selected again as soon as use resumes.",
    },
]
