"""Biology · Inheritance, Variation and Evolution — the MRB-338 expansion,
subtopic `resistant-bacteria`.

The baseline twelve cover where Staphylococcus aureus lives, what
antibiotics treat, the twenty-minute doubling time, the term selection
pressure, the "bacteria change their DNA" misconception, why drug companies
invest little, phage therapy, the "antibiotics get weaker" error, ten
million bacteria with two mutants, a virus-caused sore throat, farming and
hand hygiene. This file supplies the parts the specification asks for and
the baseline leaves out: the SEQUENCE by which resistance arises and
spreads (random mutation, the antibiotic kills the non-resistant, the
resistant survive and reproduce, the resistant strain spreads because
people are not immune and there is no effective treatment); the THREE
control measures (doctors not prescribing antibiotics for non-serious or
viral infections, patients completing the course, restricting agricultural
use); and why developing new antibiotics is slow and costly.

⚠️ `evolution-natural-selection` owns the general mechanism and
`evidence-for-evolution` owns resistance treated as evidence. This leaf is
about the bacteria, the drugs and what can be done about them.
"""

TOPIC = "inheritance"
SUBJECT = "biology"

QUESTIONS = [
    {
        "id": "ks4-resistant-bacteria-e05",
        "subtopic_slug": "resistant-bacteria",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State where the allele for antibiotic resistance originally comes from.",
        "options": [
            "A random mutation in a bacterium",
            "The antibiotic itself, which adds the allele to the bacteria it touches",
            "The patient, who passes it to the bacteria living inside their body",
            "The hospital ward where the patient was treated",
        ],
        "correct_index": 0,
        "why": "Resistance begins as a chance mutation, which is present before the antibiotic is ever used.",
    },
    {
        "id": "ks4-resistant-bacteria-e06",
        "subtopic_slug": "resistant-bacteria",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happens to the non-resistant bacteria when an antibiotic is given.",
        "options": [
            "They become resistant so that they can survive the course of treatment",
            "They reproduce faster than they did before the antibiotic was given to them",
            "They are killed, leaving only the resistant ones",
            "They pass their alleles to the resistant ones",
        ],
        "correct_index": 2,
        "why": "The antibiotic kills the bacteria that have no resistance allele, leaving the resistant ones behind.",
    },
    {
        "id": "ks4-resistant-bacteria-e07",
        "subtopic_slug": "resistant-bacteria",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give one thing doctors should avoid in order to slow the spread of resistance.",
        "options": [
            "Washing their hands between seeing one patient and seeing the next one",
            "Asking a patient about the symptoms they have been experiencing",
            "Recording which antibiotic was used",
            "Prescribing antibiotics for non-serious or viral infections",
        ],
        "correct_index": 3,
        "why": "Every unnecessary course applies a selection pressure and makes resistance more likely to spread.",
    },
    {
        "id": "ks4-resistant-bacteria-e08",
        "subtopic_slug": "resistant-bacteria",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a patient should do with a course of antibiotics they have been given.",
        "options": [
            "Stop taking them as soon as they begin to feel a little better than before",
            "Complete the whole course",
            "Share the remaining tablets with anybody else who has similar symptoms",
            "Save half of the course in case the same illness returns some time later",
        ],
        "correct_index": 1,
        "why": "Finishing the course kills the bacteria that survive longest, so none are left to breed a resistant population.",
    },
    {
        "id": "ks4-resistant-bacteria-e09",
        "subtopic_slug": "resistant-bacteria",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the third control measure, besides careful prescribing and finishing a course.",
        "options": [
            "Giving every patient a larger dose than the one they actually need",
            "Using two different antibiotics for every infection that is treated",
            "Restricting the use of antibiotics in farming",
            "Closing hospitals down completely for a time",
        ],
        "correct_index": 2,
        "why": "Antibiotics used widely in agriculture select for resistant bacteria that can then reach people.",
    },
    {
        "id": "ks4-resistant-bacteria-e10",
        "subtopic_slug": "resistant-bacteria",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State why a resistant strain of bacteria spreads quickly through a population of people.",
        "options": [
            "Because people are not immune to it and there is no effective treatment",
            "Because people are able to make themselves immune to it very quickly",
            "Because the strain changes into a different species as it spreads",
            "Because resistant bacteria are larger",
        ],
        "correct_index": 0,
        "why": "A new resistant strain meets no immunity and no working drug, so nothing slows it down.",
    },
    {
        "id": "ks4-resistant-bacteria-e11",
        "subtopic_slug": "resistant-bacteria",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how quickly new antibiotics can be developed.",
        "options": [
            "Within a few days, because the chemistry involved is very straightforward indeed",
            "Very slowly, and at great cost",
            "Immediately, as soon as a resistant strain of bacteria has been identified",
            "In about a week or two at the very most",
        ],
        "correct_index": 1,
        "why": "Development takes many years of testing and enormous sums of money, so new drugs cannot keep pace with resistance.",
    },
    {
        "id": "ks4-resistant-bacteria-e12",
        "subtopic_slug": "resistant-bacteria",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what MRSA stands for in terms of what it is resistant to.",
        "options": [
            "A virus that has become resistant to every antiviral drug that exists",
            "A fungus that is resistant to the treatments used against it in hospitals",
            "A type of vaccine",
            "A strain of bacteria resistant to a particular antibiotic",
        ],
        "correct_index": 3,
        "why": "MRSA is a strain of Staphylococcus aureus that the antibiotic methicillin can no longer kill.",
    },
    {
        "id": "ks4-resistant-bacteria-s05",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Put the stages of resistance developing in the correct order.",
        "options": [
            "The antibiotic is given, a mutation is caused by it, and the strain then spreads",
            "The strain spreads first, then a mutation occurs, and the antibiotic is given last",
            "The bacteria decide to become resistant",
            "Mutation, the antibiotic kills the rest, the survivors reproduce, the strain spreads",
        ],
        "correct_index": 3,
        "why": "The mutation comes first by chance; the antibiotic only selects between bacteria that already differ.",
    },
    {
        "id": "ks4-resistant-bacteria-s06",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why finishing a course of antibiotics reduces the risk of resistance.",
        "options": [
            "Because the last few tablets of a course are stronger than the earlier ones",
            "Because stopping early always leaves the hardest-to-kill bacteria alive",
            "Because a full course changes the alleles of the bacteria back again",
            "Because it uses up the tablets",
        ],
        "correct_index": 1,
        "why": "The bacteria that survive longest are the least susceptible, and those are exactly the ones to finish off.",
    },
    {
        "id": "ks4-resistant-bacteria-s07",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why giving antibiotics for a cold makes resistance worse.",
        "options": [
            "Because a cold is caused by a virus, but the drug still selects resistant bacteria",
            "Because the antibiotic makes the cold virus mutate into a bacterium",
            "Because antibiotics have no effect on anything at all in the body",
            "Because a cold lasts longer than a bacterial infection",
        ],
        "correct_index": 0,
        "why": "The drug cannot touch the virus, but it still kills susceptible bacteria and leaves resistant ones behind.",
    },
    {
        "id": "ks4-resistant-bacteria-s08",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what an antibiotic does and does not act on.",
        "options": [
            "It kills viruses but has no effect at all on any kind of bacterium",
            "It kills both bacteria and viruses equally well in every patient",
            "It kills bacteria but never has any effect on viruses",
            "It kills neither of them",
        ],
        "correct_index": 2,
        "why": "Antibiotics attack structures and processes that bacteria have and viruses do not.",
    },
    {
        "id": "ks4-resistant-bacteria-s09",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why antibiotic use in farming can lead to resistant infections in people.",
        "options": [
            "Because farm animals pass their own alleles directly to the people who eat them",
            "Because resistant bacteria selected in the animals can reach people in food",
            "Because antibiotics given to animals become stronger inside the animals' bodies",
            "Because farm animals catch human diseases",
        ],
        "correct_index": 1,
        "why": "Bacteria move between animals, food, the environment and people, carrying their resistance alleles with them.",
    },
    {
        "id": "ks4-resistant-bacteria-s10",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happens to the proportion of resistant bacteria during a course of treatment.",
        "options": [
            "It falls, because the antibiotic kills the resistant bacteria first of all",
            "It stays exactly the same throughout the whole of the course of treatment",
            "It cannot be measured",
            "It rises",
        ],
        "correct_index": 3,
        "why": "The susceptible bacteria are removed, so the resistant ones make up a larger share of what is left.",
    },
    {
        "id": "ks4-resistant-bacteria-s11",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why hospitals are places where resistant strains are especially common.",
        "options": [
            "Because hospitals are warmer than any other building that people spend time in",
            "Because bacteria are only able to reproduce inside a hospital building",
            "Because antibiotics are used heavily there and many patients are already unwell",
            "Because hospitals are cleaned too often",
        ],
        "correct_index": 2,
        "why": "Heavy antibiotic use applies a strong selection pressure, and vulnerable patients are close together.",
    },
    {
        "id": "ks4-resistant-bacteria-s12",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a resistance mutation gives no advantage when no antibiotic is present.",
        "options": [
            "Because there is nothing for the resistance to protect the bacterium against",
            "Because the mutation disappears from the bacterium when no antibiotic is used",
            "Because an antibiotic is what causes the mutation to appear in the first place",
            "Because a bacterium without the mutation cannot reproduce at all",
        ],
        "correct_index": 0,
        "why": "An advantage only exists in relation to a pressure, and with no drug present resistance is simply spare machinery.",
    },
    {
        "id": "ks4-resistant-bacteria-s13",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how vaccination helps to slow the development of antibiotic resistance.",
        "options": [
            "Fewer people become ill, so fewer courses of antibiotics are needed",
            "It kills resistant bacteria directly wherever they are found in the body",
            "It changes the alleles carried by the bacteria in the patient's body",
            "It makes antibiotics stronger",
        ],
        "correct_index": 0,
        "why": "Preventing infection removes the need for treatment, which removes the selection pressure.",
    },
    {
        "id": "ks4-resistant-bacteria-s14",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why resistance appears in bacteria faster than in larger organisms.",
        "options": [
            "Because bacteria are able to choose which alleles they will carry next",
            "Because larger organisms never carry any mutations at all",
            "Because bacteria reproduce very rapidly",
            "Because bacteria are smaller than other organisms",
        ],
        "correct_index": 2,
        "why": "Evolution is measured in generations, and a bacterial population can pass through dozens in a single day.",
    },
    {
        "id": "ks4-resistant-bacteria-s15",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State why the development of resistance is described as natural selection.",
        "options": [
            "Because bacteria change themselves deliberately in response to the drug",
            "Because the antibiotic is a natural substance rather than a manufactured one",
            "Because the bacteria are naturally resistant",
            "Because an existing variation is selected by a pressure in the environment",
        ],
        "correct_index": 3,
        "why": "Variation exists, a pressure favours some individuals, and their alleles become commoner — the standard sequence.",
    },
    {
        "id": "ks4-resistant-bacteria-s16",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a doctor takes a swab before prescribing an antibiotic for a serious infection.",
        "options": [
            "To make the patient wait until the infection has cleared up on its own",
            "To check which bacterium is present and which drug will work",
            "To remove the resistant bacteria from the wound with the swab itself",
            "To count how many bacteria there are",
        ],
        "correct_index": 1,
        "why": "Choosing the right drug first time avoids a wasted course that would select for resistance without curing anything.",
    },
    {
        "id": "ks4-resistant-bacteria-s17",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what is meant by a resistant strain of bacteria.",
        "options": [
            "A single bacterium that has survived a course of antibiotic treatment by chance",
            "A group of bacteria that has been deliberately bred in a laboratory by scientists",
            "A population of bacteria that the antibiotic can no longer kill",
            "Bacteria that cause no disease",
        ],
        "correct_index": 2,
        "why": "A strain is a population descended from resistant ancestors, so nearly all of its members carry the allele.",
    },
    {
        "id": "ks4-resistant-bacteria-s18",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why resistance is a problem even for people who have never taken an antibiotic.",
        "options": [
            "Because anybody can be infected by a resistant strain",
            "Because a person who has never taken an antibiotic carries no bacteria at all",
            "Because resistance is inherited from a person's parents rather than caught",
            "Because everybody takes antibiotics",
        ],
        "correct_index": 0,
        "why": "Resistant bacteria spread from person to person like any other infection, whatever the new patient's history.",
    },
    {
        "id": "ks4-resistant-bacteria-s19",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why using several different antibiotics together can slow resistance.",
        "options": [
            "Because two drugs together are always twice as strong as one drug on its own",
            "Because a bacterium would need to carry resistance to both drugs at once",
            "Because one drug destroys the mutation that the other drug has caused",
            "Because the drugs cancel each other out",
        ],
        "correct_index": 1,
        "why": "Carrying two independent mutations is far less likely than carrying one, so few bacteria survive.",
    },
    {
        "id": "ks4-resistant-bacteria-s20",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happens to a resistant bacterium that is exposed to the antibiotic.",
        "options": [
            "It dies more slowly than the other bacteria present around it in the body",
            "It loses its resistance allele and is then killed by the drug",
            "It stops reproducing inside the body",
            "It survives and goes on to reproduce",
        ],
        "correct_index": 3,
        "why": "Survival plus reproduction is what turns a rare mutation into a whole resistant population.",
    },
    {
        "id": "ks4-resistant-bacteria-s21",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why resistance would still develop even if every patient finished every course.",
        "options": [
            "Because finishing a course causes a mutation in the bacteria being treated",
            "Because the last tablets of a course are the weakest of all",
            "Because patients never finish courses",
            "Because mutations still occur by chance",
        ],
        "correct_index": 3,
        "why": "Good practice slows resistance down; it cannot stop it, because mutation and selection continue regardless.",
    },
    {
        "id": "ks4-resistant-bacteria-s22",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why an infection with a resistant strain is more likely to be fatal.",
        "options": [
            "Because a resistant strain produces a stronger toxin than other strains do",
            "Because the usual treatment does not work, so the infection is not stopped",
            "Because a resistant strain reproduces more slowly inside a patient's body",
            "Because resistant bacteria are larger in size",
        ],
        "correct_index": 1,
        "why": "The danger comes from losing the treatment, not from the bacterium becoming more aggressive.",
    },
    {
        "id": "ks4-resistant-bacteria-s23",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe why resistance is described as an example of evolution happening now.",
        "options": [
            "Because the population changes over generations in a way we can measure",
            "Because the antibiotic alters the genetic material of the bacteria it reaches",
            "Because a single bacterium changes during the course of its own lifetime",
            "Because bacteria are very simple organisms",
        ],
        "correct_index": 0,
        "why": "The proportion of resistant individuals rises generation by generation, which is exactly what evolution means.",
    },
    {
        "id": "ks4-resistant-bacteria-s24",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State one reason antibiotics should not be used to treat a mild throat infection.",
        "options": [
            "Because a mild infection cannot be treated with any medicine of any kind",
            "Because mild infections are always caused by fungi rather than by bacteria",
            "Because an unnecessary course selects resistant bacteria for no benefit",
            "Because the tablets taste unpleasant",
        ],
        "correct_index": 2,
        "why": "A mild infection the body will clear anyway gains nothing from a course that still drives resistance.",
    },
    {
        "id": "ks4-resistant-bacteria-s25",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the number of new antibiotics being developed matters to everybody.",
        "options": [
            "Because a new antibiotic makes the older ones work better again over time",
            "Because without new drugs there may one day be untreatable infections",
            "Because new antibiotics stop mutations happening in bacteria altogether",
            "Because older antibiotics expire",
        ],
        "correct_index": 1,
        "why": "Resistance keeps spreading, so the supply of new drugs is what stands between us and untreatable infections.",
    },
    {
        "id": "ks4-resistant-bacteria-s26",
        "subtopic_slug": "resistant-bacteria",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why isolating a patient with a resistant infection is an effective measure.",
        "options": [
            "Because isolation makes the resistant bacteria lose their resistance allele",
            "Because a patient kept alone recovers from any infection much more quickly",
            "Because isolation kills the bacteria present",
            "Because it stops the strain being passed to other patients",
        ],
        "correct_index": 3,
        "why": "Resistance cannot be reversed, so limiting how far a resistant strain spreads is the practical response.",
    },
    {
        "id": "ks4-resistant-bacteria-h05",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A patient stops taking antibiotics after three days of a seven-day course. Predict the effect on the bacteria left in the body.",
        "options": [
            "Every bacterium left in the body will have been killed by the first three days",
            "The bacteria that remain lose their resistance and become easy to kill",
            "The least susceptible bacteria survive and reproduce, so treatment gets harder",
            "Nothing at all happens to them",
        ],
        "correct_index": 2,
        "why": "Stopping early removes the pressure exactly when only the toughest bacteria are left.",
    },
    {
        "id": "ks4-resistant-bacteria-h06",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that resistance could be stopped completely by banning antibiotics.",
        "options": [
            "It is unworkable — people would die of treatable infections that we can cure now",
            "It would work perfectly, because resistance disappears as soon as a drug is not used",
            "It is correct, because bacteria lose their alleles when they are not exposed to a drug",
            "It is correct, because antibiotics are not needed",
        ],
        "correct_index": 0,
        "why": "The alleles persist at low frequency, and the cost of losing antibiotics altogether would be enormous.",
    },
    {
        "id": "ks4-resistant-bacteria-h07",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare what an antibiotic does to a bacterial population with what it does to an individual bacterium.",
        "options": [
            "It changes the makeup of the population; it kills or fails to kill each individual",
            "It changes an individual bacterium into a resistant one and leaves the population alone",
            "It has exactly the same effect on the population as it does on an individual",
            "It affects neither of them",
        ],
        "correct_index": 0,
        "why": "No bacterium changes; what changes is which bacteria are left, which is a property of the population.",
    },
    {
        "id": "ks4-resistant-bacteria-h08",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a resistant strain can spread between countries within weeks.",
        "options": [
            "Because the resistance allele travels through the air across very long distances",
            "Because bacteria are able to move by themselves from one country to another",
            "Because infected people travel, carrying the bacteria with them",
            "Because antibiotics are shipped abroad",
        ],
        "correct_index": 2,
        "why": "The bacteria move with their hosts, so a strain arising in one hospital can appear anywhere very quickly.",
    },
    {
        "id": "ks4-resistant-bacteria-h09",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why resistance can appear in an infection that has never met the antibiotic before.",
        "options": [
            "Because the infection is able to predict which antibiotic will be used on it",
            "Because an antibiotic is present in the body of every person at all times",
            "Because all bacteria are already resistant",
            "Because mutations occur at random, so the allele can already be present by chance",
        ],
        "correct_index": 3,
        "why": "Mutation does not wait for the drug; with millions of bacteria dividing, rare variants are always present.",
    },
    {
        "id": "ks4-resistant-bacteria-h10",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why resistance can sometimes fall again after an antibiotic stops being used.",
        "options": [
            "Because the resistant bacteria lose the allele once the drug has been withdrawn",
            "Because resistance may carry a cost, so plain bacteria compete better without the drug",
            "Because a bacterium cannot survive without being exposed to an antibiotic",
            "Because resistance is never inherited",
        ],
        "correct_index": 1,
        "why": "Maintaining resistance machinery can slow growth, so without the drug the plain strain may outcompete it.",
    },
    {
        "id": "ks4-resistant-bacteria-h11",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why hand hygiene works against a resistant strain even though no drug is involved.",
        "options": [
            "Because soap adds a mutation to the bacteria that removes their resistance",
            "Because washing hands makes the antibiotic work better in the patient",
            "Because it stops the strain being passed on",
            "Because resistance is carried only on the hands",
        ],
        "correct_index": 2,
        "why": "Preventing spread is entirely independent of whether a drug still works, which is why it remains effective.",
    },
    {
        "id": "ks4-resistant-bacteria-h12",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why resistance is a bigger problem for surgery than for a minor cut.",
        "options": [
            "Because operations depend on antibiotics to prevent serious infection",
            "Because a minor cut never becomes infected by bacteria of any kind at all",
            "Because surgery is only carried out on patients who are already resistant",
            "Because surgery takes a long time",
        ],
        "correct_index": 0,
        "why": "Routine operations became safe partly because infection could be prevented and treated; without that they become far riskier.",
    },
    {
        "id": "ks4-resistant-bacteria-h13",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a doctor may still prescribe an antibiotic even when resistance is a concern.",
        "options": [
            "Because prescribing an antibiotic removes resistance from the community",
            "Because a serious untreated infection can kill the patient in front of them",
            "Because antibiotics work equally well on every possible infection",
            "Because patients demand them",
        ],
        "correct_index": 1,
        "why": "The risk to the individual now has to be weighed against the slower, shared risk of resistance spreading.",
    },
    {
        "id": "ks4-resistant-bacteria-h14",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why resistance to a brand new antibiotic often appears within a few years.",
        "options": [
            "Because a new antibiotic is always weaker than an older one is in practice",
            "Because the drug companies release resistant bacteria alongside the drug",
            "Because new drugs are tested badly",
            "Because bacterial populations are huge, so a useful mutation turns up quickly",
        ],
        "correct_index": 3,
        "why": "With astronomical numbers of bacteria dividing constantly, even a rare mutation appears in a short time.",
    },
    {
        "id": "ks4-resistant-bacteria-h15",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why bacteria being able to share genetic material makes resistance spread faster.",
        "options": [
            "Because sharing genetic material causes new mutations in every bacterium involved",
            "Because bacteria that share material stop reproducing altogether afterwards",
            "Because it makes the bacteria larger",
            "Because a resistance allele can pass sideways between bacteria, not only to offspring",
        ],
        "correct_index": 3,
        "why": "Transfer between cells lets resistance jump sideways through a population, and even between species.",
    },
    {
        "id": "ks4-resistant-bacteria-h16",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why resistance is described as a problem for society rather than for one patient.",
        "options": [
            "Because a patient who takes antibiotics never becomes ill again afterwards",
            "Because one person's unnecessary course raises the risk for everybody else",
            "Because only societies and not individuals can be infected by bacteria",
            "Because doctors do not treat individuals",
        ],
        "correct_index": 1,
        "why": "The resistant bacteria selected in one person circulate, so the cost of overuse is shared by everyone.",
    },
    {
        "id": "ks4-resistant-bacteria-h17",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the effect of a short course of antibiotics with a long one on a growing resistance problem.",
        "options": [
            "A course that is too short leaves survivors; too long a one adds pressure for no gain",
            "A short course is always better than a long one in every situation",
            "A long course always removes resistance from the whole population",
            "The length of a course makes no difference at all",
        ],
        "correct_index": 0,
        "why": "The right length is the one that clears the infection; either error makes the resistance problem worse.",
    },
    {
        "id": "ks4-resistant-bacteria-h18",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a bacterium that is resistant to one antibiotic may still be killed by another.",
        "options": [
            "Because the second antibiotic makes the bacterium lose its resistance allele",
            "Because resistance to one drug wears off after a short period of time",
            "Because different drugs attack different parts of the bacterium",
            "Because the second drug is always stronger",
        ],
        "correct_index": 2,
        "why": "A mutation that blocks one drug's target usually does nothing about a completely different target.",
    },
    {
        "id": "ks4-resistant-bacteria-h19",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the mutation rate of bacteria does not need to be high for resistance to appear.",
        "options": [
            "Because bacteria are able to choose when they will produce a mutation",
            "Because the numbers of bacteria are so vast",
            "Because every bacterium carries the resistance allele from the start",
            "Because mutations are caused by antibiotics",
        ],
        "correct_index": 1,
        "why": "A one-in-a-billion mutation is a near certainty in a population of many billions of cells.",
    },
    {
        "id": "ks4-resistant-bacteria-h20",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why drug companies have found new antibiotics a poor investment.",
        "options": [
            "Because an antibiotic is far more expensive to manufacture than any other drug",
            "Because antibiotics are given away free by every government in the world",
            "Because no patient ever needs an antibiotic",
            "Because a short course earns far less than a drug taken daily for years",
        ],
        "correct_index": 3,
        "why": "The economics run the wrong way: the most valuable new antibiotic would be the one kept in reserve and rarely sold.",
    },
    {
        "id": "ks4-resistant-bacteria-h21",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why keeping a new antibiotic in reserve would slow resistance to it.",
        "options": [
            "Because an antibiotic kept in reserve becomes stronger the longer it is stored",
            "Because reserving a drug removes the alleles that would make bacteria resistant",
            "Because the less it is used, the weaker the selection pressure favouring resistance",
            "Because reserved drugs cannot be used",
        ],
        "correct_index": 2,
        "why": "Resistance spreads in proportion to how much the drug is used, so restricting use preserves its value.",
    },
    {
        "id": "ks4-resistant-bacteria-h22",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that resistance shows bacteria are getting stronger over time.",
        "options": [
            "It is misleading — they are not stronger, only unaffected by one particular drug",
            "It is correct, because a resistant bacterium is stronger in every possible respect",
            "It is correct, because bacteria grow larger as they become more resistant",
            "It is wrong, because bacteria do not change",
        ],
        "correct_index": 0,
        "why": "Resistance is a narrow advantage against one chemical; in other respects resistant bacteria may do worse.",
    },
    {
        "id": "ks4-resistant-bacteria-h23",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a farm using antibiotics routinely applies a stronger selection pressure than a hospital.",
        "options": [
            "Because the drugs are given constantly to healthy animals",
            "Because farm animals are much larger than the patients treated in a hospital",
            "Because a hospital never uses any antibiotics on the patients it treats",
            "Because farms are dirtier than hospitals",
        ],
        "correct_index": 0,
        "why": "Constant low-level exposure across a whole herd selects for resistance continuously rather than in short bursts.",
    },
    {
        "id": "ks4-resistant-bacteria-h24",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why resistance is expected to keep appearing however carefully antibiotics are used.",
        "options": [
            "Because careful use of antibiotics causes more mutations to occur in bacteria",
            "Because mutation is random and any use of a drug selects the survivors",
            "Because doctors are unable to follow the guidance they have been given",
            "Because resistance is inherited by people",
        ],
        "correct_index": 1,
        "why": "Good practice buys time; it cannot remove the two ingredients, which are random mutation and selection.",
    },
    {
        "id": "ks4-resistant-bacteria-h25",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the rise of resistance is sometimes compared to running up a down escalator.",
        "options": [
            "Because bacteria climb through the body in the way that a person climbs a stair",
            "Because antibiotics work only when a patient is moving about and active",
            "Because new drugs must keep arriving simply to hold the present position",
            "Because resistance rises and falls in a regular cycle",
        ],
        "correct_index": 2,
        "why": "Resistance erodes the drugs we have, so a steady supply of new ones is needed just to stand still.",
    },
    {
        "id": "ks4-resistant-bacteria-h26",
        "subtopic_slug": "resistant-bacteria",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why resistance is a clearer example of selection than most examples from the wild.",
        "options": [
            "Because bacteria are the only organisms that natural selection is able to act upon",
            "Because bacteria are not affected by any conditions other than the antibiotic",
            "Because wild animals cannot be studied at all",
            "Because the selection pressure is known exactly and the change is measured in days",
        ],
        "correct_index": 3,
        "why": "The pressure is deliberately applied and the population is enormous, so the whole process can be watched directly.",
    },
]
