"""Biology · Inheritance, Variation and Evolution — the MRB-338 expansion,
subtopic `sex-determination`.

The baseline twelve cover the word autosome, the size of the Y, the SRY
gene, the moment sex is decided, temperature-dependent sex in reptiles, a
sorted sperm sample, the ZW system in birds, why the 23rd pair may not
match, why about half of babies are male, a Y-bearing gamete, why the ratio
is not exactly even and why the autosomes are the same in both sexes. This
file supplies the core the baseline assumes: XX and XY written out; the
genetic diagram for sex and the one-to-one ratio that comes out of it; every
egg carrying an X; the father's gametes being the ones that differ; the
probability being one half for every child independently; converting that
between a fraction, a percentage and a ratio; the Y carrying very few genes
compared with the X; and why a run of boys or girls in one family is not
evidence against the ratio.

⚠️ `genetic-inheritance` owns the general Punnett-square method, and
`meiosis` owns why a gamete carries one chromosome of each pair. This leaf
stays on the 23rd pair.
"""

TOPIC = "inheritance"
SUBJECT = "biology"

QUESTIONS = [
    {
        "id": "ks4-sex-determination-e05",
        "subtopic_slug": "sex-determination",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the pair of sex chromosomes carried by a human female.",
        "options": [
            "Two X chromosomes, written as XX in a genetic diagram of the 23rd pair",
            "One X and one Y",
            "Two Y chromosomes",
            "XYY",
        ],
        "correct_index": 0,
        "why": "A female has two X chromosomes in the 23rd pair, so every egg she makes carries an X.",
    },
    {
        "id": "ks4-sex-determination-e06",
        "subtopic_slug": "sex-determination",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give the two sex chromosomes found in the body cells of a man.",
        "options": [
            "Two X chromosomes, in the same way that all of the other pairs match each other",
            "Two Y chromosomes, one inherited from each of his parents at fertilisation",
            "One X chromosome and one Y chromosome",
            "No sex chromosomes",
        ],
        "correct_index": 2,
        "why": "A male carries one X and one Y, so his sperm may carry either of the two.",
    },
    {
        "id": "ks4-sex-determination-e07",
        "subtopic_slug": "sex-determination",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State which sex chromosome every human egg cell carries.",
        "options": [
            "Either an X or a Y, depending on which of the mother's two chromosomes went into it",
            "A Y chromosome, because the mother carries one of each kind in her body cells",
            "Neither of them",
            "An X chromosome",
        ],
        "correct_index": 3,
        "why": "A mother has two X chromosomes, so meiosis can only put an X into each egg she produces.",
    },
    {
        "id": "ks4-sex-determination-e08",
        "subtopic_slug": "sex-determination",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State which parent's gametes decide the sex of a human baby.",
        "options": [
            "The mother's, because her eggs carry either an X chromosome or a Y chromosome",
            "The father's",
            "Both parents equally, since each of them supplies one chromosome of the 23rd pair",
            "Neither parent, because sex is decided by conditions in the womb after fertilisation",
        ],
        "correct_index": 1,
        "why": "Half the father's sperm carry an X and half carry a Y, so it is his gamete that decides.",
    },
    {
        "id": "ks4-sex-determination-e09",
        "subtopic_slug": "sex-determination",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the number of the chromosome pair that decides a person's sex.",
        "options": [
            "The first pair",
            "The 46th pair",
            "The 23rd pair, the only pair whose two members may be shaped differently",
            "The 22nd",
        ],
        "correct_index": 2,
        "why": "Twenty-two pairs are autosomes; the 23rd pair carries the sex chromosomes.",
    },
    {
        "id": "ks4-sex-determination-e10",
        "subtopic_slug": "sex-determination",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the two kinds of sperm cell a man produces.",
        "options": [
            "Some carrying an X and some carrying a Y",
            "Sperm that carry two X chromosomes and sperm that carry two Y chromosomes each",
            "Sperm that carry a sex chromosome and sperm that carry none of them at all",
            "They are all the same",
        ],
        "correct_index": 0,
        "why": "Meiosis separates the X from the Y, so half the sperm carry each one.",
    },
    {
        "id": "ks4-sex-determination-e11",
        "subtopic_slug": "sex-determination",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the sex chromosome that holds a large number of ordinary genes.",
        "options": [
            "The Y chromosome, which is very much the larger of the two in a body cell",
            "The X chromosome",
            "Both of them carry exactly the same number of genes as one another",
            "Neither carries genes",
        ],
        "correct_index": 1,
        "why": "The X is a large chromosome carrying many genes; the Y is small and carries very few.",
    },
    {
        "id": "ks4-sex-determination-e12",
        "subtopic_slug": "sex-determination",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the chance that any one human baby is a boy.",
        "options": [
            "One in four, in the same way as a recessive disorder appears in a quarter of children",
            "Three in four, because more boys than girls are born in most countries each year",
            "It cannot be given as a number at any point before the baby has been born",
            "One in two",
        ],
        "correct_index": 3,
        "why": "Half the sperm carry a Y, so each fertilisation has a one in two chance of giving a boy.",
    },
    {
        "id": "ks4-sex-determination-s05",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what a genetic diagram for sex has written along its two edges.",
        "options": [
            "The four possible offspring",
            "The 22 pairs of autosomes",
            "Two Y chromosomes",
            "The mother's gametes, both carrying X, along one edge and the father's X and Y along the other",
        ],
        "correct_index": 3,
        "why": "One parent's possible gametes go on each edge, and the boxes then give the four possible offspring.",
    },
    {
        "id": "ks4-sex-determination-s06",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the ratio of boys to girls predicted by a genetic diagram for sex.",
        "options": [
            "Three boys to one girl, which is the ratio a cross between two carriers would give",
            "One boy to one girl",
            "Two boys to every one girl, because a father carries two different sex chromosomes",
            "All of the children would be boys",
        ],
        "correct_index": 1,
        "why": "Two of the four boxes give XX and two give XY, so the predicted ratio is one to one.",
    },
    {
        "id": "ks4-sex-determination-s07",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a mother cannot influence whether her baby is a boy or a girl.",
        "options": [
            "Because every egg she produces carries an X chromosome",
            "Because a mother's body decides the sex of her baby only after it has been born",
            "Because a mother passes on no chromosomes at all to any of her children",
            "Because the womb has no effect",
        ],
        "correct_index": 0,
        "why": "With only X chromosomes to give, nothing about her gamete can change the outcome.",
    },
    {
        "id": "ks4-sex-determination-s08",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A couple have three daughters. State the chance that their next child is a daughter.",
        "options": [
            "Much lower than one half, because the family has already had three daughters in a row",
            "Much higher than one half, since the couple appear to produce daughters more readily",
            "One half",
            "It cannot be estimated once a family has already had three children of the same sex",
        ],
        "correct_index": 2,
        "why": "Each fertilisation is independent, so the previous children make no difference at all.",
    },
    {
        "id": "ks4-sex-determination-s09",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Express the chance of having a son as a percentage and as a ratio.",
        "options": [
            "25 per cent, or one to three",
            "50 per cent, which is the same as a one to one ratio of sons to daughters",
            "75 per cent, or three to one",
            "100 per cent",
        ],
        "correct_index": 1,
        "why": "A half can be written as 50%, as a one in two chance, or as a one to one ratio.",
    },
    {
        "id": "ks4-sex-determination-s10",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the 23rd pair is the only pair whose two chromosomes may look different.",
        "options": [
            "Because the 23rd pair is the only pair that is copied before a body cell divides",
            "Because the chromosomes of the 23rd pair are not inherited from either of the parents",
            "Because it is the last pair",
            "Because in a male one of them is an X and the other is a much smaller Y",
        ],
        "correct_index": 3,
        "why": "All 22 autosome pairs match; only XY is a pair of two differently shaped chromosomes.",
    },
    {
        "id": "ks4-sex-determination-s11",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what happens when an egg is fertilised by a sperm carrying an X chromosome.",
        "options": [
            "The zygote carries no sex chromosomes and so develops without a sex of any kind",
            "The zygote receives a Y chromosome from the mother instead of from the father",
            "The zygote is XX and develops as a girl",
            "Nothing at all happens to the egg cell involved",
        ],
        "correct_index": 2,
        "why": "The egg's X and the sperm's X together give XX, which develops into a female.",
    },
    {
        "id": "ks4-sex-determination-s12",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A Y-bearing sperm fertilises an egg. Predict the sex of the baby and name the gene involved.",
        "options": [
            "The zygote is XY, so the SRY gene on the Y switches on the development of testes",
            "The zygote receives two Y chromosomes, one from each of the two gametes that fused",
            "The zygote develops as a female, because the egg cell is much larger than the sperm",
            "The zygote has 47 chromosomes",
        ],
        "correct_index": 0,
        "why": "An X from the egg and a Y from the sperm give XY, and the Y carries the gene that starts male development.",
    },
    {
        "id": "ks4-sex-determination-s13",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a family with five sons is not evidence against a one to one ratio.",
        "options": [
            "Because five children is a very small sample",
            "Because the ratio of boys to girls does not apply to families of more than four",
            "Because the father of the family must have produced only Y-bearing sperm cells",
            "Because ratios of this kind are not real at all",
        ],
        "correct_index": 0,
        "why": "Five boys in a row has a chance of about one in thirty-two, which happens often across many families.",
    },
    {
        "id": "ks4-sex-determination-s14",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what the 22 pairs of chromosomes other than the sex chromosomes are called.",
        "options": [
            "Gametes, because they are the chromosomes that are passed on to the next generation",
            "Alleles, since each of them carries a different version of the same gene as its partner",
            "Autosomes",
            "Sex cells of the body",
        ],
        "correct_index": 2,
        "why": "The 22 matching pairs are the autosomes; only the 23rd pair carries the sex chromosomes.",
    },
    {
        "id": "ks4-sex-determination-s15",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why roughly equal numbers of boys and girls are born across a whole country.",
        "options": [
            "Because doctors adjust the numbers so that the two sexes come out equal in the end",
            "Because every family in the country has the same number of sons as daughters",
            "Because the ratio is fixed by law",
            "Because half the sperm carry an X and half carry a Y, and fertilisation is random",
        ],
        "correct_index": 3,
        "why": "Over millions of fertilisations the one in two chance averages out to an almost even split.",
    },
    {
        "id": "ks4-sex-determination-s16",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how many chromosomes in a human sperm cell are sex chromosomes.",
        "options": [
            "Twenty-three of them, because every chromosome in a gamete helps to decide the sex",
            "One",
            "Two of them, one X and one Y, so that the sperm can fertilise either kind of egg",
            "None at all",
        ],
        "correct_index": 1,
        "why": "A gamete carries one chromosome from each pair, so it has one sex chromosome out of its 23.",
    },
    {
        "id": "ks4-sex-determination-s17",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the X chromosome carries genes that have nothing to do with sex.",
        "options": [
            "Because the X chromosome is inherited only by daughters and not by sons",
            "Because every gene on the X chromosome is switched off in a male",
            "Because it is a large chromosome full of ordinary genes",
            "Because it is small",
        ],
        "correct_index": 2,
        "why": "Being a sex chromosome does not stop it being an ordinary large chromosome full of other genes.",
    },
    {
        "id": "ks4-sex-determination-s18",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Set out what a woman's body cell contains, counting autosomes and sex chromosomes separately.",
        "options": [
            "Twenty-two matching pairs plus two X chromosomes",
            "Twenty-three single chromosomes with no partners, as in a gamete",
            "Forty-six chromosomes with one X and one Y among them",
            "Ninety-two chromosomes",
        ],
        "correct_index": 0,
        "why": "A female body cell has 22 pairs of autosomes and one pair of X chromosomes.",
    },
    {
        "id": "ks4-sex-determination-s19",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a sperm cannot carry both an X and a Y chromosome.",
        "options": [
            "Because the Y chromosome is destroyed while the sperm cell is being made in the testes",
            "Because meiosis separates the pair, so each sperm receives only one of them",
            "Because a sperm carries none of the chromosomes of the man who produced it",
            "Because they repel each other",
        ],
        "correct_index": 1,
        "why": "The X and the Y are a pair, and meiosis always puts the two members of a pair into different cells.",
    },
    {
        "id": "ks4-sex-determination-s20",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a doctor would look for in a cell sample to tell whether it came from a male.",
        "options": [
            "The total number of chromosomes, which is different in males and in females",
            "The size of the nucleus, which is larger in the body cells of a male than a female",
            "The number of autosomes",
            "Whether the 23rd pair contains a Y chromosome",
        ],
        "correct_index": 3,
        "why": "Males and females have the same 46 chromosomes; only the presence of a Y separates them.",
    },
    {
        "id": "ks4-sex-determination-s21",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the sex of a baby cannot be chosen by the parents naturally.",
        "options": [
            "Because the sex of a baby is decided by conditions in the womb long after fertilisation",
            "Because a mother is able to choose which of her eggs will be fertilised by a sperm",
            "Because both parents carry a Y",
            "Because which sperm reaches the egg first is a matter of chance",
        ],
        "correct_index": 3,
        "why": "Millions of sperm compete, half of each kind, and nothing the parents do changes which one arrives.",
    },
    {
        "id": "ks4-sex-determination-s22",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a father is not responsible for having only daughters.",
        "options": [
            "Because the mother chooses which kind of sperm is allowed to fertilise her egg cell",
            "Because he produces equal numbers of both kinds of sperm, and chance does the rest",
            "Because the sex of a child is decided by the food the mother eats during pregnancy",
            "Because daughters are commoner",
        ],
        "correct_index": 1,
        "why": "His gametes are half X and half Y; which one fertilises the egg is entirely a matter of chance.",
    },
    {
        "id": "ks4-sex-determination-s23",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what would happen to the sex of offspring if all sperm carried an X chromosome.",
        "options": [
            "Every child would be female",
            "Half of the children would still be male, because the mother also supplies a chromosome",
            "Every child would be male, because an X chromosome from the father starts male development",
            "Nothing about the sexes would change at all",
        ],
        "correct_index": 0,
        "why": "An X from the father added to the egg's X would give XX every time.",
    },
    {
        "id": "ks4-sex-determination-s24",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how sex determination in humans differs from sex determination in a crocodile.",
        "options": [
            "In humans the mother decides it and in a crocodile the father decides it instead",
            "In a crocodile it is decided by chromosomes and in a human it is decided by the diet",
            "In humans chromosomes decide it; in a crocodile the nest temperature does",
            "There is no difference",
        ],
        "correct_index": 2,
        "why": "Chromosomal sex determination is fixed at fertilisation; temperature-dependent sex is decided afterwards.",
    },
    {
        "id": "ks4-sex-determination-s25",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how many of the four boxes in a genetic diagram for sex give a female.",
        "options": [
            "All four of them, because the mother supplies an X chromosome in every one of the boxes",
            "Two of them",
            "One of the four boxes, which is why girls are rarer than boys in the population",
            "None of them",
        ],
        "correct_index": 1,
        "why": "Two boxes come out XX and two come out XY, which is the one to one ratio.",
    },
    {
        "id": "ks4-sex-determination-s26",
        "subtopic_slug": "sex-determination",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the sex chromosomes are still called a pair even when they differ.",
        "options": [
            "Because they are exactly the same size and shape as each other in a body cell",
            "Because a pair means any two chromosomes that happen to lie beside one another",
            "Because they carry no genes",
            "Because they separate into different gametes at meiosis",
        ],
        "correct_index": 3,
        "why": "A pair is defined by the two chromosomes behaving as partners in meiosis, not by their looking alike.",
    },
    {
        "id": "ks4-sex-determination-h05",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A country records 512 000 boys and 488 000 girls in one year. Evaluate whether this supports a one to one ratio.",
        "options": [
            "It disproves the ratio completely, because the two numbers are not exactly equal",
            "It cannot be judged without knowing how many families each of the children belonged to",
            "It does support it — the numbers are very close",
            "It shows that boys are very much commoner than girls",
        ],
        "correct_index": 2,
        "why": "A difference of about two per cent in a million births is well within ordinary chance variation.",
    },
    {
        "id": "ks4-sex-determination-h06",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Calculate the chance that a couple's first two children are both boys.",
        "options": [
            "One in four",
            "One half, because each child independently has a one in two chance of being a boy",
            "One in eight, in the same way as the chance of having three boys one after another",
            "It is certain",
        ],
        "correct_index": 0,
        "why": "A half multiplied by a half is a quarter, because the two fertilisations are independent.",
    },
    {
        "id": "ks4-sex-determination-h07",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a gene carried on the Y chromosome can only be passed from father to son.",
        "options": [
            "Because a daughter receives an X from her father and never receives his Y chromosome",
            "Because a mother passes her Y chromosome to her sons but not to her daughters",
            "Because the genes on the Y chromosome are switched off in every one of a daughter's cells",
            "Because daughters have no genes",
        ],
        "correct_index": 0,
        "why": "The father gives a Y to his sons and an X to his daughters, so the Y follows the male line only.",
    },
    {
        "id": "ks4-sex-determination-h08",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a sperm-sorting technique could change the sex ratio of a herd of cattle.",
        "options": [
            "Because sorting the sperm changes the chromosomes that each of the sperm cells carries",
            "Because it changes the number of eggs that each of the cows in the herd produces",
            "Because it changes the proportion of X- and Y-bearing sperm used for fertilisation",
            "Because it makes cows breed faster",
        ],
        "correct_index": 2,
        "why": "The ratio comes from the mix of sperm; change the mix and the expected ratio of calves changes with it.",
    },
    {
        "id": "ks4-sex-determination-h09",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A dairy farmer wants mostly female calves. Explain why sorted sperm is more useful to him than choosing which cows to breed.",
        "options": [
            "Because a cow can be made to produce only female calves by changing what she is fed",
            "Because choosing cows changes the chromosomes that the bull's sperm cells carry",
            "Because cows are much easier to sort than bulls",
            "Because the cow supplies only X chromosomes",
        ],
        "correct_index": 3,
        "why": "The mother cannot influence sex at all, so the only point at which the ratio can be shifted is the sperm.",
    },
    {
        "id": "ks4-sex-determination-h10",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a faulty allele on the X chromosome affects more males than females.",
        "options": [
            "Because a male's cells contain a larger number of X chromosomes than a female's cells do",
            "Because a male has only one X, so he has no second copy to mask a faulty allele",
            "Because the faulty allele is destroyed in the cells of a female before it can be read",
            "Because males have more genes",
        ],
        "correct_index": 1,
        "why": "A female has a second X that can carry a working allele; a male has no backup copy at all.",
    },
    {
        "id": "ks4-sex-determination-h11",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the chromosomes a boy inherits from his mother with those he inherits from his father.",
        "options": [
            "He gets every one of his chromosomes from his father and none at all from his mother",
            "He gets an X from each of his two parents, which is what makes him male at fertilisation",
            "He gets 22 autosomes and an X from his mother, and 22 autosomes and a Y from his father",
            "He gets 46 from each parent",
        ],
        "correct_index": 2,
        "why": "Each parent supplies 23 chromosomes; the mother's sex chromosome is always an X, the father's may be either.",
    },
    {
        "id": "ks4-sex-determination-h12",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that a couple who have had four girls are now due a boy.",
        "options": [
            "It is wrong — the chance is one half again",
            "It is correct, because the ratio of boys to girls has to even out inside every family",
            "It is correct, because the mother's eggs change after she has had four daughters",
            "It is wrong, because girls are commoner than boys",
        ],
        "correct_index": 0,
        "why": "Chance has no memory; the ratio evens out across huge numbers of births, not within one family.",
    },
    {
        "id": "ks4-sex-determination-h13",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the Y chromosome has far fewer genes than the X despite being in the same pair.",
        "options": [
            "Because the genes on the Y chromosome have been moved onto the autosomes over time",
            "Because it is much smaller, so there is far less DNA on it to carry genes",
            "Because a Y chromosome is only present in half of the cells of a male's body",
            "Because it is only used once",
        ],
        "correct_index": 1,
        "why": "Gene number goes with the amount of DNA, and the Y is one of the smallest human chromosomes.",
    },
    {
        "id": "ks4-sex-determination-h14",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why an ultrasound scan can reveal a baby's sex but a genetic diagram cannot.",
        "options": [
            "Because an ultrasound scan changes the sex chromosomes of the baby that is being scanned",
            "Because a genetic diagram is only accurate for characteristics other than a baby's sex",
            "Because scans are newer",
            "A diagram gives the probability for any baby; a scan observes one particular baby",
        ],
        "correct_index": 3,
        "why": "The square predicts proportions across many fertilisations; only observation settles an individual case.",
    },
    {
        "id": "ks4-sex-determination-h15",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "In bees, males develop from unfertilised eggs and females from fertilised ones. Compare this with human sex determination.",
        "options": [
            "Both systems depend entirely on which sex chromosome the sperm cell carried",
            "In bees sex is decided by temperature and in humans it is decided by the mother's gametes",
            "The two systems are the same",
            "In bees it depends on whether fertilisation happened at all",
        ],
        "correct_index": 3,
        "why": "A bee's sex follows from whether an egg was fertilised at all, not from a pair of sex chromosomes.",
    },
    {
        "id": "ks4-sex-determination-h16",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the SRY gene must be switched on early in the development of an embryo.",
        "options": [
            "Because the gene is destroyed by the cells of the embryo after the first few weeks",
            "Because the reproductive organs form early, and the gene directs which ones develop",
            "Because an embryo has no chromosomes at all until it has been developing for some time",
            "Because it works only once",
        ],
        "correct_index": 1,
        "why": "The gene has to act while the tissue that will become the reproductive organs is still unspecialised.",
    },
    {
        "id": "ks4-sex-determination-h17",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why an embryo with XY chromosomes but no working SRY gene may not develop as a male.",
        "options": [
            "Because it is the gene, not the chromosome itself, that starts the testes developing",
            "Because the Y chromosome would be removed from the cells of the embryo as it develops",
            "Because the embryo would develop two X chromosomes in place of the missing gene",
            "Because XY always gives a female",
        ],
        "correct_index": 0,
        "why": "The Y matters because it carries SRY; without a working copy the switch is never thrown.",
    },
    {
        "id": "ks4-sex-determination-h18",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the ratio of boys to girls born is very slightly uneven in most countries.",
        "options": [
            "Because half of the sperm produced by a father carry an X and the other half carry a Y",
            "Because a genetic diagram predicts an uneven ratio of boys to girls at fertilisation",
            "Because chance acts on very large numbers of births",
            "Because records are wrong",
        ],
        "correct_index": 2,
        "why": "A one to one expectation does not mean an exact result, and small survival differences act on top of chance.",
    },
    {
        "id": "ks4-sex-determination-h19",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the sex of a human is settled before any organ has formed.",
        "options": [
            "Because the reproductive organs of an embryo form before any of the other organs do",
            "Because the combination of sex chromosomes is fixed at the moment of fertilisation",
            "Because a doctor is able to decide the sex of an embryo during the first few weeks",
            "Because organs form very late",
        ],
        "correct_index": 1,
        "why": "The zygote is already XX or XY, so the outcome is determined before development begins.",
    },
    {
        "id": "ks4-sex-determination-h20",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student says the Y chromosome makes a person male because it is smaller. Evaluate this.",
        "options": [
            "It is correct, because a smaller chromosome always produces a male in every mammal",
            "It is correct, because the smaller chromosome of a pair carries all the important genes",
            "It is wrong, because the Y is larger",
            "It is wrong — its size is irrelevant, and it is the SRY gene on it that matters",
        ],
        "correct_index": 3,
        "why": "Size is a coincidence; what makes the Y the male-determining chromosome is the gene it carries.",
    },
    {
        "id": "ks4-sex-determination-h21",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why knowing a baby's sex chromosomes does not predict its personality or abilities.",
        "options": [
            "Because the sex chromosomes are not passed on to a baby by either of its parents",
            "Because a baby's sex chromosomes change several times as it grows into an adult",
            "Because personality and ability depend on many genes and on upbringing as well",
            "Because they carry no genes",
        ],
        "correct_index": 2,
        "why": "The 23rd pair settles sex; everything else comes from the rest of the genome and from the environment.",
    },
    {
        "id": "ks4-sex-determination-h22",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a Punnett square for sex looks the same for every couple in the world.",
        "options": [
            "Because every mother is XX and every father is XY, so the gametes are always the same",
            "Because a Punnett square is drawn in the same way for every characteristic there is",
            "Because the sex chromosomes of a couple change to match one another before conception",
            "Because it is a rule",
        ],
        "correct_index": 0,
        "why": "Unlike other characteristics, both parental genotypes are known in advance, so the square never varies.",
    },
    {
        "id": "ks4-sex-determination-h23",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare what a genetic diagram predicts with what a hospital's birth records actually show.",
        "options": [
            "The diagram gives an expected one to one ratio; the records show numbers close to it but not exact",
            "The diagram and the records agree exactly, because chance plays no part in fertilisation",
            "The records show a three to one ratio, which is what the diagram predicts for sex",
            "They cannot be compared",
        ],
        "correct_index": 0,
        "why": "A prediction is about proportions in the long run; real counts scatter around it.",
    },
    {
        "id": "ks4-sex-determination-h24",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a species in which the mother decided sex would show the same overall ratio.",
        "options": [
            "Because a mother is able to control how many sons and daughters she produces in total",
            "Because one parent still makes two kinds of gamete in equal numbers, and pairing is random",
            "Because the ratio depends only on the number of eggs produced during a breeding season",
            "Because ratios are fixed",
        ],
        "correct_index": 1,
        "why": "In birds the female is the one with two different sex chromosomes, and the expected ratio is still one to one.",
    },
    {
        "id": "ks4-sex-determination-h25",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why sorting sperm before fertilisation raises ethical questions that a Punnett square does not.",
        "options": [
            "Because a Punnett square is able to change the sex of a baby once it has been conceived",
            "Because sorting sperm changes the chromosomes that the sperm cells are carrying",
            "Because it lets people choose a child's sex, rather than only predicting the chances",
            "Because squares are older",
        ],
        "correct_index": 2,
        "why": "Predicting a probability changes nothing; acting to select one outcome is a decision people disagree about.",
    },
    {
        "id": "ks4-sex-determination-h26",
        "subtopic_slug": "sex-determination",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the autosomes are numbered from 1 to 22 but the sex chromosomes are given letters.",
        "options": [
            "Because the sex chromosomes were discovered long after all of the autosomes had been numbered",
            "Because a letter can be written more quickly than a number when drawing out a diagram",
            "Because they are larger",
            "Because the two sex chromosomes differ from each other, so numbering them as a pair would mislead",
        ],
        "correct_index": 3,
        "why": "The numbered pairs are matching partners; X and Y are not the same chromosome, so they are named separately.",
    },
]
