"""Biology · Inheritance, Variation and Evolution — the MRB-338 expansion,
subtopic `genetic-inheritance`.

The baseline twelve are almost all crosses already worked out in peas, mice
and guinea pigs, plus one line on dominance not meaning commonness. This
file supplies the VOCABULARY and the METHOD that those crosses assume and
that the baseline never states: gamete, zygote, genotype, phenotype,
homozygous, heterozygous, dominant and recessive as defined terms; the
capital-and-lowercase lettering convention; how a Punnett square is built
and what goes on each edge; probability written as a fraction, a percentage
and a ratio; the test cross for finding an unknown genotype; working
backwards from offspring to parents; why a predicted ratio is approximate;
independence between one offspring and the next; and the fact that most
characteristics are controlled by several genes rather than one.

⚠️ `understanding-genetics` is the neighbouring leaf and owns Mendel — his
method, his peas and the history. Crosses here use other organisms on
purpose. `inherited-disorders` owns cystic fibrosis, polydactyly and
carriers; `sex-determination` owns X and Y. None of those is re-asked here.
"""

TOPIC = "inheritance"
SUBJECT = "biology"

QUESTIONS = [
    {
        "id": "ks4-genetic-inheritance-e05",
        "subtopic_slug": "genetic-inheritance",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give the meaning of the word genotype.",
        "options": [
            "The combination of alleles that the organism carries for a characteristic",
            "The way the organism looks",
            "The number of its offspring",
            "Its species name",
        ],
        "correct_index": 0,
        "why": "The genotype is the pair of alleles an organism carries; the phenotype is what those alleles produce.",
    },
    {
        "id": "ks4-genetic-inheritance-e06",
        "subtopic_slug": "genetic-inheritance",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what a biologist means by an organism's phenotype.",
        "options": [
            "The two alleles it carries for a characteristic, written as a pair of letters",
            "The gametes it produces during its lifetime",
            "The characteristics it actually shows",
            "Its chromosomes",
        ],
        "correct_index": 2,
        "why": "The phenotype is the characteristic you can observe, produced by the genotype together with the environment.",
    },
    {
        "id": "ks4-genetic-inheritance-e07",
        "subtopic_slug": "genetic-inheritance",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what the word homozygous means.",
        "options": [
            "That the organism carries one allele of each kind for the characteristic concerned",
            "That it has no alleles",
            "That it has four alleles",
            "That both alleles for the characteristic are the same",
        ],
        "correct_index": 3,
        "why": "Homozygous means the two alleles match — either both dominant or both recessive.",
    },
    {
        "id": "ks4-genetic-inheritance-e08",
        "subtopic_slug": "genetic-inheritance",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what the word heterozygous means.",
        "options": [
            "That the organism carries two alleles that are exactly the same as one another",
            "The two alleles differ",
            "That it carries three alleles",
            "That it carries no dominant allele",
        ],
        "correct_index": 1,
        "why": "Heterozygous means the two alleles are different, so one is dominant over the other.",
    },
    {
        "id": "ks4-genetic-inheritance-e09",
        "subtopic_slug": "genetic-inheritance",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how many alleles for one characteristic a gamete carries.",
        "options": [
            "Two",
            "Four",
            "One, because the pair separated when the gamete was made",
            "None at all",
        ],
        "correct_index": 2,
        "why": "Gametes are made by meiosis, which puts one allele of each pair into each gamete.",
    },
    {
        "id": "ks4-genetic-inheritance-e10",
        "subtopic_slug": "genetic-inheritance",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State why a capital letter is used for one allele and a small letter for the other.",
        "options": [
            "The capital letter shows the dominant allele",
            "Because the capital letter shows which allele came from the father of the offspring",
            "Because capital letters are used for animals and small letters for plants",
            "It is random",
        ],
        "correct_index": 0,
        "why": "By convention the dominant allele takes the capital letter and the recessive one the same letter in lower case.",
    },
    {
        "id": "ks4-genetic-inheritance-e11",
        "subtopic_slug": "genetic-inheritance",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the cell formed when two gametes fuse together.",
        "options": [
            "A body cell, which then goes on to divide by meiosis to form the embryo",
            "A zygote",
            "A clone",
            "Sperm",
        ],
        "correct_index": 1,
        "why": "Fertilisation joins two gametes to give a zygote, which then divides by mitosis to form an embryo.",
    },
    {
        "id": "ks4-genetic-inheritance-e12",
        "subtopic_slug": "genetic-inheritance",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what is meant by a recessive allele.",
        "options": [
            "An allele that shows in the phenotype whenever it is present in the organism",
            "An allele that is passed on by the mother rather than by the father",
            "An allele that is always the rarer of the two in any population",
            "An allele that only shows when two copies are present",
        ],
        "correct_index": 3,
        "why": "A recessive allele is masked by a dominant one, so it shows only in a homozygous recessive organism.",
    },
    {
        "id": "ks4-genetic-inheritance-s05",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "In rabbits, short fur (S) is dominant to long fur (s). Describe the genotypes that would give a short-furred rabbit.",
        "options": [
            "ss only",
            "Ss but not SS",
            "SS and nothing else",
            "Either SS or Ss, because one dominant allele is enough to give short fur",
        ],
        "correct_index": 3,
        "why": "A dominant characteristic is shown by both the homozygous dominant and the heterozygous genotype.",
    },
    {
        "id": "ks4-genetic-inheritance-s06",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what a breeder writes along the top edge and down the side edge of a Punnett square.",
        "options": [
            "The full genotype of each parent is written along both edges of the square in full",
            "The gametes each parent can make",
            "The phenotypes of the offspring that are expected from the cross once it has been carried out",
            "The names of the two parents",
        ],
        "correct_index": 1,
        "why": "One parent's possible gametes go along the top and the other's down the side; the boxes then give the offspring genotypes.",
    },
    {
        "id": "ks4-genetic-inheritance-s07",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "In tomatoes, red fruit (R) is dominant to yellow fruit (r). Predict the offspring of a cross between an RR plant and an Rr plant.",
        "options": [
            "All of them red, because neither parent can pass on more than one r allele",
            "One tomato plant in every four would be expected to carry yellow fruit after this cross",
            "Half red and half yellow",
            "All yellow",
        ],
        "correct_index": 0,
        "why": "The RR parent can only give R, so every offspring has at least one R allele and is red.",
    },
    {
        "id": "ks4-genetic-inheritance-s08",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the two kinds of gamete a heterozygous organism can produce for one characteristic.",
        "options": [
            "Gametes carrying both of its alleles together, in equal numbers each time it reproduces",
            "Gametes that carry no allele for that characteristic at all",
            "One with each allele",
            "Gametes that all carry the dominant allele of the pair",
        ],
        "correct_index": 2,
        "why": "The pair separates in meiosis, so half the gametes carry one allele and half carry the other.",
    },
    {
        "id": "ks4-genetic-inheritance-s09",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a breeder cannot tell by looking whether a short-furred rabbit is homozygous or heterozygous.",
        "options": [
            "Because fur length is not an inherited characteristic",
            "Because a single dominant allele produces exactly the same appearance as two dominant alleles do",
            "Because rabbits have no alleles for fur length",
            "Because the fur changes with the seasons",
        ],
        "correct_index": 1,
        "why": "Dominance means one copy of the allele is enough, so SS and Ss look identical.",
    },
    {
        "id": "ks4-genetic-inheritance-s10",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe the cross a breeder would carry out to find whether an animal showing a dominant characteristic is heterozygous.",
        "options": [
            "Cross it with another animal that shows exactly the same dominant characteristic as it does",
            "Cross it with an animal that has twice as many chromosomes as it carries itself",
            "Cross it with itself",
            "Cross it with a homozygous recessive animal",
        ],
        "correct_index": 3,
        "why": "A recessive partner can only give recessive alleles, so any recessive offspring proves the tested animal is heterozygous.",
    },
    {
        "id": "ks4-genetic-inheritance-s11",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "In cattle, polled (hornless, P) is dominant to horned (p). Predict the offspring of a Pp bull crossed with a pp cow.",
        "options": [
            "All of the calves would be expected to be hornless, whichever allele the bull happens to pass on",
            "All horned",
            "About half hornless and half horned",
            "Three hornless to one horned",
        ],
        "correct_index": 2,
        "why": "Half the bull's gametes carry P and half carry p, while the cow gives only p, so the ratio is one to one.",
    },
    {
        "id": "ks4-genetic-inheritance-s12",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a probability of one quarter can also be written as.",
        "options": [
            "25%, or a one in four chance",
            "A one in two chance, which can equally well be written as fifty per cent of the time",
            "Seventy-five per cent of the offspring produced",
            "Four times out of every ten offspring",
        ],
        "correct_index": 0,
        "why": "A quarter, 25% and one in four are three ways of writing the same probability.",
    },
    {
        "id": "ks4-genetic-inheritance-s13",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why two parents showing the same characteristic can have an offspring that does not show it.",
        "options": [
            "Because both parents may be heterozygous, so each can pass on the hidden recessive allele",
            "Because the offspring inherits nothing from either parent",
            "Because characteristics are set by the environment",
            "Because the offspring has a new pair of chromosomes",
        ],
        "correct_index": 0,
        "why": "Two heterozygotes can both pass on the recessive allele, giving a homozygous recessive offspring.",
    },
    {
        "id": "ks4-genetic-inheritance-s14",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the genotype of a budgerigar that is homozygous dominant for a gene with alleles G and g.",
        "options": [
            "Gg, because a homozygous dominant bird carries one allele of each of the two possible kinds",
            "gg, the pairing that produces the recessive form of this characteristic in the bird",
            "GG, two dominant alleles",
            "G only",
        ],
        "correct_index": 2,
        "why": "Homozygous dominant means two copies of the dominant allele, written GG.",
    },
    {
        "id": "ks4-genetic-inheritance-s15",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a predicted ratio of three to one is rarely obtained exactly in a real cross.",
        "options": [
            "Because the alleles change during fertilisation and no longer match the prediction that was made",
            "Because ratios apply only to plants and never to animals",
            "Because the dominant allele becomes recessive over time",
            "Because which gamete fuses with which is a matter of chance in every fertilisation",
        ],
        "correct_index": 3,
        "why": "Fertilisation is random, so real numbers scatter around the predicted ratio, especially with small numbers of offspring.",
    },
    {
        "id": "ks4-genetic-inheritance-s16",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State where in a cell the two alleles of one gene are found.",
        "options": [
            "In two different cells of the body, one allele in each of them, so that they never meet",
            "One on each chromosome of a pair",
            "Both on the same chromosome, next to one another",
            "In the cytoplasm, outside the nucleus of the cell",
        ],
        "correct_index": 1,
        "why": "The two chromosomes of a pair carry the same genes at the same positions, so one allele sits on each.",
    },
    {
        "id": "ks4-genetic-inheritance-s17",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "In pea pods, green (G) is dominant to yellow (g). A grower crosses two Gg plants and raises 200 pods.",
        "options": [
            "About 100 yellow pods",
            "About 200 yellow",
            "About 50 of the pods would be expected to be yellow, since a quarter of the offspring are gg",
            "None yellow",
        ],
        "correct_index": 2,
        "why": "A Gg by Gg cross gives one quarter gg, and one quarter of 200 is 50.",
    },
    {
        "id": "ks4-genetic-inheritance-s18",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what a genetic diagram is used for.",
        "options": [
            "To predict the possible genotypes of offspring from the parents' genotypes",
            "To show all of the genes that an organism carries on each one of its chromosomes in turn",
            "To record which characteristics an organism has developed from its environment",
            "To count chromosomes",
        ],
        "correct_index": 0,
        "why": "A genetic diagram sets out the parents' gametes and combines them to show the possible offspring and their chances.",
    },
    {
        "id": "ks4-genetic-inheritance-s19",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why most human characteristics cannot be predicted from a simple genetic diagram.",
        "options": [
            "Because human gametes carry both alleles of every pair instead of separating them properly",
            "Because most of them are controlled by several genes working together",
            "Because humans have no dominant allele",
            "Because a diagram only works for plants",
        ],
        "correct_index": 1,
        "why": "Characteristics such as height and skin colour are controlled by many genes, so they vary continuously rather than falling into groups.",
    },
    {
        "id": "ks4-genetic-inheritance-s20",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what proportion of its alleles an offspring receives from each of its parents.",
        "options": [
            "All of them come from the mother, since the egg cell is very much larger than a sperm cell",
            "Three quarters from the mother and one quarter from the father in every case",
            "Two thirds from the father",
            "Half from each",
        ],
        "correct_index": 3,
        "why": "One gamete comes from each parent, so each supplies one allele of every pair.",
    },
    {
        "id": "ks4-genetic-inheritance-s21",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "In horses, chestnut coat colour is recessive to bay. A chestnut foal is born to two bay parents. Deduce the genotypes of the parents.",
        "options": [
            "Both homozygous bay",
            "Both homozygous chestnut",
            "One of each kind",
            "Both heterozygous, since each must have passed on a chestnut allele to produce a chestnut foal",
        ],
        "correct_index": 3,
        "why": "A chestnut foal is homozygous recessive, so it received one chestnut allele from each bay parent.",
    },
    {
        "id": "ks4-genetic-inheritance-s22",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the phenotype of an organism is not decided by its genotype alone.",
        "options": [
            "Because an organism's genotype changes several times over the course of its lifetime",
            "Because conditions such as diet, light and temperature also affect how it develops",
            "Because the genotype is only formed after the organism has finished growing completely, late in life",
            "Because alleles have no effect",
        ],
        "correct_index": 1,
        "why": "The environment acts on the characteristics the alleles specify, so genotype and surroundings together give the phenotype.",
    },
    {
        "id": "ks4-genetic-inheritance-s23",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the genotypes of the offspring when a homozygous dominant parent is crossed with a homozygous recessive one.",
        "options": [
            "All of them heterozygous",
            "Half of them homozygous dominant and half of them homozygous recessive, in equal numbers",
            "All recessive",
            "All homozygous dominant",
        ],
        "correct_index": 0,
        "why": "One parent can give only the dominant allele and the other only the recessive, so every offspring carries one of each.",
    },
    {
        "id": "ks4-genetic-inheritance-s24",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what is meant by a dominant allele.",
        "options": [
            "An allele that is passed on to a larger number of offspring than its partner allele ever is",
            "An allele that is present in a greater number of the individuals in the population",
            "An allele that shows even when only one copy is present",
            "An allele found on the larger chromosome of a matching pair of chromosomes",
        ],
        "correct_index": 2,
        "why": "One copy of a dominant allele is enough to give the characteristic, whatever the other allele is.",
    },
    {
        "id": "ks4-genetic-inheritance-s25",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a gardener grows a large number of seedlings before judging the results of a cross.",
        "options": [
            "Because seedlings grown in small numbers cannot inherit alleles from either of their parents",
            "Because a large sample reduces the effect of chance, so the observed proportions come closer to the predicted ones",
            "Because the alleles work only in a crowded seed tray",
            "Because small numbers change the ratio",
        ],
        "correct_index": 1,
        "why": "Each fertilisation is a chance event, so the larger the sample the closer the counts come to the expected proportions.",
    },
    {
        "id": "ks4-genetic-inheritance-s26",
        "subtopic_slug": "genetic-inheritance",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why alleles are described as alternative versions of the same gene.",
        "options": [
            "Because they sit on completely different chromosomes and control entirely separate characteristics of the organism",
            "Because one of them is made of DNA while the other one of them is made of protein instead",
            "Because an allele is a whole chromosome",
            "Because they sit at the same position on a chromosome pair but differ in base sequence",
        ],
        "correct_index": 3,
        "why": "Alleles are the same gene with slightly different base sequences, found at the same place on each chromosome of a pair.",
    },
    {
        "id": "ks4-genetic-inheritance-h05",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A grower crosses two heterozygous red-fruited tomato plants and raises 400 seedlings. Calculate how many are expected to carry at least one recessive allele.",
        "options": [
            "All 400 of them, because every one of the offspring of this cross inherits one allele from each parent",
            "100",
            "300, because three quarters of the offspring are either heterozygous or homozygous recessive",
            "None of them",
        ],
        "correct_index": 2,
        "why": "The genotypes come out 1 RR : 2 Rr : 1 rr, so three quarters of 400, which is 300, carry at least one r.",
    },
    {
        "id": "ks4-genetic-inheritance-h06",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A breeder crosses a heterozygous animal with a homozygous recessive one four times and gets four offspring showing the dominant form. Evaluate the conclusion that the animal is homozygous dominant.",
        "options": [
            "It is unsafe — four offspring is a small sample, and this can happen by chance",
            "It is safe, because a heterozygous parent can never produce four offspring of the same kind in a row",
            "It is safe, because four offspring is more than enough to settle the genotype of a parent quite beyond any doubt",
            "It is wrong, because a homozygous dominant parent could not produce these offspring at all",
        ],
        "correct_index": 0,
        "why": "With a heterozygous parent each offspring has a one in two chance of showing the dominant form, so four in a row happens about one time in sixteen.",
    },
    {
        "id": "ks4-genetic-inheritance-h07",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare what a genotype tells a breeder with what a phenotype tells them.",
        "options": [
            "The genotype names the alleles, so it predicts what can be passed on; the phenotype shows only what the animal looks like now",
            "The phenotype names the alleles and the genotype shows the appearance",
            "Both give exactly the same information",
            "Neither is of any use to a breeder",
        ],
        "correct_index": 0,
        "why": "Two animals with the same appearance can carry different alleles, so only the genotype predicts what the offspring may be.",
    },
    {
        "id": "ks4-genetic-inheritance-h08",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student says a cross giving three tall to one short proves that the tall allele is stronger. Evaluate this.",
        "options": [
            "It is correct, because a dominant allele is physically stronger than the recessive one it masks",
            "It is correct, because a ratio of three to one can only ever arise from a difference in strength between them",
            "It is wrong — dominance is about which allele is expressed, not about strength",
            "It is wrong, because the ratio should have been one to one",
        ],
        "correct_index": 2,
        "why": "Dominance describes which allele determines the phenotype in a heterozygote; no allele is stronger than another.",
    },
    {
        "id": "ks4-genetic-inheritance-h09",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A couple have three children, all with brown eyes. Predict the chance that a fourth child has blue eyes, given both parents are heterozygous.",
        "options": [
            "Zero, because the three brown-eyed children have already used up the chance for this family",
            "One in two",
            "It is certain",
            "One in four, because each fertilisation is independent of the ones before it",
        ],
        "correct_index": 3,
        "why": "Each fertilisation is a separate chance event, so previous children do not change the probability for the next one.",
    },
    {
        "id": "ks4-genetic-inheritance-h10",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "In mice, a coat gene has alleles C and c. Deduce the genotypes of two parents whose offspring are about half CC and half Cc.",
        "options": [
            "Because one parent is Cc and the other one is cc, so the cross cannot give any CC offspring at all",
            "CC and Cc",
            "Both parents must be cc, so that every offspring receives a recessive allele from each",
            "Both parents must be heterozygous, giving one quarter CC and one quarter cc offspring",
        ],
        "correct_index": 1,
        "why": "No offspring is cc, so one parent gives only C; the other gives C or c, producing half CC and half Cc.",
    },
    {
        "id": "ks4-genetic-inheritance-h11",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a recessive allele can remain in a population for many generations without being seen.",
        "options": [
            "Because it disappears and is remade each generation",
            "Because it changes into a dominant allele",
            "Because heterozygous individuals carry it and pass it on while showing the dominant characteristic themselves",
            "Because it is stored outside the nucleus",
        ],
        "correct_index": 2,
        "why": "Carriers show the dominant phenotype, so the recessive allele is hidden until two carriers have offspring together.",
    },
    {
        "id": "ks4-genetic-inheritance-h12",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a test cross uses a homozygous recessive partner rather than a heterozygous one.",
        "options": [
            "It can pass on only the recessive allele",
            "Because a heterozygous partner would not be able to produce gametes of any kind for the cross",
            "Because the recessive partner passes on twice as many alleles to each offspring",
            "Because it produces more offspring",
        ],
        "correct_index": 0,
        "why": "Because the partner contributes only recessive alleles, the offspring's appearance reveals the unknown parent's second allele directly.",
    },
    {
        "id": "ks4-genetic-inheritance-h13",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A cross between two heterozygous plants gives 82 dominant and 18 recessive offspring. Evaluate how well this fits a three to one prediction.",
        "options": [
            "It does not fit in any way, because the two numbers ought to have been exactly 75 and exactly 25",
            "It fits reasonably well — 75 and 25 were expected, and chance explains a gap this size",
            "It fits perfectly and exactly",
            "It shows the plants were not heterozygous at all",
        ],
        "correct_index": 1,
        "why": "The expected split is 75 to 25; a result of 82 to 18 in a sample of 100 is well within ordinary chance variation.",
    },
    {
        "id": "ks4-genetic-inheritance-h14",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a dominant characteristic can become rarer in a population over time.",
        "options": [
            "Because a dominant allele will turn into a recessive one after it has been passed on several times",
            "Because dominant alleles are lost from the gametes as an organism gets older",
            "Because dominance is gradually lost over the generations",
            "Because those that carry it may have fewer offspring",
        ],
        "correct_index": 3,
        "why": "How common an allele is depends on how successfully its carriers reproduce, not on whether it is dominant.",
    },
    {
        "id": "ks4-genetic-inheritance-h15",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two pea plants are crossed and every one of the 60 offspring shows the dominant characteristic. Suggest what this indicates.",
        "options": [
            "That both parents were recessive",
            "That the characteristic is not inherited",
            "That the offspring are clones",
            "That at least one parent was almost certainly homozygous dominant, since 60 offspring with no recessive is very unlikely otherwise",
        ],
        "correct_index": 3,
        "why": "Two heterozygotes would be expected to give about 15 recessive offspring in 60, so seeing none points to a homozygous dominant parent.",
    },
    {
        "id": "ks4-genetic-inheritance-h16",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why breeders keep written records of the genotypes of their animals rather than relying on appearance.",
        "options": [
            "Because the appearance of an animal changes entirely every time it produces a litter of offspring of its own",
            "Because appearance hides whether a recessive allele is being carried in the herd",
            "Because the genotype of an animal can be read directly from the colour of its coat and its eyes",
            "Because genotypes are easier to see than phenotypes",
        ],
        "correct_index": 1,
        "why": "A heterozygote looks identical to a homozygous dominant animal, so only records reveal which recessive alleles are in the herd.",
    },
    {
        "id": "ks4-genetic-inheritance-h17",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the offspring expected from a heterozygous by heterozygous cross with those from a heterozygous by homozygous recessive cross.",
        "options": [
            "Three quarters show the dominant form in the first cross, but only half do in the second",
            "The first cross gives every offspring showing the dominant form, while the second gives every offspring showing the recessive form instead",
            "Both crosses give the same three to one ratio",
            "Neither cross gives any recessive offspring",
        ],
        "correct_index": 0,
        "why": "Heterozygous by heterozygous gives 3:1; heterozygous by homozygous recessive gives 1:1.",
    },
    {
        "id": "ks4-genetic-inheritance-h18",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A farmer wants every calf from a herd to be hornless, where hornless is dominant. Suggest how this can be guaranteed.",
        "options": [
            "By using a bull that is heterozygous for the hornless allele with every cow in the herd",
            "By removing the horns of the calves as soon as they are born on the farm",
            "Use a homozygous hornless bull",
            "By breeding only from the cows that have the smallest horns in the whole herd",
        ],
        "correct_index": 2,
        "why": "A homozygous dominant bull can pass on only the hornless allele, so every calf inherits at least one and is hornless.",
    },
    {
        "id": "ks4-genetic-inheritance-h19",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the two alleles an organism carries do not affect one another's base sequence.",
        "options": [
            "Because one of them is switched off permanently as soon as fertilisation takes place",
            "Because they sit on separate chromosomes and are copied separately, so each is passed on unchanged",
            "Because alleles have no base sequence",
            "Because the dominant allele destroys the recessive one",
        ],
        "correct_index": 1,
        "why": "Dominance affects which protein shows in the phenotype; the recessive allele itself is copied and passed on intact.",
    },
    {
        "id": "ks4-genetic-inheritance-h20",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a genetic diagram predicts proportions rather than the exact offspring that will be born.",
        "options": [
            "Because the diagram is drawn before the parents have produced any of the gametes needed for the cross",
            "Because a diagram can only be used for characteristics controlled by more than one gene",
            "Because the alleles are written as letters and not as DNA",
            "Because it shows how likely each combination is, not which one will happen",
        ],
        "correct_index": 3,
        "why": "The square lists every equally likely combination; which one a particular fertilisation produces is down to chance.",
    },
    {
        "id": "ks4-genetic-inheritance-h21",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "In a plant, white flowers are recessive to purple. A purple plant crossed with a white one gives 30 purple and 28 white. Deduce the purple parent's genotype.",
        "options": [
            "Homozygous dominant, since it produced a large number of purple offspring in the cross",
            "It cannot be decided from these results",
            "Heterozygous, because about half the offspring are white",
            "Homozygous recessive",
        ],
        "correct_index": 2,
        "why": "A roughly one to one split with a white partner shows the purple parent passed on a white allele half the time.",
    },
    {
        "id": "ks4-genetic-inheritance-h22",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a characteristic controlled by one gene gives clear groups while one controlled by many genes does not.",
        "options": [
            "One gene gives a few genotypes; many genes give a huge number of combinations",
            "Because a characteristic controlled by many genes cannot be inherited by the offspring at any point",
            "Because one gene gives a continuous range while many genes give distinct groups",
            "Because genes controlled in groups are switched off in the gametes before fertilisation",
        ],
        "correct_index": 0,
        "why": "Three genotypes give two or three visible groups; dozens of combinations blur into a continuous range.",
    },
    {
        "id": "ks4-genetic-inheritance-h23",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A rabbit breeder wants to remove a recessive allele from a herd completely. Explain why this is difficult.",
        "options": [
            "Heterozygous rabbits look exactly like homozygous dominant ones, so carriers cannot be picked out by eye and keep passing the allele on",
            "Because a recessive allele returns to the herd by itself each generation",
            "Because removing one allele removes the whole gene",
            "Because rabbits cannot be bred selectively",
        ],
        "correct_index": 0,
        "why": "Only the homozygous recessive animals can be identified by appearance; carriers are invisible and continue to spread the allele.",
    },
    {
        "id": "ks4-genetic-inheritance-h24",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the same pair of parents can produce offspring with several different genotypes.",
        "options": [
            "Because the parents' own genotypes change between one offspring and the next",
            "Because each gamete carries one of the two alleles, and which gametes meet is random",
            "Because the offspring produce new alleles that neither of their two parents ever carried at all",
            "Because a genotype is decided by the conditions that the offspring grows up in rather than by its parents",
        ],
        "correct_index": 1,
        "why": "A heterozygous parent makes two kinds of gamete, and random fertilisation combines them in different ways each time.",
    },
    {
        "id": "ks4-genetic-inheritance-h25",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why knowing that a characteristic is recessive helps a breeder predict how often it will appear.",
        "options": [
            "Because a recessive characteristic appears in every generation without ever once skipping one of them",
            "Because a recessive characteristic can be produced by one parent alone",
            "Because it appears only in offspring that receive the allele from both parents",
            "Because recessive characteristics ignore which parents are chosen",
        ],
        "correct_index": 2,
        "why": "Only the homozygous recessive genotype shows it, and the Punnett square gives exactly what fraction of offspring that is.",
    },
    {
        "id": "ks4-genetic-inheritance-h26",
        "subtopic_slug": "genetic-inheritance",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student writes the genotype of an organism as T only, using a single letter. Explain the error.",
        "options": [
            "A single letter would describe a gamete rather than a body cell, because each gamete carries only one allele of the pair",
            "The letter should have been written as a small letter rather than as a capital letter in this case",
            "The genotype should have been written using the name of the characteristic instead of using any letter",
            "A body cell carries two alleles, so the genotype needs two letters",
        ],
        "correct_index": 3,
        "why": "Body cells are diploid, so a genotype is always written as a pair — TT, Tt or tt.",
    },
]
