"""Biology · Inheritance, Variation and Evolution — the MRB-338 expansion,
subtopic `dna-genome`.

The baseline twelve cover where chromosomes sit, 23 pairs, a gene coding for
a protein, the 20 000 figure, one base-pairing calculation, forensic
identification and one line on alleles. This file takes the GENOME itself as
its ground, which the baseline barely touches: the definition of a genome
against the definition of a gene, the chromosome–gene–base hierarchy, the
3 billion base pairs, the Human Genome Project as an international
collaboration and the 2003 publication, the three specification uses
(searching for genes linked to disease, understanding and treating inherited
disorders, tracing past human migration), why open publication mattered, why
genome size is not a measure of complexity, why two body cells of one person
carry the same genome while looking different, what "expressed" means, cost
and speed of sequencing, genome data and privacy, and the limits of what a
sequence on its own can predict.

⚠️ `dna-structure` is the neighbouring leaf and owns the MOLECULE — the
nucleotide, base pairing, the triplet code, transcription and translation,
and the three kinds of mutation. Nothing here re-asks any of that. The
Mendel history belongs to `understanding-genetics`, and genotype, phenotype
and Punnett squares belong to `genetic-inheritance`.
"""

TOPIC = "inheritance"
SUBJECT = "biology"

QUESTIONS = [
    {
        "id": "ks4-dna-genome-e05",
        "subtopic_slug": "dna-genome",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what is meant by the genome of an organism.",
        "options": [
            "The entire genetic material of that organism",
            "One chromosome",
            "A single gene",
            "The proteins it makes",
        ],
        "correct_index": 0,
        "why": "The genome is all of an organism's genetic material — every chromosome, every gene and the DNA between them.",
    },
    {
        "id": "ks4-dna-genome-e06",
        "subtopic_slug": "dna-genome",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a gene is.",
        "options": [
            "A whole chromosome, made of tightly coiled DNA and stored in the nucleus",
            "A protein used by the body for growth and repair of tissue",
            "A small section of DNA that codes for a protein",
            "A type of cell",
        ],
        "correct_index": 2,
        "why": "A gene is a short length of DNA coding for a particular sequence of amino acids, and so for one protein.",
    },
    {
        "id": "ks4-dna-genome-e07",
        "subtopic_slug": "dna-genome",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State approximately how many base pairs make up the human genome.",
        "options": [
            "About 20 000, which is also the number of genes it contains",
            "About 46",
            "About 500",
            "About 3 billion",
        ],
        "correct_index": 3,
        "why": "The human genome is about 3 billion base pairs long, although only about 20 000 stretches of it are protein-coding genes.",
    },
    {
        "id": "ks4-dna-genome-e08",
        "subtopic_slug": "dna-genome",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the project that worked out the order of all the bases in human DNA.",
        "options": [
            "The Manhattan Project, an international effort completed in the 1940s",
            "The Human Genome Project",
            "The Mendel Inheritance Study",
            "The Origin of Species Survey of 1859",
        ],
        "correct_index": 1,
        "why": "The Human Genome Project sequenced the whole human genome, and its results were published in 2003.",
    },
    {
        "id": "ks4-dna-genome-e09",
        "subtopic_slug": "dna-genome",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give one use scientists make of knowing the human genome.",
        "options": [
            "Curing every disease",
            "Making new elements",
            "Searching for genes that are linked to particular diseases",
            "Changing a person's blood group",
        ],
        "correct_index": 2,
        "why": "The search for genes linked to different types of disease is one of the three main uses named by the specification.",
    },
    {
        "id": "ks4-dna-genome-e10",
        "subtopic_slug": "dna-genome",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State where in a chromosome a gene is found.",
        "options": [
            "Along the DNA molecule",
            "Floating freely in the cytoplasm outside the nucleus",
            "Attached to the outside of the cell membrane",
            "In the vacuole",
        ],
        "correct_index": 0,
        "why": "A chromosome is one long DNA molecule, and each gene is a section of that molecule.",
    },
    {
        "id": "ks4-dna-genome-e11",
        "subtopic_slug": "dna-genome",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how many copies of each gene a human body cell normally carries.",
        "options": [
            "One copy, kept in the nucleus where it is protected from damage",
            "Two copies, one on each chromosome of a pair",
            "Twenty copies",
            "None at all",
        ],
        "correct_index": 1,
        "why": "Chromosomes come in pairs, so a body cell carries two copies of each gene — one inherited from each parent.",
    },
    {
        "id": "ks4-dna-genome-e12",
        "subtopic_slug": "dna-genome",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State approximately what proportion of their DNA any two unrelated people share.",
        "options": [
            "About 50%, which is why brothers and sisters look alike in some ways",
            "About 25% of it",
            "About 75%",
            "Over 99%",
        ],
        "correct_index": 3,
        "why": "Human genomes are more than 99% identical; the small remaining difference accounts for all our inherited variation.",
    },
    {
        "id": "ks4-dna-genome-s05",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why knowing the human genome helps in the study of inherited disorders.",
        "options": [
            "It allows any disorder to be cured immediately",
            "It shows how many chromosomes a person has",
            "It changes the alleles a person carries",
            "The faulty alleles that cause a disorder can be located, and their effects on the body studied",
        ],
        "correct_index": 3,
        "why": "Understanding and treating inherited disorders is one of the three uses of the genome named by the specification.",
    },
    {
        "id": "ks4-dna-genome-s06",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain how comparing genomes helps scientists trace the migrations of people in the past.",
        "options": [
            "Because DNA slowly turns into a different substance as people travel across the world and back",
            "Populations that separated long ago have built up more differences in their DNA",
            "Because the genome records every place a person has visited during their lifetime",
            "Because migration changes the number of genes",
        ],
        "correct_index": 1,
        "why": "Mutations accumulate over time, so the more two populations' genomes differ, the longer ago their ancestors separated.",
    },
    {
        "id": "ks4-dna-genome-s07",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how a chromosome, a gene and a DNA base are related in size order.",
        "options": [
            "A chromosome is a long DNA molecule, a gene is a section of it, and a base is one unit of the DNA",
            "A base contains several genes, and a number of these bases together make up one chromosome in the cell nucleus",
            "A gene contains several chromosomes",
            "All three are the same size",
        ],
        "correct_index": 0,
        "why": "Largest to smallest: the chromosome, then a gene within it, then a single base of the DNA.",
    },
    {
        "id": "ks4-dna-genome-s08",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what is meant by an allele.",
        "options": [
            "A chromosome that has been copied twice and then stored in the nucleus of the cell",
            "A protein made from the instructions carried by one gene",
            "A version of a gene",
            "A gamete produced in the ovary or the testis",
        ],
        "correct_index": 2,
        "why": "Alleles are the different versions a gene can take at the same position on a chromosome.",
    },
    {
        "id": "ks4-dna-genome-s09",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a genome contains far more DNA than is needed for its 20 000 genes.",
        "options": [
            "Because each gene is stored as twenty separate copies",
            "Much of the genome is non-coding DNA, which lies between and around the genes",
            "Because the genome includes the proteins as well as the DNA",
            "Because every base is counted twice over",
        ],
        "correct_index": 1,
        "why": "Only a small fraction of the 3 billion bases lies inside protein-coding genes; most of the genome is non-coding DNA.",
    },
    {
        "id": "ks4-dna-genome-s10",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why sequencing the human genome needed scientists in many countries working together.",
        "options": [
            "Because each country may only study the chromosomes of its own population",
            "Because the genome differs from one country to the next, so every national version had to be read",
            "Because one laboratory can read only a single gene",
            "Because the genome is enormous, so the work was shared out",
        ],
        "correct_index": 3,
        "why": "Three billion bases is far too much for one laboratory, so the work was divided between teams internationally.",
    },
    {
        "id": "ks4-dna-genome-s11",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a doctor might want a patient's genome sequenced before choosing a drug.",
        "options": [
            "Because sequencing a genome changes the alleles that the patient's cells will carry from then on",
            "Because every drug works the same way in everyone",
            "Because the alleles a patient carries can affect how well a drug works for them",
            "Because a genome shows what a patient has eaten",
        ],
        "correct_index": 2,
        "why": "People respond differently to the same drug partly because of the alleles they carry, so the genome can guide the choice.",
    },
    {
        "id": "ks4-dna-genome-s12",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how a person comes to have two copies of every gene.",
        "options": [
            "One copy is inherited from each parent",
            "Both copies are inherited from the mother, because the egg cell is much larger",
            "The cell makes a second copy of every gene after fertilisation",
            "The copies are made when the person is growing",
        ],
        "correct_index": 0,
        "why": "Each gamete brings one chromosome of every pair, so the zygote receives one copy of each gene from each parent.",
    },
    {
        "id": "ks4-dna-genome-s13",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain the difference between a gene and a genome.",
        "options": [
            "A gene is one section of DNA coding for a protein; the genome is all of an organism's genetic material",
            "A gene is found in plants and a genome is found in animals",
            "A genome is one chromosome and a gene is one base",
            "They mean the same thing",
        ],
        "correct_index": 0,
        "why": "A genome is the whole set of genetic material; a gene is one small coding section of it.",
    },
    {
        "id": "ks4-dna-genome-s14",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "An onion has a larger genome than a human being. Suggest what this shows about genome size.",
        "options": [
            "It shows that onions carry far more protein-coding genes than a human being does",
            "It shows that onions are more complex organisms than humans in every way",
            "Genome size does not measure how complex an organism is",
            "It shows the onion is older",
        ],
        "correct_index": 2,
        "why": "Much of any genome is non-coding, so a larger genome does not mean more genes or a more complex organism.",
    },
    {
        "id": "ks4-dna-genome-s15",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why two brothers do not have identical genomes even though they have the same parents.",
        "options": [
            "Because a person's genome changes throughout their life as they grow older and their cells divide",
            "Because each brother has a different number of chromosomes",
            "Because one of them inherited his genome from only one parent",
            "Because each of them inherited a different combination of their parents' alleles",
        ],
        "correct_index": 3,
        "why": "Each gamete carries a different mixture of the parent's alleles, so each child receives a different combination.",
    },
    {
        "id": "ks4-dna-genome-s16",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the substance that chromosomes are made of.",
        "options": [
            "Protein, coiled tightly and stored inside the nucleus of the cell",
            "DNA",
            "Starch",
            "Cellulose fibres",
        ],
        "correct_index": 1,
        "why": "A chromosome is a very long DNA molecule, coiled up so that it fits inside the nucleus.",
    },
    {
        "id": "ks4-dna-genome-s17",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why finding a gene linked to a disease does not immediately give a cure.",
        "options": [
            "Because the gene cannot be read once it has been found",
            "Because genes are not involved in disease",
            "Because knowing which gene is involved still leaves the protein it makes, and its effects on the body, to be worked out",
            "Because the patient would need a new genome",
        ],
        "correct_index": 2,
        "why": "Locating a gene is only the first step; treating the disease means understanding the protein it codes for and how to correct its effect.",
    },
    {
        "id": "ks4-dna-genome-s18",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the genome of a bacterium is much smaller than the genome of a human.",
        "options": [
            "A bacterium is a single cell with far fewer genes to carry",
            "Because a bacterium keeps its genome outside its cell wall where there is more room available",
            "Because bacteria have no genetic material of any kind inside them",
            "Because bacteria are older",
        ],
        "correct_index": 0,
        "why": "A bacterium is one simple cell and needs far fewer proteins, so it needs far fewer genes and much less DNA.",
    },
    {
        "id": "ks4-dna-genome-s19",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a genome is described as an organism's complete set of instructions.",
        "options": [
            "Because it tells the organism which environment it should live in during its life",
            "Because it holds the code for every protein the organism can build",
            "Because it contains all the proteins the organism has made",
            "Because it is copied once",
        ],
        "correct_index": 1,
        "why": "The genome carries the coding sequence for every protein the organism is able to make, and proteins build and run the body.",
    },
    {
        "id": "ks4-dna-genome-s20",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the year in which the Human Genome Project published the finished human sequence.",
        "options": [
            "1859, the same year that Darwin published his theory of natural selection",
            "1953, when the structure of DNA was worked out",
            "1866, when Mendel published",
            "2003",
        ],
        "correct_index": 3,
        "why": "The Human Genome Project ran from 1990 and published the completed sequence in 2003.",
    },
    {
        "id": "ks4-dna-genome-s21",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the results of the Human Genome Project were made freely available to everyone.",
        "options": [
            "So that no scientist could ever study them",
            "So that the sequence could be kept secret",
            "So that one company could use them",
            "So that researchers everywhere could use the data, which speeds up medical discoveries",
        ],
        "correct_index": 3,
        "why": "Open publication let laboratories worldwide build on the sequence at once instead of duplicating the same work.",
    },
    {
        "id": "ks4-dna-genome-s22",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what is meant by saying that a gene is expressed in a cell.",
        "options": [
            "That the gene has been removed from the chromosome and stored in the cytoplasm of the cell",
            "That the gene is being read and its protein is being made",
            "That the gene has been copied ready for the cell to divide in two",
            "That the gene has mutated",
        ],
        "correct_index": 1,
        "why": "A gene is expressed when it is being read and the protein it codes for is actually being produced.",
    },
    {
        "id": "ks4-dna-genome-s23",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A dog has 78 chromosomes in each body cell. State the number of pairs this is.",
        "options": [
            "39 pairs",
            "78 pairs, one pair for each chromosome that the animal carries",
            "156",
            "26",
        ],
        "correct_index": 0,
        "why": "Chromosomes come in pairs, so 78 chromosomes is 39 pairs.",
    },
    {
        "id": "ks4-dna-genome-s24",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what has to be worked out in order to sequence a genome.",
        "options": [
            "The mass of every chromosome in the nucleus, measured to the nearest milligram",
            "The number of cells in the organism",
            "The order of the bases",
            "The shape of the nucleus",
        ],
        "correct_index": 2,
        "why": "Sequencing means reading the order in which the four bases occur along the DNA.",
    },
    {
        "id": "ks4-dna-genome-s25",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the Human Genome Project took over ten years to complete.",
        "options": [
            "Because the genome had to be copied out by hand",
            "Because three billion bases had to be read in order, and the technology of the time was slow and expensive",
            "Because there were only twenty genes to find",
            "Because the DNA had to be grown first",
        ],
        "correct_index": 1,
        "why": "Three billion bases is an enormous amount to read, and sequencing in the 1990s was far slower and costlier than it is now.",
    },
    {
        "id": "ks4-dna-genome-s26",
        "subtopic_slug": "dna-genome",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why knowing the genome of a virus is useful during an outbreak of disease.",
        "options": [
            "Because the genome tells doctors which patients will catch the virus next in the population",
            "Because the virus can then be persuaded to stop reproducing inside its host cells",
            "Because a genome makes a person immune",
            "Because changes in the virus's genome can be tracked as it spreads",
        ],
        "correct_index": 3,
        "why": "Sequencing lets scientists follow how a virus is changing and spreading, which guides vaccine design and control measures.",
    },
    {
        "id": "ks4-dna-genome-h05",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Species A shares 85% of its genome with species B, and 60% with species C. Deduce which two of the three are most closely related.",
        "options": [
            "B and C, because both of their percentages were measured against the same first species",
            "None of them can be related to each other",
            "A and B, because a larger shared fraction means a more recent ancestor",
            "A and C",
        ],
        "correct_index": 2,
        "why": "The more of the genome two species share, the less time has passed since their lines separated.",
    },
    {
        "id": "ks4-dna-genome-h06",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that sequencing every baby's genome at birth would be a wholly good thing.",
        "options": [
            "It is not clear-cut: it could warn of disease but also creates worry",
            "It is good in every case, because knowing a genome removes the risk of illness in later life",
            "It is a bad idea, because a sequenced genome could no longer be passed on to the next generation properly",
            "It is a bad idea, because the sequence would be out of date by the time the baby grew up",
        ],
        "correct_index": 0,
        "why": "Early sequencing could flag treatable conditions, but it also creates lifelong private data and anxiety about conditions that may never develop.",
    },
    {
        "id": "ks4-dna-genome-h07",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a genome sequence alone cannot tell you everything about how an organism will turn out.",
        "options": [
            "Because characteristics also depend on the environment, and on which genes are switched on in each cell",
            "Because the genome changes completely as the organism grows",
            "Because a genome contains no information about proteins",
            "Because every organism has the same genome",
        ],
        "correct_index": 0,
        "why": "Characteristics come from genes and environment together, and from which genes are expressed in which cells.",
    },
    {
        "id": "ks4-dna-genome-h08",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A scientist claims she has found the single gene for intelligence. Evaluate this claim.",
        "options": [
            "It is sound, because each human characteristic is controlled by exactly one gene of its own",
            "It is sound, because upbringing and schooling cannot affect a person's intelligence",
            "It is doubtful — most characteristics involve many genes and the environment too",
            "It is wrong, because genes do not exist",
        ],
        "correct_index": 2,
        "why": "Most human characteristics are controlled by several genes and strongly affected by environment, so a single gene for a complex trait is very unlikely.",
    },
    {
        "id": "ks4-dna-genome-h09",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the discovery that humans have only about 20 000 genes surprised scientists.",
        "options": [
            "Because a simple worm was already known to have several million genes of its own",
            "Because the number is far larger than anyone expected",
            "Because humans have no non-coding DNA",
            "Because humans build many more than 20 000 proteins and are very complex",
        ],
        "correct_index": 3,
        "why": "Scientists had expected far more genes in an organism as complex as a human; the small number showed that complexity does not come from gene count alone.",
    },
    {
        "id": "ks4-dna-genome-h10",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a genome sequence can be more useful to a doctor than a family history of illness.",
        "options": [
            "Because a family history cannot be written down accurately by any member of the family",
            "It shows the actual alleles the patient carries",
            "Because a genome tells the doctor which illnesses the patient has already had",
            "Because a family history is about the environment only",
        ],
        "correct_index": 1,
        "why": "A family history is indirect evidence of risk; the genome shows directly which alleles a patient actually carries.",
    },
    {
        "id": "ks4-dna-genome-h11",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A company offers to sequence the genome of a pet dog and predict its behaviour. Evaluate this offer.",
        "options": [
            "It is reliable, because behaviour is set by genes",
            "It is worthless, because dogs have no genome",
            "It is limited — genes influence behaviour, but training and the dog's experiences matter a great deal too",
            "It is reliable for puppies but not adults",
        ],
        "correct_index": 2,
        "why": "Behaviour is influenced by alleles but shaped heavily by environment, so a genome can give tendencies rather than predictions.",
    },
    {
        "id": "ks4-dna-genome-h12",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a person's genome stays the same throughout their life while their characteristics change.",
        "options": [
            "Because the genome is fixed at fertilisation but features also depend on environment",
            "Because the whole genome is rewritten from scratch every time one of the body's own cells divides",
            "Because characteristics are decided by the proteins a person eats rather than by genes",
            "Because the genome is stored outside the body",
        ],
        "correct_index": 0,
        "why": "The base sequence you inherit does not change, but how you develop depends on environment and on which genes are expressed at different ages.",
    },
    {
        "id": "ks4-dna-genome-h13",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two unrelated people differ at about 3 million bases out of 3 billion. Calculate the percentage of their genome that differs.",
        "options": [
            "30%, because 3 million is a very large number of bases to differ by in total",
            "About 0.1% of the genome",
            "10%",
            "1%",
        ],
        "correct_index": 1,
        "why": "3 million divided by 3 billion is 0.001, which is 0.1%.",
    },
    {
        "id": "ks4-dna-genome-h14",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why sequencing the genomes of many people, rather than just one, was needed to find disease genes.",
        "options": [
            "Because one person's genome would have been damaged during the sequencing process that was used",
            "Because one genome holds far too few bases for a gene to be located in it",
            "Because every person carries a completely different set of genes from everyone else",
            "Because a link only shows up across many affected people",
        ],
        "correct_index": 3,
        "why": "A gene counts as disease-linked only when the same variant turns up repeatedly in affected people and rarely in unaffected ones.",
    },
    {
        "id": "ks4-dna-genome-h15",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the same gene can be found in a human, a mouse and a fruit fly.",
        "options": [
            "Because the gene evolved separately three times over",
            "Because all three animals share the same habitat",
            "Because all animals have identical genomes",
            "Because all three inherited it from a shared ancestor, and the sequence has changed only slowly since",
        ],
        "correct_index": 3,
        "why": "Genes essential to all animals are inherited from a distant common ancestor and change very slowly, because most changes to them are harmful.",
    },
    {
        "id": "ks4-dna-genome-h16",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why storing genome data securely is harder than storing an ordinary medical test result.",
        "options": [
            "Because a genome file is far too large for any computer in the world to store on its own",
            "Because a genome identifies a person and their relatives, and it never changes",
            "Because genome data must be printed onto paper before it can be stored anywhere",
            "Because genomes are secret",
        ],
        "correct_index": 1,
        "why": "A genome cannot be reissued like a password, and it also reveals information about a person's relatives, so a leak is permanent and wide.",
    },
    {
        "id": "ks4-dna-genome-h17",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare what a genome tells you with what a person's outward characteristics tell you.",
        "options": [
            "The genome gives the instructions; the characteristics are what those instructions and the environment produced",
            "The genome and the characteristics are simply two different words for the same thing, with no real difference between them",
            "The characteristics are inherited and the genome is not",
            "Both are set entirely by the environment",
        ],
        "correct_index": 0,
        "why": "The genome is the inherited code; the characteristics are the observable result of that code interacting with the environment.",
    },
    {
        "id": "ks4-dna-genome-h18",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A crop plant's genome is sequenced. Suggest how a plant breeder could make use of this.",
        "options": [
            "By rewriting the whole genome so that the crop no longer needs water in order to grow",
            "By counting how many chromosomes each plant in the field happens to have",
            "To find the alleles that give higher yield",
            "By making every plant in the crop genetically identical to the sequenced one",
        ],
        "correct_index": 2,
        "why": "Knowing the sequence lets a breeder identify which alleles are linked to a desirable characteristic and select plants that carry them.",
    },
    {
        "id": "ks4-dna-genome-h19",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a genome sequence taken from a 5000-year-old human skeleton is valuable to scientists.",
        "options": [
            "Because ancient DNA works better than modern DNA",
            "Because it can be compared with living populations, showing how people moved and mixed in the past",
            "Because the skeleton's genome is larger than ours",
            "Because ancient people had more genes",
        ],
        "correct_index": 1,
        "why": "Comparing ancient and modern genomes is exactly how migration patterns of the past are traced.",
    },
    {
        "id": "ks4-dna-genome-h20",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student says that because your genome is fixed, nothing you do can change your health. Evaluate this.",
        "options": [
            "Correct, because the alleles that a person inherits decide every illness they will ever suffer from",
            "Correct, because diet and exercise have no effect on the way that a person's body works",
            "Wrong, because a person's genome changes each time they exercise",
            "Wrong — the genome sets risks, but diet, exercise and environment affect health too",
        ],
        "correct_index": 3,
        "why": "Genes set susceptibility rather than destiny; lifestyle and environment strongly affect whether a risk becomes an illness.",
    },
    {
        "id": "ks4-dna-genome-h21",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why sequencing a bacterium that is causing an outbreak helps to find where the outbreak began.",
        "options": [
            "Because the bacterium's own genome names the hospital ward on which it first appeared",
            "Because bacteria have no genome unless they are infecting somebody",
            "Because samples with almost identical genomes must come from the same source",
            "Because sequencing kills the bacteria",
        ],
        "correct_index": 2,
        "why": "Bacteria from one source share a near-identical sequence, so matching genomes links cases and points back to the origin.",
    },
    {
        "id": "ks4-dna-genome-h22",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the number of genes in a genome is not the same as the number of bases in it.",
        "options": [
            "A gene is many bases long",
            "Because bases are only found in the non-coding parts of the genome, never inside a gene",
            "Because a gene contains no bases and is made of protein instead",
            "Because each base contains several thousand different genes inside it",
        ],
        "correct_index": 0,
        "why": "Each gene is a stretch of hundreds or thousands of bases, so 3 billion bases make only about 20 000 genes.",
    },
    {
        "id": "ks4-dna-genome-h23",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the genome of a person with the genome of their identical twin.",
        "options": [
            "They are essentially the same, because both developed from one fertilised egg that divided by mitosis",
            "They share half of their alleles, as brothers and sisters do",
            "They are completely different genomes",
            "Twins have no genome of their own",
        ],
        "correct_index": 0,
        "why": "Identical twins come from one zygote, so their genomes are the same apart from rare mutations arising afterwards.",
    },
    {
        "id": "ks4-dna-genome-h24",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why sequencing genomes has become far cheaper since 2003.",
        "options": [
            "Because a genome has become a very great deal shorter than it used to be in the years before",
            "Because the technology has improved and can now read many sequences at once",
            "Because a genome no longer has to be read in order, so any part of it can be skipped",
            "Because DNA is cheap",
        ],
        "correct_index": 1,
        "why": "Sequencing machines now read millions of fragments in parallel, so the cost of one genome has fallen from billions of pounds to a few hundred.",
    },
    {
        "id": "ks4-dna-genome-h25",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A patient's genome shows an allele linked to a disease, but the patient is healthy. Explain how this is possible.",
        "options": [
            "Because a genome cannot show which alleles a patient carries, but only how many of them there are",
            "Because the allele must have been read incorrectly by the machine",
            "Because such an allele raises the risk of the illness rather than guaranteeing it",
            "Because healthy people have no alleles",
        ],
        "correct_index": 2,
        "why": "Most disease-linked alleles change the probability of developing a condition; environment and other genes decide whether it appears.",
    },
    {
        "id": "ks4-dna-genome-h26",
        "subtopic_slug": "dna-genome",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why comparing the genomes of two separated populations of one species can still show differences.",
        "options": [
            "Because two populations of one species carry completely different sets of genes from each other",
            "Because each population has its own number of chromosomes in every body cell",
            "Because a genome is different in every cell of every individual in the population",
            "Because different alleles become common in populations that live apart",
        ],
        "correct_index": 3,
        "why": "Populations that breed separately accumulate different mutations and different allele frequencies, though they remain one species.",
    },
]
