"""Biology · Inheritance, Variation and Evolution — the MRB-338 expansion,
subtopic `sexual-asexual-reproduction`.

The baseline twelve cover one parent, potato tubers, fertilisation, the
zygote's 46 chromosomes, a clone evaluation, aphids, two sisters against two
strawberry plants, a monoculture risk, runners, a spawning fish, meiosis in
a testis and why clones are identical. This file takes the DEFINITIONS and
the NAMED EXAMPLES the specification asks for and the baseline skips:
sexual reproduction as the fusion of gametes with a mixing of genetic
information; the gametes of animals and of plants named; asexual
reproduction as mitosis with no gametes and no fusion; binary fission in
bacteria; spores in fungi; budding in yeast; bulbs and runners against seeds
in one plant; the malarial parasite using both, in the mosquito and in the
human host; and which cell division belongs to which.

⚠️ `meiosis` owns the cell division and the chromosome arithmetic;
`advantages-sexual-asexual` owns the weighing-up of the two strategies, and
`cloning` owns the artificial techniques — tissue culture, cuttings, embryo
transplant and adult cell cloning. This leaf describes what the two kinds of
reproduction ARE and where they occur in nature.
"""

TOPIC = "inheritance"
SUBJECT = "biology"

QUESTIONS = [
    {
        "id": "ks4-sexual-asexual-reproduction-e05",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what sexual reproduction involves.",
        "options": [
            "The fusion of a male gamete with a female gamete, mixing genetic information from two parents",
            "One parent dividing",
            "A cell splitting in two",
            "Growth from a bulb",
        ],
        "correct_index": 0,
        "why": "Sexual reproduction joins two gametes, so the offspring receives a mixture of both parents' genetic information.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-e06",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the two gametes involved in human reproduction.",
        "options": [
            "Pollen grains and ovules, which are the two gametes that flowering plants produce",
            "Two identical spores released from the parent",
            "Sperm and egg cells",
            "Two zygotes",
        ],
        "correct_index": 2,
        "why": "The male gamete is the sperm cell and the female gamete is the egg cell.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-e07",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the type of cell division used in asexual reproduction.",
        "options": [
            "Meiosis, which halves the chromosome number as the gametes are being made",
            "Both kinds together",
            "Neither kind",
            "Mitosis, and nothing else",
        ],
        "correct_index": 3,
        "why": "Asexual reproduction uses mitosis only, so the offspring are genetically identical to the parent.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-e08",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the process by which a bacterium reproduces asexually.",
        "options": [
            "Fertilisation, in which two bacterial cells fuse together to form one new cell",
            "Binary fission",
            "Budding, in which an outgrowth breaks away from the parent",
            "Pollination, which carries the male gamete to the female part",
        ],
        "correct_index": 1,
        "why": "A bacterium copies its DNA and splits into two identical cells, which is called binary fission.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-e09",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the structures that many fungi release in order to reproduce asexually.",
        "options": [
            "Seeds",
            "Eggs",
            "Spores, which are carried away and grow into new fungi that match the parent",
            "Runners",
        ],
        "correct_index": 2,
        "why": "Fungi such as moulds scatter huge numbers of spores, each of which can grow into a new individual.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-e10",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how many parents asexual reproduction needs.",
        "options": [
            "Just one, and never two",
            "Two parents, one of which supplies the male gamete and the other the female gamete",
            "Two parents of the same sex, which exchange genetic material between them",
            "None",
        ],
        "correct_index": 0,
        "why": "No gametes are involved, so one parent alone produces the offspring.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-e11",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the two gametes that a flowering plant uses in sexual reproduction.",
        "options": [
            "Two spores of the same kind, released from the anthers of the flower into the air",
            "Pollen and the egg cell",
            "Sperm and egg",
            "Runners and bulbs",
        ],
        "correct_index": 1,
        "why": "The male gamete is carried in the pollen grain and the female gamete is the egg cell inside the ovule.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-e12",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what is produced when a daffodil grows a new plant from its bulb.",
        "options": [
            "An offspring that is different from the parent in most of its characteristics",
            "A seed that must be pollinated before it can start to grow",
            "A plant with twice the number of chromosomes",
            "A clone of the parent",
        ],
        "correct_index": 3,
        "why": "Growth from a bulb is asexual, so the new plant is genetically identical to the parent.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s05",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the offspring of sexual reproduction all differ from one another.",
        "options": [
            "Because they grow in different places",
            "Because they are fed differently",
            "Because they are produced by mitosis",
            "Because every gamete carries a different mixture of alleles and which two fuse is a matter of chance",
        ],
        "correct_index": 3,
        "why": "Meiosis gives each gamete a different combination of alleles, and fertilisation combines them at random.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s06",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how yeast reproduces when conditions are good.",
        "options": [
            "Two yeast cells fuse together to produce a single new cell that has a mixture of alleles",
            "It buds, growing a small outgrowth that breaks away as a new cell",
            "It releases gametes that must find a partner cell in the surrounding liquid",
            "It splits into four",
        ],
        "correct_index": 1,
        "why": "Budding is asexual: a bulge forms on the parent cell, receives a copy of the nucleus and separates.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s07",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what happens to the genetic information of the two parents during sexual reproduction.",
        "options": [
            "It is mixed, so the offspring carries half of its alleles from each of its two parents",
            "It is copied exactly from one parent only, so that the offspring matches that parent in every way",
            "It is destroyed and replaced",
            "It is doubled",
        ],
        "correct_index": 0,
        "why": "Each gamete brings half a set, so the offspring is a new combination of both parents' alleles.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s08",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State where in its life cycle the malarial parasite reproduces sexually.",
        "options": [
            "In the red blood cells of the person it has infected, where it multiplies very rapidly",
            "In the soil, before it is taken up by a mosquito feeding nearby",
            "In the mosquito",
            "In the liver of the human host, during the first few days of an infection",
        ],
        "correct_index": 2,
        "why": "The parasite reproduces sexually inside the mosquito and asexually inside the human host.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s09",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a strawberry plant can produce both identical and non-identical offspring.",
        "options": [
            "Because it grows in two different kinds of soil",
            "Because it reproduces asexually through runners and sexually through the seeds in its fruit",
            "Because some of its offspring are fed better",
            "Because its flowers open at different times",
        ],
        "correct_index": 1,
        "why": "Runners are asexual and give clones; seeds are the product of fertilisation and all differ.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s10",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what happens to a bacterium's DNA just before binary fission.",
        "options": [
            "It is shared out between the two new cells without being copied at any point first",
            "It is exchanged with the DNA of a second bacterium alongside it",
            "It is broken down",
            "It is copied, so that each new cell receives a complete set",
        ],
        "correct_index": 3,
        "why": "The circular DNA is copied first, so both daughter cells end up with the full genetic material.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s11",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why no gametes are needed in asexual reproduction.",
        "options": [
            "Because gametes are only made by animals and never by any plant or fungus at any stage",
            "Because gametes cannot survive",
            "Because there is no fusion — one parent's cells simply divide",
            "Because the parent uses seeds",
        ],
        "correct_index": 2,
        "why": "Gametes exist so that genetic information can be combined; with no fusion, none is needed.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s12",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a gardener produces by planting one bulb and getting several new bulbs a year later.",
        "options": [
            "Clones",
            "Offspring that each carry a different mixture of the alleles of the original plant",
            "Seeds that must be pollinated before they can germinate",
            "Plants with half the usual number of chromosomes in their cells",
        ],
        "correct_index": 0,
        "why": "New bulbs form by mitosis from the parent bulb, so every plant is genetically identical to it.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s13",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why sexual reproduction is needed for a species to show genetic variation between individuals.",
        "options": [
            "Because it is the only way of bringing alleles from two different parents together in one offspring",
            "Because it produces more offspring",
            "Because gametes are larger",
            "Because it uses mitosis",
        ],
        "correct_index": 0,
        "why": "Only fertilisation combines alleles from two individuals, which is where most new combinations come from.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s14",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how the malarial parasite reproduces inside a person it has infected.",
        "options": [
            "It produces gametes that fuse in the bloodstream to give a new generation of parasites",
            "It waits without reproducing until the person is bitten by a second mosquito",
            "Asexually, so the parasites multiply rapidly",
            "It reproduces sexually in the liver",
        ],
        "correct_index": 2,
        "why": "Inside the human host the parasite divides asexually, which is why numbers rise so quickly during an attack.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s15",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a fungus can spread across a whole field from a single individual.",
        "options": [
            "Because a fungus grows so quickly that it covers the ground before anything else can grow there",
            "Because fungi need no food",
            "Because the field is warm",
            "Because it releases spores asexually, and each one grows into a new fungus",
        ],
        "correct_index": 3,
        "why": "Asexual spores are produced in enormous numbers and each can start a new individual without a partner.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s16",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the name given to the new individual formed immediately after two gametes have fused.",
        "options": [
            "A clone of the parent that produced the larger of the two gametes involved",
            "A zygote",
            "A gamete of a third kind, which fuses with another one",
            "An embryo that has already begun to specialise",
        ],
        "correct_index": 1,
        "why": "The single cell formed at fertilisation is the zygote; it becomes an embryo once it starts dividing.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s17",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why bacteria can produce an enormous population in a single day.",
        "options": [
            "Because they reproduce sexually",
            "Because they live in warm places",
            "Because each cell splits into two by binary fission, and under good conditions this can happen every twenty minutes",
            "Because they eat very little",
        ],
        "correct_index": 2,
        "why": "Asexual division needs no partner, so numbers double again and again in a very short time.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s18",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what a gardener does when taking a cutting from a plant.",
        "options": [
            "Removes a piece of stem and grows it into a new plant",
            "Collects the pollen from one plant and brushes it onto the flower of a second plant nearby",
            "Collects the seeds from the fruit and sows them in damp compost",
            "Grafts two plants",
        ],
        "correct_index": 0,
        "why": "A cutting grows by mitosis into a whole new plant, which is a clone of the one it was taken from.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s19",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what must happen before a seed can be formed in a flowering plant.",
        "options": [
            "The plant must grow a runner out sideways so that a new plantlet can be produced at its tip",
            "A pollen grain's gamete must fuse with an egg cell in the ovule",
            "The flower must close up completely",
            "The plant must be cut back",
        ],
        "correct_index": 1,
        "why": "A seed is the product of fertilisation, so a male gamete must reach and fuse with the egg cell.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s20",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State which kind of reproduction produces offspring carrying alleles from two individuals.",
        "options": [
            "Asexual reproduction, in which the single parent shares its alleles between its offspring",
            "Budding, in which a small outgrowth separates from the parent",
            "Binary fission, which doubles the number of cells present each time it takes place",
            "Sexual reproduction",
        ],
        "correct_index": 3,
        "why": "Only fertilisation brings alleles from two parents together in one offspring.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s21",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a potato grower plants pieces of potato rather than potato seeds.",
        "options": [
            "Because seeds cost more",
            "Because potato plants never flower",
            "Because seeds grow too quickly",
            "Because each piece grows into a clone, so the whole crop has the same qualities as the parent plant",
        ],
        "correct_index": 3,
        "why": "Asexual reproduction from tubers keeps the variety uniform; seed-grown potatoes would all differ.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s22",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why asexual reproduction produces no new combinations of alleles.",
        "options": [
            "Because the parent carries only one allele for each of the characteristics that it passes on",
            "Because mitosis copies the parent's DNA exactly, with no second parent",
            "Because the offspring are much smaller than the parent plant that produced them",
            "Because alleles are lost",
        ],
        "correct_index": 1,
        "why": "There is no meiosis to shuffle the alleles and no fertilisation to bring in a second set.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s23",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happens to the number of chromosomes when a gamete is formed.",
        "options": [
            "It is halved, so a gamete has half a set",
            "It is doubled, so that the gamete carries twice as many chromosomes as a body cell does",
            "It stays the same",
            "It falls to a quarter",
        ],
        "correct_index": 0,
        "why": "Gametes are made by meiosis, which reduces the chromosome number to half that of a body cell.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s24",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State which organisms in this list reproduce asexually: bacteria, some fungi and many plants.",
        "options": [
            "Only the bacteria, because a fungus and a plant both have to produce gametes in order to breed",
            "Only the fungi and the plants, since a bacterium is far too small to be able to divide",
            "All three of them",
            "None of them reproduce asexually under any conditions at all",
        ],
        "correct_index": 2,
        "why": "Bacteria use binary fission, fungi release asexual spores and many plants use runners, bulbs or tubers.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s25",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why fertilisation has to follow meiosis in a sexual life cycle.",
        "options": [
            "Because meiosis kills the parent",
            "Because meiosis halves the chromosome number, and fertilisation is what puts the full set back together again",
            "Because gametes are too large",
            "Because meiosis makes two cells",
        ],
        "correct_index": 1,
        "why": "The halving and the fusing match each other, so the chromosome number of the species stays constant.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-s26",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what happens to a spore after a fungus has released it into the air.",
        "options": [
            "It fuses with a second spore that it meets, forming a cell with a full set of chromosomes",
            "It must be fertilised by a gamete before it is able to grow into anything at all",
            "It breaks down",
            "It settles and grows into a new fungus identical to the parent",
        ],
        "correct_index": 3,
        "why": "An asexual spore needs no partner: it germinates where it lands and grows into a clone of the parent.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h05",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A greenhouse of tomato plants all grown from cuttings is attacked by a new virus. Predict what happens and explain why.",
        "options": [
            "Only half of the plants are affected, because half of them will have inherited resistance from the parent",
            "None are affected, because cuttings give stronger plants",
            "Almost all are affected, because every plant carries the same alleles",
            "The plants recover",
        ],
        "correct_index": 2,
        "why": "Clones share their alleles, so a pest or disease that can harm one can harm them all.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h06",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why asexual reproduction is faster than sexual reproduction for most organisms that can use both.",
        "options": [
            "No partner is needed and no gametes have to be made",
            "Because the offspring of asexual reproduction grow to their full adult size far more quickly",
            "Because asexual offspring need no food while they are developing",
            "Because sexual reproduction can only take place at one particular time of the year",
        ],
        "correct_index": 0,
        "why": "Finding a mate and producing gametes both take time and energy, and asexual reproduction skips both steps.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h07",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the genetic material of a bacterium with that of the two cells it produces by binary fission.",
        "options": [
            "All three carry the same genetic material, because the DNA was copied and one copy went to each new cell",
            "Each new cell carries half of it",
            "The two new cells each carry double",
            "The new cells carry none of it",
        ],
        "correct_index": 0,
        "why": "Binary fission is asexual, so both daughter cells are identical to the parent apart from any new mutation.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h08",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A mosquito bites a person with malaria and later bites a second person. Explain how sexual reproduction in the mosquito matters to the second person.",
        "options": [
            "It does not matter at all, because the parasite reproduces in exactly the same way inside both of the two hosts",
            "It means no parasite is passed on",
            "It means the parasite passed to the second person carries a new combination of alleles",
            "It means the parasite reaching the second person is an exact copy of the one taken from the first host",
        ],
        "correct_index": 2,
        "why": "Sexual reproduction inside the mosquito reshuffles the parasite's alleles, so the strain reaching the next host can differ.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h09",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a species living in a habitat that changes unpredictably usually reproduces sexually.",
        "options": [
            "Because sexual reproduction always produces a far larger number of offspring in every generation",
            "Because a species reproducing sexually need not compete for resources",
            "Because an unpredictable habitat makes mitosis impossible",
            "Because the variation it produces means some offspring may cope with the new conditions",
        ],
        "correct_index": 3,
        "why": "Variation is the raw material selection needs; identical offspring would all fail together if conditions turned against them.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h10",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a single bacterium left on a work surface is a serious hygiene problem.",
        "options": [
            "Because bacteria are able to reproduce sexually with any other bacterium that they come across",
            "It can divide asexually into millions within hours",
            "Because one bacterium is large enough to be seen without using a microscope of any kind",
            "Because a bacterium releases spores that travel through the air",
        ],
        "correct_index": 1,
        "why": "Binary fission needs no partner, so one cell in warm, moist conditions becomes a huge population very quickly.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h11",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A grower finds one plant among a field of clones with an unusual leaf shape. Suggest the cause.",
        "options": [
            "The plant was fertilised",
            "That plant has two parents",
            "A mutation occurred in the cell that gave rise to that plant, so its DNA is no longer an exact copy",
            "Clones are never alike",
        ],
        "correct_index": 2,
        "why": "Asexual reproduction copies the DNA, but a copying error can still arise, which is the one source of variation clones have.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h12",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the offspring of one pair of parents are not identical to each other but a bulb's offspring are.",
        "options": [
            "Meiosis and fertilisation give each offspring a different mixture",
            "Because the bulb's offspring are grown in soil of a completely uniform composition throughout the bed",
            "Because a bulb produces gametes that are all identical to one another before it reproduces",
            "Because the parents are old",
        ],
        "correct_index": 0,
        "why": "Two independent shuffles happen in sexual reproduction; asexual reproduction copies one parent exactly.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h13",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why many plants are able to reproduce both sexually and asexually.",
        "options": [
            "Because a plant that reproduces in only one of the two ways will die within a single growing season anyway",
            "Spreading asexually fills good ground quickly, while seeds give variation and can travel further",
            "Because sexual reproduction is impossible for a rooted plant",
            "Because a plant has no gametes",
        ],
        "correct_index": 1,
        "why": "The two methods do different jobs: rapid local spread when conditions suit, and varied, dispersing offspring otherwise.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h14",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student says that because bacteria reproduce asexually they can never evolve. Evaluate this statement.",
        "options": [
            "It is correct, because a population of bacteria carries no variation of any kind between its members",
            "It is correct, because evolution only happens in species that reproduce sexually",
            "It is wrong, because bacteria reproduce sexually when conditions get difficult",
            "It is wrong — mutations still occur",
        ],
        "correct_index": 3,
        "why": "Mutation alone supplies variation, and bacteria divide so fast that useful mutations spread very quickly.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h15",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a fungus that has been growing well may switch to sexual reproduction when its food runs out.",
        "options": [
            "Because spores need food",
            "Because sexual reproduction is faster",
            "Because mitosis stops at once",
            "Because varied offspring have a better chance that at least some of them can survive the harder conditions",
        ],
        "correct_index": 3,
        "why": "When conditions turn against the parent, being identical to it is no longer an advantage, so variation becomes valuable.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h16",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a new potato variety must be produced from seed rather than from tubers.",
        "options": [
            "Because a tuber cannot be planted in the ground and grown on in the way that a seed can be",
            "Tubers give clones, so only seeds can give a genuinely new combination",
            "Because a seed grows into a much larger plant than a tuber does in one season",
            "Because tubers cost more",
        ],
        "correct_index": 1,
        "why": "A new variety needs a new combination of alleles, and only sexual reproduction can create one.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h17",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the number of offspring an organism can produce asexually with the number it can produce sexually.",
        "options": [
            "Asexual reproduction usually gives far more, because no mate and no gametes are needed",
            "Sexual reproduction always gives more offspring, because two parents are contributing to the process",
            "Both methods give the same number",
            "Neither method gives offspring",
        ],
        "correct_index": 0,
        "why": "Without the cost of finding a mate and making gametes, an organism can produce offspring much faster and in greater numbers.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h18",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a coral reef damaged by a storm can regrow from surviving fragments.",
        "options": [
            "Because coral fragments take in genetic material from the sea water around them as they grow",
            "Because the storm causes the coral animals to produce gametes faster",
            "Each fragment grows asexually into a new colony",
            "Because the fragments are fertilised by the coral colonies further along the reef",
        ],
        "correct_index": 2,
        "why": "Coral polyps divide asexually, so a broken piece can rebuild a whole colony of genetically identical animals.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h19",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a species that reproduces only asexually has a smaller gene pool than one that reproduces sexually.",
        "options": [
            "Because it has fewer offspring",
            "Because no new combinations of alleles are ever made, so the only new alleles come from mutation",
            "Because its offspring die young",
            "Because it produces no DNA",
        ],
        "correct_index": 1,
        "why": "Sexual reproduction constantly creates new allele combinations; asexual lines rely on the rare mutation alone.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h20",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A farmer buys new seed potatoes every year instead of saving his own tubers. Suggest why.",
        "options": [
            "Because tubers saved on the farm would produce plants that all differ from one another in their yield",
            "Because a tuber saved from a crop cannot be planted again in the following growing season",
            "Because saved tubers grow into seeds",
            "Because disease builds up in tubers passed on from crop to crop",
        ],
        "correct_index": 3,
        "why": "Because every plant in the clone is equally susceptible, an infection carried in the tubers spreads through the whole crop.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h21",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a single aphid arriving on a rose bush can produce a large colony within weeks.",
        "options": [
            "Because an aphid is able to fertilise itself and so produce a very large number of seeds at once",
            "Because aphids grow very rapidly",
            "Because it reproduces asexually and needs no mate to produce offspring",
            "Because roses attract aphids",
        ],
        "correct_index": 2,
        "why": "Asexual reproduction lets one founder produce offspring immediately, with no time or energy spent finding a partner.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h22",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the offspring of asexual reproduction are described as a population with no genetic variation.",
        "options": [
            "They are all clones",
            "Because they are all born at exactly the same moment as one another in the growing season",
            "Because the population contains very few separate individuals",
            "Because each carries only half the parent's chromosomes",
        ],
        "correct_index": 0,
        "why": "Mitosis copies the parent's DNA, so every offspring has the same alleles as the parent and as each other.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h23",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a plant grown from a runner flowers at the same time and colour as its parent.",
        "options": [
            "Because the runner carried a complete copy of the parent's alleles, and those alleles control both of those features",
            "Because the two plants are joined",
            "Because both plants get the same light",
            "Because runners carry no DNA",
        ],
        "correct_index": 0,
        "why": "A runner produces a clone by mitosis, so it carries exactly the alleles that control flowering time and flower colour.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h24",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why sexual reproduction is more common than asexual reproduction among large animals.",
        "options": [
            "Because a large animal is physically quite unable to carry out mitosis in any of the cells of its body",
            "Because large animals live in changing habitats and few can bud off copies",
            "Because a large animal has more chromosomes than a small one and so must reproduce sexually",
            "Because they are slow",
        ],
        "correct_index": 1,
        "why": "Complex bodies cannot simply bud off copies, and long-lived animals in variable environments benefit from varied offspring.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h25",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A gardener wants twenty plants with exactly the same flower colour as one prized specimen. Recommend a method and justify it.",
        "options": [
            "Collect the seeds from the prized plant and sow them, because seeds carry the parent's alleles unchanged",
            "Cross it with a different variety and keep the closest offspring",
            "Take cuttings, because each one grows by mitosis into an identical clone",
            "Grow the plant in a larger pot",
        ],
        "correct_index": 2,
        "why": "Only asexual reproduction guarantees the same alleles; seeds from the plant would each carry a different combination.",
    },
    {
        "id": "ks4-sexual-asexual-reproduction-h26",
        "subtopic_slug": "sexual-asexual-reproduction",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the two kinds of reproduction are distinguished by whether gametes fuse rather than by the number of offspring.",
        "options": [
            "Because the number of offspring is impossible for a biologist to count",
            "Because asexual reproduction always gives exactly one offspring per parent",
            "Because sexual reproduction produces a smaller number of offspring than asexual reproduction does",
            "Because fusion is what mixes the genetic information",
        ],
        "correct_index": 3,
        "why": "Both methods can give many offspring; what separates them is whether two sets of genetic information are combined.",
    },
]
