"""Biology · Inheritance, Variation and Evolution — the MRB-338 expansion,
subtopic `selective-breeding`.

The baseline twelve cover the term artificial selection, the ten-thousand
year figure, wild cabbage, the first step, a fungal epidemic in one variety,
why a bacterial gene cannot be bred in, the "safe because natural" argument,
two breeders and herd size, a wool flock, why breeding cannot invent a
characteristic, short-stemmed wheat and ten generations of strawberries.
This file supplies the process as a repeated CYCLE — choose the parents,
breed them, choose the best of the offspring, repeat over many generations
— together with the four kinds of characteristic the specification names
(disease resistance in food crops, animals that produce more meat or milk,
domestic dogs with a gentle nature, and large or unusual flowers), the
inbreeding problems that follow (inherited defects and susceptibility to
disease), and a direct comparison with natural selection.

⚠️ `genetic-engineering` is the neighbouring leaf and owns moving a gene
between species; `cloning` owns copying one individual. This leaf only ever
uses alleles the species already carries.
"""

TOPIC = "inheritance"
SUBJECT = "biology"

QUESTIONS = [
    {
        "id": "ks4-selective-breeding-e05",
        "subtopic_slug": "selective-breeding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a breeder does after choosing the two parents with the desired characteristic.",
        "options": [
            "Breeds them together",
            "Destroys the offspring they produce and then starts again with two new parents",
            "Waits for the characteristic to appear in a different species altogether",
            "Inserts a gene from another organism into the cells of both of them",
        ],
        "correct_index": 0,
        "why": "The chosen parents are bred, and the best of their offspring are then chosen as the next parents.",
    },
    {
        "id": "ks4-selective-breeding-e06",
        "subtopic_slug": "selective-breeding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how many generations selective breeding usually takes to produce a clear change.",
        "options": [
            "One generation, because the offspring always show the characteristic perfectly",
            "Half a generation, since the change appears before the offspring are even born",
            "Many generations",
            "None at all, because the parents themselves change during the process",
        ],
        "correct_index": 2,
        "why": "The cycle of choosing and breeding has to be repeated many times before the characteristic is fully established.",
    },
    {
        "id": "ks4-selective-breeding-e07",
        "subtopic_slug": "selective-breeding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give one characteristic that food crops are selectively bred for.",
        "options": [
            "The ability to make a protein found only in a soil bacterium",
            "The ability to grow without carrying out photosynthesis at all",
            "The ability to move to a better field",
            "Disease resistance",
        ],
        "correct_index": 3,
        "why": "Disease resistance in food crops is one of the four aims named by the specification.",
    },
    {
        "id": "ks4-selective-breeding-e08",
        "subtopic_slug": "selective-breeding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name a quality that cattle and sheep have been bred to improve on a farm.",
        "options": [
            "The ability to reproduce asexually when no mate can be found nearby",
            "Producing more meat or milk",
            "A coat that changes colour with the seasons of the year",
            "The ability to survive without eating any food",
        ],
        "correct_index": 1,
        "why": "Animals that produce more meat or more milk is one of the four aims the specification names.",
    },
    {
        "id": "ks4-selective-breeding-e09",
        "subtopic_slug": "selective-breeding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the characteristic domestic dogs have been bred for that is about behaviour.",
        "options": [
            "The ability to see colours that a human being is completely unable to see",
            "Resistance to all of the diseases that a dog might catch during its lifetime",
            "A gentle nature",
            "A much greater number of chromosomes than a wild dog carries",
        ],
        "correct_index": 2,
        "why": "Dogs with a gentle nature is the behavioural example named by the specification.",
    },
    {
        "id": "ks4-selective-breeding-e10",
        "subtopic_slug": "selective-breeding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name a quality a nursery would breed an ornamental plant to improve.",
        "options": [
            "Large or unusual flowers",
            "Roots that are able to grow through solid rock without any difficulty",
            "The ability to produce seeds without needing to be pollinated at all",
            "Leaves that stay exactly the same size throughout the whole year",
        ],
        "correct_index": 0,
        "why": "Large or unusual flowers is the fourth aim named, alongside crop disease resistance, meat or milk yield and gentle dogs.",
    },
    {
        "id": "ks4-selective-breeding-e11",
        "subtopic_slug": "selective-breeding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happens to the genetic variation of a population that is selectively bred.",
        "options": [
            "It rises steadily, because new alleles are created in each generation",
            "It falls",
            "It reaches its highest possible level after about ten generations of breeding",
            "It stays at exactly the same level as it was at the very beginning",
        ],
        "correct_index": 1,
        "why": "Breeding only from a few chosen individuals means many alleles are left behind in each generation.",
    },
    {
        "id": "ks4-selective-breeding-e12",
        "subtopic_slug": "selective-breeding",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the problem caused by breeding closely related individuals together.",
        "options": [
            "Mutation, in which the base sequence of a gene is altered by chance",
            "Natural selection, in which the environment decides which individuals survive",
            "Genetic engineering",
            "Inbreeding",
        ],
        "correct_index": 3,
        "why": "Inbreeding makes it far likelier that an offspring inherits two copies of the same faulty recessive allele.",
    },
    {
        "id": "ks4-selective-breeding-s05",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Put the steps of a selective breeding programme into the right order.",
        "options": [
            "Breed at random first, then choose the parents, and finally destroy the offspring",
            "Insert a gene, then choose the parents, and then repeat over many generations",
            "Choose the offspring before the parents have been bred together at all",
            "Choose the best parents, breed them, choose the best offspring, repeat many times",
        ],
        "correct_index": 3,
        "why": "The programme is a repeated cycle of choosing and breeding, not a single event.",
    },
    {
        "id": "ks4-selective-breeding-s06",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why inbreeding makes an inherited defect more likely to appear.",
        "options": [
            "Because close relatives carry more mutations than unrelated individuals do",
            "Because close relatives often carry the same faulty allele",
            "Because inbreeding causes new faulty alleles to appear in each generation",
            "Because a defect is caused by the environment",
        ],
        "correct_index": 1,
        "why": "A recessive defect only shows when two copies meet, and relatives are far likelier to share the allele.",
    },
    {
        "id": "ks4-selective-breeding-s07",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare who does the choosing in natural selection and in selective breeding.",
        "options": [
            "The environment decides; in breeding a person decides",
            "In both of them a person chooses which individuals will be allowed to breed",
            "In natural selection a person decides and in selective breeding the environment does",
            "In neither of them does anything do any choosing",
        ],
        "correct_index": 0,
        "why": "The mechanism is the same; only the selecting agent differs, which is why breeding is called artificial selection.",
    },
    {
        "id": "ks4-selective-breeding-s08",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why selective breeding works faster than natural selection.",
        "options": [
            "Because a breeder is able to create new alleles that the species did not have",
            "Because selective breeding removes the need for the animals to reproduce",
            "Because a breeder selects strongly every generation",
            "Because natural selection acts only on plants",
        ],
        "correct_index": 2,
        "why": "A breeder applies a far stronger and more consistent selection than the environment usually does.",
    },
    {
        "id": "ks4-selective-breeding-s09",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a breeder must be able to do before a characteristic can be selected for.",
        "options": [
            "Insert the allele for it into the cells of the chosen parent organisms",
            "Recognise the characteristic in the individuals actually available",
            "Prove that the characteristic has never appeared in the species before",
            "Remove every other allele from the population first",
        ],
        "correct_index": 1,
        "why": "Selection can only act on what the breeder can see or measure in the individuals in front of them.",
    },
    {
        "id": "ks4-selective-breeding-s10",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a breeder keeps records of which animals were bred together.",
        "options": [
            "To make sure that every animal in the herd is bred exactly the same number of times",
            "To prove to a buyer that the animals have never been genetically modified at all",
            "To count how many animals there are",
            "To avoid breeding close relatives and to track which alleles are in the herd",
        ],
        "correct_index": 3,
        "why": "Records are the only way to manage inbreeding and to know which lines carry a useful or a faulty allele.",
    },
    {
        "id": "ks4-selective-breeding-s11",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a breeder cannot produce a characteristic that no individual shows.",
        "options": [
            "Because the characteristic would be too difficult for a breeder to measure",
            "Because a new characteristic would make the offspring infertile",
            "Because breeding only concentrates alleles that are already present",
            "Because a breeder is not permitted to try",
        ],
        "correct_index": 2,
        "why": "There is nothing to select; a genuinely new allele would have to come from mutation or from engineering.",
    },
    {
        "id": "ks4-selective-breeding-s12",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what happens to the alleles of the individuals that are not chosen to breed.",
        "options": [
            "They are lost from the population",
            "They are passed to the next generation through the chosen parents instead",
            "They change into the alleles that the breeder has chosen to select for",
            "They become more common in the next generation than they were before",
        ],
        "correct_index": 0,
        "why": "Anything not bred from contributes nothing, which is exactly why variation falls generation by generation.",
    },
    {
        "id": "ks4-selective-breeding-s13",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a pedigree dog breed often suffers from particular health problems.",
        "options": [
            "Because the breed was built from a small number of related animals",
            "Because pedigree dogs are given a different diet from other dogs",
            "Because a pedigree dog carries a greater number of genes than a mixed-breed dog",
            "Because pedigree dogs are never vaccinated",
        ],
        "correct_index": 0,
        "why": "A narrow founding population concentrates faulty recessive alleles, which then appear throughout the breed.",
    },
    {
        "id": "ks4-selective-breeding-s14",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a selectively bred crop is vulnerable to a new disease.",
        "options": [
            "Because a bred crop grows far more slowly than a wild plant does",
            "Because the plants of a bred crop produce no seeds of their own",
            "Because the plants are all very similar",
            "Because the crop is grown in the same field every single year",
        ],
        "correct_index": 2,
        "why": "Reduced variation means a pathogen that can infect one plant can usually infect the whole field.",
    },
    {
        "id": "ks4-selective-breeding-s15",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe how a dairy farmer would begin to raise the milk yield of a herd.",
        "options": [
            "By giving every cow in the herd a much larger quantity of feed each day",
            "By inserting a gene for high milk yield into each of the calves born",
            "By keeping the herd indoors",
            "By breeding from the cows with the highest yields, and from bulls whose mothers yielded well",
        ],
        "correct_index": 3,
        "why": "A bull carries alleles for milk yield even though he produces none, so his mother's record is what guides the choice.",
    },
    {
        "id": "ks4-selective-breeding-s16",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what the wild ancestor of most modern vegetables tells us about selective breeding.",
        "options": [
            "That every vegetable grown today is a genetically modified organism",
            "That very different crops can be produced from one species",
            "That vegetables were created separately and have never changed since",
            "That wild plants cannot be eaten",
        ],
        "correct_index": 1,
        "why": "Broccoli, cabbage, kale and cauliflower all came from wild cabbage by selecting different parts of the plant.",
    },
    {
        "id": "ks4-selective-breeding-s17",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why breeding for one characteristic can worsen another.",
        "options": [
            "Because every allele in a population controls two characteristics at once",
            "Because selecting for a characteristic removes every other gene from the animal",
            "Because a breeder chooses on one characteristic, so the others are not being selected for",
            "Because breeders are careless",
        ],
        "correct_index": 2,
        "why": "Animals chosen only for yield or for looks may be worse in health, temperament or fertility, because nothing was watching those.",
    },
    {
        "id": "ks4-selective-breeding-s18",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a breeder sometimes introduces an animal from an unrelated herd.",
        "options": [
            "To bring in new alleles and reduce inbreeding",
            "To make sure the herd is exactly the same size as it was before",
            "To remove the characteristic that has been selected for over many years",
            "To make the herd more uniform than it already is",
        ],
        "correct_index": 0,
        "why": "Outcrossing restores variation and dilutes the faulty recessive alleles that inbreeding has concentrated.",
    },
    {
        "id": "ks4-selective-breeding-s19",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State why selective breeding is also called artificial selection.",
        "options": [
            "Because the animals produced by it are artificial rather than living organisms",
            "Because a human chooses which individuals breed, rather than the environment",
            "Because the alleles involved are made artificially in a laboratory beforehand",
            "Because it happens only in artificial habitats",
        ],
        "correct_index": 1,
        "why": "The process is natural selection with a human being as the selecting agent.",
    },
    {
        "id": "ks4-selective-breeding-s20",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a breeder breeds from the best of the offspring rather than repeating the original cross.",
        "options": [
            "Because the original parents are always destroyed after the first cross is made",
            "Because the original parents change their alleles after they have bred once",
            "Because offspring are cheaper to keep",
            "Because the best offspring carry a better combination than either parent had",
        ],
        "correct_index": 3,
        "why": "Each generation can combine useful alleles from both parents, so the best offspring exceed either of them.",
    },
    {
        "id": "ks4-selective-breeding-s21",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why selective breeding of a wild species for conservation is risky.",
        "options": [
            "Because a wild species is unable to breed in captivity under any circumstances",
            "Because selective breeding creates new species that cannot live in the wild",
            "Because wild animals have no alleles",
            "Because breeding from few individuals reduces variation",
        ],
        "correct_index": 3,
        "why": "Conservation aims to keep variation, and selecting hard for any characteristic works against that.",
    },
    {
        "id": "ks4-selective-breeding-s22",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what a breeder would do if the desired characteristic did not appear in the offspring.",
        "options": [
            "Insert the allele for the characteristic into the next generation directly",
            "Breed again from the individuals closest to what is wanted",
            "Abandon the programme, because the characteristic can never now appear",
            "Change to a completely different species of animal",
        ],
        "correct_index": 1,
        "why": "Progress is gradual, so the breeder keeps selecting the nearest individuals and repeating the cycle.",
    },
    {
        "id": "ks4-selective-breeding-s23",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why selective breeding needs sexual reproduction.",
        "options": [
            "Because alleles from two parents must be combined",
            "Because asexual reproduction is impossible in any farmed species of animal",
            "Because sexual reproduction produces a far greater number of offspring",
            "Because gametes are cheaper to obtain than cuttings",
        ],
        "correct_index": 0,
        "why": "Cloning preserves what exists; only fertilisation creates the new combinations a breeder is selecting among.",
    },
    {
        "id": "ks4-selective-breeding-s24",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why old crop varieties are kept in seed banks even though they yield less.",
        "options": [
            "Because old varieties are much cheaper to store than modern ones are",
            "Because seed banks are required to keep every variety ever grown",
            "Because they carry alleles that modern varieties have lost",
            "Because old seeds germinate faster",
        ],
        "correct_index": 2,
        "why": "A resistance allele lost from a modern variety may still exist in an old one, and can be bred back in.",
    },
    {
        "id": "ks4-selective-breeding-s25",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a breeder measures the characteristic rather than judging it by eye.",
        "options": [
            "Because measuring changes the alleles that the animal carries for it",
            "Because a measurement identifies the best reliably",
            "Because judging by eye is not permitted in any breeding programme",
            "Because a measurement is quicker than looking at the animal",
        ],
        "correct_index": 1,
        "why": "Small differences decide which animals are chosen, and they are far easier to see in numbers than by eye.",
    },
    {
        "id": "ks4-selective-breeding-s26",
        "subtopic_slug": "selective-breeding",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what selective breeding has done to the appearance of domestic dogs.",
        "options": [
            "It has kept every breed looking exactly like the wolf they descended from",
            "It has made every dog breed identical to every other dog breed",
            "It has had no effect on how a dog looks",
            "It has produced breeds that differ enormously in size and in shape",
        ],
        "correct_index": 3,
        "why": "All breeds descend from the wolf, and the differences between them are the work of selective breeding.",
    },
    {
        "id": "ks4-selective-breeding-h05",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A breeder raises milk yield by 30% in twenty years but fertility falls. Explain what has happened.",
        "options": [
            "The alleles for high yield have changed into alleles that reduce fertility instead",
            "Milk yield and fertility are controlled by exactly the same single gene in cattle",
            "Selection acted only on yield, so alleles harming fertility were carried along unchecked",
            "The fall in fertility has nothing to do with the breeding programme at all",
        ],
        "correct_index": 2,
        "why": "Anything the breeder is not selecting on is free to drift or to decline, which is why breeding goals are now broader.",
    },
    {
        "id": "ks4-selective-breeding-h06",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that selective breeding is more natural than genetic engineering.",
        "options": [
            "It is questionable — both deliberately change a population's alleles, and breeding causes real harm too",
            "It is correct, because selective breeding has no effect on the alleles of a population",
            "It is correct, because genetic engineering has never been used on any organism",
            "It is wrong, because selective breeding is not used by anybody",
        ],
        "correct_index": 0,
        "why": "The methods differ in how alleles are changed, but calling one natural does not make it harmless.",
    },
    {
        "id": "ks4-selective-breeding-h07",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the effect of selective breeding on a population with the effect of natural selection.",
        "options": [
            "Both change allele frequencies, but breeding is faster and narrows variation much more",
            "Breeding changes alleles while natural selection has no effect on them at all",
            "Natural selection is faster than breeding and reduces variation far more sharply",
            "Neither of the two changes the alleles of a population in any way",
        ],
        "correct_index": 0,
        "why": "They are the same mechanism; the human version is stronger, faster and far more costly in variation.",
    },
    {
        "id": "ks4-selective-breeding-h08",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a breeder would use a bull whose daughters yield well rather than one that looks impressive.",
        "options": [
            "Because a bull that looks impressive is likely to be infertile in most cases",
            "Because appearance in cattle is caused entirely by the environment they live in",
            "Because the daughters' yields show which alleles the bull actually passes on",
            "Because a bull cannot be judged by eye at all",
        ],
        "correct_index": 2,
        "why": "A bull produces no milk himself, so his daughters' performance is the only direct evidence of what he carries.",
    },
    {
        "id": "ks4-selective-breeding-h09",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a breeding programme run on a very small population makes little progress.",
        "options": [
            "Because a small population is unable to reproduce sexually at any point",
            "Because the individuals of a small population all carry identical alleles from birth",
            "Because small populations reproduce too quickly for a breeder to keep up",
            "Because a small population loses variation quickly",
        ],
        "correct_index": 3,
        "why": "Selection needs differences, and inbreeding in a small population removes them within a few generations.",
    },
    {
        "id": "ks4-selective-breeding-h10",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the wild ancestor of a crop is valuable to a modern plant breeder.",
        "options": [
            "Because a wild ancestor produces a much larger yield than the modern crop does",
            "Because the wild plant still carries alleles that the crop has lost",
            "Because a wild plant can be grown without any soil being needed at all",
            "Because wild plants have more chromosomes than crops do",
        ],
        "correct_index": 1,
        "why": "Disease resistance lost during domestication can often be bred back in from the wild relative.",
    },
    {
        "id": "ks4-selective-breeding-h11",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a characteristic controlled by many genes is slower to breed for.",
        "options": [
            "Because a characteristic of that kind is not inherited by the offspring at all",
            "Because many genes cannot be passed on together in a single gamete",
            "Because many alleles must be brought together",
            "Because such a characteristic cannot be measured by a breeder",
        ],
        "correct_index": 2,
        "why": "Gathering a favourable combination across many genes takes far more generations than fixing one allele.",
    },
    {
        "id": "ks4-selective-breeding-h12",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a farmer growing several varieties is safer than one growing the best variety alone.",
        "options": [
            "Because a disease that destroys one variety may not destroy the others",
            "Because several varieties together produce a much larger yield in every season",
            "Because growing several varieties removes the need to use any pesticide",
            "Because a single variety cannot be harvested by machine",
        ],
        "correct_index": 0,
        "why": "Mixing varieties restores some of the variation that breeding removed, and limits how far an outbreak can spread.",
    },
    {
        "id": "ks4-selective-breeding-h13",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why some dog breeds have serious breathing problems.",
        "options": [
            "Because dogs of those breeds are not given enough exercise by their owners",
            "Because selection for a flat face has shortened the airway as well",
            "Because those breeds carry a gene taken from a completely different species",
            "Because breathing problems are caught from other dogs",
        ],
        "correct_index": 1,
        "why": "Selecting hard on appearance changed the underlying structure too, and the welfare cost came with it.",
    },
    {
        "id": "ks4-selective-breeding-h14",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a breeding programme is easier in plants than in large mammals.",
        "options": [
            "Because plants carry far fewer alleles than mammals do in their cells",
            "Because plants do not pass any of their characteristics to their offspring",
            "Because a mammal cannot be selected for any characteristic at all",
            "Because plants give many offspring quickly",
        ],
        "correct_index": 3,
        "why": "Short generations and large numbers of offspring let a plant breeder run many more cycles of selection.",
    },
    {
        "id": "ks4-selective-breeding-h15",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why selective breeding cannot give a crop resistance to a brand new disease.",
        "options": [
            "Because a new disease is caused by conditions rather than by any organism",
            "Because a crop plant is unable to inherit resistance from either of its parents",
            "Because resistance alleles cannot be passed between two plants",
            "Because no plant in the population is likely to carry a resistance allele yet",
        ],
        "correct_index": 3,
        "why": "Breeding concentrates existing alleles, so if nothing in the population resists, there is nothing to select.",
    },
    {
        "id": "ks4-selective-breeding-h16",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare what selective breeding and genetic engineering could each do about a new crop disease.",
        "options": [
            "Both of them would have to wait for a resistant plant to appear in the crop",
            "Breeding needs a resistant plant to exist; engineering could bring a gene in from another species",
            "Engineering needs a resistant plant, while breeding can use any species at all",
            "Neither of them could do anything about a new disease",
        ],
        "correct_index": 1,
        "why": "The difference is where the allele may come from, which is exactly why engineering can act when breeding cannot.",
    },
    {
        "id": "ks4-selective-breeding-h17",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the effects of ten thousand years of breeding are visible in a modern farm animal.",
        "options": [
            "Because thousands of generations of strong selection",
            "Because farm animals change their bodies during their own lifetimes to suit farming",
            "Because modern farm animals were created separately from their wild ancestors",
            "Because the animals were genetically engineered in the distant past",
        ],
        "correct_index": 0,
        "why": "Selection compounds over generations, and ten thousand years is a great many generations of it.",
    },
    {
        "id": "ks4-selective-breeding-h18",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a breeder would test a valuable animal's offspring before using it widely.",
        "options": [
            "Because testing the offspring adds new alleles to the animal that produced them",
            "Because an animal that has not been tested is unable to reproduce successfully",
            "Because the offspring reveal any faulty recessive allele the animal is carrying",
            "Because the offspring must be counted before a breeder may sell the parent",
        ],
        "correct_index": 2,
        "why": "A widely used sire can spread a hidden faulty allele through a whole breed before anyone notices.",
    },
    {
        "id": "ks4-selective-breeding-h19",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why breeding for yield alone has been criticised on welfare grounds.",
        "options": [
            "Because an animal bred for high yield produces no offspring of its own",
            "Because animals may be pushed beyond what their bodies comfortably support",
            "Because high-yielding animals are always more expensive for a farmer to keep",
            "Because yield cannot be measured accurately in a farm animal",
        ],
        "correct_index": 1,
        "why": "Very high output can bring lameness, mastitis and reduced lifespan if health is not selected for as well.",
    },
    {
        "id": "ks4-selective-breeding-h20",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a selectively bred variety often performs poorly in a different climate.",
        "options": [
            "Because a bred variety loses its alleles whenever it is moved to a new place",
            "Because climate has no effect on how any crop variety performs in a field",
            "Because a variety can only grow in the country where it was first bred",
            "Because it was selected under other conditions",
        ],
        "correct_index": 3,
        "why": "Selection always fits an organism to the conditions it was selected in, which is why varieties are region-specific.",
    },
    {
        "id": "ks4-selective-breeding-h21",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why modern breeders increasingly use DNA testing alongside measurement.",
        "options": [
            "Because DNA testing changes the alleles of the animal that has been tested",
            "Because a measurement of a characteristic cannot be taken from any animal",
            "Because it reveals the alleles before offspring are born",
            "Because DNA testing is cheaper than keeping written records of a herd",
        ],
        "correct_index": 2,
        "why": "Reading the genotype directly means a breeder need not wait a generation to discover what an animal carries.",
    },
    {
        "id": "ks4-selective-breeding-h22",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the loss of variation from breeding is a problem for the future rather than today.",
        "options": [
            "Because variation only matters once the environment or the diseases change",
            "Because variation has no effect on a population at any point in its history",
            "Because a variety with little variation produces no crop in the present year",
            "Because the problem will be solved without anybody doing anything",
        ],
        "correct_index": 0,
        "why": "A uniform variety performs beautifully until conditions shift, and then there is nothing to fall back on.",
    },
    {
        "id": "ks4-selective-breeding-h23",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why two breeders selecting for the same characteristic may end up with different herds.",
        "options": [
            "Because they start from different animals",
            "Because the characteristic is not inherited in one of the two herds",
            "Because selecting for a characteristic produces a random result every time",
            "Because one of the two breeders must have made a mistake",
        ],
        "correct_index": 0,
        "why": "Selection can only work with what each starting population happens to carry, and those differ.",
    },
    {
        "id": "ks4-selective-breeding-h24",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why selective breeding supported Darwin's argument for natural selection.",
        "options": [
            "Because it proved that characteristics developed during life are inherited",
            "Because it showed that a population can be changed greatly by selecting its parents",
            "Because breeders had already written down the theory of natural selection",
            "Because selective breeding produces entirely new species in one generation",
        ],
        "correct_index": 1,
        "why": "If a breeder can reshape a species in centuries, nature selecting over millions of years can do far more.",
    },
    {
        "id": "ks4-selective-breeding-h25",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a breeding programme should set a target before it begins.",
        "options": [
            "Because a target is required by law before any animals may be bred",
            "Because a target changes the alleles present in the starting population",
            "Because the target decides which count as the best",
            "Because without a target the animals would not reproduce at all",
        ],
        "correct_index": 2,
        "why": "Selection is only as good as the definition of what is being selected for, so the target shapes the outcome.",
    },
    {
        "id": "ks4-selective-breeding-h26",
        "subtopic_slug": "selective-breeding",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that selective breeding has no drawbacks because it has been used for so long.",
        "options": [
            "It is correct, because a practice used for ten thousand years must be safe",
            "It is correct, because no problem has ever been reported by any breeder",
            "It is wrong, because selective breeding has only been used recently",
            "It is unsound — long use does not remove inbreeding, lost variation or welfare problems",
        ],
        "correct_index": 3,
        "why": "How long something has been done says nothing about its costs, and the costs here are well documented.",
    },
]
