"""Biology · Inheritance, Variation and Evolution — the MRB-338 expansion,
subtopic `theory-of-evolution`.

The baseline twelve cover 1859, the pale pre-industrial moth, the name of
the process, Wallace on warning colouration, why the theory was accepted,
the Darwin-against-Wallace question, genetics supplying the mechanism, a
Lamarckian error, a dark-soil island, the clean-air reversal, the twenty-year
delay and the stretched giraffe. This file adds the HISTORY the baseline
keeps gesturing at: Lamarck's theory stated as a theory rather than as an
error; the three reasons Darwin's ideas were only gradually accepted (they
challenged the religious account of creation, the evidence at the time was
thin, and no mechanism of inheritance was known for another fifty years);
the joint presentation of 1858 and Wallace's letter from the Malay
Archipelago; what Darwin actually had as evidence; and what the word
"theory" means in science.

⚠️ `evolution-natural-selection` owns the mechanism itself, and
`evidence-for-evolution` owns the modern evidence. This leaf is about the
people, the ideas and how the scientific community came to accept them.
"""

TOPIC = "inheritance"
SUBJECT = "biology"

QUESTIONS = [
    {
        "id": "ks4-theory-of-evolution-e05",
        "subtopic_slug": "theory-of-evolution",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the scientist who proposed that characteristics developed during life are inherited.",
        "options": [
            "Lamarck",
            "Gregor Mendel, who worked out the rules of inheritance using pea plants in a garden",
            "Rosalind Franklin, whose X-ray images helped reveal the structure of DNA",
            "Carl Woese, who divided living things into three domains",
        ],
        "correct_index": 0,
        "why": "Lamarck's theory was that characteristics an organism develops in its lifetime are passed to its offspring.",
    },
    {
        "id": "ks4-theory-of-evolution-e06",
        "subtopic_slug": "theory-of-evolution",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the islands where Darwin made many of the observations that shaped his thinking.",
        "options": [
            "The British Isles, which he studied carefully for many years after he came home again",
            "Iceland and Greenland, both of which lie a long way to the north",
            "The Galapagos Islands",
            "The Isles of Scilly",
        ],
        "correct_index": 2,
        "why": "Darwin's observations of finches and tortoises in the Galapagos were central to his later thinking.",
    },
    {
        "id": "ks4-theory-of-evolution-e07",
        "subtopic_slug": "theory-of-evolution",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name the region Wallace was working in when he wrote to Darwin about natural selection.",
        "options": [
            "The Arctic Circle, where he had been studying the animals that live on the sea ice",
            "The Sahara Desert, which he crossed on foot while collecting plants and insects",
            "The Antarctic",
            "The Malay Archipelago",
        ],
        "correct_index": 3,
        "why": "Wallace was collecting in the Malay Archipelago when he sent Darwin his own account of natural selection.",
    },
    {
        "id": "ks4-theory-of-evolution-e08",
        "subtopic_slug": "theory-of-evolution",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State the year in which the work of Darwin and Wallace was first presented together.",
        "options": [
            "1953, which is the year in which the structure of DNA was finally worked out",
            "1858",
            "1866, when Mendel published the results of his breeding experiments",
            "2003, when the Human Genome Project published its results",
        ],
        "correct_index": 1,
        "why": "Their papers were read together at the Linnean Society in 1858, a year before Darwin's book appeared.",
    },
    {
        "id": "ks4-theory-of-evolution-e09",
        "subtopic_slug": "theory-of-evolution",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what the word theory means to a scientist.",
        "options": [
            "A guess that somebody has made without collecting any evidence at all beforehand",
            "A rule that has been proved beyond any possibility of doubt whatsoever",
            "An explanation supported by a large body of evidence",
            "An idea that has been shown to be wrong",
        ],
        "correct_index": 2,
        "why": "In science a theory is a well-supported explanation, not a hunch, which is why 'only a theory' misses the point.",
    },
    {
        "id": "ks4-theory-of-evolution-e10",
        "subtopic_slug": "theory-of-evolution",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Give one reason Darwin's theory was only gradually accepted.",
        "options": [
            "It challenged the idea that God made all the living things on Earth",
            "Because it had been published in a language that almost nobody was able to read",
            "Because Darwin refused to let anybody else read the book he had written",
            "Because nobody had heard of Darwin",
        ],
        "correct_index": 0,
        "why": "The theory cut across the religious account of creation accepted by most people at the time.",
    },
    {
        "id": "ks4-theory-of-evolution-e11",
        "subtopic_slug": "theory-of-evolution",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "State how long it was after 1859 before the mechanism of inheritance was understood.",
        "options": [
            "Less than a single year, because Mendel's results appeared almost at the same time",
            "About fifty years",
            "Around five hundred years, which is why the theory is still being argued about",
            "It is still unknown",
        ],
        "correct_index": 1,
        "why": "Mendel's work was not widely known until 1900, so for about fifty years the theory had no mechanism.",
    },
    {
        "id": "ks4-theory-of-evolution-e12",
        "subtopic_slug": "theory-of-evolution",
        "band": "easier",
        "tier": "foundation",
        "triple_only": True,
        "text": "Name one kind of evidence Darwin used to build his argument.",
        "options": [
            "DNA sequences taken from many different species and compared with one another",
            "The results of the experiments that Mendel had carried out on his pea plants",
            "Photographs of fossils",
            "The way farmers bred animals to change them",
        ],
        "correct_index": 3,
        "why": "Darwin used selective breeding as an argument by analogy: if breeders can change a species, nature can too.",
    },
    {
        "id": "ks4-theory-of-evolution-s05",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Describe what Lamarck's theory said would happen to the offspring of a blacksmith.",
        "options": [
            "They would inherit nothing from their father, since he was not born with strong arms",
            "They would be born with weaker arms than their father",
            "They would need to become blacksmiths too",
            "They would inherit the strong arms their father had developed through his work",
        ],
        "correct_index": 3,
        "why": "Lamarck held that characteristics gained during a parent's life are passed on, which is why the blacksmith is the standard example.",
    },
    {
        "id": "ks4-theory-of-evolution-s06",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why Lamarck's theory is rejected today.",
        "options": [
            "Because Lamarck published his ideas long before Darwin published any of his own work",
            "Because changes to the body never change the DNA in the gametes",
            "Because Lamarck studied only plants",
            "Because his theory was too complicated",
        ],
        "correct_index": 1,
        "why": "Only the genetic material in gametes is inherited, so a characteristic developed by use cannot be passed on.",
    },
    {
        "id": "ks4-theory-of-evolution-s07",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "State the title of the book in which Darwin set out his theory.",
        "options": [
            "On the Origin of Species",
            "The Voyage of the Beagle, which described the journey he had made round the world",
            "Experiments on Plant Hybridisation, the paper on seven pea characteristics",
            "The Malay Archipelago, an account of eight years of collecting",
        ],
        "correct_index": 0,
        "why": "On the Origin of Species, published in 1859, is where the theory of natural selection was set out in full.",
    },
    {
        "id": "ks4-theory-of-evolution-s08",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why Darwin could not say how variation arose in a population.",
        "options": [
            "Because he had not collected enough specimens on his voyage to be able to judge",
            "Because he believed variation could not exist",
            "Because genes, alleles and mutation were never known in his lifetime",
            "Because he never saw a living population",
        ],
        "correct_index": 2,
        "why": "The physical basis of inheritance was discovered decades later, so Darwin could describe variation but not explain it.",
    },
    {
        "id": "ks4-theory-of-evolution-s09",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Describe what Wallace sent to Darwin in 1858.",
        "options": [
            "A collection of fossils he had dug out of the rocks of the Malay Archipelago",
            "An essay setting out natural selection",
            "A set of pea plants grown from seed gathered while he was travelling",
            "A request for money",
        ],
        "correct_index": 1,
        "why": "Wallace had arrived independently at the same idea, and his essay is what prompted the joint presentation.",
    },
    {
        "id": "ks4-theory-of-evolution-s10",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why the evidence available in 1859 was not enough to convince everyone.",
        "options": [
            "Because all of the evidence of the time had been collected by Darwin and Wallace alone",
            "Because no scientist in 1859 had any way of collecting evidence at all",
            "Because the evidence was secret",
            "There was little fossil evidence and no account of inheritance",
        ],
        "correct_index": 3,
        "why": "The fossil record was thin, transitional forms were few, and the mechanism of inheritance was unknown.",
    },
    {
        "id": "ks4-theory-of-evolution-s11",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why the rediscovery of Mendel's work strengthened Darwin's theory.",
        "options": [
            "Because it showed that Darwin had been right about the age of the Earth as well",
            "Because Mendel had worked on the same species",
            "It explained how variation is passed on unchanged between generations",
            "Because it made the theory simpler",
        ],
        "correct_index": 2,
        "why": "Mendel's units solved the problem of how a favourable characteristic could be inherited without being diluted away.",
    },
    {
        "id": "ks4-theory-of-evolution-s12",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Describe how Darwin used pigeon breeding in his argument.",
        "options": [
            "He argued that if breeders can change pigeons, nature can change species too",
            "He used pigeons to show that characteristics gained in life are inherited",
            "He bred pigeons to prove that all birds share an ancestor",
            "He kept pigeons as pets",
        ],
        "correct_index": 0,
        "why": "Selective breeding gave Darwin a visible, familiar example of a population being changed by selection.",
    },
    {
        "id": "ks4-theory-of-evolution-s13",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what Wallace is best remembered for besides co-discovering natural selection.",
        "options": [
            "His work on warning colouration",
            "Discovering the structure of the DNA molecule with the help of X-ray images",
            "Writing the first classification system",
            "Sailing on HMS Beagle",
        ],
        "correct_index": 0,
        "why": "Wallace pioneered work on warning colouration and did important work on speciation and animal distribution.",
    },
    {
        "id": "ks4-theory-of-evolution-s14",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why a scientist would object to the phrase only a theory.",
        "options": [
            "Because a scientist never uses the word theory to describe anything at all",
            "Because a theory has been proved finally",
            "Because a theory in science is not a guess but an explanation backed by evidence",
            "Because theories are always right",
        ],
        "correct_index": 2,
        "why": "The everyday meaning of theory is a hunch; the scientific meaning is a well-tested explanation.",
    },
    {
        "id": "ks4-theory-of-evolution-s15",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what Darwin observed about the finches he saw on different islands.",
        "options": [
            "That every island had exactly the same kind of finch living on it as the others",
            "That the finches of each island could not feed themselves properly",
            "That the finches migrated yearly",
            "Their beaks differed and suited the food available",
        ],
        "correct_index": 3,
        "why": "Beak shape matching the local food supply is the observation that pointed towards selection.",
    },
    {
        "id": "ks4-theory-of-evolution-s16",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why Darwin spent twenty years gathering evidence before publishing.",
        "options": [
            "Because printing a book took twenty years to organise at that time",
            "Because he knew the idea would be strongly opposed and wanted his case to be solid",
            "Because he was waiting for Wallace's essay",
            "Because he had lost his notes",
        ],
        "correct_index": 1,
        "why": "Darwin understood how controversial the idea would be, and gathered evidence accordingly.",
    },
    {
        "id": "ks4-theory-of-evolution-s17",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Describe what finally prompted Darwin to publish in 1859.",
        "options": [
            "The discovery that DNA carries the genetic information of every living organism",
            "A request from the Linnean Society",
            "Wallace's essay",
            "Mendel's results",
        ],
        "correct_index": 2,
        "why": "Receiving Wallace's independent account made delaying publication impossible.",
    },
    {
        "id": "ks4-theory-of-evolution-s18",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what Lamarck and Darwin agreed about, even though their theories differed.",
        "options": [
            "That species change over time rather than staying fixed",
            "That characteristics developed during a lifetime are passed on to the offspring",
            "That new species never change at all",
            "That inheritance works through units",
        ],
        "correct_index": 0,
        "why": "Both rejected the idea that species are fixed; they disagreed about how the change happens.",
    },
    {
        "id": "ks4-theory-of-evolution-s19",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why the theory of evolution is still called a theory today.",
        "options": [
            "Because scientists have not yet found any evidence at all to support the idea",
            "Because a theory is what a well-supported scientific explanation is called",
            "Because Darwin's own title has to be kept",
            "Because it may soon be shown wrong",
        ],
        "correct_index": 1,
        "why": "Calling it a theory is a statement of its status as a tested explanation, not a doubt about it.",
    },
    {
        "id": "ks4-theory-of-evolution-s20",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why the work of Darwin and Wallace was read out together rather than separately.",
        "options": [
            "Because the Linnean Society would only accept a paper written by two scientists",
            "Because the two men had carried out all of their work side by side",
            "Because the meeting was short",
            "So that both were credited for the same idea",
        ],
        "correct_index": 3,
        "why": "The joint reading was a way of giving both men credit without either losing priority.",
    },
    {
        "id": "ks4-theory-of-evolution-s21",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Describe how geology influenced Darwin's thinking about the age of the Earth.",
        "options": [
            "It showed him the Earth had formed only a few thousand years earlier",
            "It proved rocks form in a single event",
            "It had no influence at all",
            "It suggested a far older Earth",
        ],
        "correct_index": 3,
        "why": "Slow geological change over vast time gave Darwin the long timescale that natural selection needs.",
    },
    {
        "id": "ks4-theory-of-evolution-s22",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what Darwin proposed that all species had descended from.",
        "options": [
            "A small number of large animals that lived in the sea a very long time ago",
            "Simple life forms and a common ancestor",
            "The species that are still alive on the Earth today",
            "Nothing at all",
        ],
        "correct_index": 1,
        "why": "Descent with modification from common ancestors is the core claim of the theory.",
    },
    {
        "id": "ks4-theory-of-evolution-s23",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why the theory of evolution is accepted by scientists today.",
        "options": [
            "Because a great deal of independent evidence has supported it since 1859",
            "Because Darwin was a famous man whose books were widely read at the time",
            "Because nobody has ever tested it",
            "Because it is taught in schools",
        ],
        "correct_index": 0,
        "why": "Fossils, genetics, DNA comparison and directly observed evolution have all supported it since.",
    },
    {
        "id": "ks4-theory-of-evolution-s24",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "State what Darwin's theory says happens to individuals better suited to their environment.",
        "options": [
            "They change their own bodies during life to suit the environment even better",
            "They move to a habitat that suits them less",
            "They breed more and pass on their alleles",
            "They stop reproducing",
        ],
        "correct_index": 2,
        "why": "Differential survival and reproduction is the whole of the mechanism Darwin proposed.",
    },
    {
        "id": "ks4-theory-of-evolution-s25",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why some opposition to Darwin's theory was not scientific in nature.",
        "options": [
            "Because the book he wrote was extremely expensive to buy at that time",
            "Because it conflicted with beliefs many people held about how life came to exist",
            "Because Darwin had never travelled at all",
            "Because no scientist knew him",
        ],
        "correct_index": 1,
        "why": "Much of the opposition was religious and social rather than a dispute about evidence.",
    },
    {
        "id": "ks4-theory-of-evolution-s26",
        "subtopic_slug": "theory-of-evolution",
        "band": "standard",
        "tier": "foundation",
        "triple_only": True,
        "text": "Describe what happened to the number of dark peppered moths during the Industrial Revolution.",
        "options": [
            "It stayed exactly the same, because moth colour is not an inherited characteristic",
            "It fell steadily, because soot made dark moths easier for birds to spot",
            "It fell to zero everywhere",
            "It rose, because soot darkened the bark and hid them",
        ],
        "correct_index": 3,
        "why": "Soot-blackened bark made the dark form better camouflaged, so more of them survived to breed.",
    },
    {
        "id": "ks4-theory-of-evolution-h05",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Compare Lamarck's explanation of the giraffe's neck with Darwin's explanation.",
        "options": [
            "Both of them said individual giraffes stretch their necks and pass the change on",
            "Lamarck said longer necks were selected",
            "Lamarck said stretching in life was inherited; Darwin said longer-necked individuals survived better",
            "Neither wrote about giraffes",
        ],
        "correct_index": 2,
        "why": "The two theories explain the same observation in opposite ways: change during life against selection of existing variation.",
    },
    {
        "id": "ks4-theory-of-evolution-h06",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why Darwin's theory could not be fully tested in his own lifetime.",
        "options": [
            "Because the technology to compare DNA did not exist for another century",
            "Because no scientist of the time was interested in testing anything that he wrote",
            "Because he allowed nobody to see his evidence",
            "Because it made no predictions",
        ],
        "correct_index": 0,
        "why": "The strongest tests — genetics, molecular comparison, observed evolution — all became possible long after his death.",
    },
    {
        "id": "ks4-theory-of-evolution-h07",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Evaluate the claim that Wallace deserves equal credit with Darwin.",
        "options": [
            "There is a case for it — he reached the idea independently — but Darwin had far more evidence",
            "It is wrong, because Wallace played no part in developing the idea",
            "It is correct, because they worked together for years",
            "Credit does not matter in science",
        ],
        "correct_index": 0,
        "why": "Both arrived at natural selection; the difference was the twenty years of evidence Darwin could set beside it.",
    },
    {
        "id": "ks4-theory-of-evolution-h08",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why a theory with no known mechanism is harder for scientists to accept.",
        "options": [
            "Because a theory without a mechanism cannot be written down in a scientific paper",
            "Because scientists are interested only in mechanisms and never in explanations",
            "Because it says what happens but not how",
            "Because mechanisms are required by law",
        ],
        "correct_index": 2,
        "why": "Darwin could show that populations change but not what carried the change, which left a real gap in the argument.",
    },
    {
        "id": "ks4-theory-of-evolution-h09",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why the peppered moth is used so often as an example of Darwin's theory.",
        "options": [
            "Because moths are the only animals on which natural selection has ever been shown to act",
            "Because Darwin studied the moths himself",
            "Because the moths are easy to catch",
            "Because the change was seen within a human lifetime and its cause was clear",
        ],
        "correct_index": 3,
        "why": "The rise and fall of the dark form tracks a measurable change in the environment, which makes it a very clean case.",
    },
    {
        "id": "ks4-theory-of-evolution-h10",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why Darwin's use of selective breeding was a powerful argument in 1859.",
        "options": [
            "Because selective breeding produces a brand new species in a single generation",
            "Because readers could see for themselves that selection changes a population",
            "Because farmers in 1859 had never seen an animal change in any way",
            "Because breeding was a new idea",
        ],
        "correct_index": 1,
        "why": "Every farmer already knew that choosing parents changes a herd; Darwin only had to argue that nature does the choosing.",
    },
    {
        "id": "ks4-theory-of-evolution-h11",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why Lamarck's theory seemed reasonable to many people at the time.",
        "options": [
            "Because Lamarck had produced far more evidence than Darwin produced",
            "Because no other theory existed in Europe",
            "Because it fitted the everyday observation that use strengthens a part of the body",
            "Because it had been proved by experiment",
        ],
        "correct_index": 2,
        "why": "Muscles do grow with use, so the idea that such gains are passed on is an easy step to take without genetics.",
    },
    {
        "id": "ks4-theory-of-evolution-h12",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Compare the amount of evidence Darwin had in 1859 with the evidence available now.",
        "options": [
            "Darwin had observations, fossils and breeding; today there is also genetics and DNA comparison",
            "Darwin had far more evidence than scientists have available to them today",
            "The evidence has not changed since he wrote",
            "There is no evidence either way",
        ],
        "correct_index": 0,
        "why": "The theory has been tested by kinds of evidence Darwin could not have imagined, and it has survived all of them.",
    },
    {
        "id": "ks4-theory-of-evolution-h13",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why scientists do not simply say the theory of evolution has been proved.",
        "options": [
            "Because there is still very little evidence supporting the theory",
            "Because a scientific explanation always remains open to testing against new evidence",
            "Because the word proof is banned in science",
            "Because Darwin asked them not to",
        ],
        "correct_index": 1,
        "why": "Science supports explanations with evidence rather than proving them; being open to testing is a strength, not a doubt.",
    },
    {
        "id": "ks4-theory-of-evolution-h14",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why the discovery of DNA in the twentieth century mattered to Darwin's theory.",
        "options": [
            "Because it showed that Darwin had been wrong about how species change over time",
            "Because it proved acquired characteristics are inherited",
            "Because it made fossils unnecessary",
            "It identified what actually carries inherited variation between generations",
        ],
        "correct_index": 3,
        "why": "DNA supplied the physical basis for the units of inheritance the theory had needed since 1859.",
    },
    {
        "id": "ks4-theory-of-evolution-h15",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "A student says Darwin proved evolution by watching species change. Evaluate this.",
        "options": [
            "It is correct, because Darwin watched a species change during his voyage on the Beagle",
            "It is correct, because selection acts quickly enough to be seen in one lifetime",
            "It is wrong, because he made no observations",
            "It is wrong — he inferred it, since the change is far too slow to watch",
        ],
        "correct_index": 3,
        "why": "Darwin's argument was an inference from many lines of evidence, not a direct observation of one species changing.",
    },
    {
        "id": "ks4-theory-of-evolution-h16",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why Wallace is less well known than Darwin outside science.",
        "options": [
            "Because Wallace never actually agreed with the theory of natural selection at all",
            "Because Darwin published the detailed book that carried the argument to the public",
            "Because Wallace told nobody his ideas",
            "Because Wallace died very young",
        ],
        "correct_index": 1,
        "why": "On the Origin of Species was the work that reached a wide public, and the theory took its author's name.",
    },
    {
        "id": "ks4-theory-of-evolution-h17",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why two scientists reaching the same idea independently strengthens that idea.",
        "options": [
            "Because two people working on their own are unlikely to make the very same mistake",
            "Because an idea becomes correct as soon as two people agree about it",
            "Because two authors are required for publication",
            "Because it doubles the evidence",
        ],
        "correct_index": 0,
        "why": "Independent arrival at the same conclusion from different evidence is a check against one person's error or bias.",
    },
    {
        "id": "ks4-theory-of-evolution-h18",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why opposition to Darwin's theory did not stop scientists from testing it.",
        "options": [
            "Because scientists are required to ignore what anybody outside science happens to think",
            "Because opposition had disappeared entirely within a year of publication",
            "Because an idea is judged on evidence, not on how popular it is",
            "Because the theory was easy to test",
        ],
        "correct_index": 2,
        "why": "How welcome an idea is has no bearing on whether the evidence supports it, and the evidence kept accumulating.",
    },
    {
        "id": "ks4-theory-of-evolution-h19",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why Darwin's long timescale depended on the work of geologists.",
        "options": [
            "Because geologists had shown that the Earth was only a few thousand years old",
            "Natural selection needs vast time, and geology showed the Earth was very old",
            "Because geologists alone would listen to him",
            "Because rocks contain no fossils",
        ],
        "correct_index": 1,
        "why": "Slow accumulation of small changes is only possible if there has been an enormous amount of time for it.",
    },
    {
        "id": "ks4-theory-of-evolution-h20",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why a scientific theory can be modified without being abandoned.",
        "options": [
            "Because a theory is never allowed to be changed once it has been published anywhere",
            "Because only the details of a theory are ever supported by evidence",
            "Because theories are never wrong",
            "Because new evidence may refine parts of it while supporting its central explanation",
        ],
        "correct_index": 3,
        "why": "Adding genetics to Darwin's theory changed and strengthened it without overturning natural selection.",
    },
    {
        "id": "ks4-theory-of-evolution-h21",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why the fifty-year gap before Mendel's work was rediscovered mattered so much.",
        "options": [
            "Because scientists stopped studying living organisms during that time",
            "Because Darwin's book was out of print",
            "Because the theory had no account of how variation arose or how it was passed on",
            "Because Mendel refused to publish",
        ],
        "correct_index": 2,
        "why": "That gap is exactly why the theory was accepted slowly: its central process had no known cause.",
    },
    {
        "id": "ks4-theory-of-evolution-h22",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Compare what Darwin could explain with what Lamarck's theory could not.",
        "options": [
            "Darwin could explain why a characteristic that is never used still appears in the offspring",
            "Lamarck could explain variation while Darwin could explain nothing",
            "Both explained the same observations equally well",
            "Neither theory explained anything",
        ],
        "correct_index": 0,
        "why": "Lamarck's theory requires use; Darwin's needs only inherited variation, so it covers cases where nothing was used.",
    },
    {
        "id": "ks4-theory-of-evolution-h23",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why Darwin's theory is described as one of the most important ideas in biology.",
        "options": [
            "Because it explains the whole diversity of life through one mechanism",
            "Because it was the first scientific idea that anybody in biology had ever written down",
            "Because it took the longest to be accepted",
            "Because Darwin travelled a long way",
        ],
        "correct_index": 0,
        "why": "One mechanism accounts for adaptation, diversity and the relatedness of every species, which is why it organises the whole subject.",
    },
    {
        "id": "ks4-theory-of-evolution-h24",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Explain why Wallace's warning colouration idea fits natural selection.",
        "options": [
            "Because bright colours are developed by an animal during the course of its own life",
            "A bright colour predators avoid raises survival, so the allele spreads",
            "Because a predator learns to choose the brightest prey it can find",
            "Because colours are not inherited",
        ],
        "correct_index": 1,
        "why": "The colour only works because predators avoid it, which is a survival advantage and therefore selectable.",
    },
    {
        "id": "ks4-theory-of-evolution-h25",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Suggest why Darwin's theory made predictions that could be tested after his death.",
        "options": [
            "Because he predicted the exact date on which each new fossil would be discovered",
            "Because his theory said nothing about what anyone might find later",
            "Because it implied there must be transitional fossils and a mechanism of inheritance",
            "Because he wrote a second book",
        ],
        "correct_index": 2,
        "why": "A theory that says what ought to exist can be tested by going to look, and transitional fossils were duly found.",
    },
    {
        "id": "ks4-theory-of-evolution-h26",
        "subtopic_slug": "theory-of-evolution",
        "band": "harder",
        "tier": "foundation",
        "triple_only": True,
        "text": "Evaluate the view that Darwin's theory was accepted simply because it was fashionable.",
        "options": [
            "It is correct, because scientific ideas are always accepted according to fashion",
            "It is correct, because it was accepted at once",
            "It is wrong, because it was never accepted",
            "It is wrong — it was accepted as independent evidence from several fields accumulated",
        ],
        "correct_index": 3,
        "why": "Acceptance was slow and followed the evidence: genetics, DNA, fossils and observed change all pointed the same way.",
    },
]
