"""Biology · Inheritance, Variation and Evolution — the MRB-338 expansion,
subtopic `evolution-natural-selection`.

The baseline twelve cover the definition of evolution, the Beagle, Wallace,
selection acting on existing variation, the Lamarckian giraffe, extinction
despite selection, high against low variation, a beetle population, rabbits
and a faster predator, why an individual does not evolve, why a
characteristic must be inherited and Wallace's work on distribution. This
file sets out the MECHANISM as a sequence — variation, competition for
resources, survival of those best suited, and their alleles becoming more
common — which the baseline uses but never states. It adds selection
pressure with named examples, what "best adapted" does and does not mean,
the three-billion-year timescale from simple life forms, and the
specification's definition of a new species: two populations that can no
longer interbreed to produce fertile offspring.

⚠️ `theory-of-evolution` owns Darwin, Wallace, Lamarck and the peppered
moth as history; `evidence-for-evolution` owns fossils and DNA as evidence;
`resistant-bacteria` owns antibiotic resistance. This leaf is the mechanism
itself.
"""

TOPIC = "inheritance"
SUBJECT = "biology"

QUESTIONS = [
    {
        "id": "ks4-evolution-natural-selection-e05",
        "subtopic_slug": "evolution-natural-selection",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State the first requirement for natural selection to act on a population.",
        "options": [
            "There must be variation between the individuals",
            "Every individual in the population must be genetically identical to all of the others",
            "The environment must stay exactly the same throughout",
            "There must be only one individual",
        ],
        "correct_index": 0,
        "why": "Selection can only favour some individuals over others if the individuals differ in the first place.",
    },
    {
        "id": "ks4-evolution-natural-selection-e06",
        "subtopic_slug": "evolution-natural-selection",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what individuals in a population compete for.",
        "options": [
            "Nothing at all, because there is always more than enough of everything to go round",
            "The chance to change their own alleles to suit conditions",
            "Resources such as food, water, space and mates",
            "A place in the classification system",
        ],
        "correct_index": 2,
        "why": "Resources are limited, so not every individual born can survive and reproduce.",
    },
    {
        "id": "ks4-evolution-natural-selection-e07",
        "subtopic_slug": "evolution-natural-selection",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happens to the alleles of the individuals that survive and reproduce.",
        "options": [
            "They are lost at the end of the individual's lifetime",
            "They change into different alleles before being passed on to the next generation",
            "They are destroyed by the others",
            "They are passed on and become more common",
        ],
        "correct_index": 3,
        "why": "Survivors breed, so the alleles that helped them survive appear more often in the next generation.",
    },
    {
        "id": "ks4-evolution-natural-selection-e08",
        "subtopic_slug": "evolution-natural-selection",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe the kind of thing that counts as a selection pressure.",
        "options": [
            "The weight of an organism pressing down on the ground that it happens to be standing on",
            "Something in the environment that makes some individuals likelier to survive",
            "The effort a population makes to change itself so that it suits its conditions better",
            "A measure of how many individuals a population contains at one particular moment",
        ],
        "correct_index": 1,
        "why": "Predators, disease, climate and competition for food are all selection pressures.",
    },
    {
        "id": "ks4-evolution-natural-selection-e09",
        "subtopic_slug": "evolution-natural-selection",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give one example of a selection pressure acting on a population of birds.",
        "options": [
            "The scientific name given to the species of bird",
            "The number of feathers that each individual bird happens to have on its wings",
            "A shortage of the seeds they feed on",
            "The colour of the sky above",
        ],
        "correct_index": 2,
        "why": "A food shortage means only the birds best able to find or handle food survive to breed.",
    },
    {
        "id": "ks4-evolution-natural-selection-e10",
        "subtopic_slug": "evolution-natural-selection",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State roughly how long life on Earth has been evolving.",
        "options": [
            "About three billion years",
            "About three hundred years, which is the time since natural selection was first described",
            "About sixty-six million years, which is the time since the dinosaurs became extinct",
            "About ten thousand years, which is the time since farming first began in the world",
        ],
        "correct_index": 0,
        "why": "Life has been evolving from simple beginnings for about three billion years.",
    },
    {
        "id": "ks4-evolution-natural-selection-e11",
        "subtopic_slug": "evolution-natural-selection",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what all life on Earth is thought to have evolved from.",
        "options": [
            "Several thousand different kinds of complex organism that all appeared at the same time",
            "Simple life forms",
            "The organisms that are alive on the Earth at the present day and nothing else besides",
            "A group of large animals that lived in the sea before any land animals had appeared",
        ],
        "correct_index": 1,
        "why": "The theory holds that all species have descended from simple life forms present about three billion years ago.",
    },
    {
        "id": "ks4-evolution-natural-selection-e12",
        "subtopic_slug": "evolution-natural-selection",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what the phrase best adapted means in the study of natural selection.",
        "options": [
            "The largest and strongest individuals present",
            "The individuals that live for the longest time without ever producing any offspring",
            "Those born earliest in the year",
            "Best suited to the conditions there",
        ],
        "correct_index": 3,
        "why": "Being best adapted means fitting the particular conditions, which may have nothing to do with size or strength.",
    },
    {
        "id": "ks4-evolution-natural-selection-s05",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Put the stages of natural selection in the right order.",
        "options": [
            "Competition first, then the alleles becoming more common, then variation appearing last of all",
            "The alleles become more common, then variation appears, and only then is there competition",
            "Survival first, then variation appears, and competition between the individuals comes last",
            "Variation, competition, survival of those best suited, their alleles becoming more common",
        ],
        "correct_index": 3,
        "why": "Variation must exist before competition can sort it, and only then do the successful alleles spread.",
    },
    {
        "id": "ks4-evolution-natural-selection-s06",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why natural selection cannot act on a characteristic caused only by the environment.",
        "options": [
            "Because a characteristic of that kind is far too small to make any difference to survival",
            "Because it is not controlled by alleles, so it can never be passed on",
            "Because the environment changes too quickly",
            "Because only animals have characteristics caused by their environment",
        ],
        "correct_index": 1,
        "why": "Selection changes a population only by changing which alleles are passed on, so the characteristic must be inherited.",
    },
    {
        "id": "ks4-evolution-natural-selection-s07",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State when two populations of one species are counted as two separate species.",
        "options": [
            "When they can no longer interbreed to produce fertile offspring",
            "When they live in two different countries",
            "As soon as the individuals of the two populations look noticeably different from each other",
            "When one of the two populations has grown much larger than the other",
        ],
        "correct_index": 0,
        "why": "The specification's test is fertile offspring: once that fails, the two populations are separate species.",
    },
    {
        "id": "ks4-evolution-natural-selection-s08",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what happens to two populations of one species that become separated for a very long time.",
        "options": [
            "They stay exactly the same as each other, because they began as members of one species",
            "They both die out, since a population that is separated cannot survive on its own",
            "Different mutations and different conditions make them gradually more different",
            "They swap alleles across the barrier that separates them, so they remain identical",
        ],
        "correct_index": 2,
        "why": "With no interbreeding, separate mutations and separate selection pressures push the two apart.",
    },
    {
        "id": "ks4-evolution-natural-selection-s09",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why natural selection usually takes many generations to change a population.",
        "options": [
            "Because the alleles themselves take many years to change into different ones",
            "Because an allele spreads only as its carriers reproduce, which takes a generation each time",
            "Because every individual has to change during the course of its own lifetime first",
            "Because the environment takes many generations to apply a selection pressure at all",
        ],
        "correct_index": 1,
        "why": "The frequency of an allele can only shift when offspring are produced, so change is measured in generations.",
    },
    {
        "id": "ks4-evolution-natural-selection-s10",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a strong individual may still leave no offspring at all.",
        "options": [
            "Because strength is the only characteristic that natural selection is able to act upon",
            "Because a strong individual always dies before it is old enough to reproduce",
            "Because strong individuals produce gametes that are unable to take part in fertilisation",
            "Because being strong is of no use if it is not suited to the conditions of that habitat",
        ],
        "correct_index": 3,
        "why": "What counts is suitability to the conditions; strength only matters where strength is what the conditions reward.",
    },
    {
        "id": "ks4-evolution-natural-selection-s11",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe the effect on a population of a selection pressure that suddenly becomes stronger.",
        "options": [
            "Nothing changes in the population, since a selection pressure has no effect on survival",
            "Every individual in the population changes to suit the new conditions",
            "A smaller proportion survive, and those that do are the best suited",
            "The population becomes genetically identical at once",
        ],
        "correct_index": 2,
        "why": "A stronger pressure means a harder filter, so the population shifts faster towards the favoured alleles.",
    },
    {
        "id": "ks4-evolution-natural-selection-s12",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happens to an allele that makes its carriers less likely to survive.",
        "options": [
            "It becomes rarer over the generations",
            "It becomes more common, because the population needs every allele that it carries",
            "It changes into a different allele that helps its carriers survive the conditions better",
            "It stays at exactly the same frequency in the population from one generation to the next",
        ],
        "correct_index": 0,
        "why": "Fewer carriers survive to breed, so fewer copies of the allele appear in the next generation.",
    },
    {
        "id": "ks4-evolution-natural-selection-s13",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a population living on an island may evolve differently from one on the mainland.",
        "options": [
            "Because they are isolated, so different alleles and pressures act on each",
            "Because an island population contains more individuals",
            "Because the individuals on an island are unable to reproduce sexually with one another",
            "Because island populations have a greater number of chromosomes in each cell",
        ],
        "correct_index": 0,
        "why": "No interbreeding between the two means the changes in each population are independent.",
    },
    {
        "id": "ks4-evolution-natural-selection-s14",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest what would happen to a well-adapted population if its climate changed sharply.",
        "options": [
            "Nothing at all would happen, because the population is already well adapted to its habitat",
            "Every individual would change during its own lifetime in order to suit the new climate",
            "The alleles that suited the old climate would become less useful, and the population may decline",
            "The population would move to another habitat without any of its alleles changing at all",
        ],
        "correct_index": 2,
        "why": "Being well adapted is always adaptation to particular conditions; change the conditions and the advantage is gone.",
    },
    {
        "id": "ks4-evolution-natural-selection-s15",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what a finch's beak shape tells a biologist about the island it lives on.",
        "options": [
            "Nothing at all, because the shape of a beak is not affected by anything in the habitat",
            "That the island has been separated from every other island for many thousands of years",
            "That the bird is more closely related to the finches on other islands than to its neighbours",
            "Something about the food available there",
        ],
        "correct_index": 3,
        "why": "Beak shape is selected by what the birds have to eat, so different food supplies give different beaks.",
    },
    {
        "id": "ks4-evolution-natural-selection-s16",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why natural selection does not produce a perfect organism.",
        "options": [
            "Because natural selection acts on individuals, not populations",
            "It can only work on the variation that happens to be present",
            "Because the organisms reproduce too slowly",
            "Because every mutation that occurs in a population is harmful to the organism carrying it",
        ],
        "correct_index": 1,
        "why": "Selection has no foresight and no design; it can only favour what chance has already supplied.",
    },
    {
        "id": "ks4-evolution-natural-selection-s17",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State which unit of biology natural selection changes over time.",
        "options": [
            "A single individual organism, which changes gradually over the course of its own lifetime",
            "One cell of an organism's body, which becomes better suited as the organism grows older",
            "The whole population",
            "The non-living parts of the habitat, which are altered by the organisms that live in it",
        ],
        "correct_index": 2,
        "why": "Individuals do not evolve; what changes is which alleles are common in the population.",
    },
    {
        "id": "ks4-evolution-natural-selection-s18",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a species with a very short generation time can evolve quickly.",
        "options": [
            "Because many generations pass in a short time, so allele frequencies shift quickly",
            "Because a species of that kind has a much greater number of alleles than others do",
            "Because each of its individuals lives long enough to change during its own lifetime",
            "Because short-lived organisms are not affected by any selection pressure at all",
        ],
        "correct_index": 0,
        "why": "Evolution is measured in generations, so a species that turns over generations fast can change fast.",
    },
    {
        "id": "ks4-evolution-natural-selection-s19",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a mountain range can lead to two species forming from one.",
        "options": [
            "Because a mountain range changes the alleles carried by the animals that cross it",
            "It separates the populations, so they no longer interbreed and drift apart",
            "Because the air on a mountain range causes a large number of harmful mutations",
            "Because the animals on each side of a mountain range eat exactly the same food",
        ],
        "correct_index": 1,
        "why": "Isolation stops alleles being shared, and separate mutation and selection then push the two apart.",
    },
    {
        "id": "ks4-evolution-natural-selection-s20",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a biologist measures to show that a population has evolved.",
        "options": [
            "The total number of individuals present",
            "The size of the individuals, which increases as it evolves",
            "The length of time that the average individual of the population manages to live for",
            "A change in how common an inherited characteristic is",
        ],
        "correct_index": 3,
        "why": "Evolution is a change in the inherited characteristics of a population, so that is what has to be measured.",
    },
    {
        "id": "ks4-evolution-natural-selection-s21",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why an allele that is useful in one habitat may be useless in another.",
        "options": [
            "Because an allele changes into a different one when an organism moves somewhere new",
            "Because an allele is only able to work in the habitat in which it first appeared",
            "Because every habitat applies exactly the same selection pressure to its organisms",
            "Because the usefulness of an allele depends on the conditions the organism meets",
        ],
        "correct_index": 3,
        "why": "There is no such thing as a generally useful allele, only one that suits a particular set of conditions.",
    },
    {
        "id": "ks4-evolution-natural-selection-s22",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a new predator arriving in a habitat is a powerful selection pressure.",
        "options": [
            "Because a predator changes the alleles carried by the animals that it hunts for food",
            "It kills many prey, so only those that escape it go on to breed",
            "Because a new predator increases the number of prey in the habitat",
            "Because a predator makes the prey grow larger",
        ],
        "correct_index": 1,
        "why": "A heavy death rate concentrated on one kind of individual shifts allele frequencies very quickly.",
    },
    {
        "id": "ks4-evolution-natural-selection-s23",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe where the variation that natural selection acts on originally comes from.",
        "options": [
            "From mutation, and from the shuffling of alleles in sexual reproduction",
            "From the conditions that each individual organism happens to grow up in during its life",
            "From the deliberate choices made by the organisms",
            "From the food that the parents of each individual ate before it was born",
        ],
        "correct_index": 0,
        "why": "Mutation supplies new alleles and sexual reproduction supplies new combinations of them.",
    },
    {
        "id": "ks4-evolution-natural-selection-s24",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what would happen to natural selection if every individual in a population were identical.",
        "options": [
            "It would act more strongly, because the whole population would be equally well suited",
            "It would act only on the youngest individuals of the population and on none of the others",
            "It could not change the population",
            "It would create new variation in the population in order to give itself something to act on",
        ],
        "correct_index": 2,
        "why": "With nothing to choose between, survival would be random and no allele would become commoner.",
    },
    {
        "id": "ks4-evolution-natural-selection-s25",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why competition is an essential part of natural selection.",
        "options": [
            "Because it is the way in which organisms decide which will reproduce next",
            "Because resources are limited, so not all the young produced can survive",
            "Because competition creates the variation",
            "Because without it there is no competition between the alleles of a single individual",
        ],
        "correct_index": 1,
        "why": "If every offspring survived, nothing would be selected and allele frequencies would not change.",
    },
    {
        "id": "ks4-evolution-natural-selection-s26",
        "subtopic_slug": "evolution-natural-selection",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest what a biologist would record to test whether a moth population is evolving.",
        "options": [
            "The mass of a single moth, measured several times over the course of its own lifetime",
            "The number of moths caught on one night in a single trap in a wood",
            "The temperature of the air in the wood",
            "The proportion of each colour form, sampled over many years",
        ],
        "correct_index": 3,
        "why": "Evolution is a change in the population over generations, so the proportions have to be followed over time.",
    },
    {
        "id": "ks4-evolution-natural-selection-h05",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A lizard population is split by a new river. Predict what may happen over many thousands of years.",
        "options": [
            "Both groups will remain identical, because they began as one single population of lizards",
            "Both of the groups will die out, because neither of them can cross the river to the other",
            "They may become two species, if they can no longer produce fertile offspring together",
            "The two groups will swap alleles across the river and so stay exactly the same as before",
        ],
        "correct_index": 2,
        "why": "Isolation plus separate mutation and selection is the route by which one species becomes two.",
    },
    {
        "id": "ks4-evolution-natural-selection-h06",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why natural selection is described as having no goal.",
        "options": [
            "Because it favours whatever happens to survive now, with no aim for the future",
            "Because the organisms of a population are unable to set themselves a goal of any kind",
            "Because natural selection only acts on populations that are already perfectly adapted",
            "Because every generation of a population is identical to the one that came before it",
        ],
        "correct_index": 0,
        "why": "Selection is simply differential survival in present conditions; nothing in it looks ahead.",
    },
    {
        "id": "ks4-evolution-natural-selection-h07",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare what happens to a useful allele with what happens to a harmful one over many generations.",
        "options": [
            "The useful one becomes commoner and the harmful one becomes rarer",
            "Both of them become commoner in the population",
            "The useful one becomes rarer because it is used up, while the harmful one becomes commoner",
            "Neither of them changes in frequency, as allele frequencies are fixed",
        ],
        "correct_index": 0,
        "why": "Carriers of a useful allele leave more offspring, so its share of the population rises and the harmful one's falls.",
    },
    {
        "id": "ks4-evolution-natural-selection-h08",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student says a giraffe grew a long neck because it needed one. Explain the error in the reasoning.",
        "options": [
            "Because a giraffe would in fact have no need of a long neck in the habitat it lives in",
            "Because the neck of a giraffe is not an inherited characteristic of the animal at all",
            "Needing something cannot produce it; the variation must already exist to be selected",
            "Because giraffes have always had exactly the same neck length as one another",
        ],
        "correct_index": 2,
        "why": "Selection works on variation that is already present by chance; need plays no part in creating it.",
    },
    {
        "id": "ks4-evolution-natural-selection-h09",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why two species living in similar habitats on different continents may look alike.",
        "options": [
            "Because the two species must have interbred at some point in the distant past",
            "Because every species that lives in a particular habitat belongs to the same genus",
            "Because animals are able to choose the appearance that best suits their habitat",
            "Because similar conditions select for similar characteristics in unrelated species",
        ],
        "correct_index": 3,
        "why": "The same selection pressures acting on different populations can produce the same solution twice.",
    },
    {
        "id": "ks4-evolution-natural-selection-h10",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why removing all of a population's predators may not stop it evolving.",
        "options": [
            "Because a population continues to evolve when nothing acts on it",
            "Other pressures still act, such as disease, climate and competition for food",
            "Because the predators leave behind alleles that go on acting on the prey population",
            "Because a population without predators grows",
        ],
        "correct_index": 1,
        "why": "Predation is one selection pressure among many; removing it changes which pressures dominate, not whether any act.",
    },
    {
        "id": "ks4-evolution-natural-selection-h11",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A population of snails on a dark shore is mostly dark; on a pale shore mostly pale. Explain what this shows.",
        "options": [
            "That the snails are able to change their own shell colour to suit the shore they live on",
            "That the two populations belong to two completely different species of snail",
            "That birds hunting by sight have selected the better camouflaged snails on each shore",
            "That the colour of a snail's shell is not inherited from its parents in any way",
        ],
        "correct_index": 2,
        "why": "Camouflage raises survival, so on each shore the better-hidden form leaves more offspring.",
    },
    {
        "id": "ks4-evolution-natural-selection-h12",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that natural selection makes every species stronger over time.",
        "options": [
            "It is misleading — selection favours what suits the conditions, which may mean smaller or weaker",
            "It is correct, because the strongest individuals always survive in every habitat on Earth",
            "It is correct, because strength is the characteristic that all animals compete over",
            "It is wrong, because natural selection has no effect on any species at all",
        ],
        "correct_index": 0,
        "why": "In many habitats being small, well hidden or efficient beats being strong, and selection favours whichever works.",
    },
    {
        "id": "ks4-evolution-natural-selection-h13",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the fossil record shows some species unchanged for millions of years.",
        "options": [
            "Because those species were unable to reproduce during the whole of that time",
            "Because their conditions stayed stable, so selection kept favouring the same form",
            "Because natural selection stops acting on a species after a certain number of years",
            "Because those species carried no variation at all between their individuals",
        ],
        "correct_index": 1,
        "why": "Selection can hold a population still as easily as it can move it, when the existing form is the best-suited one.",
    },
    {
        "id": "ks4-evolution-natural-selection-h14",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the offspring of a population that has evolved are not identical to their ancestors.",
        "options": [
            "Because each individual changes during its own lifetime to suit the conditions it meets",
            "Because the offspring have inherited nothing at all from the ancestors of their population",
            "Because the offspring of a population always carry twice as many alleles as their ancestors",
            "Because the alleles that are common in the population have changed over the generations",
        ],
        "correct_index": 3,
        "why": "Evolution is exactly this: a shift in which alleles the population carries, inherited by the offspring.",
    },
    {
        "id": "ks4-evolution-natural-selection-h15",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a species that has evolved to suit one narrow habitat is at risk.",
        "options": [
            "Because it will always be outcompeted by a species that has a much wider habitat",
            "Because a narrow habitat contains fewer resources than a wide habitat does in total",
            "Because a species of this kind is unable to reproduce sexually within its habitat",
            "If that habitat changes, the characteristics that suited it become a disadvantage",
        ],
        "correct_index": 3,
        "why": "Close adaptation to one set of conditions is an advantage only while those conditions last.",
    },
    {
        "id": "ks4-evolution-natural-selection-h16",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why two populations that still interbreed are counted as one species however different they look.",
        "options": [
            "Because appearance is decided entirely by the conditions in which each population lives",
            "Because alleles still flow between them, so they cannot drift apart into separate species",
            "Because two populations that look different can never be found within one single species",
            "Because the test for a species is whether the two populations live in the same habitat",
        ],
        "correct_index": 1,
        "why": "Interbreeding keeps mixing the alleles of the two, which prevents the split that would make two species.",
    },
    {
        "id": "ks4-evolution-natural-selection-h17",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the role of mutation with the role of selection in evolution.",
        "options": [
            "Mutation supplies the new alleles; selection decides which of them become common",
            "Mutation decides which alleles become common and selection supplies the new ones instead",
            "Both of them supply new alleles to the population in exactly the same way as each other",
            "Neither of them has any effect on the alleles that a population carries over time",
        ],
        "correct_index": 0,
        "why": "The two do different jobs: one creates the raw material at random, the other sorts it non-randomly.",
    },
    {
        "id": "ks4-evolution-natural-selection-h18",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why evolution is hard to observe directly in a large mammal.",
        "options": [
            "Because large mammals carry no variation between the individuals of a population",
            "Because natural selection does not act on mammals in the way it acts on other animals",
            "Because its generation time is long, so measurable change takes far longer than a career",
            "Because a large mammal is unable to pass any of its alleles to the next generation",
        ],
        "correct_index": 2,
        "why": "Change is counted in generations, and a few human lifetimes cover very few elephant or whale generations.",
    },
    {
        "id": "ks4-evolution-natural-selection-h19",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why natural selection can act faster on a large population than a small one.",
        "options": [
            "Because a large population is able to change its own alleles more quickly than a small one",
            "A large population contains more variation for selection to work on",
            "Because selection cannot act on a small population",
            "Because every individual in a large population survives to reproduce",
        ],
        "correct_index": 1,
        "why": "More individuals means more mutations and more allele combinations available to be favoured.",
    },
    {
        "id": "ks4-evolution-natural-selection-h20",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a characteristic that helps survival but reduces breeding may not spread.",
        "options": [
            "Because a characteristic that helps survival is always passed on to every offspring",
            "Because such a characteristic cannot be controlled by an allele of any kind at all",
            "Because surviving for longer has no effect on how many offspring an individual leaves",
            "Because selection favours whatever leaves the most offspring, not whatever survives longest",
        ],
        "correct_index": 3,
        "why": "An allele spreads through being passed on, so reproduction and not mere survival is what decides its fate.",
    },
    {
        "id": "ks4-evolution-natural-selection-h21",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A conservationist wants a population to keep evolving. Explain why she works to keep its numbers high.",
        "options": [
            "Because a large population is able to move to a new habitat if conditions become poor",
            "Because a small population contains too many individuals for selection to act upon",
            "Because a small population loses variation, and without variation selection has nothing to act on",
            "Because numbers are the only measure of whether a population is healthy or not",
        ],
        "correct_index": 2,
        "why": "A population that falls very low loses alleles permanently, and cannot then adapt to anything new.",
    },
    {
        "id": "ks4-evolution-natural-selection-h22",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why the same species may be evolving in opposite directions in two places.",
        "options": [
            "Because the conditions differ, so different characteristics are favoured in each place",
            "Because the two populations are made up of individuals of two different species",
            "Because alleles change into different alleles when an organism moves to a new place",
            "Because evolution always moves in opposite directions in two separate populations",
        ],
        "correct_index": 0,
        "why": "Selection has no single direction; it follows the local conditions, which can pull two populations apart.",
    },
    {
        "id": "ks4-evolution-natural-selection-h23",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that evolution has stopped in modern humans.",
        "options": [
            "It is doubtful — selection pressures have changed rather than disappeared, and alleles still shift",
            "It is correct, because medicine means that every human being now survives to adulthood",
            "It is correct, because humans no longer carry any variation between individuals",
            "It is wrong, because natural selection acts on individuals and not on a population",
        ],
        "correct_index": 0,
        "why": "Disease, fertility and environment still act; what has changed is which pressures matter most.",
    },
    {
        "id": "ks4-evolution-natural-selection-h24",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why two populations may stop interbreeding even before a physical barrier appears.",
        "options": [
            "Because two populations of one species are never able to interbreed with one another",
            "Because differences in behaviour or breeding season can keep them apart",
            "Because the individuals of one population decide to stop breeding",
            "Because a population stops breeding at a certain size",
        ],
        "correct_index": 1,
        "why": "Anything that stops gametes meeting has the same effect as a mountain range, including timing and behaviour.",
    },
    {
        "id": "ks4-evolution-natural-selection-h25",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why natural selection cannot plan for a change that has not happened yet.",
        "options": [
            "Because populations are unable to carry any variation until a change has actually happened",
            "Because every allele in a population is equally useful in every possible set of conditions",
            "Because selection acts on survival and reproduction now, and the future cannot affect the present",
            "Because natural selection only acts once a population has already become extinct",
        ],
        "correct_index": 2,
        "why": "An allele that would be useful later gives no advantage today, so nothing makes it spread in advance.",
    },
    {
        "id": "ks4-evolution-natural-selection-h26",
        "subtopic_slug": "evolution-natural-selection",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why an allele can become common even if it gives only a very small advantage.",
        "options": [
            "Because a small advantage is turned into a much larger one by the environment over time",
            "Because every allele becomes common sooner or later",
            "Because an allele with a small advantage is always passed on",
            "Because a small advantage repeated over very many generations still adds up",
        ],
        "correct_index": 3,
        "why": "Selection compounds: a tiny difference in survival, repeated for thousands of generations, changes a population completely.",
    },
]
