"""Biology · Inheritance, Variation and Evolution — the MRB-338 expansion,
subtopic `inherited-disorders`.

The baseline twelve cover the ff genotype, what polydactyly does, one
treatment, the one-in-twenty-five carrier figure, a new dominant mutation,
one cross, one testing argument, one counselling case, a 50% calculation,
digestion in cystic fibrosis, amniocentesis and a 25% calculation. This file
adds the ground the baseline never reaches: what cystic fibrosis IS (a
disorder of cell membranes giving thick sticky mucus); what a carrier is and
why a carrier shows nothing; embryo screening set out as a procedure, with
the economic, social and ethical arguments on both sides; reading a family
pattern in words to decide whether an allele is dominant or recessive; why a
recessive disorder can appear with no family history; independence between
one child and the next; and genetic counselling as what a family actually
receives.

⚠️ `genetic-inheritance` owns the general Punnett-square method and the
vocabulary; `dna-genome` owns what knowing the genome does for medicine.
This leaf stays on the two named disorders and on the decisions families and
doctors face.
"""

TOPIC = "inheritance"
SUBJECT = "biology"

QUESTIONS = [
    {
        "id": "ks4-inherited-disorders-e05",
        "subtopic_slug": "inherited-disorders",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State which part of a cell is affected by the faulty allele that causes cystic fibrosis.",
        "options": [
            "The cell membrane",
            "The nucleus, which controls all of the activities that go on inside the cell",
            "The mitochondria, where the reactions of aerobic respiration take place",
            "The ribosomes in the cytoplasm",
        ],
        "correct_index": 0,
        "why": "Cystic fibrosis is a disorder of cell membranes, which is why mucus in the lungs and gut becomes thick and sticky.",
    },
    {
        "id": "ks4-inherited-disorders-e06",
        "subtopic_slug": "inherited-disorders",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State whether the allele that causes polydactyly is dominant or recessive.",
        "options": [
            "Recessive, so two copies of the allele are needed before it shows",
            "It is neither, because polydactyly is caused by conditions before birth",
            "Dominant",
            "It depends on which parent it came from",
        ],
        "correct_index": 2,
        "why": "Polydactyly is caused by a dominant allele, so one copy is enough for a person to have extra digits.",
    },
    {
        "id": "ks4-inherited-disorders-e07",
        "subtopic_slug": "inherited-disorders",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what is meant by a carrier of cystic fibrosis.",
        "options": [
            "Somebody who has the disorder and can pass it on to all of their own children",
            "Somebody who caught the disorder from another person during their childhood",
            "Somebody with no faulty alleles at all",
            "Somebody with one faulty allele who never develops the disorder",
        ],
        "correct_index": 3,
        "why": "One normal allele is enough for healthy membranes, so a carrier is unaffected but can pass the faulty allele on.",
    },
    {
        "id": "ks4-inherited-disorders-e08",
        "subtopic_slug": "inherited-disorders",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe the mucus produced by a person who has cystic fibrosis.",
        "options": [
            "Much thinner and runnier than normal mucus, so that it drains away far too quickly",
            "Thick and sticky",
            "Exactly the same as the mucus produced by anybody who does not have the disorder",
            "No mucus is produced at all",
        ],
        "correct_index": 1,
        "why": "The faulty membrane protein leaves the mucus thick, so it blocks the airways and the ducts of the pancreas.",
    },
    {
        "id": "ks4-inherited-disorders-e09",
        "subtopic_slug": "inherited-disorders",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the procedure in which cells are taken from an IVF embryo and tested for a faulty allele.",
        "options": [
            "Selective breeding, in which the parents with the best characteristics are chosen to breed",
            "Tissue culture, in which a few cells are grown on a sterile jelly containing hormones",
            "Embryo screening",
            "Vaccination against the allele",
        ],
        "correct_index": 2,
        "why": "Embryo screening tests embryos produced by IVF so that only unaffected ones are implanted.",
    },
    {
        "id": "ks4-inherited-disorders-e10",
        "subtopic_slug": "inherited-disorders",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how many faulty alleles a person must inherit to have cystic fibrosis.",
        "options": [
            "Two, one from each parent",
            "One, provided that it was inherited from the mother rather than from the father",
            "Three or more, which is why the disorder is so rare in the population",
            "None at all, since it is not inherited",
        ],
        "correct_index": 0,
        "why": "The faulty allele is recessive, so both parents must pass one on for the disorder to appear.",
    },
    {
        "id": "ks4-inherited-disorders-e11",
        "subtopic_slug": "inherited-disorders",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "Name the service that explains inherited risk to a family before they decide to have children.",
        "options": [
            "A course of antibiotics given to both of the parents before they try for a baby",
            "Genetic counselling",
            "Physiotherapy, in which the chest is clapped to loosen the mucus in the airways",
            "Gene editing of the embryo",
        ],
        "correct_index": 1,
        "why": "A genetic counsellor sets out the risk and the options so that the family can make an informed choice.",
    },
    {
        "id": "ks4-inherited-disorders-e12",
        "subtopic_slug": "inherited-disorders",
        "band": "easier",
        "tier": "foundation",
        "triple_only": False,
        "text": "State how many parents must be affected for a child to inherit polydactyly.",
        "options": [
            "Both of them, because a dominant allele can only be passed on by two affected parents",
            "Neither parent has to carry the allele, since polydactyly develops before birth",
            "Four grandparents",
            "One is enough",
        ],
        "correct_index": 3,
        "why": "Because the allele is dominant, a single affected parent can pass it on and the child will show it.",
    },
    {
        "id": "ks4-inherited-disorders-s05",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a carrier of cystic fibrosis shows none of the symptoms.",
        "options": [
            "Because the faulty allele is destroyed by the body before it can be used by any cell",
            "Because a carrier has only one copy of every gene in their body cells",
            "Because carriers are treated",
            "Because the carrier's normal allele always makes the working membrane protein",
        ],
        "correct_index": 3,
        "why": "One working copy of the gene is enough to keep the cell membranes functioning normally.",
    },
    {
        "id": "ks4-inherited-disorders-s06",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A child has an inherited disorder but neither parent shows it. Deduce whether the allele is dominant or recessive.",
        "options": [
            "Dominant, since a dominant allele is able to skip a generation before it shows itself",
            "Recessive, because both unaffected parents must have been carrying it hidden",
            "It cannot be decided from this information without testing the grandparents as well",
            "Neither, because the disorder is environmental",
        ],
        "correct_index": 1,
        "why": "A dominant allele always shows in whoever carries it, so unaffected parents means the allele must be recessive.",
    },
    {
        "id": "ks4-inherited-disorders-s07",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "A disorder appears in every generation of a family, in both males and females. Suggest what this indicates.",
        "options": [
            "That the allele causing it is dominant, because it shows in whoever inherits it",
            "That the disorder is caused entirely by the diet that the family has eaten for generations",
            "That the allele is recessive and every member of the family happens to be a carrier",
            "That the family are all clones",
        ],
        "correct_index": 0,
        "why": "A recessive disorder usually skips generations; appearing in every one points to a dominant allele.",
    },
    {
        "id": "ks4-inherited-disorders-s08",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe the first step of embryo screening after eggs have been fertilised in the laboratory.",
        "options": [
            "The embryos are all implanted into the mother before any testing is carried out on them",
            "The embryos are frozen for a year so that they can be tested when they are older",
            "A cell is removed from each embryo and its alleles are checked",
            "The embryos are cloned",
        ],
        "correct_index": 2,
        "why": "One cell is taken while the embryo's cells are still unspecialised, and that cell's DNA is tested.",
    },
    {
        "id": "ks4-inherited-disorders-s09",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give one economic argument used in favour of embryo screening.",
        "options": [
            "That screening every embryo costs a health service nothing at all to carry out",
            "Treating an inherited disorder for a lifetime is very expensive",
            "That families with an inherited disorder pay less tax than other families do",
            "That screening creates jobs",
        ],
        "correct_index": 1,
        "why": "Lifelong treatment for a serious disorder is costly, and that cost is one argument people make for screening.",
    },
    {
        "id": "ks4-inherited-disorders-s10",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give one ethical argument used against embryo screening.",
        "options": [
            "That screening an embryo changes the alleles that the embryo carries in its cells",
            "That the results of screening an embryo are far too unreliable to be used by anyone",
            "That embryo screening takes far too long",
            "That an embryo is destroyed",
        ],
        "correct_index": 3,
        "why": "Screening means selecting between embryos, and objections to destroying the unselected ones are ethical rather than technical.",
    },
    {
        "id": "ks4-inherited-disorders-s11",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Give one social argument used against embryo screening.",
        "options": [
            "That the embryos would all be genetically identical to one another once screening had finished",
            "That a screened embryo is unable to develop normally once it has been implanted",
            "That people might start choosing other characteristics too",
            "That screening is not available",
        ],
        "correct_index": 2,
        "why": "The social worry is where the line is drawn, and what the practice says about the value of disabled lives.",
    },
    {
        "id": "ks4-inherited-disorders-s12",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two carriers of cystic fibrosis have a child. State the chance that the child has the disorder.",
        "options": [
            "One in four",
            "There is no chance at all, because neither of the two parents has the disorder themselves",
            "One in two, because each of the parents carries one faulty allele out of the two they have",
            "It is certain",
        ],
        "correct_index": 0,
        "why": "Each parent passes on the faulty allele half the time, and a half of a half is a quarter.",
    },
    {
        "id": "ks4-inherited-disorders-s13",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why cystic fibrosis can appear in a family with no previous history of it.",
        "options": [
            "Because carriers show no symptoms",
            "Because the disorder is caught from somebody else who already has it in the family",
            "Because a dominant allele can stay hidden for several generations before it appears",
            "Because the disorder is environmental",
        ],
        "correct_index": 0,
        "why": "About one person in twenty-five is a carrier, and nothing about a carrier reveals the allele until two of them have a child.",
    },
    {
        "id": "ks4-inherited-disorders-s14",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe what is done with the embryos that pass an embryo screening test.",
        "options": [
            "They are frozen and kept in storage without ever being used by the family concerned",
            "They are tested a second time to check the result that was obtained the first time",
            "Only embryos free of the faulty allele are implanted into the mother",
            "They are all discarded",
        ],
        "correct_index": 2,
        "why": "The point of the procedure is that the pregnancy starts from an embryo known not to carry the disorder.",
    },
    {
        "id": "ks4-inherited-disorders-s15",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a couple who already have one child with cystic fibrosis still face the same risk with the next.",
        "options": [
            "Because the risk of a disorder rises with each child that a couple decides to have",
            "Because the first child used up the only normal allele that the parents carried",
            "Because the risk falls to zero after one child",
            "Because each fertilisation is a separate event",
        ],
        "correct_index": 3,
        "why": "Previous children do not change what a gamete carries, so the probability starts afresh for every pregnancy.",
    },
    {
        "id": "ks4-inherited-disorders-s16",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe one way, other than physiotherapy, that a person with cystic fibrosis is treated.",
        "options": [
            "By being given a course of vaccinations against the faulty allele that causes it",
            "Enzyme capsules taken with meals, because the pancreatic ducts are blocked",
            "By having the faulty allele removed from every one of the cells of their body",
            "By taking painkillers",
        ],
        "correct_index": 1,
        "why": "Thick mucus blocks the pancreatic duct, so digestive enzymes have to be swallowed with food instead.",
    },
    {
        "id": "ks4-inherited-disorders-s17",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why people with cystic fibrosis get frequent chest infections.",
        "options": [
            "Because the faulty allele stops their white blood cells from working properly at all",
            "Because they are given antibiotics far too often over the course of a year",
            "Because the thick mucus is hard to clear, so bacteria multiply in the airways",
            "Because their lungs are smaller",
        ],
        "correct_index": 2,
        "why": "Mucus that cannot be moved out of the lungs traps bacteria and gives them a place to grow.",
    },
    {
        "id": "ks4-inherited-disorders-s18",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why polydactyly is much less likely than cystic fibrosis to be missed in a family history.",
        "options": [
            "Because the allele always shows",
            "Because polydactyly is caused by an allele that is passed on far more often than others",
            "Because a person with polydactyly has more chromosomes than an unaffected person",
            "Because the disorder is always fatal",
        ],
        "correct_index": 0,
        "why": "A dominant allele cannot hide, so the family pattern is visible in every generation that carries it.",
    },
    {
        "id": "ks4-inherited-disorders-s19",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what a genetic counsellor can tell a couple who are both carriers.",
        "options": [
            "Exactly which of their future children will be affected and which of them will not be",
            "The chance that a child of theirs would have the disorder, and the choices open to them",
            "That there is no risk at all to any child that they may have together in future",
            "That they cannot have children",
        ],
        "correct_index": 1,
        "why": "Counselling gives the probability and the options; it cannot say what any particular pregnancy will bring.",
    },
    {
        "id": "ks4-inherited-disorders-s20",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a person with polydactyly may have children who do not have it.",
        "options": [
            "Because polydactyly is only inherited by children of the same sex as the affected parent",
            "Because a dominant allele cannot be passed on to a child by either of its parents",
            "Because the allele disappears from the family line entirely",
            "Because an affected parent is usually heterozygous",
        ],
        "correct_index": 3,
        "why": "Most affected people carry one faulty and one normal allele, so each child has a one in two chance of inheriting it.",
    },
    {
        "id": "ks4-inherited-disorders-s21",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what the letters used in a genetic diagram for cystic fibrosis stand for.",
        "options": [
            "The two parents, one letter for the mother and one letter for the father of the child",
            "The chance of the disorder appearing and the chance of it not appearing in the child",
            "Two separate genes",
            "The normal allele and the faulty allele of the same gene",
        ],
        "correct_index": 3,
        "why": "A capital F is the normal allele and a lower-case f the faulty one, both versions of the same gene.",
    },
    {
        "id": "ks4-inherited-disorders-s22",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why embryo screening is only available to couples using IVF.",
        "options": [
            "Because a couple who are not using IVF cannot inherit any faulty allele at all",
            "Because the embryo has to be outside the body for a cell to be taken and tested",
            "Because IVF removes the faulty allele from the embryos before they are tested",
            "Because IVF is cheaper",
        ],
        "correct_index": 1,
        "why": "The test needs a cell from the embryo before implantation, which is only possible when fertilisation happens in the laboratory.",
    },
    {
        "id": "ks4-inherited-disorders-s23",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Describe why a recessive disorder can persist in a population for many generations.",
        "options": [
            "Because carriers are unaffected and keep passing the allele on without knowing",
            "Because the allele is remade by mutation in every single generation of the population",
            "Because a recessive allele becomes dominant after it has been passed on several times",
            "Because it is not inherited",
        ],
        "correct_index": 0,
        "why": "Selection acts on affected individuals only, and they are a small minority of those carrying the allele.",
    },
    {
        "id": "ks4-inherited-disorders-s24",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "State what happens to the digestive enzymes of a person with cystic fibrosis.",
        "options": [
            "They are broken down by the thick mucus before they can be made by the pancreas",
            "They are made in far larger quantities than an unaffected person makes them",
            "They cannot reach the gut, because the duct is blocked",
            "They are not made by the pancreas of the person at any point",
        ],
        "correct_index": 2,
        "why": "The pancreas works, but the sticky mucus blocks the tube carrying its enzymes to the small intestine.",
    },
    {
        "id": "ks4-inherited-disorders-s25",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why an affected person with a recessive disorder must have two carrier parents at least.",
        "options": [
            "Because a recessive disorder can only be inherited from the mother of the child",
            "Because two faulty alleles are needed, and each parent supplies one of the two",
            "Because the parents must both have the disorder in order to pass the allele on",
            "Because carriers cannot have children",
        ],
        "correct_index": 1,
        "why": "One allele comes from each parent, so both must carry the faulty one even if neither shows the disorder.",
    },
    {
        "id": "ks4-inherited-disorders-s26",
        "subtopic_slug": "inherited-disorders",
        "band": "standard",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the number of people with cystic fibrosis living into adulthood has risen sharply.",
        "options": [
            "Because the faulty allele has been removed from the population over recent decades",
            "Because far fewer people inherit two faulty alleles than used to inherit them",
            "Because the disorder has become milder",
            "Because treatment has improved, so the lungs and the gut are managed much better",
        ],
        "correct_index": 3,
        "why": "The allele is unchanged; physiotherapy, antibiotics and enzyme replacement have transformed what the disorder means.",
    },
    {
        "id": "ks4-inherited-disorders-h05",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "In a family, an affected grandfather, an unaffected father and an affected grandson all have extra fingers. Deduce what this pattern shows.",
        "options": [
            "That the allele is dominant, because it has shown in each of the three generations in turn",
            "That the pattern is inconsistent with any single allele, so the cause must be environmental",
            "That the allele must be recessive, because the father in the middle generation is unaffected",
            "That the grandson is a carrier",
        ],
        "correct_index": 2,
        "why": "A dominant allele would have shown in the father; skipping a generation points to a recessive allele instead.",
    },
    {
        "id": "ks4-inherited-disorders-h06",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A carrier of cystic fibrosis has children with a person who carries no faulty allele. Predict the outcome for their children.",
        "options": [
            "None will have it, but about half will be carriers",
            "All of their children would be expected to have the disorder from birth onwards",
            "Half of their children would be expected to have the disorder and half would not",
            "One quarter will have it",
        ],
        "correct_index": 0,
        "why": "Every child gets a normal allele from one parent, so none is affected, but half inherit the faulty allele from the carrier.",
    },
    {
        "id": "ks4-inherited-disorders-h07",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare what a dominant and a recessive disorder look like when you draw out a family over four generations.",
        "options": [
            "A dominant disorder shows in every generation; a recessive one can skip",
            "Both of them appear in every single generation of a family without any exception at all",
            "A recessive disorder appears in each generation while a dominant one always skips one",
            "Neither of them shows any pattern",
        ],
        "correct_index": 0,
        "why": "A dominant allele cannot hide; a recessive one passes silently through carriers and reappears when two of them meet.",
    },
    {
        "id": "ks4-inherited-disorders-h08",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the argument that embryo screening should be used for every inherited condition without exception.",
        "options": [
            "It is sound, because any inherited condition at all is better prevented than treated later",
            "It is wrong, because embryo screening does not work for conditions of any kind",
            "It is questionable — conditions differ greatly in severity",
            "It is sound, because screening is cheap",
        ],
        "correct_index": 2,
        "why": "Science can say what an embryo carries; it cannot say which conditions are serious enough to justify selecting against.",
    },
    {
        "id": "ks4-inherited-disorders-h09",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the faulty cystic fibrosis allele has not been removed from the population by natural selection.",
        "options": [
            "Because natural selection cannot act on alleles that cause a disorder in human beings",
            "Because the allele changes back into a normal allele whenever it is passed on",
            "Because the disorder is mild",
            "Because most copies of it sit hidden in carriers, where selection cannot reach them",
        ],
        "correct_index": 3,
        "why": "Selection can only act on the phenotype, and the great majority of the faulty alleles are in unaffected carriers.",
    },
    {
        "id": "ks4-inherited-disorders-h10",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Two parents are both carriers and have four children. Evaluate the claim that exactly one of the four will be affected.",
        "options": [
            "It is correct, because a one in four chance always gives exactly one in every four children born",
            "It is unsafe — one in four is a probability, so any number from zero to four is possible",
            "It is wrong, because none of the four children of two carriers can ever be affected at all",
            "It is correct for boys only",
        ],
        "correct_index": 1,
        "why": "Each child independently has a one in four chance, so the expected number is one but the actual number varies.",
    },
    {
        "id": "ks4-inherited-disorders-h11",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a faulty membrane protein affects the lungs and the pancreas but not the bones.",
        "options": [
            "Because bone cells have no cell membranes in the way that other body cells do",
            "Because the gene is switched off completely in the cells of the lungs and the pancreas",
            "Because those organs depend on moving salts and water across membranes to make thin mucus",
            "Because bones are harder",
        ],
        "correct_index": 2,
        "why": "The same faulty protein matters most where secretion depends on it, which is why the symptoms are where they are.",
    },
    {
        "id": "ks4-inherited-disorders-h12",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why testing an unborn baby raises different questions from testing an embryo before implantation.",
        "options": [
            "A pregnancy is already established, so the choice that follows a positive result is far harder",
            "Because a test carried out during pregnancy gives a result that is known to be unreliable",
            "Because an unborn baby carries different alleles from the embryo that it grew from",
            "Because embryos cannot be tested",
        ],
        "correct_index": 0,
        "why": "Screening selects between embryos before a pregnancy starts; a prenatal test comes after it has begun.",
    },
    {
        "id": "ks4-inherited-disorders-h13",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A person with polydactyly has an unaffected partner and four children, all affected. Deduce the most likely genotype of the affected parent.",
        "options": [
            "Heterozygous, since about half of the children of a heterozygous parent are affected",
            "Homozygous dominant",
            "Homozygous recessive, because every one of the four children inherited the condition",
            "It cannot be worked out from four children under any circumstances whatsoever",
        ],
        "correct_index": 1,
        "why": "A heterozygous parent would be expected to give about two unaffected children in four, so four affected points to two dominant alleles.",
    },
    {
        "id": "ks4-inherited-disorders-h14",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why knowing that about one person in twenty-five carries the cystic fibrosis allele is useful to a doctor.",
        "options": [
            "Because it tells the doctor exactly which of their patients will develop the disorder",
            "Because it shows that the faulty allele is dominant rather than recessive after all",
            "Because it proves the disorder is caught",
            "It lets the doctor estimate the chance that both partners are carriers",
        ],
        "correct_index": 3,
        "why": "The carrier frequency is what turns a population statistic into an estimate of risk for a particular couple.",
    },
    {
        "id": "ks4-inherited-disorders-h15",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why an inherited disorder caused by a dominant allele that acts late in life is not removed by selection.",
        "options": [
            "Because a dominant allele is always too strong for natural selection to be able to act on it",
            "Because an allele acting late in life is not passed on to any of a person's children",
            "Because it is not inherited",
            "Because the person has usually already had children before the disorder appears",
        ],
        "correct_index": 3,
        "why": "Selection acts through reproduction, so an allele whose effects come after childbearing is largely invisible to it.",
    },
    {
        "id": "ks4-inherited-disorders-h16",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Compare the risk to a child of two carriers with the risk to a child of one carrier and one affected person.",
        "options": [
            "Both of the pairings give exactly the same one in four risk as each other in every case",
            "Two carriers give a one in four risk; a carrier with an affected partner gives a one in two risk",
            "Two carriers give a one in two risk while a carrier and an affected person give one in four",
            "Neither pairing carries any risk",
        ],
        "correct_index": 1,
        "why": "An affected partner passes on a faulty allele every time, so only the carrier's half chance is left to multiply.",
    },
    {
        "id": "ks4-inherited-disorders-h17",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a couple may still choose to have children naturally after genetic counselling shows a high risk.",
        "options": [
            "Because the decision is theirs, and it weighs values and circumstances as well as probability",
            "Because counselling removes the faulty alleles that the couple happen to be carrying",
            "Because a high risk means that none of their children could actually be affected",
            "Because the risk is always wrong",
        ],
        "correct_index": 0,
        "why": "Counselling informs a choice rather than making it; the science gives the odds and the family decides.",
    },
    {
        "id": "ks4-inherited-disorders-h18",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why screening a population for carriers of a recessive disorder is harder than screening for an affected person.",
        "options": [
            "Because carriers are far rarer in a population than affected people are in every case",
            "Because affected people are unwilling to be tested for a disorder they already have",
            "Because a carrier shows no symptoms, so only a DNA test can identify one",
            "Because carriers change over time",
        ],
        "correct_index": 2,
        "why": "An affected person can be identified by their symptoms; a carrier is indistinguishable without testing the DNA itself.",
    },
    {
        "id": "ks4-inherited-disorders-h19",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Evaluate the claim that embryo screening will eventually remove cystic fibrosis from the population.",
        "options": [
            "It is correct, because every couple in the country is screened before having any children",
            "It is doubtful — screening is used by very few couples, and carriers go on passing the allele on",
            "It is correct, because screening changes the alleles carried by the parents themselves",
            "It is wrong, because screening does not detect the allele",
        ],
        "correct_index": 1,
        "why": "Almost all copies of the allele sit in carriers who never come near an IVF clinic, so the reservoir is untouched.",
    },
    {
        "id": "ks4-inherited-disorders-h20",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why a child of two affected parents with a recessive disorder must also be affected.",
        "options": [
            "Because a recessive disorder is passed on to every child regardless of the alleles involved",
            "Because the parents' symptoms are passed to the child during the pregnancy itself",
            "Because the child has more alleles",
            "Because each parent carries two faulty alleles, so a faulty one is all either can pass on",
        ],
        "correct_index": 3,
        "why": "With no normal allele available from either parent, every child must inherit two faulty ones.",
    },
    {
        "id": "ks4-inherited-disorders-h21",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why polydactyly rarely affects how long a person lives, while cystic fibrosis does.",
        "options": [
            "Because polydactyly is caused by the environment rather than by any allele at all",
            "Because polydactyly is treated with surgery and cystic fibrosis cannot be treated",
            "Because an extra digit does not stop an organ working, while thick mucus damages the lungs",
            "Because polydactyly is rarer",
        ],
        "correct_index": 2,
        "why": "How serious a disorder is depends on what the faulty protein does, not on whether the allele is dominant or recessive.",
    },
    {
        "id": "ks4-inherited-disorders-h22",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A student says that because cystic fibrosis is recessive it must be rarer than polydactyly. Evaluate this.",
        "options": [
            "It is wrong — how common a disorder is depends on how common the allele is, not on dominance",
            "It is correct, because a recessive allele is always rarer than a dominant one in a population",
            "It is correct, because recessive disorders are only inherited from one of the two parents",
            "It is wrong, because polydactyly is recessive",
        ],
        "correct_index": 0,
        "why": "Dominance decides whether an allele shows, not how many copies of it a population happens to contain.",
    },
    {
        "id": "ks4-inherited-disorders-h23",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why a treatment that replaced the faulty allele in lung cells would not stop the disorder being passed on.",
        "options": [
            "Because the gametes would still carry the faulty allele, and they are what is inherited",
            "Because the treated cells would reject the new allele within a few weeks of receiving it",
            "Because the faulty allele would return to the lung cells each time they divided by mitosis",
            "Because the lungs are not inherited",
        ],
        "correct_index": 0,
        "why": "Changing body cells treats the patient; only a change in the gametes could alter what the next generation receives.",
    },
    {
        "id": "ks4-inherited-disorders-h24",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Explain why doctors describe cystic fibrosis as affecting several organ systems at once.",
        "options": [
            "Because a person with the disorder inherits several different faulty alleles together",
            "Because the faulty protein is in the membranes of cells in the lungs, the gut and elsewhere",
            "Because the disorder spreads from one organ to the next as a person gets older",
            "Because the organs are connected",
        ],
        "correct_index": 1,
        "why": "One gene, one protein, but that protein is used wherever thin secretions are needed, so several systems are affected.",
    },
    {
        "id": "ks4-inherited-disorders-h25",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "A couple are told their risk is one in four but the clinic tests only four embryos. Suggest why none may be suitable.",
        "options": [
            "Because four embryos are far too few for any laboratory to be able to test them at all",
            "Because a tested embryo can no longer be implanted into the mother afterwards",
            "Because one in four is only a probability",
            "Because embryo screening always fails in practice",
        ],
        "correct_index": 2,
        "why": "Chance does not deal out exactly one affected embryo in four, so a small batch can contain several.",
    },
    {
        "id": "ks4-inherited-disorders-h26",
        "subtopic_slug": "inherited-disorders",
        "band": "harder",
        "tier": "foundation",
        "triple_only": False,
        "text": "Suggest why the arguments about embryo screening cannot be settled by scientific evidence alone.",
        "options": [
            "Because the evidence about what embryo screening actually does is still far too weak to use",
            "Because scientists are not allowed to give an opinion about embryo screening in public",
            "Because the science is secret",
            "Because the disagreements are about values, and evidence cannot decide what people ought to do",
        ],
        "correct_index": 3,
        "why": "Evidence settles what a procedure does; whether it should be done is an ethical and social judgement.",
    },
]
