insert into public.pending_staff_classes (pending_staff_id, class_id, subject_id, role)
select ps.id, c.id, sub.id, 'subject_teacher'
from (values
  ('BLF','10h/Sc4','Combined Science'),
  ('BLF','10r/Ph1','Physics'),
  ('BLF','11h/Sc1','Combined Science'),
  ('BLF','11r/Ph3','Physics'),
  ('BLF','7h/Sc2','Science'),
  ('BLF','8h/Sc1','Science'),
  ('BLF','9h/Sc4','Science'),
  ('BLF','9r/Sc2','Science'),
  ('BRB','10h/Sc5','Combined Science'),
  ('BRB','10r/Ch2','Chemistry'),
  ('BRB','10r/Sc1','Combined Science'),
  ('BRB','11h/Sc2','Combined Science'),
  ('BRB','7h/Sc3','Science'),
  ('BRB','7h/Sc4','Science'),
  ('BRB','7r/Sc5','Science'),
  ('BRB','8h/Sc4','Science'),
  ('BRB','8r/Sc3','Science'),
  ('ELV','10r/Sc2','Combined Science'),
  ('ELV','7h/Sc2','Science'),
  ('ELV','7r/Sc4','Science'),
  ('ELV','8h/Sc3','Science'),
  ('ELV','8r/Sc1','Science'),
  ('ELV','8r/Sc4','Science'),
  ('ELV','9h/Sc4','Science'),
  ('ELV','9r/Sc4','Science'),
  ('FNL','10h/Sc3','Combined Science'),
  ('FNL','10h/Sc5','Combined Science'),
  ('FNL','10r/Ph3','Physics'),
  ('FNL','11h/Sc3','Combined Science'),
  ('FNL','11r/Ph1','Physics'),
  ('FNL','7h/Sc4','Science'),
  ('FNL','7r/Sc2','Science'),
  ('FNL','8h/Sc3','Science'),
  ('FNL','8r/Sc5','Science'),
  ('FNL','9r/Sc5','Science'),
  ('HTJ','10D/Bi1','Biology'),
  ('HTJ','11A/Bi1','Biology'),
  ('HTJ','11D/Bi1','Biology'),
  ('HTJ','11r/Sc1','Combined Science'),
  ('HTJ','7h/Sc5','Science'),
  ('HTJ','7r/Sc1','Science'),
  ('HRS','10h/Sc3','Combined Science'),
  ('HRS','10r/Ch3','Chemistry'),
  ('HRS','11h/Sc1','Combined Science'),
  ('HRS','11r/Ch1','Chemistry'),
  ('HRS','11r/Ch3','Chemistry'),
  ('HRS','7h/Sc1','Science'),
  ('HRS','7r/Sc4','Science'),
  ('HRS','9h/Sc3','Science'),
  ('JKS','10h/Ch1','Chemistry'),
  ('JKS','10h/Sc1','Combined Science'),
  ('JKS','11r/Ch2','Chemistry'),
  ('JKS','7h/Sc6','Science'),
  ('JKS','7r/Sc2','Science'),
  ('JKS','8h/Sc1','Science'),
  ('JKS','8h/Sc2','Science'),
  ('JKS','9r/Sc2','Science'),
  ('MKB','10h/Sc1','Combined Science'),
  ('MKB','10r/Ch1','Chemistry'),
  ('MKB','11h/Ch1','Chemistry'),
  ('MKB','11r/Sc2','Combined Science'),
  ('MKB','8h/Sc4','Science'),
  ('MKB','8h/Sc5','Science'),
  ('MKB','9h/Sc1','Science'),
  ('MKB','9r/Sc3','Science'),
  ('RNN','10A/Bi1','Biology'),
  ('RNN','10h/Sc2','Combined Science'),
  ('RNN','11B/Bi1','Biology'),
  ('RNN','11h/Sc3','Combined Science'),
  ('RNN','11r/Sc2','Combined Science'),
  ('RNN','7h/Sc1','Science'),
  ('RNN','7r/Sc3','Science'),
  ('RNN','8r/Sc2','Science'),
  ('RNN','9h/Sc2','Science'),
  ('RNN','9r/Sc3','Science'),
  ('SRE','10B/Bi1','Biology'),
  ('SRE','10C/Bi1','Biology'),
  ('SRE','10h/Sc4','Combined Science'),
  ('SRE','10r/Sc2','Combined Science'),
  ('SRE','11C/Bi1','Biology'),
  ('SRE','11h/Sc4','Combined Science'),
  ('SRE','7h/Sc6','Science'),
  ('SRE','7r/Sc5','Science'),
  ('SPD','10r/Ph2','Physics'),
  ('SPD','10r/Sc1','Combined Science'),
  ('SPD','11h/Sc4','Combined Science'),
  ('SPD','11h/Sc5','Combined Science'),
  ('SPD','11r/Ph2','Physics'),
  ('SPD','8h/Sc5','Science'),
  ('SPD','8r/Sc5','Science'),
  ('SPD','9h/Sc2','Science'),
  ('SPD','9r/Sc4','Science'),
  ('WKN','11h/Sc2','Combined Science'),
  ('WKN','7h/Sc3','Science'),
  ('WKN','7r/Sc1','Science'),
  ('WKN','8h/Sc4','Science'),
  ('WKN','8r/Sc2','Science'),
  ('WKN','9h/Sc5','Science'),
  ('WKN','9r/Sc1','Science')
) as v(staff_code, class_name, subject_name)
join public.pending_staff ps on ps.staff_code = v.staff_code and ps.deleted_at is null
join public.classes  c   on c.name = v.class_name and c.school_id = (select id from public.schools where code='RHS') and c.academic_year_id = (select id from public.academic_years where school_id=(select id from public.schools where code='RHS') and name='2026-27')
join public.subjects sub on sub.name = v.subject_name
where not exists (select 1 from public.pending_staff_classes x
                   where x.pending_staff_id = ps.id and x.class_id = c.id
                     and x.subject_id = sub.id and x.role = 'subject_teacher');