with sch as (select id from public.schools where code='RHS'),
     yr  as (select id from public.academic_years where school_id=(select id from sch) and name='2026-27'),
cls as (select * from public.classes where school_id=(select id from sch) and academic_year_id=(select id from yr)),
intended as (
  select c.name cls, coalesce(p.staff_code,'BDA') code
    from cls c join public.class_teachers ct on ct.class_id=c.id and ct.ended_at is null and ct.deleted_at is null
    left join public.pending_staff p on p.claimed_profile_id=ct.teacher_id
  union
  select c.name, ps.staff_code from cls c
    join public.pending_staff_classes psc on psc.class_id=c.id
    join public.pending_staff ps on ps.id=psc.pending_staff_id and ps.deleted_at is null),
live as (select cls, string_agg(code,',' order by code) codes from intended group by cls),
pinned(cls, codes) as (values
  ('10A/Bi1','RNN'),
  ('10B/Bi1','SRE'),
  ('10C/Bi1','SRE'),
  ('10D/Bi1','HTJ'),
  ('10h/Ch1','JKS'),
  ('10h/Ph1','BDA'),
  ('10h/Sc1','JKS,MKB'),
  ('10h/Sc2','BDA,RNN'),
  ('10h/Sc3','FNL,HRS'),
  ('10h/Sc4','BLF,SRE'),
  ('10h/Sc5','BRB,FNL'),
  ('10r/Ch1','MKB'),
  ('10r/Ch2','BRB'),
  ('10r/Ch3','HRS'),
  ('10r/Ph1','BLF'),
  ('10r/Ph2','SPD'),
  ('10r/Ph3','FNL'),
  ('10r/Sc1','BRB,SPD'),
  ('10r/Sc2','ELV,SRE'),
  ('11A/Bi1','HTJ'),
  ('11B/Bi1','RNN'),
  ('11C/Bi1','SRE'),
  ('11D/Bi1','HTJ'),
  ('11h/Ch1','MKB'),
  ('11h/Ph1','BDA'),
  ('11h/Sc1','BLF,HRS'),
  ('11h/Sc2','BRB,WKN'),
  ('11h/Sc3','FNL,RNN'),
  ('11h/Sc4','SPD,SRE'),
  ('11h/Sc5','BDA,SPD'),
  ('11r/Ch1','HRS'),
  ('11r/Ch2','JKS'),
  ('11r/Ch3','HRS'),
  ('11r/Ph1','FNL'),
  ('11r/Ph2','SPD'),
  ('11r/Ph3','BLF'),
  ('11r/Sc1','BDA,HTJ'),
  ('11r/Sc2','MKB,RNN'),
  ('7h/Sc1','HRS,RNN'),
  ('7h/Sc2','BLF,ELV'),
  ('7h/Sc3','BRB,WKN'),
  ('7h/Sc4','BRB,FNL'),
  ('7h/Sc5','BDA,HTJ'),
  ('7h/Sc6','JKS,SRE'),
  ('7r/Sc1','HTJ,WKN'),
  ('7r/Sc2','FNL,JKS'),
  ('7r/Sc3','BDA,RNN'),
  ('7r/Sc4','ELV,HRS'),
  ('7r/Sc5','BRB,SRE'),
  ('8h/Sc1','BLF,JKS'),
  ('8h/Sc2','BDA,JKS'),
  ('8h/Sc3','ELV,FNL'),
  ('8h/Sc4','BRB,MKB,WKN'),
  ('8h/Sc5','MKB,SPD'),
  ('8r/Sc1','BDA,ELV'),
  ('8r/Sc2','RNN,WKN'),
  ('8r/Sc3','BRB'),
  ('8r/Sc4','BDA,ELV'),
  ('8r/Sc5','FNL,SPD'),
  ('9h/Sc1','MKB'),
  ('9h/Sc2','RNN,SPD'),
  ('9h/Sc3','HRS'),
  ('9h/Sc4','BLF,ELV'),
  ('9h/Sc5','BDA,WKN'),
  ('9r/Sc1','WKN'),
  ('9r/Sc2','BLF,JKS'),
  ('9r/Sc3','MKB,RNN'),
  ('9r/Sc4','ELV,SPD'),
  ('9r/Sc5','BDA,FNL')
)
select coalesce(jsonb_agg(jsonb_build_object('class',coalesce(p.cls,l.cls),'pinned',p.codes,'live',l.codes)),'[]'::jsonb) as MISMATCHES
from pinned p full outer join live l on l.cls=p.cls
where p.cls is null or l.cls is null or p.codes is distinct from l.codes;