/* shared/brand/brand.js — GENERATED by brand.py on every build. Do not edit.
   The one brand lockup (Mide's ruling, 13 Sep 2026) for pages that draw their
   header in JavaScript. Same bytes as brand.brand_lockup() in the build. */
(function () {
  'use strict';
  var MARK = "<svg class=\"mrb-brand__mark\" data-mrb-mark viewBox=\"0 0 22 22\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M3.5 3.5 L11 11 L3.5 18.5\" stroke=\"#E4572E\" stroke-opacity=\"0.34\" stroke-width=\"3.4\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path><path d=\"M12 3.5 L19.5 11 L12 18.5\" stroke=\"#E4572E\" stroke-width=\"3.4\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path></svg>";
  var NAME = "MrBadmus";
  function lockup(href, onDark) {
    return '<a class="mrb-brand' + (onDark ? ' mrb-brand--on-dark' : '') + '" href="' +
      (href || '/index.html') + '" aria-label="' + NAME + ' home">' + MARK +
      '<span class="mrb-brand__word">' + NAME + '</span></a>';
  }
  window.MrBadmusBrand = { NAME: NAME, MARK: MARK, lockup: lockup };
})();
